### ISSUE TITLE
Bitwise Operations over 32 bits

### ISSUE THREAD

**Issue by RussGlover** [josdejong/mathjs#1005]
Are bitwise operations limited to 32 bits? Left shift wraps around to 0  at 32. I.E 1 << 32 = 1.

I tried using big numbers but that did not seem to resolve my issue

**Comment by RussGlover** [comment]
I can replace the left shift with 1 * 2^32 but I also need a bitwise OR operator.

**Comment by joelhoover** [comment]
It seems to work just fine if you use BigNumbers (live example [here](https://jsfiddle.net/joelahoover/xqsu3q5v/)):

```javascript
3 & 5
    1
3*2^70 & 5*2^70
    0
bignumber(3*2^70) & bignumber(5*2^70)
    1.180591620717411393024e+21
(bignumber(3*2^70) & bignumber(5*2^70))>>70
    1

3 | 5
    7
3*2^70 | 5*2^70
    0
bignumber(3*2^70) | bignumber(5*2^70)
    8.264141345021879606976e+21
(bignumber(3*2^70) | bignumber(5*2^70))>>70
    7
```

**Comment by RussGlover** [comment]
Okay thanks Joel, I tried again with big numbers and was able to get it to work. I guess I was setting the math config improperly somehow.

Thanks again.

**Comment by FSMaxB** [comment]
The 32 bit limit of bitwise operations seem to be [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators](inherent to JavaScript).

Fun fact: This is even used for doing integer type annotations in [asm.js](http://asmjs.org/spec/latest/#parameter-type-annotations)
