### ISSUE TITLE
Using with ES6 import/export

### ISSUE THREAD

**Issue by rbiggs** [josdejong/mathjs#1007]
Nice library. I'd love to use this with normal ES6 imports for projects. I use Rollup for that. As it stands Mathjs doesn't work with Rollup for imports. I use the `commonjs` plugins for Rollup when I need a library that uses commonjs module format without problem. However, in the case of Mathjs I've been unable to import it into an ES6 Rollup project. I can indeed import the main part of Mathjs, but any internal dependencies that are called with `require` fail, leaving the library inoperable. It would be great if there was a version of Mathjs that was written in modern ES6 format with proper export/import. This is the future of modules. There are many modules that are offering an ES6 version these days.

**Comment by josdejong** [comment]
Yes we definitely have to set up a build script to convert ES6/7/8 to ES5, thanks for your suggestion. 

I will mark this issue duplicate in favor of #914 to keep the discussion focused. Help would be welcome :)
