### ISSUE TITLE
npm install mathjs deletes other npm installed packages

### ISSUE THREAD

**Issue by adityamertia** [josdejong/mathjs#1009]
Hi,
This is consistently seen everytime i do "npm install mathjs" that it deletes for e.g. 60 packages that are installed in npm. Why should mathjs deletes other packages?

[ec2-user@demo demo]$ npm install mathjs
npm WARN myproject@1.0.0 No description
npm WARN myproject@1.0.0 No repository field.

+ mathjs@3.19.0
removed 60 packages and updated 1 package in 2.022s

**Comment by HarrySarson** [comment]
This is about npm deleting packages. The mathjs libary has nothing to do with this issue.

Maybe https://github.com/npm/npm/issues/17379 might help you :)
