### ISSUE TITLE
question: math.lup vs lu_factorize, permutation vector different?

### ISSUE THREAD

**Issue by lab4quant** [josdejong/mathjs#1010]
Hello, I'm trying to use math.js (latest versoin from cdn) to perform matrix decomposition.

```js
let M1 = [ [1.0, 0.9, 0.7], [0.9, 1.0, 0.4], [0.7, 0.4, 1.0]]
math.lup(M1)
```

which produces this result:
```
L: [
      [1, 0, 0],
      [0.7, 1, 0],
      [0.9, -0.8260869565217389, 1]
]

U: [
      [1, 0.9, 0.7],
      [0, -0.22999999999999998, 0.51],
      [0, 0, 0.19130434782608685]
]

P: [0, 2, 1]
```

When I used boost `lu_factorize` function for the same matrix, it produces this result:

```
M: [
      [1, 0.9, 0.7],
      [0.7, -0.22999999999999998, 0.51],
      [0.9, -0.8260869565217389, 0.19130434782608685]
]

PM: [0, 2, 2]
```

the M from `lu_factorize` is 'combined' L & U, but the `permutation vector` from mathjs is different from boost.

Please help me to understand the difference, I'm trying to calculate determinant from the lup function result

Thanks!

**Comment by ericman314** [comment]
I checked two online LU decomposition calculators [here](https://www.wolframalpha.com/input/?i=lu+decomposition+of+%5B+%5B1.0,+0.9,+0.7%5D,+%5B0.9,+1.0,+0.4%5D,+%5B0.7,+0.4,+1.0%5D%5D) and [here](http://comnuan.com/cmnn0100d/), and both return the same result as math.js. It's possible that boost's permutation matrix has a different meaning, which results in the same L and U, but different P, but as I could not find any documentation for boost's `lu_factorize` it's impossible to say. In any rate, I don't even think a permutation vector of `[0, 2, 2]` makes sense. It would mean the same row appears in two places in the permuted matrix.

**Comment by lab4quant** [comment]
@ericman314 , thank you for your update
Let me investigate further into lu_factorize, the parameter is called PM, which should be permutation matrix not vector

**Comment by lab4quant** [comment]
I'm still confused with `lu_factorize` `pm` output, with `math.lup` output: `L`, `U`, `P`, how do I calculate determinant? I know there's `math.det` function for that. 
Thanks!

**Comment by ericman314** [comment]
The determinant is the product of the diagonal entries in `U`, but that product changes sign every time a row swap is done during the decomposition. The number of row swaps can be determined from `P`. In your example, it takes one swap to go from [0,1,2] to [0,2,1], so the determinant is the negative product of the diagonals, or 0.044. There is discussion (see #908) on changing `math.det` to use the LU decomposition, which would be faster than the current implementation.

**Comment by lab4quant** [comment]
@ericman314 thanks a lot!
