### ISSUE TITLE
A strange question

### ISSUE THREAD

**Issue by luwzchn** [josdejong/mathjs#1017]
why i use： math.eval('69.57*1500');  it's return 104354.99999999999 ？ the right result should be 104355。

**Comment by firepick1** [comment]
I'm not sure there is much difference there. What trouble does this cause you?

**Comment by luwzchn** [comment]
@firepick1 I mean ：Why can't we remove the precision problem of JS when i using multiplication? 
when i use ： math.eval('69.57*1500');   i need  the  results is : 104355 not  104354.99999999999
for example,  I need  19.9*100=1990  not 19.9 * 100 = 1989.9999999999998

**Comment by josdejong** [comment]
@luwzchn these are numerical round-off errors. See: http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

this is the most asked question ;)
