### ISSUE TITLE
simplifyCore fails when called directly by client

### ISSUE THREAD

**Issue by firepick1** [josdejong/mathjs#1018]
Error message: ParenthesisNode is not defined

To reproduce: math.simplify.simplifyCore(math.parse("((x)*(y))")

**Comment by firepick1** [comment]
Fixed in https://github.com/josdejong/mathjs/commit/c4b555c36fd58e88930690a9c3cff0e5121362f1

Added new unit test. All tests pass in simplify2 branch.

**Comment by josdejong** [comment]
Thanks for the fix Karl! I've released v3.20.1 containing this fix.
