### ISSUE TITLE
Change `ConstantNode` to just hold a value instead of a stringified value and its type

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#1023]
Currently, the `ConstantNode` type holds a stringified value and its type, like 
`new ConstantNode('2', 'number')`. When evaluating the ConstantNode, it is parsed into a number, BigNumber, or Fraction. 

I would like to change this such that ConstantNode simply holds a value, like `new ConstantNode(2)` and `new ConstantNode(math.bignumber(2))`. That's simply easier to understand and work with. 

It will also make `simplify` and `derivative` work more consistently with bignumbers, similar to the rest of the library. Right now BigNumber and Fraction are still a bit second class citizen.

I've implemented this change to see how it works out, see:

Branch: https://github.com/josdejong/mathjs/tree/v4_constant_node
Commit: https://github.com/josdejong/mathjs/commit/924299c42b4d42ce09c35795cc5c8a8d1b287585

@firepick1 I would love to hear how you think about such a change.

**Comment by FSMaxB** [comment]
Actually wouldn't it make sense to print fractions as actual fractions in the LaTeX-Output? On the v4_constant_node branch it curently looks like you treat numbers, bignumbers and fractions all the same.

**Comment by josdejong** [comment]
Yes we could actually format fractions nicely. There was no special handling for Fractions when stringifying or using toTex before, but we can certainly add that. 

Would you be interested to add this to the ConstantNode?

**Comment by FSMaxB** [comment]
I can do that. Should I make a pull request to the `v4_constant_node` branch or wait until it is in `develop`?

**Comment by josdejong** [comment]
Thanks! A PR to `v4_constant_node` would be great.

**Comment by FSMaxB** [comment]
I just noticed that fraction.js already has builtin LaTeX support.

**Comment by FSMaxB** [comment]
There is a problem because `getType` can never return `BigNumber` or `Fraction`. See https://github.com/josdejong/mathjs/blob/087f53d8544dd3631d75b6ce836446153fc88de1/lib/utils/types.js#L29-L39

This means that the `Fraction` and `BigNumber` cases are absolutely pointless here:
https://github.com/josdejong/mathjs/blob/087f53d8544dd3631d75b6ce836446153fc88de1/lib/expression/node/ConstantNode.js#L135-L143

I tried to change `lib/utils/types.js` so that it returns `Fraction` and `BigNumber` properly but I don't really know how I should do that.

This is what I naively tried to do:
```js
    if (Object.getPrototypeOf(x)) {
      var prototype = Object.getPrototypeOf(x);
      if (prototype.hasOwnProperty('type')) {
        return prototype.type;
      }
    }
```
But it breaks other stuff because `DenseMatrix` then doesn't have the type `Matrix` anymore. I guess this should be fixed by using `instanceof` but I don't understand enough about `typed-function` to know where to get the classes that the object has to be an instance of.

Some help would be appreciated.

**Comment by josdejong** [comment]
Ah, sorry @FSMaxB . That's indeed a bug. There are two typeof functions in the code base, that's confusing:

- A generic one understanding just plain JS types:
  https://github.com/josdejong/mathjs/blob/v4_constant_node/lib/utils/types.js
- A more advanced one which also recognizes mathjs types like Matrix, BigNumber, Fraction:
  https://github.com/josdejong/mathjs/blob/v4_constant_node/lib/function/utils/typeof.js

In this case we should use the latter, I've fixed it in https://github.com/josdejong/mathjs/commit/f112348eec9c786f9cb1f169c170936c3dfb8f4d.

This low level `type` function has been used in the past in other util functions, but that isn't the case anymore. I've moved it into `math.typeof` so we cannot have this issue again, see https://github.com/josdejong/mathjs/commit/02d7d592e4198f43e5016c2b4224a231947480bc.

**Comment by FSMaxB** [comment]
Note that the code that escapes strings for latex needs to be ported to the new ConstantNode as well, once it is merged.

**Comment by josdejong** [comment]
Good point. For reference, see #1022

**Comment by josdejong** [comment]
I would love to have some input from Karl about this issue, but I have a strong feeling that this change in `ConstantNode` is a good improvement. In order to be able to move forward and prevent merge conflicts with other changes for v4 I will now merge `v4_constant_node` into `v4`.

**Comment by josdejong** [comment]
> Note that the code that escapes strings for latex needs to be ported to the new ConstantNode as well, once it is merged.

@FSMaxB I've just merged your fix for escaping latex string from the `develop` branch into `v4`.
