### ISSUE TITLE
Memory leak in mathjs.eval()

### ISSUE THREAD

**Issue by gizmodus** [josdejong/mathjs#1030]
Hi,

First thanks a lot for this great project, we are using mathjs in a large project!
Yesterday, I made some memory investigations with Chrome Developer Tool and I found a possible problem with mathjs.eval(). If you call this function a couple of times, memory usage in Chrome's heap snapshot increases significantly.

I created a little project on stackblitz to illustrate the problem (relevant code is in hello.component.ts):
Editor: https://stackblitz.com/edit/angular-nn4wmp
Preview: https://angular-nn4wmp.stackblitz.io

The application repeatedly runs the following code:
`const a = mathJs.eval('2 > 1');`

If you take some heap snapshots over time, some strings from mathjs seem to accumulate in the memory (see screenshot below with comparison of two subsequent snapshots). For our project this is quite critical as memory is limited on the tablet device and our application gets slower and slower over time.

Could you take a look at this?

Thanks in advance!

![stack01](https://user-images.githubusercontent.com/11334553/35500981-b521fd46-04d8-11e8-90b9-7bf5515fafe0.JPG)
![stack02](https://user-images.githubusercontent.com/11334553/35500988-bc888bf4-04d8-11e8-8b17-4902b86ec529.JPG)

**Comment by gizmodus** [comment]
Great, thank you very much!
Is v4 already stable enough to be used in production?

**Comment by josdejong** [comment]
> Is v4 already stable enough to be used in production?

I wouldn't advise you to use it in production. v4 not yet released, and we're still working on a few breaking changes. The expression compiler itself is done and well tested, but hasn't been used in real world applications yet. I hope that we can release v4 within a couple of weeks - but it's ready when it's ready.

**Comment by gizmodus** [comment]
Okay, thank you!

**Comment by ceremcem** [comment]
Is this a `wontfix` till v4?

**Comment by josdejong** [comment]
I would love to fix it but it may require a lot of effort, maybe so much that it isn't worth it given that it will be fixed in v4. I've briefly checked whether I could find a fix, but that wasn't the case. Any help would be welcome.

**Comment by josdejong** [comment]
Mathjs `v4.0.0` has been released which doesn't suffer from this memory leak. 

Let's keep this issue open for a while without high prio: it will probably take a lot of time to fix. If people can seamlessly upgrade to v4, and v3 is retired soon, it may not be worth putting in much effort. Let's see.

**Comment by harrysarson** [comment]
Can we close this now? I doubt any fixes are gonna land on v3 at this point?

**Comment by gizmodus** [comment]
We switched to v4 and are happy with it!

**Comment by josdejong** [comment]
Agree let's close it, it will take a lot of effort to get this fixed in v3 whilst we have it solved in v4.

Thanks for the feedback @gizmodus, glad to hear!
