### ISSUE TITLE
Unit: Adjustable range for usable prefixes on output (toString, format)

### ISSUE THREAD

**Issue by faeron** [josdejong/mathjs#1033]
I was wondering if it was possible to limit/define the range of prefixes when formatting a unit.
Although the output is totally correct from mathematical point of view, it looks somehow unusual for a "normal" user in some cases (e.g. a calculated distance from a map)

`
math.unit(10000000, 'm').toString()
`
it shows `10 Mm` but `10000 km` would look more natural in that case.

Basically what I ask is, can I tell mathjs: use only prefixes in a defined range, and used the highest/lowest in case the value exceeds in either direction.

**Comment by josdejong** [comment]
There is currently no way to customize the way prefixes are selected. Of course you can always overwrite the built-in implementation, which you can find here: [Unit.prototype._bestPrefix](https://github.com/josdejong/mathjs/blob/master/lib/type/unit/Unit.js#L1163-L1210), though these internals may change in future versions of mathjs which would break your adjustment.

Related discussion: https://github.com/josdejong/mathjs/issues/898

**Comment by faeron** [comment]
Thank you. I will look into the function you mentioned.

**Comment by josdejong** [comment]
:+1:
