### ISSUE TITLE
Eval error with function and implicit multiplication

### ISSUE THREAD

**Issue by ericman314** [josdejong/mathjs#1035]
I came across a bug in the last example in the docs for implicit multiplication:

```js
math.eval('sqrt(4)(1+2)');   //  TypeError: fn is not a function
```

The output of `console.log(util.inspect(math.parse('sqrt(4)(1+2)'), {depth:100}));`

```js
Node {
  fn: 
   Node {
     fn: Node { name: 'sqrt' },
     args: [ Node { value: '4', valueType: 'number' } ] },
  args: 
   [ Node {
       implicit: false,
       op: '+',
       fn: 'add',
       args: 
        [ Node { value: '1', valueType: 'number' },
          Node { value: '2', valueType: 'number' } ] } ],
  comment: '' }
```

The error occurs in the current `develop` branch but *not* the `master` branch.

**Comment by josdejong** [comment]
That's a good point. this behavior has been there for a long time though (I tried for example v3.10.0). Basically the output of `sqrt(4)` is expected to be a function, which is then invoked with argument `(1+2)`. We can discuss whether this is desirable behavior or whether we want to change it in v4. 

Here some example cases that we need to consider then I think:

```js
//  function call or implicit multiplication?
(2)(3)
fn(2)
(fn)(2)
fn(2)(3)
obj.fn(2)
(obj.fn)(2) 
obj['fn'](2)

// get matrix subset or implicit multiplication?
fn(2)[3]
```

**Comment by josdejong** [comment]
Thinking about it, it makes sense to make this change. If you want to invoke the output of a function or access a matrix subset, you can always first store the result in a variable, and then use that variable as function or matrix.

**Comment by josdejong** [comment]
@ericman314 I've implemented your idea in #1037. 

I think usage as implicit multiplication is more common in maths than immediately invoking a returned function, so this will be an improvement.

What do you think?

**Comment by ericman314** [comment]
You're probably right.

**Comment by josdejong** [comment]
I think it's the best choice, will merge #1037 now.
