### ISSUE TITLE
Add units mcd and t (tonne)

### ISSUE THREAD

**Issue by naeco33** [josdejong/mathjs#1043]
Hi,

I discovers that 
math.unit("3mcd");
do not work, Normally, it exist, but i have the error  "SyntaxError: Unit \"mcd\" not found.".

And
math.string(math.unit("3tonne")); : "3 tonne"
but 
math.string(math.unit("3t")); :  "SyntaxError: Unit \"mcd\" not found.".

Best regards

**Comment by josdejong** [comment]
Thanks for your suggestions!

**Comment by harrysarson** [comment]
The unit `mcd` would class with `mili candela` possibly?

**Comment by naeco33** [comment]
yes exactly :)

**Comment by harrysarson** [comment]
So a `mcd` is meant to be a milli candela?

**Comment by josdejong** [comment]
Yes, see also https://www.wikiwand.com/en/Candela

**Comment by naeco33** [comment]
When i bought some LED for my electronics project, the value is always write as :
Diamètre = 3mm
Tension / Voltage = 1.8 - 3.4V
Consommation = 20mA - 30mA
Color = 460-465nm
4500-5500mcd
30 degree
exemple : http://www.ebay.fr/itm/LED-Verte-3mm-lot-de-100-500mcd/350277858979?hash=item518e2ff6a3:g:k2wAAMXQvTlRh3yL

**Comment by naeco33** [comment]
Hi again,

I continue my work with your useful librairie, and there is still another
unit not recognize : the Decibel (dB).

Have a beautiful Sunday,
Best regards,
Willy

2018-02-21 17:58 GMT+01:00 Jos de Jong - notifications@github.com <
github.naeco.2d084a3543.notifications#reply@reply.github.com>:

**Comment by josdejong** [comment]
Thanks for your suggestion @naeco33, I've opened a separate issue for it: #1209

**Comment by josdejong** [comment]
Addressed via #1518
