### ISSUE TITLE
Unexpected result with "in" operator during unit conversion

### ISSUE THREAD

**Issue by bornova** [josdejong/mathjs#1044]
Hi,
If I don't include the unit to convert to after the "in" operator, I get some unexpected results:

`math.eval("2 liter in")` returns `61.023744094732294 in^4`
or
`math.eval("2 km in")` returns `39370.07874015748 in^2`

This maybe a trivial issue as you wouldn't do a conversion like that.  However, I have an application where I evaluate and print the answer as I type the expression and it will display these unexpected results briefly while trying to get to "2 liter in gallon" for example. .  This doesn't happen when using the "to" operator.  `math.eval("2 liter to")` doesn't return anything as expected.

Thank you for this great library!

**Comment by ericman314** [comment]
This is because `in` is also an alias for inch, but its use as an operator to convert units goes back to the early days of the library. To avoid ambiguities, I personally always use `to` in my expressions.

**Comment by harrysarson** [comment]
@bornova if you have any more questions feel free to re-open but I am going to assume Eric answered your question here and close this issue.
