### ISSUE TITLE
Cloudflare production 4.0 links are broken

### ISSUE THREAD

**Issue by enil42** [josdejong/mathjs#1047]
On: http://mathjs.org/download.html

http://cdnjs.cloudflare.com/ajax/libs/mathjs/4.0.0/math.min.js

is returning a 404.

**Comment by josdejong** [comment]
Thanks for reporting! Looks like it works again, not sure what it was.

I've now replaced the cdnjs links with unpkg - right after a new version is deployed, it always takes a while before the new version is available on cdnjs whilst unpkg is directly available.
