### ISSUE TITLE
math.round() returns wrong value

### ISSUE THREAD

**Issue by dave11mj** [josdejong/mathjs#1052]
### Given
`math.round(1.649, 1)`

### Expected
`1.7`

### Actual
`1.6`

**Comment by josdejong** [comment]
`math.round` rounds to the nearest integer so the `1.6` output is actually expected output. `math.round(1.651, 1)` would round to `1.7`.

**Comment by dave11mj** [comment]
Cool ! :D .. we actually had a good debate on the different ways of rounding, and I can see why that is the expected result. ^^

**Comment by josdejong** [comment]
:+1: 

you also have functions like `floor`, `ceil`, `fix` if you want different rounding, only these functions do not (yet) support passing a number of digits like `round` (see #894)

**Comment by josdejong** [comment]
Sorry I mean #1021
