### ISSUE TITLE
Rename 'eye'

### ISSUE THREAD

**Issue by AlexMouton** [josdejong/mathjs#1054]
Just a vote here to rename this to 'identity'.
Two reasons, Identity is ubiquitous, and an 'eye matrix' can be confused for a view/projection/look-at matrix in graphics environments.

**Comment by josdejong** [comment]
Thanks for your suggestion. I think `eye` is quite common too and used in various math applications. I'm open to discussing renaming the function to `identity` which is indeed more clear.

At least it's very easy to create an alias `identity` for your self and use that instead of `eye` if you want :)

**Comment by josdejong** [comment]
Thanks! Scilab uses `eye` too, and Wolfram Alpha uses `IdentityMatrix`.

I prefer having just one of the two, not both. If people really want they can always make an alias themselves.

**Comment by josdejong** [comment]
I would like to decide upon this now. I prefer `identity` since it better reflects what the function is about. This means a breaking change though, we'll start with implementing `identity` and marking `eye` deprecated, have it output a console warning when used.

**Comment by josdejong** [comment]
I've renamed `eye` to `identity`. Using `eye` throws an error explaining to use `identity` now. Will be released in v5.

**Comment by avielkis** [comment]
typescript @types/mathjs still only supports `eye` and throws error.

**Comment by josdejong** [comment]
@avielkis can you report this with the maintainer of the type definitions?
