### ISSUE TITLE
Ways to get around having to encode expressions in the URL in REST API?

### ISSUE THREAD

**Issue by jaaneh** [josdejong/mathjs#1056]
Hey there,

Using the API, I noticed that it doesn't like addition (+) and returns an API Error. 

Example: http://api.mathjs.org/v4/?expr=1+1

I know it has to be url encoded, and %2B works fine, but are there any way to get around this? I know / works instead of %2F 

Thanks!

**Comment by josdejong** [comment]
Well, it's simply that the url has to be encoded, you can't get around it. The only way not to have to use encoding is using the POST request instead of GET: in that case you can put your expressions in the request body in JSON format.

**Comment by jaaneh** [comment]
Exactly what I was looking for. Cheers!
