### ISSUE TITLE
Print function could receive array

### ISSUE THREAD

**Issue by jean-emmanuel** [josdejong/mathjs#1057]
It seems that `print` could also accept Array as its value argument, couldn't it ?

**Comment by josdejong** [comment]
I'm not sure what you mean, can you elaborate? Which function print do you mean? What not simply try out whether it works?

**Comment by jean-emmanuel** [comment]
Sorry, I mean this function : https://github.com/josdejong/mathjs/blob/d7d25e83c835c3f060bff2e26e293710b61fc32b/lib/function/string/print.js#L56
It only accepts plain objects and throws when `values` is an array, although it seems this code could just "work" with arrays too.

```
TypeError: Unexpected type of argument in function print (expected: Object, actual: Array, index: 1)
    at createError (/node_modules/typed-function/typed-function.js:555:19)
    at generic (/node_modules/typed-function/typed-function.js:1077:15)
    at Object.print (/node_modules/typed-function/typed-function.js:1092:24)
```

**Comment by jean-emmanuel** [comment]
#1058

**Comment by josdejong** [comment]
Ah, I get it. I think it's will be a nice extension of `print`, thank for your suggestion.

**Comment by thecodeboss** [comment]
I see #1058 was merged, this issue can be closed now @josdejong

**Comment by josdejong** [comment]
Good point, thanks!
