### ISSUE TITLE
Unhelpful error message for non-intersecting lines

### ISSUE THREAD

**Issue by Yatoom** [josdejong/mathjs#1059]
I used the `math.intersect()` method to determine whether two line segments intersect. However, I found two line segments that are not intersecting, and I still got an answer.

```javascript
import * as math from "mathjs";

console.log(math.intersect(
    [0, -200], [0, 200], [0, -600], [300, -600]
));
```
This is the output of the script above:
```javascript
[0, -600]
```

Wouldn't it be nice if it would return `false` if the line segments do not intersect?

**Comment by ericman314** [comment]
The lines in your example do in fact intersect.

However, the function does return a useless error when two non-intersecting lines are provided. The function should instead return a more helpful error, so I've labeled this as a bug.

**Comment by Yatoom** [comment]
I thought the lines would look like this:
![](https://i.imgur.com/eCsoopx.png)

**Comment by FSMaxB** [comment]
That are not lines but line segments. `intersect` intersects the entire lines.

**Comment by Yatoom** [comment]
Ah that makes sense. Thanks!

**Comment by FSMaxB** [comment]
Essentially to get the intersection of two line segments, you have to check if the intersection point is on the two segments, therefore being inside of the two rectangles that are defined by the endpoints of the segments.

The x coordinate of the intersection needs to be between the x coordinates of line segment endpoints respectively. Same for the y coordinates.

**Comment by ericman314** [comment]
Aha, I understand now. If you think a corresponding `intersectSegment` function or even an option such as `intersect(..., { segment: true } )` might be useful we can open another issue.

**Comment by harrysarson** [comment]
So currently `math.intersect` returns `null` when the lines do not intersect.

What would the desired behaviour be, throwing an Error?

**Comment by josdejong** [comment]
I think it's a very common case to see whether there is an intersection or not, so the behavior of returning is what you want, otherwise you have to catch exceptions to see when there is no intersection.

**Comment by harrysarson** [comment]
In that case there is no issue here I believe?

**Comment by josdejong** [comment]
Ah, old topic. I think you're right @harrysarson. Let's close this issue.
