### ISSUE TITLE
Support for unit 1/x

### ISSUE THREAD

**Issue by XeniaSiskaki** [josdejong/mathjs#1061]
Currently a unit like `1/K` isn't acceptable and has to be manually converted to `K^-1` before creating the unit.

This currently works in the [Math notepad](http://mathnotepad.com/) and can partially work in mathjs with:

`var x = math.eval('1/K')`
`x.equalBase(math.unit('K^-1')) // => true`

Would it be possible to add support for such units?

**Comment by josdejong** [comment]
Thanks for your input Xenia. It's not yet clear to me what you mean exactly, you can already use `1/K` both in calculations as well as when defining a new unit. What are you missing exactly?

**Comment by XeniaSiskaki** [comment]
Doing `math.unit('1/K')` throws an `Uncaught SyntaxError: Unexpected "/" in "1/K" at index 1`

**Comment by ericman314** [comment]
The `Unit` constructor invoked using `math.unit` uses a very simple parser that can only understand certain expressions. Evidently, "number divided by unit", such as `1/K`, is not one of them. We could probably add support for that if necessary. (Curiously, `1 K/K^2` _is_ supported.)

Although using `math.unit` directly is faster, you can achieve the same results using `math.eval('1/K')`, which gives you all the functionality of the full expression parser, and which will return the same thing `math.unit` would. Is it acceptable for you to use `math.eval` instead?

**Comment by XeniaSiskaki** [comment]
Thanks for your quick input! We will go with `math.eval` until this is fixed (if ever).

**Comment by josdejong** [comment]
@ericman314 we should indeed be careful not to built an entire expression parser in the unit parser. 

The current unit parser already has support for divisions like `5 m/s`, it only doesn't handle a case like `1 / s` correctly where the division is right after the number, so I think this is simply a bug that we should solve.

**Comment by josdejong** [comment]
this should be fixed via https://github.com/josdejong/mathjs/commit/b00e0b7460e1d7165dfe83b6de7d23a04ca2bd42 (currently in the develop branch)

**Comment by ericman314** [comment]
Agreed. Thanks for fixing that.

**Comment by XeniaSiskaki** [comment]
Thanks!
