### ISSUE TITLE
Typed-functions breaks mathjs for iOS 9.3

### ISSUE THREAD

**Issue by jean-emmanuel** [josdejong/mathjs#1062]
https://github.com/josdejong/typed-function/blob/master/typed-function.js#L1096
This throws `TypeError: Attempting to change value of a readonly property.` thus preventing mathjs to load.
Tested with iOS 9.3 (can be reproduced with desktop safari 9.1).

**Comment by josdejong** [comment]
Thanks for reporting this issue! 

It should be easy to make a fallback for older browsers and browser that don't allow replacing a function name, will look into it within a few days.

**Comment by blackdynamo** [comment]
I am also seeing this on older android versions. Threw me for a loop cause didn't have a clue where the error was coming and it's just including the mathjs@4.0.0 release.

**Comment by josdejong** [comment]
This should be fixed now in v4.0.1

**Comment by jean-emmanuel** [comment]
Thanks a lot !
