### ISSUE TITLE
eval() on a node returns a 'number' regardless of config options

### ISSUE THREAD

**Issue by arnog** [josdejong/mathjs#1064]
When invoking `eval()` on a node, the result is reduced to a number, even when the config has been set to use `'BigNumber'` or `'Fraction'`.

In the code below, I would expect all 3 calls to return a BigNumber object. The workaround is to convert the node to a string, then evaluate the string.

```javascript
mathjs.config({
   number: 'BigNumber',
   precision: 64
});
const expr = new mathjs.expression.node.OperatorNode('/', 'divide',
   [new mathjs.expression.node.ConstantNode(1),
   new mathjs.expression.node.ConstantNode(3)]);
console.log(expr.eval());         // 0.3333333333333333
console.log(mathjs.eval(expr.toString())); // o {constructor: ƒ, s: 1, e: -1, d: Array(10)}
console.log(mathjs.eval('1 / 3')); // o {constructor: ƒ, s: 1, e: -1, d: Array(10)}
```

**Comment by josdejong** [comment]
The `number` configuration is only used when _creating_ a new number somewhere, like when parsing/evaluating an expression from a string such as `"1/3"`. The configuration is _not_ applied when you create ConstantNodes with some value yourself, or when calling a function with numeric input like `math.add(2, 3)`.

**Comment by arnog** [comment]
Ah, I see. Re-reading the docs, it indeed says that. So a fix would be to pass a BigNumber to the node constructor:
```javascript
const expr = new mathjs.expression.node.OperatorNode('/', 'divide',
   [new mathjs.expression.node.ConstantNode(mathjs.bignumber(1)),
   new mathjs.expression.node.ConstantNode(mathjs.bignumber(3))]);
console.log(expr.eval());         // o {constructor: ƒ, s: 1, e: -1, d: Array(10)}
```

Thank for the quick response!

**Comment by josdejong** [comment]
Yes that's correct @arnog 

I've tried to improve the docs on the `number` configuration, see this commit: https://github.com/josdejong/mathjs/commit/c5fb3bcbc5e6f020c98936eba19abb9483cf54d4. I hope this will help others with the same questions as you.
