### ISSUE TITLE
compare() and compareNatural() behave unexpectedly.

### ISSUE THREAD

**Issue by arnog** [josdejong/mathjs#1065]
The doc for `compareNatural()` indicates: 

> For numeric values, the function works the same as math.compare.

However, the following results are returned:

```javascript
 console.log(mathjs.compareNatural("3.141592652582646125206037179644022371557877983160126149695135327918621058849781011234089260957039555", 3.1415926525826463));
// Outputs 1
 console.log(mathjs.compare("3.141592652582646125206037179644022371557877983160126149695135327918621058849781011234089260957039555", 3.1415926525826463));
// Outputs 0
```

I would have expected the output from both functions to be identical (namely, 0).

**Comment by josdejong** [comment]
You're comparing a number and a string, and string inputs are handled differently by `compare` and `compareNatural` differ: `compare` changes string input to a number and compares the values then, where as `compareNatural` compares strings lexically.

**Comment by harrysarson** [comment]
> For numeric values, the function works the same as math.compare.

Maybe @arnog is requesting a change to this bit of the docs to clarify that a string is not a "numeric" value, even if the string happens to contain a number.

**Comment by josdejong** [comment]
The docs where indeed wrong, sorry for the confusion. 

I've updated the docs, see https://github.com/josdejong/mathjs/commit/a389d340e95ec8fc7b53c9622a8d2c773791fc65 (will become available in the first next release)
