### ISSUE TITLE
Add extensions list to the website

### ISSUE THREAD

**Issue by husayt** [josdejong/mathjs#1069]
I noticed there are extensions being built for math.js. Would be great to list them in a separate section on the website.

* numbers.js
* numeric.js
* [Simple integral](https://github.com/joelhoover/mathjs-simple-integral)
* [math.diff.js](https://github.com/hausen/math.diff.js)

and even some nonstandard ones:

* https://github.com/shauns/postcss-math
* https://github.com/otm/svg.math.js

**Comment by josdejong** [comment]
@husayt thanks, good point. I've extended the "extensions" section on the downloads page, and added a new section "other math libraries"

http://mathjs.org/download.html

I don't think svg.math.js is using math.js so I didn't add this one.
