### ISSUE TITLE
array input for math.add

### ISSUE THREAD

**Issue by gdarai** [josdejong/mathjs#1070]
Hi, nice library,
Correct me if I am wrong...
I just saw that you don't support array of Matrices as input for the math.add function.
So I have to use:
```reduce(ARRAY, (sum,M)=>math.add(sum,M), math.zeros(size));```
instead of plain
```math.add(ARRAY)```
It would make things much more readable so take this as a suggestion for a possible enhancement and keep the great work, thanks.

**Comment by josdejong** [comment]
There is a `math.sum`, that may help?

**Comment by harrysarson** [comment]
I think `math.sum` is what @gdarai is looking for :smile: 

```js
> math.sum([1, 2, 3])
6
``

Feel free to reopen this if this solution is not what you are looking for.
