### ISSUE TITLE
Selecting ranges relative to unit

### ISSUE THREAD

**Issue by lgomez** [josdejong/mathjs#1075]
Hello all,

This may be simply my limited experience working with matrices but perhaps someone can point me in the right direction or provide an example that helps me understanding this.

I'd like to perform calculations on matrices using ranges relative to a unit. For example, given a matrix where I have dates (in this case days) on the Y axis and values on the X axis, I need to calculate  moving average for every date. Say I'm using a 30-day window to calculate it, I'd need to take the values for the 30 days/rows prior to a unit. I'm struggling to understand how to express that using this library.

So far I've been trying to approach it starting with:

```javascript
math.import({
  row: (M, i) => M.subset(math.index(i, math.range(0, M._size[1]))),
  column: (M, i) => M.subset(math.index(math.range(0, M._size[0]), i))
})
```
Which allows me to grab columns and rows from a matrix. I then grab the range of data that I need and perform the calculation but I have a feeling I'm overcomplicating things. My goal is to arrive at something like:
```javascript
math.import({
  ma: (M, days) => { /* moving average calculation happens here */ }
})
```
So I could do:
```javascript
math.ma(matrix, 30)
```
Or even better (though I don't know what the recommended way to extend Matrix is):
```javascript
matrix.ma(30)
```
Thank you very much,

Luis

**Comment by josdejong** [comment]
You can indeed implement such an `ma` function and import it in mathjs. The implementation of your `ma` function depends a bit on how you want to create this moving average: per row? I guess some plain and simple JavaScript with for loops and stuff will be easiest there. 

The notation with subset, index, range is indeed rather cumbersome though you have to write it only once. You could also look into using the expression parser there which has a much more concise notation for matrix operations (like `M[i, :]` to get row `i`).

**Comment by lgomez** [comment]
I see. Yes, I think deep down I was hoping to be able to use or implement something that came closer to range selection like one would do them in spreadsheets lol. I started hacking away last night on this. Will share if i get to anything useful.

By the way, is there a way to get metadata about a unit gotten from a matrix? For example, if I were to use `.get()` to grab a value from a matrix, is there a way to then get the coordinates for that unit? If I loop through the matrix I can keep track of that I know... But is there a way to get more info from `.get()` or is there an alternative to that?

Thanks!

**Comment by josdejong** [comment]
> I think deep down I was hoping to be able to use or implement something that came closer to range selection like one would do them in spreadsheets lol.

Well, there is: you can use the expression parser which makes life easier when working with matrices and range, like simply doing `M[i, :]` to get row `i`. See docs: http://mathjs.org/docs/expressions/syntax.html#matrices (mind you the expression parser is one-based)

If you get some value from a matrix, the value itself does not know anything about where it came from. If you need something like that, you could create a `get` utility function for yourself which grabs a value from a matrix and returns it wrapped in an object also containing the meta information you want:
```js
function getWithMeta(matrix, row, col) {
  return {
    value: matrix.get([row, col]),
    row,
    col
  }
}
```

**Comment by lgomez** [comment]
Understood. Thank you!
