### ISSUE TITLE
Doco error on matrix page (multiplication)

### ISSUE THREAD

**Issue by g1fa** [josdejong/mathjs#1078]
matrix markdown doco contains an error: 

// multiply an array with a matrix
var c = [[2, 0], [-1, 3]];                // Array
var d = math.matrix([[7, 1], [-2, 3]]);   // Matrix
math.multiply(c, d);                      // Matrix, [[14, 2], [-13, 8]]

should be (and mathjs calculates to):

// multiply an array with a matrix
var c = [[2, 0], [-1, 3]];                // Array
var d = math.matrix([[7, 1], [-2, 3]]);   // Matrix
math.multiply(c, d);                      // Matrix, [[14, 2], [-1, 8]]

**Comment by josdejong** [comment]
I'm not sure whether I understand your point, when I evaluate this code, it evaluates to `[[14, 2], [-13, 8]]`, the same as the comments say so it looks like the documentation is correct, right? I also calculated the result by hand and on wolframalpha, and the result looks correct.
