### ISSUE TITLE
can't use math.js in JDK's ScriptEngine

### ISSUE THREAD

**Issue by activequant** [josdejong/mathjs#108]
MessagE: 
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: missing name after . operator (<Unknown source>#2670) in <Unknown source> at line number 2670

I used version the full 0.15 version. 

To reproduce: 

import java.io.FileNotFoundException;
import java.io.FileReader;

import javax.script.Compilable;
import javax.script.CompiledScript;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

public class CompileTest {
    public static void main(String args[]) throws FileNotFoundException {
        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("javascript");

```
    engine.put("counter", 0);
    if (engine instanceof Compilable) {
        Compilable compEngine = (Compilable) engine;
        try {

            // can i build a classpath of javascript?
            //

            // let's go through all javascript files.
            engine.eval(new FileReader("src/main/js/library/math.js"));
        } catch (ScriptException e) {
            System.err.println(e);
        }
    } else {
        System.err.println("Engine can't compile code");
    }
}
```

}

**Comment by jobmission** [comment]
Hi,
When I used it on jdk11, it didn't work. Did you use it on a later version of JDK?

**Comment by josdejong** [comment]
I suppose the latest versions of mathjs contain some JavaScript ES5 features that may be not (fully) supported by JDK's ScriptEngine.
