### ISSUE TITLE
Why api.mathjs.org doesn't have HTTPS (TLS)?

### ISSUE THREAD

**Issue by vladimirmartsul** [josdejong/mathjs#1087]

**Comment by josdejong** [comment]
I'll have to buy an SSL certificate for that and configure the website and REST service correctly. Costs time and money, which I haven't spend on it so far.

As a workaround: the web application is a Heroku application, and Heroku provides applications with an SSL certificate by default, so you could use the url from heroku too:

https://mathjs.herokuapp.com

**Comment by josdejong** [comment]
It has bin a while but I finally took the time to set up SSL for both the website https://mathjs.org as well as the REST Service https://api.mathjs.org

**Comment by harrysarson** [comment]
Nice 💯

**Comment by ericman314** [comment]
http://mathjs.org isn't redirecting to https://mathjs.org for me.

**Comment by josdejong** [comment]
@ericman314 that's correct, I think I will look into that in a few days or so. I want to make sure first everything works fine and that I didn't over look anything, keep them side by side for now.
