### ISSUE TITLE
toHtml() for invalid or partial expression

### ISSUE THREAD

**Issue by vikash20186** [josdejong/mathjs#1089]
Hi All,

I was trying to use toHtml() and it works great given expression is valid and math.parser is able to parse it. But i am looking for toHtml kind of output for invalid expression also. Is there any relevant method available to generate html representation for an invalid or partial expression?

Thanks,
Vikash

**Comment by josdejong** [comment]
That would be nice indeed, though it's currently not possible, see #416. Thanks for your suggestion Vikash.

Let's continue any discussion in #416 to keep the topic focused.
