### ISSUE TITLE
Is there a way to do partial import ?

### ISSUE THREAD

**Issue by xerosanyam** [josdejong/mathjs#1091]
I am importing 'mathjs' in my app. Is there a way that I could import only few functions
for example: add, subtract, multiply, bignumber

Currently I have to include complete lib, which increases my bundlesize

**Comment by josdejong** [comment]
Yes, see 

Docs: http://mathjs.org/docs/custom_bundling.html
Example: http://mathjs.org/examples/advanced/custom_loading.js.html
