### ISSUE TITLE
Dividing two numbers unit issue

### ISSUE THREAD

**Issue by codewp** [josdejong/mathjs#1095]
Hi and thank you for the great library.

I found an issue in mathjs that below code can show it.
```javascript
var test = '400 aUnit/bUnit / 100 cUnit/dUnit'
math.eval(test).toString();
// Output will be.
"4 aUnit / (bUnit cUnit dUnit)"
// Correct output should be
"4 aUnit dUnit / bUnit cUnit"
```
Also, I should say that I already defined units like this.
```javascript
math.createUnit('aUnit');
```

Please let me know how can I solve this problem?

Thanks.

**Comment by josdejong** [comment]
With expressions with so much ambiguity it's a good idea to use parenthesis to prevent your expression being evaluated differently from what you may be expecting, i.e.

```js
var test = '(400 aUnit/bUnit) / (100 cUnit/dUnit)'
```

Here is some documentation on the exact behavior of implicit multiplication:
http://mathjs.org/docs/expressions/syntax.html#implicit-multiplication

**Comment by codewp** [comment]
@josdejong 

Thank you so much, worked.

Bests.
