### ISSUE TITLE
Try to keep dependencies up to date

### ISSUE THREAD

**Issue by cnsgithub** [josdejong/mathjs#1100]
Hi, i noticed that fraction and other dependencies have not been updated for quite a while

4.0.4 vs
https://github.com/infusion/Fraction.js/tree/v4.0.8

2.0.3 vs
https://github.com/infusion/Complex.js/tree/v2.0.10

I think updates on 3rd party dependencies should be done more frequently. Thanks

**Comment by josdejong** [comment]
Good point. Also the decimal.js dependency must be updated (marked as a major change).

It would help me a lot if you or anybody could put together a pull request updating the dependencies (and make sure all unit tests still pass).

**Comment by harrysarson** [comment]
Upgrading complex might be semver major, I'm not sure but the way some values (especially infinity) are handled has changed between 2.0.3 and 2.0.10

**Comment by josdejong** [comment]
> Upgrading complex might be semver major, I'm not sure but the way some values (especially infinity) are handled has changed between 2.0.3 and 2.0.10

Yes, I saw that too. Haven't looked into how it changed exactly and whether that's a bugfix or breaking change. @infusion maybe you can easily explain the changes?

**Comment by infusion** [comment]
Thanks for mentioning. I recently did some minor things like upgrading all my libs to ES6 and noticed that people failed making it work with babel, so I reverted the changes. Additionally, I integrated minor improvements like numerical stability things. Also the first things towards infinity changes were introduced, but I think it's not breaking but only additional features at the moment. When I reviewed and integrated @harrysarson PR, a new major release will be made. But for now I wanted to ship small changes and PRs early - so forgive me about the semver confusion.

**Comment by josdejong** [comment]
Thanks for your quick reply Robert. 

Some unit tests where breaking when using v2.0.10, boiled down to complex infinity now consistently being returned as `complex(Infinity, Infinity)` (instead of sometimes having a 0 or NaN value for either re or im). Makes sense to me to see this as a fix and not a breaking change. 

See commit: https://github.com/josdejong/mathjs/commit/0abdfbe5906ad59937414405c43fb1bd941a25a9

**Comment by DrSensor** [comment]
Using CI like [greenkeeper](https://greenkeeper.io) maybe can help sync update with 3rd party dependencies.

**Comment by josdejong** [comment]
Thanks for the suggestion @DrSensor , that's a great idea. 

Anyone interested in looking into integrating greenkeeper with mathjs?

**Comment by TheDancingCode** [comment]
Only the repository admin can enable greenkeeper.

**Comment by DrSensor** [comment]
Another one that I found interesting is https://dependabot.com. And yes, only the repository owner can enable it.

**Comment by josdejong** [comment]
I've now configured greenkeeper, let's see if this works nicely and if not we can look into for example https://dependabot.com.

**Comment by josdejong** [comment]
Apparently it works ;)

See https://github.com/josdejong/mathjs/pull/1153

**Comment by harrysarson** [comment]
Fixed by #1153 🎉
