### ISSUE TITLE
Using API Call with Notation: 'fixed' Error

### ISSUE THREAD

**Issue by lwirtz** [josdejong/mathjs#1102]
Small back story, I'm trying to round a value to an exact decimal without mathjs dropping the zero with the return value. I'm having a heck of a time with what seems like a simple task. The following screen shot depicts my main hangup. I'm not sure why 'fixed' isn't working and pulling an error. Can someone help me through this obstacle? Is there another function that will solve this problem for me? Again, I don't want mathjs to drop the zero if it rounds up (sometimes these calcs happen and sometimes they don't, but I need it to consistently return the solution to the specified decimal).
![2018-05-09_9-43-24](https://user-images.githubusercontent.com/35850855/39824923-c3e5507e-536d-11e8-8795-755bde8a3a84.jpg)

**Comment by harrysarson** [comment]
Trying swapping the single quotes around `'fixed'` for double quotes (like the error message says :smiley:), you will need to escape the double quotes to make the JSON valid.

**Comment by lwirtz** [comment]
@harrysarson Thank you! I'm a novice, so I had no idea about adding the escape to the double quotes! Works like a charm!

**Comment by harrysarson** [comment]
No worries, glad I could be off assistance.
