### ISSUE TITLE
How do we add alias to an existing unit?

### ISSUE THREAD

**Issue by ceremcem** [josdejong/mathjs#1108]
For example, I want to add `foo` as an alias of `hour`, how can I do that?

**Comment by ericman314** [comment]
This will do it:

```js
math.createUnit('foo', '1 hour');
```

And then:

```js
math.eval('120 minutes to foo');      // 2 foo
```

**Comment by ceremcem** [comment]
I was about to add your answer to the documentation, but here it was: http://mathjs.org/docs/datatypes/units.html#userdefined-units
