### ISSUE TITLE
Unexpected Value for tan

### ISSUE THREAD

**Issue by whatisthiswtf** [josdejong/mathjs#1113]
Running `tan(pi/2)` does not give `Infinity`

Also, `cos(pi/2)` gives `6.1232339957368e-17 `

Maybe this a more general problem with rounding, or rounding at intermediate steps?

Can the same problem affect other functions or procedures?

Tested on the expression parser on mathjs.org on May 27, 2018 2:25 P.M. EDT

**Comment by josdejong** [comment]
This is indeed a generic rounding issue. As far as I know there is no numerical solution to this problem (except some tricks that you could apply to have it occur less often). 

This as a duplicate of #133.
