### ISSUE TITLE
Test on Internet Explorer and Edge

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1115]
As of #1111 mathjs can now test on any browser but currently only test on chrome and firefox.

We should definitely: 
 - [x] Run tests on Microsoft Edge: fairly easy, need to fix some error message checks and account for some rounding differences.
 - [x] Run tests on IE 11: harder, need to polyfill some of the newer additions to JavaScipt.

We should look into:
 - [ ] Running tests on IE 9: would need to downgrade Mocha and possibly make quite a few changes to mathjs itself. I have a hunch this isn't worth it but is worth a look.

**Comment by harrysarson** [comment]
I am fairly busy for next two weeks or so. If anyone wants to have a go at this they would be very welcome to. I am happy to help if you need advice on where to start.

**Comment by harrysarson** [comment]
Applying this patch is a good place to start. It will get browserstack to run tests on IE 11 and Edge

```
diff --git a/browser-test-config/browserstack-karma.js b/browser-test-config/browserstack-karma.js
--- a/browser-test-config/browserstack-karma.js
+++ b/browser-test-config/browserstack-karma.js
@@ -7,6 +7,8 @@ module.exports = function(config) {
   config.set(Object.assign(baseConfig, {
     browsers: [
       'bs_firefox_android',
+      'bs_ie_11',
+      'bs_edge',
       'bs_chrome_mac',
     ],
     reporters: [
@@ -29,6 +31,20 @@ module.exports = function(config) {
         os: 'android',
         os_version: '7.0',
       },
+      bs_ie_11: {
+        base: 'BrowserStack',
+        browser: 'IE',
+        browser_version: '11',
+        os: 'Windows',
+        os_version: '7',
+      },
+      bs_edge: {
+        base: 'BrowserStack',
+        browser: 'Edge',
+        browser_version: '16',
+        os: 'Windows',
+        os_version: '10',
+      },
       bs_chrome_mac: {
         base: 'BrowserStack',
         browser: 'Chrome',
```

**Comment by josdejong** [comment]
See this branch: https://github.com/josdejong/mathjs/tree/browser_testing

Some tests on the IE11 and Edge are currently failing (like with error messages `TypeError: Object doesn't support property or method 'assign'`, and numerical round-off errors), will fix that coming weekend I hope.

**Comment by josdejong** [comment]
The tests are working now on IE11, Edge 17, Firefox 60, Safari 11.1 :tada:

**Comment by harrysarson** [comment]
I think it would be fair to drop IE 9 in version 5, that would save us from the head ache of testing it?

**Comment by josdejong** [comment]
Agree, let's drop official support for IE 9 (though it probably still works using ES5 shims)

**Comment by josdejong** [comment]
In that case, this issue is fully resolved :)

thanks again Harry, the browserstack tests really helped me a lot to make sure the ES6 build setup worked correctly, generating output that can be run on all browsers.
