### ISSUE TITLE
Add note on browser testing to README

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1116]
Now that #1099 and #1111 have landed we should expand the section of the readme that explains how to test mathjs.

 - A new (sub)section explaining how to use `npm run test:browser` to get karma to run the tests.
 - There is a bit already about browserstack. We should modify it to explain how to run our tests using the platform. We should also say this will only work if you have a browserstack account which most people probably won't have.

**Comment by josdejong** [comment]
:+1:
