### ISSUE TITLE
Browserstack tests are failling

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1117]
oh dear...

https://travis-ci.org/josdejong/mathjs/builds

It is some sort of network issue I think, `ETIMEDOUT` when trying to connect to browserstack.
I will have a look in the morning.

**Comment by josdejong** [comment]
Travis CI had issuesyesterday. I will rerun the failing tests to see if everything works again

**Comment by josdejong** [comment]
I've rerun the broken tests, and now everything passes again.

Thanks for your attentiveness!

**Comment by harrysarson** [comment]
Ah nice :smile:
