### ISSUE TITLE
TypeError: Scalar expected when calling math.subset

### ISSUE THREAD

**Issue by Clan-Utility** [josdejong/mathjs#1119]
Math.js 3.20.2

In general, I would like to append a matrix to another matrix on the right. 
That is, append
```
[
    [0, 1],
    [2, 3]
]
```
to
```
[
    [0, 1, 2],
    [3, 4, 5]
]
```
and get
[
    [0, 1, 2, 0, 1],
    [3, 4, 5, 2, 3]
]

```javascript
let a = math.matrix(...);  // size: n * m
let b = math.matrix(...);  // size: n * k

const rowRange = math.range(0, n);
const columnRange = math.range(m,m + k);
const indicesToReplace = math.index(rowRange, columnRange);
math.subset(a, indicesToReplace, b);
```

However, math.index sets _isScalar to true if n===1 & k===1, and that makes math.subset raise TypeError: Scalar expected

```javascript
let a = math.matrix([1, 4]); // size: 1x2
let b = math.matrix([2]);  // size: 1x1

// Expected result: [1, 4, 2]

const rowRange = math.range(0, 1);
const columnRange = math.range(2,3);
const indicesToReplace = math.index(rowRange, columnRange); // indicesToReplace._isScalar === true

// indicesToReplace._isScalar = false;  // If we manually set _isScalar to false, the following call will not raise exception and gives correct result
math.subset(a, indicesToReplace, b);  // This raises *TypeError: Scalar expected*
```

**Comment by josdejong** [comment]
I've tried your code on the latest version of mathjs and also on v3.20.2, and it works just fine. I don't get an error, so I'm not sure how to reproduce this issue. Note that you have to use the new matrix returned by `math.subset` to actually get the merged result.

Maybe your life will become a bit easier though by using the `concat` function: to do what you want you can simply do:
```js
const c = math.concat(a, b)
```

**Comment by Clan-Utility** [comment]
I was using node v9.5.0 on mac.

Anyway, math.concat works like a charm. Thanks.

**Comment by josdejong** [comment]
:+1:
