### ISSUE TITLE
CompareNatural does not compare strings lexically.

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1121]
`CompareNatural` uses [javascript-natural-sort](https://www.npmjs.com/package/javascript-natural-sort) to compare strings.

Strings are not compared lexically as the docs say they should be.

For example:

``` js
> math.compareNatural('5', '10')
-1
> '5' < '10'
false
```

and

``` js
> math.compareNatural('10/11/2009', '10/12/2008')
1
> '10/11/2009' < '10/12/2008'
true
```

Is this a bug or should we change the docs to say something like `strings are compared in a sensible way`?

(Note that the javascript operator `<` does lexical comparison on strings)

**Comment by josdejong** [comment]
Thanks, it's indeed an error in the documentation. I've updated the docs.

For reference, see also #1065.
