### ISSUE TITLE
Is it possible to use mathjs inside javascript function ?

### ISSUE THREAD

**Issue by nichabalie** [josdejong/mathjs#1123]
Hi, I want to use mathjs to evaluate mathematical expression inside a basic javascript function.

Simple example: 
```js
function f(a, b) {return a+b;}
```
I want the following result: `f([1,2,3], [4,5,6]) = [5, 7, 9]`

But when I use:
```js
math.import({f: function (a, b) {return a+b}});
parser.eval(f([1,2,3],[4,5,6]))
```
the result is `[1,2,3][4,5,6]`

Is there a way to use mathjs inside function? Thanks

**Comment by josdejong** [comment]
I guess what you want to do is add two arrays element wise, in that case you have to use the `math.add` function instead of the JavaScript `+` operator:

```js
function f(a, b) {return math.add(a, b)};
f([1,2,3], [4,5,6]) // [5, 7, 9]
```

Or you could define the function using the expression parser and use it externally like:

```js
var f = math.eval('f(a, b) = a + b');
f([1,2,3], [4,5,6]) // [5, 7, 9]
```

**Comment by harrysarson** [comment]
WHen calling the function 
```js
function f(a, b) {return a+b;}
```
with parameters that are not numbers it converts `a` and `b` to strings and then concatenates them
which is why you see the result as `[1,2,3][4,5,6]`.

You can see that this happens even with without using the expression parser:

```js
f([1,2,3], [4,5,6]) // '1,2,34,5,6'
f(math.matrix([1,2,3]), math.matrix([4,5,6])) // '[1,2,3][4,5,6]'
```

**Comment by nichabalie** [comment]
math.add(a,b) works well, thanks !

**Comment by josdejong** [comment]
:+1:
