### ISSUE TITLE
Logo Contribution For mathjs

### ISSUE THREAD

**Issue by iqbalhood** [josdejong/mathjs#1130]
Hello @josdejong. Can I Contribute to make Logo For This Project ?

**Comment by josdejong** [comment]
Thanks for your offer Mohammad. Yes sure, if you can come up with something that's new and fresh and better than the current logo would be nice. You will have to convince us of course :)

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
