### ISSUE TITLE
webassembly

### ISSUE THREAD

**Issue by elpeleq42** [josdejong/mathjs#1141]
Since nowadays every browser supports webassembly and (I think) even nodejs,electron, nwjs,etc also do, maybe mathjs should be ported to C/C++ and then compiled to webassembly.

Considering webassembly code to be only 30% slower than pure compiled code, and really easy to integrate with javascript, it could keep things as easy to use as they're now, but improve performance of complex/huge operations by a lot.

**Comment by FSMaxB** [comment]
Where WebAssembly would probably make sense is for typed matrix operations.
