### ISSUE TITLE
Spead up rationalize tests

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1142]
These two tests for `rationalize`:
 - processing power expressions (1857ms) 
 - processing tougher expressions (9316ms)
found in file https://github.com/josdejong/mathjs/blob/master/test/function/algebra/rationalize.test.js both take for ever to complete. This slows down our CI and makes running `npm test` more fustrating than it should be.

We should either:
 - reduce the complexity of these test cases.
 - speed up `rationalize`

**Comment by harrysarson** [comment]
Tagging @paulobuchsbaum as git blames says they added these tests.

**Comment by paulobuchsbaum** [comment]
The fast solution would be take out this 2 test cases, because it's proved that they work. 

In terms of speeding up processing I find it somewhat difficult because the bottleneck is in the meta structure of simplifying rules processing made by `simplify` function,  done by other collaborators.

**Comment by harrysarson** [comment]
Closed by 6edac98 in #1143
