### ISSUE TITLE
Is it possible to combine two matrices ?

### ISSUE THREAD

**Issue by nichabalie** [josdejong/mathjs#1145]
Hello,

Is it possible to combine two matrices (or arrays) by row or by column like cbind() or rbind() in R?

Thanks.

**Comment by josdejong** [comment]
Not sure but I think you're looking for `concat`

Docs: http://mathjs.org/docs/reference/functions/concat.html

**Comment by nichabalie** [comment]
Yes, but it only work if both matrices have the same dimensions. Is it possible to concatenate an array with a matrix by row or by column for example?

**Comment by josdejong** [comment]
@nichabalie I'm not sure I understand your use case, can you post a code example of what you would like to be able to do?

**Comment by nichabalie** [comment]
Sorry, the function `concat` worked well, I just needed to used it with matrix instead of array.
Thanks

**Comment by josdejong** [comment]
👍 thanks for the feedback.

The function should work for both Array and Matrix

**Comment by nichabalie** [comment]
@josdejong 
In fact the function works between Array-Array and Matrix-Matrix but not between Array-Matrix.
If I wanted to concatenate the Array `A = [1,2]` with the Matrix `B = [[3,4],[5,6]]`, `concat(A,B)` didn't work (DimensionError: Dimension mismatch (1 != 2)).
So I had to create a Matrix `C = transpose([[1,2]])` and use `concat(C,B)` to obtain my result: `[[1, 3, 4], [2, 5, 6]]`
It is not very practical but it works

**Comment by josdejong** [comment]
Ah, now I understand what you mean with Array vs Matrix, you mean a one dimensional Array vs a two dimensional array. In math.js there is also a Matrix class (created via `math.matrix(...)`) I thought you where referring to that.

You indeed have to make sure the two Arrays have the same dimensions.
