### ISSUE TITLE
rationalize() throws exception for some input with decimals

### ISSUE THREAD

**Issue by maruta** [josdejong/mathjs#1146]
rationalize() seems to fail for some input with decimals. 
So far, I tested
`math.rationalize('1/(0.1x+1)+1').toString()` 
-> throws exception
`math.rationalize('1/(1.0x+1)+1').toString()`
 -> "(x + 2) / (x + 1)" OK  
`math.rationalize('1/(0.1x+1)').toString()`
 -> "10 / (x + 10)" OK
with version 5.0.0.

Thanks!

**Comment by maruta** [comment]
After further investigation,
I found a part of the problem is related to negative integer exponents.
This problem is reproduced by simpler example
```
math.rationalize('1/x^2+1')
// ArgumentsError: There is a non-integer exponent
```
and some modification seems to solve this problem.
https://github.com/maruta/mathjs/commit/35c9aa7a689454047bfb552a0dcc6d026788d939

To make
```
math.rationalize('1/(0.1x+1)+1').toString())
```
work, I needed to modify rationalize() algorithm
https://github.com/maruta/mathjs/commit/b0d077f38628b43ac673c2a7fe3c4db9e417bd9a
but I'm not confident this is preferable in general case.

**Comment by harrysarson** [comment]
When you run `npm test` after your changes, do they all pass?

**Comment by maruta** [comment]
When I run `npm test` in my environment, one test fails as follows
```
  4166 passing (35s)
  18 pending
  1 failing

  1) Unit
       prefixes
         should accept both long and short prefixes for bar:
     SyntaxError: Unit "millibar" not found.
```
the failed test also fails in v5.0.0 and seems to have nothing to do with my change.

**Comment by josdejong** [comment]
Thanks for diving into this @maruta! I hope to look into this soon unless @paulobuchsbaum beats me ;)

**Comment by josdejong** [comment]
I've implemented a fix based on the work of @maruta (thanks again!), see https://github.com/josdejong/mathjs/commit/0d93fff8784e1187af3fe5071a85bfc9817e221d

@paulobuchsbaum and @maruta can you please review this commit? I'm not very familiar/confident with this part of the code base, so a pair of extra eyes would be helpful.

**Comment by josdejong** [comment]
I've released the fix based on @maruta 's work in `v5.0.2`, please let me know if there are still issues in this regard.

**Comment by maruta** [comment]
@josdejong @paulobuchsbaum 
Thanks a lot!
I totally agree with comments by @paulobuchsbaum

**Comment by josdejong** [comment]
Thanks for your input @paulobuchsbaum . I don't fully understand all your points but if you can turn it into a PR it would be great!

> @josdejong, can I make a new pull request? What branch?

To the `develop` branch. Note that there has been quite some refactoring going in v4 and v5, so please make sure your `develop` branch is up to date before implementing your suggested improvements.
