### ISSUE TITLE
Make simple integral extension as part of mathjs main lib.

### ISSUE THREAD

**Issue by elpeleq42** [josdejong/mathjs#1149]
From what I could find, it seems that mathjs has no built in way to solve integrals, and requires the extension given on the website(which I couldn't install using 5.0.1 btw, not the main topic) to do so(for simple cases only, also).

My question is: Why?Since integrals are so used in math (mainly on college/university or other serious places, which are probably the public of mathjs), why is this an extension and not a main feature?(Also, why so long to update? 6 months since last file was updated)

also, adding to my question/request, here's another request: If in the future there be a implementation of integrals to default mathjs, can there be added support for it in math.eval()? Because that function is really really useful.

**Comment by josdejong** [comment]
Integration is indeed not yet been implemented. There are discussions about it though:

#442
#788
#993
#1015

**Comment by elpeleq42** [comment]
Oh thanks by the info. From what I could understand from the website, It looked like as this extension was never going to be a thing in mathjs, remaining just an extension.

Thanks for clarifying.

**Comment by josdejong** [comment]
This extension you refer to is a first step. I really hope we will get `integral` built-in mathjs itself. It's not trivial though. 

Will close this issue now since the discussion is covered in other issues too.
