### ISSUE TITLE
Type Error when triggering Matrix function after calling math.zeros

### ISSUE THREAD

**Issue by JasonShin** [josdejong/mathjs#1150]
Hello, I'm using Math.js in my Typescript application. I found that I cannot trigger interface methods of Matrix after using math.zeros because the return type is 'number[] | number[][] | Matrix'

When I run the code below

```
const placeholder = math.zeros(_.size(classes), _.size(classes));
console.log(placeholder.toJSON());
```

It complains that `Property 'toJSON' does not exist on type 'number[]'..`

The only walkaround is using datatype:any, which I don't strictly like to do

```
const placeholder:any = math.zeros(_.size(classes), _.size(classes));
console.log(placeholder.toJSON());
```

Please suggest me a better solution to this

**Comment by JasonShin** [comment]
Apologies if I haven't followed any standard formatting when creating issues

**Comment by josdejong** [comment]
I guess this is some issue in the TypeScript definitions that you use, which I don't maintain.

Maybe @bradbesserman can help here since he has been working on the TypeScript definitions recently? https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mathjs

**Comment by bradbesserman** [comment]
Maybe try JSON.stringify(placeholder) - should accomplish the same thing and I think stringify is a little more versatile.  I don't think this is a problem with the mathjs type file - the error seems to be that Typescript doesn't recognize a toJSON function associated with the number[] type.

**Comment by josdejong** [comment]
Ah, good point @bradbesserman, you should indeed use `JSON.stringify` and not `toJSON`.

See also docs: http://mathjs.org/docs/core/serialization.html

**Comment by bradbesserman** [comment]
I think the confusion is that zeros() can return a standard typescript number array or a mathjs Matrix type.  Mathjs matrix type does explicitly have a toJSON function.

**Comment by josdejong** [comment]
> How do you invoke zeros to get Arrays instead of a Matrix type?

That's determined by a config setting `math.config({matrix: 'Matrix' | 'Array'})`

Docs: http://mathjs.org/docs/core/configuration.html

**Comment by JasonShin** [comment]
Thank you !

**Comment by josdejong** [comment]
:+1:
