### ISSUE TITLE
Shouldn't forEach provide an index to the callback ?

### ISSUE THREAD

**Issue by ashwinmr** [josdejong/mathjs#1152]
The forEach function provides 3 parameters to the callback. Namely, val, ind, mat
```
math.forEach(x, callback)
```
I found that `ind` is an array instead of an index. This makes it difficult to use it to access elements in the matrix
```
let m = math.matrix([
    [1, 2],
    [3, 4]
])
math.forEach(m, function(val,ind,mat) {
mat.subset(ind) = 0
})
```
This gives an error since `ind` is an array and not an index.

`m.subset(math.index(ind))` also does not work because `m` is not an array.

The only way I can think of to make this work is to break apart `ind` and use it in `math.index(i,j)` which kind of defeats the use of `ind`. Also more involved for higher dimensions.

**Comment by josdejong** [comment]
>  found that ind is an array instead of an index.

**Comment by josdejong** [comment]
I think what you try to do is:

```js
let m = math.matrix([
    [1, 2],
    [3, 4]
])
math.forEach(m, function(val,ind,mat) {
  mat.set(ind, 0)
})
```

or
```js
let m = math.matrix([
    [1, 2],
    [3, 4]
])
math.forEach(m, function(val,ind,mat) {
  m = math.subset(m, math.index(...ind), 0)
})
```

**Comment by josdejong** [comment]
:+1:

**Comment by Prabakaran-Chandran** [comment]
Dont we need to assign 
math.forEach(m, function(val,ind,mat) {
  m = math.subset(m, math.index(...ind), 0)
})

to any variable

**Comment by josdejong** [comment]
I'm not sure what you mean @Prabakaran-Chandran
