### ISSUE TITLE
Is it possible to add string comparison using == operator?

### ISSUE THREAD

**Issue by AnastasiaArtyom** [josdejong/mathjs#1171]
when I tried evaluating something like "a" == "a" I got this error:
Error: Cannot convert "a" to a number
Is it possible to fix?

**Comment by harrysarson** [comment]
Hi @AnastasiaArtyom, this is by design, please see https://github.com/josdejong/mathjs/issues/1085 for more info about comparison of strings. You may find the function `equalText` useful (http://mathjs.org/docs/reference/functions/equalText.html).

**Comment by AnastasiaArtyom** [comment]
@harrysarson Thanks!
