### ISSUE TITLE
err.message undefined

### ISSUE THREAD

**Issue by javazen** [josdejong/mathjs#1180]
This simple piece of code does not work (err.message is undefined) when given a bad formula such as "sum(a:c)" :
```js
  try {
    rootNode = math.parse(formula);
    // my transforms
    rootNode = math.simplify(rootNode);
  } catch (err) {
    if (DEBUG) console.log('err: ' + err.message);
  }
```

Version 4.4.2 math.js line 20491 is not throwing a "new Error" of any kind, just a string... (I see this on line 20280 as well)

**Comment by josdejong** [comment]
Thanks for reporting @javazen 

This has been fixed already , about a month ago: 

https://github.com/josdejong/mathjs/blob/master/src/function/algebra/simplify/simplifyConstant.js#L247

I don't know by heart which version exactly contains this fix, but the latest version (`v5.0.3`) should throw a proper `Error`.

**Comment by javazen** [comment]
Yes, I did look in 5.0 and saw that it was fixed there. I'll still evaluating 5.0 for use in my project, I'll try to get up to the latest asap...

**Comment by josdejong** [comment]
:+1:
