### ISSUE TITLE
subset/index not working on terminal? 

### ISSUE THREAD

**Issue by honeybar** [josdejong/mathjs#1182]
I try to run this particular example from the documentation [http://mathjs.org/docs/reference/functions/subset.html](http://mathjs.org/docs/reference/functions/subset.html) in particular this one:
```
const d = [[1, 2], [3, 4]]
math.subset(d, math.index(1, 0)) 

```
it doesn't run when I do it on terminal, however:
```
> d = [ [ 1, 2 ], [ 3, 4 ] ]
d = [[1, 2], [3, 4]]
> subset(d, index(1, 0))
IndexError: Index out of range (0 < 1)
```

**Comment by josdejong** [comment]
There are some important differences between de JavaScript API and the expression parser API, one is that the expression parser is one-based instead of zero based. In the expression parser you would do:

```
d = [ [ 1, 2 ], [ 3, 4 ] ]
d[2, 1]. # 3
```

**Comment by honeybar** [comment]
Ah I see. I am still new to javascript so I am not quite familiar with it. Thanks for explaining :)

**Comment by josdejong** [comment]
Well, this implemented difference between the JavaScript API and the expression parser API can be confusing. It's an imperfect attempt to serve two different audiences at the same time.

See docs for more information: http://mathjs.org/docs/expressions/syntax.html#differences-from-javascript

If you would like to read some more background on the choices made here I can send you a paper about math.js that @ericman314 and I wrote recently.
