### ISSUE TITLE
Maintained badge links to invalid site.

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1188]
In the readme, when I click the maintained badge

[![Maintenance](https://img.shields.io/maintenance/yes/2018.svg)]()

I am taken to https://github.com/josdejong/mathjs/blob/master which is a 404. We should fix this to link to somewhere appropriate.

**Comment by josdejong** [comment]
:+1: I've changed it to link to the commit activity of the project: https://github.com/josdejong/mathjs/graphs/commit-activity
