### ISSUE TITLE
Set rounding modes for BigNumber

### ISSUE THREAD

**Issue by nativemeadow** [josdejong/mathjs#1190]
As described in the docs for the BigNumber type, BigNumber is powered by Decimal.js.  Decimal.js allows you to configure the rounding mode (ROUND_UP, ROUND_DOWN, ROUND_HALF_UP, ROUND_HALF_DOWN... etc.).  Is there a reason why the same cannot done for BigNumber in mathjs.  Taking a quick look at the code it seems the configuration options for Decimal.js in mathjs are "hard" coded.   Thanks

**Comment by harrysarson** [comment]
A (very old) PR adding configurable bignumber rounding: #831

**Comment by gwhitney** [comment]
If you need to round any mathjs type, floor, ceil, fix, and round give you four "modes" of rounding with any specified number of digits. So this feature would seem unnecessary. Closing.
