### ISSUE TITLE
Problem with Fraction adding...

### ISSUE THREAD

**Issue by S-W-007** [josdejong/mathjs#1197]
I used the following code in my project:
```
const fr = math.fraction(count);
      return `${fr.n}/${fr.d}`;
```
For example, if count=0.33333333, it will be converted to 1/3.
Then continue adding the same number, it will be 2/3, finally, 3/3 becoming `**1/1**` rather than 1.  
So the output looks very strange.

How to fix it?   Thanks in advance!

**Comment by ericman314** [comment]
Try `toFraction()`:

```js
const fr = math.fraction(count);
      return fr.toFraction();
```

**Comment by S-W-007** [comment]
That works!  Thank you!
