### ISSUE TITLE
[BUG] Inaccurate INCH to FEET

### ISSUE THREAD

**Issue by NavyCo** [josdejong/mathjs#1208]
I was trying testing the **CLI** part...
By trying to convert 24 inches to feet.
![image](https://user-images.githubusercontent.com/7671296/43997450-26bbabaa-9da9-11e8-845a-adf05bf760c7.png)
As most know 12 inches equals a single foot.
So 24 inches should equal 2 feet!
But I tried 12 inches alone...
![image](https://user-images.githubusercontent.com/7671296/43997466-9303cc3e-9da9-11e8-8d70-e235a847b59a.png)

**Comment by harrysarson** [comment]
Hi @NavyCo, the round off errors you see are due to the way real numbers are stored on a computer and is explained at http://mathjs.org/docs/datatypes/numbers.html#round-off-errors.
