### ISSUE TITLE
Add unit decibel

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#1209]
For reference: https://github.com/josdejong/mathjs/issues/1043#issuecomment-412334683

**Comment by josdejong** [comment]
Addressed via #1518

**Comment by veggiesaurus** [comment]
@josdejong has there been a regression on this? dB and decibels don't seem to work anymore

**Comment by josdejong** [comment]
@veggiesaurus these units have been removed again, see: https://github.com/josdejong/mathjs/pull/1518#issuecomment-494226286.

If needed, you can always define them yourself via `createUnit`.
