### ISSUE TITLE
Single quote parsing oddities; unexpected effect of `a = '2''`

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1210]
We should lock down the behaviour of `'2''` with a test.

See #1202

**Comment by harrysarson** [comment]
If no one gets to this by September I will have a go then

**Comment by gwhitney** [comment]
Bizarrely, `a = '2''` currently results in a being assigned  the _number_  2 as its value. That's just bizarre. It would seem fine to be an error, or to make a the string `"2'"`, or there might be other reasonable outcomes, but in what world should a be the number 2? So marking this as a bug and retitling it.

**Comment by josdejong** [comment]
What is happening here is that the expression `'2''` is parsed as the `ctranspose` of the string `'2'`. It basically evaluates to `conj(transpose('2'))`, which results in the answer `2`.

So it is kind of odd behavior but I don't think there is a fixable bug in play here. I'll close this issue, feel free to reopen if needed.
