### ISSUE TITLE
Show a number greater than 5 as an integer

### ISSUE THREAD

**Issue by niloo26** [josdejong/mathjs#1211]
Hello
What formulas do I use to call a number greater than 5 digits if the number is given as an integer or if it is numbers in the form of an integer

![adnpper](https://user-images.githubusercontent.com/42408289/44146468-e881daea-a0a4-11e8-9b73-274617244ce8.png)

**Comment by josdejong** [comment]
`isInteger`, `format`, `size`, `larger`, ...

**Comment by niloo26** [comment]
![default](https://user-images.githubusercontent.com/42408289/44164948-aa95e680-a0dc-11e8-8157-93b0c42875aa.png)


![default](https://user-images.githubusercontent.com/42408289/44164982-c4cfc480-a0dc-11e8-9480-ca89c5fa8e5e.png)
