### ISSUE TITLE
Alias operator to another operator?

### ISSUE THREAD

**Issue by stoplion** [josdejong/mathjs#1212]
Hello, I've gone through the documentation and I'm still trying to figure out how to do a few things. 
I'm looking for guidance on how to disable the `%` as modulo operator and using `mod` as modulo operator instead. And then creating `%` as a new 'percent' unit. I think I've got the creating of `%` down, but is there a way to "alias" on operator to another (in this case alias `%` to `mod`)?

**Comment by josdejong** [comment]
It's not possible to do custom operators right now. Here is an (old) topic discussing this: #467. Lets continue the discussion there ok?

**Comment by josdejong** [comment]
Note that you can already use `7 mod 3` if you want
