### ISSUE TITLE
Possible to not throw error on array of equations ?

### ISSUE THREAD

**Issue by stoplion** [josdejong/mathjs#1213]
It there any option to have MathJS not throw and error (or to catch it) when eval-ing an array of equation string?
Say I had an array of 50 lines of equations and one created an error, instead of totally erroring out, it returned NaN or something instead?

`math.eval('[1+3, 4-1, 5/1, 2+2, 3+null]')`
throws an error

**Comment by josdejong** [comment]
mathjs treats `null` as a clear flag that there is something wrong. `null` is not a number, so most probably something is missing in your inputs. In general it is best to see where this `null` comes from and solve it at the root. 

So please think about it carefully. If you really want to treat `null` as a valid number `0`, you could:

1. Write a RegExp to replace occurrences of `null` with `0` (be careful not to replace parts of a variable name, so use word boundaries)

2. Parse the expression, replace occurrences of `ConstantNode` with value `null` with `0`, and then evaluate the expression:

    ```js
    function replaceNull(tree) {
      return tree.transform((node, path, parent) => {
        if (node.isConstantNode && node.value === null) {
          return new math.expression.node.ConstantNode(0)
        }
        else {
          return node
        }
      })
    }

    const tree = math.parse('[1+3, 4-1, 5/1, 2+2, 3+null]')
    console.log(replaceNull(tree).eval())  // Matrix [ 4, 3, 5, 4, 3 ]
    ```

3. Define a conversion from `null` to `0`:

    ```js
    // create an empty mathjs instance
    const core = require('../../core')
    const math = core.create()

    // define our conversion before importing all functions
    math.typed.addConversion({ 
      from: 'null', 
      to: 'number', 
      convert: (value) => 0 
    })

    // import all functions
    math.import(require('../../lib'))

    console.log(math.eval('[1+3, 4-1, 5/1, 2+2, 3+null]')) // Matrix [ 4, 3, 5, 4, 3 ]
    ```
