### ISSUE TITLE
Typo in the guide

### ISSUE THREAD

**Issue by Ty-Won** [josdejong/mathjs#1222]
Hi There!

There's a small typo in the guide about subsets. The index specified should be : 
```
math.subset(d, math.index([0, 1], 1))   // returns [[2], [4]]
```
![screenshot from 2018-08-24 16-03-52](https://user-images.githubusercontent.com/19980222/44605422-4f888180-a7b7-11e8-8d96-a606997347e4.png)

**Comment by josdejong** [comment]
Thanks for reporting @Ty-Won . It's fixed in the `develop` branch now and will be fixed on the website the first next release.
