### ISSUE TITLE
Input preprocessor for numbers

### ISSUE THREAD

**Issue by pbelmans** [josdejong/mathjs#123]
I'm not sure whether it's a bug or a feature, but if I configure Math.js to work with `bignumber`, i.e.

    var math = mathjs({
      number: 'bignumber',
    });

I would expect

    console.log(typeof math.factorial(3));
    console.log(typeof math.factorial(math.bignumber(3)));

to give the same output: I want both of them to be a `BigNumber`. Unfortunately only the latter is. Am I missing something, which would make this desired behaviour possible? Or is this actually undesired behaviour, and am I expecting something against the structure of Math.js?

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by pbelmans** [comment]
It wasn't an issue per se to start with, just some confusion. Whichever way it is resolved in the code wasn't important in the end, and I worked around it in my implementation if I remember correctly.

**Comment by josdejong** [comment]
Ok thanks, I will close this issue then.
