### ISSUE TITLE
quantileSeq has inconsistant return

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1236]
I found that `quantileSeq` has an inconsistent return:
- `math.quantileSeq([1,2,3,4,5], math.bignumber(.2))` returns `bignumber(1.8)`.
- `math.quantileSeq([1,2,3,4,5], math.bignumber(.25))` returns `2` (a non big number).

This should have been flagged by mathjs tests but node's `assert.equal` has let us down. I found this whilst swapping `assert.equal` for `assert.strictEqual`.

I am fairly confident that this is a bug.

**Comment by josdejong** [comment]
Very nice that this issue pops up now with `assert.strictEqual` :+1:

**Comment by josdejong** [comment]
Should be fixed now via https://github.com/josdejong/mathjs/commit/4e1bed2a74fd6f85cf82fb0e3e0f4524d75cd492
