### ISSUE TITLE
norm returns a complex number

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1237]
http://mathjs.org/docs/reference/functions/norm.html documents `math.norm` as returning a Number or a BigNumber.

However, the frobenius norm of a matrix containing complex values is a complex number (with imaginary part equal to 0).

```js
math.norm(math.matrix([[math.complex(1, 4)]]), 'fro')
// Object { re: 4.123105625617661, im: 0 }
```

**Comment by harrysarson** [comment]
Note: unless the matrix is 2D the result is correct.

```js
math.norm(math.complex(1, 4), 'fro')
// 4.123105625617661

math.norm(math.matrix([math.complex(1, 4)]), 'fro')
// 4.123105625617661

```

**Comment by josdejong** [comment]
:+1: should be fixed via https://github.com/josdejong/mathjs/commit/ba1987f7e5dd52dc557a5d90cd19ba39b4298c58

**Comment by harrysarson** [comment]
ba1987f looks ace :+1:
