### ISSUE TITLE
Can we subset or slice Matrix like Numpy?

### ISSUE THREAD

**Issue by JasonShin** [josdejong/mathjs#1239]
Hello,

Is it possible to slice a matrix (tensor) like in Numpy with Math.js? To give you examples,

```
train_image.shape # MNIST image data saved as a Tensor with shape (60000, 28, 28)
train_image[10: 100] # 1. Retrieve 10th ~ 99th MNIST digits
train_images[128 * n:128 * (n + 1)] # 2. getting an nth batch
```

What's the best way to achieve this? 
1) Can you do this using `math.subset`? 
2) Should we create another function named `slice`?
3) Is it better to do this outside of Math.js?

**Comment by josdejong** [comment]
Yes something like that would be cool. We had a similar discussion long time ago, see #54

**Comment by josdejong** [comment]
For reference: mathjs supports ranges like `A[10: 100]` and `A[2: end - 2]` right now, but does not offer more complicated slicing like you suggest.

See examples in the docs: http://mathjs.org/docs/expressions/syntax.html#matrices

**Comment by gwhitney** [comment]
Much time has passed, and indeed now all of the original poster's examples work more or less exactly as described in the internal mathjs parsed notation (just with slight indexing variations because mathjs ranges are inclusive, and all dimensions must be mentioned):
```
M = <some expression that returns a (60000 x 28 x 28) collection -- Matrix or Array>
M[10:99, :, :] # returns a 90x28x28 collection of the 10th through 99th "planes" of M
n = 7 # which "batch" we want
M[128*n : 128*(n+1)-1, :, :]  # Returns the nth batch
```

Hence closing.
