### ISSUE TITLE
feature: Find the unique elements of an Array/Matrix

### ISSUE THREAD

**Issue by alvinhui** [josdejong/mathjs#1242]
Examples:

```javascript
math.unique([1, 1, 2, 2, 3, 3]) // [1, 2, 3]
math.unique([[1, 1], [2, 3]]) // [1, 2, 3]
```

more: [numpy.unique](https://docs.scipy.org/doc/numpy/reference/generated/numpy.unique.html)

**Comment by alvinhui** [comment]
it should be easier to implement as array:

```javascript
function unique(collection) {
  return[...new Set(math.flatten(collection))];
}
```

**Comment by josdejong** [comment]
@alvinhui have you tried the set functions, like `setUnion`?

http://mathjs.org/docs/reference/functions.html#set-functions
http://mathjs.org/docs/reference/functions/setUnion.html

**Comment by alvinhui** [comment]
@josdejong 

`setUnion` doesn't seem to be the purpose of finding the  unique  element of a matrix.

setUnion usage: 

```javascript
math.setUnion(
  [[1, 2], [3, 4]],  // a1
  [[3, 4], [5, 6]] // a2
)
```
If I use it in the scene I mentioned above

```javascript
math.setUnion([[1, 1], [2, 3]]) // got a error: Too few arguments in function setUnion (expected: Array or Matrix
```

**Comment by josdejong** [comment]
ah sorry, my bad. You're right `setUnion` is about finding unique elements in two sets but not in one.

**Comment by Nekomajin42** [comment]
I guess you are looking for `setDistinct`.

http://mathjs.org/docs/reference/functions/setDistinct.html

**Comment by josdejong** [comment]
ah of course, good suggestion Tóth

**Comment by alvinhui** [comment]
@Nekomajin42 @josdejong wo, looks good for me.
