### ISSUE TITLE
Example math.eval('2 inch to cm') does not return 5.08 cm [docs]

### ISSUE THREAD

**Issue by q2apro** [josdejong/mathjs#1249]
In the docs at http://mathjs.org/examples/units.js.html it states:

    print(math.eval('2 inch to cm')) // 5.08 cm

However, executing:

    math.eval('2 inch to cm')

in the webdeveloper console returns:

    E {units: Array(1), dimensions: Array(9), value: 0.0508, fixPrefix: true, isUnitListSimplified: true} 

Am I doing something wrong or are the docs outdated?

**Comment by harrysarson** [comment]
Hi @q2apro,

If you convert the object you get in the webdeveloper console to a string then it should give "5.08 cm"

Try:
```js
math.eval('2 inch to cm').toString()
```

In the docs a function `print` is used. This function is defined near the bottom of the example and does the conversion to string.

**Comment by q2apro** [comment]
This works. Thanks a lot!

**Comment by harrysarson** [comment]
No worries :)
