### ISSUE TITLE
Can i write a math equation which has unknown part ?

### ISSUE THREAD

**Issue by AliOsamaHassan** [josdejong/mathjs#1252]
Which components will help me to display dynamically an Math Equation which has an **unknown part** like this ? 

I already have the equation with its **unknown** and **known** parts, but i need to display the known part to be (**_non editable_**) and the unknown part to be (**_editable_**) dynamically.

See the following examples !

![examples](https://user-images.githubusercontent.com/19392865/45609499-92591480-ba58-11e8-802c-f467d41ea421.PNG)

![example](https://user-images.githubusercontent.com/19392865/45609498-91c07e00-ba58-11e8-83f2-49993745b4c3.PNG)

**Comment by AliOsamaHassan** [comment]
@josdejong  Thank you very much !!

**Comment by josdejong** [comment]
:+1:
