### ISSUE TITLE
How do I refer to a previously defined function in parser?

### ISSUE THREAD

**Issue by davesnotes** [josdejong/mathjs#1255]
Hi,
Some code probably explains it best:
```
parser = mathjs.parser();

this.parser.set('A', n => n + 1);
this.parser.set('B', n => A(n) + 1);
```

When I call B I get an error:

"ReferenceError: A is not defined"

Can this be done?

**Comment by josdejong** [comment]
`A` is only defined inside the parser, not in your JavaScript context

I think you could do:
```js
parser = mathjs.parser();

this.parser.set('A', n => n + 1);
this.parser.set('B', n => this.parser.get('A')(n) + 1);
```
Or you can create the function `B` inside the parser (or both `A` and `B`):
```js
parser = mathjs.parser();

this.parser.set('A', n => n + 1); // or this.parser.eval('A(n) = n + 1');
this.parser.eval('B(n) = A(n) + 1');
```

**Comment by davesnotes** [comment]
Excellent, thanks for the quick reply.  I decided to go with the first suggestion of using parser.get which works exactly as I want.

Thanks again.
