### ISSUE TITLE
isUnit check?

### ISSUE THREAD

**Issue by stoplion** [josdejong/mathjs#1257]
Since unit is multiply Node with a ConstantNode and SymbolNode. Have to check the args[1] each time to see if a node is unit. I read in other Issues mention of `isUnit` property. Is that currently available? If not, is there a preferred way to check if a node is a unit?

**Comment by josdejong** [comment]
Hm, there is an `isUnit` function but it's a bit hidden under `math.type.isUnit`. 

Makes sense to move these functions to the main `math` namespace instead

**Comment by josdejong** [comment]
Duplicate of #627, let's continue the discussion there.
