### ISSUE TITLE
pow(x,2) failing in math.derivative method

### ISSUE THREAD

**Issue by sriram15690** [josdejong/mathjs#1259]
Derivative of `derivative("x^2", "x")` works fine but `derivative("pow(x,2)", 'x')` throws an error.

After debugging, I found that it fails in `funcArgsCheck` as the number of Args is `!= 1`. I guess the `,`(comma) between `x` & `2` in `pow(x,2)` is splitting the string.

Can you please help? Below are the links to MathsJs notepad with the above equations.

Url: http://mathnotepad.com/#contents=N4IgzgLghhCmIC5RlgG1gYwgSwPYDtFRt8ATWAD0QCYAacaAJwkQAZ7Yy2BfesDRrlSoAKrgAOiAMy8QlcY1hgwefGEQBtUADcoqAK7wEIco2y6c22AAoAOiAoA9avdoACexXsBKEPQC2sNBE3Lw6eoaIJrBmFuY29uK4AO7WFLTU3q5uAOQUOb4BQVAhYSC6BkYgfiCBwUihtOGVUTV1JQ3cALr0VowqBNL0%2BuKkMLCkUdSsAIwAHAC0rACcCzPLIjMArAgALLsI0wB0rFJbAFog3EA

<img width="415" alt="screen shot 2018-09-19 at 16 44 25" src="https://user-images.githubusercontent.com/8079683/45764766-59bd6480-bc2b-11e8-8e1a-96f11953f9ee.png">

**Comment by josdejong** [comment]
Thanks for reporting @sriram15690 . 

It turns out that the function `pow` isn't yet added to `derivative.js`. Should be quite easy to add support for this since the operator `^` is supported.

Anyone interested in extending `derivative` with support for the function `pow`?

**Comment by sam-19** [comment]
I created a pull request that fixes this issue by simply passing the pow function arguments to the already existing operator node parser for pow. I'm pretty new to GitHub so it may not be exactly what you were looking for, but it passed my test cases.
