### ISSUE TITLE
Is it possible to parse expression to tokens list?

### ISSUE THREAD

**Issue by pie6k** [josdejong/mathjs#1275]
Right now I was able to parse expression to nodes tree.

However, I'd like to perform some kind of syntax highlighting and I'd like to parse expression to tokens list.

Something like:

```
math.getTokens('2     + 2');

---->
[
  {
    type: 'CONST',
    content: '2'
  },
  {
    type: 'WHITESPACE',
    content: '     '
  },
  {
    type: 'OPERATOR',
    content: '+'
  },
  {
    type: 'WHITESPACE',
    content: ' '
  },
  {
    type: 'CONST',
    content: '2'
  },
]
```

Note I need to keep information about all whitespaces (even those that are not needed for parsing)

**Comment by josdejong** [comment]
The parser indeed loses all information about white spaces. Only comments are kept. I think you will have to be creative and find a way around it :(
