### ISSUE TITLE
Comparing an array of strings with a single string fails

### ISSUE THREAD

**Issue by mcaviola** [josdejong/mathjs#1276]
In former versions it was possible to compare arrays of strings with a single string.
It seems that in the current version this is not possible anymore.

> arr1=[2,4,6]
> [2, 4, 6]
> 
> arr1==4
> [false, true, false]
> 
> arr2=['b','d','f']
> ["b", "d", "f"]
> 
> arr2=='d'
> Error: Cannot convert "b" to a number

I would expect to get the following result:

> arr2=='d'
> [false, true, false]

Is the current behavior intended or an issue?

**Comment by josdejong** [comment]
The behavior of comparing strings was indeed changed to compare the numerical contents of strings by default, that was in version 4.0.

To compare strings lexically you can use the functions `equalText` and `compareText`.

**Comment by mcaviola** [comment]
Ok, great! That works for me.
Thanks for your answer.

**Comment by mcaviola** [comment]
equalText can be used instead of '=='
