### ISSUE TITLE
Conversion from rod to feet is wrong

### ISSUE THREAD

**Issue by akanshgulati** [josdejong/mathjs#1279]
Ideally, 1 rod is exactly 16.5 feet but somehow Math.js adds more digits after decimal places. Checked the SI conversion too. 1rod = 5.5 yards and 1 yard = 3 feet exactly.

**Comment by josdejong** [comment]
1 rod in feet gives as output `16.500032808399 feet`. I guess it's a numerical round off error. In math.js, a `rod` is defined as `5.02921 meter`.

**Comment by ericman314** [comment]
I believe the value should be `5.0292 meter`. This was probably just a typo.

**Comment by josdejong** [comment]
wow you're right! I don't know how I overlooked that when checking yesterday. Thanks for your fix in #1280

**Comment by josdejong** [comment]
Was fixed in `5.2.1`, forgot to close this issue.
