### ISSUE TITLE
Implement a function hasNumericValue(text)

### ISSUE THREAD

**Issue by LloydLS** [josdejong/mathjs#1281]
Hi,

I'd like to request a change to how the `number()` function deals with strings that it can't convert to numbers:

```
number("a") # returns: error;  would like: "a"
```

This would be useful because currently, 

```
isNumeric("1")  # returns: false; 
```

so I would like to be able to do something like this:

```
testNum(val) = isNumeric(number(val));
testNum("1") # would like to return: true;
testNum("a") # would like to return: false;
```

Also, I noticed this result which i didn't expect:

```
isNumeric(NaN) # returns: true;  expected: false
```

Thanks!

**Comment by josdejong** [comment]
@LloydLS if I understand you correctly you would like to have a function which checks whether a string contains a numeric value?

**Comment by LloydLS** [comment]
Yes, that sounds good.

Thanks!

**Comment by josdejong** [comment]
Ok clear, I will change the title of this issue accordingly and mark it as a feature request.

We could name the function something like `hasNumericValue(text)` but I'm open to suggestions.

Anyone interested in implementing this new function `hasNumericValue`?
