### ISSUE TITLE
How to represent ÷ math symbol as \div in Latex ? or what is the math expression of  \div latex command ?

### ISSUE THREAD

**Issue by AliOsamaHassan** [josdejong/mathjs#1288]
Can i represent the `÷` math symbol as `\div` in Latex ? 
or
what is the math expression of  `\div` latex command ?

Hint : i use the `\` math symbol for fraction which represented by `\frac` latex command, so i want another math symbol for division which  represented by `\div` latex command

**Comment by josdejong** [comment]
Have you tried creating a custom latex handler?

Docs: http://mathjs.org/docs/expressions/customization.html#custom-html-latex-and-string-output

**Comment by AliOsamaHassan** [comment]
Thanks @josdejong, I'll see it.
