### ISSUE TITLE
getAll() missing from Parse type definitions

### ISSUE THREAD

**Issue by jfstephe** [josdejong/mathjs#1294]
Hi,
I know it's not this repo but I thought if I create an issue in definitelyTyped it'd not get seen for the trees.

Over at [the parser interface defintion](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mathjs/index.d.ts#L2876) the Parser is missing the getAll() call.

Any chance this can be added?

Thanks,
John

**Comment by josdejong** [comment]
@jfstephe can you create PR or open an issue at DefinitelyTyped for this?

**Comment by jfstephe** [comment]
@josdejong Done [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30138).

**Comment by gwhitney** [comment]
mathjs is now delivering its own types, and it has getAll(). So closing.
