### ISSUE TITLE
A way to handle currency units and number

### ISSUE THREAD

**Issue by stoplion** [josdejong/mathjs#1295]
Is there a way to handle something like `5 EUR + 2` and return 7 EUR?
I'm following the [currency example](http://mathjs.org/examples/browser/currency_conversion.html) and currency [+-/*] currency works great. I'm trying to handle this sort of like [soulver](https://www.acqualia.com/soulver/) does and infers the answer is a currency too. But currently this (`5 EUR + 2`) causes an error.

**Comment by stoplion** [comment]
Gotcha. Sounds like this is a situation where I'd need to preprocess the line and add the `currency unit` to the missing term.

**Comment by josdejong** [comment]
Yes you could do preprocessing if you want to change this behavior. Function `parse` and method `.transform(...)` could be of help there, see docs: http://mathjs.org/docs/expressions/expression_trees.html

It may be tricky though, you have a lot of possible cases which you have to handle to make things consistent, like `5 EUR + 2 + 4`, `5 EUR + (2)`, `5 EUR - 2`, `5 EUR + 2 USD + 4`, etc.
