### ISSUE TITLE
`toTex()` renders tildes instead of multiplication by juxtaposition

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#1299]
## Input
`math.parse('x y z').toTex()`

## Expected output
`x y z`

## Actual output
`x~ y~ z`

**Comment by FSMaxB** [comment]
That is intentional, because `x y z` would render as `xyz` so it would look identical to a variable that is actually named `xyz`.

**Comment by FSMaxB** [comment]
The tilde is a forced whitespace.

**Comment by m93a** [comment]
Ah, alright. I didn't know tilde could be used to force a whitespace. And TexZilla apparently didn't know that either, as it treated the tildes as operators. Could you please point me to any specification mentioning this? I couldn't find any.

Also, the rendering of `bitNot(a)` is wrong then, as it outputs `~\left( a\right)` which means “space and ‘a’ in parens”.

**Comment by ChristopherChudzicki** [comment]
Re 

> Could you please point me to any specification mentioning this? I couldn't find any. (The LaTeX wikibook only mentions \,, \:, \;, \! – couldn't we switch to one of them?)

I generally look for TeX-related answers on tex.stackexchange. Here's a nice post listing all (maybe?) the types horizontal spaces: [What commands are there for horizontal spacing?](https://tex.stackexchange.com/a/74354/27666) The `~` space is [non-breaking](https://en.wikipedia.org/wiki/Non-breaking_space).

Re

> Also, the rendering of bitNot(a) is wrong then, as it outputs ~\left( a\right) which means “space and ‘a’ in parens”.

That does seem like a bug. Maybe open a separate issue for it? It should render as `\~ \left( a \right)`. (`\~` renders an actual tilde.)

**Comment by FSMaxB** [comment]
Yes the incorrect tilde is a bug!
