### ISSUE TITLE
Squared units causing TypeError with BigNumber configured

### ISSUE THREAD

**Issue by zcohan** [josdejong/mathjs#1304]
I'm encountering an error when evaluating units with a power sign (squared units) with BigNumber on.

Example:

```
const math = require('./math.min.js')
math.config({number: 'BigNumber', precision: 64}) //disable big number and the following expression works fine, but with big number on, it fails
math.eval('9.7 meters^2')
```

The error is:

> TypeError: Unexpected type of argument in function pow (expected: number or string or boolean, actual: BigNumber, index: 1)

**Comment by josdejong** [comment]
Thanks for reporting @zcohan . Turns out function `pow` didn't support a combination of `pow(Unit, BigNumber)`, like:

```
math.pow(math.unit('9.7 meters'), math.bignumber(2))
```

Should be fixed now via https://github.com/josdejong/mathjs/commit/5b6863e364f87e6469b577571fc7a64cca3d9222
