### ISSUE TITLE
Add support for ANP calculations

### ISSUE THREAD

**Issue by wjladams** [josdejong/mathjs#1309]
AHP/ANP are a theoretical decision making framework.  I already have an open source python library for performing those calculations at https://github.com/wjladams/pyanp however I know of some folks who would like a javascript library for it.  I was wondering if I could contribute code to this project to support that decision making framework, or if you all feel that a separate project would be a better fit.  Thanks for your time.

**Comment by josdejong** [comment]
Thanks for your suggestion @wjladams . I'm not familiar with ANP calculations, and I'm not sure how widely used/needed it is.

It would be great to have a JavaScript implementation of course. My preference would be to built it as a separate project and integrate it in mathjs.

Looking at npm I see there is a project in this direction, https://github.com/airicyu/ahp, are you aware of that?

**Comment by wjladams** [comment]
@josdejong that makes sense.  I was not aware of that project, but I am looking to implement the more general ANP setup (AHP is the equivalent of trees, whereas ANP allows information feedback where ever).

I will make a standalone library and import the mathjs stuff I may require. 

Thanks for your time

**Comment by josdejong** [comment]
I'll close this issue, I'm not sure if we will ever implement ANP calculations. If there is interest please open a new discussion.
