### ISSUE TITLE
Can't transform function to string

### ISSUE THREAD

**Issue by sashaalesin** [josdejong/mathjs#1311]
How can I transform function to text string?
Example:
`fun = math.eval('f(x) = x^2')`
`fun(2) --> 4`

`fun.toString() -->`
`"function(e,t){return arguments.length===B&&m(e)&&x(t)?S.apply(null,arguments):arguments.length===k&&h(e)&&b(t)?O.apply(null,arguments):arguments.length===I&&d(e)&&w(t)?T.apply(null,arguments):arguments.length===P&&y(e)&&N(t)?_.apply(null,arguments):arguments.length===R&&g(e)&&M(t)?C.apply(null,arguments):arguments.length===U&&v(e)&&E(t)?z.apply(null,arguments):L.apply(null,arguments)}"`

`math.string(fun) -->
"function(e,t){return arguments.length===B&&m(e)&&x(t)?S.apply(null,arguments):arguments.length===k&&h(e)&&b(t)?O.apply(null,arguments):arguments.length===I&&d(e)&&w(t)?T.apply(null,arguments):arguments.length===P&&y(e)&&N(t)?_.apply(null,arguments):arguments.length===R&&g(e)&&M(t)?C.apply(null,arguments):arguments.length===U&&v(e)&&E(t)?z.apply(null,arguments):L.apply(null,arguments)}"`

it seemed to work before

**Comment by josdejong** [comment]
Maybe you mean `math.parse('f(x) = x^2').toString()`?

**Comment by josdejong** [comment]
> it seemed to work before

In which version of mathjs did "it" work?

You can do something like:
```js
const node = math.parse('f(x) = x^2')
const fn = node.eval()
console.log(fn(2)) // 4
console.log(node.toString()) // f(x) = x ^ 2
```

**Comment by sashaalesin** [comment]
ok, thanks
