### ISSUE TITLE
Add fixPrefix as a config option

### ISSUE THREAD

**Issue by bornova** [josdejong/mathjs#1314]
As a feature request, would be nice if we could set `fixPrefix: true` in config to prevent auto conversion of the units.

**Comment by josdejong** [comment]
Thanks for your suggestion. We try to keep the amount of global configuration minimal, and try to pass as much options as possible "locally". Would it help in your case to have `math.unit` extended so you can pass `fixPrefix: true`? 

(You could already create your own helper function to achieve this)

**Comment by josdejong** [comment]
Ah, that's a good point 👍 . I think you're right and that a global setting makes sense. We may have to think about a better name than `fixPrefix` though, maybe something like `fixUnitPrefix`.

**Comment by bornova** [comment]
👍 for `fixUnitPrefix`

**Comment by josdejong** [comment]
Closing this issue in favor of #2738
