### ISSUE TITLE
math.derivative() not calculating partial differentials correctly

### ISSUE THREAD

**Issue by pringon** [josdejong/mathjs#1318]
### Differentiation with respect to x
Expected output: 2x + y
Actual output: 2x

### Differentiation with respect to y
Expected output: x + 1
Actual output: 1

**Comment by josdejong** [comment]
Thanks for reporting this bug!

Help with hunting down this bug would be welcome! Anyone?

**Comment by josdejong** [comment]
I was just looking into this issue and realized that it's not a bug but a misunderstanding: `xy` in the expression `x^2 + xy + y` is not interpreted as an implicit multiplication between `x` and `y` but is interpreted as a variable with the name `xy`. Differentiation works as expected when you change it into an explicit multiplication or put a space between x and y:

```js
math.derivative('x^2 + xy + y', 'x').toString()    // '2 * x'
math.derivative('x^2 + x * y + y', 'x').toString() // '2 * x + y'
math.derivative('x^2 + x y + y', 'x').toString()   // '2 * x + y'
```
For the expression parser there is no way to know whether a string like `xy` is meant as two variables or not (like in the case of `pi`).
