### ISSUE TITLE
Expressions: objects can't be written multi-line

### ISSUE THREAD

**Issue by jean-emmanuel** [josdejong/mathjs#1328]
Looks like the `getTokenSkipNewLine` function could be used [here](https://github.com/josdejong/mathjs/blob/develop/src/expression/parse.js#L1512) to allow multi-line objects. What do you think ?

**Comment by josdejong** [comment]
Wow, good point. Never realized that this isn't supported right now, it would be really useful to allow multi line inside objects.

Anyone interested in creating a PR to improve this?

**Comment by josdejong** [comment]
This issue has been addressed by @GHolk, in v5.4.0 multi-line object contents can be used.
