### ISSUE TITLE
es6 tag template literals expression support

### ISSUE THREAD

**Issue by GHolk** [josdejong/mathjs#1330]
`Math.eval` is a good idea, and in es6 we have tag template literal,
which allow more natural syntax.

before:
```
let A, P, L
/* compute them */
const x = Math.eval(` A' * P * A * A' * L `, {A,P,L})
```

with es6 tag template we can write:

```
let A, P, L
/* compute them */
const x = Math.runTemplate` ${A}' * ${P} * ${A} * ${A}' * ${L} `
```

it is easy to patch this kind of template base on current mathjs:

```
MathJs.runTemplate = function (template, ...variable) {
    const prefix = '_variable'
    const scope = {}
    const expression = template.reduce((previousExpression, nextExpression, index) => {
        if (index == 0) return previousExpression + nextExpression
        else {
            const variableCount = index - 1
            const variableName = prefix + variableCount
            scope[variableName] = variable[variableCount]

            return previousExpression + variableName + nextExpression
        }
    }, '')
    return this.eval(expression, scope)
}
```

maybe i can patch it myself and send you pull request
after i finish my reports and other thing.
this module is a little big, so i need to which file to patch.

**Comment by josdejong** [comment]
Thanks for your suggestion @GHolk . I understand why you would like to do this though don't think the added value/flexibility is worth it. I would like to keep the API as simple and straight as it is right now and not introduce more ways to do the same thing. 

You can of course always create a separate plugin/library to implement this feature and we could probably add it to the downloads page.

**Comment by GHolk** [comment]
a simple evalTag snippet can be import by mathjs, host on gist.
<https://gist.github.com/GHolk/de01600aed974d2e9a61960a0b029d25>

**Comment by josdejong** [comment]
:+1: thanks for sharing @GHolk
