### ISSUE TITLE
BigNumber fraction oddity

### ISSUE THREAD

**Issue by andraaspar** [josdejong/mathjs#1331]
```
> fraction(100/24)
25/6
> config({number:'BigNumber'})
{"epsilon": 1e-12, "matrix": "Matrix", "number": "BigNumber", "precision": 64, "predictable": false, "randomSeed": null}
> fraction(100/24)
7602530730928912/1824607375422939
```

Am I doing something wrong?

**Comment by josdejong** [comment]
Thanks for reporting. I've opened an issue at the fraction.js library, maybe Robert can explain this behavior: https://github.com/infusion/Fraction.js/issues/28.

**Comment by josdejong** [comment]
See the referred issue at Fraction.js for more information, will close this issue now.
