### ISSUE TITLE
Please check if you have this backdoor script installed

### ISSUE THREAD

**Issue by JasonShin** [josdejong/mathjs#1335]
https://github.com/dominictarr/event-stream/issues/115

cheers

**Comment by harrysarson** [comment]
Thanks for flagging. I checked `package-lock.json` and mathjs does not depend on event-stream so we should be all good here. :)

**Comment by josdejong** [comment]
:+1: I also checked the output of `npm list` and `event-stream` is indeed no dependency. Thanks @JasonShin for the reminder.
