### ISSUE TITLE
Unit toSI() uses 'mm' instead of 'm' for small 'ft' values

### ISSUE THREAD

**Issue by BjoernSimon** [josdejong/mathjs#1336]
I am using Math.js Units to parse a string value and always convert it to the SI system to normalize the values. This works very well except for small 'ft' length and 'ft^2' area values. I did not try it for other units as I am assuming this is a generic issue.

**Issue 1:** 
`Unit.parse('0.111 ft^2').toSI()` converts into `'10312.23744 mm^2'`instead of `'0.01031223744 m^2'`

**Issue 2:**
getting the 'unit' from JSON immediately after constructing it e.g. via `Unit.parse(value).toSI().toJSON().unit)` returns `'m^2'` (correct SI unit) instead of `'mm^2'` (the unit it was incorrectly converted to, see issue 1).

Please see example code and output below for details.

```javascript
const math = require('mathjs');  //v5.2.3
math.config({number: 'BigNumber'}); // to change to BigNumbers.
const Unit = math.type.Unit;

function mathjsUnitBug(value) {
    console.log("\nOriginal value:     ", value)
    const unitObj = Unit.parse(value).toSI(); //BigNumber

    const unitJson = unitObj.toJSON();
    console.log("unitJson.unit:      ", unitJson.unit)
    console.log("unitObj.toString(): ", unitObj.toString())
}
```

Results in
```
Original value:      11.1 ft^2
unitJson.unit:       m^2
unitObj.toString():  1.031223744 m^2

Original value:      0.111 ft^2
unitJson.unit:       m^2
unitObj.toString():  10312.23744 mm^2

Original value:      11.1 ft
unitJson.unit:       m
unitObj.toString():  3.38328 m

Original value:      0.111 ft
unitJson.unit:       m
unitObj.toString():  33.8328 mm
```

**Comment by josdejong** [comment]
I think how `toSI()` is implemented right now is that it converts units like `feet` and `inch` to `meter`, but it does still allow using prefixes like `millimeters`, right @ericman314?

**Comment by ericman314** [comment]
Jos, I'm not certain. I don't think the intent was to auto-select the best prefix. This could be a bug.

**Comment by josdejong** [comment]
Looking at the unit tests of `.toSI()` I think it was not intentional behavior and we can consider this a bug:

https://github.com/josdejong/mathjs/blob/638ed7ec839bf1a5968b04cf31e1fa523b1d5197/test/type/unit/Unit.test.js#L1240-L1264

**Comment by josdejong** [comment]
Anyone interested in helping to fix this bug?

**Comment by ericman314** [comment]
I should be able to get to it within a week or two.

**Comment by ericman314** [comment]
Okay it was easier than I thought.

On a similar note, I really dislike the side-effects in `Unit.format`, (or equivalently, `Unit.toString`) in which the units are simplified lazily. It always seems to break things. Also it is in that function that the best prefix is applied, meaning that unless `fixPrefix` is set, the prefix can change whenever `toString` is called on the unit. I'm open to suggestions. I feel like if we can separate the unit calculation logic from the formatting of the unit a little better, these problems might go away. Or at the very least remove the side-effects from `format`.

**Comment by harrysarson** [comment]
>  I really dislike the side-effects in `Unit.format`

I could not agree more

**Comment by josdejong** [comment]
@BjoernSimon this issue should be fixed now in `v5.3.1` thanks to the fix provided by Eric.

@ericman314 would it work if we would create a method `Unit.simplify()` which returns a new, simplified Unit, and when calling `Unit.format()`, basically return `this.simplify().format()`? Or just do this internally in `format`: don't change the unit itself but create a temporary simplified unit?

**Comment by ericman314** [comment]
I think so. Perhaps the right way to approach this is to make Units immutable, and refactor all the methods as necessary. I imagine the API could change significantly so it might be a breaking change.

**Comment by harrysarson** [comment]
Moving towards immutability is a good thing in my book 👍

**Comment by ericman314** [comment]
PR #1344 removes the side-effects.

**Comment by josdejong** [comment]
In the refactoring I'm working on (#71) I smashed quite some times into issues around mathjs functions not being immutable but for example listening for config changes, which makes it impossible to really isolate them and get tree-shaking working, see my comment here: https://github.com/josdejong/mathjs/issues/71#issuecomment-442990327. The refactoring really pushes us towards pure functions, which is great!

**Comment by josdejong** [comment]
I think we can close this issue, it was solved by Eric already.
