### ISSUE TITLE
Move built-in units to their own file

### ISSUE THREAD

**Issue by ericman314** [josdejong/mathjs#1345]
Units.js is very large. In my latest PR I attempted to move the built-in units, base units, prefixes, and aliases into their own files, and use `require` to load them:

```js
const UNITS = require('./units')
```
where units.js contains all the built-in units:
```js
module.exports = {
  meter: { ... },
  ...
}
```

However, this causes new instances of math created using `math.create()` to reuse the same `UNITS` object, so that if I use `createUnit` in one instance, the new unit is added to all other instances as well. What is the preferred way to do this? I can think of a few possibilities but I haven't tested them:

```js
// Shallow copy
const UNITS = Object.assign({}, require('./units'))
```

```js
// Just taking a shot in the dark with this one
const UNITS = load(require('./units'))
```

**Comment by ericman314** [comment]
Sounds like `modular_architecture` will be a great improvement. If I do any work on this I'll push it to that branch.

**Comment by josdejong** [comment]
:+1:

**Comment by josdejong** [comment]
FYI: I've merged `modular_architecture` into `develop` now.

**Comment by ericman314** [comment]
Do you want to try to finish this before releasing V6?

**Comment by josdejong** [comment]
I don't think so, moving the code will not result in a breaking change would it?

**Comment by ericman314** [comment]
It could result in some minor breaking changes, yes. I'm taking the
opportunity to improve some things with the code, and there could be some
corner cases that are different. I am hoping to minimize those changes,
though.

**Comment by josdejong** [comment]
Ah ok. Well, the final v6 is still weeks away. It's both fine if you catch this train or the next. It's ready when it's ready :)

**Comment by ericman314** [comment]
The new library is making good progress. I think we could have a stable API ready in time for v6.

**Comment by josdejong** [comment]
:sunglasses:

**Comment by gwhitney** [comment]
I think this is more or less moot by this point. I think everyone wants eventually to get units from UnitMath, and that it will happen sooner or later. So closing.
