### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by asilinwei** [josdejong/mathjs#1346]
Hi, a problem about performance, see an example:
use `var nativeIsArray = Array.isArray;  nativeIsArray(child)` instead of `Array.isArray(child)`
and use `var nativeMin = Math.min;  nativeMin(oldLen, newLen)` instead of `Math.min(oldLen, newLen)`
is best practice about performance.

**Comment by josdejong** [comment]
Thanks for your input @asilinwei . 

Do you have any concrete benchmarks for mathjs showing that this change would improve performance significantly?

**Comment by ohpyupi** [comment]
Just out of curiosity, I ran a very simple benchmark for @asilinwei proposal. It looks like the proposal is true for the big number of iterations. `nativeIsArray` was ~25% more faster than `Array.isArray`. In detail, for 1000000000 iterations of simple array type checking, the former took ~18878ms while the latter ~15217ms. However, for the small number of iterations, direct use of `Array.isArray` was more performant than `nativeIsArray`. Below is the benchmark result with different number of iterations.

| Iteration  | `Array.isArray`(ms) | `nativeIsArray` (ms) |
| ------------- | ------------- | ---------- |
| 10^3 | 0 | 0 | 
| 10^4 | 1 | 3 |
| 10^5 | 7 | 3 |
| 10^7 | 200  | 157 |
| 10^9 | 18878  | 15217 |

Also, Let me share my test scripts for clarity. Please don't hesitate to leave comment if the benchmark has some flaws. Thanks.
```javascript
const nativeIsArray = Array.isArray;
const testExp = (iteration = 1, cb) => {
	const startTime = Date.now();
	for (let i = 0; i < iteration; i++) {
		cb([]);
	}
	const endTime = Date.now();
	return endTime - startTime;
};
const iteration = 1000000000;
const testATime = testExp(iteration, Array.isArray);
const testBTime = testExp(iteration, nativeIsArray);
console.log(testATime, testBTime); // 18878 15217
```

**Comment by josdejong** [comment]
I think the main flaw of the benchmark is that it's a micro benchmark. You're not testing a real-world piece of code but execution of a single operation in isolation. Only if this particular operation is a bottleneck in a real piece of code, you will see a noticeable difference in practice. Besides that, browser engines optimize a lot so you really have to benchmark real code to know what it does in practice, the performance will not be a summation of the performance of individual operations in most cases (for better or worse).

**Comment by ohpyupi** [comment]
@josdejong Yeah, I agree.

**Comment by josdejong** [comment]
I will close this issue now.

Note that there is a little benchmark section in the project (folder `benchmark`) which you can use when working on performance of specific functions like `det`.
