### ISSUE TITLE
Inaccuracy of functions such as sin(pi) can give wrong results when they are nested in another functions.

### ISSUE THREAD

**Issue by Saikedo** [josdejong/mathjs#1350]
So I noticed that functions such as sin(pi) are not exactly 0 but they are very close to 0. Then I found an issue that says using math.config({number: 'bignumber'}); will make the result of sin(pi) more accurate and the issue was closed. The problem is that expressions such as log(sin(pi)) are returning wrong results and using bigNumber does not fix this issue. Is there any way around this problem? I feel like any equation that involves infinities will have this issue.

**Comment by josdejong** [comment]
Maybe the documentation on rounding errors helps?

http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
http://mathjs.org/docs/datatypes/bignumbers.html#roundoff-errors
http://mathjs.org/docs/datatypes/bignumbers.html#limitations

**Comment by Saikedo** [comment]
This is not much of a help unfortunately since in our program most of the evaluation is being done at once (basically something similar to passing "log(sin(pi))). Now if I wanted to get a result for sin(pi) and round that up then that would work perfectly fine but when I am trying to get a result from the entire equation of log(sin(pi)) I get something -34 instead of -Infinity and I can`t handle this by rounding it up.

**Comment by Saikedo** [comment]
Ah, that is what I was afraid of lol. We are currently using nerdamer every time we encounter pi or e but my JS guy said that nerdamer was not as stable as math.js for some of the calculations and I was wondering if it was possible to get accurate values out of math.js for cases like these.

**Comment by josdejong** [comment]
Yeah, well, this is not an issue related to the library or programming language you use, but a limitation in numerical calculations. Only real solution is algebraic computation.
