### ISSUE TITLE
Solver

### ISSUE THREAD

**Issue by GitterHubber** [josdejong/mathjs#1358]
Is a solver for math.js anywhere on the horizon?

I may be using the wrong term but I mean something similar to his.
`V = I * R`
And If I do somethng like
Solve for I
and it should return the result for `V / R`
I know that some Python libraries do this like SymPy, also Qalculate! does it?

Do you think its worth integrating this kind of thing in math.js?

**Comment by josdejong** [comment]
Yes I would love to have a solver @GitterHubber 

See #38, let's continue any discussion there and close this issue as a duplicate.
