### ISSUE TITLE
feature: create a utility function to apply a function over the rows or columns of a matrix

### ISSUE THREAD

**Issue by bnlcas** [josdejong/mathjs#1359]
It would be helpful to have a utility function that would apply a function over the rows or columns of a matrix. This would let developers vectorize their code, and efficiently transform their data. Also it would make it simpler to extend the functions of math.js to support calculation across multiple dimensions. A similar feature can be found in R's [apply](https://www.rdocumentation.org/packages/base/versions/3.5.1/topics/apply) function.

**Comment by bnlcas** [comment]
@josdejong My apologies for the delay - I recently started a new job. I have a [branch with this feature implemented](https://github.com/bnlcas/mathjs/tree/create_apply_utility_Request_1359). I noticed that the utility functions (deepMap, deepForEach, reduce,...) do not have any tests or documentation. This seems reasonable since they are not publicly exposed, but please let me know if some tests should be included. Otherwise, if this feature is fine on its own, I can submit a PR.

**Comment by josdejong** [comment]
@bnlcas no problem at all, this is open source, no dead lines or anything :) 

Yes this `apply` function would be great to have!

In general I like to have the unit tests as low-level as possible, so possibly we could move some tests from the public functions to these internal utility functions, and focus the unit tests of the public functions on just the part of the logic that is added there. On the other hand we should be pragmatic, most important is _that_ the code is tested.

**Comment by bnlcas** [comment]
Yeah, more test coverage is always a good idea, so I added a unit test for this function. In addition to this I have checked it out, and the apply function is giving the correct results when it is used with some basic statistics functions (mean, sum, var, std). I'll submit a PR for this.

**Comment by gwhitney** [comment]
As `apply()` of a function along some dimension of a matrix is in mathjs now, it appears this has been resolved but never closed. Doing so now.
