### ISSUE TITLE
math.multiply not accepting a function as the second parameter

### ISSUE THREAD

**Issue by vickylance** [josdejong/mathjs#1367]
I want to initialize a matrix with random values in it. So I looked and I didnt have built in function to generate a random initialized matrix, but not only that when I tried to create a random initialized matrix using math.ones and multiply it with math.random it generated a matrix with same random values in all places so I tried giving the input as `() => Math.random()` but it looks like the multiply function does not get function as second parameter. I feel like it will be a very useful feature if the func parameter gets the current value in the array/matrix and depending upon the value we can return a number that has to be multiplied against that value in the matrix.
```
      return math.multiply(
        math.ones([
          idx === 0 ? this.input : layer.neurons,
          this.layers[idx + 1].neurons
        ]),
        () => Math.random()
      ) as math.Matrix;
```
This is what i tried doing.
I would atleast expect a Random function in matrix to return a randomly initialized matrix in values of 0-1 for the given size. Like in this - http://sylvester.jcoglan.com/api/matrix.html#random

**Comment by josdejong** [comment]
@vickylance have you tried the random function of math.js?
```js
math.random([2, 3])
```

**Comment by vickylance** [comment]
@josdejong Ok the math.random is working as expected. But having a custom callback function to return a value depending upon current iteration value would be nicer, eg:- like lets say the value in matrix is less than 5 multiply that element by 10 else multiply by 8.

**Comment by josdejong** [comment]
Yes definitely! I think the `apply` function proposed by @bnlcas in #1359 will be a good fit for these situations.

**Comment by vickylance** [comment]
Yes that would be really useful
