### ISSUE TITLE
mathjs have native random features ?

### ISSUE THREAD

**Issue by djmisterjon** [josdejong/mathjs#1368]
Hi, do your math libs include some random math methods?
Something like this ?
http://numbers.github.io/random.html
I take fast look in the docs, all good feature for math are the, but seem missing random features?

Am working on a projet with a lot of procedural computing, and am searching a libs that make math and randomiser more easier.

thanks you

**Comment by josdejong** [comment]
@djmisterjon math.js has a `random` function but no advanced functionality in that area. You can of course import the functions from numbers.js into math.js, see http://mathjs.org/examples/import.js.html
