### ISSUE TITLE
Use esm to avoid need for transpiling scripts on node

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1371]
I think #1129 was a great thing for mathjs and am excited to see #1319 when it is ready. However, there is just one thing that I have found (slightly) jarring when working with the new mathjs. Every time I make a change to mathjs and wanna test it in the REPL I have to run babel to see my changes.

For node, the only thing that babel needs to do is convert es modules to common js ones. I was wondering if it would be possible to use https://www.npmjs.com/package/esm to avoid the need to transpile mathjs on node?

If folk are keen I can investigate if this is possible.

**Comment by josdejong** [comment]
Would definitely be interesting to do some experimentation :)

I think in general we will keep this transpile step, but moving to .esm can be a next step after the refactoring of #1319 (making good progress there btw).

**Comment by josdejong** [comment]
I think it can be closed. If there are still issues, please reopen.
