### ISSUE TITLE
problem with math.js precise

### ISSUE THREAD

**Issue by phoenixor** [josdejong/mathjs#1382]
in some case, i need to calculate 5000.11*100, my expected result is 500011, but i got 500010 !!
My code is like this:
`math.multiply(math.bignumber(5000.11), math.bignumber(100))`

**Comment by josdejong** [comment]
@phoenixor when I execute your example, it outputs the expected result `500011`. Can you give an example which gives a wrong result?

**Comment by phoenixor** [comment]
@josdejong i found the problem, it is my fault. My code`s  return type is 'bignumber' and i need a number for my DB. I wrap the code with math.number() and it is done. Thanks for your work

**Comment by josdejong** [comment]
:+1:
