### ISSUE TITLE
-a^0=1 not -1

### ISSUE THREAD

**Issue by husayt** [josdejong/mathjs#1384]
Try for example `-9^1` and you will get `-1`. Correct answer is `1`

**Comment by bornova** [comment]
I believe the expression `-9^0` is interpreted as `-(9^0)` by mathjs, giving the exponent priority. This gives you `-1` as it should.   If you change your expression to `(-9)^0`, you will get the answer you are looking for, which is `1`.

**Comment by husayt** [comment]
@bornova I agree. Excellent argument. Current behavior is correct then
