### ISSUE TITLE
Derivative of cos^2(x) returns a wrong result

### ISSUE THREAD

**Issue by Otomakan** [josdejong/mathjs#1386]
## Context

Hi ! I have been playing around with the math.derivative function and here is a little issue I found. I hope it helps! Thanks for your work

## PROCESS
I'm using the latest version through the CDN
https://cdnjs.cloudflare.com/ajax/libs/mathjs/5.4.1/math.min.js

math.derivative('cos^2(x)','x')

## Expected result
-2cos(x)+sin(x)
which could be simplified as −sin(2x)

## Current result
cos^2

**Comment by josdejong** [comment]
Thanks for reporting @Otomakan. I think the confusion here is `cos^2(...)` which is not an existing function, and is evaluated totally different then you expect, as a regular exponent: `pow(cos, 2)` which is not what you mean.

You could defined this function yourself, like:

```
cos2(x) = (1/2) * (cos(2*x) + 1)
```
and then use the `cos2` function.

**Comment by Otomakan** [comment]
I love the convoluted way you defined cos2(x) indeed:
`cos2x = cos(x)*cos(x)`
Works too. Sorry I should I have thought about. Thank you

**Comment by josdejong** [comment]
Ah, yes. `cos2x = cos(x)*cos(x)` may be better after all since it's easier to understand the meaning. Anyway, good to hear this works for you.
