### ISSUE TITLE
How to selectively remove whitespace in `.parse()` or `toString()`

### ISSUE THREAD

**Issue by rcavezza** [josdejong/mathjs#1398]
Hi - I want to be able to eliminate whitespace from the formulas after I run the following code. 

```
const node = math.parse(mathExpression);

const options = {parenthesis: 'auto', implicit: 'show'}

node.toString(options)
```

This will get me something like `1 + 3 + 5`, but I want to be able to parse it as `1+3+5`. I also go in and map variable names to nodes, so the reason I can't remove all whitespace is because I need to end up parsing this in a format like `3+Name That Goes Here+25`. 

I was thinking there was a way to add `options` to `math.parse` to remove whitespace or there was an optional handler I could throw into `options` for toString`, but I haven't been able to find any documentation or workarounds. 

Any help here would be appreciated. I went into the code searching `toString` for everything, and was not able to come away with anything helpful.

**Comment by josdejong** [comment]
There is no built in option to get output without whitespace but removing whitespace should be very easy with a regexp:

```js
'1 + 2 + 3'.replace(/\s/g, '') // '1+2+3'
```

**Comment by josdejong** [comment]
ah sorry I read now you do not want to remove spaces from variable names. How is it that you have variables with spaces in the first place? Do you have object property names with spaces or so?

**Comment by rcavezza** [comment]
Hey @josdejong - It appears that I'm looping through and changing the `node.name` variable to another string with spaces using custom symbols. Your comment made me consider an alternate way to achieve what I'm trying to do. I'm going to a search and replace after `toString`. Your comment helped me get there. I'm going to close this issue as a nonissue. Thanks!

**Comment by josdejong** [comment]
:+1:
