### ISSUE TITLE
Cannot implicitly convert a number with >15 significant digits to BigNumber (value: 1.4142135623730951). Use function bignumber(x) to convert to BigNumber.

### ISSUE THREAD

**Issue by siriuscxj** [josdejong/mathjs#1402]
I using code below:

math.config({
  number: 'BigNumber'
});
math.subtract(deviation, math.sqrt(2));

and I got this error:Cannot implicitly convert a number with >15 significant digits to BigNumber (value: 1.4142135623730951). Use function bignumber(x) to convert to BigNumber.
I think probably because the result of math.sqrt(2) is >15 digits, and this maybe a bug, I thought mathjs will automatic convert result when using BigNumber.

**Comment by josdejong** [comment]
I think the confusion is in that mathjs doesn't automatically turn the `2` in `math.sqrt(2)` in a BigNumber when you have configured to use big numbers. That is only the case in the expression parser and other places where strings are parsed into a numeric value. 

What will do the trick is:
```js
math.subtract(deviation, math.sqrt(math.bignumber(2)))
```
or 
```js
const scope = { deviation }
math.eval('deviation - sqrt(2)', scope)
```
