### ISSUE TITLE
Question - Get defined and undefined scope from expression

### ISSUE THREAD

**Issue by sebastianfelipe** [josdejong/mathjs#1414]
Hi,

I would like to make an expression, but also, get the variables in there. Parser has a method called getAll, to get every defined variable into an expression, but I would like to get every variable, defined and undefined inside an expression. For example, if the expression is (x + y)/z -> get ['x', 'y', 'z'] as variables or as scope {x: undefined, y: undefined, z: undefined} or null. Is there a method that I could use to get that result or similar?

Thanks,
Sebastián.

**Comment by josdejong** [comment]
Yes you can extract all symbols in an expression. If you parse an expression using `math.parse`, you get a node tree having methods like `filter`, `map`, `traverse` to iterate over it and for example find all symbol nodes. See docs (I think you want to use the `filter` method):

http://mathjs.org/docs/expressions/expression_trees.html

**Comment by sebastianfelipe** [comment]
Perfect! Haven't seen that function. I made a recursive function to solve that, but I think filter is better. How can you choose symbols (not functions) only? For example if a apply a log, then it appears it were a SymbolNode and I don't need it, just need the variables.

**Comment by sebastianfelipe** [comment]
I think I have the answer, using the second parameter from filter called "path" it is possible to discriminate if it is "fn" or not. Thanks!

**Comment by josdejong** [comment]
Yes indeed, or you can check whether the `parent` is a `FunctionNode`.
