### ISSUE TITLE
missing white wpace with not operator wen using toString()

### ISSUE THREAD

**Issue by AlexDmr** [josdejong/mathjs#1418]
Ex:
n = math.parse( "not toto" )
n.toString()

// Return: "nottoto"
// Should return "not toto"

**Comment by josdejong** [comment]
Thanks for reporting @AlexDmr. Let's double check for other named operators too.

Anyone interesting in fixing this issue?

**Comment by josdejong** [comment]
Fixed via https://github.com/josdejong/mathjs/commit/d9deed993de7abba61ac1b04dbfbf245ade54822 (not yet published)

**Comment by josdejong** [comment]
The fix is published now in `v5.6.0`

**Comment by AlexDmr** [comment]
Great :) and thanks for this very useful library !
