### ISSUE TITLE
How do I treat constants symbolically?

### ISSUE THREAD

**Issue by Kreijstal** [josdejong/mathjs#1422]
Is math.js a CAS? When executing Pi+2 for example I get the evaluation of the expression, however I only want it to be evaluated when I tell it to, into arbitrary precision, is this something mathjs supports?

Thanks

**Comment by josdejong** [comment]
With `parse` you can parse your expressions without evaluating them. You can do operations on your parsed expression (transform, simplify, derivative, ...) and after that evaluate it. 

See docs:
http://mathjs.org/docs/expressions/parsing.html#parse
http://mathjs.org/docs/expressions/expression_trees.html
