### ISSUE TITLE
Suggestion: better simplify by factoring out common terms

### ISSUE THREAD

**Issue by Kreijstal** [josdejong/mathjs#1423]
Simplify is not factoring out common terms which would help the project develop the goal to create a solver.

For example
`simplify(parse("k*(a*k+b)/k^4"))` gets simplified but `simplify(parse("(a*k^2+b*k)/k^4"))` stays the same.

**Comment by javazen** [comment]
I tried adding a rule 
```
     'n1*c1^c2 + n2*c1 -> c1*(n1*c1^(c2-1) + n2)'
```
but that also did not make it work.  I don't know if I got the syntax on the rule correct, though.

**Comment by josdejong** [comment]
Would be nice the improve `simplify` in this regard. 

@javazen Something like that may work. Shouldn't the constant `c1` in your rule be a variable (say `n3`)?

**Comment by josdejong** [comment]
This has been addressed now in `v10.2.0`
