### ISSUE TITLE
mathjs@5.6.0 - Math.js blocks React Native production bundling

### ISSUE THREAD

**Issue by jackmew** [josdejong/mathjs#1433]
This is the issue related to #797 .
React Native Debug bundling is no problem. 
After I try to release React Native Project to TestFlight. It just crash when it start.
The error message is only show` Cannot convert a symbol to a string`.
![screen shot 2019-03-07 at 5 52 54 pm](https://user-images.githubusercontent.com/6193983/54007074-07e9a600-419b-11e9-8282-a05029335bea.png)

I can't make sure what happen, so I tune the build configuration. 
Understanding the process of xcode build and xcode run script build phase -  react-native-xcode.sh.

After that, I definitely know the problem is caused by jsbundle. So I just build the release main.jsbundle and remove part of the code and test... test again. Finally, If I remove `import * as math from 'mathjs' `, it just can work on release/production.

I installed npm install --save mathjs for the latest version. And Try it again. there is no luck..
Then I try npm install --save mathjs@3.9.3. Due to [Jonrh](https://github.com/josdejong/mathjs/issues/797#issuecomment-282009813) already test it. [mathjs@3.9.3 by josdejong](https://github.com/josdejong/mathjs/issues/797#issuecomment-281801363).

And it worked !!!!!

But I still don't know what happened after mathjs@3.9.3. 
I just want to noted it for developers who face the same problem.

react-native: 0.53.6
react: 16.2.0

**Comment by harrysarson** [comment]
Would it be possible to try using the last 4.x release of mathjs (i.e. `npm install --save mathjs@4)?

**Comment by josdejong** [comment]
@jackmew thanks for reporting. I don't have a ReactNative setup right now so I can't easily test this myself. 

I suppose you're using the latest version of mathjs. Can you try the following? 
```js
import * as math from 'mathjs/dist/math.js'
```
If this gives the same issue, at least we should get a more informative error and in that case I would love to know the line of code where the error occurs, that may give a clue.

**Comment by josdejong** [comment]
Who can help out here and do some debugging?

**Comment by adteague** [comment]
@josdejong I came across this same issue after having utilized math for the same function on our server (NodeJs). I received the following error message:

`undefined is not an object (evaluating '_mathjs.default.fraction')`

Taking your advice about using `import * as math from 'mathjs/dist/math.js'` solved the issue. Thanks!

**Comment by josdejong** [comment]
I'm not sure if this is still an issue. If still an issue, please open a new discussion
