### ISSUE TITLE
One page docs

### ISSUE THREAD

**Issue by bichotll** [josdejong/mathjs#1436]
Hi there.
I have recently discovered your library.

It looks good. There is one big issue tho, finding the methods is pretty difficult.
It would be nice if the docs were like http://mikemcl.github.io/decimal.js/ or http://pixijs.download/release/docs/index.html

Those are really easy to manage.

Cheers

**Comment by josdejong** [comment]
Thanks for your input Jaume. There is definitely room to improve the docs, there was an other discussion in this regard, shall we continue any discussion there to keep it focused? 

See: #1323

If you look for a list with all functions you may like this page: https://mathjs.org/docs/reference/functions.html
