### ISSUE TITLE
Missing BigNumber constants

### ISSUE THREAD

**Issue by hsmyers** [josdejong/mathjs#1440]
Minimally there should exist math.bignumber.PI and math.bignumber.E. My irritating workaround is Mathematica N[PI,100] cut and paste. If you can't afford the real thing, get a Raspberry-Pi! I realize you are not the actual authors of this extension, but most of your users are exposed to this package not through them but rather through you.

Think of there being a big strikethrough here. First I discovered 'Constants' and second Decimal.js's Pi. Between the two I was able to define what I needed. 

`x = new math.bignumber(1)
p = new math.bignumber(-1)
Complex.PI = new Complex(p.acos(-1), 0)
Complex.E = new Complex(x.exp(), 0)
{"re":"3.141592653589793238462643383279502884197169399375105820974944592","im":"0"} {"re":"2.718281828459045235360287471352662497757247093699959574966967628","im":"0"}
`
which of course works just fine!

**Comment by josdejong** [comment]
I'm not going to reply to such rude, negative comments.

If you're really interested in having a discussion about this try again in a new issue in a constructive way.
