### ISSUE TITLE
Apology for rude comments about Constants…

### ISSUE THREAD

**Issue by hsmyers** [josdejong/mathjs#1441]
I apologize sincerely for the rudeness of my remarks about the lack of Constants. I'm more than old enough to refrains from saying anything while upset and have no excuse at all. If you glance at the second half where I made a feeble attempt to both explain and apologize, you will see that I was able to come to a resolution. A resolution I should have achieved before complaining as I did. As I said, please draw a line through 1440.

**Comment by josdejong** [comment]
Thanks Hugh, apologies accepted :+1: I've deleted the issue, no need to stay online forever.

As for bignumber constants: when you configure to use bignumbers, you get a bignumber PI and E directly:

```js
math.config({ number: 'BigNumber', precision: 64 })

console.log(math.pi.toString()) // 3.141592653589793238462643383279502884197169399375105820974944592
console.log(math.e.toString())  // 2.718281828459045235360287471352662497757247093699959574966967628
```
and if needed you can wrap them into a Complex number with `math.complex(math.pi)`, though most functions in mathjs automatically convert to a complex number: 

```js
math.config({ number: 'BigNumber', precision: 64 })
math.eval('e ^ (pi * i)') // Complex -i (with a round-off error)
```

**Comment by josdejong** [comment]
ah, what may be important to know too: Complex.js uses numbers internally. There are some plans/wishes to extend it such that it can use BigNumbers for `re` and `im`, but right now you simply lose any bignumber precision when converting to a Complex number.

**Comment by hsmyers** [comment]
Thank you. And thanks for the additional information! Oddly enough I'm
writing my own extended precision complex class using BigNumbers so of
course, all of this is of great interest to me. I need them for the usual
suspect—fractals. It's the kind of programming I enjoy the most both
fractals and writing EP code.

**Comment by josdejong** [comment]
sounds fun :)

I will close this issue now, feel free to reopen if there is more to discuss.
