### ISSUE TITLE
custom bundle webpack license missing

### ISSUE THREAD

**Issue by zhy0** [josdejong/mathjs#1442]
I noticed that using custom bundling as described [here](https://mathjs.org/docs/custom_bundling.html) with webpack the license/copyright notice of mathjs is missing in the produced bundle.

I tried including `lib/header.js` like so
```javascript
const core = require('mathjs/core');
const math = core.create();
math.import(require('mathjs/lib/header'));
math.import(require('mathjs/lib/type/matrix'));
```
but the `@date` and `@version` param seem missing. Is this the right way to do it?

Thanks, Yang

**Comment by josdejong** [comment]
The placehoders @date and @version in `header.js` file are only resolved when creating bundles `math.js` and `math.min.js`. It shouldn't be too hard replacing them in `/lib/header.js` too. 

Anyone interested in fixing this?

**Comment by kevjin** [comment]
Hi @josdejong, I would be interested in fixing this issue. Should be able to submit a PR in a day or two, thanks! :)

**Comment by josdejong** [comment]
:+1: thanks Kevin!

**Comment by kevjin** [comment]
@josdejong just submitted the above PR, thanks!

**Comment by josdejong** [comment]
Thanks Kevin, appreciated!

**Comment by josdejong** [comment]
@kevjin we hope to release a beta version of mathjs@6.0.0 soon, which has a large breaking change for custom bundling: it will come with support for tree-shaking out of the box. Would you be interested in giving it a try as soon as it's in beta? That would be very helpful. See #71 for more information.

**Comment by kevjin** [comment]
@josdejong Absolutely! Just read the discussion and am looking forward to the new changes. Will definitely give it a try :)

**Comment by josdejong** [comment]
:+1: will keep you posted
