### ISSUE TITLE
US and metric cooking units

### ISSUE THREAD

**Issue by charmanjoe** [josdejong/mathjs#1449]
Some units are in metric while others are in US units. For example:
math.unit(1,"cup").toNumber("tablespoon")
15.772546666666665
From [here](https://en.wikipedia.org/wiki/Cup_(unit)), a US legal cup is 240 mL, while a US customary cup is 236.5882365 mL.
From [here](https://en.wikipedia.org/wiki/Tablespoon), a metric tablespoon is 15 mL, while a US tablespoon is approximately 14.8 mL.
From my example, it seems like it uses a US customary cup and a metric tablespoon.
Please include the option for US units.

**Comment by josdejong** [comment]
Hm yes you're right, we should change the value of `tablespoon` to ~14.8 mL to make it consistent with cup. And probably create new units for the other variants of the units.

**Comment by charmanjoe** [comment]
[Here](https://en.wikipedia.org/wiki/United_States_customary_units#Fluid_volume) is a list of the United States Customary Units.

**Comment by josdejong** [comment]
Who's interested in fixing the these units? 

It will be a breaking change so we'll have to schedule it for `v6`

**Comment by edgarjrg** [comment]
I haven't found anything that solves the US system, Imperial, Metric differences of `cup`, `Tbs` etc well, same issue happens in [measuring-cup](https://github.com/cgatno/measuring-cup/issues/4). The need of

1. Transform between systems (US, Imperial, Metric, etc)
1. Transform between units (`cup` of sugar -> `g` of sugar)

Are very common use cases for cooking, (the 2nd point is a total different issue, but would be amazing to have something to do it)

**Comment by ericman314** [comment]
I've been working (very slowly) on migrating all the units functions from math.js into their own library. Would you mind raising this issue over at https://github.com/ericman314/UnitMath/issues ? That way I will not forget about it. I imagine that this might be something we could address with a configuration option to choose between the various types of cups, etc, or have units with suffixes such as `cupImperial`, with an alias of `cup`, depending on the configuration option.

**Comment by gwhitney** [comment]
Since this is recorded over at UnitMath, closing it here (as it is more likely to be resolved over there than here, I'd say).
