### ISSUE TITLE
math.format 'engineering' not allowed, causes exception

### ISSUE THREAD

**Issue by hsmyers** [josdejong/mathjs#1459]
In version 5.4.0 
this code:

    `t = math.format(div(G.four,G.fwidth),{notation: 'engineering'})`

where `G.four` and `G.fwidth` are both `bignumbers` and `div` is a short form of `math.divide`, raises this exception:

**Error: Unknown notation "engineering". Choose "auto", "exponential", or "fixed".**

The workaround is to use `'exponential' `instead. Although to nit-pick, your use of precision differs by one (`format` needs 4 where `toExponential` needs 3) which should be noted in the documentation? 

At any rate, this came as a surprise, not an upset as this was hardly the worst I ran into today. I continue to use math.js with great success and have already suggested it to two other programmers climbing down the rabbit hole along with me (fractals)! Thanks muchly for the incredible work put in for this very well done API/Library.

**Comment by josdejong** [comment]
This should be fixed now in `v5.9.0`

**Comment by hsmyers** [comment]
Thanks, kind sir, I appreciate it!
