### ISSUE TITLE
node.toHTML() for factorial is not correct

### ISSUE THREAD

**Issue by hanguokai** [josdejong/mathjs#1465]
math.js version 5.8.0

The result of `math.parse('5!').toHTML()` is !5 (`<span class="math-operator math-unary-operator math-righthand-unary-operator">!</span><span class="math-number">5</span>`) , but it should be 5!

**Comment by josdejong** [comment]
Thanks for reporting! I've fixed the issue via c155eb20d7084d57e92f5eff379c26aa4b058212.

**Comment by josdejong** [comment]
This should be fixed now in `v5.9.0`

**Comment by hanguokai** [comment]
:thumbsup: :tada:
