### ISSUE TITLE
Cannot subtract variables that are BigNumbers with unit

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#1467]
```
TypeError: Unexpected type of argument in function subtract (expected: Unit or Array or DenseMatrix or SparseMatrix or Matrix, actual: BigNumber, index: 1)
```

https://jsfiddle.net/d72vwzxp/1/

**Comment by josdejong** [comment]
You try to evaluate `300 mm - 0`, a Unit minus a number (both have a BigNumber value). That's not possible, both should be a unit, ie. `300 mm - 0 mm`.

**Comment by m93a** [comment]
Oh, cool, I was in a hurry yesterday, so I didn't notice that. I'm closing the issue then! Sorry to bother you!

**Comment by m93a** [comment]
But maybe a better error message would be fine.
