### ISSUE TITLE
Unexpected type error with math.subtract and bignumbers

### ISSUE THREAD

**Issue by hsmyers** [josdejong/mathjs#1470]
With the expression:

`t = math.subtract(G.ImMax, G.ImMin)`

I get this error:

 **TypeError: Unexpected type of argument in function subtract (expected: Array or DenseMatrix or SparseMatrix or Matrix, actual: Object, index: 1)**

Since both operands are bignumbers, I do not understand the failure. I note also that the error message is omitting bignumbers while the documentation on subtract includes them This adds to my confusion.

**Comment by josdejong** [comment]
@hsmyers how can I reproduce this issue? Do you have a small code example?

**Comment by hsmyers** [comment]
@josdejong I missed your comment. I'll work up a short example and post shortly. Again sorry—I'll slap my Gmail upside o' the head ;)

**Comment by hsmyers** [comment]
I write in coffeescript which generates javascript. At any rate, I've attached all. Strip off the ridiculous .txt I've used to defeat the GitHub attachment bug. Should you wish to re-compile, my associated command line is '`coffee --map --bare --compile --output lib/ ./`'

[tj.coffee.txt](https://github.com/josdejong/mathjs/files/3123101/tj.coffee.txt)
[tj.html.txt](https://github.com/josdejong/mathjs/files/3123102/tj.html.txt)
[tj.js.map.txt](https://github.com/josdejong/mathjs/files/3123103/tj.js.map.txt)
[tj.js.txt](https://github.com/josdejong/mathjs/files/3123104/tj.js.txt)

**Comment by hsmyers** [comment]
Here are the files needed. Strip off the .txt extension. If you need to recompile here is the command line 'coffee --map --bare --compile --output lib/ ./`'

[tj.coffee.txt](https://github.com/josdejong/mathjs/files/3123117/tj.coffee.txt)
[tj.html.txt](https://github.com/josdejong/mathjs/files/3123118/tj.html.txt)
[tj.js.map.txt](https://github.com/josdejong/mathjs/files/3123119/tj.js.map.txt)
[tj.js.txt](https://github.com/josdejong/mathjs/files/3123120/tj.js.txt)

**Comment by hsmyers** [comment]
Sorry, wrong button…

**Comment by josdejong** [comment]
I'm still not sure how to reproduce your issue. Can you strip the issue you have to a bare-bone example like:

```js
const G = {
  ImMax: ...,
  ImMin: ...
}
const t = math.subtract(G.ImMax, G.ImMin) // error this or that
```

**Comment by hsmyers** [comment]
Yes, I can and will later this morning. I should still be asleep but
foolishly checked my email and saw your response…

**Comment by hsmyers** [comment]
Here it is:

<!DOCTYPE html>
> <html>
> <head>
> <meta charset='utf-8'>
> <meta http-equiv='X-UA-Compatible' content='IE=edge'>
> <title>tj2</title>
> <meta name='viewport' content='width=device-width, initial-scale=1'>
> </head>
> <script type='text/javascript' src='..\math.min.js'></script>
> <script>
> testBox = class testBox {
> constructor(n) {
> this.tn = math.bignumber(n);
> }
>
> };
> var x = math.bignumber(5.5);
> var a = new testBox(x);
> var b = JSON.stringify(a, null, 2);
> var y = JSON.parse(b);
> console.log('x:', x);
> console.log('a:', a);
> console.log('b:', b);
> console.log('y:', y);
> </script>
> <body>
> </body>
> </html>
>

What goes in comes back changed. A possible fix would be to change the
math.bignumber.prototype.toJSON to a string version of the original?

**Comment by josdejong** [comment]
If you want to serialize and deserialize for example a bignumber, you have to use the reviver when parsing, see docs: https://mathjs.org/docs/core/serialization.html

In your example I guess `testBox` will not properly revive because it's not a class known by mathjs.

**Comment by hsmyers** [comment]
Excellent! I just tested it by replacing the 'parse' line with

var y = JSON.parse(b, math.json.reviver);
>
>
Worked exactly as I would want. Problem solved, pull the switch 😎👍

p.s. for my needs, all that is required is that all bignumbers are
preserved in and out an this is the case with the simple modification.

**Comment by josdejong** [comment]
:+1:
