### ISSUE TITLE
feature: fraction lack of toTex

### ISSUE THREAD

**Issue by alvachien** [josdejong/mathjs#1472]
It seems that fraction doesn't support toTex.

**Comment by josdejong** [comment]
Can you give an example of what you mean?

**Comment by alvachien** [comment]
@josdejong Thanks for the reply.

For instance, you create a fraction as following (https://mathjs.org/docs/datatypes/fractions.html):
`let testnumber = math.fraction('0.(3)');`

Is it possible to export testnumber with Tex format (via method toTex) which supported by math.parse?
`const node = math.parse('sqrt(x/x+1)');
node.toTex()      // returns '\sqrt{ {\frac{x}{x} }+{1} }'
`
Like following:
`
let testnumber = math.fraction('0.(3)');
testnumber.toTex() // return '\1 \over 3'
`

**Comment by josdejong** [comment]
The `Fraction` class has a method `toLatex()`. This is not created by mathjs but built-in with the fraction library used by mathjs: https://github.com/infusion/Fraction.js. Does that address your issue?

**Comment by gwhitney** [comment]
mathjs supports toTex() only on expressions, not arbitrary mathematical values. I don't see that changing. Closing as "works as intended".
