### ISSUE TITLE
Unexpected joules in watt hour calculations

### ISSUE THREAD

**Issue by zcohan** [josdejong/mathjs#1481]
I'm having trouble understanding math.js's behaviour in regard to watt hour units. I'd expect to be able to work directly with kilowatt hours or watt hours, however they sometimes are displayed in joules implicitly:

Example:

> 1 kWh = 1 kWh (expected)
> 1 kilowatt hour = 3.6 MJ (unexpected).

**Comment by ericman314** [comment]
The way math.js chooses a display unit when using the `auto` unit system is that it gives preference to units that you have used before. The best way to describe it is with an example:

```js
console.log(math.eval('1 kilowatt * 1 hour').toString())
console.log(math.eval('1 kWh').toString())
console.log(math.eval('1 kilowatt * 1 hour').toString())
```
Which outputs:
```
3.6 MJ
1 kWh
1 kWh
```

Before you use the `kWh` unit explicitly in the second statement, math.js does not know whether you prefer `MJ` or something else.

We don't like side effects but we haven't been able to come up with a better way to do it yet.

**Comment by zcohan** [comment]
Thanks Eric, that's indeed quite surprising. Can I ask what the reasoning was behind the decision to take previous calculations into account when evaluating an expression? 

What would be the downside to math.js only doing a unit conversion in `auto` when the conversion is explicitly requested?

**Comment by ericman314** [comment]
We've had lots of issues regarding making the unit formatting more configurable. I've opened another issue so we can collect all the ideas in one place: #1483
