### ISSUE TITLE
Feedback on v6

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1511]
I haven't had a chance to dig too deep into version 6 yet but:

 a) it looks great!
 b) There are a couple of points of feedback I do have.

1. The repo contains quite a lot of things. 
  Whilst searching for the correct files to include to take advantage of the modular architecture, I was a bit overwhelmed by the number of files hanging around. 
  There are:
    *  core.js (depreciated)
    *  index.js
    *  number.js
    *  es5/index.js
    *  es5/number.js
    *  es6/index.js
    *  es6/number.js
    *  src/bundleAny.js
    *  src/factoriesAny.js
    *  src/factoriesBundle.js
    *  src/factoriesNumber.js
    *  src/index.js
    *  src/core/core.js
    *  src/plain/bignumber/arithmetic.js 	
    *  src/plain/bignumber/index.js
    *  src/plain/number/arithmetic.js 	
    *  src/plain/number/index.js
    *  possibly more that I haven't found

2. It is not very clear where the documentation is. 
    This is partly (or mainly?) due to the fact that the website is still at v5 so maybe this is not a problem after all.
    However, I struggled to find explanations of what I needed to do to (for example) get a bundle of only complex number functions.
    The examples are great but there is not so much explanation of what they are examples of (I mainly had to go off the files name).

---

There may be more I find as a explore the new version :) Hope this helps!

**Comment by josdejong** [comment]
Thanks for your feedback @harrysarson, that really helps. 

The docs aren't updated yet, sorry (see ["Still to do"](https://github.com/josdejong/mathjs/issues/71#issuecomment-488089077)). The best starting point is looking at [the short explanation in the history](https://github.com/josdejong/mathjs/blob/develop/HISTORY.md#2019-04-31-version-600-beta1), and [the examples](https://github.com/josdejong/mathjs/tree/develop/examples) (see also ["How to try the new stuff?"](https://github.com/josdejong/mathjs/issues/71#issuecomment-488089077)). Does that help?

**Comment by harrysarson** [comment]
The HISTORY.md explainers are very helpful! 

> Does that help?

Yes.

---

My mistake was I intuatively reached for `import { something } from 'mathjs/something';` whereas I now see that all imports are from `'mathjs'` and treeshaking works it's magic 👍

**Comment by josdejong** [comment]
:dancing_women:
