### ISSUE TITLE
format in engineering notation with precision < 3 can produce incorrect results

### ISSUE THREAD

**Issue by jstafford** [josdejong/mathjs#1512]
Numbers such as 100e3, which is a perfectly valid engineering notation number, will be formatted as 10e3 when the precisions is set to 2. Formatting a number should never change its value. This is a general bug whenever the engineering notation would require a significand with more digits than the specified precision.

Example code:
```
const mathjs = require('mathjs')

const testEngFormat = () => {
  const testNumber = 100e3
  console.log(`testNumber ${testNumber}`)
  const formattedNum = mathjs.format(testNumber, {notation: 'engineering', precision: 2})
  console.log(`formattedNum ${formattedNum}`)
  const equal = testNumber === Number(formattedNum)
  console.log(`equal ${equal}`)
}

testEngFormat()
```

**Comment by josdejong** [comment]
Thanks for reporting Jason, this is definitely a bug. There is something really weird going on:

```js
console.log(math.format(100e3, {notation: 'engineering', precision: 2})) 
// output: "10e+3" 
// expected: "100e+3"

console.log(math.format(math.bignumber(100e3), {notation: 'engineering', precision: 2}))
// output: "1.0e+2e+3"
// expected: "100e+3"
```

**Comment by josdejong** [comment]
Proposed a fix in #1513

**Comment by josdejong** [comment]
This issue should be fixed now in `v5.10.1`. @jstafford can you give it a try?

**Comment by jstafford** [comment]
I did a yearn upgrade and reran my test app. I get the following error:
```
/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/core.js:94
      throw new Error('Factory object with properties `type`, `name`, and `factory` expected');
      ^

Error: Factory object with properties `type`, `name`, and `factory` expected
    at load (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/core.js:94:13)
    at Object.factory (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/type/matrix/utils/getArrayDataType.js:4:17)
    at load (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/core.js:106:28)
    at Object.factory (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/type/matrix/DenseMatrix.js:18:26)
    at load (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/core.js:106:28)
    at resolver (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/function/import.js:220:24)
    at _importFactory (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/function/import.js:256:27)
    at mathImport (/Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/function/import.js:74:7)
    at /Users/jason/code/µscratch/math-js-bug/node_modules/mathjs/lib/core/function/import.js:77:9
    at Array.forEach (<anonymous>)
```
I don't know why this is happening. I will investigate further.

**Comment by jstafford** [comment]
Well, I can't figure it out. I did a ```yarn remove mathjs``` and a ```yarn add mathjs``` and got the same problem. Verified that the version of mathjs is 5.10.1. Looked into the code and sure enough getArrayDataType doesn't have type and name like the error message says. But it doesn't seem like object isFactory is actually checking for either of those. (Though the comments do indicate that it is).  Looked at the code on GitHub, and none of the files in the stack trace appear to have been changed in months.

**Comment by josdejong** [comment]
I messed up `v5.10.1` yesterday, sorry for that. See https://github.com/josdejong/mathjs/issues/1516#issuecomment-493652418 for details.

Can you give `v5.10.2` a try and see if it fixes the original issue of the `engineering` notation?

**Comment by jstafford** [comment]
I've tested v5.10.3 with our use case and it fixes the problem as far as I can see. Thanks for jumping on this so quickly.

**Comment by josdejong** [comment]
:+1: good to hear
