### ISSUE TITLE
Optimizing for sparse matrices?

### ISSUE THREAD

**Issue by bfitzp** [josdejong/mathjs#152]
I am using mathjs for a quantum walk simulator and in some cases I have to deal with massive sparse matrices. My application becomes incredibly slow in these cases.

Is there any possibility of optimizing for these kinds of matrices similar to the way they are supported by, say, MatLab or Octave?

http://www.mathworks.co.uk/help/matlab/ref/sparse.html
http://www.gnu.org/software/octave/doc/interpreter/Sparse-Matrices.html

**Comment by josdejong** [comment]
Support for sparse matrices has been implemented by @rjbaucells , enjoy!
