### ISSUE TITLE
Redefinition of SI units and physical constants

### ISSUE THREAD

**Issue by ericman314** [josdejong/mathjs#1521]
On May 20, 2019, new definitions of SI base units came into effect. This means that some physical quantities which before were determined experimentally, are now defined exactly. We should check the physical constants to ensure the values are correct.

**Comment by josdejong** [comment]
:+1:

**Comment by harrysarson** [comment]
I believe that no numerical values changed. However, it is possible that wikipedia is not the source of _all_ knowledge.

**Comment by ericman314** [comment]
Here are some I found:

Constant | Old (mathjs) | New (2019)
-|-|-
planckConstant | 6.626069311e-34 | 6.62607015e-34
elementaryCharge | 1.60217656535e-19 | 1.602176634e-19
boltzmann | 1.380648813e-23 | 1.380649e-23 
avogadro | 6.0221412927e23 |  6.02214076e-23

There are a few others as well. I can get a PR together tonight or tomorrow if no one else can.

**Comment by gwhitney** [comment]
Since all four of the above now reflect the "New" column, I am going to assume this is done. Closing.
