### ISSUE TITLE
Nuxt + mathjs = Pre-generated OK, Client OK, server side (Node.js) KO

### ISSUE THREAD

**Issue by anat** [josdejong/mathjs#1531]
Hi everybody,

I'm trying to get my project working on server side (dev) using Nuxt + Math.js.

It actually works on Client (chrome) side and using "nuxt generate" (npm run generate) but it is not working on SSR (Debug).

:heavy_check_mark: Client
:heavy_check_mark: Generated (nuxt generate)
:japanese_goblin: SSR (dev)

## First issue

`No access to property "foo"`

Inside mathjs the function called isPlainObject return false

Here is the function with the debug I added :
node_modules/mathjs/lib/utils/customs.js
```
function isPlainObject(object) {
  console.log("customs.js object.constructor === Object")
  console.log(object.constructor === Object);
  return _typeof(object) === 'object' && object && object.constructor === Object;
}
```
**Result show : false**

```
Inside my pages/index.vue I have following code : 
 console.log("customs.js object.constructor === Object")
 console.log(scope.constructor === Object);
```

**Result show : true**

## Second issue
`Value has unknown type. Value: [object Object]`

I tried to debug this thing, but with no success, the problem is in here :
https://github.com/josdejong/typed-function

I'm first trying to figure out for the 1st bug. It seems that they are related (type checking error)

### Reproduction link
Here is a mini project to recreate the issues.
https://github.com/anat/bug-mathjs-nuxt/

### Steps to reproduce
```
npm i
npm run dev
```

- Go to localhost:3000

- See bug

Test other case, replace {{ case1() }} by {{ case2() }}

### What is expected ?
Should not crash but do the addition in both case1 & case2

**Comment by josdejong** [comment]
Thanks for your detailed report and project which replicates the issue @anat .

I can imagine this has to do with the `scope.constructor === Object` check. Could it be that the code runs in a different JS envionment, similar to having a JavaScript running in an isolated iframe?

The `getSafeProperty` method is there to prevent security issues, we should be really careful making changes/fixes there.

**Comment by gwhitney** [comment]
Does there remain any actionable issue here years later, or can this be closed?

**Comment by josdejong** [comment]
I'll close this issue now. Please reopen if this is still an issue.
