### ISSUE TITLE
Units Like `gallon / min` Cannot Be Created?

### ISSUE THREAD

**Issue by naseemali925** [josdejong/mathjs#1545]
Hi,
I am trying to use the library to create new units. But units like `gallon / min` on creation throw error? 

Any help would be appreciated.

**Comment by ericman314** [comment]
Try `gallon / minute`. `min` is actually the minimum function.

**Comment by naseemali925** [comment]
Hi @ericman314 `gallon / minute.min` Doesn't Works.
Could you suggest something that works?

**Comment by ericman314** [comment]
Can you provide a small code sample?

**Comment by naseemali925** [comment]
@ericman314 Code Sample
```js
const unit ="gallon/minute";
mathjs.createUnit(unit);
```

**Comment by ericman314** [comment]
Thanks @naseemali925. The first argument to `createUnit` is the name of the new unit, and it has to be alphanumeric. The second argument is the definition of the new unit.

Like this:

```js
math.createUnit('gpm', '1 gallon/minute')
let x = math.unit('1 L/minute').to('gpm')
console.log(x.toString()) // 0.26417203728418465 gpm
```

**Comment by naseemali925** [comment]
Thanks @ericman314 This Helped A Lot. Solved My Issue.
