### ISSUE TITLE
Unexpected cubed inches in unit calculation result

### ISSUE THREAD

**Issue by zcohan** [josdejong/mathjs#1546]
These unit expressions evaluate correctly:
```
8 litres/minute * 3 minutes = 24 litres // correct!
24 litres * 4 kg = 96 litres kg // correct!
```

But performing them both in one operation produces a result in terms of kg cubed inches:

```
8 litres/minute * 3 minutes * 4 kg = 5858.2794330943 kg inch^3 // incorrect!
```

I was expecting `96 litres kg`.

I tried bracketing, but it doesn't change the result:
```
(8 litres/minute * 3 minutes) * 4 kg = 5858.2794330943 kg inch^3 //incorrect!
```

**Comment by ericman314** [comment]
Thanks @zcohan for reporting. This is yet another consequence of the helpful (?) auto unit system. We recently split off `Unit.js` into its own [library](https://github.com/ericman314/unitmath) and made some major modifications to make all the operations on units deterministic. We're just working on getting it integrated into Math.js. We're hoping to have it ready for v7.

**Comment by xxczaki** [comment]
@josdejong @ericman314 I'm experiencing something similar:

```
A = 0.42 m^2
U = 2.14 m
Q = A * U
```

The expected result is `0,8988 m^3`, but I seem to get `54,848.1412 inch^3` 😢 I tried using `parser.evaluate`, as well as `evaluate` with a `new Map()` as a scope - the problem occurs in both cases. Surprisingly, I wasn't able to reproduce the issue on the "Demo" section of https://mathjs.org/.

**Comment by ericman314** [comment]
Indeed it is strange that it doesn't happen in the demo section. Doing arithmetic with units in the "auto" unit system causes side effects and is full of bugs. This is likely what's responsible for the unexpected behavior. 

You can try the undocumented `setUnitSystem` to change the system from "auto" (the default) to something more predictable, like "si". I know this doesn't really answer the question, but it's the best suggestion I have. https://github.com/ericman314/unitmath will fix a lot of these types of bugs, I just wish I had more time to work on it.

https://github.com/josdejong/mathjs/blob/28333172819fd9741c07d30c6fcde31809ee7606/src/type/unit/Unit.js#L2951-L2961

**Comment by josdejong** [comment]
@xxczaki stupid question, but are you using the latest version of mathjs?

**Comment by xxczaki** [comment]
@josdejong Yes, using version 10.0.0.

**Comment by xxczaki** [comment]
> Indeed it is strange that it doesn't happen in the demo section. Doing arithmetic with units in the "auto" unit system causes side effects and is full of bugs. This is likely what's responsible for the unexpected behavior.
> 
> You can try the undocumented `setUnitSystem` to change the system from "auto" (the default) to something more predictable, like "si". I know this doesn't really answer the question, but it's the best suggestion I have. [ericman314/unitmath](https://github.com/ericman314/unitmath) will fix a lot of these types of bugs, I just wish I had more time to work on it.
> 
> https://github.com/josdejong/mathjs/blob/28333172819fd9741c07d30c6fcde31809ee7606/src/type/unit/Unit.js#L2951-L2961

Thanks for the suggestion, but I have no idea how to access `setUnitSystem` - I'm importing math.js like so:

```ts
import {...} from 'mathjs';
```

**Comment by xxczaki** [comment]
> Indeed it is strange that it doesn't happen in the demo section. Doing arithmetic with units in the "auto" unit system causes side effects and is full of bugs. This is likely what's responsible for the unexpected behavior.
> 
> You can try the undocumented `setUnitSystem` to change the system from "auto" (the default) to something more predictable, like "si". I know this doesn't really answer the question, but it's the best suggestion I have. [ericman314/unitmath](https://github.com/ericman314/unitmath) will fix a lot of these types of bugs, I just wish I had more time to work on it.
> 
> https://github.com/josdejong/mathjs/blob/28333172819fd9741c07d30c6fcde31809ee7606/src/type/unit/Unit.js#L2951-L2961

I had some setup issues at first, but I managed to get things to work. The problem doesn't occur anymore - thank you for the suggestion!

**Comment by josdejong** [comment]
That's good to hear. 

Will close this issue now. Like Eric mentioned, there are tricky cases with the "auto" system. These will be adressed with `MathUnit`, which is still a work in progress.
