### ISSUE TITLE
bignumber() result is in an array?

### ISSUE THREAD

**Issue by raydlevel5** [josdejong/mathjs#1547]
Hey!  I'm dealing with a database that has a decimal datatype, precision of 38 and a scale of 30.  Long story short, the precision of the number is 38.

I can't find where it says in the documentation that `bignumber()` will return an array.  I expected an actual string or number.

*Is* an [array] of the broken-up number the intended response?  Am I supposed to concatenate the response as a string?  Does JavaScript just not support long numbers?

```
// desired result
// formula = (0.505*193/190)*230/260)/1.1032
// 0.411334674542662787386271222800



math.evaluate( ((0.505*193/190)*230/260)/1.1032 )

// response
// 0.4113346745426628



math.bignumber(math.evaluate((     (0.505*193/190)*230/260)/1.1032     ))

// response is an object that contains an array with the result broken into chunks
// {constructor: ƒ, s: 1, e: -1, d: Array(3)}
// here's the array:
// 
// d:  [4113346, 7454266, 2800000]

```

**Comment by ericman314** [comment]
> ```math.bignumber(math.evaluate((     (0.505*193/190)*230/260)/1.1032     ))```

This first performs the arithmetic using ordinary JavaScript floating-point numbers which have a precision of about 16 digits, then constructs a `BigNumber` from that result, which is why the last several digits are all zero. The array in the returned object is internal to `BigNumber`: you just have to call `toString()` on the `BigNumber` object.

Try:

```js
const { create, all } = require('mathjs')

const config = {
  number: 'BigNumber',
  precision: 38
}

const math = create(all, config)

math.evaluate('((0.505*193/190)*230/260)/1.1032').toString() // 0.41133467454266278738627122276601304119
```

**Comment by raydlevel5** [comment]
I'm having issues trying to replicate this.... Will post something substantial for you soon.

**Comment by raydlevel5** [comment]
I should note that I'm using plain-old JavaScript.  Also, I'm kind of entry level here.  I recognize the ES6 `const`  options, but I don't know exactly how to use it.

I also do not know how to create a separate instance of Math.js --- like, how could I instansiate a specific instance of Math.JS so that *not every* output has the BigNumber configuration?

![image](https://user-images.githubusercontent.com/21373144/59879028-c5c62800-9377-11e9-9278-1a75ce48ae83.png)

**Comment by ericman314** [comment]
Here's an ES5 version that creates a new configuration named `bigmath` and also keeps the original configuration:

```js
var math = require('mathjs')

var config = { 
  number: 'BigNumber',
  precision: 38
}
var bigmath = math.create(math.all, config)

console.log(bigmath.evaluate('((0.505*193/190)*230/260)/1.1032').toString())
console.log(math.evaluate('((0.505*193/190)*230/260)/1.1032').toString())
```

Outputs:
```
0.41133467454266278738627122276601304119
0.4113346745426628
```

And another note, in v6 of Math.js, you can't alter the global config using `math.config`, you have to create a new instance using `math.create` first.

**Comment by raydlevel5** [comment]
Oh man, I'm sorry I'm so dense --- I must be doing something terribly wrong! :(

i really appreciate your help, by the way...

What is `require`?   What am I doing wrong?

![image](https://user-images.githubusercontent.com/21373144/59880321-c1e7d500-937a-11e9-8a0c-a7049f184ac3.png)

**Comment by ericman314** [comment]
Oh I'm sorry, the code I posted was for Node.js. If you're working in the browser it's a little bit different. Here's a working example: https://codepen.io/anon/pen/gNgjWm?editors=1010

**Comment by raydlevel5** [comment]
It's because I omitted the single quotes around the expression :(

https://codepen.io/anon/pen/jjypjd?editors=1010

That you for showing me how to instantiate a new instance of math.js, and the config option, and how to get the long number.
