### ISSUE TITLE
Uncaught TypeError: while calculating matrices using lusolve

### ISSUE THREAD

**Issue by Sanjit1** [josdejong/mathjs#1549]
When I try to solve Matrices using lusolve, then I get an error telling me that there is a type error, even though I am using Arrays.
I am including some code, that I am using:
`var button = document.getElementById("enter");`
`var R1Html = document.getElementById("R1");`
`var R2Html = document.getElementById("R2");`
`var R3Html = document.getElementById("R3");`
`var T1Html = document.getElementById("T1");`
`var T2Html = document.getElementById("T2");`
`var T3Html = document.getElementById("T3");`
`var AHtml = document.getElementById("A");`
`var BHtml = document.getElementById("B");`
`var CHtml = document.getElementById("C");`

`button.onclick = function(){`
    `var R1 = parseFloat(R1Html.value);`
    `var R2 = parseFloat(R2Html.value);`
    `var R3 = parseFloat(R3Html.value);`
    `var T1 = parseFloat(T1Html.value) + 273.15;`
    `var T2 = parseFloat(T2Html.value) + 273.15;`
    `var T3 = parseFloat(T3Html.value) + 273.15;`
    `if((R1!=R2)&&(R1!=R3)&&(R2!=R3)&&(T1!=T2)&&(T1!=T3)&&(T2!=T3)){`

        `var M1 = [`
            `[1,ln(R1),cb(ln(R1))],`
            `[1,ln(R2),cb(ln(R2))],`
            `[1,ln(R3),cb(ln(R3))]`
        `];`

        `var M2 = [1/T1,1/T2,1/T3];`

        `var M3 = math.lusolve(M1,M2);`

        `CHtml.innerHTML = M3[2];`
        `BHtml.innerHTML = M3[1];`
        `AHtml.innerHTML = M3[0];`

    `}`

    `function cb(n){`
        `return n*n*n;`
    `}`

    `function ln(n){`
        `Math.log(n,Math.E);`
    `}`
`};`

This is the error that I got:
`math.js:10288 Uncaught TypeError: Unexpected type of argument in function subtract (expected: Array or DenseMatrix or SparseMatrix or Matrix, actual: number, index: 1)`
    `at Z (math.js:10288)`
    `at D (math.js:10503)`
    `at subtract (math.js:10506)`
    `at o (math.js:5472)`
    `at DenseMatrix (math.js:5511)`
    `at lup (math.js:10506)`
    `at Array, Array | Matrix (math.js:16352)`
    `at Object.lusolve (math.js:10506)`
    `at HTMLButtonElement.button.onclick (calibrator.js:37)`
`Z @ math.js:10288`
`D @ math.js:10503`
`subtract @ math.js:10506`
`o @ math.js:5472`
`DenseMatrix @ math.js:5511`
`lup @ math.js:10506`
`Array, Array | Matrix @ math.js:16352`
`lusolve @ math.js:10506`
`button.onclick @ calibrator.js:37`
Here is some more information:
The Matrix equation should be:
M1*M3=M2
And if you want to test the code, then working variables would be:
R1 = 25000;
R2 = 10000;
R3 = 4000;
T1 = 5;
T2 = 25;
T3 = 45;
And the resulting vars should be:
A = 0.002108508173112706
B = 0.00007979204726779947
C = 6.535076314649418e-7

**Comment by Sanjit1** [comment]
The above error was showing when I used math.min.js. When I switched to math.js, then I got a different error for the same code.

`math.js:32207 Uncaught TypeError: Unexpected type of argument in function lusolve (expected: Array or DenseMatrix or SparseMatrix or Object or Matrix, actual: undefined, index: 0)`
    `at createError (math.js:32207)`
    `at generic (math.js:32729)`
    `at Object.lusolve (math.js:32744)`
   ` at HTMLButtonElement.button.onclick (calibrator.js:37)`

**Comment by josdejong** [comment]
I tried to reproduce your issue, and with the variable values you list and I get an `M1` containing undefined and NaN values. Your custom `ln` function doesn't return its result, which I think is causing the issue.

**Comment by Sanjit1** [comment]
Hmmm. You are right. After I fixed that my code works! Thanks. Can't believe I got stuck on that!
