### ISSUE TITLE
getAll returns non-native data types

### ISSUE THREAD

**Issue by koosvanderkolk** [josdejong/mathjs#1555]
When I run this code using mathjs' evaluate function:

```javascript
my_mathjs_parser.evaluate("myArray = [1,2,3,4,5];");
```

and then retrieve the variables using mathjs' getAll function:

```javascript
var scriptResultVars = my_mathjs_parser.getAll();
```

I expect scriptResultVars.myArray to be a JavaScript Array.

```javascript
scriptResultVars.myArray; // expected value: [1,2,3,4,5]
```
 Nevertheless, I do get an object:

```javascript
scriptResultVars.myArray; // value is: {"mathjs":"DenseMatrix","data":{"mathjs":"DenseMatrix","data":[1,2,3,4,5],"size":[5]},"size":{"mathjs":"DenseMatrix","data":[5],"size":[1]}}`
```

Probably this is by design, but (at least for me :-)) it would be more convenient to return 'normal' JavaScript data types. Another option would be to add this info to the get/getAll function documentation. An even better option would be add a boolean flag to getAll, e.g. returnJavascriptTypes.

**Comment by josdejong** [comment]
By default, the expression parser parses matrices as a `DenseMatrix`. You can change this using configuration `{matrix: 'Array'}`, see docs: https://mathjs.org/docs/core/configuration.html

**Comment by koosvanderkolk** [comment]
Dear Jos,

Thanks for the quick response, I did not know of the 'matrix' option!

> matrix. The default type of matrix output for functions. Available values are: 'Matrix' (default) or 'Array'. Where possible, the type of matrix output from functions is determined from the function input: An array as input will return an Array, a Matrix as input will return a Matrix. In case of no matrix as input, the type of output is determined by the option matrix. In case of mixed matrix inputs, a matrix will be returned always.

Does this setting affect other functions in MathJS? In other words: should I check all my existing mathjs-scripts to see if they still work?

**Comment by koosvanderkolk** [comment]
Additon: I think I should also set the 'number' config option, to get what I want (true Javascript data types)

**Comment by josdejong** [comment]
There are a few functions like `zeros` and `ones` which return output based on the config setting `matrix`. You may also want to configure `predictable: true` to prevent for example `sqrt(-4)` from returning a Complex number. 

Well... just checkout the docs and configure to match your needs.
