### ISSUE TITLE
Discussion: codi.vim integration and soulver features

### ISSUE THREAD

**Issue by slavaGanzin** [josdejong/mathjs#1564]
[Codi.vim](https://github.com/metakirby5/codi.vim) is an interactive interpreter interface for vim.

![codi](https://user-images.githubusercontent.com/1011721/60875984-a9652f00-a243-11e9-86b9-6acb472c09f0.gif)

I created a pull-request to run mathjs in codi:
https://github.com/metakirby5/codi.vim/pull/112

[Soulver](https://soulver.app/) is an interactive editor calculator for Mac OS.

Basically codi + mathjs is superior to soulver. However mathjs cli lacks some easy to implement features:

1. Comments: `#Just ignore lines`

2. An argument (like --no-strict) to ignore undefined symbols:
```
16e3 $ / 5 people
>>> Error: Undefined symbol people
```
may just return: 3200 $

3. Common shortcuts for order in numbers (SI notation). We all know scientific notation is superior, but when you think about money it's 15k, and not 15e3

4. Parse percent symbol: `30% = .3`

5. Built-in currency converter, like [one in examples](https://mathjs.org/examples/browser/currency_conversion.html.html)

6. Human variable names: `monthly rent = 1000 $`. 
```
Parsing: Everything before '=' or 'is' should be considered as variable.
And then: monthly rent * 12 month = 12000$
```
Of course, I'm not talking about copying all stuff from soulver. But all features I enumerate are easy to implement and gives huge boost in productivity. I'm open for a discussion and understand that this features are far from your main focus.

Thanks for awesome project!

**Comment by ericman314** [comment]
So if I understand right you want to be able to make more customizations to the CLI interface, through the use of command line arguments or perhaps through running a setup script? What about pre- or post-processing the input/output outside of the mathjs cli? Would that work for your use case?

**Comment by slavaGanzin** [comment]
It will work with comments, parsing percents and SI notation. But isn't this desirable features for mathjs too? That's what I'm asking in a first place

With variables parsing (cases 2 and 6) it certainly wouldn't work: how will wrapper know what can and what can not be interpreted?

Although currency parser should be integrated in mathjs to work properly.

**Comment by josdejong** [comment]
Interesting idea Slava! 

1. Comments are already supported, exactly like you mention, starting with a `#`
2. That's sounds like a wildcard for a unit or so. I don't fully understand how that would work.
3. You can output the results like you want, you can use `math.format`, or create your own formatter.
4. The `%` symbol is already used for modulus, it's not possible to also use it for percentage. See #304
5. Integrating a currencies in mathjs itself involves doing http requests, having a valid key for a service providing the actual rates, regularly refreshing the rates, etc. This is not something that should be part of mathjs itself (which is a static, universal library), it's application specific how you want to handle this.
6. Interesting, it indeed reads very nicely to allow spaces in variable names. It does conflict though with implicit multiplication (`a b` will evaluate to `a * b`). Maybe you could do some smart preprocessing here, replacing the space in a variable name with an undercore or so and then parse it with mathjs.

**Comment by slavaGanzin** [comment]
1. Comments
 ```
> #asdasdsd
undefined
```
Why undefined? It should be null (like: nothing was evaluated) and not printed at all :)

2. A wildcard unit can work as:
```js
2 hands + 2 hands = 4 hands //without pluralization of course: here unit is "hands" and not "hand"
2 banana * 2 = 4 banana
```
So basically if something is in equation on units position but cannot be parsed as unit, this pseudo-unit should be created and treated as regular one.

Let's parse it (in pseudo code):
```
10 people hour / 10 people

NUMBER UNDEFINED_SYMBOL HOUR DIVIDE NUMBER UNDEFINED_SYMBOL
```

```js
if (!args.strict) {
  for (symbol in UNDEFINED_SYMBOLS) {
   createUnit(symbol)
  }
}

Reevaluate:
> 10 people hour / 10 people
1 hour
```
And `--strict` should be by default.

3. I was talking about internal [SI prefix](https://en.wikipedia.org/wiki/Metric_prefix) parsing. And I found it's already done in mathjs. So `15k$` would be parsed to `15,000 $` if `$` would be defined as unit.

Thanks for pointing to `math.format`!

4. I think @bornova solution is awesome. Maybe add his code and enable it with argument? It's feasible solution: if you add to cli `--handle-percentages` you already know what your doing and if not it just works as expected by most.

5. Good point. 
 - Is there any plugin system in mathjs?
 - Is there a way to handle currency conversion in wrapper and leave only calculation for mathjs?

6. Explicit multiplication can be done only if `a` and `b` was defined:
```
> a * b
Error: Undefined symbol a
> a  b
Error: Undefined symbol a
```

And interestingly it has some caveats too:
```
> a = 1
a = 1
> a  b
1 b
> a * b
1 b
# and not "Undefined symbol b" cause be is parsed as "bit"
```

But if we can provide a mechanism to long variable names definition it will just work, like:
```js
bad mouses = 3
//implicitly: new math.expression.node.SymbolNode('bad mouses')
bad mouses / 2 good cats
// implicitly: new math.expression.node.SymbolNode('good cats')
> 1.5 bad mouses / good cats
```

Yeah, I know "it's easy to innovate but hard to implement". And there are caveats, for sure. :)

**Comment by josdejong** [comment]
1. :joy: yeah well we can argue about whether it should return `null` or `undefined`, that's a big topic in JavaScript world. Anyway it's returning `undefined` in mathjs.
2. I get the idea. This may lead to ambiguity though. @ericman314 do you think something like this could work out nicely? 
3. :+1:
4. We don't have plans to implement percentages in mathjs. If you want to use it you'll have to change the behavior of the parser yourself with post/preprocessing or hacking into the code itself.
5. mathjs is quite extendable, you can import your own functions, do mixing and matching of functionality. The currency example is a nice demo I would say? 
6. Yes you have to define variables `a` and `b` before you can evaluate. It was just an example. The variable `b` is indeed defined already since it's a unit. Spaces in variable names will lead to ambiguities. Like your example `10 people hour / 10 people`: should that be parsed as an implicit multiplication between `people` and `hour`, or is this a single variable `"people hour"` containing a space? Again, I do not think it's a good idea to support variable names containing spaces, but you're free to build some preprocessing enabling this for your application.

**Comment by slavaGanzin** [comment]
2 and 6:
If something can be parsed like 'hour' it should be parsed and after that all unknown symbols can be transformed into units/variables if --no-strict argument is passed.

**Comment by ericman314** [comment]
2. I would catch the undefined symbol error, parse the error text, and use `createUnit` to create the unit in question, then reprocess the input. How do to that from the CLI, I'm not sure, you would have to make a wrapper for the mathjs CLI or something.

**Comment by josdejong** [comment]
@slavaGanzin mathjs first performs a parse+compile step an after that an evaluation step. At parse time, it is not known what variables are defined, that is only known during evaluation.

**Comment by slavaGanzin** [comment]
> I would catch the undefined symbol error, parse the error text, and use createUnit to create the unit in question, then reprocess the input. How do to that from the CLI, I'm not sure, you would have to make a wrapper for the mathjs CLI or something.

Seriously? So it's easier for me to write wrapper that magically understands what should be defined as symbol using mathjs as black box oracle, than for you to write: map(createUnit, unknown_symbols). 
Whatever

I'll close this. I understand your attitude. Don't bother

**Comment by josdejong** [comment]
Mathjs is indeed so flexible that you can adjust it to your needs. The behavior you're looking for does conflict with the existing behavior of mathjs, so we cannot solve this in mathjs itself. You can adjust the behavior to your needs, but you'll have to put in a bit of effort yourself by writing a small wrapper around it.

**Comment by xxczaki** [comment]
I recently built an application called [Parsify Desktop](https://parsify.app/). Is was inspired by several different apps, like Soulver and it uses Math.js underneath :smile:

**Comment by josdejong** [comment]
That looks very neat Antoni! Thanks for sharing.

**Comment by Yohannfra** [comment]
Hi guys, I know it's an old thread but I ended up making a vim plugin to use soulver3  directly in vim/nvim. 

You can find it here: https://github.com/Yohannfra/soulver3.vim
