### ISSUE TITLE
Proposition: Units should be printed in explicit form

### ISSUE THREAD

**Issue by slavaGanzin** [josdejong/mathjs#1568]
Hello

For explicitness and to prevent ugly errors of units misuse I propose to use long unit names in output:

now:
```
> 1b
1 b
> 1 m
1 m
```

after:
```
> 1 b
1 bit
> 1 m
1 meter
```

**Comment by ericman314** [comment]
Thank you for the suggestion. This could indeed be done via a configured option. Would you mind raising this issue over at https://github.com/ericman314/UnitMath/issues? We are working on migrating the unit functions there.

**Comment by slavaGanzin** [comment]
Moved to: https://github.com/ericman314/UnitMath/issues/19
