### ISSUE TITLE
Mathjs undefined  in ng serve prod

### ISSUE THREAD

**Issue by Toso82** [josdejong/mathjs#1581]
I Use mathjs 6.0.3 on my Angular 8 application. The strange i notice that function evaluate it is undefined on ng serve prod. I Import like:

```TS
import * as math from 'mathjs';
```
It coud be something in import optimization .  If i use this work well.

```TS
import { create, all } from 'mathjs';
const math = create(all);
```
Any idea while?

**Comment by josdejong** [comment]
Have you also tried the following?

```js
import { evaluate } from 'mathjs';
```

**Comment by Toso82** [comment]
Hi @josdejong  i'm just try to use 
```TS
import { evaluate } from 'mathjs';
```

but give:
```console
evaluate(2+3);
VM118:1 Uncaught ReferenceError: evaluate is not defined
```
The strange do this just on compile release

**Comment by josdejong** [comment]
I've created a small Angular 8 + mathjs 6 demo that works fine. Maybe this demo can help you find what's going on in your own Angular setup?

Angular + mathjs demo
https://stackblitz.com/edit/angular-mathjs-demo?file=src%2Fapp%2Fapp.component.ts

**Comment by Toso82** [comment]
Hi @josdejong  thanks for example i try to download this. I update @angular/core @angular/cli because it is old ok this is work well in ng serve but if u try ng serve --prod  not work 

You can try and find this here:

https://github.com/Toso82/angular-mathjs-test

I thinks this is strange majbe some optimization or during package for release not include library.

**Comment by Anexo** [comment]
Hi @Toso82 

I am also building an Angular 8 app+ mathjs. It is working fine on ng serve.

Just as you, when I build the app with ng build, I see an error, but in my case, it is different than yours:

Error: Function multiply missing in provided namespace "math"

I am importing the library like this: 

`import { evaluate } from 'mathjs'`

And using it like:

`volumen = evaluate(csv[object], scope);`

Where you able to solve it? Thanks in advance.

**Comment by josdejong** [comment]
@Toso82 running `ng serve --prod` with [your example product](https://github.com/josdejong/mathjs/issues/1581#issuecomment-515761368) gives me the following error (also with the recently published `mathjs@6.0.4`:

```
ERROR TypeError: "Cannot convert 16 to type "undefined"; valid output types are number, BigNumber, Fraction"
    Sl numeric.js.pre-build-optimizer.js:67
    ...
```

When running `ng build` and opening the generated application, all works fine though, so this is probably not a blocking issue?

I have no clue where this can come from, nor whether it is an issue originating in mathjs or in angular. Any help figuring this out will be welcome, I will not have time for it any time soon (and I have zero knowledge of Angular which also doesn't help).

**Comment by Toso82** [comment]
@josdejong  Hi try now update with new version of  `mathjs@6.0.4`  also `@angular/cli@8.2.0` `@angular/core@8.2.0`  `typescript@3.5.3` and now seams work well with `ng serve --prod` if you want to try i update my example.

You can try and find this here:

https://github.com/Toso82/angular-mathjs-test

The problem maybe there is in angular compiler or latest typescript version fix this.

**Comment by josdejong** [comment]
That's good news! I think we can close this issue then?
