### ISSUE TITLE
Question: how to add math.round into custom bundle

### ISSUE THREAD

**Issue by handoyo** [josdejong/mathjs#1587]
Hi,

i want to be able using math.round function in my code?

Currently this is my custom bundle file:

```js
import {
    create,
    fractionDependencies,
    addDependencies,
    formatDependencies,
    matrixDependencies,
    multiplyDependencies,
    roundDependencies,
} from 'mathjs'

const config = {
    // optionally, you can specify configuration
}

// Create just the functions we need
const { fraction, add, format, matrix, multiply, round } = create({
    fractionDependencies,
    addDependencies,
    formatDependencies,
    matrixDependencies,
    multiplyDependencies,
    roundDependencies
}, config)
```

Which file should i import in order to be able to use the math.round function?

Thanks for the guidance.

**Comment by josdejong** [comment]
I'm not sure what you mean. If you only need `round`, all you have to do is 

```js
const { round } = create({ roundDependencies })
```

**Comment by handoyo** [comment]
I have tried it, but when i use math.round(), i get an error says:

`Uncaught TypeError: math.round is not a function`

**Comment by josdejong** [comment]
@handoyo can you extend your code example above to show how you try to use the created function `round`? How can I reproduce the error you get?

**Comment by handoyo** [comment]
This is my testing code:

`console.log(math.round(math.number(math.to(math.unit('14 ft'), 'ft'), 'ft')),2);`

**Comment by josdejong** [comment]
Can you share an example of creating your custom bundle and using the function round created in this bundle?

**Comment by handoyo** [comment]
index.js: 

    import {
    create,
    fractionDependencies,
    addDependencies,
    formatDependencies,
    matrixDependencies,
    multiplyDependencies,
    roundDependencies,
    } from 'mathjs'

    const config = {
    // optionally, you can specify configuration
    }

     // Create just the functions we need
    const { fraction, add, format, matrix, multiply, round } = create({
     fractionDependencies,
     addDependencies,
     formatDependencies,
     matrixDependencies,
     multiplyDependencies,
     roundDependencies
    }, config)

index.html:

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <script type="text/javascript" src="math.min.js"></script>

     </head>
    <body>
    <script type="text/javascript">
        console.log(math.round(math.number(math.to(math.unit('14 ft'), 'ft'), 'ft')),2);
    </script>
    </body>
    </html>`

**Comment by josdejong** [comment]
Do you generate `math.min.js` from your `index.js`?

The file `index.js` doesn't export anything, so it doesn't look to me that you can use it like that. You either have to move your code console.log inside your `index.js` file, or change your `index.js` to actually export something and/or expose something on `window` if you just want to use it in the browser

**Comment by handoyo** [comment]
Yes i do generate math.min.js by following the custom bundling example. I attach the generated math.min.js from index.js.

[https://www.dropbox.com/s/7xase2dg84t0xz7/math.min.js](url)

**Comment by josdejong** [comment]
Did you see my previous comment? https://github.com/josdejong/mathjs/issues/1587#issuecomment-517909967

**Comment by handoyo** [comment]
Sorry, i missed the details. I have export and now i can use the round function. Thanks a lot

**Comment by josdejong** [comment]
:+1:
