### ISSUE TITLE
sqrtm of 3D matrix returns undefined

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1597]
Try `math.sqrtm(math.zeros(2, 2, 2))` in mathjs v6. The function will return `undefined` - it should either return something sensible or throw an error.

**Comment by harrysarson** [comment]
Inserting this code is a good start:
```js

        default:
          // multi dimensional array
          throw new RangeError('Matrix must be two dimensional ' +
          '(size: ' + format(size) + ')')
```

**Comment by josdejong** [comment]
Good find! You're proposal of adding a `default:` case to the switch throwing an error is the right solution I think.

**Comment by harrysarson** [comment]
The linter knows better than we do 😊

**Comment by josdejong** [comment]
:joy:

**Comment by harrysarson** [comment]
Just to confirm, still a bug :)

**Comment by josdejong** [comment]
Just to confirm: help still welcome :)
