### ISSUE TITLE
use fraction got a incorrect number

### ISSUE THREAD

**Issue by AshoneA** [josdejong/mathjs#1603]
when i use `math.fraction(10.234567) ` to fraction, i got a fraction is 99401400/9712321, but 99401400/9712321 result is 10.234566999999279. I think i should got a fraction like 10234567/1000000, maybe i should set some config ?

**Comment by harrysarson** [comment]
This is due to the inexact representation of `10.234567` in javascript. (see http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors).

Try `math.fraction("10.234567")`

Hope that helps!

**Comment by AshoneA** [comment]
@harrysarson awesome! thanks for your help!

**Comment by harrysarson** [comment]
pleasure
