### ISSUE TITLE
Doubt - Help! 

### ISSUE THREAD

**Issue by GauravKanted** [josdejong/mathjs#1612]
@josdejong @rjbaucells 
Hi, 

I've looked through the docs and the issues posted here and could not find a solution for my issue.
I'm quite surprised nobody's faced what I'm facing (or maybe I'm approaching it wrong!)

So I'm using the library to convert a math text (from an excel) into it's LateX format using NodeJS
Something along the lines given below but the parser throws up an "UnhandledPromiseRejectionWarning" for the symbols - {,},?, and =.

mathText = " (4/5)^2 = ? * {4/5}"
math.parse(mathText).toTex()

I want the parser to exclude the special characters ( =, ?) in place and just convert the math operators into their LateX code (i.e /times, /frac, /div etc)

What's the best way to do this? Can I somewhere pass a function or callback handler with symbols for the parser to ignore and convert just the rest?

P.s - I have read through the docs for [Customization](https://mathjs.org/docs/expressions/customization.html) and wasn't able to use any of them for my use case. 

Any help is appreciated. TIA!

**Comment by josdejong** [comment]
The expression parser does not support expressions like `(4/5)^2 = ? * {4/5}`. You would have to adjust the parser quite a bit to be able to do something like that. In this particular example: it expects a variable on the left hand side of `=`, not an expression, it doesn't know what `?` is, and it doesn't know what `{4/5}` is, it's not a valid object notation. 

Are you looking for something like https://www.mathjax.org/ or https://latex.js.org/ maybe?

**Comment by GauravKanted** [comment]
Thanks for you prompt reply @josdejong!

I understand. I was just wondering maybe we could pass an array of arguments to the parser that when it encounters these symbols,or regex, to just ignore and move ahead. Somewhat like the replace function present in JavaScript, just instead of replacing the parser can move to the next character.

My end goal here is to convert the expression(and 1000's more) to the LaTeX format like this:
math exp - `(4/5)^2 = ? * {4/5} `
math latex - `{\left(\frac{4}{5}\right)}^{2} = ?\times{\frac{4}{5}} `

So the special characters (?,= and {}) all are in place but just the math operation is converted to LateX code).

Thanks for the links that you have suggested, I went through them and they are majorly used for the frontend display *after* conversion into LaTex or KaTeX code. 
I'm looking for a solution to do the conversion on my server and store the data in the latex format to display later. 
Thanks for your help!

**Comment by josdejong** [comment]
Unfortunately the parser cannot just "ignore" some syntax it doesn't understand. The parser first translates the syntax into a model ("expression tree", or "abstract syntax tree"), so it has to know how to translate.

Maybe you can build a preprocessing step, something like:

- Split the expression in two if there is an assignment `=` somewhere, have mathjs parse left hand side and right hand side separately. Join the outcome afterwards.
- Create a regular expression to replace all `?` with `unknown`, then have mathjs parse it (`unknown` is then treated as a variable), and afterwards replace the `unknown` occurrences again with `?`.
- The `{...}` syntax you want to use is tricky, this conflicts with existing mathjs syntax for creating objects. maybe you could write a regex to replace `{...}` with `placeholder_0`, parse the inner contents separately, and afterwards replace the variable `placeholder_0` with the inner result again.

Alternatively, you could write your own parser using a parser generator like https://pegjs.org/, but that will require quite some work.

**Comment by GauravKanted** [comment]
Okay, thanks a lot for your support. 
Will look at these ways.
