### ISSUE TITLE
Document 'isNumeric' function does not correct

### ISSUE THREAD

**Issue by wanmifam** [josdejong/mathjs#1615]
The document of function [isNumeric](https://mathjs.org/docs/reference/functions/isNumeric.html) does not correct as below point:
> math.isNumeric('2')  // returns true

It always return false if parameter is 'string' type.
It seems mistake as below: https://github.com/josdejong/mathjs/blame/develop/src/function/utils/isNumeric.js#L20

**Comment by josdejong** [comment]
Thanks for reporting, that's indeed an error in the docs Fixed it via a4f8451 (not yet published).
