### ISSUE TITLE
Cannot call string methods on empty string

### ISSUE THREAD

**Issue by borboss366** [josdejong/mathjs#1628]
If you have a string, and try to use some of the default string methods (like toUpperCase, toLowerCase, etc).
If the string is '' (empty) calling these methods will fail with error 'No access to method', because of the check in isSafeMethod function. 
```js
  if (!object || typeof object[method] !== 'function') {
    return false;
  }
``` 
!'' is always true. But '' is a legit string.
!object should be replaced with condition !== null && !== undefined

**Comment by josdejong** [comment]
Ouch! Thanks for reporting. This is one of these classic JavaScript pitfalls. The same issue occurs with calling a method on a number with value `0`, like `(0).toFixed()`.

**Comment by josdejong** [comment]
This is fixed now in `v6.2.2`

**Comment by borboss366** [comment]
Great!!!!

**Comment by borboss366** [comment]
Thanks! Already integrated changes! =)
