### ISSUE TITLE
Missing diff

### ISSUE THREAD

**Issue by danger89** [josdejong/mathjs#1634]
Hi,

I have an array of numbers, I would like to calculate the diffs between them.
> Calculate the n-th discrete difference along the given axis.

Just like the [numpy diff](https://docs.scipy.org/doc/numpy/reference/generated/numpy.diff.html).

Is that possible?

Ps. this is definitely not the same as your `math.setDifference`!

Regards,
Melroy

**Comment by LloydLS** [comment]
You can use `.map()`, e.g.

```
arr = [1,6,3,8,7,10];
diff = [];
arr.map( f(x,i,a) =  (i[1] + 2 > size(a)[1]) ? "" : diff = concat(diff, [a[i[1] + 2] - x] ))
// diff == [5, -3, 5, -1, 3]
```
The function `f(x,i,a)` used in `.map()` gives you access to the element of the array (`x`), the index of the array (`i`, note that this is zero based and returned as an array containing 1 element), and the array itself (`a`)

**Comment by danger89** [comment]
@LloydLS 
Is this also possible to calculate the diff between two arrays? Example of numpy:
```py
x = np.array([[1, 3, 6, 10], [0, 5, 6, 8]])
np.diff(x)
```

**Comment by danger89** [comment]
More over your code gives `ReferenceError: f is not defined`

**Comment by danger89** [comment]
The answer would be, but nevertheless maybe somebody just want to add it to mathjs?
```js
var x = a.map(function(item, index) {
  return item - b[index];
})
```

**Comment by LloydLS** [comment]
> The answer would be, but nevertheless maybe somebody just want to add it to mathjs?
> 
> ```js
> x = [..., .. ,..]
> y = [..., ..,..]
> // Assuming both x & y are the same length
> var diff = x.map((value, index) => value - y[index])
> ```

Hi, 
If you want to subtract one array from another in MathJS you don't need `.map()`, you can just subtract one from the other.

**Comment by LloydLS** [comment]
> More over your code gives `ReferenceError: f is not defined`

That's odd, it works for me on the MathJS site. Maybe someone else can chime in on this.

**Comment by josdejong** [comment]
Thanks for your suggestion Melroy, would be nice to add a function `diff`.

@LloydLS the function `diff` would not calculate the difference between two matrices, but calculates the difference between the elements in a matrix: `[1, 2, 4, 7, 0]` should return `[ 1,  2,  3, -7]` for example.

Before implementing `diff` we should discuss the details of how it should behave, we can take the Python implementation as example and source of inspiration.

Anyone interested in implementing `diff`? Help would be welcome.

**Comment by Veeloxfire** [comment]
I wrote a function called `crush` (named after garlic crusher to give you an idea of what it should kinda do)
Currently what it does is take a function and an array. It then takes the array and runs the function on slices of the length equal to the number of parameters of that function. So for this example it would be `diff = (x ,y) => y - x` and `arr = [1, 2, 4, 7, 0]` then `math.crush(arr, dif)` goes over the array like this: `[diff(arr[1] - arr[0]), diff(arr[2] - arr[1]), diff(arr[3] - arr[2]), diff(arr[4] - arr[3])]`
It uses `Function.prototype.apply(null, diff)` so it can take functions of any number of parameters (but throws RangeError if function takes more parameters than the array contains)

e.g.
`largeAdd = (a, b, c, d, e, f, g, h) => a + b + c + d + e + f + g + h` <- 8 elements
`arr = [1, 2, 3, 4, 5, 6, 7, 8]  or matrix([1, 2, 3, 4, 5, 6, 7, 8])` <- 8 elements
`math.crush(arr, largeAdd) returns [36] or  matrix([36])` <- 1 element


I wrote it this way becuase it allows it to be slightly more general kinda like the map function than just implementing a diff function, which didnt take very long when I tried it originally. 

@josdejong What are your thoughts? Is this the sort of thing you were thinking of?

**Comment by josdejong** [comment]
That is an interesting approach. So this way you can pass any function which will be applied to every pair of two elements, but also can loop over every set of 3 or 8 elements as in your example. I guess you can use that for calculating sliding windows and things like that? Can you give some usecases for this function `crush`?  It looks interesting, but it also feels quite specific to me. I have the feeling that in many cases writing a little for-loop or map or reduce offers you more freedom so I'm not sure how much value it adds. 

I think the function `diff` is so common that it is good to implement this. Under the hood it _could_ utilize a more generic function like `crush`, but I think diff is so simple that this would only complicate things and is probably not worth it.  

I'm not sure about the naming, I see Matlab and Python both use `diff` as name, wouldn't it make sense to simply follow them?

**Comment by Veeloxfire** [comment]
Yeah that does make sense. I was just trying to generalise but I guess its no common enough to need that as the diff function would be the only example that woud need it.

**Comment by josdejong** [comment]
👍 let's start simple then and see how it evolves :)

**Comment by josdejong** [comment]
Closing this issue, `diff` has been implemented in the meantime.
