### ISSUE TITLE
Parsing input stored in calculator app before clearing or evaluation - may or may not be valid expression

### ISSUE THREAD

**Issue by DragonOsman** [josdejong/mathjs#1636]
I'm trying to implement a browser-based calculator app that tries to emulate the Windows calculator app (except making the symbols for squaring and getting the square-root of a number being the ones that this library would require).  I have the input stored in the calculator appear at the top in the display screen, which I have as a `div` element with two `p` elements: one for the stored input and one for the current entry which also updated with calculation results or when stored input is evaluated upon pressing an operator or function key.  And that last bit is what I'm having trouble with right now and is why I opened this issue.  My code is in this [gist](https://gist.github.com/DragonOsman/b474ff037c9d440f679f8ad1ceccfa5d).

I have a regular expression I found on SO that I'm using here, but it apparently can't handle parentheses.  I want something that can also handle parentheses.  Can I use the `math.parse` method in Math.js for this?  If not, then how should I do this when using this library?  Thanks in advance for any help.

**Comment by josdejong** [comment]
You can use parentheses in regular expressions but you'll have to escape them.

If I understand you correctly you use this regular expression to check whether the input is valid before evaluating? You can simply execute `math.parse` and enclose it in a `try {... } catch`: if the input is not valid it will throw and you catch and continue.

**Comment by DragonOsman** [comment]
What if the expression is incomplete?  I need a way to tell if the expression is complete, for example that it has enough numbers and operators in it or at least one function that can be successfully evaluated.  Would be good if the exception I get can help with that.

**Comment by josdejong** [comment]
Well, it's just my 2-cents. I don't know what kind of rules you have in mind to determine whether an expression is complete. Anyway, just trying to parse it and see if it fails will allow you to figure out whether the expression is valid, and is not missing a closing bracket or a value on the right side of an operator, etc.
