### ISSUE TITLE
on std.js there is a duplicated 'min' in seealso:

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#1639]
Change
`  seealso: [
    'max',
    'mean',
    'min',
    'median',
    'min',
    'prod',
    'sum',
    'variance'
  ]
`
to
`  seealso: [
    'max',
    'mean',
    'min',
    'median',
    'prod',
    'sum',
    'variance'
  ]`

**Comment by josdejong** [comment]
Thanks for reporting @dvd101x , fixes via 2713431b846226f9d4b7567345ef3199b6b20c44
