### ISSUE TITLE
Using mean with units throws error in evaluate function

### ISSUE THREAD

**Issue by Chris1234567899** [josdejong/mathjs#1640]
Using a calculation like this:

`var calculation = "mean(5km,10km)";`
`math.evaluate(calculation);`

results in the following error:
` Cannot calculate mean, unexpected type of argument (type: Unit, value: {"mathjs":"Unit","value":5,"unit":"km","fixPrefix":false})`

It is because of the units, because the line 
`var calculation = "mean(5,10)";`
works perfectly fine.

I tested the same with functions like sum, max, min, median and mode and there it works fine with units.
With mean, however it does not, which looks like a bug.
Using mathjs 6.2.2

**Comment by ericman314** [comment]
Thanks for reporting. Anyone want to work on a fix? Might be a while before I can get to it.

**Comment by clintonc** [comment]
I'd like to work on this (and related matters); I've got working code and tests, so I can make a PR later today.

**Comment by josdejong** [comment]
For reference: fixed via #1644

**Comment by Chris1234567899** [comment]
Cool, great.

I noticed the round() function as as well problems with units. Maybe you could have a look at that while you are on it. Maybe it's the same thing.

**Comment by ericman314** [comment]
Thanks, @clintonc!

@Chris1234567899, if you mean `round(6.35 cm)` or something, that's not supported because we don't want the results of expressions to change based on what units they're written in:

```
equal(6.35 cm, 2.5 in) // true
equal(round(6.35 cm), round(2.5 in)) // false
```

It's even more problematic when the argument to `round(...)` is an expression itself with various units,  then there's no telling which unit it will be expressed in when it is passed to `round`.

**Comment by Chris1234567899** [comment]
@ericman314  thanks for the explanation. I had in mind to overcome the problem with floating point precision with rounding, but it seems I can take the format() functionality for that in my case. This has no problem with units. Nevermind then :)

**Comment by ericman314** [comment]
Cool!

**Comment by josdejong** [comment]
That's a clear explanation Eric. I can imagine we extend the function `round` so you can pass the unit which you want to use to round the value, like `round(6.3542 cm, {unit: cm, precision: 2})` or `round(6.3542 cm, cm, 2)`.
