### ISSUE TITLE
Stupid question if

### ISSUE THREAD

**Issue by tobiasguimaraes** [josdejong/mathjs#1643]
Theres a way apply if else in middle of the expression?

math.evaluate(' if(scope.a > scope.b) ? scope.a * 10 : scope.b * 20 ', scope) ?

Where it evaluates the variable apply the correct way ?

**Comment by josdejong** [comment]
You probably mean the conditional operator `condition ? truePart : falsePart` .

https://mathjs.org/docs/expressions/syntax.html#operators
