### ISSUE TITLE
Object syntax doesn't allow keywords (to, mod, in, etc) as keys

### ISSUE THREAD

**Issue by wes-r** [josdejong/mathjs#1645]
`math.parse('{from: 5, to: 7}')`
fails with:
`math.js:46660 Uncaught SyntaxError: Symbol or string expected as object key (char 11)`

This fails for all of the keywords in the syntax: `mod, and, not, or, xor, to, in`.

Tested version: `6.2.2`.

**Comment by josdejong** [comment]
Thanks for your suggestion Wesley, it would be nice indeed if we could use keywords as object properties. Should be possible I think.

**Comment by Veeloxfire** [comment]
Problem to me seems that, when assigning the toke type, all `NAMED_DELIMITERS`  are assigned as `TOKENTYPE.DELIMITER` where they are actually usable as `TOKENTYPE.SYMBOL` in this context. 
Maybe adding `TOKENTYPE.NAMED_DELIMITER` or having `state.tokenType` be an array instead so if there are more than one options then it could go through in order of priorty. If it would crash on a certain option it could revert to the second etc.
This would involve a lot of rewriting though so maybe just easier to have the extra option on `TOKENTYPE`

**Comment by josdejong** [comment]
This issue is fixed now in `mathjs@6.6.3`

**Comment by josdejong** [comment]
Thanks again @Veeloxfire
