### ISSUE TITLE
mathjs/number missing typescript definitions.

### ISSUE THREAD

**Issue by VorpalBlade** [josdejong/mathjs#1665]
mathjs/number (documented at https://mathjs.org/docs/custom_bundling.html) doesn't seem to work with TypeScript. It looks to me like this is missing from the @types/mathjs TypeScript definitions.

Is this sort of issue tracked here at mathjs or should I open a separate bug against the DefinitelyTyped repository instead?

**Comment by josdejong** [comment]
@charlee has been working on the TypeScript definitions. I think he also wanted to implement types for `mathjs/number` but I don't know the status of that.

See #1539, let's continue the discussion there ok?
