### ISSUE TITLE
math.qr returning lower triangular matrix

### ISSUE THREAD

**Issue by kevinkelleher12** [josdejong/mathjs#1669]
`math.qr([[0, 1], [1, 0]])`

throws this error: 

`Uncaught Error: math.qr(): unknown error - R is not lower triangular (element (1, 0)  = 1)`

I'm able to use the QR decomposition in other software on this example matrix.

I believe the issue is with the below line of code returning 0 when pivot is 0, so that the reflection is not properly calculated:

`const sgn = unaryMinus(sign(pivot))`

Side note - I believe the error message above should read: "R is not upper triangular."

**Comment by josdejong** [comment]
Thanks for reporting Kevin.

So if I understand you correctly there are two issues:

1. The qr fails for example above whilst it should be able to calculate the result
2. The error message is incorrect.

Anyone able to look into this issue in more detail? Help would be very welcome.

**Comment by kevinkelleher12** [comment]
Thanks, yes I believe you've summarized the issues correctly.

After changing the line of code I identified to read:

`const sgn = pivot === 0 ? 1 : unaryMinus(sign(pivot))`

the function correctly calculates the QR decomposition for my example and passes all tests.

I would be interested to hear someone else's thoughts, as I'm not an expert (especially unsure how to properly handle this for complex numbers).

**Comment by harrysarson** [comment]
Yeah, legit bug. Thanks for flagging!

I can fix this, do you have an example of a complex matrix that would cause the same error?

**Comment by josdejong** [comment]
This issue is fixed now in `v6.2.4`. Thanks again @harrysarson and @kevinkelleher12.
