### ISSUE TITLE
Parsing `{}` as variable instead of object?

### ISSUE THREAD

**Issue by daveisfera** [josdejong/mathjs#1672]
Currently, we have some Python code that overrides the `set` parsing to be able to identify variables that have spaces and such and we'd like to be able to use these same expressions and evaluate them in Javascript. A simple solution we could do is to replace `{}` and spaces with another characters, like `_`, but we'd love to be able to build this into the parser and we almost can. Here's an example:

```
import { parse } from 'mathjs';

const isAlphaOriginal = parse.isAlpha;
parse.isAlpha = (c, cPrev, cNext) => {
    return isAlphaOriginal(c, cPrev, cNext) || c === '{' || c === '}' || c === ' ';
};

const node2 = parse('{x value}^{another one}');
const code2 = node2.compile();
const scope = {
    '{x value}': 3,
    '{another one}': 2,
};
const first = code2.evaluate(scope); // 9
console.log(first);

scope['{another one}'] = 3;
const second = code2.evaluate(scope); // 27
console.log(second);
```

That works if you replace `{}` with `_` but the `{}` appear to be parsed as `DELIMITERS` and can't be handled using the current customization points. Is there another way to accomplish this or should we just go with the replacement and be done with it?

**Comment by josdejong** [comment]
You can indeed not use variables with spaces or special characters in the global scope. You could defined them as object properties though, like this:

```js
const scope = {
  variables: {
    '{x value}': 3,
    '{another one}': 2,
  }
};
math.evaluate('variables["{x value}"] ^ variables["{another one}"]', scope); // 9
```

Would that work for you?

**Comment by daveisfera** [comment]
That's an interesting idea, but the formulas are already stored in that format and that's how the user can enter them, so we'd have to parse and rewrite the expression to do something like that and that's what I'm trying to avoid. Basically, is sounds like the search and replace concept is probably the easiest option.

**Comment by josdejong** [comment]
In that case I think you're right and replacing the special characters with an underscore is best.

**Comment by daveisfera** [comment]
👍
