### ISSUE TITLE
TypeError in the browser

### ISSUE THREAD

**Issue by andipabst** [josdejong/mathjs#1676]
When I try to use mathjs 6.2.3 in the browser, it doesn't load, but throws the error `TypeError: array is undefined in math.js:5408:19`. This seems to be a line in the function `parseSignature` from the library typed-function (https://github.com/josdejong/typed-function/blob/e298b5c360018c6b1c3df7e558e61ee11055e450/typed-function.js#L316)

The same also occures with the minified version and both in Chrome 78.0.3904.97 and Firefox 70.0.1 (both 64bit on Linux 4.19 (MANJARO)).

**Comment by andipabst** [comment]
Sorry for bothering you, another library was messing with Array.prototype.map without me noticing.

**Comment by josdejong** [comment]
👍
