### ISSUE TITLE
"foo.2.baz" yields "Unexpected operator ." error

### ISSUE THREAD

**Issue by wes-r** [josdejong/mathjs#1678]
I have some scope variables that use numbers as keys, e.g. `{foo: {2: {baz: 33}}`.

I'd like to be able to do `math.evaluate("foo.2.baz", {foo: {2: {baz: 33}})` and get `33`. Attempting to do so currently yields an `Unexpected operator .` error.

Would it be possible to get the parser to work for this case? Open to attempting a PR if I had some guidance on where to look/poke. TY!

**Comment by josdejong** [comment]
Interesting case. I think we can indeed improve the parser to allow array indexes in dot notation.

Would be great if you can give this a try!

The relevant code is in the function [`parseAccessors`](https://github.com/josdejong/mathjs/blob/develop/src/expression/parse.js#L1273) in `parse.js`.

**Comment by wes-r** [comment]
I tried exploring that code a bit but am fairly lost.

Additionally, I was able to rework things on my end to use arrays.

Closing, but feel free to re-open if desired. Ty!

**Comment by josdejong** [comment]
👍
