### ISSUE TITLE
Adding simple floats sometimes results in incorrect value

### ISSUE THREAD

**Issue by cosmorunner** [josdejong/mathjs#1683]
Hi, im using default configuration and executing folling statements:

`math.evaluate('0.1 + 0.1');`
--> 0.2
`math.evaluate('0.1 + 0.8');`
--> 0.9
`math.evaluate('0.1 + 0.8 + 0.1');`
--> 1
`math.evaluate('0.1 + 0.7 + 0.1');`
--> 0.8999999999999999
`math.chain('0.1').add('0.8');`
--> Object { value: 0.9 }
`math.chain('0.1').add('0.1').add('0.7');`
--> Object { value: 0.8999999999999999 }

Is there anything i am missing, considering the results with "0.899999..."?

**Comment by Yaffle** [comment]
@cosmorunner , see https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
