### ISSUE TITLE
math.intersect() for lines produces wrong intersections

### ISSUE THREAD

**Issue by instafluff** [josdejong/mathjs#1685]
Using the production 6.2.5 version [https://unpkg.com/mathjs@6.2.5/dist/math.min.js](https://unpkg.com/mathjs@6.2.5/dist/math.min.js) of math.js, the following code should return null but returns an intersection point of (6, 0):

```javascript
let intersection = math.intersect( [ 0, 0 ], [ 8, 0 ], [ 6, -3 ], [ 6, -7 ] );
console.log( intersection );
```

**Comment by josdejong** [comment]
Thanks for your feedback @instafluff. I think your assumption is that lines have a start and end and only intersect when the intersection is between the start and end of the line. The current implementation of `intersect` though takes the two points you give as "some" location on the line but not a start and end, it works with lines which have infinite length. You could validate whether the returned intersection point is inside the line segment by checking if `x_1 <= x_intersection <= x_2` and  `y_1 <= y_intersection <= y_2`.
