### ISSUE TITLE
Same unit name with 2 different bases

### ISSUE THREAD

**Issue by petermarks12** [josdejong/mathjs#1693]
I have just gone through docs.  I want to create 2 units with same name but different base.

mb stands for millibar
mb stands for megabyte

I want to create 2 units with same name, one for binary and one for pressure.  This is just an example.   I could not see any option where i can define base for these units on this page.

https://mathjs.org/docs/reference/functions/createUnit.html

**Comment by ericman314** [comment]
Unit names have to be unique, so unfortunately you can't define two units with the same name.

The base of a unit is inferred from its definition, so if you do `math.createUnit('inHg', '3386.39 Pa')`, it knows `inHg` should be a pressure because `Pa` is an existing pressure unit. Does that help?

**Comment by petermarks12** [comment]
Thanks, got it... one small question... is there a function to get base of the unit?

**Comment by ericman314** [comment]
There is not a built-in function to get the base. There will be in the next major release, hopefully.

Here's a polyfill you could use to get the base:

```js
math.Unit.prototype.getBase = function() {
  return Object.values(math.Unit.BASE_UNITS).find(b => this.equalBase(b))
}
```

Then you can do:

```js
let x = math.unit("2 torr")
console.log(x.getBase().key) // PRESSURE
```

The built-in bases are a little limited right now, but that should change in the next major release, because we hope to be using [UnitMath](https://github.com/ericman314/UnitMath) by that time, which recognizes many more bases.

**Comment by petermarks12** [comment]
thanks, you are very very helpful

**Comment by ericman314** [comment]
We are moving math.js's unit functionality into its own library, UnitMath. Nearly all of the functions for units that are available in math.js right now will be included in UnitMath, plus some extras. Then, the next major release of math.js will use UnitMath, so all of those functions will still be available.

**Comment by josdejong** [comment]
Really looking forward to see UnitMath finished :)

I think we can close this issue right? Feel free to reopen if needed.
