### ISSUE TITLE
There are some errors in the calculation results

### ISSUE THREAD

**Issue by good-fat** [josdejong/mathjs#1703]
I use eval function to calculate a number,the expression is as follows:
math.eval('12 / (2.3 + 0.74)');
The correct result should be: 3.9473684210526316(rounding) or 3.9473684210526315(no rounding),
but, math.js gives me the result: 3.9473684210526314.
There is an error.
Releases: v6.2.5

**Comment by josdejong** [comment]
This is a floating point round-off error, see docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
