### ISSUE TITLE
Unit validation?

### ISSUE THREAD

**Issue by peteruithoven** [josdejong/mathjs#1704]
Thanks for creating this great library!

I was wondering whether there is an easy way to validate / check whether a given unit is supported?

The easiest way for now seems to try to do a `math.unit("foo")` and if there is no error thrown it's a valid unit. 

I'd love a simple build in function, something like:
``` js
math.unit("kg").isValid() // outputs true
math.unit("foo").isValid() // outputs false
```

**Comment by peteruithoven** [comment]
This is somewhat related to: https://github.com/josdejong/mathjs/issues/627

**Comment by peteruithoven** [comment]
I now realize `math.unit("foo")` would already throw an error which prevents the use of a `isValid()` function. 

Maybe something like `math.validate("foo")` beside the existing `math.evaluate()`?

**Comment by ericman314** [comment]
You can access the built-in (and user-defined) units using `math.Unit.UNITS`, so you could do something like `math.Unit.UNITS.hasOwnProperty('foo')`, but that wouldn't correctly validate units with prefixes, like `kg`.

The fastest way to check for the validity of a unit would be to access the underlying parse function like this: `math.Unit.parse('foo')`. This will throw if the unit and prefix does not exist.

If you don't want to have to catch the error every time, you could write a function that does the try/catch and returns a boolean. You could even import the function into math.js. Here's a complete example:

```js
const { create, all } = require("mathjs");
const math = create(all)

math.import({
  validate: (str) => {
    try {
      math.Unit.parse(str)
      return true
    } catch (err) {
      return false
    }   
  }
})

math.validate('kg') // true
math.validate('foo') // false
```

**Comment by peteruithoven** [comment]
Good point. Thanks for the example. 
I'll close the issue.
