### ISSUE TITLE
Custom unit base for createUnit

### ISSUE THREAD

**Issue by peteruithoven** [josdejong/mathjs#1707]
I noticed that when I add a custom unit using `createUnit` without a definition it will automatically create a unit base name. 
See: https://github.com/josdejong/mathjs/blob/718b93b2b4ffccac8cb60b6c628e3696962604af/src/type/unit/Unit.js#L3174
For example when I add "mycustomuni" it will create the unit base: "mycustomunit_STUFF". 

Since I'm using this name in my UI I'd like to customize it. 

Maybe a `baseName` option could be added?

**Comment by ericman314** [comment]
Sure, I don't see any reason why not. Eventually, we will be migrating to using [UnitMath](https://github.com/ericman314/UnitMath) which will have options for that. In the mean time, this shouldn't be too difficult to add.

**Comment by josdejong** [comment]
The `baseName` option created by Eric in #1708 is now available in `mathjs@6.5.0`

**Comment by josdejong** [comment]
thanks again Eric :)

**Comment by peteruithoven** [comment]
Whow that's quick, thanks @ericman314!
