### ISSUE TITLE
Can't add mathjs as a dependency using yarn

### ISSUE THREAD

**Issue by Lazin** [josdejong/mathjs#1715]
I'm trying to use `mathjs` in my grafana plugin https://github.com/akumuli/akumuli-datasource 
It's built using Typescript so I'm using this commands to add `mathjs` as a dependency:

```
>> yarn add mathjs
>> yarn add @types/mathjs
```

Everything is OK so far. Than I'm adding an import to my src/datasource.ts and run `npm run build`. This command fails with this error:

```
>> dist/datasource.ts(5,25): error TS2307: Cannot find module 'mathjs'.
Warning: Task "typescript:build" failed. Use --force to continue.
```

**Comment by josdejong** [comment]
So what is in your `datasource.ts`? How can I reproduce your issue?

**Comment by Lazin** [comment]
I hope this should be easy and won't take a lot of time. Clone the repo - https://github.com/akumuli/akumuli-datasource/tree/addmathjs, checkout addmathjs branch, than run `yarn install; npm run build`

I expected that it will work (I only added dependency and imported mathjs in datasource.ts). But it fails with the aforementioned error. The @types/mathjs is not referenced in the branch but it makes no difference when I added it.

**Comment by josdejong** [comment]
I see you import mathjs as:

```js
import * as math from "mathjs";
```

I'm not sure if that works, can you try some examples from the [getting started](https://mathjs.org/docs/getting_started.html)? Like:

```js
import { create, all } from 'mathjs'

const config = { }
const math = create(all, config)
```

**Comment by Lazin** [comment]
I tried this and the result is the same. I also updated the branch. 

```
Running "typescript:build" (typescript) task
>> dist/datasource.ts(5,29): error TS2307: Cannot find module 'mathjs'.
```

**Comment by josdejong** [comment]
I had a short look at your project. I'm not sure why it doesn't work. I do not think it is an issue with yarn or npm but with your TypeScript setup: the error is a typical TypeScript error and sounds like the TypeScript compiler is not able to find the TypeScript definitions of mathjs for some reason.

It is weird that you have added other dependencies like lodash+types which does work, that suggests that the setup is ok and there is something strange with mathjs or its type definitions.

I've tried adding mathjs to an empty Angular project on codesandbox, that just works: https://codesandbox.io/s/mathjs-angular-m4gif. Maybe you can try create an empty project, see if you can get it working there?

**Comment by josdejong** [comment]
Will close this issue now due to inactivity, please reopen when still an issue.
