### ISSUE TITLE
Need some help in fixing decimal values

### ISSUE THREAD

**Issue by petermarks12** [josdejong/mathjs#1716]
I am getting unexpected decimal output in various user-defined unit conversions. I want to know is there any library or inbuilt function which can fix this.

I want to format decimal output in following way.

3.999999999999999 -> 4
3.999999999999998 -> 4
1936.0000000000002 -> 1936
364.50000000000006 -> 364.5
0.0055570000008 -> 0.005557

**Comment by josdejong** [comment]
This are floating point round-off errors. 

See docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by petermarks12** [comment]
thanks, will have a look
