### ISSUE TITLE
Formatting numbers with only 0's in decimal

### ISSUE THREAD

**Issue by stoplion** [josdejong/mathjs#1717]
Is there a way to format a number's precision (leave them off) if it only has 0's in the decimal?

For example:

Show the decimals when there are non 0 values after the decimal:
`1.5 + 8 = 9.5`

But leave them off if there are only 0 values after the decimal:
`1 foot - 1 inch in inches =  11.00 inches`
// if precision is 2

Instead format like:
`1 foot - 1 inch in inches = 11 inches`

**Comment by josdejong** [comment]
Have a look at `format`: https://mathjs.org/docs/reference/functions/format.html

I think what you ask is the default behavior? If not you will have to write a little if/else to apply different logic for your different cases.

**Comment by stoplion** [comment]
thanks!
