### ISSUE TITLE
Error popping up from create.js due to docs import

### ISSUE THREAD

**Issue by Prashanth-Primaseller** [josdejong/mathjs#1719]
While creating instance of mathjs using create method. The following error pops-up.
As I am catching all the errors in my app. I get this pop-up quite often. I see the code, that this module comes under deprecated. Could someone remove this and update please. 

```
create.js?0508:210 Uncaught (in promise) Error: math.expression.docs has been moved. Please import via "import { docs } from 'mathjs'"
    at eval (create.js?0508:210)
    at Object.get [as docs] (object.js?0b40:230)
```

**Comment by josdejong** [comment]
Thanks for reporting. You should only see this message when trying to access the deprecated location of the docs `math.expression.docs`. 

How can I reproduce your issue? Can it be that your code still uses the deprecated `math.expression.docs`?

**Comment by Prashanth-Primaseller** [comment]
The below code is what I am using to access mathjs.

`import {
  create,
  addDependencies,
  divideDependencies,
  formatDependencies,
  chainDependencies,
} from 'mathjs';

let math = create(
  {
    addDependencies,
    divideDependencies,
    formatDependencies,
    chainDependencies,
  },
  {
    epsilon: 1e-12,
    number: 'BigNumber',
    precision: 5,
    rounding: 4,
    matrix: 'Array',
    predictable: false,
  }
);

function calculateTotal(price, discount, sumProductTotal) {
  return math
  .chain(price)
  .subtract(
    math
      .chain(discount)
      .multiply(price)
      .divide(sumProductTotal)
      .done()
  )
  .done()
  .toFixed(5);
}`

And along with that error I mentioned, I get bunch of warning logs that are being thrown from /src/core/create.js.

**Comment by josdejong** [comment]
I tried to reproduce your issue but when I run your code in codesandbox it does not output any console errors or warnings, see: https://codesandbox.io/s/mathjs-1719-tbu9z. Any idea?

**Comment by Prashanth-Primaseller** [comment]
Thanks. I found the issue. Its not issue with the library. I am using mathjs with vuejs. It seems when vue tries to make mathjs reactive, that's when I get that error. 

I fixed it by passing mathjs as argument to the methods which will prevent from making it reactive and all works well.

Thanks again for helping me find the issue.

**Comment by josdejong** [comment]
Glad to hear you found a solution :+1:
