### ISSUE TITLE
Unexpected out-of-memory error in concatenation

### ISSUE THREAD

**Issue by davidmrdavid** [josdejong/mathjs#1728]
The following script loads four matrices: **B**, **C**, **D**, and **E**.
Then **B** and **C** are multiplied together, followed with **D** by **E**.

Lastly, I attempt to column-wise-concatenate the two results, as they have the same number of rows, but doing so causes an out-of-memory exception. 

This is strange because the runtime does not error out when making 3 simultaneous copies of **BC** and **DE**. Since this does not error out, I suspect that the concatenation should also not error out. Please let me know what you think :).

Script:
```JavaScript
const fs = require("fs");
const math = require("mathjs");

function main () {
    contents = fs.readFileSync("B.json");
    json = JSON.parse(contents);
    let B = math.SparseMatrix.fromJSON(json);

    contents = fs.readFileSync("C.json");
    json = JSON.parse(contents);
    let C = math.SparseMatrix.fromJSON(json);

    contents = fs.readFileSync("D.json");
    json = JSON.parse(contents);
    let D = math.SparseMatrix.fromJSON(json);

    contents = fs.readFileSync("E.json");
    json = JSON.parse(contents);
    let E = math.SparseMatrix.fromJSON(json);

    let BC = math.multiply(B,C);
    let DE = math.multiply(D,E);


    // COMMENT THIS BLOCK ON/AND OFF
    // I can make multiple copies of BC and DE
    // But I can't concatenate them w/o running
    // out of memory, which is unexpected
    /*
    let BC2 = math.multiply(B,C);
    let DE2 = math.multiply(D,E);
    let BC3 = math.multiply(B,C);
    let DE3 = math.multiply(D,E);
    */
    //
    console.log(BC.size()); // [ 253120, 28022 ]
    console.log(DE.size()); // [ 253120, 53641 ]
    let res = math.concat(BC, DE, 1);
}

main();

```

Reproducing files:
[reproduce2.zip](https://github.com/josdejong/mathjs/files/4125271/reproduce2.zip)

Heads up, you'll need a beefy machine to reproduce this. I'm running it on over 200GB of RAM but perhaps that's overkill.

**Comment by josdejong** [comment]
Thanks for your report.

It's hard to tell why in this case concatenation causes running out of memory. I do not have 200GB of RAM to reproduce your issue though :joy: . Is it possible for you to create a reproducable issue when loading node.js with a max RAM of say 1 GB?

**Comment by davidmrdavid** [comment]
Hahaha, understandable.
I'm not aware of a means to reproduce this error with smaller matrices at the time being. I'll follow-up if I manage to come up with something :)

**Comment by josdejong** [comment]
:joy:  Yeah. Let's close this issue for now then, and please reopen if you manage to reproduce it on a bit smaller scale.
