### ISSUE TITLE
atan bug

### ISSUE THREAD

**Issue by 80LevelElf** [josdejong/mathjs#173]
Hello!
If I want to calculate atan(i) I get this answer: NaN - aNi.
atan(2i) and atan with others arguments I can calc well.

**Comment by BigFav** [comment]
This has been resolved.

**Comment by josdejong** [comment]
Yes, thanks Favian. Did you maybe check whether other trigonometric functions have similar edge cases?

**Comment by BigFav** [comment]
I don't know much about this problem, but every trig test set has this test case. It was even in this set, but it had a `TODO` comment next to it, followed by the problem..

**Comment by josdejong** [comment]
Ok then. Besides that I can't think of any similar cases. Let's close this issue.
