### ISSUE TITLE
Implicit hide not working in latex for 2*x

### ISSUE THREAD

**Issue by thunderkid** [josdejong/mathjs#1738]
When I try to render `2*x` to latex, I'm always getting a `\cdot` even if I use `{implicit: 'hide'}`:

```math2.parse('2*x').toTex({implicit: 'hide'})      // gives   2\cdot x```

Shouldn't the `\cdot` be hidden? I'm not sure whether this is the same as issue 
https://github.com/josdejong/mathjs/issues/1137 since I'm not doing a chain of calculations here, I'm just extracting the latex.

**Comment by josdejong** [comment]
This is because `2*x` is an explicit multiplication. `2x` is implicit, and the `{ implicit: 'hide' }` option only applies there.

```js
math2.parse('2x').toTex({implicit: 'hide'}) // '2~ x'
```

**Comment by dcaillibaud** [comment]
Ok, it's the same with `math.simplify(math.parse('9a/3')).toTex({implicit: 'hide'})` giving `3\\cdot a` when we can expect `3a`
