### ISSUE TITLE
Modular multiplicative inverse

### ISSUE THREAD

**Issue by ohpyupi** [josdejong/mathjs#1744]
Any plan on implementing the modular multiplicative inverse?

**Comment by josdejong** [comment]
I have to say I had never heard of it :). I understand it's a function from number theory and in math applications it's called `invmod` or `inverse_modulus`. 

If it's a relevant function it would be nice to add of course. Anyone interested into implementing `invmod`?

**Comment by ohpyupi** [comment]
It will be my pleasure to implement it in the library!

**Comment by ohpyupi** [comment]
@josdejong Made an early PR https://github.com/josdejong/mathjs/pull/1749. Can you take a look at it?

**Comment by thetazero** [comment]
Given that it's still not implemented, I'll take a crack at it.

**Comment by josdejong** [comment]
Thanks @thetazero, appreciated!

**Comment by thetazero** [comment]
I'm pretty confident that I've implemented this for numbers and big Numbers.

**Comment by josdejong** [comment]
Available now in `v10.1.0`, see #2368.
