### ISSUE TITLE
How To Removing Rows or Columns from a Matrix

### ISSUE THREAD

**Issue by mhmtbk** [josdejong/mathjs#1750]
#I have multi dimensional matrix and a single dimensional matrix (such as [30, 10] and [10, 1]).  I want to completely remove specific rows and columns. How can I do it in math.js.

If assume A is my matrix with 30 rows and 10 column ([30, 10]), I want to delete the 3rd and 9th rows and 5th column. Finally size of my matrix will be: ([28, 9]).

**Comment by josdejong** [comment]
There is currently no function to remove specific rows or columns from a matrix, though we discussed some ideas long time ago already, see #54. 

What you will have to do at this point is create subsets of the parts of the matrix that you want to keep, and concatenate them. When using the expression parser that looks something like:

```
a = diag(1:4)
# 1, 0, 0, 0
# 0, 2, 0, 0
# 0, 0, 3, 0
# 0, 0, 0, 4

b = concat(a[1:2,:], a[4,:], 1)
# 1, 0, 0
# 0, 2, 0
# 0, 0, 0
# 0, 0, 4
```

**Comment by mehmetbak** [comment]
> There is currently no function to remove specific rows or columns from a matrix, though we discussed some ideas long time ago already, see #54.
> 
> What you will have to do at this point is create subsets of the parts of the matrix that you want to keep, and concatenate them. When using the expression parser that looks something like:
> 
> ```
> a = diag(1:4)
> # 1, 0, 0, 0
> # 0, 2, 0, 0
> # 0, 0, 3, 0
> # 0, 0, 0, 4
> 
> b = concat(a[1:2,:], a[4,:], 1)
> # 1, 0, 0, 0
> # 0, 2, 0, 0
> # 0, 0, 0, 4
> ```

Thank you for your response to the question. Your suggestion gives an idea but I actually wonder if there is a matrix created by math.matrix function, how can I completely remove specific rows and columns? Finally I found something as a result of my research and your advice, which is stated below.

const a = math.matrix([[0, 1, 2], [3, 4, 5], [6, 7, 8]]) ;

Remove last column;
a.subset(math.index(math.range(0, 3), math.range(0, 2)))                   //[[0, 1], [3, 4], [6, 7]]

Remove first row;
a.subset(math.index(math.range(1, 3), math.range(0, 3)))                  // [[3, 4, 5], [6, 7, 8]]

Remove specific row and column;
const b = a.subset(math.index(0, [0, 2]))                                            // [[0, 2]]
const c = a.subset(math.index(2, [0, 2]))                                            // [[6, 8]]
const d = math.concat(b, c, 0) ;                                                         // [[0, 2], [6, 8]]

**Comment by josdejong** [comment]
> I actually wonder if there is a matrix created by math.matrix function, how can I completely remove specific rows and columns?

The example I gave does that, or not? It constructs a new matrix by gluing the part left and right from the column you want to remove into a new matrix. Are you looking for the plain JavaScript syntax for this instead, or is it something else I don't understand?

**Comment by gwhitney** [comment]
It seems to me that currently the canonical way in mathjs to perform the originally requested operation (remove 3rd and 9th row and 5th column of a 30x10 matrix) is (in mathjs "internal notation" as implemented by parse; this can of course be translated to direct JavaScript calls, involving reindexing all indices down by one):
```
M = reshape(1:300, [30,10])  # something to work on where we can see the rows and cols
rows = filter(1:30, r != 3 and r != 9) # rows we want
cols = filter(1:10, c != 5) # cols we want
M[rows, cols]
```
If you try this in the demo parser in the home page, it produces exactly what was requested. Note though that M remains unchanged after this operation, it's just extracting the desired portion of M and returning it as a new collection. A version of this operation that _modifies_ M would require an implementation of #54.

I don't think there's much else to say on this topic that isn't covered by #54, so closing.
