### ISSUE TITLE
Bug: tune config.epsilon parameter

### ISSUE THREAD

**Issue by kyriiherman** [josdejong/mathjs#1758]
Currently, EPSILON equals to 1e-12, but for example `589.44 * 1 * 10**2 = 58944.00000000001` so `nearlyEqual`[](https://github.com/josdejong/mathjs/blob/033a6baac7e4517e3ec258df359d040aa9585b47/src/utils/number.js#L567) doesn't work anymore.

**Comment by josdejong** [comment]
Can you give an example where nearly equal doesn't work for you?

```js
math.equal(589.44 * 1 * 10**2, 58944) // true, as I would expect
```

**Comment by josdejong** [comment]
Note that if needed you can set epsilon to a different value.
