### ISSUE TITLE
Complex dot product doesn't conjugate

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#1761]
Inner product on ℂ is supposed to be _sesquilinear_ – it should conjugate one of the two vectors before multiplying them. [Source](https://en.wikipedia.org/wiki/Dot_product#Complex_vectors).
```javascript
const I = math.complex(0,1)
math.dot( [1,0], [I,0] ) // I
math.dot( [I,0], [1,0] ) // I
```
The current `dot` product clearly doesn't conjugate neither one of the vectors. This is also true of `multiply(Vector, Vector)` which apparently has a different implementation than `dot`.

While the Wikipedia article I linked uses the convention <v, w> = vᵀ w̅ (inner product is linear in the first argument and antilinear in the second argument), the opposite convention <v, w> = v⁺ w = v̅ ᵀ w is used as often, if not more. (For example in quantum mechanics, the first argument is exclusively antilinear.)

**Comment by josdejong** [comment]
Ah, that's interesting. The `dot` function simply uses `multiply` internally and doesn't do anything special for complex input values.

What would be needed to fix this behavior for complex values? Wrap the function in `conj(...)`?

**Comment by m93a** [comment]
Yes, wrapping one of the vectors in `conj` would solve the issue. The question is:
1. Do we mind changing the API? (This is potentialy a breaking change.)
2. Which of the two vectors should be conjugated? (I strongly root for the _first_ one.)

**Comment by josdejong** [comment]
Thanks Michal! 

1. Since the behavior changes (though you could maybe pitch it as a bug fix) I think it's best to make it a major, breaking change. Which is no problem at all, it's just changing a different number in the version number :)
2. I'm not an expert on this subject, so I think it would be best to follow what other math applications do (Matlab, Mathematica, Python numpy, ...). What do you think?

**Comment by m93a** [comment]
Making a survey on how other applications do it is always a good idea! I checked _Mathematica_, _Matlab_ and two Python libraries – _Numpy_ and _Scipy_. I was surprised that only two of these four tools had a sesquilinear dot product. Both of them conjugated the first vector.

### Mathematica
Mathematica has a dot product which **doesn't conjugate** [[discussion]](https://community.wolfram.com/groups/-/m/t/1008112#ksaq_reply) [[docs]](https://reference.wolfram.com/language/ref/Dot.html).

### Matlab
Matlab **conjugates the first argument** [[docs]](https://nl.mathworks.com/help/matlab/ref/dot.html#bt9p8vi-1)
```matlab
A = [1i 0];
B = [1 0];
dot(A, B)
% ans = 0.0000 - 1.0000i
```

### Numpy
Numpy has two dot products. First one, `dot`, is meant for general N-dimensional arrays and it **doesn't conjugate** [[docs]](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html):
```python
>>> np.dot([2j, 3j], [2j, 3j])
(-13+0j)
```

The second one is `vdot` and it performs “the dot product of two vectors”. It **conjugates the first argument** [[docs]](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vdot.html):
```python
>>> a = np.array([1+2j,3+4j])
>>> b = np.array([5+6j,7+8j])
>>> np.vdot(a, b)
(70-8j)
>>> np.vdot(b, a)
(70+8j)
```

### Sympy
Classic sympy **doesn't conjugate** [[live]](https://live.sympy.org/?evaluate=M%20%3D%20Matrix(%5BI%2C%200%5D)%0A%23--%0AM.dot(M)%0A%23--%0A):
```python
>>> M = Matrix([I, 0])
>>> M.dot(M)
-1
```

Sympy for QM **conjugates symbolically**, but since the operations are coordinate-independent, it's impossible to tell which of the vectors is conjugated [[live]](https://live.sympy.org/?evaluate=from%20sympy.physics.quantum%20import%20*%0AA%20%3D%20Ket(%27A%27)%3B%20B%20%3D%20Ket(%27B%27)%0Aconjugate(%20Dagger(A)%20*%20B%20)%20%3D%3D%20Dagger(B)%20*%20A%0A):
```python
>>> from sympy.physics.quantum import *
>>> A = Ket('A'); B = Ket('B')
>>> conjugate( Dagger(A) * B ) == Dagger(B) * A
True
```

**Comment by josdejong** [comment]
Sorry for the late reply. Thanks @m93a this is a very clear and useful overview! . 

So conclusions are:

1. _If_ we conjugate we do the _first_ argument
2. There is no standard behaviour in whether or not to conjugate. So we simply have to decide. I sort of like what Numpy does by simply offering two different implementations. I think though for mathjs it makes sense to offer just one solution which does conjugate, which will be a (small) breaking change in the current behavior. Do you agree? If so, I think #1773 is ready to be merged, right?

**Comment by m93a** [comment]
Hey Jos,
Yes, I agree that in mathjs it makes sense to offer just one solution which does conjugate.
I also confirm that the PR is ready to be merged :)
