### ISSUE TITLE
 Is it possible to make a parser with a zero initial configuration?

### ISSUE THREAD

**Issue by NikitaIT** [josdejong/mathjs#1763]
I use mathjs in several formula editors and would like to be able to explicitly set all allowed operations. Perhaps there is some way to reduce dependencies?

One of the problems I noticed:
`// before parse => after parse`
`and 4` => `"and" * 4`
`4 and 5` => ` 4 and 5`
in one of my editors "*" and "="(in inline formulas) are not valid operations, how can I forbid them?

`create({}, {})` has:
> ["isNumber", "isComplex", "isBigNumber", "isFraction", "isUnit", "isString", "isArray", "isMatrix", "isCollection", "isDenseMatrix", "isSparseMatrix", "isRange", "isIndex", "isBoolean", "isResultSet", "isHelp", "isFunction", "isDate", "isRegExp", "isObject", "isNull", "isUndefined", "isAccessorNode", "isArrayNode", "isAssignmentNode", "isBlockNode", "isConditionalNode", "isConstantNode", "isFunctionAssignmentNode", "isFunctionNode", "isIndexNode", "isNode", "isObjectNode", "isOperatorNode", "isParenthesisNode", "isRangeNode", "isSymbolNode", "isChain", "on", "off", "once", "emit", "config", "expression", "import", "create", "factory", "type", "json", "error", "ArgumentsError", "DimensionError", "IndexError"]

`create({ parseDependencies }, {})` has all from `create({}, {})` and:
```js
47: "Node"
48: "Matrix"
49: "DenseMatrix"
50: "BigNumber"
51: "Complex"
52: "Fraction"
53: "typed"
54: "equalScalar"
55: "SparseMatrix"
56: "matrix"
57: "subset"
58: "AccessorNode"
59: "ArrayNode"
60: "AssignmentNode"
61: "ResultSet"
62: "BlockNode"
63: "ConditionalNode"
64: "ConstantNode"
65: "FunctionAssignmentNode"
66: "abs"
67: "addScalar"
68: "bignumber"
69: "fraction"
70: "number"
71: "numeric"
72: "divideScalar"
73: "equal"
74: "zeros"
75: "round"
76: "ceil"
77: "floor"
78: "fix"
79: "format"
80: "isNumeric"
81: "multiplyScalar"
82: "identity"
83: "multiply"
84: "pow"
85: "unaryMinus"
86: "subtract"
87: "Unit"
88: "SymbolNode"
89: "FunctionNode"
90: "Range"
91: "size"
92: "IndexNode"
93: "ObjectNode"
94: "OperatorNode"
95: "ParenthesisNode"
96: "RangeNode"
97: "RelationalNode"
98: "parse"
99: "type"
```

**Comment by NikitaIT** [comment]
workaround
```
const exclude = [
    "equalScalar",
    "matrix",
    "subset",
    "abs",
    "addScalar",
    "bignumber",
    "fraction",
    "number",
    "numeric",
    "divideScalar",
    "equal",
    "zeros",
    "round",
    "ceil",
    "floor",
    "fix",
    "format",
    "multiplyScalar",
    "identity",
    "multiply",
    "pow",
    "unaryMinus",
    "subtract",
    "size"
  ];
const throw = () => {
 throw new Error();
})
exclude.map(x => (mathJsAndOrNotParenthesis[x] = throw));
```

**Comment by josdejong** [comment]
You can disable built-in operators by:

1. Replacing the actual implementations of `multiply` (operator `*`) with a function throwing an error.
2. And/or parsing the expression into an [expression tree](https://mathjs.org/docs/expressions/expression_trees.html), then check whether the tree contains non-supported operators by searching for occurrences of say `OperatorNode` with `op === '*'`, and if found, throw an error.

**Comment by NikitaIT** [comment]
@josdejong Thank you, these are really two methods that I use now, the second, unlike the first, allows you to determine the specific location of the error in the expression. 
It would be nice to someday see the pluginable AST parser, how it was done with dependencies.

**Comment by josdejong** [comment]
👍
