### ISSUE TITLE
Why is SparseMatrix always two-dimensional?

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#1770]
I noticed that sparse matrices can only be 2-dimensional, as opposed to dense matrices which can be used to store a tensor of any rank. Why is that? I don't see it documented anywhere and it seems very counter-intuitive to me.
```javascript
math.sparse([1]).size() // [1,1]
math.sparse([[1]]).size() // [1,1]
math.sparse([[[1]]]).size() // TypeError: Unexpected type of argument in function equalScalar
```

**Comment by josdejong** [comment]
I think it simply started as 2d because that was the most common case and straightforward to implement, and currently all functions are implemented and optimized for 2d. 

It would be nice to have support for n-dimensional `SparseMatrix`, but that is probably not trivial to implement.

**Comment by m93a** [comment]
For people who decide to implement N-dimensional SparseArray in the future: A whole bunch of methods in mathjs depend on the fact that SparseArray is always 2-dimensional and a lot of type checking and unit testing will have to be added.
