### ISSUE TITLE
switch to dependabot

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#1777]
Given: 
![image](https://user-images.githubusercontent.com/16308754/76707006-ae885100-66e3-11ea-828e-5b716a4938ec.png)

I thought it might be a good time to consider switching to https://dependabot.com/ for managing mathjs's dependancies. It has a couple of nice features like automatically rebasing pull requests and automatically recreating pull requests when there are further version bumps. Other upsides include being owned by microsoft and therefore having a tighter integration into github.

I have used it for other projects and found it to be very good.

**Comment by josdejong** [comment]
Yes indeed, GreenKeeper is about to stop!

I have not much experience with dependabot, but it sounds good to me.

Snyk was also already integrated with mathjs, I've clicked the migration button, so far it fails to migrate the mathjs project.

**Comment by josdejong** [comment]
hm maybe Snyk is working after all, not sure, let's see if it starts creating PR's for dependencies. I've configured it to test daily.

I've also connected Dependabot. It looks much simpler than Snyk. Let's keep them both for a couple of weeks before we decide to go for one or the other ok?

**Comment by harrysarson** [comment]
Sounds good!

**Comment by harrysarson** [comment]
Done!
