### ISSUE TITLE
fraction with unary minus operator multiplying a variable produce a different tree

### ISSUE THREAD

**Issue by mt4c** [josdejong/mathjs#1778]
```
console.log(JSON.stringify(math.parse('4/3x')));
```
results in

{"mathjs":"OperatorNode","op":"*","fn":"multiply","args":[{"mathjs":"OperatorNode","op":"/","fn":"divide","args":[{"mathjs":"ConstantNode","value":4},{"mathjs":"ConstantNode","value":3}],"implicit":false},{"mathjs":"SymbolNode","name":"x"}],"implicit":true}

```
console.log(JSON.stringify(math.parse('+4/3x')));
console.log(JSON.stringify(math.parse('-4/3x')));
```
results in

{"mathjs":"OperatorNode","op":"/","fn":"divide","args":[{"mathjs":"OperatorNode","op":"+","fn":"unaryPlus","args":[{"mathjs":"ConstantNode","value":4}],"implicit":false},{"mathjs":"OperatorNode","op":"*","fn":"multiply","args":[{"mathjs":"ConstantNode","value":3},{"mathjs":"SymbolNode","name":"x"}],"implicit":true}],"implicit":false}

{"mathjs":"OperatorNode","op":"/","fn":"divide","args":[{"mathjs":"OperatorNode","op":"-","fn":"unaryMinus","args":[{"mathjs":"ConstantNode","value":4}],"implicit":false},{"mathjs":"OperatorNode","op":"*","fn":"multiply","args":[{"mathjs":"ConstantNode","value":3},{"mathjs":"SymbolNode","name":"x"}],"implicit":true}],"implicit":false}

the first expression was parsed as ```(4/3)x```

the next expressions were parsed as ```4/(3x)``` and ```-4/(3x)```

Why do the unary operators make the differences

**Comment by m93a** [comment]
This is a known bug in the parser, see #1431.

**Comment by josdejong** [comment]
Let's continue any discussion in #1431. Any help solving the issue is very welcome.
