### ISSUE TITLE
issue with accessing members in scope

### ISSUE THREAD

**Issue by tlitovsk** [josdejong/mathjs#1787]
import {parse,evaluate} from 'mathjs'
let expression = "1+b"
let node = parse(expression)
let tcode = node.compile()
console.log(node)
let bla = {b:Number(1)}
let result = evaluate(["b=1","1+b"])
let result2 = evaluate("1+b",bla)
let result3 = tcode.evaluate(bla)

result2 fails with TypeError: Value has unknown type. Value: [object Object]
result3 fails with Error: no access to property "b"

**Comment by josdejong** [comment]
This is probably because you've created a number as `Number(1)`, which is not supported. 
Can you try creating as `{ b: 1 }`?

**Comment by bornova** [comment]
Could it be just a typo?  Changing `let bla = {b:Number(1)}` to `let bla = {b:number(1)}` fixes it on my end.

**Comment by josdejong** [comment]
@bornova I'm not sure about your example, I don't think that is plain JavaScript as in the example of @tlitovsk right?

**Comment by josdejong** [comment]
@tlitovsk what version of mathjs are you using? I just tried to actually reproduce your issue, but it simply evaluates and does not throw an error.

**Comment by bornova** [comment]
> @bornova I'm not sure about your example, I don't think that is plain JavaScript as in the example of @tlitovsk right?

You are right.  I was just evaluating each line using math.evaluate therefore using the built in `number` function of mathjs.  As you mentioned, no errors in plain JS.

Sorry for the confusion.
