### ISSUE TITLE
toExponential should not add extra zeros to the number if using bigger precision

### ISSUE THREAD

**Issue by jcubic** [josdejong/mathjs#1791]
I'm testing the function from your API:
```javascript
toExponential(10e+10, 16)
```

I think that it should not return multiple zeros after the dot. The proper result for is single zero if the value is `1.0` and if it's `1.1` it should not get extra zeros.

So this should return: `1.0e11` not `1.000000000000000e+11`.

The code that is responsible for this is in number.js:

https://github.com/josdejong/mathjs/blob/08feb7fc7936df5c35c2b3ab8a88ed903cd39f02/src/utils/number.js#L416

it should only add one zero if last digits is not 0.

**Comment by josdejong** [comment]
This is simply how the `exponential` notation of function `format` is implemented. From the docs:

> `precision`: number A number between 0 and 16 to round the digits of the number. In case of notations ‘exponential’, ‘engineering’, and ‘auto’, precision defines the total number of significant digits returned. In case of notation ‘fixed’, precision defines the number of significant digits after the decimal point. precision is undefined by default.

If you do not want to have all the zeros returned, you can either omit specifying `precision`, or first round your value to 16 digits and then format it with notation `fixed`, `precision: 1`, or something like that.

**Comment by jcubic** [comment]
Thanks, I wanted to use the code in my Scheme/Lisp Interpreter, but it was not exactly what I needed, I've decided to use use normal float and use whatever JavaScript is returning for float numbers.

**Comment by josdejong** [comment]
:+1: simple solutions are often the best :)
