### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ThugDenGamer** [josdejong/mathjs#1797]
There are some bugs in multiplication and converting inch to centimeter.

**Comment by harrysarson** [comment]
Could we have some reproducible code showing the bugs? Then we might be able to work towards the fix.

**Comment by ThugDenGamer** [comment]
Y

**Comment by ThugDenGamer** [comment]
![15859297497121125713434](https://user-images.githubusercontent.com/58256550/78381290-d2053400-75dd-11ea-9fc9-b4f0ae39a952.jpg)
For example

**Comment by ThugDenGamer** [comment]
![15859299514691859417561](https://user-images.githubusercontent.com/58256550/78381604-46d86e00-75de-11ea-9b42-c4a61746e118.jpg)
And another example

**Comment by Veeloxfire** [comment]
This is a floating point arithmetic error. A fundamental error of floating point numbers. Try this in many languages that use them and you get the same answer of `12.7*2.54=32.257999999999996` which is obviously doesnt. I tested this on python, Javascript and Ruby quickly to check and the default language will give this (c++ and c# gave rounded answers if you really need the precision I guess)
Here is a video by Tom Scott to explain: https://www.youtube.com/watch?v=PZRI1IfStY0

**Comment by harrysarson** [comment]
@ThugDenGamer we have some docs on rounding issues which might help you https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors.

I'm gonna close this as we dont have anything actionable here.
