### ISSUE TITLE
'npm run-script build-and-test' fails

### ISSUE THREAD

**Issue by Veeloxfire** [josdejong/mathjs#1806]
I found this when writing some stuff recently and fixed it by changing  `'bin/cli.js '` to `'node bin/cli.js '` in test/node-tests/cli/cli.test.js
Does this break on other machines or is it just me?

To reproduce:
Fork the repo
Run 'npm run-script build-and-test'
Fails as shown in image
![image](https://user-images.githubusercontent.com/58116051/78509793-9fe40580-7788-11ea-9d61-5164ed1ca614.png)

It only fails on `build-and-test` as far as I can tell because this runs `test:all` compared to the normal `test` script which runs `test:src`

It is also reproducable with `npm run-script test:node` and this is much faster

**Comment by harrysarson** [comment]
Which operating system are you on?

**Comment by Veeloxfire** [comment]
Ah yeah Im on windows. Thought that might be the issue. And I'll happily look in to that!

**Comment by harrysarson** [comment]
> It is fixed by just putting the node prexif on the command so would it make sense to just do that or would that fail on linux and mac?

Go for it, we would love a PR. I very much doubt it will fail, but if it does our CI will catch it 👍

**Comment by Veeloxfire** [comment]
As a sidenote the file was created this way so I guess it would always have been broken on windows maybe and nobody ran `test:node` somehow

**Comment by harrysarson** [comment]
The file was probably added by someone using linux or macos.

**Comment by josdejong** [comment]
> The file was probably added by someone using linux or macos.

Yeah I'm running linux.

This issue is fixed now via #1807. Thanks again @Veeloxfire
