### ISSUE TITLE
lack of precision for trigonometry functions

### ISSUE THREAD

**Issue by KevinGervais** [josdejong/mathjs#1820]
with big numbers when i do
cos(90 deg)
it gives me
-8.9259567433588466765*10^(-102)
but when I do cos(0) the result is 1, so the precision is exact here.
When I do sin(pi rad)
it gives me
-1.7851913486717693353*10^(-101)
But when I do sin(pi/2 rad)  the result is 1, so the precision is exact here.

What I would expect:
That for all trigonometric functions, we handle detection of resulting zero

By example for cos, when we are in degrees mode,
if the param of cos is 90 +180 * n where n is natural, return zero

Thanks you for your effort of contribution!

**Comment by josdejong** [comment]
Thanks for your input Kevin. See for example #755 and #133 for some in-depth discussion on this subject.
