### ISSUE TITLE
Is there a way to entirely disable implicit multiplication?

### ISSUE THREAD

**Issue by ElectrifyPro** [josdejong/mathjs#1821]
I saw [this](https://github.com/josdejong/mathjs/issues/1334) issue but it unfortunately doesn't seem to be implemented. Is there a workaround I could use to do this?

**Comment by josdejong** [comment]
Yes, a good workaround is described in the issue you're linking too: https://github.com/josdejong/mathjs/issues/1334#issuecomment-442821198

**Comment by ElectrifyPro** [comment]
Thank for reminding me I need to improve my awareness

**Comment by josdejong** [comment]
😂 you're welcome
