### ISSUE TITLE
show math expression evaluation order i.e. PEMDAS

### ISSUE THREAD

**Issue by kmacthecoder** [josdejong/mathjs#1826]
looked through the docs but couldn't find an implementation for this so wanted to double check - is there a feature that shows/explains how the math expression is evaluated, like an abstract syntax tree? e.g. 1+5 * 2 means do 5*2 first and then add 1

**Comment by kmacthecoder** [comment]
came across https://mathjs.org/docs/expressions/expression_trees.html

**Comment by josdejong** [comment]
:+1: Yes you have a lot of flexibility with that. Also, the option `parenthesis: 'all'` of the method `.toString` may be useful.
