### ISSUE TITLE
Ignore values like "null" in array functions

### ISSUE THREAD

**Issue by Big-Gremlin** [josdejong/mathjs#1829]
Is there a way to ignore specific values in arrays when using array functions?
Please without overwriting all functions. :)

Example:
```
const testArray = [1, 2, 3, null, 5];
math.evaluate('max(testArray)', {testArray: testArray});
// returns TypeError: Cannot calculate max, unexpected type of argument (type: null, value: null)
```

Default JavaScript Math works fine:
```
Math.max(testArray);
// returns 5
```

`NaN` or `undefined` instead of `null` also doesn't work.

An optimal solution for me would be to ignore specific objects.
```
const testArray = [1, 2, 3, { message: "An error message" }, 5];
math.evaluate('max(testArray)', {testArray: testArray});
// should return 5
```

The same array should work with all other array functions. 
In my case, the usage of mathjs is very dynamic. The content of the array can be the result of an other expression. Sometimes I need a value from the array based on an index, sometimes I work with a single value, for the array length I need the entire array... That's why I can't clean up / transform / filter the array before evaluation. 

**EDIT**:
If there is currently no integrated solution for my problem, is there a way to create something like a wrapper?

Example:
```
function max(array) {
    const filteredArray = array.filter(value => value !== null);
    return math.max(filteredArray);
}
```

If I want to calculate, it should be done over the wrapper-method.
```
const testArray = [1, 2, 3, null, 5];
math.evaluate('max(testArray)', {testArray: testArray});
// returns 5, because the internal call was math.max([1, 2, 3, 5]);
```

I hope, you know what I mean. :)

**Comment by josdejong** [comment]
I think you can write a little filter function to filter non-numeric values from your array before passing it to `max` I think, something like:

```js
const scope = {
  testArray: [1, 2, 3, null, 5],
  filterNumericValues: (array) => array.filter(math.isNumber)
}
math.evaluate('max(filterNumericValues(testArray))', scope) // 5
```

Would that work for you?

**Comment by Big-Gremlin** [comment]
> I think you can write a little filter function to filter non-numeric values from your array before passing it to `max` I think, something like:
> 
> ```js
> const scope = {
>   testArray: [1, 2, 3, null, 5],
>   filterNumericValues: (array) => array.filter(math.isNumber)
> }
> math.evaluate('max(filterNumericValues(testArray))', scope) // 5
> ```
> 
> Would that work for you?

Thx for your answer.  :)
That would work, but the problem is, in my case it should be done on every max call, every min call, ...

I found the solution with that simple wrapper function like this: 

```js
const defaultMaxFunc = mathjs.max;
const newMaxFunc = factory('max', [], ({ multiply, unaryMinus }) => {
  return (x) => {
    x = Array.isArray(x) ?  x.filter(value => !isNaN(value)) : x;
    return defaultMaxFunc(x);
  };
});

math.import([newMaxFunc], { override: true });
```

This is very simple an can be done on the same way with all needed functions. :)

**Comment by josdejong** [comment]
> That would work, but the problem is, in my case it should be done on every max call, every min call, ...

You can indeed override the built-in functions with your own wrapper which does do the filtering 👍 . Thanks for sharing your solution.
