### ISSUE TITLE
math.evaluate giving wrong answers

### ISSUE THREAD

**Issue by Shocks50541** [josdejong/mathjs#1836]
When i try to use math.evaluate, it works fine when its something like 1+2, but when i do `math.evaluate("12.7cm to inch")` it will show this when i log it to console, 
![image](https://user-images.githubusercontent.com/8074090/80727485-afdbd480-8afd-11ea-839d-6467f32e79c9.png)

**Comment by harrysarson** [comment]
I think this is some bad joke. Closing and locking according.

**Comment by harrysarson** [comment]
I am still unwilling to open your link. Would it be possible to insert the screenshot directly into the issue https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests?

**Comment by Shocks50541** [comment]
I've updated it just now

**Comment by Shocks50541** [comment]
Ooh! I think i've figured it out! For the answers for these ones where its a conversion, you have to convert it to a string afterward with `.toString()`, I don't think I saw this in the docs, if i did i must've skipped right over it, though if possible, i'd say to make it a bit clearer in the docs so that people who havent used this before don't get confused by that

**Comment by josdejong** [comment]
@Shocks50541 you indeed have to stringify using `.toString()` or `math.format(...)`.
