### ISSUE TITLE
I think this is some bad joke. Closing and locking according.

### ISSUE THREAD

**Issue by Shocks50541** [josdejong/mathjs#1838]
I think this is some bad joke. Closing and locking according.

_Originally posted by @harrysarson in https://github.com/josdejong/mathjs/issues/1836#issuecomment-621883598_

Its not a bad joke, i looked at the docs, was trying for about an hour and i couldnt get this to work? if you're talking about the link, its just my custom domain that i use for image hosting. look at how theres a .png at the end of it

**Comment by Shocks50541** [comment]
didnt really include the actual issue in this one but w/e. point stands

**Comment by harrysarson** [comment]
Okay, maybe I misunderstood/overreacted, will reopen the ticket.
