### ISSUE TITLE
Providing toTeX for units

### ISSUE THREAD

**Issue by skgadi** [josdejong/mathjs#1849]
Developing a function `math.unit.toTeX()` would be a good idea.

Thank you.

**Comment by josdejong** [comment]
Thanks for your suggestion Suresh. The method `toTex` is implemented on parsed expressions and not on data types like Unit or DenseMatrix. It could be interesting. 

On the other hand, maybe the following works just as fine: 

```js
function toTex (value) {
  return math.parse(math.format(value)).toTex()
}

const width = math.unit('5 cm')
console.log(toTex(width)) // 5~\\mathrm{cm}
```
Is that a solution for you?

**Comment by skgadi** [comment]
Perfect.

It works as expected. Thank you.

**Comment by josdejong** [comment]
👍
