### ISSUE TITLE
Wrong Formatting of Fractions

### ISSUE THREAD

**Issue by MarkusThill** [josdejong/mathjs#1854]
I have to evaluate some user inputs and then output the result of the evaluation as a LaTex-expression. Currently, I only manage to achieve this with the following lines of code:

```
math.config({
        number: 'Fraction'
}); 

let result = math.evaluate(expr, options.scope);   
let formatted = math.format(result, { fraction: 'ratio' });
let tex = math.parse(formatted).toTex();
``` 

It would be nice, if I could directly generate a LaTex String from the variable `result`. 

However, I have another, more severe problem: I want to work, where possible, with fractions. Also, fractions should be generated with the toTex() function, if necessary. The problem is that when I have trivial fractions such as "4/1" or "6/3" then I do not want them to be displayed this way. Rather, they should be treated as regular integers. I tried to use math.simplify(), but this only works for some simple cases and not for fractions in matrices, etc.
Is there any solution to this problem? Or do I have to sanitize the output myself?

[Edit]
I found the problem in the function `OperatorNode.prototype._toTex = function (options)...`. Not exactly sure why we end up there, if we have fractions. Currently, a fast hack of mine is the following:

```
switch (this.getIdentifier()) {
        case 'OperatorNode:divide':
          // op contains '\\frac' at this point
            // added this...
            if(rhsTex === "1")
                return '{' + lhsTex + '}';
...
```

**Comment by josdejong** [comment]
Thanks for your inputs Markus! 

I think you're discussing two things here:

1.  It would be nice if we would have a function `toTex(data)`. Which works for all data types such as Fractions. The workaround of data -> format as string -> parse -> toTex works in most cases but can be tricky.

2.  You describe specific cases like `4/1` where do or do not want to format a fraction as a fraction. Whether or not you want to simplify such cases depends on your application. I think we should not add such rules to `OperatorNode.prototype._toTex`, this function should be "dumb" and just output what is there. What you could do is indeed use `simplify`, or write this logic yourself like: 

    ```js
	math.config({
        number: 'Fraction'
	}); 

	let result = math.evaluate(expr, options.scope);   
	let formatted = math.isInteger(result) 
	  ? math.format(result, { fraction: 'decimal' })
	  : math.format(result, { fraction: 'ratio' });
	let tex = math.parse(formatted).toTex();
    ```

**Comment by MarkusThill** [comment]
Thanks for your comments. Currently, I am doing fine with your suggestion in 1.

Would your suggestion in 2. also work if I have fractions in a matrix? I have cases where I have a sum of matrices. The matrices themselves can contain integers and fractions at the same time. I did not manage to solve that problem yet.

**Comment by josdejong** [comment]
@MarkusThill it will probably not hold for more complicated cases like a Matrix containing different types of values, but you can easily try out what happens 😄 . You can probably use `Matrix.map` to map over all individual values to turn it into formatted Tex, not sure though.

**Comment by MarkusThill** [comment]
Okay. Thanks for your help. I will try to make the more complex scenarios work as well.
