### ISSUE TITLE
Possible error in the documentation for math.nthRoots(x)

### ISSUE THREAD

**Issue by skgadi** [josdejong/mathjs#1855]
Hi,

I am trying to use `math.nthRoots(x)` for matrices but it seems not working. The documentation says it takes the inputs "number | BigNumber | Fraction | Complex | Array | Matrix", but when I use matrices, system throws error "Uncaught TypeError: Unexpected type of argument in function nthRoots (expected: Complex or number or Fraction or string or BigNumber, actual: Matrix, index: 0)"

Also, it seems the parameter description, return value description are incorrect.

Please look into it. Thank you.

Best regards

**Comment by josdejong** [comment]
Thanks for bringing this up, it's an error in the documentation indeed. The implementation only supports scalars: https://github.com/josdejong/mathjs/blob/develop/src/function/arithmetic/nthRoots.js#L39-L43

**Comment by josdejong** [comment]
Docs are fixed now in v7.0.1

**Comment by skgadi** [comment]
Thank you.
