### ISSUE TITLE
How to deal with running out of RAM or freezing CPU with heavy operations

### ISSUE THREAD

**Issue by jagamypriera** [josdejong/mathjs#1866]
Run this function will causes spike on CPU usage and eventually lead to crash
`math.evaluate('-Infinity:Infinity')`

**Comment by josdejong** [comment]
Yes that's for sure. I can give you plenty examples of mathjs expressions that will run out of memory or will keep your CPU busy forever. Do you have a concrete question about this?

**Comment by jagamypriera** [comment]
Is there any way to avoid it? Like return Infinity instead of keep CPU busy

**Comment by josdejong** [comment]
This is a very good question :). 

Well, this is just one example of creating an insanely large matrix, but there are many ways. Like `math.evaluate('0:1e9999')` or so. And there are many other ways to fill RAM or keep the CPU busy. I think it's not doable to try "lock down" the inputs that the user can give to safe ones.

One solution is to run calculations in a WebWorker or child process (depending on whether you run in the browser or in node.js). This is for example done in the web service https://api.mathjs.org/, which can handle calculations that go out of memory or take longer than 10 seconds. The web service uses [workerpool](https://github.com/josdejong/workerpool) to achieve this, but you can use any similar library.
