### ISSUE TITLE
Security again: how to limit the scope.

### ISSUE THREAD

**Issue by audetto** [josdejong/mathjs#1876]
I am using math.js for a website where the user can draw a custom function.

Security-wise this might be a nightmare as the input string is user controlled, so I would like to know if there is a way to completely limit the scope of what symbols are available.

Very simple use case: try to parse this function "s" and call it with any scope you want (except one where you set "s").

I was really surprised of what it actually returned. The s it finds in scope seems to come from Node.js

```
  Node.prototype.compile = function () {
    var expr = this._compile(mathWithTransform, {});

    var args = {};
    var context = null;

    function evaluate(scope) {
      var s = scope || {};

      _validateScope(s);

      return expr(s, args, context);
    }
```

I am not sure I am getting the right end of the stick here.

So is it possible to remove every possible symbol except the ones that are explicitly allowed? Or this is impossible in javascript?

Or, after parsing, check all the free variables required for a function?

Regards.

**Comment by josdejong** [comment]
Hi Andrea, very good to hear that you're thinking through the security implications!

I suppose you've read this page: https://mathjs.org/docs/expressions/security.html (if not please do so)

> The s it finds in scope seems to come from Node.js

This is not true, math.js has an internal class called `Node`, and classes like `FunctionNode`, `OperatorNode`, etc. [See source code](https://github.com/josdejong/mathjs/tree/develop/src/expression/node).

The expression parser has excellent options to investigate what is being parsed, and to check the parsed expression against your security criteria, and only when all is ok evaluate the expression.  You can parse the expression using `math.parse`, and then `traverse` the returned expression to check everything against your whitelist. Besides that, you can create a mathjs instance (with `create`) with a minimal number of functions, constants, and data types to reduce the API surface.

Docs:
https://mathjs.org/docs/expressions/parsing.html#parse
https://mathjs.org/docs/expressions/expression_trees.html 
https://mathjs.org/docs/custom_bundling.html

**Comment by audetto** [comment]
> 
> > The s it finds in scope seems to come from Node.js
> 
> This is not true, math.js has an internal class called `Node`, and classes like `FunctionNode`, `OperatorNode`, etc. [See source code](https://github.com/josdejong/mathjs/tree/develop/src/expression/node).
> 

I was wrong.
The s is a unit (presumably seconds).

I found how to solve my problem

import { create, all, MathJsStatic } from 'mathjs/number';

but VScode warns me that 

Could not find a declaration file for module 'mathjs/number'. '/home/andrea/projects/aio/some-app/node_modules/mathjs/number.js' implicitly has an 'any' type.
  If the 'mathjs' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mathjs`t

But it still works.

Is this something you might want to fix?

**Comment by josdejong** [comment]
Yes, `s` is indeed the unit seconds, and there are more.

If the TypeScript definitions are not up to date we should of course update them. Help would be very welcome!

**Comment by audetto** [comment]
I have another issue now.
Even when importing from mathjs/number an expression like "sin" is valid and when evaluated returns a function.

Is this the intended behaviour?
Is there a way to enforce that functions are actually called? Or should I check the return type?

**Comment by josdejong** [comment]
That's correct, like in JavaScript, fuinctions are first class citizens. A function can return a function, and variables can contain a function. After evaluation you can check the type of the result and of defined variables to see if they are functions if you want to lock that down.
