### ISSUE TITLE
Implicit multiplication treated as function 

### ISSUE THREAD

**Issue by xZGit** [josdejong/mathjs#1886]
when i hava a expresson something like "a(x+1)=2"

what i want is "a*(x+1)=2"

but actually it was treated as function node like this

```
Node {
  fn: Node { name: 'a' },
  args:
   [ Node { implicit: false, op: '+', fn: 'add', args: [Array] } ],
  comment: '' }
```

what i do to avoid this is use transform like below

```javascript
 const transformed = node.transform(function (node) {
 
        if(node.type === "FunctionNode" && !["sqrt", "abs", "pow", "nthRoot"].includes(node.fn.name)){  
            return new math.OperatorNode("*", "multiply", [node.fn, node.args[0]], true)
        }

        return node;
    });
```

Is  there any better solution to fix this?

**Comment by josdejong** [comment]
Implicit multiplication has tricky edge cases like this one. For the parser, there is no difference between parsing `sin(x+1)` or `a(x+1)`, only at evaluation the variables (`sin` or `a` respectively) are resolved and then indeed invoked as a function. 

For reference here a link to the documentation about explicit multiplication: 
https://mathjs.org/docs/expressions/syntax.html#implicit-multiplication

Your approach with the transform is a good one to prevent this. We also discussed creating a configuration option to allow disabling implicit multiplication, see #1334.
