### ISSUE TITLE
how to import unit for custom build uning in browser - not working on my side

### ISSUE THREAD

**Issue by qadeesz** [josdejong/mathjs#1887]
### i use these libraries for unit conversion in web console  
- math.import(require('mathjs/lib/expression/node'));
- math.import(require('mathjs/lib/expression/embeddedDocs/construction/unit.js'));
- math.import(require('mathjs/lib/type/unit'));
**but its not working** 
![image](https://user-images.githubusercontent.com/25366607/84619878-d8722f00-aeef-11ea-9967-c8641bff175c.png)
**return object sometime missing "inch"**
![image](https://user-images.githubusercontent.com/25366607/84619964-1a9b7080-aef0-11ea-88d7-c8b10e67cb75.png)

Which line of code import for unit conversion perform in browser by custom build please help 
_**mathjs version : 5.10.3**_

**Comment by josdejong** [comment]
Qadees the `mathjs-expression-parser` library is using a very old version of mathjs. Custom building has changed a lot in the mean time, and you probably don't need this library anymore if you use the latest version of mathjs.

See docs: https://mathjs.org/docs/custom_bundling.html

**Comment by qadeesz** [comment]
i use  **custom_build** example but **not woking** in browser how export unit module by custom build using latest version of mathjs.

**Comment by josdejong** [comment]
I'm not sure which example "custom_build" you're referring to.

Do you mean your question is how to create a bundle yourself which exposes the "window.math" so you can use it as library in the browser? If so, that are things that you can configure with Webpack/Browserify. For example in case of Webpack you can define the following in your config:

```
{
  output: {
    library: 'math',
    libraryTarget: 'umd',
    // ...
  }
  // ...
}
```

**Comment by qadeesz** [comment]
thanks for response
firstly i build custom_loading.js to custom_loading.min.js using by this command:
_**npx webpack custom_loading.js -o custom_loading.bundle.js --mode=production**_
[https://mathjs.org/examples/advanced/custom_loading.js.html](url)
custom_loading.min.js its building but not work in browser

so, i want to build a math.bundle.min.js file only use these modules with latest version of mathjs
- math.unit
- math.to
- math.number

**Comment by josdejong** [comment]
> custom_loading.min.js its building but not work in browser

Just to be sure I executed the command to create the bundle, and I can load it perfectly fine in the browser or run it using node.js, and as expected it outputs the following in the developer console:

```
c = 16/21
d = 7/9
```
Does that not work for you? I think it would help to first get that example working. Then the next step of bundling only `math.unit`, `math.to`, and `math.number` should be very easy: just replace the functions created and used in the example with these functions.

**Comment by josdejong** [comment]
Will close this now due to lack of response. Feel free to reopen if needed.
