### ISSUE TITLE
math.js pre-compressed with Brotli:11 on open source CDN

### ISSUE THREAD

**Issue by praisedpk** [josdejong/mathjs#1888]
Hi @josdejong 

I have added math.js on PageCDN, compressed it with brotli:11 to reduce file size, and enabled immutable caching for extreme results. The files are available on CDN here: https://pagecdn.com/lib/mathjs

Current size of [math.min.js](https://pagecdn.io/lib/mathjs/7.0.1/math.min.js) for version 7.0.1 is **113.28 KB**. Brotli:11 reduced the file size sharply. Adding this CDN link on [download page](https://mathjs.org/download.html) may be helpful for some users looking for small file sizes.

Thanks.

**Comment by josdejong** [comment]
Thanks, I've added the link on the downloads page of the website: https://mathjs.org/download.html
