### ISSUE TITLE
math.js seems to be not working my React calculator (using hooks) and producing React error #321

### ISSUE THREAD

**Issue by konstantinkrumin** [josdejong/mathjs#1889]
So basically I'm trying to create a Calculator app with React using hooks and for calculating the total value I'm using math.js library, however it seems to be producing a Minified React error #321, which looks like this:

> Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app [...].

I'm not sure why exactly it is happening since the function, where I have math.compile() and .evaluate() methods, is logging out correct string that is getting passed into math.compile(). Also when I tested this in plain JS file I got correct output:

```const nums = '3+5*6-2/4'

const code1 = math.compile(nums)
const result = code1.evaluate()
console.log(result) // produces 32.5 as it is supposed to
```

But when the following function is called in the main React component on button click:

```function handleEqual() {
  let totalRow = calcRow.slice(0,)

  if (regex.test(displayNum)) {
    if (displayNum === '-' && regex.test(calcRow[calcRow.length-1])) {
    totalRow = totalRow.slice(0, totalRow.length-1)
    }
  
    totalRow = totalRow.slice(0, totalRow.length-1)
  } else {
    totalRow = totalRow.concat(displayNum)
  }

  console.log(totalRow)

  const total = math.compile(totalRow)
  const result = total.evaluate()
  console.log(result)
  // setCalcRow(totalRow + '=' + result)
  // setDisplayNum(result)
  // setTimeout(() => {
  //   setCalcRow(totalRow + '=' + result)
  //   setDisplayNum(result)
  // }, 500)

  setIsCalculated(true)
} 
```

I get the aforementioned error. Why would it be happening and would could be done to get this issue fixed?

Here is my [pen](https://codepen.io/konstantinkrumin/pen/gOPPaJB?editors=0011) with the whole project code just in case.

Thanks in advance, Konstantin

**Comment by josdejong** [comment]
Thanks for reporting and sharing the application Konstantin. It's a bit hard to pinpoint what exactly is going wrong in the full application. Is it possible to create a minimal example showing what's going wrong? (i.e. the whole application stripped, leaving over the `.compile `and `.evaluate` and console.logs?

**Comment by konstantinkrumin** [comment]
Hello, 

I created a separate pen with using math.js in a minimal React component and for some reason it still seems to be not working for me. I posted it [here](https://codepen.io/konstantinkrumin/pen/eYJvwBz?editors=0011).

```
function App() {
  const expression = "3+5*6-2/4"
  const { total, setTotal } = React.useState(0)
  
  function handleCalc() {
    const total = math.compile(expression)
    const result = total.evaluate()
    setTotal(result)
    console.log(result)
  }
  
  return (
    <div>
      <h1>Calculator</h1>
      <p>Expression: 3+5*6-2/4</p>
      <button onClick={handleCalc}>Calculate</button>
      <h1>{total}</h1>
    </div>
  )
}

ReactDOM.render(<App />, document.getElementById("root"))
```

**Comment by konstantinkrumin** [comment]
I was actually able to make the component mentioned in the last message above to work (the isolated scenario), was some typo. The issue that is I'm having seems to be more related to my React code, not to do with math.js

Thank you!

**Comment by josdejong** [comment]
Good to hear you found the cause 👍
