### ISSUE TITLE
Override built-in arithmetic expressions

### ISSUE THREAD

**Issue by alex-ppg** [josdejong/mathjs#1895]
I have scoured the documentation but found no such feature documented. I want to use the library in conjunction with custom data types to parse user-input functions and conduct operations on the custom data types. 

I found that the normal arithmetic operations are detailed in the [arithmetic.js](https://github.com/josdejong/mathjs/blob/develop/src/plain/number/arithmetic.js) file which might be slightly complex to convert to an "editable" one unless a configuration parameter is passed to the library.

If this is something of interest I would be willing to look around and contribute if possible. Alternative ideas are welcome!

**Comment by josdejong** [comment]
Thanks for sharing your ideas Alex.

I guess you mean instantiating a version of the expression parser with custom functions? This is already possible, the setup with factory functions is quite flexible. 

Just to be sure I tried out a few experiments, I added two new examples:

https://github.com/josdejong/mathjs/blob/develop/examples/advanced/custom_evaluate_using_factories.js
https://github.com/josdejong/mathjs/blob/develop/examples/advanced/custom_evaluate_using_import.js

There was already one existing example:
https://github.com/josdejong/mathjs/blob/develop/examples/advanced/custom_relational_functions.js

Is that what you mean, or do you mean something totally different?

**Comment by alex-ppg** [comment]
This is great and exactly what I wanted, thank you very much @josdejong.

**Comment by josdejong** [comment]
👍 

There can be some rough edges using these factory functions and collections like `evaluateDependencies`, and the collection of plain number functions is limited too. If you come across issues or have ideas to improve documentation please let me know.
