### ISSUE TITLE
How can I convert power function with a power on the left rather than the right

### ISSUE THREAD

**Issue by MAGNETO903** [josdejong/mathjs#1896]
I did:
`math.parse("sin(x)^2").toTex()`

This returned:
`"{\sin\left( x\right)}^{2}"`

And this looks:
![returned](https://user-images.githubusercontent.com/31848594/85730673-0c392a00-b724-11ea-9d6d-dfeee99d983e.gif)

But I need this look (like in wolfram alpha or Maxima System) :
![need](https://user-images.githubusercontent.com/31848594/85731191-7fdb3700-b724-11ea-9495-30ede0fbe05f.gif)

How can I do this with mathjs?

**Comment by josdejong** [comment]
There is no built-in option to recognize this and format it like `sin2(x)` using toTex. What you can do is create a custom `handler` in and pass that to `toTex`. In the handler you can test for every node if you're dealing with a function `pow(sin(x), 2)` and if so, output the formatting like `sin2(x)`.

See docs: https://mathjs.org/docs/expressions/customization.html#handler

**Comment by MAGNETO903** [comment]
Yes! Great!
You are right!
I wrote this code and now everything works!


`var shifted_power = function(node, options) {`
`    if (node.type == "OperatorNode") {`
`        if (node.op == '^') {`
`            if (node.args[0].type == 'FunctionNode') {`
`                var arg_1 = node.args[0].fn.name;`
`                return node.args[0].toTex(options).replace(new RegExp(arg_1), arg_1+"^{"+node.args[1].toTex(options)+"}")`
`            }`
`        }`
`     }`
`}`

`console.log(math.parse("sin(x)^2").toTex({handler: shifted_power, parenthesis: 'auto'}));`
`// return: \sin^{2}\left( x\right)`
`console.log(math.parse("ln(x)^3").toTex({handler: shifted_power, parenthesis: 'auto'}));`
`// return: \mathrm{ln^{3}}\left( x\right)`

**Comment by josdejong** [comment]
😎 thanks for sharing your solution 👍
