### ISSUE TITLE
math.expression.node is no longer works since version 7

### ISSUE THREAD

**Issue by ovk** [josdejong/mathjs#1899]
It appears that `math.expression.node` (as described in this documentation: https://mathjs.org/docs/expressions/expression_trees.html) is no longer working since MathJS 7.

You can see that it is `undefined` in 7.0.2: https://jsfiddle.net/8qr3cLyn/ . But if you switch to MathJS 6 it works find and contains constructors for all the nodes as expected (ConstantNode, SymbolNode etc.).

**Comment by josdejong** [comment]
Thanks for reporting, I see the documentation is outdated. 

The classes in `math.expression.node.*` are moved to `math.*` since v6.0.0 (should show a deprecation warning in the console), and removed since 7.0.0.

Fixed via 2df28bb.

**Comment by josdejong** [comment]
This fix has been published now in `v7.1.0`
