### ISSUE TITLE
Typo in element-wise power operator example

### ISSUE THREAD

**Issue by hogpilot** [josdejong/mathjs#1902]
The **Operators** table in the expressions syntax doc ([docs/expressions/syntax.md](https://github.com/josdejong/mathjs/blob/develop/docs/expressions/syntax.md)) has a minor typo in the example:

- Element-wise power operator `.^`
 --  The example of `[2,3] .^ [3,3]` is incorrectly shown to evaluate to `[9,27]` instead of `[8,27]`

**Comment by josdejong** [comment]
Thanks for reporting William, I've fixed it via e9cf247.
