### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by Toso82** [josdejong/mathjs#1904]
@josdejong 

Latest Angular 10  Version give this warning:

<pre>
<code>
vendor.js:404297 E:\forMca\forMca\node_modules\mathjs\es\type\bignumber\BigNumber.js depends on 'decimal.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
warnings @ vendor.js:404297
vendor.js:404297 E:\forMca\forMca\node_modules\mathjs\es\type\fraction\Fraction.js depends on 'fraction.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
warnings @ vendor.js:404297
vendor.js:404297 E:\forMca\forMca\node_modules\mathjs\es\type\complex\Complex.js depends on 'complex.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
warnings @ vendor.js:404297
vendor.js:404297 E:\forMca\forMca\node_modules\mathjs\es\core\function\typed.js depends on 'typed-function'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
warnings @ vendor.js:404297
</code>
</pre>

I can disable but. If it is possible it is something to fix.

**Comment by josdejong** [comment]
Thanks for reporting. That's a useful new warning of Angular! 

It sounds needlessly scary though.

If I understand it correctly [from this article](https://blog.angular.io/version-10-of-angular-now-available-78960babd41), the message means like "you're importing an CommonJS/AMD bundle as a whole, no possibilities for tree-shaking". In case of say lodash, you typically only need a small part of the functionality so importing the whole bundle is overkill and makes your own application needlessly large. However, in the cases of these 4 mathjs dependencies (`decimal.js`, `fraction.js`, `complex.js`, `typed-function`), we need 100% of the functionality of these libraries. So suppose there where ES module versions of the libraries, it would not lead to smaller bundles.

So, whilst it would be great if these dependencies get a modern ES version, it will not result in smaller bundles.

**Comment by TiS** [comment]
I think it may, depending what mathjs **user** will import. If only one function is required and everything is ES - it will (potentially) dramatically reduce final bundle size.

**Comment by josdejong** [comment]
Three-shaking like that is already in place :) 

See https://mathjs.org/docs/custom_bundling.html for more information.

**Comment by optimistex** [comment]
> Three-shaking like that is already in place :)
> 
> See https://mathjs.org/docs/custom_bundling.html for more information.

@josdejong 
I've tried, but it is still heavy.
The full bundle is ~530Kb. I need only the function `intersect`, and I've got ~136Kb bundle. It's too much. Well done, but too heavy yet.

**Comment by josdejong** [comment]
Yeah, see the explanation at https://mathjs.org/docs/custom_bundling.html#bundle-size. This is probably because `intersect` depends on matrix related stuff, so the matrix classes are included.

**Comment by optimistex** [comment]
@josdejong In final, I've removed mathjs and used 20 lines code to find intersects via Vector3. I did it for threejs geometry.

**Comment by josdejong** [comment]
That sounds like a much simpler solution Konstantin 👍

**Comment by tswaters** [comment]
I'm hitting a similar issue - mathjs is massive and I only need a few things.

In the bad-old days (looking back at version control, this would've been ~3.20.2), we would do something like this --

```
const core = require('mathjs/core')
const math = core.create()
// import functions/operations that are required
math.import(require('mathjs/lib/function/arithmetic/multiply'))
// ... many other imports, but all simple math... //
```

But this broke somewhere along the way.  

It works _mostly_, but we get a lot of missing dependencies when accessing some routines, in the case of "multiply" - "typed", "matrix", "addScalar", "multiplyScalar", "equalScalar"....   that's fine, I'm OK with importing them, but attempting to import some of these dependencies the same way using paths inside the module throws a really nasty error --  specifically, for matrix:

```
Error: The index file $snip/node_modules/mathjs/lib/type/matrix/index.js is deprecated since v6.0.0. Please import and load individual files from the main index file instead, like: 
   import { create, addDependencies, multiplyDependencies } from 'mathjs' 
  const math = create({ addDependencies, multiplyDependencies }) 
```

"Deprecation" might be a light word for a thrown runtime error, I think.  This happens under 6.2.1.  We ended up "fixing" it by just importing everything -- but now I'm going back and looking at bundle size and mathjs is a huge outlier (bigger than moment-timezone and react-dom combined!)

Anyway, with the described recommendations, using cjs/require, requiring from the base like that will bring in the _entire_ bundle  -- so what was once a couple kb turns into the full [624kb](https://bundlephobia.com/result?p=mathjs@6.2.1).  I figure this will work fine under  import syntax - for some this is not yet possible, and it's the users that suffer from the massive bundle size.

**Comment by tswaters** [comment]
I ended up coming up with a workaround and managed to cut the bundle size of importing mathjs to around 30% of it's original size.  I see the latest version of this module (again, I'm using 6.6.5) -- has `exports` defined so this method will not work under the newer version....   Maybe the bundling situation is better under the latest version, I'm not sure.  The following applies to 6.x

Everything you can use with "$thingDependencies" expose a `create$SomeThing` method, and these can be passed into the `import` function.   Going this route, I needed to manually manage all the dependencies, which can be a bit of a pain.  

After hitting an error, I ran this:  `grep p-R 'exports.create$thing' node_modules/mathjs/lib` to figure out where the function was being defined, added an import, and moved on to the next one.  This is a bit labour intensive, but works.   (I had to add 26 additional imports from the ones I had imported previously).   

I would have used the files in `./entry` to avoid needing to map out the dependencies, but each generated file here pulls in "factoriesAny" which includes pretty much everything under the sun.

**Comment by josdejong** [comment]
Thanks for sharing Tyler. Things could indeed improved further since [v8.0.0](https://mathjs.org/history.html#20201106-version-800). With ES6 modules it should be fine to import an index file like `factoriesAny`, because non-used imports can be removed by modern bundlers. When using CommonJS this doesn't work unfortunately.
