### ISSUE TITLE
[Feature Request] Possibility of implementing "If ... else" for conditionals in addition to ternary operator

### ISSUE THREAD

**Issue by AlahmadiQ8** [josdejong/mathjs#1906]
I want to first  admit that this is one of the most useful JS libraries. Thank you! 

Ternary operator is well. Even in cases with deeply nested ternary operators. 

In a particular use case where I have formulas with many nested if statements. I've been converting them into ternary expressions to make them work with Mathjs. While that works, it impairs readability of the formula. 

Would it be feasible in the future to implement "If else" statements that mathjs can parse?

**Comment by josdejong** [comment]
Thanks for your suggestion Mohammad! Glad to hear you like mathjs. 

Yes support for `if ... else`. Would be very nice. I think this is part of a larger feature to support blocks with multi line expressions and use them in for loops, while loops, etc. This is discussed in #518. I will close this issue in favor of #518, let's continue the discussion there, OK?

**Comment by AlahmadiQ8** [comment]
That's great to hear. Sorry for the duplicate issue.

Absolutely. Thank you so much for your kind response.

**Comment by josdejong** [comment]
No problem at all 👍
