### ISSUE TITLE
eval results not correct

### ISSUE THREAD

**Issue by cyomas** [josdejong/mathjs#1907]
I am using the MathJS library in an angular project. Some errors appeared as I’ve been using the evaluate function. For example:

1-0.66 the result is 0.33999999999999997 and it should be 0.34
1-0.33 the result is 0.6699999999999999 and it should be 0.67
sin(pi) the result is 1.2246467991473532e-16 and it should be 1
cos(pi/2) the result is 6.123233995736766e-17 and it should be 0

These are some of the incorrect answers I’ve detected.

**Comment by josdejong** [comment]
You've discovered that floating point numbers have rounding errors 😉

See docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
