### ISSUE TITLE
Implicit multiplication

### ISSUE THREAD

**Issue by obsgolem** [josdejong/mathjs#191]
I am using math.js primarily for its parsing ability, and have run into a small syntax problem when parsing certain expressions, most obviously functions. This error comes when I try to write a function in the form f(x) = 2x or something similar. The problem is that the multiplication is not assumed in this case. This also happens when I try something like 3(10+2i). I can prevent this error by doing something like f(x) = 2*x, but having to add a multiplication symbol for implicit multiplication is not natural for me.

**Comment by AbdulKShahid** [comment]
is there a way to restrict implicit multiplication for the user?
because in the expression i have strings like
"343_user_id"
this is taken as 343* _user_id
