### ISSUE TITLE
Q: Parsing javascript to mathjs (and back)?

### ISSUE THREAD

**Issue by rev111** [josdejong/mathjs#1917]
I am thinking about ways to convert javascript expressions into math.js expressions and back.
Reasons: The code evaluated by math.js should be "injected" into javascript code and used from there. Long story.
It seems that some things are easy, such as search/replace "&&" with "and" and so on. Conditions seem to be more complicated. So before I attempt to do this, I'd rather ask wether this has perhaps already been done by somebody? Has anyone ever tried this?
Thanks and thanks for math.js.

**Comment by axkr** [comment]
I had created a `JSForm()` function in Symja:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/doc/functions/JSForm.md

which should support these Javascript libs for output:
- https://github.com/paulmasson/math
- https://github.com/paulmasson/mathcell

See this example:
  http://matheclipse.org/input?i=JSForm%28a%2Bb%2Ac%5Ed%2C%20%22Mathcell%22%29

Maybe you can get some ideas for your converter in the main conversion class `JavaScriptFormFactory.java`:
- https://github.com/axkr/symja_android_library/blob/master/symja_android_library/matheclipse-core/src/main/java/org/matheclipse/core/form/output/JavaScriptFormFactory.java

**Comment by rev111** [comment]
Thanks a lot, that is very helpful! Especially the Java class. Closing this issue to not stand in the way.

**Comment by josdejong** [comment]
@rev11 I'm not fully understanding your use case, when parsing an expression you get back a pointer to the interpreted JavaScript code. If you use `math.parse(expression)`, you get back an expression tree. This tree has methods like `toString` and `toTex`. It sounds like you're in need of a `toJavaScript` method? I suppose you can extend the library with support for that, that should be quite straightforward. 

I hope you're going to evaluate the JavaScript code output in a secure way, allowing execution of dynamically generated JavaScript can give security risks.
