### ISSUE TITLE
Creating Multiple Custom Base Units

### ISSUE THREAD

**Issue by petermarks12** [josdejong/mathjs#1921]
I want to create multiple custom base units.  As per docs, we can pass string to it as first parameter.  I think its not good approach to call createUnit multiple times.  Can we pass array or any other way?

```
math.createUnit('foo1')
math.createUnit('foo2')
math.createUnit('foo3')
math.createUnit('foo4')
```

**Comment by josdejong** [comment]
I think these docs will be helpful: https://mathjs.org/docs/datatypes/units.html#userdefined-units

**Comment by petermarks12** [comment]
Sorry for bothering, I did read docs and I thought may be we can pass array.  But I solved problem by using following code

```
 math.createUnit({
foo1:{},
foo2:{},
foo3:{}
});
```

**Comment by josdejong** [comment]
👍 

If your concern for calling `createUnit` is performance I don't think you have to worry about that. It's just what you think is best readable. You can also create a helper function yourself `createUnits` which calls `math.createUnit` multiple times.
