### ISSUE TITLE
toSI() on a scalar

### ISSUE THREAD

**Issue by chongchonghe** [josdejong/mathjs#1925]
Is there a way to make toSI() work on a scalar? The use case is when I want to display the result of an expression in SI unit if it has units. Like this:
- math.evaluate('1 cm').toSI() --> 0.01 m
- math.evaluete('2cm / 1cm').toSI() --> 2

Or, is there a function that works like `hasunit` in the following example?
```
if (hasunit(var)) {
print(var.toSI());
}
else {
print(var);
}
```

**Comment by rnd-debug** [comment]
@chongchonghe @josdejong Check this: #1970 
Implements toSI() for scalars. Needs to extends the JS native Number type.

**Comment by josdejong** [comment]
@rnd-debug thanks for working out a solution in #1970. Extending the native JavaScript `number` object can be ok for an end-user application, but I think it's better not to do this in a library.

I see I labeled this issue "question" but never replied. Sorry ChongChong.

I think there are a couple of options here:

- Probably the easiest is to write a small wrapper function `toSI(value)` (similar to the `hasunit` example you give), which checks whether the input is a Unit and if so call the `.toSI()` method, and if not, return the value itself.
- Currently, an expression like `2cm / 1cm` returns a number and no Unit. We could think through whether it would help to extend the config option `predictable` to not convert a unit to a number in such a case, but keep it a unit containing just a value. Any thoughts on this @ericman314 ?

**Comment by ericman314** [comment]
You should be able to use `if (var.hasBase('NONE'))` to test if a unit is "unitless".

> Extend the config option predictable to not convert a unit to a number

I believe this is already the current behavior. If `predictable` is true, your answer will always be of the type Unit, even if the units cancel out.

**Comment by josdejong** [comment]
Ah, you're right Eric! Unit already respects the `predictable` config (use `math.config({ predictable: true})`), then there is always a Unit returned having the `toSI` method. 

@chongchonghe does that solve your issue? 

@rnd-debug what do you think?

**Comment by rnd-debug** [comment]
I also wasn't confortable with extending JS `Number`, so I assume that I can close the PR 😇 
One dirty code snippet:
```
const mathjs =  require('mathjs')
const config = {predictable :true }
const math = mathjs.create(mathjs.all, config)
console.log(math.typeOf(math.evaluate('4m / 1m')))         // Unit
console.log(math.evaluate('4m / 1m').toSI().toString())      // 4
```

**Comment by chongchonghe** [comment]
> I also wasn't confortable with extending JS `Number`, so I assume that I can close the PR 😇
> One dirty code snippet:
> 
> ```
> const mathjs =  require('mathjs')
> const config = {predictable :true }
> const math = mathjs.create(mathjs.all, config)
> console.log(math.typeOf(math.evaluate('4m / 1m')))         // Unit
> console.log(math.evaluate('4m / 1m').toSI().toString())      // 4
> ```

I have to apologize that I'm new to Javascript. I tested this in a browser and I didn't work. It seems like 'require' doesn't work in browser. Is there a way to make this work in a browser? I tried to remove the line with require and replace mathjs with math, but it didn't work: it returns the same error: math.evaluate(...).toSI is not a function

**Comment by rnd-debug** [comment]
@chongchonghe Tested here: https://repl.it/languages/html
Contents of 'index.hmtl'
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>repl.it</title>
    <link href="style.css" rel="stylesheet" type="text/css" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/7.2.0/math.min.js"></script>
  </head>
  <body>
    <script type="text/javascript">
      const config = {predictable :true }
      math.config(config)
      console.log(math.typeOf(math.evaluate('4m / 1m')))         // Unit
      console.log(math.evaluate('4m / 1m').toSI().toString()) 
    </script>
  </body>
</html>
```

**Comment by chongchonghe** [comment]
It worked! Thanks! This solved my question.

**Comment by josdejong** [comment]
👍 

Thanks @rnd-debug for all your inputs.
