### ISSUE TITLE
Cube root of -1 expressed in different ways returns incorrect answer?

### ISSUE THREAD

**Issue by ElectrifyPro** [josdejong/mathjs#1926]
I encountered what seems to be a bug in the library's handling of exponents:

The `cbrt` function works as expected:
```js
cbrt(-1) = -1
cbrt(-8) = -2
```

However, this strangely returns a complex number:
```js
// Mathematically equivalent
(-1)^(1/3) = 0.5 + 0.86602540378444i
(-8)^(1/3) = 1 + 1.7320508075689i
```

What exactly is happening behind the scenes?

**Comment by josdejong** [comment]
Good question. A cubic root has three solutions. `cbrt`, `pow`, and `nthRoot` only give one of the three solutions. The function `nthRoots` can give you all solutions:

```
cbrt(-8) 
# -2

pow(-8, 1/3) 
# 1 + 1.7320508075689i

nthRoot(-8, 3) 
# -2

ans = nthRoots(-8, 3)
# [
#    1 + 1.7320508075689i,
#   -2,
#    1 - 1.7320508075689i
# ]

# double check calculating back the -8
ans .^ 3
# [-8, -8, -8]
```

**Comment by ElectrifyPro** [comment]
Ah, I understand. Thanks for the heads up!
