### ISSUE TITLE
Need small help in creating custom unit

### ISSUE THREAD

**Issue by petermarks12** [josdejong/mathjs#1930]
I am creating custom unit (a) and another unit (b) is 70.86/a  - I am using following way and its throwing error, can anybody point me in right direction?

`math.createUnit({ a:{}, b:'70.86/a' });`

Error:
`Units do not match ('a' != '1 b')`

We can create units like this, but I dont know why above logic does not work.

`math.createUnit({ a:{}, b:'1/a' });`

**Comment by josdejong** [comment]
When I execute your createUnit it indeed gives the following error, but not the error you report:

```js
math.createUnit({ a:{}, b:'70.86/a' });
// Error: Cannot create unit "b": a unit with that name already exists
```

Are you using the latest version of mathjs?

**Comment by petermarks12** [comment]
I was using 6.6, but I updated to 7.1 but still getting same error.  Can you try this following code?

`math.createUnit({ tex:{}, linen:'70.86/tex' });`

**Comment by josdejong** [comment]
All seems to work fine:

```js
math.createUnit({ tex:{}, linen:'1653.5/tex' })
math.evaluate('500 / (1 tex) ').toString() // "0.3023888720895071 linen"
```

**Comment by petermarks12** [comment]
I am using following code.  I just need number after conversion.  I am converting here 1 linen to tex.

```
math.createUnit({ tex:{}, linen:'1653.5/tex' })

const u = math.unit(1, 'linen');        
let output = u.toNumber('tex');
console.log(output)
```

**Comment by josdejong** [comment]
You've defined `linen` as `1653.5/tex` or `1653.5 * tex^-1`, therefore these two units have a different base and can't be converted. It's like wanting to express `5 seconds` in `Hertz` (which is `1/s`).

If you would have something like `linen:'1653.5 * tex'` then you can convert from one unit in the other.

**Comment by petermarks12** [comment]
Thanks for the help and for explanation 👍

**Comment by josdejong** [comment]
👍
