### ISSUE TITLE
chain(99).multiply(3) => 2.9699999999999998

### ISSUE THREAD

**Issue by PLQin** [josdejong/mathjs#1939]
```javascript
chain(99).multiply(3) // 2.9699999999999998
```

Why is it happen?   
I'm looking forward to the : 

```javascript
chain(99).multiply(3) // 2.97
```

**Comment by josdejong** [comment]
That is a round-off error: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

I think though that you did `chain(0.99).multiply(3)` instead of `chain(99).multiply(3)` 😉

**Comment by PLQin** [comment]
@josdejong yes , yes, hhh 

```
chain(0.99).multiply(3) // 2.9699999999999998
```

Why is it happen?
I'm looking forward to the :

```
chain(0.99).multiply(3) // 2.97
```

**Comment by josdejong** [comment]
Please read the documentation that I linked to above, it's your answer.

**Comment by PLQin** [comment]
I got the answer I wanted,
Thank you very much;
@josdejong
