### ISSUE TITLE
format() on time units behaving strangely

### ISSUE THREAD

**Issue by absolutehype** [josdejong/mathjs#194]
``` javascript
math.unit(230000, 'g').format({notation: 'fixed', precision: 2})
```

Returns "230.00 kg"

As expected, the format function determines kg as the preferred unit for displaying 230k grams. However when using time based units the format behaviour does not behave as i'd expect

``` javascript
math.unit(230000, 'minutes').format({notation: 'fixed', precision: 2})
```

Returns "230000.00 minutes"

I would expect it to return

"3833.33 hours" or preferably "159.72 days"

Is this the expected behaviour?

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed. It may be that this will work better with UnitMath, which we want to intregrate in mathjs.
