### ISSUE TITLE
Error in matrix subset tutorial

### ISSUE THREAD

**Issue by jmenashe** [josdejong/mathjs#1940]
The subset function is not working properly in the following example. You can view the example at [this fiddle link](https://jsfiddle.net/0xjake9a/ko4n3fzc/), or run the code from the second example under the [Matrices->Resizing](https://mathjs.org/docs/datatypes/matrices.html#resizing) documentation.

The sample code was run using [this cdn source](https://unpkg.com/mathjs@7.1.0/dist/math.min.js) with mathjs version 7.1.0. The sample was also run using jQuery 3.4.1. Please let me know if I can provide any other details.

**Comment by josdejong** [comment]
Thanks for reporting Jacob. In the latest versions of mathjs the `subset` method requires an index: 

```js
// subsets are automatically squeezed
const b = math.matrix([[0, 1], [2, 3]])
b.subset(math.index(1, 0))        // 2
```

Fixed via 9e46226

**Comment by bornova** [comment]
I know this issue was just closed, but I have one question.  The following example works as expected in plain js as you mentioned in above answer.  However, when I try using it in math.evaluate I get an index error:

```
math.evaluate(b = [[0, 1], [2, 3]])    // [[0, 1], [2, 3]]
math.evaluate(subset(b, index(1, 0)))    // IndexError: Index out of range (0 < 1)
math.evaluate(subset(b, index(1, 1)))    // 0
```

Looks like when used in math.evaluate, one-based index is used instead of zero-based.  Is this the intended behaviour?

**Comment by josdejong** [comment]
`math.evaluate` expects a string containing an expression as input. Here some examples on how to work with matrices in the expression parser:

https://mathjs.org/docs/expressions/syntax.html#matrices

The syntax of working with matrices inside the expression parser is much more concise than plain JS, I think you'll like it :).

**Comment by timxyz** [comment]
@josdejong Unfortunately the issue raised by @bornova still stands. Even when strings are passed to `evaluate` the same error occurs: "**IndexError: Index out of range (0 < 1)**". 

The `evaluate` call behaves as if indices are 1-based. But the documentation explicitly says "_Matrix indexes in math.js are zero-based_".

**Comment by josdejong** [comment]
> The `evaluate` call behaves as if indices are 1-based. But the documentation explicitly says "_Matrix indexes in math.js are zero-based_".

@timxyz the expression parser _is_ indeed 1-based, see docs: https://mathjs.org/docs/expressions/syntax.html#differences-from-javascript

**Comment by timxyz** [comment]
@josdejong Thanks, I had missed that. I am still conceptually separating what applies to the library and what applies to the evaluation module. For example, I have noticed that when I evaluate a `print` expression with an array, the array indices are still zero-based.

For example:

```
mathjs.evaluate("print('$2 $3', values)", {
    values: ["a", "b", "c", "d"],
  });
```

evaluates to `"c d"`. Should this be `"b c"`?

**Comment by josdejong** [comment]
Yes it is quite confusing :( 

The function `print` is a good example, it was never meant to be used from within the expression parser, it's indeed zero based. The idea was that you have an application where the user `evaluates` an expression, after which the application can `print` the result on the screen.
