### ISSUE TITLE
Question: Is there a way to build a partial of the of functions?

### ISSUE THREAD

**Issue by chongchonghe** [josdejong/mathjs#1944]
Currently, the `math.min.js` is a half MB pure text which is HUGE! Say, I want only the basic arithmetic computations with units support and don't need the matrix calculation or equations solving. Is there a way to build some of the modules in order to get a light-weight math.js?

**Comment by josdejong** [comment]
Yes you can! There is a page in the documentation about that and an example. Can you try to find those yourself? If it's hard to find I would love to know why and think though how we can make it easier to find.

**Comment by chongchonghe** [comment]
Thanks! I think this is the page you are talking about: https://mathjs.org/docs/custom_bundling.html  
I'll check that out. It's fairly easy to find this once I'm told that it's on the website (not in the README).

**Comment by josdejong** [comment]
👍 good to hear. That's indeed the page I had in mind.
