### ISSUE TITLE
Question: Additional library for 2d/3d transformations ?

### ISSUE THREAD

**Issue by nicolas-van** [josdejong/mathjs#1948]
Hello,

Just a quick question: does anyone know a library using mathjs and providing helpers functions to use matrix in 2D and 3D engines? Examples are function that can build rotation matrices, quaternions, that can of thing.

Basically I would like similar features than the ones provided by [glMatrix](http://glmatrix.net/docs/), but with mathjs's matrices.

Thanks in advance for any answer!

**Comment by josdejong** [comment]
Hm, I'm not aware of such a library or extension. It may be possible to load the functions from glMatrix into mathjs so you can use it in the expression parser for example.

**Comment by m93a** [comment]
I'm pretty sure THREE.js does most of what you want. Eg. [quaternions](https://threejs.org/docs/#api/en/math/Quaternion).
