### ISSUE TITLE
Replace the seed-random dependency

### ISSUE THREAD

**Issue by poppinlp** [josdejong/mathjs#1949]
Hi. Thanks for the nice tool.

I've used this in my work. But recently, I found that one of the dependencies of this lib makes some troubles for me. That's [seed-random](https://github.com/ForbesLindesay/seed-random).

I've opened [an issue here](https://github.com/ForbesLindesay/seed-random/issues/9) to describe the detail. To say it simply is that it depends on the whole global object from user and does some operations from that. But it could throw errors since we don't know what exists in user's global env.

And mathjs use it inside straight forward which may cause a crash by just import mathjs without doing anything.

I've mocked a module to bypass this problem. But seems that lib is not maintained for a long time. So, I come here for just a reminder. You could choose another RNG lib to avoid this risk if you like. :)

**Comment by josdejong** [comment]
I'm fine with replacing the library with a different one. Do you have an alternative in mind?

**Comment by poppinlp** [comment]
Thanks. Glad to hear that. :)

Actually I'm not familiar with the RNG algorithm. So, I'm not pretty sure about the alternative.
Maybe [this one](https://github.com/davidbau/seedrandom)? Looks like it has many more stars and thinks about both browser and nodejs.

**Comment by josdejong** [comment]
Sounds good to me to see if we can use https://github.com/davidbau/seedrandom instead.

Anyone interested in trying this out?

**Comment by josdejong** [comment]
This fix is published now in `v8.0.0`
