### ISSUE TITLE
Accuracy issue with unit conversion

### ISSUE THREAD

**Issue by woodreamz** [josdejong/mathjs#1954]
Hi,

I just did some unit tests on the library to see if I can use the unit conversion for a webapp requiring a high precision.

A simple test like `unit(100, "mg").toNumber("mg")` give me 99.99999999999999 (instead of 100).

I tried to use BigNumbers, same result. I also have the same behavior with other units.

Here is a codesandbox to reproduce: https://codesandbox.io/s/mathjs-zz7z9.

Am I doing something wrong?

Thanks!

**Comment by josdejong** [comment]
If you use BigNumbers you will not get these round-off errors. You can use bignumbers in two ways:

```js
import { create, all } from 'mathjs'

const config = { number: 'BigNumber' }
const math = create(all, config)

console.log(math.evaluate('unit(100, "mg").toNumber("mg")')) // 100
```

Or:

```js
import { create, all } from 'mathjs'

const config = {}
const math = create(all, config)
console.log(math.unit(math.bignumber(100), "mg").toNumber("mg")) // 100
```

**Comment by woodreamz** [comment]
Thanks, it seems to fix my issue.

I was using the second way in my code but I had this code:
`import { create, all } from 'mathjs'

const config = { number: 'BigNumber' }
const math = create(all, config)
console.log(math.unit(100, "mg").toNumber("mg")) // 100`

The `math.bignumber(..)`was missing in my code :(

Thanks again!

**Comment by woodreamz** [comment]
I think the index.d.ts needs to be updated because the unit function has those definitions:

```javascript
        unit(unit: string): Unit;
        unit(value: number | MathArray | Matrix, unit: string): Unit;
```

It should also allow BigNumber for the value.

**Comment by josdejong** [comment]
> The math.bignumber(..) was missing around the value :(
> 
> Thanks again!

This is confusing indeed! We would love to change this, but it's not a trivial thing, see #864.
