### ISSUE TITLE
[bug] wrong result by evaluate function

### ISSUE THREAD

**Issue by softboy99** [josdejong/mathjs#1958]
var expr = '(79.1198-79.1149) * 1000 * 1000 / 100';

math.evaluate(expr) ==>48.99999999992133

it should be : 49

after google, i know, internal you are using decimal.js to cacluate accurately. How to get 49?

**Comment by josdejong** [comment]
BigNumber is not configured by default.

How to use BigNumbers is explained in the docs: https://mathjs.org/docs/datatypes/bignumbers.html#usage
