### ISSUE TITLE
Allow null to behave like 0

### ISSUE THREAD

**Issue by javiermarinros** [josdejong/mathjs#1966]
Since v4 null values are not allowed, and using them causes this kind of error:

`TypeError: Unexpected type of argument in function multiplyNumber (expected: number or string or boolean, actual: null, index: 0)`

Is there any way to allow back the previous null behaviour?

**Comment by josdejong** [comment]
Good question Javier. 

To understand the reasons why `null` isn't treated as `0` anymore, see: #353, #830.

In most use cases, it is possible to "sanitize" your inputs beforehand, so if you want to change `null` to `0` you could write a little wrapper function to do this conversion. If that's not possible in your use case, can you explain your case so we can better understand if/how we can make this workable?

**Comment by javiermarinros** [comment]
Thank you @josdejong 

Sanitizing the input doesn't work in my case because I need to distinguish between `0` and `null`.

I'm using MathJS to evaluate an expression where a `rating` variable is transformed into a score:

```
math = create({
      ...all,
      createEqual: factory('equal', [], () => (a, b) => a === b)
    });
math.evaluate('if(rating == 0, -2) + (rating * 2.5)', {
      rating: null,
      if: (condition, valueIfTrue) => condition ? valueIfTrue : 0
    });
```

If no rating provided (`null`), this expression should be evaluated as `0`, but for a rating of `0`, it should be evaluated as `-2`.

Right now if I try to execute that code, I get the TypeError mentioned above:

> Unexpected type of argument in function multiplyNumber (expected: number or string or boolean, actual: null, index: 0)

**Comment by josdejong** [comment]
Would it be possible to replace:

```
'if(rating == 0, -2) + (rating * 2.5)'
```

with

```
'if(rating == 0, -2) + (number(rating) * 2.5)'
```
? That would be an easy solution.

To make mathjs treat `null` as `0`, it is possible to add a conversion from `null` to `0` in `typed-function`. I think there is no need to build a configuration option for this (unless people need this a lot). If you want I can explain how to do that (basically: load an empty instance of mathjs, add a conversion from `null` to `0` to `math.typed.conversions`, and after that load all functions (like multiply)).

**Comment by javiermarinros** [comment]
Replacing with `number()` is not a solution for us as the expression is user-defined and could have infinity variations.

I followed your advice about using `math.typed.conversions` and it seems to work, now this expression is working and returning `0`:

```
const math = create({
      all,
      createEqual: factory('equal', [], () => (a, b) => a === b)
    });
    math.typed.conversions.unshift({
      from: 'null',
      to: 'number',
      convert: () => 0
    });
    const result = math.evaluate('if(rating == 0, -2) + (rating * 2.5)', {
      rating: null,
      if: (condition, valueIfTrue) => condition ? valueIfTrue : 0
    });
```

What I understand with this code is:
- custom functions like the above `if` will receive the raw `null` value
- built-in typed functions and operators will convert `null` to `0` using the defined conversion

Am I right?

Thank you!

**Comment by josdejong** [comment]
Yes that's exactly how it works, it only applies to typed-functions. Good to hear it works 👍
