### ISSUE TITLE
Usage in Node take error

### ISSUE THREAD

**Issue by myLightLin** [josdejong/mathjs#1969]
I require「add」method from number like this:
```
const { add } = require('mathjs/number')
```
then occur error,  the error message is 
```
export * from './main/esm/number' // eslint-disable-line
                                             ^^^^^^^^^^^
SyntaxError: Unexpected token export at Module._compile
```
what should I do,  I need help

**Comment by josdejong** [comment]
Thanks for your question @myLightLin . Mathjs still has some issues and limitations supporting both CommonJS and ES modules. We're addressing this (see #1962), but until then you'll have to use a workaround.

Can you try loading as follows?

```js
const { add } = require('mathjs/main/es5/number.js')
```

(this will become redundant again once we've released `mathjs@8`)

**Comment by josdejong** [comment]
This issue should be fixed now in `v8`. Will close the issue now, please reopen if needed.
