### ISSUE TITLE
`pickRandom` should not look at element types, in my opinion.

### ISSUE THREAD

**Issue by fweth** [josdejong/mathjs#1974]
`pickRandom` wants a one-dimensional array.  I understand the design decision, but it still feels not so intuitive, I expect `pickRandom` to only look at the length of my array and then return the element at a random index.  So e.g. `math.pickRandom([[0, 1], [2, 3]])` should randomly return either `[0, 1]` or `[2, 3]`.  After all, `pickRandom([0, [1, 2], [3, 4]])` works as expected.  Even if we pretend that JS is a strictly typed language with no mixed arrays, I'd expect `pickRandom` to be of type `forall a. [a] -> M a` where `M` is a suitable monad.

**Comment by josdejong** [comment]
Thanks @fweth , that is a good point. I think there is no reason to only allow a 1d array, we could simply iterate over all elements.

Anyone interested in helping improve `pickRandom` in this regard?

**Comment by josdejong** [comment]
Improvement is now available in `v7.4.0`.
