### ISSUE TITLE
Missing "subset" dependency when using "mathjs/number" entry point

### ISSUE THREAD

**Issue by sylvaingi** [josdejong/mathjs#1979]
When trying to use the `mathjs/number` entry point for a lighter final bundle size, I encountered the following error when trying to use the `evaluate` function: 

`Cannot create function "AccessorNode", some dependencies are missing: "subset".`

Adding `subsetDependencies` solves the issue.

Reproduction:
https://codesandbox.io/s/pensive-lehmann-crt4q?file=/src/index.js

**Comment by josdejong** [comment]
Thanks for reporting Sylvain. 

I'll look into why this is not working, have to figure out why this dependency is not part of the AccessorNode dependencies right now.

**Comment by josdejong** [comment]
This is fixed now in `v8.0.1`
