### ISSUE TITLE
module.exports = require('../../lib/entry/mainAny')

### ISSUE THREAD

**Issue by lgh757079506** [josdejong/mathjs#1980]
项目中无 lib 文件夹，是已经修改未同步修改吗

**Comment by josdejong** [comment]
Thanks, can you please repeat your question in English?

**Comment by Ongshu777** [comment]
Maybe he means: "There is no lib folder in the project, has it been modified without synchronization?"
(I used Google Translate)

**Comment by lgh757079506** [comment]
but i find nothing where it is in 'node_modules' by 'npm install mathjs',it means 'bin' folder doesn't exist  in 'node_modules/mathjs'

**Comment by lgh757079506** [comment]
@josdejong

**Comment by lgh757079506** [comment]
oh, i see it now,it maybe have some problems with network at that time

**Comment by josdejong** [comment]
👍 good to hear it's solved now.
