### ISSUE TITLE
v7.3.0: regression, modulo with negative number broken

### ISSUE THREAD

**Issue by dnalborczyk** [josdejong/mathjs#1981]
repro:

**v7.2.0**
```
math.bignumber(-175).modulo(100)

// -75
```

**v7.3.0**
```
math.bignumber(-175).modulo(100)

// 25
```

**Comment by ovk** [comment]
Why you consider it broken? It was actually fixed in #1964 to behave as mathematical modulo operation (consistently with how it behaves for regular number type).

`-175 mod 100` is indeed `25` as you can see [here](https://www.wolframalpha.com/input/?i=-175+mod+100).

**Comment by dnalborczyk** [comment]
interesting.

```shell
➜ node
Welcome to Node.js v14.12.0.
Type ".help" for more information.
> -175 % 100
-75
> 
```

**Comment by dnalborczyk** [comment]
nm, seems to be the difference between **modulo** and **remainder**: https://2ality.com/2019/08/remainder-vs-modulo.html

**Comment by josdejong** [comment]
> nm, seems to be the difference between **modulo** and **remainder**: https://2ality.com/2019/08/remainder-vs-modulo.html, if that is the intend.

@dnalborczyk that is correct. In `v7.3.0` we fixed/changed the behavior of modulus for BigNumbers to be consistent with how it's calculated for numbers in mathjs, and how it's calculated by the major math applications that I know of: as modulo operator like described in section "3 The modulo operator mod" of the article that you link to: https://2ality.com/2019/08/remainder-vs-modulo.html#the-modulo-operator-mod. 

I hope this clarifies what's going on.

**Comment by dnalborczyk** [comment]
thank you for the clarification! @josdejong @ovk
