### ISSUE TITLE
Handling Two or More Operators in a Row?

### ISSUE THREAD

**Issue by DragonOsman** [josdejong/mathjs#1983]
Hi, everyone.

I'm building a calculator in ReactJS for a FreeCodeCamp project and one of the user stories says this:
```
If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the negative (-) sign). For example, if 5 + * 7 = is entered, the result should be 35 (i.e. 5 * 7); if 5 * - 5 = is entered, the result should be -25 (i.e. 5 x (-5)).
```
Does `mathjs` have support for this out of the box?  

If I have to write code for it myself, will I have to worry about the number digits in the numbers or whether or not there's a number with a decimal point or will `mathjs` itself handle that?  I'm going to do it in the equals button click handling code, where I'm using `math.evaluate` to do the calculation.

**Comment by josdejong** [comment]
Mathjs does not have support for this. I'm not sure there is an actual use case for this, why would you want to enter two operators and ignore one?

**Comment by DragonOsman** [comment]
Ask the guys who decided on that user story for the project.  I'm guessing it's when a user ends up typing two or more operators in  a row, either by accident or try to break the app.  The operator entered most recently should be the one used in that case, right?  With the `-` operator being treated as a negative sign if it's more recently entered operator.

**Comment by josdejong** [comment]
I don't know. When a user enters `5 + * 7`, mathjs will simply throw an error since the user entered invalid syntax and it's not clear what the user actually meant to do.

**Comment by DragonOsman** [comment]
If I try to do this myself, will I have to write code to check for the number digits or decimal point occurrences in the numbers entered?

**Comment by josdejong** [comment]
I don't know what the intention of your FreeCodeCamp assignment is, but if it's unclear then I guess you can best ask there?

**Comment by DragonOsman** [comment]
I managed to do it by removing the previously clicked operator from my formula string when an operator aside from `-` is clicked.  

I'll close this now since it's solved.
