### ISSUE TITLE
Have a whole bunch errors being thrown from math.evaluate -- don't know how to fix

### ISSUE THREAD

**Issue by DragonOsman** [josdejong/mathjs#1988]
Hi again.

Here's the updated [code Gist](https://gist.github.com/DragonOsman/3c2b4a2b384cff1382b2c101e48ac60a).  And here's just [App.js](https://github.com/DragonOsman/javascript-calculator/blob/master/src/js/components/App.js), from the GitHub repo.

I have a whole bunch of errors being logged to the console from `math.evaluate` in the equals button click handler.  I'm catching them all and the calculator functionality for the buttons I've defined handlers for seems to work fine, but the tests fail; it could because of the errors being thrown, so I want to know how I can fix the errors.  I'll post them here.

With empty `input` array:
```
Error occurred: SyntaxError: Unexpected end of expression (char 12)
Error occurred: SyntaxError: Unexpected part ".5510" (char 5)
Error occurred: SyntaxError: Unexpected end of expression (char 4)
Error occurred: SyntaxError: Unexpected end of expression (char 3)
Error occurred: SyntaxError: Unexpected end of expression (char 3)
Error occurred: SyntaxError: Unexpected end of expression (char 3)
```
With `input` array having stuff in it:
```
input array: ["5", "*", "1", "+", "5", "+", "9", "2"]
Error occurred: SyntaxError: Unexpected end of expression (char 12)

["1", "2", "3", "3", "+", "5", "*", "6", "-", "2", "/", "4"]
Error occurred: SyntaxError: Unexpected part ".5510" (char 5)

["5", ".", "0", "5", ".", "5", "5", "1", "0", ".", "5", "-", "5", ".", "5"]
Error occurred: SyntaxError: Unexpected end of expression (char 4)

["5", "*", "-", "5"]
Error occurred: SyntaxError: Unexpected end of expression (char 3)

["5", "-", "2"]
Error occurred: SyntaxError: Unexpected end of expression (char 3)

["2", "/", "2"]
Error occurred: SyntaxError: Unexpected end of expression (char 3)
```

The last one was `2/7`, but that one doesn't cause an error.  The test says the calculator should have at least four decimal places of precision and my calculator produces the output `0.285714285714`.  But the test fails.  I don't get it.

Could it be I've configured math.js itself wrong?

**Comment by josdejong** [comment]
I guess your input contains unexpected contents. `math.evaluate(expression)` expects a string like `"2 + 3"` as input, not an array with characters. You can try adding some logging right before you call evaluate to see what is actually in the expression you pass to the evaluator, or put a debug point there to inspect.

**Comment by josdejong** [comment]
One small tip: I think you can replace:

```js
const calculatedValue = math.round(1000000000000 * math.evaluate(stored)) / 1000000000000;
```

with

```js
const calculatedValue = math.round(math.evaluate(stored), 12);
```

or use `math.format(math.evaluate(stored), { precision: 12 })` to turn your contents in a string.

**Comment by rnd-debug** [comment]
@DragonOsman  https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Array/join
`["2", "/", "2"].join()` is not what you expect.

**Comment by DragonOsman** [comment]
@josdejong I put the input into an array, for but the formula appears at the top of the screen on the calculator as a string because I do `input.join("")` to set the stored value.

```js
const newInput = input;
newInput.push(event.target.textContent);
setInput(input);
setStoredValue(input.join(""));
```
So the expression I'm passing to it is a proper string, not an array.  As I said, the calculator does math and stuff correctly and I'm using mathjs; if it weren't a string, the evaluation probably wouldn't happen.

@rnd-debug But when I try `2/2` it gives me `1` as it should.  What do you mean?  Also, I'm doing `input.join("")`.  I'm not calling it without a separator.

**Comment by DragonOsman** [comment]
I have three questions here:
1. What's the reason for the `Unexpected end of expression` error and how do I fix it?
2. I'm letting the calculator accept more than one decimal point click per expression, but there's still this weird thing:
```
5.05.5510.5-5.
App.js:210 Error occurred: SyntaxError: Unexpected part ".5510" (char 5)
```
I logged the string itself there, not the array it was made from.  

Here's the decimal click handler code:
```js
  const handleDecimalClick = event => {
    if (currentValue.includes(event.target.textContent)) {
      return null;
    } else {
      const newInput = input;
      if (currentValue === "0") {
        newInput.push(currentValue);
      }
      setCurrentValue(currentValue.concat(event.target.textContent));
      newInput.push(event.target.textContent);
      setInput(newInput);
      setStoredValue(input.join(""));
    }
  };
```
GitHub repo [link](https://github.com/DragonOsman/javascript-calculator) for full code.
Gist [link](https://gist.github.com/DragonOsman/3c2b4a2b384cff1382b2c101e48ac60a).

3. Is there something wrong with the expression string that isn't apparent from looking at the calculator display (you could also take the code and try running it yourself if you want)?  Maybe that's what's causing the errors to be thrown.

**Comment by josdejong** [comment]
An input like 

```
5.05.5510.5-5.
```

Is not something the expression parser understands. It starts to parse the value `5.05`, but then expects an operator or function but gets another `.` again. That's why it throws `"SyntaxError: Unexpected part ".5510" (char 5)"`.

I guess you'll have to do some more debugging to see why doing calculations yourself works but doing via your application throws an error.

**Comment by DragonOsman** [comment]
With my latest code, it all works except for just one test and user story.  I have to get this test to pass:
```
13. If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the negative (-) sign.
The sequence "5 * - + 5" = should produce an output of "10" : expected '25' to equal '10'
AssertionError: The sequence "5 * - + 5" = should produce an output of "10" : expected '25' to equal '10'
```
This is my operator button handler code:
```js
const handleOperatorClick = event => {
    if (input.length > 0) {
      // handle 2 or more operators clicked in a row
      if (operators.includes(input[input.length - 1]) && event.target.textContent !== "-") {
        // take the previously clicked operator out of the input array
        const newInput = input;
        newInput.splice(-1, 1);
        setInput(newInput);
        setStoredValue(input.join(""));
      } else if (input[input.length - 1].endsWith("^2")) {
        const newInput = input;
        newInput.push(event.target.textContent);
        setInput(newInput);
        setStoredValue(input.join(""));
      }
    }

    // take the result of the previous evaluation for a new calculation
    if (equalsClicked) {
      // This means equals button was clicked (can be like this in other cases too but still)
      // set input array and storedValue to equal the result from the
      // previous calculation
      const newInput = input;
      newInput.push(currentValue);
      setInput(newInput);
      setStoredValue(input.join(""));

      // reset to false to make sure other click handlers don't misunderstand
      setEqualsClicked(false);
    } else if (reciprocalClicked || squareRootClicked) {
      const newInput = input;
      setInput(newInput);
      setStoredValue(input.join(""));

      // reset to false to make sure other click handlers don't misunderstand
      setReciprocalClicked(false);
      setSquareRootClicked(false);
    }

    const newInput = input;
    newInput.push(event.target.textContent);
    setInput(newInput);
    setStoredValue(input.join(""));
  };
```
Do I just need to get the parser to not treat the `+` as a unary sign operator in that situation?  I don't really get how to do that, though.
