### ISSUE TITLE
Resize , optional direction

### ISSUE THREAD

**Issue by ebuk** [josdejong/mathjs#199]
Resize currently takes from the end of an array, or the max dimension of matrix. It would be great if you could optionally take from the beginning of an array (or matrix) in the event you are updating values over time (e.g. push new column on to a matrix, pop off first column)

**Comment by gwhitney** [comment]
Indeed, #54 if adopted would allow something like (in mathjs' internal parsed notation):
```
M = identity(4)
M[:,1] = []
```
to delete the first column. Hence closing this as subsumed by #54.
