### ISSUE TITLE
mathnotepad, plot(), legend v trace.

### ISSUE THREAD

**Issue by MvGulik** [josdejong/mathjs#1991]
http://mathnotepad.com/
Version 0.11.4
(Firefox 81.0)

If the plot(...) Legend-option is disabled (_manually or automatic_), the Trace data print moves farther into the LB corner so its data now gets clipped by the corner.

![Screenshot from 2020-10-09 07-56-30](https://user-images.githubusercontent.com/666868/95548466-6d4fe980-0a05-11eb-86ad-2e331dbfc7df.png)
![Screenshot from 2020-10-09 07-56-37](https://user-images.githubusercontent.com/666868/95548482-7640bb00-0a05-11eb-9261-791aa66b00fa.png)

Also happens, with Legend enabled. on "plot()".
![Screenshot from 2020-10-09 07-56-56](https://user-images.githubusercontent.com/666868/95548492-79d44200-0a05-11eb-8fb8-3a9ad445d6b2.png)
(_seems the "x:" and "y:" parts in the trace data are seen as legend-parts too. which I personally find a bit odd._)

**Comment by josdejong** [comment]
Thanks for reporting, looks like there is a bug in calculating the right bottom left location with margins.

**Comment by josdejong** [comment]
This is fixed now in `v0.11.5`.
