### ISSUE TITLE
Binary, Octal, and Hexadecimal parsing incorrect

### ISSUE THREAD

**Issue by clnhlzmn** [josdejong/mathjs#1995]
I noticed that the literals `0b10000000000000000000000000000000`, `0o20000000000`, `0x80000000` are incorrectly parsed as `2147483648` rather than `-2147483648`.

I am working on [#1982](https://github.com/josdejong/mathjs/issues/1982) and I intend to fix this there.

**Comment by josdejong** [comment]
👍

**Comment by clnhlzmn** [comment]
This has been fixed in #1996.
