### ISSUE TITLE
Error: math.import is not a function

### ISSUE THREAD

**Issue by rev111** [josdejong/mathjs#1997]
Hello,
I'm using 

- node 14.5.0
- mathjs 7.5.1, installed 7.1.0 with npm and updated through package.json

in a node project with ES6 imports. I import mathjs like this:
`import math from 'mathjs';`
So far I had no issues. evaluate() and parse() worked. Now I would like to use import for a custom function:
```
math.import({
            myvalue2: 42
}
```
and get the error:
`TypeError: math.import is not a function`

I think, but I am not sure that this is related to [pull request #1941](https://github.com/josdejong/mathjs/pull/1941). 
That is because I started learning node with this project and used ES6 from the beginning. It's still kind of a mystery to me what i.e. gulp or rollup does. 

I tried several variations of 
`import { all } from 'mathjs';`
but that fails immediately with
```
import { all } from 'mathjs';
         ^^^
SyntaxError: The requested module 'mathjs' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
```

My question is, am I doing something wrong? Is there something I should do differently (preferrably without recompiling the source because I don't know how to do that)?
Thank you, rev111

**Comment by rev111** [comment]
I solved this with a different import:
`import math from './node_modules/mathjs/dist/math.js';`
seems to work fine.

**Comment by josdejong** [comment]
👍 

I hope indeed that #1941 will solve many of those issues.
