### ISSUE TITLE
Why Torque unit is not available?

### ISSUE THREAD

**Issue by bgeffrault** [josdejong/mathjs#2005]
Hi,
Thanks for making this library available.
I would like to know why TORQUE unit is not available in the library?

I saw 2 comments about torque in the project but nothing to explain why.

What would be the best approach to add it?
I did this in the meantime but I’m not 100% satisfied with it.
```
math.createUnit("Nm", "1 N * m");
math.createUnit("Nmm", "1 N * mm");
math.createUnit("lbft", "1.3558179483314004 Nm");
math.createUnit("lbin", "0.0833333333333333333333 lbft");
```
Thank you in advance

**Comment by josdejong** [comment]
I think maybe @ericman314 explains in https://github.com/josdejong/mathjs/issues/1585#issuecomment-517688613 that `torque` is ambiguous:

> An example is if you're working with torque, which is usually in newton meters, but it can also be expressed in joules/radian. Then if a motor imparts x joules/radian on an object that rotates through y radians, x * y joules of work has been done. So keeping the radians around is sometimes best.

You can indeed create the units that you're missing yourself. Your solution looks good, what is the reason that you're not happy with it?

**Comment by josdejong** [comment]
For reference see also https://github.com/josdejong/mathjs/pull/683#issuecomment-234259832
