### ISSUE TITLE
Parenthesis Nodes

### ISSUE THREAD

**Issue by aminemarref** [josdejong/mathjs#2006]
Hello,

How are parenthesis nodes represented in the expression tree? I was trying to do some processing on the expression tree of the algebraic expression `'((x+1)*(x+2))/(x+3)'` but my traversal function hit a parenthesis node. Do they have operator nodes as children? Could you please draw the expression tree of the algebraic expression `'((x+1)*(x+2))/(x+3)'`?

Many thanks.

**Comment by rev111** [comment]
Hello, you can create a JSON tree in javascript:
```
const jsstring = '((x+1)*(x+2))/(x+3)';
//parse into nodes
const nodes = math.parse(jsstring);
//make json string from nodes
const nodeJSONString = JSON.stringify(nodes,null,2);
console.log(nodeJSONString);
```

**Comment by josdejong** [comment]
@aminemarref the types and properties of all expression tree nodes is documented on the following page:

https://mathjs.org/docs/expressions/expression_trees.html#parenthesisnode

**Comment by josdejong** [comment]
(and you can of course do a bit of debugging, print out the contents of a parsed tree, or put a debug point in your code, to just see what is there)
