### ISSUE TITLE
Error: Cannot create function "floor", some dependencies are missing: "matrix", "equalScalar".

### ISSUE THREAD

**Issue by ceu** [josdejong/mathjs#2012]
"react": "16.8.6",
 "react-dom": "16.8.6",
"mathjs": "^7.5.1",

![截屏2020-10-29 下午2 31 17](https://user-images.githubusercontent.com/13114273/97533591-6e1be000-19f3-11eb-88d7-e01c2c247830.png)

**Comment by ceu** [comment]
what's the  problem, i just use the bigNumber

**Comment by josdejong** [comment]
Can you share your code (a minimal example), so we can see how you're loading the library?

**Comment by gwhitney** [comment]
Likely this should simply be closed at this point, since there was never sufficient information to reproduce, and it was filed quite some time ago.

**Comment by josdejong** [comment]
Let's close this old issue now. Please reopen if it is still an issue.
