### ISSUE TITLE
Typed concat interface is not allowing 'dim' argument

### ISSUE THREAD

**Issue by PatrickHallek** [josdejong/mathjs#2014]
I use the typed version of mathjs. The imported interface of concat function is not providing any argument for the dimension. 

To reference the documentation:
```js
math.concat(A, B)                  // returns [[1, 2, 3, 4], [5, 6, 7, 8]]
math.concat(A, B, 0)               // returns [[1, 2], [5, 6], [3, 4], [7, 8]] **Doesn't work**
math.concat('hello', ' ', 'world') // returns 'hello world' **Doesn't work**
```

The second and third line will throw the error: 

> Argument of type 'number' (or 'string') is not assignable to parameter of type 'number[] | number[][] | Matrix'

 because the interface just allows matrices as input like in line 1.

The Interface description is also misleading and not aligned with the parameters:
```ts
/**
 * Concatenate two or more matrices. dim: number is a zero-based
 * dimension over which to concatenate the matrices. By default the last
 * dimension of the matrices.
 * @param args Two or more matrices
 * @returns Concatenated matrix
 */
        concat(...args: Array<MathArray | Matrix>): MathArray | Matrix;
```

**Comment by josdejong** [comment]
Hm, when I enter your examples in the JavaScript console of the website https://mathjs.org, all works fine:

```js
const A = [[1, 2], [5, 6]]
const B = [[3, 4], [7, 8]]

console.log(math.concat(A, B)) // [[1, 2, 3, 4], [5, 6, 7, 8]]
console.log(math.concat(A, B, 0)) // [[1, 2], [5, 6], [3, 4], [7, 8]]
console.log(math.concat('hello', ' ', 'world')) // 'hello world'
```

I'm not sure how to reproduce your issue.

**Comment by josdejong** [comment]
O wait, I guess this is not an issue in the library itself but in the TypeScript definitions of it. 

Anyone able to improve the typescript definitions? Maybe good to report at definitely-typed?

**Comment by PatrickHallek** [comment]
Ok, I will create a pull request for it to the definitely typed repository

**Comment by josdejong** [comment]
👍 thanks
