### ISSUE TITLE
Add kgf to unit core

### ISSUE THREAD

**Issue by nopria** [josdejong/mathjs#2016]
I think a very useful unit is missing, the **kilogram-force**, which is for the kilogram what poundforce is for the pound (i.e. **1 kgf = 1 kg * g = 9.80665 N**, where g is the gravitational acceleration whose [conventional standard value](https://en.wikipedia.org/wiki/Gravitational_acceleration) is **9.80665 m/s^2**).

Please consider adding it to math.js core.

**Comment by josdejong** [comment]
Thanks for your suggestion, makes sense 👍 

Anyone able to create a small PR with this new unit + a unit test?

**Comment by rnd-debug** [comment]
Looked easy => PR #2028 provided.

**Comment by josdejong** [comment]
I see I forgot to close this issue. The unit is added to the library via #2028.
