### ISSUE TITLE
In Plot.js wrong Graph for -cos(x)

### ISSUE THREAD

**Issue by sairish2001** [josdejong/mathjs#2020]
The point should start from negative point but starts from positive point
Showing graph of cos(x) not -cos(x)

**Comment by josdejong** [comment]
Thanks for reporting Rajinderpal. How can I reproduce your issue exactly? What Plot.js are you referring to?

**Comment by sairish2001** [comment]
https://mathjs.org/examples/browser/plot.html.html
I am referring to Plot.ly

**Comment by josdejong** [comment]
So here is how it looks when I run it:

```
cos(x)
```
![afbeelding](https://user-images.githubusercontent.com/568626/98437244-08111600-20e1-11eb-93ac-adba142cca75.png)

```
-cos(x)
```

![afbeelding](https://user-images.githubusercontent.com/568626/98437257-1ceda980-20e1-11eb-8dcb-41fc24ad9f0c.png)

All looks right. You have to click "Draw" again though after changing the expression.
