### ISSUE TITLE
Is it possible to generate tex equation?

### ISSUE THREAD

**Issue by michalmicpaw** [josdejong/mathjs#2021]
Hi.

I'm trying to parse equation with mathjs with **parse** and **toTex** methods. But I don't know how generate **=** sign.

I.e. **3!=1 * 2 * 3=6**

Is it possible to generate such Tex code?

Thanks Mike

**Comment by josdejong** [comment]
The expression parser of mathjs has it's own syntax. From this syntax it is possible to generate corresponding Tex, but you can't express any Tex notation in the syntax of the expression parser.

The `=` sign is available as assignment operator, like in `a = 3`. In Tex this is outputted as `a := 3` though.

You can find docs on the syntax here: https://mathjs.org/docs/expressions/syntax.html

Here is a live example where you can play around: https://mathjs.org/examples/browser/pretty_printing_with_mathjax.html
