### ISSUE TITLE
docs: upgrade pretty print to mathjax v3

### ISSUE THREAD

**Issue by pkra** [josdejong/mathjs#2022]
The documentation uses MathJax v2.3 which is 7 years old. Also, MathJax v3 has a completely different API.

If there's interest, I'm happy to make a PR.

**Comment by josdejong** [comment]
ahh, good point Peter 👍 

Thanks for your offer, would be great if you can update the example to use the latest MathJax!

**Comment by josdejong** [comment]
That's a long time ago we last spoke btw 😉

**Comment by pkra** [comment]
Thanks, Jos!

> That's a long time ago we last spoke btw wink

Indeed!

**Comment by josdejong** [comment]
Updated example is now published in `v8.0.1`
