### ISSUE TITLE
having problem in using sin() 

### ISSUE THREAD

**Issue by eliii** [josdejong/mathjs#2025]
I try this code : 

math.evaluate("sin(180 deg)")

the result must be 0 , but the result which it returns me is 1.2246467991473532e-16

what is the problem ? is the problem with the library ??

**Comment by josdejong** [comment]
You're asking one of the most asked questions 😄 

See docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors 

(you can search other issues about "round-off errors")
