### ISSUE TITLE
Abnormal accuracy of calculation using math.multiply

### ISSUE THREAD

**Issue by xieccc** [josdejong/mathjs#2033]
```
math.multiply(18.4, 100)
// 1839.9999999999998
// But the correct result should be 1840
```
Excuse me. How can I get the accurate value?

**Comment by josdejong** [comment]
This is the most asked question 😉 

See https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by xieccc** [comment]
Thanks.
In other words, when calculating floating-point numbers, I need to reduce the precision to less than 16 digits so that this problem can be solved normally. 
Can reducing precision usually be understood as rounding?

**Comment by josdejong** [comment]
Yes. You can't really solve the problem with floating point numbers, but you can hide it from the users eyes by rounding outputs displayed om screen.
