### ISSUE TITLE
Upgrade to webpack 5

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#2050]
We need to upgrade the build process from Webpack 4 to Webpack 5. There are breaking changes, but I'm not sure if this will be simple or not.

Any help would be very welcome! Anyone interested?

**Comment by JayFate** [comment]
I'm interested. leave this issue to me, thx.

**Comment by josdejong** [comment]
Thanks Jay 👍

**Comment by mollthecoder** [comment]
Thos problem appears to be resolved, you should probably close this now.

**Comment by josdejong** [comment]
mathjs is still using webpack 4, the issue is not resolved yet.

I see @flaviut did work on a fix in his fork of mathjs. @flaviut did you manage to get webpack 5 working? If so it would be great if you could put together a PR.

**Comment by flaviut** [comment]
I rebased https://github.com/josdejong/mathjs/pull/2066 and took another look at it, but no, I haven't been able to get it working, and unfortunately I won't have time in the near future to look at it.

**Comment by josdejong** [comment]
Thanks for giving it a try, appreciated!

Anyone else able to have a look?

**Comment by gwhitney** [comment]
The current package.json lists webpack 5.88.2, so assuming this is accomplished and just left open by accident. Closing.

**Comment by josdejong** [comment]
You're right, we managed to upgrade to Webpack 5 some time ago.
