### ISSUE TITLE
Checking if value is contained within set or array

### ISSUE THREAD

**Issue by yanickrochon** [josdejong/mathjs#2061]
How would I parse an expression such as

```js
const exists = list.includes(value);
```

In writing, I would do 

```
exists = value ∈ list
```
In short, I did not find a way to parse expressions with values as sets. (see [Set Theory Symbols](https://www.rapidtables.com/math/symbols/Set_Symbols.html))

**Comment by josdejong** [comment]
You could use `setIsSubset` to see whether a value is contained in a set:

```
list = [1,2,3]

setIsSubset([2], list) // true
setIsSubset([4], list) // false
```
