### ISSUE TITLE
remove travis badge from readme

### ISSUE THREAD

**Issue by harrysarson** [josdejong/mathjs#2063]
We forgot to do this in #2041 but the badge will go red pretty soon.

**Comment by josdejong** [comment]
ah, good point. I will do this right away

**Comment by josdejong** [comment]
let me see if there is a github workflow badge...

**Comment by josdejong** [comment]
Yes:

<img src='https://github.com/josdejong/mathjs/workflows/Node.js%20CI/badge.svg' />

https://github.com/josdejong/mathjs/workflows/Node.js%20CI/badge.svg
