### ISSUE TITLE
Is there any way to convert expression in mathjs to native javascript?

### ISSUE THREAD

**Issue by MAGNETO903** [josdejong/mathjs#2068]
Hello!
Can I convert mathjs expression in mathjs to native javascript
I want something like this:
```
var func = math.parse("sin(cos(x^2))").toJS()
```
`func` is something like:
```
function(x) {
   return Math.sin(Math.cos(Math.pow(x, 2)))
}
```

I trued to use mathjs's `math.compile()` and `math.evaluate()`

But when I measured the speed of this, I found out that it works about 3-4 times slower, than native JS function (see jsFiddle)
[math.compile() vs defining with math.evaluate() vs native js function](https://jsfiddle.net/magneto903/m10dxsLw/6/)

But I want to get function, that works as fast, as native JS

**Comment by MAGNETO903** [comment]
[My measures](https://jsfiddle.net/magneto903/m10dxsLw/1/)

**Comment by josdejong** [comment]
In general, mathjs is indeed slower than plain, native JavaScript (see also the benchmarks code [here](https://github.com/josdejong/mathjs/tree/develop/test/benchmark)). 

There are two things going on here:

1. Compiling and evaluating an expression. 

    If executing an expression is the bottleneck, you could write your expression in plain JavaScript instead, ie.

    ```js
    import { sin, cos, pow } from 'mathjs'

    const func = (x) => sin(cos(pow(x, 2)))
    ```

2. Using different function implementations, i.e. using `sin` from mathjs or using `Math.sin` from JavaScript. 

    The functions built in mathjs support different data types (like units, bignumber, complex numbers, matrices, ...), so they are more heavy weight than the functions like `Math.sin` built in JavaScript, which just handle a `number`. If this is a bottleneck, and you only need numbers, you can create a mathjs instance using those functions instead. Because this is a common use case, mathjs makes this easy for you: use `import { ... } from 'mathjs/number'` instead of `import { ... } from 'mathjs'`. See docs: https://mathjs.org/docs/custom_bundling.html#numbers-only
