### ISSUE TITLE
Calculate error

### ISSUE THREAD

**Issue by joytou** [josdejong/mathjs#2071]
```
let a = 11.1;
let b = 1.11;
let c = math.evaluate(a + "*" + b);
return c;
```

It display `12.321000000000002`, instead of `12.321`.

**Comment by joytou** [comment]
The same, 
```
let a = 111;
let b = 1.11;
let c = math.evaluate(a + "*" + b);
return c;
```

it display `123.21000000000001`, instead if `123.21`.

**Comment by josdejong** [comment]
This is the most asked question 😄 . It's a round off error.

See docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
See issues: https://github.com/josdejong/mathjs/issues?q=is%3Aissue+roundoff-errors+is%3Aclosed
