### ISSUE TITLE
Error after webpack build 

### ISSUE THREAD

**Issue by hehongfe** [josdejong/mathjs#2074]
![image](https://user-images.githubusercontent.com/18339679/103398166-69e87c00-4b76-11eb-8cc5-b59547f567cc.png)

Error after webpack build 
 the way:
![image](https://user-images.githubusercontent.com/18339679/103398246-d2375d80-4b76-11eb-80e6-3904cf72c6ac.png)

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce this issue?

**Comment by Ander00** [comment]
Getting the same error, after building for the production environment only and limited to 8.1.1. Going back to 8.1.0 fixed it for us.

**Comment by josdejong** [comment]
That it happens only since `v8.1.1` gives a very good clue, thanks. @Ander00 how can I reproduce this issue?

**Comment by m93a** [comment]
Closing as "cannot reproduce".
