### ISSUE TITLE
Function for the total number of items in an array/matrix

### ISSUE THREAD

**Issue by Josef37** [josdejong/mathjs#2085]
Here's overview how other libraries call their functions:

| Library | element count | each dimension |
| --- | --- | --- |
| numpy | [`size`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.size.html) | [`shape`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html) |
| Julia | [`length`](https://docs.julialang.org/en/v1/base/arrays/#Base.length-Tuple{AbstractArray}) | [`size`](https://docs.julialang.org/en/v1/base/arrays/#Base.size) |
| mathjs | ? | `size` |

I'm not sure how to call it then... Do you have a good idea?

PHP calls its array length `count`. But using `numberOfElements` or `elementCount` seems a bit long.

_Originally posted by @Josef37 in https://github.com/josdejong/mathjs/pull/2075#discussion_r559786530_

**Comment by josdejong** [comment]
Hm, good question. 

I'm afraid using `length` will become confusing: if you accidentally call `.length` on your 2d nested JavaScript Array, it will return the size of the outer dimension. 

So probably best to make it a very explicit name, like `elementCount` or maybe `count`. What has your preference?

**Comment by Josef37** [comment]
Oh, that `.length` makes my idea really bad 😅 

I think `count` is very good. Do you know a case where this could be confused? I don't.

**Comment by josdejong** [comment]
I think `count` is a good choice 👍

**Comment by josdejong** [comment]
Function count is now available in `v9.2.0`. Thanks again Josef
