### ISSUE TITLE
Extreme Vulnerability by simple evaluation of "1:999999999999999999" which crashes the process running it

### ISSUE THREAD

**Issue by MisterSirCode** [josdejong/mathjs#2088]
I wanted to use MathJS in a discord bot of mine as an evaluator.

I was sadly disappointed to learn from a friend that MathJS has a simple vulnerability where evaluating `1:9999999999` or something similar would instantly crash the node process.

Meaning my bot can be crashed by any random user with a command that takes no work to type at all

Heap Error:
```
FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20210123.103736.14892.0.001.json
Node.js report completed
 1: 00007FF7272E363F napi_wrap+128063
 2: 00007FF727282836 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+35142
 3: 00007FF7272834F6 public: bool __cdecl v8::base::CPU::has_sse(void)const __ptr64+38406
 4: 00007FF727A99F4E private: void __cdecl v8::Isolate::ReportExternalAllocationLimitReached(void) __ptr64+94
 5: 00007FF727A82021 public: class v8::SharedArrayBuffer::Contents __cdecl v8::SharedArrayBuffer::Externalize(void) __ptr64+833
 6: 00007FF72794E57C public: static void __cdecl v8::internal::Heap::EphemeronKeyWriteBarrierFromCode(unsigned __int64,unsigned __int64,class v8::internal::Isolate * __ptr64)+1436
 7: 00007FF72796B632 public: class v8::internal::Handle<class v8::internal::FixedArrayBase> __cdecl v8::internal::Factory::NewFixedDoubleArray(int,enum v8::internal::AllocationType) __ptr64+98
 8: 00007FF727847CCF public: class v8::Isolate * __ptr64 __cdecl v8::Message::GetIsolate(void)const __ptr64+6303
 9: 00007FF7276F824A public: class v8::internal::interpreter::JumpTableTargetOffsets::iterator & __ptr64 __cdecl v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=(class v8::internal::interpreter::JumpTableTargetOffsets::iterator && __ptr64) __ptr64+162938
10: 00007FF727EE4DDD public: virtual bool __cdecl v8::internal::SetupIsolateDelegate::SetupHeap(class v8::internal::Heap * __ptr64) __ptr64+546637
11: 000000C752F8EB05
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! googleclouddiscordbot@1.0.0 start: `node index.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the googleclouddiscordbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\-----Removed-----\AppData\Roaming\npm-cache\_logs\2021-01-23T15_37_36_815Z-debug.log
```

**Comment by josdejong** [comment]
When letting users do arbitrary calculations on your backend, you indeed have to take some measures: users can do calculations which will run out of memory, or take hours to calculate, effectively blocking the CPU. 

I hope the ideas on the following page are helpful: https://mathjs.org/docs/expressions/security.html#stability-risks

So, for example on https://api.mathjs.org, there is a small node.js server which uses `workerpool` to isolate every calculation and run multiple in parallel, and limit every request to max 10 seconds.

If you know of a way to prevent this from happening I would love to know, but there is simply an endless amount of possibilities to create long running or memory eating expressions, and depending on the context this may be ok or not (ie. you may want to run a multi hour simulation on a heavy machine with 256GB memory, or the opposite: you may have a simple 1GB RAM nodejs instance in the cloud and want to limit users to max 10 seconds or so).

**Comment by MisterSirCode** [comment]
> When letting users do arbitrary calculations on your backend, you indeed have to take some measures: users can do calculations which will run out of memory, or take hours to calculate, effectively blocking the CPU.
> 
> I hope the ideas on the following page are helpful: https://mathjs.org/docs/expressions/security.html#stability-risks
> 
> So, for example on https://api.mathjs.org, there is a small node.js server which uses `workerpool` to isolate every calculation and run multiple in parallel, and limit every request to max 10 seconds.
> 
> If you know of a way to prevent this from happening I would love to know, but there is simply an endless amount of possibilities to create long running or memory eating expressions, and depending on the context this may be ok or not (ie. you may want to run a multi hour simulation on a heavy machine with 256GB memory, or the opposite: you may have a simple 1GB RAM nodejs instance in the cloud and want to limit users to max 10 seconds or so).


Thankyou, Ill give this a try. I guess I shouldve expected it was something Id have to take care of myself, since there isnt too much that can be done to the library that wouldnt break usability of a specific feature

**Comment by josdejong** [comment]
👍
