### ISSUE TITLE
Mathjs 9.1.0 can't load crypto 

### ISSUE THREAD

**Issue by OttawaIan** [josdejong/mathjs#2096]
From looking around this issue was supposedly fixed awhile ago but I upgraded from 7.1.0 to 9.1.0 and I am having this issue in my typescript project.   Does anyone know how to fix it ??  It seemed like bigdecimal fixed this in version 

require.js:143 Uncaught Error: Script error for "crypto", needed by: mathjs/math

The example is a simple node project that displays an html page
import * as mathjs from "mathjs/math";
this.mathjsSqrt = ko.observable(mathjs.sqrt(4));

I am loading mathjs from mathjs/lib/browser folder

**Comment by josdejong** [comment]
Thanks for reporting @OttawaIan . How can I reproduce this issue exactly?

I do indeed still see a reference to `"crypto"` in the bundle script:

https://github.com/josdejong/mathjs/blob/5011ed1f04f0441c052d38ac3c796bf740e6522e/gulpfile.cjs#L84-L86

It may be a matter of removing this dependency.

**Comment by josdejong** [comment]
I've cleaned up this reference to crypto, not yet published though. This may solve your issue.

**Comment by OttawaIan** [comment]
Awesome, is there anything I can do in the short term ?  I even went back
and tried older versions 8.x  and still had the same issue.  It didn't
exist in 7.1.0 version of mathjs

I am on node v12.13.0.

Thanks for the quick response

Ian

**Comment by josdejong** [comment]
What would help me is knowing how to reproduce your issue. So far it's only a guess from my side.

**Comment by OttawaIan** [comment]
I tried removing the crypto from your gulpfile.cjs, rebuilt the library and
ran my application with the new compiled version and that did the trick.

I removed the lines:
externals: [
    'crypto' // is referenced by decimal.js
  ],


My application is pretty simple just a simple typescript web application
running with a controller.ts with
import * as mathjs from "mathjs/math";
class RootViewModel {
mathjsSqrt: ko.Observable;
  constructor() {
this.mathjsSqrt = ko.observable(mathjs.sqrt(4));
}
}

export default new RootViewModel();

Simple index.html
<html lang="en-us">
<body class="web-applayout-body">
<p>Testing mathjs: It should display the square root of 4 (i.e., 2):
    <oj-bind-text value="[[mathjsSqrt]]">
    </oj-bind-text>
</p>

</body>
</html>
Ian

**Comment by josdejong** [comment]
Awesome! Great to hear that this indeed fixes your issue 👍

**Comment by josdejong** [comment]
The fix is now published in `v9.2.0`
