### ISSUE TITLE
Is it possible to save an expression tree as a function directly? / How to use a custom parser (e.g. Jison or Bison) with math.js?

### ISSUE THREAD

**Issue by anonymousperson1209** [josdejong/mathjs#2099]
I was hoping something like this would work.

```js
let parser = math.parser();

let x = 3;
parser.set('f(x)', math.pow(x, 3);
parser.evaluate('f(2)');
```

My use case is that I'm writing my own [Jison](https://github.com/zaach/jison) syntax, so I'm hoping to not require math.js to keep parsing out math strings into trees manually if have already parsed the input.

**Comment by josdejong** [comment]
You where close, you can do this indeed:

```js
let parser = math.parser();

let x = 3;
parser.set('f', (x) => math.pow(x, 3));
parser.evaluate('f(2)');
```

**Comment by josdejong** [comment]
Or:

```js
math.import({
  f: (x) => math.pow(x, 3)
})

math.evaluate('f(2)');
```

**Comment by anonymousperson1209** [comment]
Thanks for the quick reply. I am realizing that I am leading this to an [XY Problem](https://xyproblem.info/).

My goal is to handle math that involves Unicode characters (`≤`, `∫`, typing based on character font, etc). I looked through a couple of other issues and [you suggested](https://github.com/josdejong/mathjs/issues/467#issuecomment-141633265) users utilize a parser generator such as [Jison](http://zaa.ch/jison/) if they wish to significantly change the math.js API.

This is a great suggestion; Jison looks really interesting to use and math.js is super powerful. But, I have a few questions as to how you'd recommend structuring a Jison + math.js project:

First, let me set up a concrete example. Let's say I need to parse a simple equation: `3 ⋅ 2 ÷ 2`. I have a choice; I can convert this to either of the following.
* `3 * 2 / 2` (math.js expression syntax)
* `math.divide(math.multiply(3, 2), 2)` (JavaScript)

For this example, either way works. Initially, I went straight to converting to the JavaScript because it felt more proper (why should I parse something and then give it to math.js to parse again instead of giving it straight to the JavaScript?). But, I am starting to think I should write the Jison to convert my syntax to math.js expression syntax. For instance, let's say I want to parse the following: `f(𝑥) ≔ 𝑥²`. Converting this to math.js expression syntax is easy: `f(x) = x^2`.

**Is there any disadvantage to converting my Jison input to math.js expression syntax instead of converting it directly into trees?** One disadvantage I see is that I can't easily take the derivative of a function; `derivative('f(x)', 'x')` does not work. If I had the tree for `f(x)`, I could pass that to `derivative`. **Is this just an issue that happens to happen now due to `derivative`'s infancy, or are there certain functions in math.js that only accept trees, not expression syntax strings?**

**Finally, when you suggested the use of Jison, were you thinking the input would be converted to math.js expression syntax or to math.js trees directly?**

**Comment by josdejong** [comment]
You indeed have basically two approaches. The first approach, adjusting the expression to make it a valid expression for the parser of mathjs is probably the least amount of work, _if_ it is possible to do so. If the only differences are allowing other characters like `÷` for division, this should be quite easy to do with a regular expression for example. However if the syntax you want really differs from the syntax of mathjs (like having different preference for operations), and there is not a clear 1:1 conversion to the syntax of mathjs, I think it would be best to create your own parser instead, which can directly output code like `math.divide(math.multiply(3, 2), 2)`, or generate a tree output like `math.parse(...)` does (with nodes like `OperatorNode`, `SymbolNode`, etc). Which of these two is best depends on your use case I guess. What is important to keep in mind is that in the end you have to evaluate code, which introduces security risks when using `eval` or `new Function`. The expression tree generated by the mathjs parser does not use these two, so is secure in this regard, see: https://mathjs.org/docs/expressions/security.html

**Comment by anonymousperson1209** [comment]
I appreciate the help. Thanks for the quick replies. This is a great library!

**Comment by josdejong** [comment]
👍 you're welcome
