### ISSUE TITLE
Incorporate with regression.js

### ISSUE THREAD

**Issue by JZL** [josdejong/mathjs#21]
I love your program and was using it a lot in my code but i also needed to do a regression analysis. Its only one more script src but i found a great library at https://github.com/Tom-Alexander/regression-js that works perfectly. I also saw that you program(rightly so) has a much bigger user database. I thought it would be a good combination if you made a sort of pull request(i realize that maybe it would make your code much larger but its just a thought. maybe even just a footnote under your statistics tab in the readme)

Thanks

**Comment by tommedema** [comment]
has this ever been done? interested in doing multivariate regression

**Comment by ericman314** [comment]
It may be a little outside the scope of math.js to have a built-in regression routine, but perhaps not.

Here's a [live demo](https://sesinnovation.com/curve-fitting/) of single variable regression using math.js. The [source](https://github.com/ericman314/easy-curve-fitting) is on GitHub but it's a couple years old. It shouldn't be too much work to extend that example to multiple variables.

**Comment by josdejong** [comment]
Closing this issue now, it's inactive for quite a bit. Feel free to reopen if there are fresh plans.
