### ISSUE TITLE
Improve performance of `max` and `min`

### ISSUE THREAD

**Issue by pseudosavant** [josdejong/mathjs#212]
Using `Math.max.apply(null, array)` is ~100x faster on large arrays than the current `max` and `min` implementation.

Note that Chrome has a limit of ~100k arguments when using `.apply` so arrays larger than 100k values need to be done in batches. See [here](https://github.com/pseudosavant/psMathStats/blob/master/dist/psMathStats.js#L133).

**Comment by josdejong** [comment]
math.js is slower because it's doing type-checking of all array values. 

Performance improvements for matrix operations in general is on the radar, see for example https://github.com/josdejong/mathjs/issues/275. Is it ok with you to close this issue?
