### ISSUE TITLE
Sum of string number without conversion to BigNumber

### ISSUE THREAD

**Issue by BunnyBoss75** [josdejong/mathjs#2120]
Hi, I have some problem here. I'm using internal type 'BigNumber' and trying to add two string number, but the addition happens with type 'number'. I cannot convert these numbers to 'BigNumber' before evaluate, because there are a lot of them and for each expression it is not very rational to convert them all. There is a simple solution: convert them in the expression itself, but this will complicate them considerably. Is there some way to do the conversion to 'BigNumber' from a string without using bignumber() ?
```
const num1 = '0.1';
const num2 = '0.2';
const num3 = '0.3';
const scope = {num1, num2, num3};
const math = create(all, {number: 'BigNumber'});
const res1 = math.evaluate("0.1 + 0.2 - 0.3");     // Desimal 0
const res2 = math.evaluate("num1 + num2 - num3", scope);    // numer 5.55111e-17
const res3 = math.evaluate("'0.1' + '0.2' - '0.3'");    // number 5.55111e-17
const res4 = math.evaluate("bignumber(num1 + num2 - num3)", scope);    // Decimal 5.55111e-17
const res5 = math.evaluate("bignumber(num1) + bignumber(num2) - bignumber(num3)", scope);    // Decimal 0
```

**Comment by josdejong** [comment]
I think the easiest is to turn num1, num2, and num3 into BigNumber yourself before passing them to `math.evaluate`. Something like:

```js
const num1 = '0.1'
const num2 = '0.2'
const num3 = '0.3'
const scope = { num1, num2, num3 }

const preprocessedScope = {}
Object.keys(scope).forEach(key => {
  preprocessedScope[key] = typeof scope[key] === 'string' 
    ? math.bignumber(scope[key])
    : scope[key]
})

math.evaluate("num1 + num2 - num3", preprocessedScope)
```

Related topic: #864

**Comment by BunnyBoss75** [comment]
Thanks for the answer, but the problem is that there are many string objects in the scope. However only one or two are being used. That and the amount of requests would cause a great loading. Therefore, I guess, I will use bignumber() in the expression.

**Comment by josdejong** [comment]
Many as in hundreds? Or millions?

What you could do is analyze which symbols are actually used in the expression, and only convert those. Basically: first `parse` an expression, then `traverse`, and search for all occurences of  `SymbolNode`.

Docs: https://mathjs.org/docs/expressions/expression_trees.html
Example: https://mathjs.org/examples/advanced/expression_trees.js.html

**Comment by BunnyBoss75** [comment]
Thanks.
At first, I think it’s a great solution and I tried it out. Unfortunately, it’s not exactly what I need. As it turns out, ‘scope’ parameter  can contain something like "total.value" and 'total' doesn't need to be converted to bignumber, only ‘value'. 
And there’s another problem: 'value' might be an object or an array, and it doesn't need to be converted too.  
So I think creating variables with bignumber() before using them in another expression will have to do:)

**Comment by josdejong** [comment]
Ok!

I suppose it's still possible to pre-process your values but it sounds like you need to write a recursive function and check whether values are actually a string when iterating over them. 

I'll close this issue now.
