### ISSUE TITLE
Converting a binary number to decimal

### ISSUE THREAD

**Issue by skgadi** [josdejong/mathjs#2121]
Hi,

I am trying to understand how to convert a binary number to decimal. Please guide me.

I understand that it is very direct to convert a decimal to binary with the following code.

```javascript
const a = math.bin(5);
//a = "0b101"
const b = math.bin(5.2);
// b = "0b101.00110011001100110011001100110011001100110011001101"

```
I don't know how to convert binary to decimal. I tried the following but with no complete success.

```javascript
const c = math.number(a);
// c = 5
const d = math.evaluate(a);
// d = 5
const e = math.number(b);
// error
const f = math.evaluate(b);
// error
```

Thank you!
Best regards

**Comment by josdejong** [comment]
I think this feature of parsing decimals like say `math.evaluate('0b1.01')` wasn't yet implemented. Is that correct @clnhlzmn? We discussed this in PR #1996 (see point 4. of my comment https://github.com/josdejong/mathjs/pull/1996#issuecomment-738673942).

**Comment by clnhlzmn** [comment]
That's right. Support for things like `math.evaluate('0b1.01')` was not added in #1996. I would be happy to take a look at it though.

**Comment by skgadi** [comment]
Thank you for your replies.

**Comment by skgadi** [comment]
Great! Thank you.
