### ISSUE TITLE
Missing TypeScript declaration for math.row()

### ISSUE THREAD

**Issue by soogui** [josdejong/mathjs#2123]
While working on a TS project, I am unable to use `math.row()` and `math.column()` functions. In my editor, I get the following error:
`Property 'row' does not exist on type 'MathJsStatic'.ts(2339)`.

Using `@types/mathjs": "^6.0.11`  and `mathjs": "^9.0.0`.

Thank you in advance.

**Comment by josdejong** [comment]
The TypeScript definitions are not up to date unfortunately. Help would be very welcome (it shouldn't be hard to at least add the missing functions like these to the definitions).

See also: #1801, #2100, #2076, #2019

**Comment by maria92ruiz** [comment]
Hi, we are a group of students from the University of Seville. We've been working on a project based on math.js. Hence, we've tried to fix the issue raised. Here's the [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52305).
Hope it helps!

**Comment by josdejong** [comment]
Thanks a log @maria92ruiz for picking this up 👍 👍 

It would be great if you could also have a look in for example https://github.com/josdejong/mathjs/issues/2019, that is a one-liner just removing the `null` from the definitions. Hopefully that solves the issues some people have in VS Code autocompletion.

**Comment by josdejong** [comment]
Fixed now in `mathjs@9.4.0` with the now build-in type definitions too.
