### ISSUE TITLE
typo: math.lsolve -> math.lsolveAll

### ISSUE THREAD

**Issue by milahu** [josdejong/mathjs#2128]
https://mathjs.org/docs/reference/functions.html#algebra-functions
third row should be `math.lsolveAll(L, b)`
last row should be `math.usolveAll(U, b)`

**Comment by josdejong** [comment]
Thanks for reporting, will be fixed in the first next release via 1587d12

**Comment by josdejong** [comment]
Typo is fixed now in `v9.3.0`
