### ISSUE TITLE
The function "isPrime" may emit a endless loop when paramater is huge.

### ISSUE THREAD

**Issue by JamesLIAOHJ** [josdejong/mathjs#2133]
my testing code:

```js
const { create, all } = require('mathjs');
const config = {
  epsilon: 1e-12,
  matrix: 'Matrix',
  number: 'BigNumber',
  precision: 256, //i have try 64 128
  predictable: false,
  randomSeed: null
}
const math = create(all, config)
let a = math.bignumber("230584300921369395");
let b = math.bignumber("2305843009213693951");
console.log("230584300921369395 is Prime", math.isPrime(a));  //this number is fit for then function isPrime
console.log("------");
console.log("2305843009213693951 is Prime?");
console.log(math.isPrime(b));  //this line will not finish, the cpu is 100%
console.log("exit");
```

I run it in node v12.18.1 on macOS Big Sur

I have try `precision: 64` , `precision:128` and 256,  result is the same.

Then I have check source file `isPrime.js` in path `./node_modules/mathjs/lib/cjs/function/utils/isPrime.js` 

I think the problem maybe there.  

```js
//  ./node_modules/mathjs/lib/cjs/function/utils/isPrime.js

...
BigNumber: function BigNumber(n) {
...
     for (var i = 5; n.gte(i * i); i += 6) {
        if (n.mod(i).eq(0) || n.mod(i + 2).eq(0)) {
          return false;
        }
      }
...
```

my question is: 
can `i*i` here cause the endless loop when n is big enough ?

thx.

**Comment by JamesLIAOHJ** [comment]
Sorry,   it took about 3000 seconds to execute the function `isPrime(b)` on my computer.  So  It's my fault.  I think this Issue can close now.

**Comment by Yaffle** [comment]
@JamesLIAOHJ 
If you need something much faster (for number bigger than 2**53) - a variant is https://en.wikipedia.org/wiki/Miller–Rabin_primality_test#Deterministic_variants .

**Comment by josdejong** [comment]
👍 . Yeah a faster implementation would of course be welcome 😄

**Comment by Yaffle** [comment]
@josdejong 
it is implemented in https://github.com/peterolson/BigInteger.js :
```
var bigInt = require("big-integer");

console.time();
console.log(bigInt('2305843009213693951').isPrime(true)); // false
console.timeEnd(); // ~12ms
```

**Comment by hsmyers** [comment]
Everyone is aware that MR is a probabilistic test, yes?

**Comment by Yaffle** [comment]
@hsmyers , I don't know, but is the "deterministic variant" 100% accurate?

**Comment by hsmyers** [comment]
Well, by definition, 'probabilistic' can't guarantee 100%. No more than a
sieve can unless infinite. But as you test under more and more bases, it is
less and less likely that the test is wrong. A bit like calculus and the
area under a curve. At some point someone yells out 'enough!' and you quit
testing. I remember when my partner in a small architects firm, walked in
and asked what I was doing. I told him I was making sure of the details on
the current set of plans (I was a plans architect—it's what they do.) He
looked at the screen and asked me what the scale was. I typed the code to
display the distance from point to point. He then rudely pointed out that
at the scale shown, the 'fix' would take an electron microscope to see! I
said 'Oh!' Sort of like that :)

**Comment by Yaffle** [comment]
@hsmyers nice example,
There is a "Deterministic variant" although, which is not probabilistic, seems. Well... it relies on something not proved.
Btw, seems, "deterministic" is a much like probabilistic, but iterates for a range up to some limit...

**Comment by hsmyers** [comment]
The first software I open-sourced was a diskette (5-1/4) of prime number
functions along with the necessary Unlimited Precision math. This went to
the 'C' User Group. Sometime in the 70's I think. I thought of this while
looking at the bottom of the Wikiencylopedia page reference earlier. Seems
like doing those using the obvious library in JS would be at least as much
fun as doing them in BDS C. See; https://www.bdsoft.com/resources/bdsc.html

**Comment by Yaffle** [comment]
Here is my code which uses native BigInt:
```javascript
function bitLength(n) {
  return n.toString(16).length * 4;
}

function modPow(base, exponent, modulus) {
  // exponent can be huge, use non-recursive variant
  let accumulator = 1n;
  while (exponent !== 0n) {
    if (exponent % 2n === 0n) {
      exponent /= 2n;
      base = (base * base) % modulus;
    } else {
      exponent -= 1n;
      accumulator = (accumulator * base) % modulus;
    }
  }
  return accumulator;
}

function* range(start, end) {
  for (let i = start; i <= end; i += 1) {
    yield i;
  }
}

// isPrime implementation is taken from:
// https://github.com/peterolson/BigInteger.js
// https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test#Deterministic_variants
function isPrime(n) {
  n = BigInt(n);
  if (n < 2n) {
    throw new RangeError();
  }
  if (n === 2n) {
    return true;
  }
  if (n % 2n === 0n) {
    return false;
  }
  let r = 0;
  let d = n - 1n;
  while (d % 2n === 0n) {
    d /= 2n;
    r += 1;
  }
  let bases = null;
  // https://en.wikipedia.org/wiki/Miller–Rabin_primality_test#Testing_against_small_sets_of_bases
  if (n < 3317044064679887385961981n) {
    bases = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41].filter(x => x < n);
  } else {
    const max = Math.floor(2 * (bitLength(n) * Math.log(2))**2);
    bases = range(2, max);
  }
  for (const a of bases) {
    const adn = modPow(BigInt(a), d, n);
    if (adn !== 1n) {
      for (let i = 0, x = adn; x !== n - 1n; i += 1, x = (x * x) % n) {
        if (i === r - 1) {
          return false;
        }
      }
    }
  }
  return true;
}
```

**Comment by josdejong** [comment]
Thanks for sharing @Yaffle . So is the BigInt implementation faster or better?

**Comment by Yaffle** [comment]
@josdejong , it takes only few milliseconds for the number 230584300921369395

**Comment by josdejong** [comment]
😎  that is huge! Would be great to have this implementation in mathjs. Older browsers do not have support for `BigInt` though so I think we need to fallback on the current implementation if there is no `BitInt` support. Anyone interested in working out a pull request?

**Comment by Yaffle** [comment]
@josdejong , how to fallback? seems, you are using decimal.js library for both integers and floating point numbers.
What do you think about importing of https://github.com/peterolson/BigInteger.js ?

**Comment by josdejong** [comment]
> seems, you are using decimal.js library for both integers and floating point numbers.

That is correct.

I haven't thought it through but expect we can do something like:

```js
if (typeof BigInt === 'undefined') {
  // use slow BigNumber implementation
} else {
  // use fast native BigInt implementation
}
```

**Comment by josdejong** [comment]
Using a library like https://github.com/peterolson/BigInteger.js is an interesting idea too btw!

Full support for BigInt is also on the wishlist BTW, see #1096.

**Comment by Yaffle** [comment]
@josdejong https://github.com/josdejong/mathjs/pull/2139/files
