### ISSUE TITLE
Enable filtering using a boolean index

### ISSUE THREAD

**Issue by hakib** [josdejong/mathjs#214]
mathjs is supporting cell wise operations which makes filtering a very simple task. Inspired by R and pandas I feel that the current implementation can be simplified using boolean indexes.

For example, 
```
a = 1:10
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
a > 5
[false, false, false, false, false, true, true, true, true, true]
```
So intuitively, The filter can support `filter(a, a>5)`

Since mathjs implicitly applies a function when operating on an array it also makes it easier to use functions in filters. Using the isPositive example from the docs

```
a = -5:5
[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5]
filter(a, sign(a) == 1)
# or 
filter(a, a > 0)
```
With existing functionality it's also possible to use intersection easily. For example, All numbers between -1 and 3 
```
filter(a, (a>-1) .* (a<2))
```

When using matrices It's a bit more tricky - There are two use cases 
1. Filter matrix rows, In this case the first dimension of the matrix and the boolean index should match. The most common use case for it is filtering a matrix by a "column", For example 
```
m = [[1,2,3],[4,5,6],[7,8,9]]
filter(m, m[:,2] >= 5)
```
2. Filter matrix cells, in this case the boolean index should match the size of the matrix. 
```
filter(m, m > 5)
```
I personally think that empty rows should be removed from the result, so the above would return `[[null,null,6],[7,8,9]]`. 

One cavet for the boolean index approach is that it requires creating another array/matrix to hold the boolean index results which might cause some performance issues when operating on a (very) large data sets. This can be solved by enabling function based filtering as it is now.

P.S , The doc for `filter` is missing from the doc folder. Noticed that the link from the [index](https://github.com/josdejong/mathjs/blob/master/docs/reference/functions/alphabetical.md) is broken.

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by hakib** [comment]
Nope. Thanks.

**Comment by josdejong** [comment]
Ok thanks for the feedback, I will close the issue. If you have more ideas/suggestions just let us know :)
