### ISSUE TITLE
Matrix row vs column / x vs y coordinate conventions

### ISSUE THREAD

**Issue by slutske22** [josdejong/mathjs#2142]
I am struggling to get my coordinates right with my matrices.  I'm not sure if I'm not understanding something, or maybe if I'm missing something in the docs.  Let's say I want to create a matrix that is 2 units wide by 5 units tall ([x, y] size is [2, 5]):

```javascript
const myMatrix = math.zeros([2, 5], 'sparse')

console.log(myMatrix.valueOf())
// gives:
(2) [Array(5), Array(5)]
0: (5) [0, 0, 0, 0, 0,]
1: (5) [0, 0, 0, 0, 0,]
```
This appears to be the inverse of what I wanted - the resulting matrix is 5 units wide by 2 units tall.  This seems to be present in all other methods, like `.size`, `.resize`, `.set`, `.get`, etc - they use `[y, x]` coordinates.

I need to synchronize my matrix with a separate coordinate system that uses a very physical concept of width and height, and positions based on x and y.  Is the feedback from the console just visually deceptive?  When I call `math.row(myMatrix, 0)` or `math.column(myMatrix, 0)`, it gives me rows and columns in the same fashion as they are visually laid out above.  Is a 'row' really a collection of y values with a set x value, and a column is a set of x values with a common y value?  I am struggling to understand.

**Comment by josdejong** [comment]
Representing a 2D matrix with nested 1D Arrays can be confusing indeed. When having a 2D matrix, the first dimension is normally corresponding to column, and the second one with row. This is quite common as far as I know.

So with math.js:

![afbeelding](https://user-images.githubusercontent.com/568626/112288136-54728200-8c8d-11eb-88ca-ec7ba5a303ad.png)

And for example with Matlab/Octave:

![afbeelding](https://user-images.githubusercontent.com/568626/112288238-6ce29c80-8c8d-11eb-8cd6-0fe5d3d76bde.png)

If you want to associate a dimension of a matrix with a physical x,y position you may want to invert either the way you render the data, or invert the way you input it to y,x.

**Comment by slutske22** [comment]
This is exactly the answer I needed, thank you.  Perhaps this detail could make its way into the docs?  Its been about a million years since I used Matlab, so I forgot this convention, and I imagine there may be other mathjs users who might benefit from seeing this in the docs.  (Unless its already there and I missed it?)

Considering I am trying to correlate matrix positions and values with [x, y] positions of pixels in an image, I think it makes more sense to simply reverse the coordinates in my use of all mathjs matrix methods.  For example, creating a matrix corresponds to an image 200px wide by 50px tall would be `math.zeros([50, 200])`.  Getting a pixel value from a canvas for point [x, y] would be `CanvasRenderingContext2D.getImageData(x, y, 1,  1)`, where getting the value from the matrix would be `matrix.get([y, x])`.  So I think that's fine. (If that sounds wrong, please let me know!)

Thank you for your helpful answer.

**Comment by josdejong** [comment]
👍 

It may be good to explain this in the docs indeed. I'm not sure though what would be a good place, do you have any suggestions?

**Comment by slutske22** [comment]
I would recommend on the matrix docs page (https://mathjs.org/docs/datatypes/matrices.html), right after the first codeblock, just before the **Creation** header:

# "
**Note:**
All `math.matrix` methods use a `[y, x]` coordinate system.  For example, `math.zeros(5, 2)` creates a matrix 5 units tall by 2 units wide, `math.set([0, 1], 5)` sets the second item from left in the top row to 5, `math.get(2, 4)` returns the value in the matrix at position y = 3, x = 5, etc.
# "

Something like that. I think it should be early up there in the docs so that the reader already understands this coordinate convention as they start reading about matrix creation, manipulation, etc.

Thank you for your answer and this great library!

**Comment by josdejong** [comment]
Does the follow commit help? https://github.com/josdejong/mathjs/commit/06052ecc86bba40255b9f2ad185f0da5a7cb1e05

**Comment by slutske22** [comment]
Yes! Thank you for adding this.  You rock.
