### ISSUE TITLE
Feature Request: Array/Matrix From Function

### ISSUE THREAD

**Issue by fweth** [josdejong/mathjs#2153]
Something like NumPy's `fromfunction` would be cool, specify a shape and a function to create an array or a matrix.  E.g. `math.fromFunction((x, y) => x * y, [3, 3])` would return `[[0, 0, 0], [0, 1, 2], [0, 2, 4]]`.

**Comment by HK-SHAO** [comment]
Really cool!

**Comment by josdejong** [comment]
Published in `v9.4.0`
