### ISSUE TITLE
add to yarn package manager 

### ISSUE THREAD

**Issue by alirezaseif28** [josdejong/mathjs#2157]
please add mathjs to yarn package manager

**Comment by josdejong** [comment]
You can use any npm package in yarn directly, right? Do you mean you want to add a description to the docs about it?

**Comment by alirezaseif28** [comment]
thanks .I mean in the yarn package manager no provide `yarn add mathjs`

**Comment by DDeme** [comment]
For me it works as expected
` 
yarn add mathjs
yarn add v1.22.10
warning ../../../package.json: No license field
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 9 new dependencies.
info Direct dependencies
└─ mathjs@9.3.0
info All dependencies
├─ complex.js@2.0.12
├─ decimal.js@10.2.1
├─ escape-latex@1.2.0
├─ fraction.js@4.0.13
├─ javascript-natural-sort@0.7.1
├─ mathjs@9.3.0
├─ seedrandom@3.0.5
├─ tiny-emitter@2.1.0
└─ typed-function@2.0.0
Done in 0.89s.
`

**Comment by josdejong** [comment]
So @alirezaseif28 is this still an issue?

**Comment by alirezaseif28** [comment]
ok that's right
