### ISSUE TITLE
Incorrect typings in Typescript 

### ISSUE THREAD

**Issue by DDeme** [josdejong/mathjs#2159]
I have difficulty to compile code. 

Example:
 
`
import {floor} from 'mathjs'
floor(n, 6)
`

TSError: ⨯ Unable to compile TypeScript:

"@types/mathjs": "^6.0.11",
"mathjs": "^9.3.0",

In docs function is described with two paramers. 
https://mathjs.org/docs/reference/functions/floor.html

In types there is misstype
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d21a57f090057ab87b7780b46a872c2387c6aa83/types/mathjs/index.d.ts#L662

What should I do to fix this issue ?

**Comment by josdejong** [comment]
Thanks for reporting Dany.

The TypeScript definitions of mathjs are behind. There are a couple open issues with the definitions (see #2019, #2123, #2107, #2100). Help would be very welcome, every small improvement helps.

**Comment by josdejong** [comment]
So to fix we have to create a PR at https://github.com/DefinitelyTyped/DefinitelyTyped improving the type definitions of mathjs.

**Comment by write2kcl** [comment]
Hi Jos can I work on this?
But I cannot see the master branch version of mathjs. Am I missing something
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mathjs

**Comment by josdejong** [comment]
Thanks for your offer Kiran! 

It's easier now: the types are now in the mathjs repository itself, so you don't have to create PR at DefinitelyTyped. See: https://github.com/josdejong/mathjs/tree/develop/types

**Comment by josdejong** [comment]
Fixed now in `v9.4.3`, thanks @write2kcl
