### ISSUE TITLE
Wrong year in the history record  (Web)

### ISSUE THREAD

**Issue by crigarher** [josdejong/mathjs#2160]
Reviewing the history of the versions of Mathjs it came to my mind that the last ones the year is incorrectly.
![image](https://user-images.githubusercontent.com/80218587/113747221-721cfe00-9707-11eb-8087-cd7ba83bbf77.png)

**Comment by josdejong** [comment]
Ouch! 😂  thanks for reporting. I've fixed it in the `develop` branch, this will be reflected on the website after the first next release.
