### ISSUE TITLE
video tutorial

### ISSUE THREAD

**Issue by joaquin-restoy** [josdejong/mathjs#2161]
Hey, wouldn't be nice if there would be a video tutorial explaining the installation of Mathjs in Node to make it easier for people whom is a starter in javaScript?

Thank you for your time and consideration!

**Comment by josdejong** [comment]
I'm not sure about the added value of a video, isn't the Getting Started page https://mathjs.org/docs/getting_started.html explanatory enough?

Installing mathjs is no different with any other npm package in nodejs, so I guess your question boils down to the question how to use npm and nodejs in general? You can search on youtube for tutorials on that:

https://www.youtube.com/results?search_query=how+to+use+an+npm+library+in+nodejs

For example: https://www.youtube.com/watch?v=WtbU1sI7fnw

**Comment by gwhitney** [comment]
As the creation of such a video seems unlikely and could be done by any third party in any case, just going ahead and closing this.
