### ISSUE TITLE
Erratum in the error message displayed by the function .round()

### ISSUE THREAD

**Issue by gonmarmar5** [josdejong/mathjs#2167]
Using the function round with numbers greater than 15 show the following argument : 

Error: Number of decimals in function round must be in ~~te~~ **the** range of 0-15.

The message is defined here https://github.com/josdejong/mathjs/blob/develop/src/function/arithmetic/round.js at
line 154 ->     if (n < 0 || n > 15) { throw new Error('Number of decimals in function round must be in **te** range of 0-15') }

**Comment by josdejong** [comment]
Thanks for reporting this typo @gonmarmar5 , fixed via https://github.com/josdejong/mathjs/commit/e6af8ec92a5bf83445843475f700acec81aea6f8 (fix not yet published)
