### ISSUE TITLE
Implement iterative eigenvalue finder for eigs

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#2179]
The current implementation of `eigs` relies on `usolveAll` to find eigenvectors. This often fails because of numerical errors. A more robust approach would be to use an _iterative_ algorithm. The easiest one in this case would be the [inverse iteration](https://en.wikipedia.org/wiki/Inverse_iteration) algorithm. The gist of the algorithm is this:
1. Take a random vector _b_.
2. Let _A_ be a matrix and _k_ an approximation of its eigenvalue.
3. The expression _( (A − kE)⁻¹ )ⁿ b_ converges to an eigenvector as _n → ∞_.
4. Instead of actual inversion, which is a costly operation, we can perform an implicit inversion using `usolve` _bₖ = (A − kE) bₖ₊₁_.

The relevant code is [here](https://github.com/m93a/mathjs/blob/patch-eigens/src/function/matrix/eigs/complex.js#L418).

**Comment by josdejong** [comment]
Thanks for the clear explanation, makes sense. Are you planning on picking this up yourself @m93a?

**Comment by m93a** [comment]
> Are you planning on picking this up yourself?

When I have the time and mood, yes, definitely. (I expect this means in a month or so, but I can't tell with certainty.) However, if anyone wants to tackle this issue earlier, feel free to :)

**Comment by josdejong** [comment]
👍

**Comment by 895623741x** [comment]
Hi, I would like to work on this issue. However, I am not sure how long will it take to solve the issue since this is my first time contributing to an open source.

**Comment by josdejong** [comment]
Published now in `v9.4.2`
