### ISSUE TITLE
Wrong results comparing unit numbers

### ISSUE THREAD

**Issue by hw762** [josdejong/mathjs#2183]
While the demo on mathjs homepage can correctly compare united numbers, when I import it for use in a Vue.js project, the comparison is wrong.

Minimal self-contained reproducible html:

```html
<!DOCTYPE html>
<head>
	<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/9.3.2/math.js"></script>
</head>
<body>
	<div id="mathjs-root">
		<p>62 Mg &gt; 1Mt ? {{ greater }}</p>
		<p>62 Mg to SI &gt; 1Mt to SI ? {{ greater_kg }}</p>
		<p>62 Mg to Number &gt; 1Mt to Number ? {{ greater_num }}</p>
	</div>
	<script>
		var app = new Vue({
			el: '#mathjs-root',
			data: {
				greater: math.unit("62 Mg") > math.unit("1 Mt"),
				greater_kg: math.unit("62 Mg").toSI() > math.unit("1 Mt").toSI(),
				greater_num: math.unit("62 Mg").toNumber("kg") > math.unit("1 Mt").toNumber("kg"),
			}
		})
	</script>
</body>
```

If you open this in the browser, you note that the results are wrong. If you change `62` to other numbers, the incorrect results will be incorrect in different ways. However, the third option -- manually converting to the same unit _and_ extract number, will be correct

**Comment by hw762** [comment]
Similarly, `*` does not work either. I think other operators have such trouble, too. `multiply()` does work correctly.

**Comment by josdejong** [comment]
@hw762 you're using the JavaScript `>` operator, which will call `.valueOf()` on your units, turning them into a string like `"62 Mg"` and `"1 Mt"`, and then you're comparing those strings, which is indeed nonsensical. You can either use the operators of mathjs for this `math.larger`, or do all calculations in the expression parser, like `math.evaluate('62 Mg < 1 Mt')`.

**Comment by josdejong** [comment]
Though it would be a breaking change, it may be a good idea to throw an error when `.valueOf()` is called instead of silently doing the conversion to string to prevent these kind of mistakes.

**Comment by hw762** [comment]
Huh, but why does the demo on homepage work? Is that performing some implicit conversions? 

I am not so familiar with JS. Previously I also tried comparing the two strings directly, but that throws error about strings cannot be converted to number. For instance, `"62 Mg" < "1 Mt"` would fail.

**Comment by josdejong** [comment]
The demo on the homepage uses `math.evaluate`, like `math.evaluate('62 Mg < 1 Mt')`.
