### ISSUE TITLE
Move TypeScript definitions from DefinitelyTyped into mathjs

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#2187]
For reference: https://github.com/josdejong/mathjs/issues/2185#issuecomment-822223386

Reasons:

- Having to separately install type definitions is an extra for the TypeScript user.
- The type definitions of mathjs at DefinitelyTyped are outdated, and making improvements in it is cumbersome.
- Since TypeScript is quite the defacto standard to describe typings, it makes sense to move it into the library itself.

See also #2076

Help would be very welcome!

**Comment by CatsMiaow** [comment]
PR https://github.com/josdejong/mathjs/pull/2192

**Comment by josdejong** [comment]
Published now in `v9.4.0`, thanks again @CatsMiaow
