### ISSUE TITLE
Wrong operation about matrix

### ISSUE THREAD

**Issue by cjh980402** [josdejong/mathjs#2188]
![image](https://user-images.githubusercontent.com/23624124/115980342-04a61400-a5c7-11eb-92e5-956236f19ebd.png)

[1;2] and [[1],[2]] is same,
but [3,4] and [[3,4]] is not same.

So [1;2]*[3,4] operation throws RangeError.

**Comment by josdejong** [comment]
This is indeed an unfortunate inconsistency in the API: `[1;2]` will result in a 2D matrix, but `[3,4]` in a one dimensional vector. It's because the expression parser does not only support 2d, but also a 1d vector, or 3d or n-d matrices. You can indeed solve it by explicitly creating a 2d matrix `[[3,4]]`.

**Comment by m93a** [comment]
Hey @cjh980402,

I would think that if somebody multiplies a 1-dimensional vector by a 2-dimensional vector, it was most likely a mistake. (I'm refering to the dimension of the array, the math term for it would be [tensor rank](https://mathworld.wolfram.com/TensorRank.html).) While 2-dim vectors have a clear indication whether they're a row (`[[1,2,3]]`) or a column (`[[1],[2],[3]]`), 1-dim vectors (`[1,2,3]`) can represent both a row and a column. If 1-dim vectors were accepted everywhere, where a row or column vector is, it would imho lead to more coding mistakes by people who don't realize how 1-dim vectors work.

However, I think that the error message you got might be confusing. Maybe we could replace it by something like `RangeError: Dimension mismatch in multiplication. Cannot multiply a 1-dimensional vector by a column vector. Did you mean to use 'math.dot' or to multiply a row and a column vector?`
