### ISSUE TITLE
Input ";help" on evaluate returns a function

### ISSUE THREAD

**Issue by SpeckyYT** [josdejong/mathjs#2195]
As the text implies, inputting `;help` returns an array containing a function (with non-sense code imo).

Node.js Version: 14.15.4
Math.js Version: 9.3.2

How to reproduce:
```js
const math = require('mathjs');
const result = math.evaluate(';help');
console.log(result.toString());
```
Output:
```js
[function fn(arg0, arg1) {
        'use strict';

        if (arguments.length === len0 && test00(arg0) && test01(arg1)) { return fn0.apply(fn, arguments); }
        if (arguments.length === len1 && test10(arg0) && test11(arg1)) { return fn1.apply(fn, arguments); }
        if (arguments.length === len2 && test20(arg0) && test21(arg1)) { return fn2.apply(fn, arguments); }
        if (arguments.length === len3 && test30(arg0) && test31(arg1)) { return fn3.apply(fn, arguments); }
        if (arguments.length === len4 && test40(arg0) && test41(arg1)) { return fn4.apply(fn, arguments); }
        if (arguments.length === len5 && test50(arg0) && test51(arg1)) { return fn5.apply(fn, arguments); }

        return generic.apply(fn, arguments);
      }]
```

**Comment by josdejong** [comment]
If you evaluate the name of a function, the function itself will be returned. That holds for any function, like `math.evaluate('sqrt')`.

To use `help`, you should evaluate it as a function, like `math.evaluate('help(sqrt)')`

The reason you get back an array (`ResultSet` with an Array to be precise) is because you're evaluating a multi line expression 
(i.e. `math.evaluate('width=2; height=3;area=width*height')`)

**Comment by SpeckyYT** [comment]
Oh, I didn't know that the "help" function did something. Thanks.

**Comment by josdejong** [comment]
👍

**Comment by m93a** [comment]
Maybe `evaluate` could watch if the result is the `help` function, and if it is, return a helpful hint? The Python REPL does something similar:
```python
>>> help
Type help() for interactive help, or help(object) for help about object.
```

**Comment by josdejong** [comment]
That is a very nice idea @m93a , should be very easy to add an extra case to the expression parser to return an informative message in case of `math.evaluate('help')`.
