### ISSUE TITLE
math.complex.pow() gives 2 different values for same parameter

### ISSUE THREAD

**Issue by rrahulraman** [josdejong/mathjs#2214]
*When using the math.complex.pow() function it is not returning the results as intended.*
I am using math.js through a CDN, I had typed the following commands in the console
```
c = new Complex({ re: -44.56485414747314, im: 0 });
c.pow(1/3)
```
The result matches with the actual result
output:  `{ re: 1.7726956031069194, im: 3.070398850935137 }`

But when the parameter `im:0` is replaced by `im:-0`

```
c = new Complex({ re: -44.56485414747314, im: -0 });
c.pow(1/3)

```
output: `{ re: 1.7726956031069194, im: -3.070398850935137 }`

It returns a negative imaginary part.

**Comment by m93a** [comment]
Hey Rahul,
thanks for reporting the issue! However, I'm not sure if it's a problem that needs fixing. The numbers `+0` and `-0` are different numbers even in vanilla JavaScript: `1/+0 === +Infinity` but `1/-0 === -Infinity`, therefore it makes sense that `{ re, im: +0 }` and `{ re, im: -0 }` are also different numbers. Both of the results you got are valid solutions of the equation _x³ = −44.5648_.

The more theoretical reason for the behavior you're observing is that the function _x<sup>⅓</sup>_ has a [branch cut](https://en.wikipedia.org/wiki/Branch_point) along the half-line _[0+0i, ∞+0i)_, therefore there is a discontinuous jump when moving from the bottom half to the top half of the complex plane. When you pass `im: +0` to the function, you get the limit as _Im(x) → 0_ from the top, for `im: -0` it's a limit from the bottom.

That said, it might be confusing that there are two “complex representations” for each real number. For me personally, it's okay, but if a lot of people found it non-intuitive, it might be enough of a reason to change this behavior and treat `im: +0` and `im: -0` the same... 🤔️

**Comment by rrahulraman** [comment]
Yeah ! I get it now, So -0 is considered to be 

<a href="https://www.codecogs.com/eqnedit.php?latex=\bg_white&space;\lim_{x&space;\rightarrow&space;0^-}&space;x" target="_blank"><img src="https://latex.codecogs.com/png.latex?\bg_white&space;\lim_{x&space;\rightarrow&space;0^-}&space;x" title="\lim_{x \rightarrow 0^-} x" /></a>

I was initially confused because in java script `+0 === -0` returns true.

Should I close this issue then ?

**Comment by m93a** [comment]
> I was initially confused because in JavaScript `+0 === -0` returns true.

Yeah, that's one of the many weirdnesses of [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754#Comparison_predicates) 😅️

> Should I close this issue then?

Yep, we can close it. If anybody thinks it's still a problem, let me or Jos know, we'll reopen it :)
