### ISSUE TITLE
Question: Extracting Rows/Columns of  a Matrix

### ISSUE THREAD

**Issue by BrandonKMLee** [josdejong/mathjs#2215]
Observing https://mathjs.org/docs/datatypes/matrices.html#getting-or-replacing-subsets
They require specifying all rows and columns, and cannot extract columns containing all rows (or vice versa).

**Comment by josdejong** [comment]
Thanks for your input Brandon. What is exactly your question? Is it about utility functions like `row` and `column`? (I see those are not described in the docs you're referring to, would be good to add).

**Comment by BrandonKMLee** [comment]
Yeah, something like that, as NumPy and pandas have that feature.

**Comment by josdejong** [comment]
Ah, I think I understand what you mean. The expression parse can do that for you, here some examples from the docs:

```js
parser = math.parser()

// create matrices
parser.evaluate('a = [1, 2; 3, 4]')       // Matrix, [[1, 2], [3, 4]]
parser.evaluate('b = zeros(2, 2)')        // Matrix, [[0, 0], [0, 0]]
parser.evaluate('c = 5:9')                // Matrix, [5, 6, 7, 8, 9]

// replace a subset in a matrix
parser.evaluate('b[1, 1:2] = [5, 6]')     // Matrix, [[5, 6], [0, 0]]
parser.evaluate('b[2, :] = [7, 8]')       // Matrix, [[5, 6], [7, 8]]

// perform a matrix calculation
parser.evaluate('d = a * b')              // Matrix, [[19, 22], [43, 50]]

// retrieve a subset of a matrix
parser.evaluate('d[2, 1]')                // 43
parser.evaluate('d[2, 1:end]')            // Matrix, [[43, 50]]
parser.evaluate('c[end - 1 : -1 : 2]')    // Matrix, [8, 7, 6]
```

See: https://mathjs.org/docs/expressions/syntax.html#matrices

**Comment by BrandonKMLee** [comment]
`parser.evaluate('b[2, :] = [7, 8]')       // Matrix, [[5, 6], [7, 8]]`

**Comment by josdejong** [comment]
?

**Comment by BrandonKMLee** [comment]
I think the colon part is what is missing, didn't know that such a syntax exists as it looks different from Python.

**Comment by josdejong** [comment]
What is missing exactly? It's quite similar to the syntax of Python I think? Anyway, is your issue resolved?

**Comment by BrandonKMLee** [comment]
Thanks for the resolution, just that Python mostly uses the `array[a][b][c]` rather than `array[a,b,c]` (multi-dimensional array slicing)

**Comment by josdejong** [comment]
ok clear 👍
