### ISSUE TITLE
Setting precision in config doesn't work in "mean" function

### ISSUE THREAD

**Issue by paulrberg** [josdejong/mathjs#2218]
## Description

Setting the precision to 78 doesn't make the `mean` function work with up to 78 significant digits. Take the following code snippet:

```typescript
import { BigNumber, bignumber } from "mathjs";

import { mean } from "./math";

const foo = bignumber("5.7896044618658097711785492504343953926634992332820282019728792003956564819967e+58");
const bar = bignumber("5.7896044618658097711785492504343953926634992332820282019728792003956564819967e+58");
const result = <BigNumber>mean(foo, bar);

console.log({ result: result.toString() });
```

It logs the following:

```js
{
  result: '5.7896044618658097711785492504343953926634992332820282019728792e+58'
}
```

Whereas it should log `5.7896044618658097711785492504343953926634992332820282019728792003956564819967e+58`, because the inputs are equal.

## Steps to Reproduce

1. git clone git@github.com:paulrberg/mathjs-precision-bug.git
2. yarn install
3. yarn ts-node ./src/index.ts

## Environment

- math.js@9.4.0
- typescript@4.2.4

**Comment by paulrberg** [comment]
Nevermind, the issue was that I was importing `bignumber` from the canonical `mathjs` package instead of my local configured instance. Rewriting this line:

```
import { BigNumber, bignumber } from "mathjs";

import { mean } from "./math";
```

To this:

```
import { BigNumber } from "mathjs";
import { bignumber, mean } from "./math";
```

Fixes the issue.

**Comment by josdejong** [comment]
👍
