### ISSUE TITLE
Syntax error in typed.js

### ISSUE THREAD

**Issue by PipGrylls** [josdejong/mathjs#2227]
This script:
`http://localhost:8000/node_modules/mathjs/lib/esm/core/function/typed.js`
is throwing:
`Uncaught SyntaxError: The requested module './../../../../../typed-function/typed-function.js' does not provide an export named 'default'`
on line 39.

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue?

**Comment by PipGrylls** [comment]
I'm still fairly new to JS so I cant rule out user error here.
I am running at the top of a script (5+ years old) I have inherited which was using mathjs.
`import {pi, add, subtract, multiply, dotMultiply, dotDivide, min, max} from 'mathjs';`
I will try and create a minimal example.

**Comment by PipGrylls** [comment]
I get the same error here:
https://github.com/PipGrylls/math-js-test
https://github.com/PipGrylls/math-js-test/blob/main/src/TestTest.js

**Comment by josdejong** [comment]
Ah, this is probably related to loading mathjs as a "pure" ES module, without any bundlers or anything. Unfortunately, mathjs is not 100% ready for ES modules: it supports ES modules itself, but not all of its dependencies (like `typed-function`) supports this yet. There is an issue open for this somewhere I think.

**Comment by PipGrylls** [comment]
I'm working on a workaround to get this working in the dev server. It's not there just yet but as it stands adding the following moves the problem along.
in package.json:
`"(dev)dependencies": {
...
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^11.2.1",
    "@web/dev-server": "^0.1.17",
    "@web/dev-server-esbuild": "^0.2.12",
    "@web/dev-server-rollup": "^0.3.4",
    "crypto": "npm:crypto-js",
...
`
in web-dev-server.config.mjs (similar will need to be added to rollup for build):
`  plugins: [
    ...
    rollupAdapter(commonjs()),
    rollupAdapter(nodeResolve())
    ...
  ],`

I've added all this to the test GitHub: 
https://github.com/PipGrylls/math-js-test
https://github.com/PipGrylls/math-js-test/blob/main/package.json
https://github.com/PipGrylls/math-js-test/blob/main/web-dev-server.config.mjs

There is still a bit more chasing to do before it works I will add/edit as I find solutions. Any help or comments welcome.

**Comment by josdejong** [comment]
Maybe in your case you could simply load mathjs as as an old fashioned script? Like 

```html
<!DOCTYPE HTML>
<html>
<head>
  <script src="path/to/mathjs/lib/browser/math.js" type="text/javascript"></script>
</head>
<body>
  <script>
    console.log(math.sqrt(-4).toString()) // 2i
  </script>
</body>
</html>

```

**Comment by josdejong** [comment]
And typically, a Webpack setup would solve all of these kind of issues in the mixed world of ES6/CommonJs/UMD/etc.

**Comment by PipGrylls** [comment]
Mathjs is being used in several calculation scripts that were the backend to Polymer webapps 5+ years ago. I am moving it to modern web standards to hopefully make it viable for modern browsers and do some futureproofing. I think that means it will be difficult to load it as a script. 

I'm using Rollup which I think is less flexible than Webpack but it does fit the Lit/Open-WC 'ecosystem' better. I think rollup may be able to handle it but just not in the dev server which can only do single file transformations. 

 I am going to try and move the old backend to a separate module and pack that with a bundler then import the result as a dependency as there is little to do in terms of changing the mathematics there. 
 
 Thank you for your help.

**Comment by josdejong** [comment]
I understand. Rollup should also be able to solve this (with the commonjs plugin).

**Comment by PipGrylls** [comment]
Yeah, it's now all working with the Rollup (w. node resolve and common js). Fortunately, in this instance, the maths is easy enough to separate into a backend rollup then import as an ES5+ module into the Lit web apps.  

In the final build, I fully expect to be able to use Rollup to make the entire static site in one go. But for the dev server using Open-wc it's necessary to pre-bundle the backend.

If anyone hits this via a search then the TLDR is:
For an active dev environment using Lit/Open-wc bundle any packages using mathjs (or other non ES5+ compatible modules) using Rollup+CommonJS. I target a file which looks like:
export { someMaths, ...} from 'path/to/file/that/ueses/mathjs'
Serve the static bundle to the scripts running in the dev server to use where any exported names in the targeted file can be used in modern JS formatting. 

Thanks again for your help josdejong.

**Comment by josdejong** [comment]
Thanks for sharing your solution Philip, glad to hear you got it working. Refactoring a big application to ES modules can be a tough job...
