### ISSUE TITLE
Whats the best strategy to figure out which depencies to add?

### ISSUE THREAD

**Issue by natarius** [josdejong/mathjs#2229]
Hi there, I am trying to custom bundle mathjs to reduce bundle size

here is my code:

`
create({
    evaluateDependencies
  }, {
    number: "BigNumber",
    precision: 64
  });
`
  
  I am using these functions: .evaluate, .createUnit, .typeOf, .divide, .multiply, .number, .unit and .bignumber
  
  and these objects: BigNumber, Unit
  
  I have tried adding all these but its evaluate is not able to solve all my expression cases 
  
  I wish there was error messages telling me whats missing :(
  
  What's the best way to figure this out?
  
  I would try all dependencies by hand, but there is hundreds of them!

**Comment by josdejong** [comment]
For every function there is a ready made object containing all the dependencies it needs, ie. to import `add` and it's dependencies there is `addDependencies`, and for `divide` there is `divideDependencies`, etc. You can pass those to `create`, like you already do with `evaluateDependencies`:

```js
const { fraction, add, divide, format } = create({
  evaluateDependencies,
  divideDependencies,
  multiplyDependencies,
  // ...
}, { number: "BigNumber", precision: 64 })
```

See docs: https://mathjs.org/docs/custom_bundling.html#using-just-a-few-functions 
Example: https://mathjs.org/examples/advanced/custom_loading.js.html
