### ISSUE TITLE
Factorials for non-integers

### ISSUE THREAD

**Issue by Murplyx** [josdejong/mathjs#226]
It would be nice to be able to calculate expressions like: "2.3!", factorials with non-integers, it could be implemented like this: http://jsfiddle.net/qqfLatgz/, but using BigNumbers.

**Comment by josdejong** [comment]
I think we can close this issue now, mathjs support non-integer values since @BigFav implemented the gamma function in [v1.2.0](http://mathjs.org/history.html#20141225-version-120)
