### ISSUE TITLE
 it is possible to create a function with callback parameters  with math.import

### ISSUE THREAD

**Issue by archimagogabo** [josdejong/mathjs#2263]
Hi, I'm not sure if this type of question on this channel is okay. sorry if it is not suitable. I am trying to create a callback parameter when creating a custom function with math.import do you have any idea how to do this or something similar

**Comment by josdejong** [comment]
Sure:

```js
math.import({
  myFunction: (callback) => {
    return callback()
  }
})

math.myFunction(() => 42) 
// returns 42
```
