### ISSUE TITLE
Not support ES import

### ISSUE THREAD

**Issue by whatisor** [josdejong/mathjs#2268]
I cannot import * as math from math.js
it only works with requirejs or static link in html.

**Comment by m93a** [comment]
Hey Huong,
could you provide more information about how you set your projet up? I tried creating a new math.js project and `import *` worked fine. This is how I did it:
1. create a new folder
2. run `npm init`
3. run `npm install mathjs`
4. create a file called `index.mjs` containing:
```javascript
import * as math from 'mathjs'
console.log(math.add(2,3))
```
5. run `node index.mjs`
6. it correctly logs `5`

**Comment by whatisor** [comment]
Hi @m93a 
I use  static resource with pure html and ES module javascript.( Not a nodejs code)

"math.js:27 Uncaught TypeError: Cannot set property 'math' of undefined
    at math.js:27
    at math.js:27"




`<!DOCTYPE html>
<html>
<body>

<h1>My First Heading</h1>
<p>My first paragraph.</p>
<script type="module">
    
import * as math from './math.js'
console.log(math.add(2,3))
</script>
</body>
</html>`

**Comment by josdejong** [comment]
> Anh I realized that math.js only works with RequireJS ( require....)

yes indeed. Mathjs itself is build as ES modules, but some of it's dependencies are not yet.
