### ISSUE TITLE
diff function for finding local extrema

### ISSUE THREAD

**Issue by balint42** [josdejong/mathjs#227]
I went through your lib looking for [this](https://github.com/balint42/diff.js). Since I could not find it I implemented it myself - any interest including it to your lib?

I'm going to add two versions, the current one taking [values] and another one operating on an [x] and an [y] vector.

edit: done

**Comment by milahu** [comment]
its been a while : D i pushed some commits to https://github.com/milahu/diff.js

now `function extremaXY` also detects plateaus at the start and end of  the array

todo: detect rise-plateau-rise and fall-plateau-fall (delta y is near zero for multiple points in a row)

my use case: from [a scatterplot](https://milahu.github.io/ncs-analyzer/), generate interpolations for x &rarr; y and for y &rarr; x
for the inverse function y &rarr; x, i must know the local extrema and plateaus

**Comment by josdejong** [comment]
Thanks for your inputs @milahu . Any idea on how we could integrate this nicely in mathjs? "Just" import these as new functions?

**Comment by milahu** [comment]
i suggest adding a new category for "numerical analysis" or "finite element algebra" ...
im not a native speaker (and not a mathematician), maybe you know a better name

maybe "array analysis"? (more intuitive for programmers)
these functions always operate on arrays of data points

for the local extrema function, i would prefer a longish name like `math.arrayLocalExtrema(data, options)`
only `arrayExtrema` could be misleading, cos extrema can also mean the global extrema,
what the `d3-array` library calls [extent](https://github.com/d3/d3-array#extent)

i only worked a bit on `arrayLocalExtrema` cos thats the only function i need
so `arrayDifferentiate` and `arrayIntegrate` will need some work
like simplify the API, support custom data formats, add tests, add comments, rename variables

**Comment by josdejong** [comment]
Makes sense to create a new category for this. Preferably a short name. How about "numerical"?

So this new category would basically contain numerical functions like `diff` (have to find an other name, `diff` already exists), `integral`, and `extrema`, right? That would be a great addition!
