### ISSUE TITLE
Quick way to get positions / values of sparse matrix?

### ISSUE THREAD

**Issue by slutske22** [josdejong/mathjs#2274]
Let's say I have a large, sparse matrix of zeros.  As my program runs, it changes values througout the matrix, though I may not know which values are changed until after its done.  Is there a quick way to get the positions of all values that meet a criteria?

For example, I make a sparse matrix, and assign random values to random places:

```js
const zeros = math.zeros([50, 30], "sparse");

for (let i = 0; i < 100; i++) {
  const position = [getRandomInt(0, 50), getRandomInt(0, 30)];
  const value = getRandomInt(1, 9);
  zeros.set(position, value);
}
```

Where `getRandomInt` returns a random integer in the range given.  [Here is a sandbox to play with that runs the above code](https://codesandbox.io/s/mathjs-get-sparse-values-fci30). Is there a way to quickly get the positions and values that were set?  Or even get the positions of all values that equal a certain number (say, 5)?

When I examine the matrix object in the console, I see the `._values` property, which has the values, and I also see a `._index`, which has the same length as `._values`, and `._ptr`:

<img width="624" alt="Screen Shot 2021-07-05 at 12 25 42 PM" src="https://user-images.githubusercontent.com/52637023/124511949-215f8480-dd8c-11eb-96ec-53cafd8b6c72.png">

I'm not sure how these values are used exactly to keep track of values in the matrix, and I can't find any documentation on it.  I feel like this must be trivial, but I'm missing something.  How can I say, "get me all the x, y positions of all values that satisfy a requirement (i.e. `!== 0`, `=== 5`, `> 2`, etc)"?

**Comment by m93a** [comment]
Hey Seth!
The easiest way to access all the non-zero entries of a sparse matrix is by using its iterator:
```typescript
const M = math.zeros([50, 30], 'sparse');

for (let i = 0; i < 100; i++) {
  const position = [rand(0, 50), rand(0, 30)];
  const value = rand(1, 9);
  M.set(position, value);
}

for (const { index, value } of M) {
  if (value > 2) {
    doSomething(index) // here's your index
  }
}
```
Alternatively, you can use [`M.forEach`](https://mathjs.org/docs/reference/classes/sparsematrix.html#SparseMatrix+forEach) wich works in a similar way (with slight differences – eg. you can't terminate it halfway through).

If you wanted to use the `{ _ptr, _index, _value }` properties directly, you can check out [the implementation of the iterator](https://github.com/josdejong/mathjs/blob/develop/src/type/matrix/SparseMatrix.js#L990). There you can see what each property does: `_value` holds all non-zero values, `_index` tells you the row of each value and `_ptr` has “indices of indices” – it points you to the first index of each row.

I know that the documentation for sparse matrices is quite underwhelming right now, [it's on our compass](https://github.com/josdejong/mathjs/issues/1769) :)

**Comment by slutske22** [comment]
This is not working.  When trying to use a `for of` loop, I get the following error:

```js
for (const value of zeros) {
  console.log(value);
}
```

`Invalid attempt to iterate non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method`

Am I missing something obvious here?  I tried a `for in` loop as well, but that just gives me the object properties & methods of the matrix (subset, get, set, resize, reshape, clone, size, etc).

Using a `forEach` doesn't error, but it has 2 problems - (1) is doesn't give me access to the index (xy position), just the value, and (2), it iterates through all items of the matrix, not just the nonzero ones.  That's sort of besides the point of using the sparse matrix.  I need to know how to access only those values which are not 0, otherwise for a 200 x 200 matrix of zeros, with a few values set, I'll be looping over 40,000 times just to find a few values' indices.

[Here is a codesandbox](https://codesandbox.io/s/mathjs-get-sparse-values-fci30) with both of these. 

I'm not sure why I'm getting this error, the source code you referenced seems to be wxactly what I need - "Iterate over the matrix elements, skipping zeros".  Am I doing something wrong?
