### ISSUE TITLE
 it is possible to make the comparer resolve number == "string"

### ISSUE THREAD

**Issue by archimagogabo** [josdejong/mathjs#2285]
hi, the case is: 
```
parser.evaluate (' a = 1 ')
parser.evaluate (' a == "string" ')
```

> Error: Cannot convert "string" to a number

Please can you tell me how I can make the comparison operator "==" allow comparing    ` number == "string" `
Thank

**Comment by josdejong** [comment]
mathjs tries to parse a string into a number and compare numerically. That works find if you do for example `2 == "2"`, but not when the string contains a non-numerical value. If you want to compare strings, you can do `string(number) == "string"`, or explictly use the function `equalText`.

**Comment by archimagogabo** [comment]
thanks for the prompt reply Josh. I love your library

**Comment by josdejong** [comment]
Thank you :) 

I'll close this issue now.
