### ISSUE TITLE
Conversion with Mu letter μ - e.g. 2 000 μg in mg (micrometer)

### ISSUE THREAD

**Issue by q2apro** [josdejong/mathjs#2288]
I am using MathJS for conversion which works amazingly good.

However, something like `2 000 μg in mg` is not interpreted. 

> Uncaught Error: Undefined symbol μg

How to input the `μ` as text with MathJS? Or do I have to define it customly?

**Comment by archimagogabo** [comment]
It seems to me that for this case the best option is to use "User-Defined Units"

https://mathjs.org/docs/datatypes/units.html

**Comment by q2apro** [comment]
Actually it is not a unit but a prefix. Shouldn't it be included by default? :)

https://en.wikipedia.org/wiki/Micro-#:~:text=Micro%20(Greek%20letter%20%CE%BC%20or,Greek%20letter%20%CE%BC%20(mu).

**Comment by q2apro** [comment]
Besides I tried:

```
	// Micro mu letter
	// math.createUnit('μm', '0.000001 m');
	math.createUnit( {
		mumeter: {
			definition: '0.000001 m', 
			prefixes: 'none',
			baseName: 'μm'
		},
	  },
	  {
		override: false
	});
```

Both yield:

> Uncaught Error: Undefined symbol μm

**Comment by q2apro** [comment]
Ah, I see that Math.js has the prefix! 🥳 

> micro	u	1e-6

https://mathjs.org/docs/datatypes/units.html#reference

So it's written with a `u` (!)
