### ISSUE TITLE
Loading math.js succefully using requirejs, but math object is not accessible

### ISSUE THREAD

**Issue by llagerlof** [josdejong/mathjs#2292]
I am using requirejs to load `math.js` and it loads, but "math" object is not created globally.

```
    requirejs(["js/vendor/math"], function (math) {
        console.log('math.js loaded successfully. But I CAN'T use the "math" object');
    });
```

The "math" object doesn't exist after `math.js` is succefully loaded.

I can load other libs and use its objects normally. Do I need to do something special to make math.js work with requirejs?

Just a note, if I load `math.js` using the <script> tag, it works. I have access to "math" object everywhere.

**Comment by josdejong** [comment]
requirejs is not officially supported (I think [it reached end of life](https://github.com/requirejs/requirejs/issues/1816)?) but the UMD bundle in the package `lib/browser/math.js` can be loaded using requirejs, nothing special required:

```js
requirejs(['path/to/your/mathjs/bundle'], function (math) {
  console.log(math.evaluate('2 + 3')) // 5
  console.log(math.sqrt(-4).toString()) // '2i'
})
```

**Comment by llagerlof** [comment]
Your insight gave me an idea. I found out that the problem was not the original math.js nor requirejs (I think).

I found a solution (not the ideal, though):
```js
requirejs(["js/vendor/math", "js/vendor/jquery"], function (math, $) {
  window.math = math;
});
```

I don't know why the `$` (jquery) object was automatically globally exposed, but not the `math` object. But when I manually exposed the `math` object, it can be used anywhere.

Thank you.

**Comment by josdejong** [comment]
yes, that is how it works, and this works as intended. When loading a dependency with requirejs (or commonjs or ES modules), nothing should be exposed globally (via `window`). The dependency is passed via the function argument already so you have a reference to it. There are cases where exposing libraries or stuff globally is needed, but generally it's an anti-pattern and better to keep dependencies, variables, and everything local (prevent conflicts, race conditions in loading, etc).
