### ISSUE TITLE
fromJSON - rebuild sparse matrix from results of toJSON

### ISSUE THREAD

**Issue by slutske22** [josdejong/mathjs#2293]
Perhaps this is just a lack of understanding, but here's what I'm trying to do.  I create a matrix in a NodeJS application.  After some manipulation, it needs to be sent to the front end, and manipulated further.

To send it, it needs to be serialized, which can be done with the `toJSON` method.  The results of a `toJSON` method look something like this:

<img width="704" alt="Screen Shot 2021-07-30 at 11 31 35 AM" src="https://user-images.githubusercontent.com/52637023/127696766-de40bc52-af1f-4864-9c10-fb5077b4c5af.png">

How can I transform this back into a sparse matrix on the front end, with all the utility of the class methods (`.set`, `.get`, `Symbol[Iterator]`, etc)?  Is there a simple way to do that?  Surely I must be missing something.  Thank you!

**Comment by josdejong** [comment]
You can stringify and parse like: 

```js
const myMatrix = math.sparse([[1, 2], [3, 4]]) // SparseMatrix
const myStringifiedMatrix = JSON.stringify(myMatrix) // string

// ...do something: persist, or transfer, or something else

const myRevivedMatrix = JSON.parse(myStringifiedMatrix, math.reviver) // SparseMatrix
```

You'll need a mathjs instance in the frontend too, then you can use `JSON.parse(..., math.reviver)`. If you know you're dealing with a SparseMatrix you could also directly call `SparseMatrix.fromJSON(myStringifiedMatrix)`.

See docs: https://mathjs.org/docs/core/serialization.html

**Comment by slutske22** [comment]
`SparseMatrix.fromJSON(myStringifiedMatrix)` is exactly what I was looking for!  

I realize [it is indeed in the docs](https://mathjs.org/docs/reference/classes/sparsematrix.html#sparsematrixfromjsonjson--codesparsematrixsparsematrixcode), but I think my biggest issue is the way the docs are organized -there's a wealth of information in the reference section, but you sort of have to dig to realize its there.  Perhaps a dedicated docs website, with a left-hand nested menu, where its *very obvious* what classes are available, and all the methods on a class, would be helpful.  Anyway, I'm just nitpicking, thank you for your answer and this library!

**Comment by josdejong** [comment]
👍 

> I realize [it is indeed in the docs](https://mathjs.org/docs/reference/classes/sparsematrix.html#sparsematrixfromjsonjson--codesparsematrixsparsematrixcode), but I think my biggest issue is the way the docs are organized -there's a wealth of information in the reference section, but you sort of have to dig to realize its there. Perhaps a dedicated docs website, with a left-hand nested menu, where its _very obvious_ what classes are available, and all the methods on a class, would be helpful. Anyway, I'm just nitpicking, thank you for your answer and this library!

Yeah, agree, thanks for your suggestions. Related: #1769
