### ISSUE TITLE
Typescript: MathJS does not declare constructors for expression nodes

### ISSUE THREAD

**Issue by davidtranhq** [josdejong/mathjs#2294]
The `index.d.ts` file does not export `math.AccessorNode`, `math.OperatorNode`, `math.SymbolNode`, etc. I'm wondering if this is intentional since the [docs](https://mathjs.org/docs/expressions/expression_trees.html) state that all nodes should be available in the `math` namespace.

**Comment by m93a** [comment]
Hey David,
This is indeed a bug in the declaration files, thank you for reporting it!

PRs are welcome :)

**Comment by Madanaa** [comment]
@m93a needs to update the project for a long-term solution.

**Comment by m93a** [comment]
Hey Madan,
I'm not sure I understand you. Are you talking about implementing types for the nodes, or are you talking about some repository-wide TypeScript solution? If the former, feel free to open a PR. If the latter, please open a new issue with the proposal you have on your mind, we'll discuss it there.

**Comment by m93a** [comment]
This will be fixed by #2290.

**Comment by Madanaa** [comment]
> Hey Madan,
> I'm not sure I understand your comment properly. Are you talking about implementing types for the nodes, or are you talking about some repository-wide TypeScript solution? If the former, feel free to open a PR! If the latter, please open a new issue with the proposal you have on your mind, we'll discuss it there.

@m93a okay thank you for informing me

**Comment by gwhitney** [comment]
As #2290 has been merged, I believe this is completed. Closing.
