### ISSUE TITLE
Is it possible to extend MathNode?

### ISSUE THREAD

**Issue by andrew-belyi** [josdejong/mathjs#2296]
Hello! 
I'm wondering is it possible to extend `MathNode`, to add own method into it, like `.toXML()`. I'm curious to create similar behaviour like in existing `.toHTML()` and `.toTex()` methods. 
Can tou give me some advice, please?

**Comment by josdejong** [comment]
Yes these nodes are regular JavaScript classes/prototypes, you can add new methods if you like

i.e.:

```js
math.Node.prototype.hello = () => 'hello world'
math.parse('2+3').hello() // 'hello world'
```

All available Node classes are documented here: https://mathjs.org/docs/expressions/expression_trees.html#nodes

**Comment by andrew-belyi** [comment]
Thank you!

**Comment by josdejong** [comment]
You're welcome
