### ISSUE TITLE
Unit.format() and Unit.formatUnits() give inconsistent units

### ISSUE THREAD

**Issue by chrisrishel** [josdejong/mathjs#2299]
Apologies if this has already been raised elsewhere or is intentional behavior. I'm running into an issue where format() is appropriately simplifying units, where formatUnits does not. For example:

```
a = math.unit( '10 mg/mL' );
b = math.unit( '100 mL' );
```

`math.multiply(a, b).format()` produces `1000 mg`, which is what I would expect. However `math.multiply(a, b).formatUnits()` produces `(mg mL) / mL` (I would expect just `mg`).

A hack that does produce the intended units is to just create a new unit from the appropriately-formatted multiplication result (i.e. `math.unit(math.multiply(a, b).format()).formatUnits()`). However, this is pretty clunky and inefficient.

Is this a bug or intended behavior? If the latter, is there a better way to get the simplified units? Thanks!

**Comment by m93a** [comment]
Hey Chris,
This definitely does look like a bug to me. Thanks for reporting it!

**Comment by josdejong** [comment]
The function `formatUnits` notes that the function does not first simplify the units:

> [...] The unit list is formatted as-is without first being simplified.

https://github.com/josdejong/mathjs/blob/efe367cad58f35ad9dabe69c0fd31c0093fa63ff/src/type/unit/Unit.js#L1030-L1035

If you call `.simplify()` first, the units will be simplified and give the output you expect:

```js
a = math.unit( '10 mg/mL' );
b = math.unit( '100 mL' );

math.multiply(a, b).simplify().formatUnits() // "mg"
```

**Comment by m93a** [comment]
Aight, thanks for the clarification, Jos! :)
