### ISSUE TITLE
A question about 'math.bignumber()'

### ISSUE THREAD

**Issue by psyche520** [josdejong/mathjs#2309]
When I use `math.bignumber()`,I find that some special numbers have problems in conversion.
Such as:
```
math.bignumber('6006006.006006006006006')  -> d: (4) [6006006, 60060, 600600, 6000000]
result: a {s: 1, e: 6, d: Array(4), constructor: ƒ}
```
The type in this array is a number, and the 0 in front of the number disappears by default
I guess the normal result may be `d: (4) [6006006, 0060060, 0600600, 6000000]`
Is this a bug?

**Comment by josdejong** [comment]
It's a class instance of `Decimal`. You can call `.toString()` on the result to get a human readable output, or use `math.format(...)`

**Comment by m93a** [comment]
Closing this, but feel free to reopen if needed :+1:
