### ISSUE TITLE
Inconsistencies in results from exponent operator and pow() ...?

### ISSUE THREAD

**Issue by joshstrike** [josdejong/mathjs#2311]
Hi, thanks for the great library!

I'm rewriting some older code that used math.js 3.17.0. I upgraded to the newest version, but now I'm running into inconsistencies that I don't understand between the `^` operator and pow(). They behave differently but I'm not sure what the expected behavior is.

In a straightforward context, the `^` operator only returns the <s>real</s> imaginary part of the number (negative):
`math.evaluate("(-2 ^ .5)") // -1.4142135623730951`

pow() returns the complex number:
`math.evaluate("pow(-2,.5)") // {re: 8.659560562354932e-17, im: 1.414213562373095}`

Okay. However, if I'm expecting only the imaginary number portion when using the `^` operator, then things get a bit wonky when you nest it, as now it returns a complex number:
`math.evaluate("(-2 ^ .5) ^ .5") // {re: 7.281793434556703e-17, im: 1.189207115002721}`

Additionally, this seems to be the wrong result since it is equivalent to the square root of the (negative) imaginary portion of the number, like so:
`math.evaluate("pow(-1.4142135623730951, .5)") // {re: 7.281793434556703e-17, im: 1.189207115002721}`

Whereas getting the sqrt of that negative imaginary number again with the `^` operator just yields another negative number:
`math.evaluate("-1.4142135623730951 ^ .5") // -1.189207115002721`

But it is not equivalent to the square root of the complex number that (should?) have come from the `(-2 ^ .5)`:
`math.evaluate("pow(pow(-2,.5),.5)") // {re: 0.8408964152537146, im: 0.8408964152537144}`

It looks like the first stage of `^` is always returning the negative imaginary portion but subsequent nested stages do not - for some reason. Could this be a bug with the way `^` is parsed for output as opposed to how its results are used for the next stage of calculation?

**Comment by josdejong** [comment]
The `^` operator uses `pow` under the hood. The issue here is precedence of operators: `^` has higher precedence than `-`, 
so `-2 ^ .5` is evaluated as `-(2 ^ .5)`. If you do `(-2) ^ .5` you'll get the same result as `pow(-2, .5)`.

**Comment by joshstrike** [comment]
Ahhh! Thank you! This should have been obvious but it completely eluded me.
