### ISSUE TITLE
Search for substring

### ISSUE THREAD

**Issue by Peterkmoss** [josdejong/mathjs#2316]
Hi,

I'm writing a parser that's taking in excel cells and outputting a mathjs formula to calculate the same thing.

Right now I'm in a struggle where I need to be able to look for a substring within a variable - say I want to look for "test" inside "testString". I'm basically wanting the behaviour of the excel function SEARCH, I've tried using `subset` but I can't get it to work since the index needs to be a range / ranges.

Any ideas on how I would go about doing this with mathjs?

Thanks in advance!

**Comment by josdejong** [comment]
There is no search function implemented right now, so I guess you could implement your own and import it in mathjs?

**Comment by Peterkmoss** [comment]
How would I import a custom function in mathjs? I've looked a bit around, but can't seem to find anything.

**Comment by josdejong** [comment]
👍  shall we close this issue?
