### ISSUE TITLE
Documentation of `subset` is misleading

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#2325]
In the documentation for the [`subset`](https://mathjs.org/docs/reference/functions/subset.html) function, it says that:

> Parameter `index` — An index containing ranges for each dimension

That is quite misleading, because the function expects a list of indices, not a range. Compare:
```javascript
import { subset, index, range } from 'mathjs'
const M = [[1],[2],[3]]

subset(M, index([0,2],0)) // → [[1],[3]]
subset(M, index([0,1,2],0)) // → [[1],[2],[3]]
subset(M, index(range(0,2),0)) // → [[1],[2],[3]]
```

**Comment by Claeb101** [comment]
@m93a Can I work on this issue as my first contribution to this repository?

**Comment by josdejong** [comment]
Thanks for your offer @Claeb101 , would be great if you could improve the docs 👍

**Comment by josdejong** [comment]
Docs are improved in `v10.3.0`
