### ISSUE TITLE
.d.ts for mathjs/number

### ISSUE THREAD

**Issue by riceyeh** [josdejong/mathjs#2331]
There is @types/mathjs for import from ‘mathjs’. However, when import from ‘mathjs/number’, @types/mathjs is not associated with in vscode IDE. How is this solved?

**Comment by m93a** [comment]
Hey Rice,
this looks like a duplicate of #2284. Currently, we don't have type definitions for `mathjs/number` (and we're looking for a PR). Also, `@types/mathjs` should be deprecated, since `mathjs` ships its own types.
