### ISSUE TITLE
QUESTION: Antlr4 grammar

### ISSUE THREAD

**Issue by Melozzola** [josdejong/mathjs#2352]
Is there an antlr4 grammar? If not, I think it would be a great addition to the library to provide the antlr4 grammar.

**Comment by josdejong** [comment]
Thanks for your suggestion @Melozzola . I'm not familiar with antlr4. What is exactly the use case you're thinking of?

**Comment by Melozzola** [comment]
Hi @josdejong, sorry for the late reply. [Antlr4](https://www.antlr.org/) is a tool that allows you to define a grammar (for example the grammar for your calculation language) and then automatically generate tokenisers and parsers.

There are 2 advantages that I can think of. One that is probably more interesting to you and one to me.
1.  Once you defined the grammar it becomes much easier to evolve the language by adding new functions, expressions etc. All you have to do is update the grammar file and regenerate the tokenisers and parser. 
2. Given that antlr supports different languages you can generate parsers for java for example. And the mathjs expressions can be parsed and validated in a java backend.

Hope my brief explanation is clear enough.

**Comment by m93a** [comment]
Math.js currently uses its own parser (see [`parse.js`](https://github.com/josdejong/mathjs/blob/develop/src/expression/parse.js)), which comes with a set of its own advantages – largest one of them is the ability to throw custom errors. Rewriting the current parser using some parser generator would indeed be possible, but it would be a major undertaking and it isn't clear if the result could do everything the current parser can afaik.

**Comment by josdejong** [comment]
Thanks for your clarification @Melozzola. I agree with @m93a: at this moment I do not really see a case to rewrite the parser, it would be a lot of work and I expect it not to be straightforward. However if at some point there is a need to rewrite the parser, it would be an interesting idea to see if we can use a parser generator like Antlr4.
