### ISSUE TITLE
Methods and fields for Unit are missing from Typescript interface

### ISSUE THREAD

**Issue by lorenz-h** [josdejong/mathjs#2353]
Hi Everyone!
I would like to use Unit.simplify() and Unit.units in my Typescript code but they are not present in the typescript interface. Is there any reason for this? The use case is figuring out if a unit is relative (e.g. kWh/kg, km/s) or absolute (e.g. m*s, kg). 

If this is not intentional I would be happy to create a PR and add them to https://github.com/josdejong/mathjs/blob/4ce71856afbcf1a0aaad30b70afc99c7606173c0/types/index.d.ts#L3124

**Comment by josdejong** [comment]
This is not intentional but simply still missing. Help improving the TypeScript definitions is very welcome, thanks for your offer!

**Comment by josdejong** [comment]
This is addressed now in `v10.2.0`
