### ISSUE TITLE
Subtract not working as expected, floating number problems

### ISSUE THREAD

**Issue by dekadentno** [josdejong/mathjs#2355]
As the title said, I stumbeled upon a issue with subtract and I am curious if I'm using it as expected. 
Problem reproduction:
 `
subtract(5.01,6) / -0.99 OK
subtract(2.01,2) // 0.0099999999999998 NOT OK
`

The only way to avoid this is to use the round function, but I'm not sure if that's the correct was nor should there even be a workaround ot hould this work out of the box.

**Comment by josdejong** [comment]
This is the most asked question. You can search the docs and issues section for "round off errors" to understand what it is and how to solve it.

https://github.com/josdejong/mathjs/issues?q=is%3Aissue+round+off+error+is%3Aclosed+
https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by dekadentno** [comment]
Every answer is poiting out that the precision has to be set to 14 or lower, which is not helping.

**Comment by josdejong** [comment]
Please read the section "Round-off errors" in the docs carefully, you missed an important option I think 😄 

https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
