### ISSUE TITLE
Binary tree to n-ary tree

### ISSUE THREAD

**Issue by agarwalBinay18** [josdejong/mathjs#2369]
I want to convert the binary tree to an n-ary expression tree having only a single level using math.parse. How can I achieve this?

**Comment by josdejong** [comment]
Thanks for your input. Can you elaborate a bit, and show an example of what you mean?

**Comment by gwhitney** [comment]
It seems quite possible to me that what @agarwalBinay18 may have been looking for is simplify.utils.flatten, which is not currently exported (and probably needs a bit more robustness to be made public).

**Comment by josdejong** [comment]
Yeah could be. I'll close this issue now due to lack of response. Please reopen when needed.

For reference: the discussion on `simplify.utils.flatten` can be found in #2282
