### ISSUE TITLE
Documentation for print

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#2379]
Hi, I was looking into the function print() and saw that using `help(print)` returns `Error: No documentation found on "print"`

It seems to be because of this line:
https://github.com/josdejong/mathjs/blob/d7a5693e91ddb4d53543f58955fa60bdd94d523c/src/expression/embeddedDocs/embeddedDocs.js#L548

At the moment it seems the parser already supports objects, thus the documentation for print might work now.

I tried using the function print as the [documentation states](src/expression/embeddedDocs/function/utils/print.js) and it works fine:

```javascript
print("Lucy is $age years old", {age: 5}) // "Lucy is 5 years old"
print("The value of pi is $pi", {pi: pi}, 3) // "The value of pi is 3.14"
print("Hello, $user.name!", {user: {name: "John"}}) // "Hello, John!"
print("Values: $0, $1, $2", [6, 9, 4]) // "Values: 6, 9, 4"
```

**Comment by josdejong** [comment]
Ahh, you're right, it just works nowadays 😁 . Fixed via e3b7324.
