### ISSUE TITLE
forEach default example shows SyntaxError on the parser

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#2380]
When typing `help(forEach)` on the parser

The example shows a syntax error.
```
Name: forEach

Category: Matrix

Description:
    Iterates over all elements of a matrix/array, and executes the given callback function.

Syntax:
    forEach(x, callback)

Examples:
    forEach([1, 2, 3], function(val) { console.log(val) })
        SyntaxError: Parenthesis ) expected (char 34)

See also: map, sort, filter
```

When trying that example on https://mathjs.org/ : `forEach([1, 2, 3], function(val) { console.log(val) })` it returns the same syntax error:
`SyntaxError: Parenthesis ) expected (char 34)`

When looking at the source file the expected result seems to be different.
https://github.com/josdejong/mathjs/blob/47a493d70ac92daa47b26f9eea88513a7efa4408/src/function/matrix/forEach.js#L21

I tried outside the parser and it works fine

**Comment by josdejong** [comment]
Thanks for reporting. I see the example is a bad copy-paste from the JavaScript syntax. 

I was thinking but I can't come up with a good example of `forEach` inside the expression parser, it's mostly useful in plain JavaScript right now. The syntax of the expression parser is too limited to make it useful to do stuff inside the callback of the `forEach` function.

Do you have an idea for a useful example? If not I will just clear the example, that's at least better than an error.

**Comment by josdejong** [comment]
Yes indeed, with an external function that does do "something" it makes sense. We cannot do that in this example though. I'll make the examples empty for now.

**Comment by josdejong** [comment]
Ok fixed via https://github.com/josdejong/mathjs/commit/a4d5993594758758536eb497e88538e1c6b12617

**Comment by dvd101x** [comment]
I've found some of usefull example for the function forEach that works directly on the parser

# Fibonacci

```python
N = 16;
n = 3:N;
F = concat([1,1],zeros(N-2));
fib(n) = F[n] = F[n-1]+F[n-2];
forEach(n, fib);
F
```
Yields: `[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987]`

It seems to do the trick.

# Euler

A longer example is the euler method simiar to https://mathjs.org/examples/browser/rocket_trajectory_optimization.html running within the parser

Solve a y' = y equation with y(0) = 1 stepsize of 1 where t is between 0 and 4 as showon on [Euler Method](https://en.wikipedia.org/wiki/Euler_method#Using_step_size_equal_to_1_(h_=_1))

```python
#Input
u0 = 1;
h = 1;
f(t,y) = y;

# Setup;
t = 0:h:4;
N = size(t)[1]-1;
n = 1:N;
u = zeros(N+1);
u[1]=u0;

# Euler function
euler(n) = u[n+1] = u[n]+h*f(t[n],u[n]);

# Call the function
forEach(n,euler);
u
```
Yields: `[1, 2, 4, 8, 16]`

**Comment by josdejong** [comment]
That are some nice examples indeed, that's nifty. It feels a bit like an any pattern though, having the function like `fib` make changes in the variable `F`, but I guess it's nice to show. What do you think, shall we add this to the embedded docs of `forEach`?

**Comment by dvd101x** [comment]
Thank you for considering this!

I think it could be usefull to show that some assignemnts can be made inside the function, thus `forEach` can modify values and be usefull inside the expression parser.

Maybe it could be a simpler example like

```python
numberOfPets = {};
addPet(n) = numberOfPets[n] = (numberOfPets[n] ? numberOfPets[n]:0 ) + 1;
forEach(['Dog','Cat','Cat'], addPet)

numberOfPets       # {"Dog": 1, "Cat": 2}
```

I just found out that multiple assignemnts can be made on the same function so maybe the fibonacci example could be rewritten.

```python
# A single run for the fibonaccio function
f(n) = [F = a+b,
        a = b,
        b = F];
# Calculate the Nth number from the fibonacci sequence       
fib(n) = [a = 1,
          b = 1,
          forEach(1:n-2,f)];

fib(10);
F    #55
```

This could also mean that some more complex numerical methods could be programmed like Runge-Kutta as mentioned on #2302 

```python
u = [1];                                 # Initial value
h = 1;                                   # Step size
t = 0:h:4;                               # Time setup
f(t,y) = y;                              # forcing function

# Runge Kutta 4th order
rk4(n) = [k1     = f(t[n],u[n]),
          k2     = f(t[n]+h/2,u[n]+h*k1/2),
          k3     = f(t[n]+h/2,u[n]+h*k2/2),
          k4     = f(t[n]+h,  u[n]+h*k3),
          u[n+1] = u[n]+h/6*(k1+2 k2+ 2 k3+ k4)];

forEach(1:4,rk4);                      # Call the function
format(u,6)                            # [1, 2.70833, 7.33507, 19.8658, 53.8032]
```

This is not the way I'm used to program but it blows my mind how powerful the parser can be.

I don't know which example would be better to show on the help section, but it would certainly be nice to know that the `forEach` function can also work inside the expression parser.

**Comment by josdejong** [comment]
> This is not the way I'm used to program but it blows my mind how powerful the parser can be.

😂 

Well, I still would like to extend the parser with support for loops like `for`, `while`, `do`, and multi-line function bodies. That will open up a lot of new options and allow you to create bigger scripts instead of one-line expressions 😄.

I do like your `numberOfPets` example quite a lot. It will not lead people into copy/pasting a questionable pattern like with Fibonacci, but it does show what `forEach` does. Can you create a small PR adding this `numberOfPets` example? That would be nice.

**Comment by dvd101x** [comment]
> Well, I still would like to extend the parser with support for loops like for, while, do, and multi-line function bodies. That will open up a lot of new options and allow you to create bigger scripts instead of one-line expressions 😄.

I'm very glad to hear that! As I was working on it I had some interesting results by putting more than one expression on one function by putting them in an array and then return only the last expression with [end] simulating a `return` let's say `f(x) = [a=x, a+x][end]`, it did work but had some odd issues with the scope that I didn't fully understand.

> I do like your numberOfPets example quite a lot. It will not lead people into copy/pasting a questionable pattern like with Fibonacci, but it does show what forEach does. Can you create a small PR adding this numberOfPets example? That would be nice.

I'm glad you like it, yes of course!, you can find it at #2507 

I used more than one expression and put them on each element of the array of examples, I don't know if they are evaluated on the same scope while showing the embedded docs. Maybe I should have put all the expressions on the same element of the array of examples and separate them by `\n` but I also don't know if they will format correctly.

So please let me know if there is something to fix on the PR

**Comment by josdejong** [comment]
Thanks, looks good 👍
