### ISSUE TITLE
[docs] Download page still mentions @types/mathjs whereas types are now shipped built-in

### ISSUE THREAD

**Issue by bobo96run** [josdejong/mathjs#2386]
Hi,

Thank you for this awesome library!

The current download page still mentions that one has to install the `@types/mathjs` package to get TypeScript definition for the library.
<img width="784" alt="Capture d’écran 2022-01-14 à 16 31 42" src="https://user-images.githubusercontent.com/79259815/149515993-8d7d5d12-9495-4a90-8d69-2a7d8822ea4b.png">

https://github.com/josdejong/mathjs/blob/98452e358c7cc40d7b934f4b7e7a241002c57e97/download.md?plain=1#L16

But mathjs now ships its own definitions (see https://github.com/josdejong/mathjs/issues/2187 and associated PR https://github.com/josdejong/mathjs/pull/2192)

Therefore it looks to me that this mention could be removed from docs, to avoid misleading developers?

**Comment by josdejong** [comment]
Good point, thanks for creating a fix 👍
