### ISSUE TITLE
Regression bug in simplify(): 2-(x+1)

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2393]
In mathjs 10.1.0, `2-(x+1)` does not simplify to `1-x`. Although this was not in the unit tests, I assume this is a regression caused by the recent changes to simplify(). Will file a fixing PR as soon as possible.

**Comment by gwhitney** [comment]
Note that `x-(y-y+x)` also regressed (no longer simplified to '0'), but this has now also been added to the tests and corrected in #2394.

**Comment by josdejong** [comment]
👍  Thanks
