### ISSUE TITLE
Inconsistent returning formats "across platforms" and Bug with Negative values

### ISSUE THREAD

**Issue by xMxster** [josdejong/mathjs#2397]
# Inconsistent output *across platforms*

<table>
<tr>
<th></th>
<th>Node.js</th>
<th>React-Native</th>
</tr>
<tr>
<td>code</td>
<td>
<pre>
<code>
const {fraction} = require('mathjs');
const f1 = fraction(-1, 3);
console.log(f1);
</code>
</pre>
</td>
<td>
<pre>
<code>
import React from 'react';
import {View} from 'react-native';
import {fraction} from 'mathjs';
const f1 = fraction(-1, 3);
console.log(f1);
</code>
</pre>
</td>
</tr>
<tr>
<td>output</td>
<td>{ s: -1, n: 1, d: 3 }<br/>
</td>
<td>{"d": 3, "mathjs": "Fraction", "n": -1}<br/>
</tr>
<tr>
<td>observation</td>
<td>
<li>Expected return as intended by you (I hope)</li>
<li><b>Sign of the numerator expressed with s</b></li>
</td>
<td>
<li>Returned in a different order (non important, mostly)</li>
<li>Missing <b>s</b> value</li>
<li><b>Sign of n included in itself (probably better)</b></li>
<li>Nonsense <b>"mathjs": "Fraction"</b> returned (maybe it's a bug?)</li>
</td>
</tr>
</table>

Maybe the way it works with *normal node* is the old way? and the *react-way* is the new intended mode?

I think it's better to include the sign in the same var as numerator because it allows the denominator to have a sign too (eg. -1/-3 = 1/3)

<br/>

# Strange object behaviour (react-native)

The sign of numerator on node can be know by using the **s** var, but it's not included when mathjs is being used with react-native.

<pre>
<code>
const f1 = fraction(-1, 3)
console.log(f1)
// output {"d": 3, "mathjs": "Fraction", "n": -1}
// n is negative number here, as expected

// returning a positive value when referencing n directly 
console.log(f1.n)
// output 1

// not even using {sign} can get the value as negative
console.log(sign(f1.n))
// output 1
</code>
</pre>

`sign()` does work with normal numbers like `-3`, `5`, etc, but not `fraction.n`

Retriving negative values from normal objects does work, so it's not javascript itself.

----

- I'd already uploaded this, but it wasn't as well explained, hopefully this time is better.
- Thank you for reading this, if any of you have doubts about what I meant in any part, please let me know, so I can fix it.
- I really wish you're not getting a notification for every time I edited this post and the past, or I'll feel even more sorry than I do now

**Comment by xMxster** [comment]
Sorry for the edits and closing and opening

First post (although done the best I thought) was confusing and added unnecessary stuff.

This one was better (although I had to sacrifice code formatting to embed the code into tables), i hope it helps

As per the closing, i thought the button meant "close the app"

I'm so sorry, I'm new to github basically

**Comment by josdejong** [comment]
As for your question on fractions: fraction internally normalizes values, and hence can change numerator, denominator, and move the sign from one to the other. Try for example `math.fraction(2, 4)`.

Please open a separate issue for separate questions in the future, not multiple questions in one issue.

**Comment by xMxster** [comment]
Okay, `math.fraction(-2, -4)` output is indeed `n:1, d:2` that's the equivalent.

I still have this problem, in react-native 

```javascript
import React from 'react';
import {View} from 'react-native';
import {fraction, sign} from 'mathjs';

const f1 = fraction(-1, 3);

console.log('object:', f1);
console.log('get n:', f1.n); // incorrectly returns n as positive

console.log('object:', f1.toJSON());
console.log('get n:', f1.toJSON().n); // correctly return n as negative

const App = () => {
    return <View></View>;
};
export default App;

// output: 
object: {"d": 3, "mathjs": "Fraction", "n": -1}
get n: 1
object: {"d": 3, "mathjs": "Fraction", "n": -1}
get n: -1

```

Objects seem to be exactly the same, yet, the first returns positive when referencing it...
It seems like an odd behavior, I'm not very good at javascript yet, but I don't think that's how it's intended to be.

Thanks for your suggestion about different issues!
Thank you for your time Jos, someday when I get better I wish to be a collaborator of this wonderful project.

**Comment by josdejong** [comment]
Have a look at the serialization logic of mathjs to serialize a Fraction as a JSON object: https://github.com/josdejong/mathjs/blob/develop/src/type/fraction/Fraction.js

In short:

- A Fraction class instance holds `s`, `n`, and `d`
- mathjs serializes a Fraction as JSON with just `n` and `d`, not and `s`. Reason for that is that the Fraction constructor `new Fraction(...)` supports an object with `n` and `d`, but not with `s`, so this serialization allows for very straight forward deserialization ([see docs](https://github.com/infusion/Fraction.js/#arrays--objects)).

**Comment by xMxster** [comment]
Thank you!

I still don't understand lots of things (mainly why reacts calls it in a different way)

But all my doubts are mainly solved!
