### ISSUE TITLE
Missing attributes in ConfigOptions type?

### ISSUE THREAD

**Issue by TheBB** [josdejong/mathjs#2401]
The type for *ConfigOptions* appears to be missing *predictable*. I assume that's an oversight?

https://github.com/josdejong/mathjs/blob/3c54623662b5524261b258b426f1e447457d5c64/types/index.d.ts#L3410-L3417

**Comment by josdejong** [comment]
Thanks for reporting, that is a bug. `parenthesis` should be `predictable`, see docs: https://mathjs.org/docs/core/configuration.html

**Comment by josdejong** [comment]
Fixed via ce67989. (not yet published)

**Comment by TheBB** [comment]
Thanks for the quick response!
