### ISSUE TITLE
Browser extension

### ISSUE THREAD

**Issue by Nekomajin42** [josdejong/mathjs#241]
Hey! I'd like to request a feature for mathnotepad. I am not sure if this is the right place, but I did not find any mathnotepad repo. So, I love that site, but it would be awesome to use it with one click in my browser. A toolbar button with a dropdown bubble. It requires only a few lines and minimal work with the Chrome extension APIs (and it work in Opera too). But I don't know how much work does it requires in Firefox.

Thanks for reading!

**Comment by AdansBatista** [comment]
Hi there, any chance that you are releasing a API for mathnotepad, that we can use? It's really amazing work, and it will help a lot one of my apps.

**Comment by josdejong** [comment]
@AdansBatista what sort of API do you mean?

**Comment by AdansBatista** [comment]
Hey @josdejong, I meant an ui api kind of thing. Something that can init by a textarea tag on html, and use yours css and js embedded, that returns some objects to use on script side. I started coding now with mathjs that are amazing, the tree nodes are great, very good implementation. I'm trying to produce something similar with mathnotepad on my ui!!! Cheers for your work!!!

**Comment by josdejong** [comment]
Thanks, glad you like it :). At least for the time being, Math Notepad is not open source. It's a cool idea to turn it into a UI library. It won't happen any time soon seen my time constraints though.
