### ISSUE TITLE
Edge case: `diff([1])`

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2412]
Currently, `math.evaluate('diff([1])')` returns `[1]`. It seems to me that to be consistent with `diff()` called on any array of length > 1 (where it returns an array of length one less than the input), the value of `diff([x])` ought to be `[]` no matter what x is. In other words , there are _no_ consecutive differences of a list of length 1. (`diff([])` would continue to produce `[]` as it currently does; there are also no consecutive differences of a list of length 0.)

If there's agreement that the current behavior is anomalous and should be corrected, I will be happy to supply the small PR needed to fix.

Incidentally, it seems to me that issue #1634 asking for diff in the first place can be closed.

**Comment by josdejong** [comment]
You're right, I would expect `diff([1])` to return `[]`, this is a bug, though I see from the unit tests that this behavior was implemented like this intentionally (see https://github.com/josdejong/mathjs/commit/1348d67b7eb737708efd77809c01ee40bd8af44b). 

I've put together a fix in #2422

Does this make sense @Veeloxfire ?
