### ISSUE TITLE
simplify does not operate (much) on expressions in prefix function-call form

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2415]
Currently, `simplify("add(4, 2x, 3x)")` returns `add(add(4, 2x), 3x)`, whereas `simplify("4 + 2x + 3x")` returns `5*x + 4`, even though the two initial expressions are semantically identical (well, except possibly for association, but clearly simplify is already using the associative property to make them completely equivalent).

It seems to me that it would be good if simplify worked equally well regardless of whether an expression happened to be specified in infix or (prefix) function-call form (or even a mix). As usual, I am happy to work on this, but there are design questions: How to approach making the functionality work either way? Some thoughts, not in a particular order:

0) Write a bunch of new rules in simplify to handle prefix forms. The redundancy in this approach seems unwise.

1) As each rule is read in, convert the rule to prefix form as well and add the converted version also. As a simple example, the rule `0*n -> 0` would also add `multiply(0,n) -> 0`. I fear this would not handle mixed expressions, i.e., wouldn't we want `add(4,2x) + 3x` to simplify, either to `add(5x, 4)` or to `5x + 4` (even if it is not quite clear which)? But I think it would work fine on totally-infix and totally-prefix expressions.

2) Convert all expressions coming in to the form simplify currently works in, namely infix form, then perform the simplification, then optionally convert back to prefix form based on an option like 'functionalForm' which could either be 'infix', 'prefix', or 'keep', which would attempt to match the input form. (Although `keep` would just have to guess whether you want `5x+4` or `add(multiply(5,x),4)` if you gave it `multiply(5,x) + 4` -- once that had been converted internally to `5x+4` for simplification, there would be no way to partially convert it back to prefix form.)

3) A much more radical thought: merge FunctionNodes and OperatorNodes altogether. There's actually very little separating them currently, as the "drop-throughs" in a number of case statements dealing with them shows. The merged "OperationNode" or whatever it would be called would have a `fn` property which would be a Node, typically a SymbolNode, giving its prefix name/identity, an optional `op` property, a string, giving its infix name if it has one, an `args` list of nodes, an `implicit` flag just like an operator node currently does, and an `infix` flag along very much the same lines as `implicit` for whether it was presented as an infix operator.  I think down this avenue, it would behoove implementing a more useful means of propagating the flags during simplification, which would make whether the result uses infix or prefix notation seem sensible, and would at the same time if we used the same mechanism for implicit finally take care of the fact that `2x+3x` simplifies to `5*x` when one might expect `5x`. The charm of this solution is that suddenly simplify wouldn't care which way you wrote the expression -- it would operate identically either way, because the internal representation would be exactly the same, except for some flags remembering which way it was input. And in this scenario, Node.toString might have an option concerning the infix/prefix presentation much like the one controlling implicit printing right now.

I think my sense that the last option could really help likely shows through, but let me be clear that (A) I am totally open to and happy to work on any approach, including one not listed here that you might suggest; and (B) I understand that option (3) would definitely be too big a change to occur in a single PR, as ultimately it would affect very large extents of the code, so I/we would have to come up with an incremental approach. That could perhaps be something like first creating the "OperationNode", then making sure it can print OK even though the parser never produces it, then making sure it evaluates OK, etc. etc., until finally once the parser is no longer producing either FunctionNodes or OperatorNodes, they can be dropped from the codebase. Or alternatively, the existing OperatorNode could gradually morph into the merged node, first changing its `fn` into a Node, then getting the `infix` flag, etc, and then once the OperatorNode had all of the capacities of the current FunctionNode, the parser could be changed to start producing OperatorNodes in place of FunctionNodes, and then after that FunctionNode could be dropped.

**Comment by gwhitney** [comment]
4. Here's a much less-radical version of (3): (A) Just in `simplify()`, convert any prefix-function-forms of operators into the corresponding OperatorNodes, but tag those nodes with a 'wasPrefix' property, taking advantage of the fact that you can add arbitrary properties to a JavaScript object; (B) implement propagation of operator properties across rules, to apply at least to 'implicit' and 'wasPrefix'; (C) perform the simplification on the operator version of the expression, using that propagation; (D) when you are done, go through the tree and transform any OperatorNodes that have the 'wasPrefix' property back into ordinary FunctionNodes. So this is basically doing a temporary merge of the node types, just for the purposes of `simplify`.

I'd be happy to work on a PR along the lines of (4), or on the chance you happen to think that (3) is actually a good direction to go, start working toward that goal.

Finally, a thought on how to propagate the labels like 'implicit' or 'wasPrefix' on operators when applying a rule in simplify: If the rule matches, then each operator on the LHS of the rule corresponds to a specific OperatorNode in the input parse tree. So then we just need to create a correspondence between operators on the RHS of the rule and operators on the LHS of the rule; then when we create the OperatorNodes in the result of applying the expression, we can just copy the properties from the OperatorNode associated with the corresponding operator on the LHS.

I suggest the following heuristics for determining which operator on the LHS should correspond to a given one on the RHS:
1) First, see if there are any occurrences of the same operator on the LHS. If not, go to step 4
2) If there is just one occurrence of the same operator on the LHS, use that one (note that this may make more than one operator on the RHS correspond to a single operator on the LHS, but that's OK)
3) If there are multiple occurrences of the same operator on the LHS, then if this is the first occurrence of that operator on the RHS, use the first occurrence on the LHS, if it's the second, use the second, etc; if there are not enough occurrences on the LHS to match up, just use the last occurrence of the LHS.
4) In this case, there are no occurrences of the same operator on the LHS. So use the operator in the same position in the list of all operators that do occur, but regardless of what the operator is: so the first on the RHS would correspond to the first on the LHS, the second to the second, and so on. As in (3), we'd just keep reusing the last on on the LHS if there are more operators on the RHS than the LHS.

That correspondence seems like it would be quite sensible for most (but not quite all) of the rules currently in simplify. So we could just see how it works. If there were cases where it was just producing inexplicable results, we could find the rules where things went awry, and implement an additional property or notation for rules or that would allow you to specify for each operator on the RHS "where it came from" in terms of the operators on the left. But I'm hopeful it wouldn't have to be that elaborate.

Thanks for your thoughts. Hopefully we can find a way to get simplify working well on prefix-functional forms of expressions as well.

**Comment by josdejong** [comment]
This is an interesting idea. Indeed `add(a, b)` is equivalent to `a + b`, so ideally `simplify` can deal with both, also when mixed together. It feels to me like we indeed need to give functions more meaning, like discussed recently in #2407 on giving meaning to `i`, `sin`, `log`, etc.

Your idea 3 sounds like a proper solution indeed, basically merging `FunctionNode` and `OperatorNode` together, and use flags to denote infix/prefix form. That would really solve the underlying issue. I like you're idea (4), which makes it much more pragmatic to get this idea working.

I have one more idea in this regard, though it didn't fully pan out yet:

(5) implement a new concept of aliases in the rule engine, so the engine understands these equivalent notations. So, a rule like `{ l: 'n*n', r: 'n^2' }`  should match occurrences like `n*n`, but also `multiply(n, n)`. And `{ l: 'n*c + c', r: '(n+1)*c' }` should match `n*c + c` but also `multiply(n, c) + c`, `add(n*c, c)`, and `add(multiply(n, c), c)`. I'm not yet sure if this could work out and if these different aliases could be calculated beforehand (where the amount of possible combinations can easily explode), or that the matching could be smarter and match both the prefix and infix variant of the rule.

**Comment by josdejong** [comment]
I'm open to try both (4) and (5). I'm convinced (4) will result in a good pragmatic solution. At this point I'm not sure (5) would work out nicely. I think you're most into this matter right now so probably the best to see this through (or do a little experiment).

> i.e. `multiply(pow(x,a), pow(x,b))` would be simplified to `x^(a+b)` (but `add(pow(x,a), pow(x,b)` would be left alone, i.e. would not be changed to `x^a + x^b`). Maybe that's a feature? Or maybe it's a problem?

I think this brings up a slightly different issue: when would we want `simplify` to replace functions with there operator equivalent? I think we will need new options and rules for that (basically: (a) leave as is unless it's a result of a simplification, or (b) replace functions with operators wherever possible). 

If we would only implement (b) though, life would become way simpler though 🤔 : just replace ("normalize") all functions like `add` and `multiply` with their operator, and after that, run `simplify`. Would that be acceptable? I myself do not see a reason to write `add(a,b)` over `a+b` when they are semantically the same).

**Comment by gwhitney** [comment]
Ok, as soon as I can get back to this I will write a non-exposed simplify.util.infixate that converts add(a,b) to a+b etc and make it the first rule in simplify -- unless you want that transform to happen in simplifyCore as well (which would be perfectly reasonable). I agree, as long as infix expressions are "preferred" this solves the problem with no further ado.

**Comment by josdejong** [comment]
Thanks 😎 !

**Comment by gwhitney** [comment]
Sure. Please just let me know whether you want this "infixate" to operate both in simplifyCore and in simplify, or just in simplify. It is a simple one-pass process, so it potentially "qualifies" for simplifyCore.

**Comment by josdejong** [comment]
At this point I think it fits well in `simplifyCore`. (if it turns out some day in the future that we want to make it configurable or so, we can revisit and probably move it to `simplify`then)
