### ISSUE TITLE
Assigning a readonly property

### ISSUE THREAD

**Issue by elvinaspredkelis** [josdejong/mathjs#2420]
Hey!

I'm trying to use the `mathjs` package with Typescript (which I'm not sure is related to the issue) and I started getting this error:

`TypeError: Attempted to assign to readonly property.` and it points to `decimal.mjs:2435`.

It happens when I call the `create` function as so, even if the project is completely new and only has mathjs as a dependency:

```javascript
import { create, all } from "mathjs"
const math = create(all)
```

For good measure, I did try substituting `const` with `let`.

Perhaps someone has some thoughts/suggestions on this?

**Comment by josdejong** [comment]
How can I reproduce your issue exactly?

**Comment by elvinaspredkelis** [comment]
@josdejong thank you for the reply.

I literally just discovered that it was caused by a setting not related to the mathjs library. A framework I'm using was implicitly freezing prototypes and that caused the issue.

Closing!

**Comment by josdejong** [comment]
👍 good to hear it's solved
