### ISSUE TITLE
Matrix operations failing because each element is stored as number[]

### ISSUE THREAD

**Issue by jchatkinson** [josdejong/mathjs#2428]
Hi mathjs team. 

I'm creating a small matrix structural analysis program using mathjs, but have hit a roadblock... 

It seems that some operations (multiply, subset, etc) are taking inputs with format of 
`[[ a, b ], [ c, d ]]` 

and returning a format of 
`[[ [a], [b] ], [ [c], [d] ]]` 
where each element of the output is in an array of length 1. 

further operations then fail to work on this format of output matrix, and I need to do things like squeeze(m.toArray()) to remove the nested arrays.

Is there something I am doing, unknowingly, to cause this behaviour? I appreciate any advice you have.

**Comment by josdejong** [comment]
Thanks for reporting Jeremy. How can I reproduce your issue?

**Comment by jchatkinson** [comment]
Now that i look more into it, I think I was mainly confused about the different behavior between matlab and mathjs. 

In matlab you can take a vector [a,b,c] and add to a row of a matrix directly. 

In mathjs, functions like subset, row, etc are returning [[ a,b,c ]] and not [a,b,c]. 

https://stackblitz.com/edit/mathjs-2428?file=index.ts

This seems to be the source of my problems

Apologies for the non-issue issue.

**Comment by josdejong** [comment]
👍
