### ISSUE TITLE
std and variance function signature don't match with document

### ISSUE THREAD

**Issue by NattapongSiri** [josdejong/mathjs#2429]
In [variance](https://mathjs.org/docs/reference/functions/variance.html), it suppose to work with data like:
```typescript
let x = [[1, 2, 3], [4, 5, 6]]
variance(x, 1)
```
However, typescript compiler complain that second parameter must be string.
The same goes for std function.
I take a look into type definition in here:
https://github.com/josdejong/mathjs/blob/c35e0b99c19c2cc0f415ed92abfa567049aedba4/types/index.d.ts#L2242
and
https://github.com/josdejong/mathjs/blob/c35e0b99c19c2cc0f415ed92abfa567049aedba4/types/index.d.ts#L2272
and
https://github.com/josdejong/mathjs/blob/c35e0b99c19c2cc0f415ed92abfa567049aedba4/types/index.d.ts#L2280

It's clear that the type definition are all mismatch with what describe in official doc itself.

**Comment by josdejong** [comment]
Thanks for reporting. 

Anyone able to improve the TypeScript definitions of `std` and `variance`?

**Comment by josdejong** [comment]
The type definitions are created by hand, they are all located in index.d.ts

**Comment by NattapongSiri** [comment]
Does it support dimension argument as well ?

**Comment by josdejong** [comment]
Yes indeed, it's basically the methods are the same as the functions, but the first argument is gone.

**Comment by NattapongSiri** [comment]
I added overload to std and var in MathJsChain.

**Comment by josdejong** [comment]
Improved definitions are published in `v10.4.0`

**Comment by robocop6** [comment]
With the current code, this raises a typescript error:

```ts
const array = [1, 2, 3];
std(array); // Argument of type 'number[]' is not assignable to parameter of type 'number'. ts(2345)
```

Of course it can be fixed by using `std(...array)`, but I was wondering if there should be an overload with optional `dimension` and `normalization` parameters, so that `std(array)` is valid as well.

**Comment by NattapongSiri** [comment]
This will be a quick and easy fix.
Do you preferred to reopen this issue ? Or create a new one ?

**Comment by josdejong** [comment]
Ow, good point. I had overlooked that too.

@NattapongSiri can you put together a small PR to fix this?

**Comment by gwhitney** [comment]
With #2474 merged, can this issue be closed again? I think so, but I thought either @NattapongSiri or @josdejong should weigh in.

**Comment by NattapongSiri** [comment]
I think it can be closed.
