### ISSUE TITLE
Update typedefs for filter functions in `is.js` (`isInteger`, etc)

### ISSUE THREAD

**Issue by ChristopherChudzicki** [josdejong/mathjs#2430]
**Issue:** The typedef for `isInteger` is currently
```ts
// current typedef
isInteger(x: number | BigNumber | Fraction | MathArray | Matrix): boolean;
```
So calling `isInteger('cat')` is a type error. But calling `isInteger` is safe on any input and the result makes sense on any input ("cat" is not an integer).

**Proposal** Change the typedef for `isInteger` to
```ts
isInteger(x: unknown): boolean;
```
which also matches how Typescript handles `Number.isInteger`. (See https://github.com/microsoft/TypeScript/blob/d699bcdaae9d7138eb29612d410e628154a254b6/src/lib/es2015.core.d.ts#L213)

Also:
- Do this for all the `is` functions 
- Add typedefs for `is` functions that are missing typedefs. E.g., `isMatrix` has no typedef

**Comment by ChristopherChudzicki** [comment]
I am going to open a PR for this, but thought I'd write an issue first

**Comment by ChristopherChudzicki** [comment]
Closing this. I was wrong about `isInteger` being safe to call on anything.

**Comment by josdejong** [comment]
👍
