### ISSUE TITLE
Add typedefs for `is.js` functions

### ISSUE THREAD

**Issue by ChristopherChudzicki** [josdejong/mathjs#2431]
The functions in `is.js` do not have typedefs...  (Certainly most of them don't, anyway).

So, add typedefs for functions in `is.js`.

I am happy to make a PR for this. _isMatrix is my immediate need, but I'll add them all._

**Comment by gwhitney** [comment]
The difficulty seems to be that although the "isXXX" functions of src/utils/is.js have been exported as part of the mathjs instance, they have not yet really been promoted to "first-class" parts of the mathjs API: they are not listed in the mathjs function reference, and they are not usable within a mathjs expression (try typing `isMatrix([1,2])` in the demo on the front page. That explains why there is no TypeScript typing for them (which is what I assume you are asking about) in `types/index.d.ts`.

So I think the first step would be a proposal to expose some or all of these "isXXX" functions to the primary mathjs API. I don't see any reason for that not to happen, but the package lead @josdejong would need to weigh in on that.

Then we could address the TypeScript typing. It might be slightly tricky as we would want TypeScript to infer that once e.g. `isMatrix(x)` had returned true that `x` is in fact of type `Matrix`, and I think the syntax for that was only introduced at a certain release of TypeScript (I am not particularly a TypeScript expert). So we might need to take care to make `index.d.ts` resilient to different versions of TypeScript. Assuming the basic idea of making these "isXXX" functions full-fledged is OK, we would absolutely appreciate help in the form of PRs.

**Comment by ChristopherChudzicki** [comment]
Thanks for the reply @gwhitney! I'm happy to open a separate issue proposing that some of these functions be part of the public API.

> It might be slightly tricky as we would want TypeScript to infer that once e.g. isMatrix(x) had returned true that x is in fact of type Matrix, and I think the syntax for that was only introduced at a certain release of TypeScript 

This is possible with [type predicates](https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates) (aka "type guards"). I don't know exactly in what version of Typescript these were introduced, but the MathJS typedefs already use them (e.g., for `isNumeric`) so there should be no compatibility issue.

**Comment by gwhitney** [comment]
> I'm happy to open a separate issue proposing that some of these functions be part of the public API.
Yes, please do, propose whatever subset (or all) of them makes sense and we will see where the project lead lands on this.

> the MathJS typedefs already use [type predicates]
Ah, OK, I didn't realize that; so in that case (as I see your proposed TypeScript typings also use them) I agree there is no issue here.

**Comment by ChristopherChudzicki** [comment]
Closing in favor of #2444
