### ISSUE TITLE
"New functions can be defined using the `function` keyword." ?

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2442]
The issue title is a quote from https://mathjs.org/docs/expressions/syntax.html

But I don't see any example of this and can't find anything in the code this would correspond to. Is it perhaps a leftover in the documentation, not reflecting the current state of affairs? If so, am happy to do a PR removing it.

**Comment by gwhitney** [comment]
I really couldn't see any "function" keyword in current mathjs (although maybe I am just being blind) so I went so far as to remove that from the documentation in the PR allowing functions as arguments.

**Comment by josdejong** [comment]
I think this is just a vague sentence in the docs and should be improved, I see you did that already in #2443 👍

**Comment by josdejong** [comment]
Fix published in `v10.3.0`
