### ISSUE TITLE
Object syntax doesn't allow numbers as keys

### ISSUE THREAD

**Issue by WesleyKapow** [josdejong/mathjs#2451]
For some complex reasons I have objects that have numeric keys. I'd like to access those as numbers to allow for variables in place of the key. E.g. `math.evaluate("foo[index]", {index: 3, foo: {0: 'rar', 1: 'baz', 2: 'bar', 3: 'hello'}})`. This is not currently possible due to a limitation where mathjs rejects numeric keys on objects.

Example:
```js
// Using a string as the key.
math.evaluate("foo['3']", {foo: {3: 'hello'}})
// > 'hello'

// Using a number as the key.
math.evaluate("foo[3]", {foo: {3: 'hello'}})
// > access.js:35 Uncaught TypeError: Cannot apply a numeric index as object property
```

I've traced the issue to these lines where `arg` is a number and so this code turns it into an `ImmutableDenseMatrix` instead of just leaving the number `arg` as is.
https://github.com/josdejong/mathjs/blob/47a493d70ac92daa47b26f9eea88513a7efa4408/src/type/matrix/MatrixIndex.js#L54-L59

Thoughts on work arounds or a fix?

Thank you!

**Comment by gwhitney** [comment]
Wesley, thanks so much for bringing up this concern.
Note
```
math.evaluate("foo[string(index)]", {index: 3, foo: {0: 'rar', 1: 'baz', 2: 'bar', 3: 'hello'}})
// => 'hello'
// Alternatively,
math.evaluate("get(obj, key) = obj[string(key)]; get(foo, index)", {index: 3, foo: {0: 'rar', 1: 'baz', 2: 'bar', 3: 'hello'}})
// => ['hello']
// produces a ResultSet because of the semicolon, but you can also make a parser object and just evaluate
// the `get` definition once and then use that parser with expressions that include `get`
```
Does either of these work for you?

**Comment by josdejong** [comment]
Interesting issue, thanks Wesley. 

Conceptually I would love to keep objects and array separated from each other. Have objects work with string properties, and arrays with numeric indices. In JavaScript, arrays and objects are half mixed and numeric properties are automagically coerced into strings when acting on an object. And arrays can have additional string properties etc. I'm in doubt whether that intermixed freedom is a good thing.

If there is a clear, common case to allow using numbers as object keys we can consider it of course. Until then I hope there is a workaround that is workable for you, like the ideas that Glen proposes such as stringifying the index/property: `foo[string(index)]`

**Comment by WesleyKapow** [comment]
Thanks for the response and I think that makes a lot of sense. The `foo[string(index)]` solution _can_ work for me but it'll be a bit hacky as these expressions are user inputs. So I'll have to regex to/from to hide this from users.

**Comment by josdejong** [comment]
ah, yes that can be tricky. A regex will probably work (at least when the user enters just a number as property). 

If you need a more robust solution, you can look into parsing the expression, and transforming the expression tree: check for occurrences of `IndexNode`, and change numeric indices into a string, and only after that evaluate the expression. See docs on the method transform on this page: https://mathjs.org/docs/expressions/expression_trees.html

**Comment by josdejong** [comment]
👍
