### ISSUE TITLE
pow(matrix, n) can easily be extended to negative n

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2463]
The typical meaning of M^(-2) would be inv(M)^2. It would seem reasonable to extend pow(M,n) to negative n in this way. There doesn't seem to be any risk; pow(M,-2) might throw an error if M is noninvertible, but it always throws an error at the moment. Unless some problem with this extension is foreseen, I will extend the definition of pow(M, n) in this way when I get a chance.

**Comment by josdejong** [comment]
If that calculating with the inverse M is the "normal" meaning of `M^(-2)` in maths, then it makes sense to me, sounds good 👍

**Comment by gwhitney** [comment]
Absolutely that's what someone doing linear algebra would understand by `M^(-2)`.
