### ISSUE TITLE
`nthRoot(125, 3)` results in `4.999999999999999`

### ISSUE THREAD

**Issue by apteryxxyz** [josdejong/mathjs#2464]
`cbrt(125)` returns `5` as it should, but `nthRoot(125, 3)` results in `4.999999999999999`.
The same thing happens with `4^3`.
Is this a bug?

**Comment by gwhitney** [comment]
Well, essentially all that `nthRoot(x,y)` does is call the native javascript `Math.pow(x, 1/y)` so it is not too surprising that method could have slight rounding errors. On the other hand, `cbrt(x)` calculates e^(log(x)/3) and then uses a clever correction step with a trial division of the result to increase the accuracy. Hence its numerical properties are much better - a quick search did not find an integer cube that it got wrong (although there could be some somewhere...)

There are four possible responses here, and I think the architect @josdejong will have to decide among them:
1) Do nothing, beyond perhaps documenting that nthRoot is a numeric approximation that may not find integer roots;
2) Special-case nthRoot for 2 and 3 to delegate to sqrt and cbrt, respectively; (and maybe document the approximate-ness for higher-order roots)
3) See if the correction step that cbrt does can be generalized to nth roots and if so incorporate it in the nth root algorithm;
4) When the current implementation of nthRoot comes close to an integer, do a trial cubing of the nearest integer and if it matches the input, return the integer -- recognizing the potentially important use-case for finding integer nth roots.

Thoughts?

**Comment by josdejong** [comment]
This is the most asked question. It's just a round-off error. (Search for issues on "round-off error" 😉)

Docs with explanation and solutions: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by gwhitney** [comment]
I am leaving this closed but it's not _quite_ fair to say this one is "just" a round off error. The exact 3rd root of 125 is representable in ordinary javascript number type, but the nthroot algorithm used isn't accurate enough to select the precise floating point number that is the exact cube root -- unlike the distinct cbrt algorithm, which is. It might be of service to mathjs clients for those instances that have integer nth roots for the nthroot function to find them exactly, and there are a few ways that might be approached as I listed,  but I also respect your decision if you want to do nothing. If you do decide it could be of value to increase the accuracy of nthroot for integer cases, just reopen this issue and give some indication which method you'd like to explore and I will be happy to give it a go.
