### ISSUE TITLE
simplifyCore() could do better with `a+-0`

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2484]
Currently, `simplify(parse('a+-0'))` returns the expression `a - 0`. But there is no reason it shouldn't be able to take this all the way down to just `a`, as it knows that `a+-b` is `a-b` and that `a-0` is `a`, and it does not take an extra pass to perform both steps. If there's no objection, I will file a PR that enhances `simplifyCore` to catch these "sequential steps" cases.

**Comment by josdejong** [comment]
Sounds like a logical improvement, thanks 👍
