### ISSUE TITLE
Syntax for calling a computed function?

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2495]
At the moment, you can easily create functions that produce other functions:
```
math.evaluate('twice(f) = lambda(x) = f(f(x)); fourth = twice(square); fourth(3)') // returns ResultSet([81])
```
(Note that `lambda` is an arbitrary function name, here chosen to be suggestive of lambda-expressions.)

However, the only way I could find to directly call the result of an expression is the rather convoluted:
```
math.evaluate('twice(f) = lambda(x) = f(f(x)); [twice(square)][1](3)') // returns ResultSet([81])
```
Both the syntaxes `twice(square)(3)` and `(twice(square))(3)` parse to implicit multiplication of the result of the expression `twice(square)` and `3`, rather than function application, which of course then fails, as there is no definition of multiplying a function object by 3 (nor should there be, most likely).

Should there be a more direct syntax for applying the result of an expression like `twice(square)` to arguments? Perhaps one or the other of `twice(square)(3)` or `(twice(square))(3)` ? In other words, one of the two syntaxes `EXPR(3)` or `(EXPR)(3)` would only be interpreted as implicit multiplication in some special cases like EXPR is a constant, as opposed to the current state of affairs in both are only interpreted as a function call when EXPR is a SymbolNode or AccessorNode and in all other cases both are interpreted as implicit multiplication?

Just brainstorming on the basis of the investigation I did for the sake of #2493.

**Comment by josdejong** [comment]
Thanks for bringing this up. It's related to this syntax being used for implicit multiplication too. Difficulty is that you would have to know at parse time what the actual value of a variable like `twice` is. Right now, parsing and evaluation are strictly separated, which brings a lot of good. If possible I would like to keep it that way.

We've discussed this before in #2182, let's continue the discussion there and close this issue as a duplicate ok?
