### ISSUE TITLE
0.1 + 0.2 is not 0.3

### ISSUE THREAD

**Issue by elijahmanor** [josdejong/mathjs#25]
I was playing around with your library, which is great by the way. I've noticed some inconsistencies from what I've seen on your website and what I get when I use the library. See the following screenshot. I've experienced the same thing in Chrome Canary, IE10, and Firefox latest. 

http://twitpic.com/d3tbxq

**Comment by alfiqmiq** [comment]
an simple answer:

`+(0.2 + 0.1).toFixed(12)`

works in IE 11, EDGE, Chrome, Opera, FF
