### ISSUE TITLE
Unit conversion/selection oddities

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#2500]
Here are ~~three~~two cases in determining the units of an answer that do not behave as expected. In each case, the expression is simply evaluated and the result is printed as a string:

~~1) "720 deg/s to hertz" -- expected "2 hertz", actual throws an error~~ Ah I didn't understand that in the mathjs hertz is strictly second^-1 and that cycle/second is a distinct unit and there is no implicit or automatic conversion between them. So I retract this concern, although the other two stand. 

2) "2 J/K/g * 2g" -- expected "4 J/K", actual "4 (J g)/(K g)" (Why is it not canceling the same unit in numerator and denominator?)

3) "2 J/K/g * 2K" -- expected "4 J/g", actual "5.5800111600223e+11 ft^2 / hour^2"

In the last example, the dimensions are actually correct, in that a joule per gram does have dimensions length squared per time squared, but the selection of units is really strange, in particular an english unit showing up when all the inputs are metric. (And why convert to hours?) [Not sure if these are bugs or feature requests or if the three items should be split into separate issues...]

**Comment by dvd101x** [comment]
Hi, I don't know if this is helpful for the discussion, but here is a way to work around this behavior.

1. `720 deg / (cycle s) to hertz` -> `2 hertz`

2. `2 J / K / g * 2 g to J / K` -> `4 J / K`

3. `2 J / K / g * 2 K to J / g` -> `4 J / g`

**Comment by josdejong** [comment]
It could very well be that these issues are addressed in https://github.com/ericman314/UnitMath (which we want to use to replace the build int Unit.js class). @ericman314 do you have any feedback on this?

**Comment by gwhitney** [comment]
> don't know if this is helpful for the discussion

Actually your item 1 was very helpful in my understanding the unit system better and therefore why I should not actually have expected example 1 to work. Thanks!

**Comment by ericman314** [comment]
I think UnitMath will help with some of these issues; I'm still trying to work out a few bugs before releasing v1.0. I have no idea why `ft^2 / hour^2` is showing up in example 3 though.

**Comment by josdejong** [comment]
Thanks for your feedback @ericman314. Still looking forward to to `UnitMath@1.0` 😁

**Comment by gwhitney** [comment]
OK, I am going to assume it's not worth chasing down particulars on example 2 and 3 at the moment; they can be added as unit tests after the adoption of UnitMath.

**Comment by josdejong** [comment]
We could add these tests to UnitMath already 😄 .

Is it ok to close this issue? It's not really solved but also not really actionable.

**Comment by gwhitney** [comment]
Well why don't I file a PR that adds examples 2 and 3 as "pending" tests to close this issue? Then they can be activated when the unit situation improves, but the project doesn't lose track of these potentially anomalous cases.

**Comment by josdejong** [comment]
Ah, yes sounds good 👍 . Feel free to add the tests directly on the `develop` branch

**Comment by gwhitney** [comment]
Felt "safer" to branch and merge; just completed with PR #2513. Closing this issue.
