### ISSUE TITLE
Bug: Binary prefix and SI prefix incorrectly used for byte ('B'). 

### ISSUE THREAD

**Issue by andrewmtoy** [josdejong/mathjs#251]
I was trying to convert a quantity from B to MB and I got an unexpected result.  
```
console.log(math.format(math.eval('5000000 B to MB'), 14))
Result:  4.7683715820313 MB
```
I was expecting to see 5MB. 

I saw in the documentation, units.md, that SI prefixes such as kilo, mega, giga, etc. have the same value as their IEC counterparts kibi, mebi, gibi, etc.    

According to IEC, this is incorrect.  Their definitions for kibibyte and kilobyte are as follows.

The definition of the kibibyte is: 
1 kibibyte = 210 bytes = 1024 bytes.

The definition of the kilobyte is:
1 kB = 1000bytes = 10^3

**Comment by josdejong** [comment]
I have created a [`v2` branch](https://github.com/josdejong/mathjs/tree/v2), which already contains the fixed behavior for bits and bytes. 

It will take some time though before v2 will be ready, I'm working on a large refactoring which will enable modularization of math.js.

**Comment by josdejong** [comment]
Rethinking this, I think it may be better to fix this bug now. It's sort of a backward incompatible "change" but on the other hand it's just a fix of wrong behavior which should not be like that anyway. This bug has been open way too long, and v2 isn't yet there...
