### ISSUE TITLE
Referring to items in object/matrix in an expression

### ISSUE THREAD

**Issue by koosvanderkolk** [josdejong/mathjs#2510]
Maybe I miss something obvious, but the following does not work 

```
let parser = math.parser();
parser.set('a', {0: 3, 1: 1});
let b = parser.evaluate('b = a.0;');
console.log(b); // expected: 3

parser.set('c', [4,5]);
let d = parser.evaluate('d = c[0];');
console.log(d); // expected: 4
```

As both give errors:

```
"error"
"TypeError: Unexpected type of argument in function multiplyScalar (expected: number or Complex or BigNumber or Fraction or Unit or string or boolean, actual: Object, index: 0)
    at M (https://cdn.jsdelivr.net/npm/mathjs:46:26941)
    at Function.I (https://cdn.jsdelivr.net/npm/mathjs:46:32176)
    at Function.ae (https://cdn.jsdelivr.net/npm/mathjs:46:31538)
    at Function.multiplyScalar (https://cdn.jsdelivr.net/npm/mathjs:46:31921)
    at Function.ae (https://cdn.jsdelivr.net/npm/mathjs:46:31507)
    at multiply (https://cdn.jsdelivr.net/npm/mathjs:46:31921)
    at https://cdn.jsdelivr.net/npm/mathjs:46:387095
    at Object.evaluate (https://cdn.jsdelivr.net/npm/mathjs:46:360318)
    at https://cdn.jsdelivr.net/npm/mathjs:46:362521
    at Array.forEach (<anonymous>)"
"error"
"TypeError: Unexpected type of argument in function multiplyScalar (expected: number or Complex or BigNumber or Fraction or Unit or string or boolean, actual: Object, index: 0)
    at M (https://cdn.jsdelivr.net/npm/mathjs:46:26941)
    at Function.I (https://cdn.jsdelivr.net/npm/mathjs:46:32176)
    at Function.ae (https://cdn.jsdelivr.net/npm/mathjs:46:31538)
    at Function.multiplyScalar (https://cdn.jsdelivr.net/npm/mathjs:46:31921)
    at Function.ae (https://cdn.jsdelivr.net/npm/mathjs:46:31507)
    at multiply (https://cdn.jsdelivr.net/npm/mathjs:46:31921)
    at https://cdn.jsdelivr.net/npm/mathjs:46:387095
    at Object.evaluate (https://cdn.jsdelivr.net/npm/mathjs:46:360318)
    at https://cdn.jsdelivr.net/npm/mathjs:46:362521
    at Array.forEach (<anonymous>)"
```

How can I refer to items in an object/matrix in an expression?

**Comment by gwhitney** [comment]
Koos, thank you for your interest in mathjs and for your question.

In mathjs, the situation is a bit different for your two cases:

1) Indexing a JavaScript object that has a key equal to 0:
    First note that '.0' is a valid notation for the number 0, and juxtaposition of an identifier and a number is by default an
    implicit multiplication in the mathjs parser. Hence it interprets `a.0` as multiplying the object a by zero, which it does not
    know how to do, so it errors.

    So then one might try `b = a[0]` but there you will run afoul of the fact that mathjs explicitly forbids indexing a (plain) object
    by a number, because it makes a greater distinction between arrays and objects than JavaScript in general does, and to
    avoid ambiguity between array and object indexing.

    But what should work here and return 3 as expected is:
    `let b = parser.evaluate('b = a["0"]')`
    since in fact in JavaScript an object key of `0` is the same as an object key of `'0'`. Also **note** the lack of a final
    semicolon in the expression being evaluated here; in the mathjs parser, `;` is an expression separator that means first
    evaluate the left-hand expression and _ignore its value_, then evaluate the (in this case, empty) right-hand expression.
    So if you kept the final semicolon, the value of b back in JavaScript would end up as the not-very-helpful 
    `ResultSet { entries: [] }`. (Even though the value of b _in the parser_ would end up as 3, as desired, since that first
    expression `b = a["0"]` is still evaluated, which sets b to 3 in the parser as a side effect; just its value is not returned.)

2) Indexing the first element of a JavaScript array:
    First, I am a bit confused about the error you are reporting in this case. When I run your second example, I get the
    following error:
```
Error
    at new IndexError (file:///home/glen/code/mathjs/src/error/IndexError.js:33:17)
    at errorTransform (file:///home/glen/code/mathjs/src/expression/transform/utils/errorTransform.js:10:12)
    at access (file:///home/glen/code/mathjs/src/expression/node/utils/access.js:35:13)
    at evalAccessorNode (file:///home/glen/code/mathjs/src/expression/node/AccessorNode.js:99:16)
    at Object.evalAssignmentNode [as evaluate] (file:///home/glen/code/mathjs/src/expression/node/AssignmentNode.js:117:23)
    at evalBlockNode (file:///home/glen/code/mathjs/src/expression/node/BlockNode.js:73:30)
    at Array.forEach (<anonymous>)
    at forEach (file:///home/glen/code/mathjs/src/utils/array.js:458:27)
    at evalBlockNodes (file:///home/glen/code/mathjs/src/expression/node/BlockNode.js:72:7)
    at Object.evaluate (file:///home/glen/code/mathjs/src/expression/node/Node.js:52:14) {
  index: 0,
  min: 1,
  max: 3,
  message: 'Index out of range (0 < 1)'
}
```
and so you may want to re-check how you are trying to run your second test case and see if you're perhaps inadvertently revisiting the first test case somehow. In any case, I think had you gotten this error it might have reminded you that the mathjs **parser** implements 1-based array access, not 0-based. So to get the first entry of "c", namely the 4, you need to:
`let d = parser.evaluate('d = c[1]');`
and then you should get 4 as expected (note again no final semicolon in the expression).

Hope this helps.

**Comment by koosvanderkolk** [comment]
@gwithney, thanks for your elaborate answer!

I indeed suspected Mathjs would disagree with numeric object keys. 

The thing about 1-based arrays confused me, as the docs state (https://mathjs.org/docs/datatypes/matrices.html)

> Matrix indexes in math.js are zero-based, like most programming languages including JavaScript itself.

But in the parser it suddenly becomes one-based? Isn't that a bug?

Anyway, this works:
```
let parser = math.parser();

parser.set('a', {x: 0, y: 1});
parser.set('c', [4,5]);

let b = parser.evaluate('b = a.y');
let d = parser.evaluate('d = c[1]');

console.log(b, d); // outputs 1 and 4
```

Finally, I noticed that adding a semicolon at the end of an expression gives a completely different result:

```
parser.set('c', [4,5]);
let d = parser.evaluate('d = c[1];'); // mind the ; at the end
console.log(d); // outputs 

// [object Object] {
// entries: [],
//  isResultSet: true,
//  toJSON: function(){return{mathjs:"ResultSet",entries:this.entries}},
//  toString: function(){return"["+this.entries.join(", ")+"]"},
//  type: "ResultSet",
//  valueOf: function(){return this.entries}
// }
```

**Comment by gwhitney** [comment]
> But in the parser it suddenly becomes one-based? Isn't that a bug?

Well, see: https://mathjs.org/docs/expressions/syntax.html
It's designed this way because the primary audience of mathjs as a library of math routines is JavaScript developers, who of course expect 0-based arrays, but the primary audience of mathjs as a computer algebra system (hence through the parser) are math, statistics, and engineering folks, quite possibly not primarily coders, who generally expect 1-based arrays.

> I noticed that adding a semicolon at the end of an expression gives a completely different result

Yes, I did also explain that in detail in my last response: the semantics of `;` is explicitly "evaluate and ignore the expression to my left and then evaluate the expression to my right." Hence a single expression with a semicolon after it evaluates to a list of no results.

**Comment by koosvanderkolk** [comment]
@gwhitney Thanks for you patience and explanation. 

Thing is, both the two-way-indexing and the semicolon behaviors are so puzzling to me that I completely missed them in your earlier explanation. Sorry for that.
