### ISSUE TITLE
evaluate expression with html elements as operands 

### ISSUE THREAD

**Issue by bahmansh** [josdejong/mathjs#2522]
I have a simple form in javascript. I'm going to calculate a formula.

I want to select elements by id and then detects operators and finally calculate final result.

    <p>
      V1: <input id="v1" />
    </p>
    <p>
      V2: <input id="v2" />
    </p>
    <p>
      V3: <input id="v3" />
    </p>
    <p>
      V4: <input id="v4" />
    </p>
    <p>
      Fromula: <input id="f1" />
    </p>
    <p>
      <button id="doAction">
        Calculate
      </button>
    </p>

Example expression is: (v1+v2)*v3-(v4-v1)/v2

https://jsfiddle.net/bshafiei/zyv7bsfd/14/

**Comment by josdejong** [comment]
You'll have to collec the values of v1, v2, v3, v4 in an object, and then you can pass this object along with the expression when evaluating:

```js
const scope = {
  v1: ...,
  v2: ...,
  v3: ...,
  v4: ...
}
const f1 = ...

const result = math.evaluate(f1, scope)
```
```

**Comment by bahmansh** [comment]
here is one simple cod that I found:


https://jsfiddle.net/bshafiei/zyv7bsfd/51/

**Comment by josdejong** [comment]
Thanks for sharing your solution 👍
