### ISSUE TITLE
Type definitions missing in ceil method

### ISSUE THREAD

**Issue by TomToms55** [josdejong/mathjs#2526]
According to Mathjs documentation math.ceil and math.floor support a second argument that is not described in the index.d.ts (eg: math.ceil(x, n) where n is the number of decimals with default value: 0).

 Add in index.d.ts:
`
 ceil(x: number, n: number): number;
`

**Comment by josdejong** [comment]
Thanks for reporting Tomas.

Anyone able to bring the TypeScript definitions of `ceil` up to date (and see if similar issues are also behind)?

**Comment by gwhitney** [comment]
The merged pull request referenced above definitely helps, but it regressed on the contents of AUTHORS (putting HanchaiN's dispreferred email address back in), did not actually address #2529 as claimed there, did not add tests for this concern in `types/index.ts`, and did not address similar issues with floor, fix, and round. I will file a follow-on PR to address these remaining points.

**Comment by josdejong** [comment]
Good points Glen, thanks for directly picking this up in #2539.
