### ISSUE TITLE
Contribution guideline

### ISSUE THREAD

**Issue by HanchaiN** [josdejong/mathjs#2528]
Current guidelines seem to provide information about the standard and some requirements without much detail. It would be helpful to have some more detail, e.g., what has to be done when implementing new functions, what has to be done when changing the existing function, where are the tests, etc.

This should reduce many repetitive comments in the PRs, issues (e.g., #2487), and so on.

This might be related to #2472.

**Comment by josdejong** [comment]
See #2548
