### ISSUE TITLE
Add the Universal Gravitational Constant

### ISSUE THREAD

**Issue by thonkinator** [josdejong/mathjs#2530]
It would be nice if mathjs had the Universal Gravitational Constant (G) as one of it's constants. I would think that it would be an uppercase G, as it's referred to normally, although depending on how other constants are defined it could also be lowercase.
Because it's so hard to measure with accuracy though, there are many different values of G, but the one that seems to be most commonly used in code is `6.67430e-11`.

**Comment by josdejong** [comment]
Thanks for your suggestion. Would be nice to add this constant. I think it makes sense to name it `G` indeed.

Anyone interested in creating a PR with this new unit?

**Comment by dextel2** [comment]
Impulsively committed. please ignore

**Comment by Kartik199** [comment]
A naive newbie question. Isn't the constant G already defined in physicalConstants.js? https://github.com/josdejong/mathjs/blob/47a493d70ac92daa47b26f9eea88513a7efa4408/src/type/unit/physicalConstants.js#L7

**Comment by HanchaiN** [comment]
This is the very first physical constant defined in this library. It would be nice to define more of them (e.g. Planck's constant, speed of light, electron's charge, Boltzmann constant, fine-structure constant, etc.) and classify them into separate categories.
Additionally, defining some of them (eight will be enough to define time, meter, kilogram, ampere, kelvin, mole, and candela) and deriving the others from the basic and unitless constants is recommended. Despite the precision error, the value will likely always be in line with one another.

**Comment by josdejong** [comment]
Actually there are quite some physical constants defined already, see [/src/type/unit/physicalConstants.js](https://github.com/josdejong/mathjs/blob/develop/src/type/unit/physicalConstants.js)

**Comment by josdejong** [comment]
o wow you're right, I hadn't realized that. 

@thonkinator does the `gravitationConstant` solve your problem? I think if you want you can always define `G=gravitationConstant` to have a shorter name.

**Comment by gwhitney** [comment]
As it appears the feature desired is already present in mathjs (albeit under a different name), closing.
