### ISSUE TITLE
math.evaluate return an Object if variable undefined

### ISSUE THREAD

**Issue by wiryonolau** [josdejong/mathjs#2549]
Is there a way to throw exception if variable not define in scope ?

```js
let series = {
  first : {
    value : "a"
  },
  second : {
    value : "b"
  }
}

let data = {
  a : 10
}

Object.keys(series).map((k) => {
  math.evaluate(series[k].value, data);
});
```

first value return 10, the second one return an object 
```
Object { units: (1) […], dimensions: (9) […], value: null, fixPrefix: false, skipAutomaticSimplification: true }
```

**Comment by josdejong** [comment]
The variabele `b` returns the unit bytes. Try `math.format(...)` on the result to see what it contains.

When a variable is unknown, an error will be thrown.
