### ISSUE TITLE
Remove example from npm distribution

### ISSUE THREAD

**Issue by SimenB** [josdejong/mathjs#2550]
`examples` - including its `node_modules` are shipped in the `npm` binary.

At the very least the `node_modules` should not be bundled

https://www.runpkg.com/?mathjs@10.5.1/examples/node_modules/.package-lock.json

**Comment by josdejong** [comment]
The `node_modules` folder is removed now in `mathjs@10.5.2`. Will close this issue, and address removing the `examples` itself in #2337

**Comment by SimenB** [comment]
thanks!
