### ISSUE TITLE
Missed opportunity for simplify() on element-wise binary/unary vector operations

### ISSUE THREAD

**Issue by zopieux** [josdejong/mathjs#2552]
#### Current behavior

    const diff = simplify('a - b', {a: parse('[a1, a2]'), b: parse('[b1, b2]')})
    diff.toString()
    // '[a1, a2] - [b1, b2]'
    simplify('diff[1]', {diff}).toString()
    // '([a1, a2] - [b1, b2])[1]'

#### Expected behavior

    diff.toString()
    // Element-wide spread of binary operator '-'
    // '[a1 - b1, a2 - b2]'
    simplify('diff[1]', {diff}).toString()
    // 'a1 - b1'
    // (simplification of vector index is already implemented, but here
    //  it's prevented by the previous step not simplifying enough)

**Comment by gwhitney** [comment]
Thank you for raising this point. It is true that simplify is currently weak on expressions involving arrays. There are structural reasons for this which we intend to address in the near term: see #2390 and #2423. I am taking this issue and adding it as an example in the discussion for #2390; it can be addressed when something along the lines of that feature proposal is implemented. Then I will close this as a separate issue
