### ISSUE TITLE
Evaluate an expression that contains an array

### ISSUE THREAD

**Issue by sergiomartindev** [josdejong/mathjs#2558]
I'm trying to evaluate this expression:

```
math.evaluate('90 == 90 & [10, 20, 30] == 30');
```
My intention is to find whether some of the values included inside of the array is equal to 30. 

In this case, the method returns an object. Which contains a _data property which seems to work properly. It is an array, of three elements, that contains a bit value corresponding to each evaluation ([0, 0, 1]). And it could work for me, but the things get crazy when I try more complex expressions. 

Is it possible to achieve what I'm looking for?

**Comment by sergiomartindev** [comment]
I think I got it. 

Overriding the behavior of the equal operations. So it checks whether any of the operands is a "dense matrix" (whether it has a [n, m] format).

```
import { create, all, factory, evaluateDependencies } from 'mathjs';

const myMathInstance = create(evaluateDependencies);

const allWithCustomFunctions = {
  ...all,
  createEqual: factory(
    'equal',
    [],
    () =>
      function equal(a, b) {
        if (a?.isDenseMatrix && b?.isDenseMatrix) {
          return a._data.some((aValue) => b._data.some((bValue) => aValue === bValue));
        } else if (a?.isDenseMatrix) {
          return a._data.includes(b);
        } else if (b?.isDenseMatrix) {
          return b._data.includes(a);
        }

        return a === b;
      }
  ),
};

const customEvaluate = create(allWithCustomFunctions).evaluate;

myMathInstance.import(
  {
    evaluate: customEvaluate,
  },
  { override: true }
);
```

**Comment by josdejong** [comment]
An expression like `[10, 20, 30] == 30` is evaluated element wise and returns `[0, 0, 1]` (I would expect it to return `[false, false, true]` but well).

I personally would prefer not to alter the `==` operator, but instead create a custom function `contains(a, b)` or something like that, but that is up to you. 

Please be careful with running a `.includes` or `.some` on the internal property like `._data`. This only works when you have a 1 dimensional matrix, but not for 2 dimensional or n-d matrices. A safer solution would be to either use the `.forEach` method on the Matrices and convert plain (nested) arrays to Matrix first, or first flatten the contents in a plain Array and then using `.includes`.
