### ISSUE TITLE
`gcd()` should accept array 

### ISSUE THREAD

**Issue by mattvague** [josdejong/mathjs#2567]
I would expect `math.gcd([1,2])` to work the same as `math.gcd(1,2)` however it currently throws "Too few arguments in function gcd (expected: number or BigNumber or Array or Matrix or Fraction or string or boolean, index: 1)"

**Comment by josdejong** [comment]
Yes I can imagine that. There are functions like `sum` and `prod` that accept both notations, but so far we only have that for functions that have a variable number of arguments, and not for functions that have a fixed number of 1 or 2 arguments (like `gcd`). I'm not sure if `math.gcd([1,2])` is a signature that we should add, I'm not sure if it really adds value. Do you have use cases for it?

**Comment by mattvague** [comment]
> for functions that have a fixed number of 1 or 2 arguments (like gcd).

gcd does seem to accept a variable number of args though

<img width="220" alt="image" src="https://user-images.githubusercontent.com/64985/169588338-6038b5fd-f96e-4172-a389-7f3d48c9a1b8.png">

If other fns do it it would be nice to be consistent

**Comment by mattvague** [comment]
>Do you have use cases for it?

I don't at the moment, I just noticed it didn't work while working on the chain types however I do think that it's best to be as forgiving about what kind of arguments are accepted as possible so that you get that "things just work" feeling

**Comment by josdejong** [comment]
Ahh, wait a second. I forgot that `gcd` also supports not only two but an variable number of arguments. Yes makes sense to me to add Array/Matrix support for `gcd` and `lcm` because of that.

I'm still a bit in doubt on whether it makes sense to add array support to say `xgcd(a, b)` which does accept only two arguments.

**Comment by mattvague** [comment]
>Ahh, wait a second. I forgot that gcd also supports not only two but an variable number of arguments. Yes makes sense to me to add Array/Matrix support for gcd and lcm because of that.

👍🏻 

> I'm still a bit in doubt on whether it makes sense to add array support to say xgcd(a, b) which does accept only two arguments.

Yes, I agree that if a function only takes 2 args then array support probably wouldn't make sense

**Comment by jakubriegel** [comment]
@MostafaEwis are still working on that? If not, then I'd like to take this as my first contribution here 🚀 
cc: @josdejong

**Comment by MostafaEwis** [comment]
@jakubriegel Hi Jakub. No, I'm no longer working on this issue, good luck in fixing it.

**Comment by josdejong** [comment]
Support for Array is published now in `v11.7.0`
