### ISSUE TITLE
.to is not a function 

### ISSUE THREAD

**Issue by jmichae3** [josdejong/mathjs#257]
please fix.
~~~
math.eval(WtCaster).to('oz').toString()
~~~

**Comment by josdejong** [comment]
@jmichae3 your expression `2 lbm/2 in*5 in` tries to divide and multiply units. This isn't yet supported, see #13. 

The parser thinks you are trying to convert units using the `in` operator and gives an error message "SyntaxError: Value expected (char 11)". If you evaluate `2 lbm/2 inch*5 inch`, the parser then gives a more useful error: "UnsupportedTypeError: Function multiply(unit, unit) not supported".

**Comment by josdejong** [comment]
I suppose this issue is resolved.
