### ISSUE TITLE
Returns wrong values

### ISSUE THREAD

**Issue by Rahuletto** [josdejong/mathjs#2570]
I have noted that mathjs is returning answers that are wrong and failed to return the expected result. Like for example, the true answer for cos(90 deg) is 0. But mathjs didn't return the expected result.

![Screenshot_2022-05-22-16-06-17-503_com.android.chrome.png](https://user-images.githubusercontent.com/71836991/169691507-04734280-7c48-4c3f-a893-c9a492e532a7.png)

**Comment by asmrcek** [comment]
You're right, it should be `0`, but computations involving floating point values are often not 100% precise, so the answer is actually correct because `6.123233995736766e-17` is practically `0`. Try formatting the number using ```(6.123233995736766e-17).toFixed(30)``` or verify by ```Math.acos(6.123233995736766e-17) / Math.PI * 180``` to see for yourself.

**Comment by Rahuletto** [comment]
I agree with you,  it cannot be 100% precise. javascript handles float values in a weird way.
