### ISSUE TITLE
Is possible to find Root of the functions

### ISSUE THREAD

**Issue by Aloento** [josdejong/mathjs#2574]
for example find the possible x for "2x + x = 0"

**Comment by josdejong** [comment]
That's not supported, though it would be awesome. I think this is a duplicate of #38. Are you thinking about a numerical solution or algebraic?

**Comment by Aloento** [comment]
the numerical solution is easier to solve with code I think.
x = 0

**Comment by josdejong** [comment]
The numerical solution is indeed the nicest. I doubt if it's the easiest though 😄 . Let's close this issue in favor of #38 and continue any discussion there.
