### ISSUE TITLE
FFT support for arbitrary size matrices

### ISSUE THREAD

**Issue by HanchaiN** [josdejong/mathjs#2577]
Currently, `math.fft` and `math.ifft` only deal with arrays with power-of-two size. However, there are other algorithms such as Bluestein's algorithm that work with the compound- and/or prime-sized arrays which will make evaluating the FFT on any data size.

_Originally posted by @HanchaiN in https://github.com/josdejong/mathjs/issues/46#issuecomment-1136624658_

**Comment by josdejong** [comment]
Thanks for opening this feature request 👍

**Comment by cyavictor88** [comment]
hello, I have implemented a Chirp-z Transform function inside [fft.js](https://github.com/cyavictor88/mathjs/blob/8a7aadf53fe073cf8fcf5169b916e2056dd9c19c/src/function/matrix/fft.js#L98) to calculate non-power-of-2 FFT.    I have also added test cases in [fft.test.js](https://github.com/cyavictor88/mathjs/blob/8a7aadf53fe073cf8fcf5169b916e2056dd9c19c/test/unit-tests/function/matrix/fft.test.js#L42)

I was able to run` npm run test` and `npm run build`. Do I just go ahead to create a pull request? thanks

**Comment by josdejong** [comment]
That sounds promising @cyavictor88 , thanks! Yes please open a PR with your implementation.

**Comment by josdejong** [comment]
Addressed via #2900.

**Comment by josdejong** [comment]
Published now in `v11.6.0`.
