### ISSUE TITLE
toTex for function extensions

### ISSUE THREAD

**Issue by Lakedaemon** [josdejong/mathjs#258]
Hello, for localization purposes (I'm french), I added two functions to math.js with
math.import({
        A: function (n,k) {return math.permutations(n,k);},
        C: function (n,k) {return math.combinations(n,k);}
});

yet, it looks like the nodes I get from the Parser have a wrong TeX representation.
math.parse('C(9,8)').compile(math).toTex() will return 
"C (9, 8)"  instead of "{9\choose 8}"

Is there a way to add a function to math.js AND to add a correct TeX representation forthis new function ?

**Comment by josdejong** [comment]
You could override the `toTex` function of the `FunctionNode`, and add cases for your function `C` (and the same for `A`):

```js
var FunctionNode = math.expression.node.FunctionNode;

// copy the original toTex function
FunctionNode.prototype._toTex = FunctionNode.prototype.toTex;

// create a new toTex function
FunctionNode.prototype.toTex = function () {
  if (this.name == 'C') {
    return '{' + this.args[0].toTex() + '\\choose ' + this.args[1].toTex() + '}';
  }
 
  // use the original toTex function
  return this._toTex(); 
}


```

**Comment by Lakedaemon** [comment]
Thanks, it works just fine. 

I noticed some issues with the toTex() method (mostly missing "()" ).

for example 
math.parse('mod(k,2) == 0 ? (pq)^(k/2-1) *(p^2+q^2) : (pq)^((k-1)/2)')

has not the same meaning than it's toTex() representation

it will probably be the same with math.parse('permutation(3*4)')

meaning = 12! rendered as TeX as 3 * 4!

The decision to put parenthesis around a group or not might be found with some analysys of the node tree

l

**Comment by josdejong** [comment]
Thanks, we should fix that

**Comment by josdejong** [comment]
Should be fixed now in the `develop` branch.
