### ISSUE TITLE
The decimal accuracy is still wrong

### ISSUE THREAD

**Issue by codepandy** [josdejong/mathjs#2602]
```
chain(20493.8).add(0.1).done();
```
![image](https://user-images.githubusercontent.com/16410281/174936698-c3f1e26e-0e9e-4eb0-bd78-870f18af5552.png)

**Comment by josdejong** [comment]
This is the most asked question. 

If you use regular numbers you just have the same accuracy as when doing `20493.8 + 0.1` right away.

See the documentation on round-off errors: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
