### ISSUE TITLE
onUndefinedSymbol  missing in TypeScript definitions

### ISSUE THREAD

**Issue by gopinav** [josdejong/mathjs#2603]
Hello, I'm trying to evaluate an expression whose scope might not contain all the necessary variables. I'd like to set null as the default value for such symbols or create a custom function that returns false if symbol does not exist.

`  console.log(math.evaluate("not c", { a: 5, b: 8 }));
`

Should return true (if possible)
I was digging up similar issues and made note of `onUndefinedFunction` and `onUndefinedSymbol` but couldn't find examples on how I can set this up once at the global level and not per node? Can someone please direct me to an example?

**Comment by josdejong** [comment]
You can use it like this:

```js
const { create, all } = import 'mathjs'

const math = create(all)

math.SymbolNode.onUndefinedSymbol = () => null

console.log(math.evaluate('nonExistingSymbol')) // null instead of an Error
```

However, the function `not` does not support `null` so that will throw an other error when you evaluate `not null`. Letting `onUndefinedSymbol ` return `0` will work.

**Comment by gopinav** [comment]
Thank you for the quick reply! I will try use false instead of null and give it a go

**Comment by gopinav** [comment]
Is this expected with TypeScript?
<img width="696" alt="image" src="https://user-images.githubusercontent.com/13146172/175027206-a6cb932b-7432-4fc9-8c11-a9e99b80bdf2.png">

**Comment by josdejong** [comment]
Ah, this property is missing in the TypeScript definitions apparently. I guess `onUndefinedFunction` probably has the same issue. 

Anyone able to create a PR fixing this?

**Comment by gopinav** [comment]
Thank you for the update. I do have a question which has to do with handling undefined symbols and short circuiting.
I want to return true based on the following condition:
if applicant count is greater than one and either 
1. applicant_two symbol is undefined or
2. applicant_two symbol is defined but first_name and sur_name on applicant_two object is empty string.

How would I go about writing the condition? Below is my current condition which throws the error pasted below.
`
"applicant_count > 1 and (not applicant_two or not applicant_two.first_name or not applicant_two.sur_name)"
`
<img width="401" alt="image" src="https://user-images.githubusercontent.com/13146172/175030449-0c51a1a7-2f87-4998-9496-1a5a8112138d.png">

**Comment by josdejong** [comment]
I think the underlying issues here are:

1. By default, an error is thrown on an undefined symbol (which you can solve with a custom `onUndefinedSymbol`)
2. Operator `or` (also `and`) should ideally evaluate lazily: do not evalulate the RHS when the LHS is already true. This is the case in many languages and is very handy. But right now `or` first evaluates both sides and then applies the `or` function. I remember there was a discussion on it for mathjs too but I can't find it.
3. Function `not` doesn't support `null` or `undefined`
4. Right now, trying to get the property of something that is not an object throws `'Error: No access to property "first_name"'`. It would be more clear if the error would explain that the property is _missing_, but most importantly, you would like to have a hook similar to `onUndefinedSymbol`, something like `onUndefinedProperty`, so you can control what happens in such a case.

I'm not sure there is a simple workaround for your case. I think you can look into preprocessing your expression, for example with a regular expression replacing the variables, or by parsing the expression and then transforming it (search `transform` on the page https://mathjs.org/docs/expressions/expression_trees.html)

**Comment by gopinav** [comment]
Thanks a bunch for your help mate! I'll see what is possible and revise my solution to have a scope that contains keys with empty values if possible in the worst case scenario.

**Comment by egziko** [comment]
@josdejong 
Take a look at #2610 to fix this
