### ISSUE TITLE
Improve TypeScript definitions of createUnit

### ISSUE THREAD

**Issue by egziko** [josdejong/mathjs#2607]
`createUnit` function can take as second parameter of type `Unit` but it's missing from type definition

![createUnit](https://user-images.githubusercontent.com/16388235/175826856-3f9d5650-5bbd-4163-863c-4d299a0b4573.png)

I'm using the example mentioned in the docs 
https://mathjs.org/examples/browser/currency_conversion.html.html

https://github.com/josdejong/mathjs/blob/b9586ab33d7cc0eef984b247a359e92772af720d/src/type/unit/Unit.js#L3133

**Comment by josdejong** [comment]
Thanks for reporting, you're right the type definitions of `math.unit` are incomplete.

Anyone able to help out and create a PR adding the options to the the definition?

**Comment by egziko** [comment]
@josdejong 
Check my PR #2609 to fix this
