### ISSUE TITLE
Cannot generate pi with precision >= 1015.

### ISSUE THREAD

**Issue by BigFav** [josdejong/mathjs#261]
I was working on optimizing pi for the small case, this was successful, however during my bounds testing I noticed that we cannot generate pi with this precision or higher as it exits with the error:
```
.../mathjs/node_modules/decimal.js/decimal.js:3090
            throw error;
                  ^
Error: ln() LN10 out of digits: 1027
    at ifExceptionsThrow (.../mathjs/node_modules/decimal.js/decimal.js:3079:25)
    at ln (.../mathjs/node_modules/decimal.js/decimal.js:3242:25)
    at Decimal.P.naturalLogarithm.P.ln (.../mathjs/node_modules/decimal.js/decimal.js:861:16)
    at module.exports (.../mathjs/lib/constants.js:27:45)
    at Object.math.config (.../mathjs/lib/math.js:69:29)
```

I believe this is also the limit of the size string you can use within a constructor.

**Comment by josdejong** [comment]
Yes, I encountered that myself too. This is some limitation in Decimal.js, where LN10 is defined as a string with 1025 digits: https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L47-L48

We could ask Michael whether he is interested in replacing this constant with a lazy evaluated and cached taylor series expansion of LN or LN10.

**Comment by BigFav** [comment]
I get why this happens, it just seems to contradict my previous understanding of the maximum precision which I thought was defined by `MAX_DIGITS = 1E9`.

**Comment by MikeMcl** [comment]
I tried calculating LN10 by Taylor series when I was developing the library, and it simply wasn't fast enough to be viable. I tried multiple different implementations and probably still have the code in the repo somewhere. 

Personally, I think you should set a limit on the precision available to using BigNumbers with math.js, and 1000 digits seems about right. I wouldn't expect many users to require more than that, and it is more or less the precision available from the decimal.js `pow`, `log`(http://mikemcl.github.io/decimal.js/#log) and `ln` methods if `LN10` is not extended. It would mean that performance remains reasonable, and would allow hard-coded constants to be used.

**Comment by josdejong** [comment]
Thanks for your thoughts on this matter Michael. Yes, it makes sense to stay pragmatic, having 99.99% of the users happy. But also, it would be so cool if we didn't have these limitations at al :). For some people it's just a sport to calculate pi with an insane amount of digits, just for the fun of it ;)

Just out of curiosity: how much time did it roughly took to generate LN10 with 1000 digits? Is it in the order of seconds, similar to calculating pi with a Taylor expansion?

**Comment by MikeMcl** [comment]
Found it.

```javascript 
var Decimal = require('./decimal.js');

/*
 * ln(10)
 * http://mathworld.wolfram.com/NaturalLogarithmof10.html
 * BBP-style formula 3
 *
 * ln(10) = 0.5 * Sum[ (6/4k+1 - 3/4k+3 - 1/4k+4) / (-4)^k ]   (k = 0, 1, 2, 3,...)
 */
function ln10() {
  var next;
  var k4 = 0;
  var denom = Decimal.ONE;
  var minusFour = new Decimal(-4);
  var sd = Decimal['precision'] += 4;
  var six = new Decimal(6);
  var sum = new Decimal(0);
  var three = new Decimal(3);

  for(;;) {
    next = sum.plus(
      six.div(k4 + 1).
      minus(three.div(k4 + 3)).
      minus(Decimal.ONE.div(k4 + 4)).
      div(denom)
    );

    if (next['c'].slice(0, sd).join('') === sum['c'].slice(0, sd).join('')) {
      break;
    }

    sum = next;
    k4 += 4;
    denom = denom.times(minusFour);
  }

  //console.log('Number of terms in the summation: ' + (k4 / 4));
  return sum.times(0.5).toSD(Decimal.precision -= 4);
};

Decimal.precision = 100;
var start = new Date;
var n = ln10();
var end = new Date;

console.log(n.toString());
console.log('Time taken: ' + ((end - start) / 1000) + ' secs');

// 100 digits:  0.015 secs
// 500 digits:  0.171 secs
// 1000 digits: 0.765 secs
// 5000 digits: 65.629 secs
```

**Comment by josdejong** [comment]
A nice, that is not bad at all! Indeed up to 1000 digits is feasible, and above that is still useful but only for very special (scientific?) cases when speed is no issue. Note that this holds for both one-time generation of constants as well as doing actual calculations with functions like `ln`, `exp`, etc.

This means that the initial calculation of `LN10` is in the same order of magnitude as any calculations you are going to do with it. If we would lazy-load all these constants, you would hardly notice in practice. For example calculating `ln(2)` with 1000 digits takes 1.2 seconds right now, that would be 2 sec the first time if lazy loading `LN10` and 1.2 sec on consecutive usage. Not that big of a problem I think. And of course this scenario *is* already exceptional, normally you have more than enough with say 20 or 64 digits.

We can lazy load constants using [Object.defineProperty](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty) if available in the browser and initialize a constant on the first `get`. We can fall back on direct loading if not supported by the browser.

I think this is actually very acceptable, and it would remove the 1000 digit limit.

**Comment by BigFav** [comment]
To save time @MikeMcl I would suggest skimming #262, as there may be a similar conversation arc lol.

**Comment by BigFav** [comment]
Is this solved now?

**Comment by MikeMcl** [comment]
Well, I don't want to replace the `LN10` constant in decimal.js itself.

I assume it is the `pow` operations in your pi calculation that are causing the issue with `LN10`. One option is to increase the value of the [`INT_POW_LIMIT`](https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L45) variable in decimal.js, so `pow` uses the 'exponentiation by
squaring' algorithm instead of `exp(y*ln(x))`.

(I should be more explicit in the documentation about the precision limit of the `pow` method, like I was for [`ln`](http://mikemcl.github.io/decimal.js/#ln), but the limit can be adjusted for integer exponents as just described.)

Another option is to use something like the following, which is adapted from the code linked to at https://github.com/MikeMcl/decimal.js/issues/9. It would have the advantage of being much faster, at the cost of more code

```javascript
// http://www.trans4mind.com/personal_development/JavaScript/longnumPiMachin.htm 
var Decimal = require('./decimal.js');

var pi = (function () {
  // Math.floor(Math.log(Base) / Math.LN10)
  // 9 is the fastest, 7 is faster than the maximum, 11.
  var digitsPerWord = 9;    
  var Base = Math.pow(10, digitsPerWord);

  // Add in-place.
  function Add(n, aX, aY) {
    var carry = 0;
    for (; n--; ) {
      aX[n] = aX[n] + aY[n] + carry;
      if (aX[n] < Base) {
        carry = 0;
      } else {
        carry = 1;
        aX[n] -= Base;
      }
    }
  }

  // Subtract in-place.
  function Sub(n, aX, aY) {
    for (; --n; ) {
      aX[n] -= aY[n];
      if (aX[n] < 0) {
        aX[n] += Base;
        aX[n - 1]--;
      }
    }
    aX[n] -= aY[n];
  }

  // Multiply by 'small' number in-place.
  function Mul(n, aX, iMult) {
    var prod;
    var carry = 0;
    for (; n--; ) {
      prod = aX[n] * iMult + carry;
      if (prod < Base) {
        carry = 0;
      } else {
        carry = Math.floor(prod / Base);
        prod -= (carry * Base);
      }
      aX[n] = prod;
    }
  }

  // Divide by 'small' number.
  function divSmall(n, aX, iDiv, aY) {
    var currVal, theDiv;
    var carry = 0;
    var i = 0;
    for (; i < n; i++) {
      currVal = aX[i] + carry * Base;
      theDiv = Math.floor(currVal / iDiv);
      carry = currVal - theDiv * iDiv;
      aY[i] = theDiv;
    }
  }

  function arctan(iAng, n, aX, aAngle, aDivK) {
    var i = 1;
    var iAng_squared = iAng * iAng;
    var k = 3;
    var sign = 0;
    for (aAngle[0] = 1; i < n; aAngle[i++] = 0);
    // aAngle = 1 / iAng
    divSmall(n, aAngle, iAng, aAngle);
    Add(n, aX, aAngle);
    do {
      // aAngle = aAngle / iAng_squared
      divSmall(n, aAngle, iAng_squared, aAngle);
      // aDivK = aAngle / k
      divSmall(n, aAngle, k, aDivK);
      // aX = aX + aDivK
      if (sign) Add(n, aX, aDivK);
      // aX = aX - aDivK
      else Sub(n, aX, aDivK);
      k += 2;
      sign = 1 - sign;
      for (i = 0; aAngle[i] === 0; i++);
    } while (i < n);
  }

  return function (precision) {
    var dPI, sPI, s, z;
    var guardDigits = 5;
    if (!(precision > 0)) precision = Decimal.precision;
    precision += guardDigits;
    var len = Math.ceil(precision / digitsPerWord + 1);
    var aAngle = new Array(len);
    var aArctan = new Array(len);
    var aDivK = new Array(len);
    var aPI = new Array(len);
    var i = 0;
    for (; i < len; i++) {
      aPI[i] = aArctan[i] = aDivK[i] = 0;
    }

    // Machin: Pi / 4 = 4 * arctan(1 / 5) - arctan(1 / 239)
    arctan(5, len, aPI, aAngle, aDivK);
    Mul(len, aPI, 4);
    arctan(239, len, aArctan, aAngle, aDivK);
    Sub(len, aPI, aArctan);
    Mul(len, aPI, 4);

    // Convert to Decimal.
    // I.e. convert the array of base Base words to the base 10^7 words used by a Decimal's coefficient array.
    dPI = new Decimal(3);
    sPI = aPI[0] + '';
    for (i = 1; i < len; sPI += s) {
      for (z = digitsPerWord - (s = aPI[i++] + '').length; z--; s = '0' + s);
    }
    sPI = sPI.slice(0, precision -= guardDigits);
    precision = Math.max(precision - 7, 1);
    for (i = 1, aPI = dPI.c; i < precision; aPI.push(+sPI.slice(i, i += 7)));
    for (s = sPI.slice(i), i = 7 - s.length; i--; s += '0');
    aPI.push(+s);

    return dPI;
  }
})();

Decimal.precision = 100;

var start = Date.now();
var n = pi(1000);
var end = Date.now();
console.log('Time taken: ' + ((end - start) / 1000) + ' secs');
console.log(n.toString());
// Tested and correct: 10000, 20000, 50000, 100000, 200000 digits.
// 1000 in 7 ms, 16500 digits in one sec.
```

**Comment by BigFav** [comment]
Oh I only asked because the precision seems more flexible now.

**Comment by josdejong** [comment]
@MikeMcl thanks for your feedback and suggestion for `pi`. My personal choice would be to go for the unlimited solution, but I can understand that you want to keep LN10 like it is now, i.e. limit decimal.js to the practical limit of ~1000 digits. 

@BigFav I think we have two options here:
- Go for the unlimited solution anyway. That would require us to fork decimal.js and adjust the `LN10` related stuff (and maintain the clone henceforth).
- Go the easy way and accept the ~1000 digit limitation of LN10 in decimal.js, and apply this same limit to all constants in math.js to be consistent.

I think at this point we should be pragmatic. So shall we just accept the ~1000 digit limitation of decimal.js? In that case we can just implement a hardcoded `pi` string with ~1000 digits, and the same with the other constants. And we can throw away all fancy lazy loading and memoize stuff :D.

If it turns out that many people actually want a higher precision of these constants we can always rethink this limitation.

**Comment by MikeMcl** [comment]
Even if ln10 was generated at runtime to a higher precision, it is not viable to use decimal.js to calculate constants such as pi to over 1000 digits using Taylor series and such like. 

It is surely better to use bespoke implementations like the example I gave above to calculate the constants - the performance is so much better - and then simply pass the result as a string to the Decimal constructor. The same applies to implementing the trigonometric functions.

**Comment by BigFav** [comment]
The original problem was that I was having trouble creating bignumbers with high precision, and this particular error just happened to appear when I was making pi.

By the way, the pi implementation is just a few [divides and multiplications](https://github.com/josdejong/mathjs/blob/develop/lib/util/bignumber.js#L51-L61), nothing complicated.

This does not happen anymore for me, so I think this should be closed unless this still happens for you @josdejong.

**Comment by josdejong** [comment]
> This does not happen anymore for me

He, you are right! What did resolve it? (I mean `pi` still uses the same algorithm).  I also see the constant `e` just works with >1000 precision, whilst I had wrongly assumed that `exp` was limited to 1000 digits too. Looking at the code of decimal.js, only `ln`, `log`, and `pow` use the constant `LN10`. 

Sorry I was still in the supposition that both `pi` and `e` where limited :Embarrassed:

Ok then lets close this issue and leave everything as it is right now. Almost everything supports unlimited precision, only `log`, `log10`, and `pow` are limited. We can have a closer look at that some day if there are reasons to.

Improving further upon the performance of all related functions stays interesting of course, we can have a look at the code Michael posted in this thread (I guess the [original source is here](http://www.trans4mind.com/personal_development/JavaScript/longnumPiMachin.htm)) and see whether that would be worth the extra code.
