### ISSUE TITLE
Please document `.get` and `.set` in examples

### ISSUE THREAD

**Issue by rrthomas** [josdejong/mathjs#2613]
The matrices documentation gives this example:

```
math.subset(a, math.index(1))                 // 1
```

but not the simpler

```
a.get([1])
```

When a number is required in TypeScript, the use of `.get` seems to be mandatory, as `math.subset` returns a `Matrix`.

It would be great if the `get` (and `set`) methods were documented in the main [Matrices](https://mathjs.org/docs/datatypes/matrices.html) page, and not just in the API reference (I eventually found them with a Google search).

Thanks for mathjs!

**Comment by josdejong** [comment]
Thanks. Good point. I mostly use the expression parser, where manipulating matrices is much easier, there the syntax is `a[1]` 😁 

I've documented the methods now, see https://github.com/josdejong/mathjs/commit/f9b944acfeb6382a5634035efb8af6f4807154c9

**Comment by rrthomas** [comment]
Many thanks!
