### ISSUE TITLE
get paths of scope expression depends on

### ISSUE THREAD

**Issue by natarius** [josdejong/mathjs#2619]
Hi there, I need to figure out a programmatic way to identify the scope objects an expression depends on

So given a expression "12 + x * y.input - z.deepNest.someFunction(33)" returns and array or so like this:

`["x", "y.input", "z.deepNest.someFunction"]`

What's the best way to do that?

**Comment by josdejong** [comment]
Depending on how simple your use case is, the easiest may be with some regular expressions.

An other solution is to parse your expression with `math.parse('12 + x * y.input - z.deepNest.someFunction(33)')`. Then you can iterate over the parsed expression tree using methods like `traverse` and `forEach`. You'll have to collect nodes of type `SymbolNode`, `AccessorNode`, `IndexNode`, `FunctionNode`.

See docs: https://mathjs.org/docs/expressions/expression_trees.html

**Comment by natarius** [comment]
Thanks for getting back

I have been playing around with math.parse

one issue I am running into is that unit postfixes like "k" in "12k" are also of type SymbolNode...any idea on how to ignore those?

**Comment by josdejong** [comment]
`12k` is parsed as an implicit multiplication: `12 * k`

**Comment by josdejong** [comment]
Implicit multiplication is indeed an `OperatorNode` with `op`  equal to `'*'`, and a flag `implicit` equal to `true`.

You'll need some time indeed to get familiar with the structures that the parser can return (the docs show you all the different node types that can be returned).

**Comment by natarius** [comment]
Perfect!

`parent.isOperatorNode && parent.op === "*" && parent.implicit === true`
 
This did the trick!

thanks!

**Comment by josdejong** [comment]
👍

**Comment by dspasojevic** [comment]
Sorry to comment on a closed issue.

Further to the above, I'm wondering if there is a way to know whether a `FunctionNode` will be satisfied during evaluation by a built-in function rather than by a user-defined function?

e.g.  given `foo(bar + sqrt(baz))`, is it possible to tell that `foo` must be supplied during evaluation but `sqrt` need not?

**Comment by josdejong** [comment]
@dspasojevic you can check whether `math['foo']` is defined and a function.
