### ISSUE TITLE
Math.round and toFixed methods not using scientific rounding

### ISSUE THREAD

**Issue by KevBeltrao** [josdejong/mathjs#2620]
I'd like to know if there's a reason why scientific rounding (even-odd rule) is not used when rounding numbers in JavaScript.

The rule specifies that if the digit being rounded is exactly 5, the decision if the value should be rounded up or down is if the digit before is even (floor) or odd (ceil). Instead, it's always rounded up.

So for example:
2.5 rounded should be 2
1.5 rounded should also be 2

and of course, 2.499 should round to 2 and 2.501 to 3.

Here's showing the the different behaviors when running in Node.js 16.15.1 and in Python 3.9.13
<img width="114" alt="image" src="https://user-images.githubusercontent.com/43002117/178138530-51bf39f5-2e47-4f66-ac92-926fd28fcb14.png">
<img width="107" alt="image" src="https://user-images.githubusercontent.com/43002117/178138541-b1a4cc61-33ec-4ef1-93b8-205e2b71180d.png">

If the suggestion above is accepted, I'd be happy to get that assigned to me.

**Comment by josdejong** [comment]
> I'd like to know if there's a reason why scientific rounding (even-odd rule) is not used when rounding numbers in JavaScript.

mathjs rounds towards nearest neighbour, and if equidistant, rounds away from zero. There is simply a handful of different ways that you could use to round numbers, and what rule is "best" and "logic" depends on your use case.

Please note that in your screenshot you're showing how JavaScript itself rounds numbers, you're not showing the behavior of mathjs.

mathjs does not have configurable rounding. for Numbers, mathjs uses the `decimal.js` library. This library does have configurable rounding modes, see docs: https://mikemcl.github.io/decimal.js/#modes

**Comment by josdejong** [comment]
Closing this issue now, please reopen if there are still things to be discussed.
