### ISSUE TITLE
Correlation function

### ISSUE THREAD

**Issue by dudeseriously** [josdejong/mathjs#2624]
It would be great to have a correlation function especially since we already have some of the sub-calculations (average and standard deviation). 

I suppose, one method may be to create a covariance function and combine it with the sub-calculations above, especially as we already have a variance function in the library?

**Comment by josdejong** [comment]
Thanks for your suggestion. 

Anyone interested in thinking through a proper API and implement this? Help would be welcome

**Comment by josdejong** [comment]
Implemented via #3015, published now in `mathjs@11.11.0`.
