### ISSUE TITLE
Need more matlab like feature

### ISSUE THREAD

**Issue by newebug** [josdejong/mathjs#263]
mathjs is the best js math library, it could be better with more matlab like matrix methods such as repmat, sqrtm, etc.

Do you have some plan to implement these?

**Comment by josdejong** [comment]
Thanks! Yes, we definitely want more advanced mathematical methods. This is on the to do list for sure. Contributions are welcome.

I would love to incorporate a lot of the functions available in for example [numeric.js](http://www.numericjs.com/documentation.html).

**Comment by ferrolho** [comment]
I stumbled upon this issue when I was trying to compute the *principal square root* of a matrix. MATLAB implements this as [`sqrtm`](https://uk.mathworks.com/help/matlab/ref/sqrtm.html). I ended up implementing the [Babylonian iterative method](https://en.wikipedia.org/wiki/Square_root_of_a_matrix#By_the_Babylonian_method) as shown below:

```javascript
sqrtm (A, iterations = 10) {
    // Square root of a matrix by the Babylonian method
    let X = math.eye(math.size(A))
    for (let i = 0; i < iterations; i++) { X = math.multiply(0.5, math.add(X, math.divide(A, X))) }
    return X
}
```

Should I open a PR?

**Comment by newebug** [comment]
May be Python scipy like api more popular.

**Comment by ferrolho** [comment]
@josdejong would you like me to create a PR with a SciPy-like implementation?

**Comment by newebug** [comment]
Welcome, SciJs  :)
