### ISSUE TITLE
v11 typings issue.

### ISSUE THREAD

**Issue by imranbarbhuiya** [josdejong/mathjs#2632]
mathjs v11 has some typing issues because of which, I'm not able to build my package without adding `skipLibCheck`.

![image](https://user-images.githubusercontent.com/74945038/180632068-9dcee04c-768d-46a8-8df1-c00bfa90a32b.png)

**Comment by josdejong** [comment]
Thanks for reporting, this issue has been fixed now in v11.0.1.

I've opened a separate issue to address the problem that these issues do not yet pop up when running the tests.
