### ISSUE TITLE
Feature request: make `evaluate` accept multiple scopes

### ISSUE THREAD

**Issue by UlyssesZh** [josdejong/mathjs#2637]
Imagine the following scene (that I actually meet with):
There are many ($\sim10^3$) different math expressions, each of which has its own scope that is different from each other. All of the expressions are independently evaluated frequently. All of the scopes share a same part (let's call it `environment`), and `environment` needs rather frequently updating. If `evaluate` does not accept multiple scopes, every time `environment` gets updating, the program should patch the updates to all of the scopes that share `environment`, which is a very heavy burden on performance. However, if `evaluate` accepts multiple scopes, it can just accept `environment` as one of its scopes, and no patching is needed.

**Comment by josdejong** [comment]
That is an interesting case indeed.

You can implement a solution yourself: the scope can be a `Map` or any object that implements the interface of a `Map`: it must have methods `get`, `set`, `keys`, and `has`. So, you can implement the `get`, `has`, and `keys` methods to iterate over all your scopes, and do something smart with `set` (depending on what you want there).

See documentation: https://mathjs.org/docs/expressions/parsing.html#scope
