### ISSUE TITLE
Error on documentation for indexing

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#2639]
Hello, while typing `help(index)` there is one example that generates an error.
https://github.com/josdejong/mathjs/blob/47a493d70ac92daa47b26f9eea88513a7efa4408/src/expression/embeddedDocs/construction/index.js#L20

` A[0:2, 0:2] = ones(2, 2)`
> DimensionError: Dimension mismatch ([3, 3] > [2, 2])

Probably due to the index zero but could be easily fixed by changing 0 to 1
```py
A[1:2, 1:2] = ones(2, 2)
```
This fixes the error

**Comment by josdejong** [comment]
Thanks for pointing this out David, I've fixed the example.

**Comment by dvd101x** [comment]
Thank you, Jos!, I just found there is also an example with an empty array
`'[]',`
I don't know if it is as intended

**Comment by josdejong** [comment]
Yes, it's not very useful indeed, I'll remove it. Thanks
