### ISSUE TITLE
Feature request: substitute some but not all variables in a compiled expression to return a new compiled expression

### ISSUE THREAD

**Issue by UlyssesZh** [josdejong/mathjs#2640]
Sometimes I need to apply some of the variables to an expression because the values of these variables will have been changed when the values of the other variables are available. However, I cannot do this, so I have to copy the whole scope to store the values (because I cannot see what variables are utilized in this expression) to utilize them in the future. This is a large burden on performance because the whole scope is much larger than the actual variables used in the expression.

**Comment by josdejong** [comment]
If I understand you correctly, I think you can go two directions:

1. As scope, pass an object with a `Map` interface that allows you to determine what variable to resolve, like I explained in #2637
2. Transform the expression using `node.transform(...)` and resolve specific SymbolNodes with ConstantNodes there, see https://mathjs.org/docs/expressions/expression_trees.html

**Comment by UlyssesZh** [comment]
> As scope, pass an object with a `Map` interface that allows you to determine what variable to resolve, like I explained in #2637

This is not feasible, either, because it still requires copying the whole scope (because I cannot know what variables are used in the expression at this stage).

I'd look into the second means.

**Comment by josdejong** [comment]
I do not know enough of your case to fully understand it, but just want to stress that a custom Map-like scope object does NOT require copying the whole scope, only looking up various scopes or whatever you like. It's just a getter that you can give custom behavior.

**Comment by UlyssesZh** [comment]
I mean the variables in the scope are mutable, but the values that I want to use are those in the past (which may have been changed now when the expressions are actually evaluated). No matter how I look up these values, I have to store the values somewhere else from the original scope to prevent them from being changed. Because I do not know what variables should be stored, I have to store all the variables, which means copying the whole scope.
(I'm just explaining why a custom `Map` inplementation is not useful in this case. Your second suggestion about using `node.transform` is exactly the thing I need, so thank you anyway!)

**Comment by josdejong** [comment]
So... wouldn't it work to have your Map-like scope read from two scope objects, say `updatedScope` and `originalScope`, and have it write only to `updatedScope` so the `originalScope` is not changed?

**Comment by UlyssesZh** [comment]
Imagine that: the scope gets updating very frequently, and many different expressions enter at different stages of updating. In this case, maintaining only two scopes is far not enough. The number of "original scopes" I have to maintain is the number of different stages where there enter new expressions, each of which is created by copying the whole scope.

**Comment by josdejong** [comment]
Ok that sounds like a nice challenge. I leave it up to you now. What I hope is that you understand the possibilities of creating a Map-like scope object. It gives a lot of power and control, you can orchestrate how to read/write variables from whatever source. It may be useful for your case.

**Comment by gwhitney** [comment]
Not 100% certain based on the description in your original posting of the issue, but is `math.resolve(expr, scope)` (https://mathjs.org/docs/reference/functions/resolve.html) helpful for you? It seems to match the operation you were describing fairly closely...

**Comment by UlyssesZh** [comment]
> is `math.resolve(expr, scope)` (https://mathjs.org/docs/reference/functions/resolve.html) helpful for you?
Oh, yes! It is what I'm looking for.
