### ISSUE TITLE
Bug: `math.range` is different from `range` used in `math.evaluated`

### ISSUE THREAD

**Issue by UlyssesZh** [josdejong/mathjs#2641]
```js
math.evaluate('range(0,3)').toString() // => '[0, 1, 2, 3]'
math.range(0,3).toString()             // => '[0, 1, 2]'
```
but I didn't expect them to be different.

**Comment by josdejong** [comment]
It can be confusing indeed, the JavaScript API differs from the expression parser API. 

See docs for more explanation: https://mathjs.org/docs/expressions/syntax.html#differences-from-javascript
