### ISSUE TITLE
Add `subtractScalar`

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#2643]
Right now, there's no `subtractScalar` method and `subtract` has `matrix` as a dependency. This way, it's impossible to make a custom bundle which only contains units and not matrices (which increase the bundle size quite significantly), as `Unit` depends on `subtract` and `matrix`.

**Comment by gwhitney** [comment]
You mean to say "...no `subtractScalar` method and `subtract` has `matrix` as a dependency..." (`subtract`, not `scalar`), correct?

**Comment by m93a** [comment]
Of course! My bad, sorry :)

**Comment by gwhitney** [comment]
Excellent point and thanks for the issue report. This issue would be moot with either a TypeScript rewrite of math.js if that's feasible somehow, or a reorganization along the lines of #1975, so in the meantime although I'd be happy to review a PR for it, I at least will be unlike to generate one...

**Comment by josdejong** [comment]
Thanks for bringing this up, I agree that we should extract a `subtractScalar` function just like we have `addScalar`, `multiplyScalar`, and `divideScalar`.

**Comment by RenelJean** [comment]
I would love to look into this, where can I locate the subtractScalar function? so I can extract it like the other functions.

**Comment by gwhitney** [comment]
Well, the point is there currently is no subtractScalar function. The idea of the solution proposed here is to refactor the existing subtract function along the lines that add is currently factored, with an addScalar that can be separately bundled.

**Comment by josdejong** [comment]
Implemented now via #3018 and published in `v11.12.0`.
