### ISSUE TITLE
Unclear documentation for calling functions with fractions

### ISSUE THREAD

**Issue by wouterbeek** [josdejong/mathjs#2645]
The documentation on <https://mathjs.org/docs/datatypes/fractions.html> states that "[m]ost functions will determine the type of output from the type of input: [...], a Fraction as input returns a Fraction as output".

I specifically cannot get this to work for fractions.  For me, every function that takes only `Fraction` parameters returns an object of type `MathType`.  This object cannot be stored in a `Fraction` object without an explicit cast (one per function call) and it cannot be returned by a function that has return type `Fraction`.

Could the documentation be wrong here?  It is required to do an explicit cast after every function call involving fractions?

Here is my example code:

```ts
import { all, ConfigOptions, create, Fraction } from 'mathjs'
const config: ConfigOptions = {
  number: 'Fraction',
}
const math = create(all, config)

async function run() {
  const a: Fraction = math.fraction(1)
  const b: Fraction = math.fraction(60)
  const c: Fraction = math.divide(a, b) // <--- wrong type, returns 'MathType'
}
```

**Comment by josdejong** [comment]
I think you're hitting the issue that the TypeScript definitions are not up to date for `Fraction` for many functions, see https://github.com/josdejong/mathjs/issues/2582#issuecomment-1141903710

**Comment by wouterbeek** [comment]
Ah, that's too bad.  I'm closing this issue since it is a duplicate.

**Comment by josdejong** [comment]
👍
