### ISSUE TITLE
Using sorting algorithms depending on data size

### ISSUE THREAD

**Issue by zhak55** [josdejong/mathjs#268]
I saw in your source that it is used native method <.sort> to sort an array (e.g. for [Link 1](https://github.com/josdejong/mathjs/blob/master/dist/math.js#L16054) )

By the example of [mode](http://en.wikipedia.org/wiki/Mode_(statistics)) I suppose it is good to use native method for big data ( more than 100 000 elements in array but less than 200 000 )

But if in an array less than 10 000 elements it is better to use Insertion sort and if you use really big array - more than  150 000 - 200 000 elements - you can use heap sorting 

Here I've made some test: [Link 2](http://jsperf.com/343233342x/2)

You can see if your array contains 10000 elements the fastest is insertion sort, if it is about 100 000 - there is mo difference between native sort method and heap - both are the fastest. 
And if you make test with array that contains 250000 elems - that fastest is heap;

Here I realize all algorithms that is used for testing : [Link 3](https://github.com/zhak55/algorithms)

It is good idea to use sort algorithms depending on the data size;

**Comment by josdejong** [comment]
Thanks, interesting idea. Besides `sort`, there may be more native JavaScript functions which can be replaced by faster implementations, like [fast.js](https://github.com/codemix/fast.js) does for example.

**Comment by devanp92** [comment]
@josdejong in the sort method, should we check to see if the array is greater than 100,000 elements and if so, use fast.js?

**Comment by josdejong** [comment]
Before we do these sorts of optimizations, I would fist like to see benchmarks. I think its best to first check whether a non-native or hybrid solution *significantly* improves performance and if so, in which cases (large/small data sets), and if this holds for all browsers. If we have this knowledge, we can see if it's worth it and decide what to do.
