### ISSUE TITLE
Easier Way To Work With Vanilla JS Arrays

### ISSUE THREAD

**Issue by fweth** [josdejong/mathjs#2685]
Hi, I think for better interoperability with vanilla JS, it would be cool if `range` returned a vanilla JS array, this is one of the features I heavily miss in JS.  I know that I can always access the `_data` property, but that feels a bit dirty.

For example, I'd like to get a list of pairs `[i, j]` with `i` and `j` ranging from `-1` to `1`.  Here is what I'd like to do:

```js
const coords = math.map(math.range(-1, 1, true), function(i) {
  return math.map(math.range(-1, 1, true), function(j) {
    return [i, j];
  }
}).flat();
```

What it currently looks like (and I think this is suboptimal):

```js
const coords = math.map(math.range(-1, 1, true)._data, function(i) {
  return math.map(math.range(-1, 1, true)._data, function(j) {
    return [i, j];
  }
}).flat();
```

If all vanilla JS array methods, like `flat`, `sort`, etc. would be implemented in Math.js, then it wouldn't be a problem, but I think it make more sense to use what JS already implements and integrate it better with Math.js.

**Comment by josdejong** [comment]
You can configure whether you want a Matrix or an Array back, with the config option `math.config({matrix: 'Matrix' | 'Array' })`.

Please do not use the internal `._data` property, it is safer to use a public method like `.toArray()`

**Comment by fweth** [comment]
Thank you so much!  `.toArray()` was what I was looking for.
