### ISSUE TITLE
json serialization formats for Complex, Matrix, etc

### ISSUE THREAD

**Issue by garrison** [josdejong/mathjs#27]
This may very well be beyond the scope of this project, but I bring it up here because you may be interested or have valuable feedback to give.

It would be very nice if there were a way to serialize e.g. a mathjs Matrix of complex numbers into json, and then unserialize it.  This would allow for e.g. communication of a matrix in its entirety between a server running nodejs and a client.

This would require a custom method of serializing these types into json objects, but that should not be difficult.  The harder thing is to settle on such a method.  I've looked a bit into how others have handled this and have found very little.  The Python documentation, for instance, defines [custom json encoders and decoders for complex numbers](http://docs.python.org/3/library/json.html), but it does not even use the same format for encoding and decoding!  So it seems to be purely a hypothetical example, and not an actual example meant to be used.

One way of storing a complex number could be something like

    {
        "mathjson": "complex",
        "real": 3,
        "imag": 4
    }

A matrix could then be stored like

    {
        "mathjson": "matrix",
        "data": [[1, 2], [3, 4]]
    }

A mathjs function could then exist that takes a decoded json object and recursively turns it and its referenced objects into their corresponding mathjs objects by searching each object for a "mathjson" field.

Thoughts?

**Comment by josdejong** [comment]
It has been a while ago, but I've finally implemented serialization and deserialization using `JSON.stringify` and `JSON.parse`. You can try it out in the `develop` branch. See [docs](https://github.com/josdejong/mathjs/blob/develop/docs/serialization.md) and [example](https://github.com/josdejong/mathjs/blob/develop/examples/serialization.js). 

Feedback is welcome.

**Comment by garrison** [comment]
Wow, this is cool.  I like the looks of this.  I've only looked at the docs and example but am curious: does it also work for matrices?

**Comment by josdejong** [comment]
When implementing this I was actually *very* happily surprised by how easy this is using the build-in `JSON.stringify` and `JSON.parse`, thanks to the optional `replace` and `revive` functions you pointed me to. These two are really brilliant. The `replace` function wasn't even needed in the end because you can implement `toJSON` functions on the concerning data types.

Serialization works for every data type of math.js, also for `Matrix`, which will serialize as `'{"mathjs":"Matrix","data":[...]}'`.

btw thanks again for your tip not to use a field like `_type` to store type information. I had used `@type` at first (like [JSON-LD](http://json-ld.org/)) but changed it to a safer, collision free `'mathjs'` in the end.

**Comment by josdejong** [comment]
Serialization is now available in v1.4.0

docs: http://mathjs.org/docs/serialization.html
example: http://mathjs.org/examples/serialization.js.html

**Comment by garrison** [comment]
Excellent!

**Comment by skgadi** [comment]
Hi,
This (reviver in JSON.parse) is very helpful. But, I am not sure how to deal with Infinity. At present, I am loosing its information. Here is an example:

`var a="[1,2i,1/0]";`
`var b=math.evaluate(a);`
`var c = JSON.stringify(b);`
`var d = JSON.parse(c,  math.json.reviver);`

By the time I reach last step, the variable `d` is losing its Infinity value.

How can I fix this problem?

Thank you for your time.

**Comment by josdejong** [comment]
Thanks for reporting @skgadi , that's a very good point. I've opened a separate issue to address this: #1840.
