### ISSUE TITLE
toTex removing important parenthesis

### ISSUE THREAD

**Issue by shashankkundu** [josdejong/mathjs#273]
Hello, 
I tried math.parse to get the correct latex form for some Math questions we were providing to students. Found this bug there..
math.parse('3^2-(1-(-11/2))').toTex() returns:  {{3}^{2}}-{{1}-{\frac{-11}{2}}} 
which is then displayed by popular latex editors (MathJax and MathQuill) as something that means  3^2-1-(-11/2) (image below for reference)
![image](https://cloud.githubusercontent.com/assets/10861085/6055825/2800a3d2-ad2d-11e4-9975-42ffcd22cf7e.png)

Not sure if the bug is in the toTex function or the parsing/displaying function of these editors. The parenthesis should ideally remain if preceeded by an operatorNode and followed by an expression (with atleast one operatorNode) till the closing parenthesis is detected. 

I see that the toTex function is placing braces here, but most editors ignore the braces unless they belong to functions or the ^ operator. 

I then tried this:   math.parse('3^2-(1-((-11x+2)/2))').toTex()
and got: "{{3}^{2}}-{{1}-{\frac{{\left({-11}\right) \, {x}}+{2}}{2}}}"
and am not sure why the parenthesis were added here around -11..

**Comment by josdejong** [comment]
Thanks, we should fix that. This issue is located in the `toTex` code (`toString` works fine, `math.parse('2-(3-4)').toString()` returns `"2 - (3 - 4)"`).

**Comment by FSMaxB** [comment]
I just took a look at the code and from how I understand it this related to the function `OperatorNode.prototype.toTex` in `lib/expressions/node/OperatorNode.js` not handling `+` and `-` in the switch-case statement that get's executed when there are 2 arguments. There should probably be cases for both operators that set `lhb` and `rhb` to true under certain conditions, is this correct? ( This is actually the first time that I looked at the code of math.js )

**Comment by josdejong** [comment]
Thanks for your reply. The `toTex` support wasn't written by me, and I haven't yet had a look at where this bug of missing parenthesis is originating. The `toTex` code works very nicely (this #273 is the first bug related to the `toTex` functionallity if I remember it well),  though code can use some refinement and simplification. I would like to see it with less indirections (closer to the current `toString` code).

**Comment by FSMaxB** [comment]
I just noticed that this is a much bigger problem than it looked at first. My commit isn't a complete fix yet, there is at least one other case that isn't handled properly by OperatorNode.js, see `-(a+b)`.

**Comment by FSMaxB** [comment]
I really wonder why no one noticed this because this is very fundamental and anyone actually using it should have stumbled across it. The most obvious mistakes should be fixed but who knows what else might be broken.

**Comment by josdejong** [comment]
I suppose a generic solution would have a list with all operators ordered by their precedence. The operators should then add parenthesis to their lhs or rhs when it is an operator with lower precedence. Note that we have to improve this for `toString` too: `toString` is overly enthusiastic with adding parenthesis.

I expect be able to take a closer look at this coming weekend.

**Comment by FSMaxB** [comment]
I looked at the current parser code but I didn't really understand how it works ( and how it deals with operator precedence ). Is there a way to somehow query the precedence of an operator ( or at least compare it's precedence to another one )? In my understanding this would be essential to do a proper implementation of `toString` and `toTex`.

**Comment by josdejong** [comment]
Indeed, we need this list with operator precedence. Right now there is no explicit list with operator precedence in the code. In [`parse.js`](https://github.com/josdejong/mathjs/blob/master/lib/expression/parse.js) you will see that all functions in the parser are called in a cascading way: `parseAddSubtract` calls `parseMultiplyDivide`, which calls `parseUnary`, which calls `parsePow`, etc.

So to solve the toTex issue neatly (and improve the toString), we will have to create a this list. The list is described in the second table in the docs op page [syntax.html#operators](http://mathjs.org/docs/expressions/syntax.html#operators).

**Comment by FSMaxB** [comment]
So the problems at hand are:
* Where to put that list and how to make it accessible
* Sometimes the same Operator has different precedence depending on it's usage ( unary minus vs. subtraction for example )
 - Maybe store the underlying function name to distinguish between them

**Comment by josdejong** [comment]
Yes indeed. I don't have a strong opinion on where the operator list must be stored. It may make most sense in a separate file under /lib/expression, named `precedence.js` or something. 

Your second point is already resolved I think: OperatorNodes do have two fields: `op` containing the operator like `'+'`, and `fn` containing the function name, like `'add'`.

**Comment by FSMaxB** [comment]
Like this? ( where the position in the array is the precedence )

```javascript
var precedence = [
{ op: '+', fn: 'add' },
{ op: '+', fn: 'unaryPlus' },
{ op: '-', fn: 'subtract' },
{ op: '+', fn: 'unaryMinus' }
];

module.exports = precedence;
```

**Comment by FSMaxB** [comment]
I just noticed that this idea works fine for operators but not for functions, ranges, units, conditional expressions and assignments. How generic should this list of precedence be?

Should it be something like this?
```javascript
'use strict'
var precedence = [
  [ { FunctionNode: '' } ],
  [
    { OperatorNode: { op: '+', fn: 'add'} }
    { OperatorNode: { op: '-', fn: 'subtract' } }
  ],
  [
    { RangeNode: '' }
  ],
  [
    { OperatorNode: { op: '&', fn: 'bitAnd' } }
  ]
];

module.exports = precedence;
```
Or is this too generic?

**Comment by josdejong** [comment]
Good point about the RangeNode, this is also an operator, and there are more of these. 

I think we have to give all Nodes a method `getPrecedence()`. The nodes for which precedence is not applicable (like FunctionNode), this method can return `Infinity`. Unless I'm overlooking something, there is no need for a separate list this way. For example OperatorNode can just compare it's own precedence with that of both it's arguments, and when an argument has a *higher* precedence, enclose this arguments in parenthesis.

**Comment by FSMaxB** [comment]
Good idea that makes it even easier. I'll implement that. Only problem is that you have to be careful when adding new operators or nodes because you might have to change the precedence of every other operator/node.

So a higher number will represent higher precedence where 0 is the lowest.

`OperatorNode` still needs to treat some Nodes specially, even if they have the `getPrecedence()`, see `ConditionalNode` for example which doesn't need parenthesis in LaTeX, but all the others can then be treated solely based on their precedence.

**Comment by josdejong** [comment]
How about something like this?

```js
// give all nodes a method getIdentifier, default can be to return the nodes type name
Node.prototype.getIdentifier() {
  return this.type;
}
OperatorNode.prototype.getIdentifier() {
  return this.type + ':' + this.fn;
}

// have a precedence list containing the identifiers of nodes 
// only relevant nodes have to be added
var precedence = [
  {
    'OperatorNode:multiply': true, 
    'OperatorNode:divide': true
  },
  {
    'OperatorNode:add': true, 
    'OperatorNode:stubtract': true
  },
  {
    'RangeNode': true
  },
  {
    'OperatorNode:bitAnd': true 
  }
];

// get the precedence for any node instance
function getPrecedence(node) {
  var identifier = node.getIdentifier();
  for (var i = 0; i < predecence.length; i++) {
    if (identifier in precedence[i]) {
      return i;
    }
  }

  // return infinity for non-specified nodes like a FunctionNode
  return Infinity;
}

```

**Comment by FSMaxB** [comment]
Currently I'm confused as to where this code would be placed and when it would be executed. A separate file called `precedence.js` in `lib/expression/node` which gets loaded at the end of `lib/expression/node/index.js`?

**Comment by FSMaxB** [comment]
I added a function to get the operator precedence. I'll start working at `toString()` and `toTex()` now.

**Comment by FSMaxB** [comment]
This bug is fixed in the current development branch!

**Comment by FSMaxB** [comment]
Release v1.5.0 contains the fix. This can be closed now.

**Comment by josdejong** [comment]
Indeed, congrats with your work on `toTex`. Thanks again.
