### ISSUE TITLE
Cannot add vector to matrix

### ISSUE THREAD

**Issue by lakam99** [josdejong/mathjs#2792]
Hello, when attempting to add a matrix A:
`[[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]]`

with vector B:
`[2,4,6,8]`

The expected result is:
`[[ 3,  6,  9, 12],
 [ 7, 10, 13, 16],
 [11, 14, 17, 20],
 [15, 18, 21, 24]]`

However, what actually happens is this error:
`{
  actual: 2,
  expected: 1,
  relation: undefined,
  message: 'Dimension mismatch (2 != 1)'
}`

Here is the code attempted in javascript with mathjs, which provides an error:

```
const { dot, transpose, dotMultiply, matrix, multiply, add } = require("mathjs");

const A = matrix([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]]);

const B = [2, 4, 6, 8];

console.log(add(A, B));
```

Here is the code in python with numpy, which provides the correct result:

```
import numpy as np

A = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]])

B = [2, 4, 6, 8]

print(A+B)
```

**Comment by dvd101x** [comment]
Fixed in #2895
