### ISSUE TITLE
rotationMatrix is not in the index.d.ts

### ISSUE THREAD

**Issue by andreaswimmer** [josdejong/mathjs#2803]
**Describe the bug**
rotationMatrix is not in the index.d.ts, leading typescript to complain when used. It is actually exported in javascript, so there is no problem at runtime. I'm using version mathjs@11.2.1

**To Reproduce**

- `import {rotationMatrix} from "mathjs";`
_TS2305: Module '"mathjs"' has no exported member 'rotationMatrix'._

**Comment by josdejong** [comment]
Thanks for reporting. I see the `rotationMatrix` is missing in [the type definitions](https://github.com/josdejong/mathjs/blob/develop/types/index.ts).

Anyone able to help out here and add `rotationMatrix`?

**Comment by brunoSnoww** [comment]
Hey there, can I be assigned this Issue ? -)

**Comment by josdejong** [comment]
Yes, thanks Bruno! Let me know if you have questions.

**Comment by josdejong** [comment]
Fixed now in `v11.5.1`.
