### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'evaluate')

### ISSUE THREAD

**Issue by mairakhalil** [josdejong/mathjs#2806]
Hey! I am using mathquill and math.js in a project.
Math.js  returns values for trig functions  like sin, cos but when I pass hyperbolic functions like cosh it returns TypeError: Cannot read properties of undefined (reading 'evaluate') . Can anyone help me why this is happening?

**here is my onclick function**
document.getElementById("cosh").onclick= function () {
    answerMathField.cmd("\cosh").focus();
}; 

**here is my mathquill function**
 var MQ = MathQuill.getInterface(2);

 var answerMathField = MQ.MathField(answerSpan, {
    handlers: {
        edit: function () {
            var enteredMath = answerMathField.latex(); // Get entered math in LaTeX format
            workingSpan.innerHTML = enteredMath;

            const escapedTex = String.raw `${enteredMath}`; // ES6 raw template string
            let mathJSTree;
            try{
                 mathJSTree=parseTex(escapedTex);
                
            }catch(err){
                mathSpan.innerHTML="err";
                workingSpan.innerHTML = err;
            }
            try{
                var code = mathJSTree.compile() ;
            }catch(err){
                workingSpan.innerHTML = err;
            }
            try{
                var answer = code.evaluate();
                mathSpan.innerHTML=answer;
            }catch(err){
                workingSpan.innerHTML = err;
            }
            

        }
    }
})

**Comment by gwhitney** [comment]
Well, what is mathJStree after parseTex? That's not a mathjs function, so we can't debug that here. Have you looked to see if it is a valid parse tree? Have you checked the value of `code` before you try to call evaluate on it? If you encounter a mathjs call that is not behaving properly, we can try to address that here. But since in the above it's not clear what inputs are being given to mathjs, there's not much we can do...

**Comment by gwhitney** [comment]
Ah, it appears that you are also using https://github.com/davidtranhq/tex-math-parser, which you overlooked to mention. Checking that project, its documentation makes no mention of `cosh`. So it appears that you should be inquiring with that project, not this one. So closing this issue. Thanks for your interest in mathjs!

**Comment by gwhitney** [comment]
Issue not with mathjs.
