### ISSUE TITLE
0.1 + 0.2 = 0.30000000000000004 ?

### ISSUE THREAD

**Issue by quanxufeng** [josdejong/mathjs#2807]
Node.js v16.17.0.
> 
> 
> const {chain,evaluate} = require('mathjs');
undefined
> 
> 
> chain('0.1')
Chain { value: '0.1' }
> chain('0.1').add(0.2)
Chain { value: 0.30000000000000004 }
>

**Comment by josdejong** [comment]
This is the most asked question. This is a round-off error.

Docs: https://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
Similar questions: https://github.com/josdejong/mathjs/issues?q=is%3Aissue+round-off+is%3Aclosed

**Comment by gwhitney** [comment]
@josdejong should we put a question  in Discussions with an accepted answer for this (would be nice if we could "pin" FAQs there), and/or put something in the issue template (is there one now?) that mentions a list of common questions not to post? Seems like this comes up almost every other week and it's a waste of time.

**Comment by josdejong** [comment]
👍 yes will do, I forgot about this not being in the Discussions section.
