### ISSUE TITLE
Wrong handling of i (imaginary unit)

### ISSUE THREAD

**Issue by gcollura** [josdejong/mathjs#281]
Hello, I'm from the team who develops [ubuntu-calculator-app](https://launchpad.net/ubuntu-calculator-app) for the Ubuntu Phone.
I've encountered a bug with the imaginary unit with your library. If you try to calculate the power of *i* (i^2) the returned value is not -1, while the definition of *i* states that *i*² = -1, mathjs returns `-1 + 1.2246467991474e-16i`.
The issue is also reproduced in this pad http://jsbin.com/fotuxuzuvo/1/edit?html,output
Thanks a lot for your support!

Giulio

**Comment by josdejong** [comment]
He, is the Ubuntu Touch Calculator using mathjs? That's awesome :).

Good point. I've improved the formatting of complex numbers (see commit https://github.com/josdejong/mathjs/commit/c29f33248c0da5a2304b3849eb2de41d629c6cd7), the  real or imaginary part is now rounded to zero when the difference is larger than the configured precision. That should solve (read: hide) these kind of numeric round-off errors. 

This should be fixed now in the `develop` branch.

**Comment by rpadovani** [comment]
Thanks for the fast fix :-)

I [updated](https://code.launchpad.net/~rpadovani/ubuntu-calculator-app/mathjs140) mathjs in the ubuntu calculator app.

FYI the calculator that is shipped atm on ubuntu phones doesn't use mathjs: we're working on a new version, developed from scratch, that uses mathjs.

This new version will substitute the actual version in next weeks: we hope to push it as update before the end of March, with the firsts sold phones.

Thanks for your amazing work!

**Comment by josdejong** [comment]
Cool. I'm really curious to see the Ubuntu phone in action, same with Firefox OS. Two promising new open source initiatives in a heavily competitive market.

Good luck with the calculator!
