### ISSUE TITLE
Unit Conversion has JS buggy math

### ISSUE THREAD

**Issue by cope** [josdejong/mathjs#2813]
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**
Converting 0.00002 decimeter gives 2.0000000000000004 micrometer, instead of 2 micrometer.

**To Reproduce**
```
math.unit('0.00002 decimeter').format()
math.unit('0.00002 decimeter').toString()
```

Interestingly, `math.multiply(0.00002, 100000)` => 2 which begs to question the above conversion. One would expect the multiply to be used.

However, even multiply seems to have an issue, because: `math.multiply(0.00002, 3)` => 0.00006000000000000001

**NOTE**: I did these [directly on the site](https://mathjs.org/docs/datatypes/units.html), in the console, in order to test before use. Not sure if the latest library is on the site?

**Comment by josdejong** [comment]
This is the most asked question, this is a round-off error.

See https://github.com/josdejong/mathjs/discussions/2811#discussioncomment-3870538 for directions
