### ISSUE TITLE
Returning different type than input

### ISSUE THREAD

**Issue by BigFav** [josdejong/mathjs#282]
I've noticed that in some of the inverse trigonometric functions the return type for a [Number is Complex](https://github.com/josdejong/mathjs/blob/develop/lib/function/trigonometry/acos.js#L50), is this ideal behavior?

EDIT: We already somewhat do this with types Boolean and `null`.

**Comment by josdejong** [comment]
Thanks, good point. I wanted to add this issue to the discussion in #279 too, shall we continue the discussion there?

**Comment by BigFav** [comment]
You make a good point in the bullet point in #279 about consistency; the boolean example is still predictable even though it returns a different type than input unlike the example I showed, so they have fundamental differences.

Yes, we can move the discussion there. I will leave this open until it is resolved in the meantime.
