### ISSUE TITLE
typescript types missing

### ISSUE THREAD

**Issue by gp187** [josdejong/mathjs#2832]
The @types are deprecated from [NPM](https://www.npmjs.com/package/@types/mathjs), claiming that the package has types. It does not.

**Comment by josdejong** [comment]
The npm library `mathjs` does have type definitions, and indeed `@types/mathjs` is outdated.

Why do you conclude that the library doesn't have typescript types?

**Comment by josdejong** [comment]
See: https://unpkg.com/browse/mathjs@11.3.2/types/ and a corresponding pointer ` "types": "./types/index.d.ts"` in the package.json file https://unpkg.com/browse/mathjs@11.3.2/package.json
