### ISSUE TITLE
The "Browser testing locally" tests fail on Github Actions

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#2842]
Since a few weeks, the "Browser testing locally" script (which runs `npm run test:browser`) fails when it runs on Github Actions. This could be related to updating a dev dependency like `karma`, it is worth trying whether an older version still works.

Example: https://github.com/josdejong/mathjs/actions/runs/3499302957/jobs/5860710342

```
Run npm run test:browser

> mathjs@11.4.0 test:browser
> karma start test/browser-test-config/local-karma.js

webpack was not included as a framework in karma configuration, setting this automatically...

START:
Webpack bundling...
asset commons.js 6.09 MiB [emitted] (name: commons) (id hint: commons)
asset runtime.js 7.49 KiB [emitted] (name: runtime)
asset browser-tests.test.4127440799.js 1.02 KiB [emitted] (name: browser-tests.test.4127440799)
Entrypoint browser-tests.test.4127440799 6.1 MiB = runtime.js 7.49 KiB commons.js 6.09 MiB browser-tests.test.4127440799.js 1.02 KiB
webpack 5.75.0 compiled successfully in 15577 ms
18 11 2022 18:26:16.955:INFO [karma-server]: Karma v6.4.1 server started at http://localhost:9876/
18 11 2022 18:26:16.956:INFO [launcher]: Launching browsers FirefoxHeadless with concurrency unlimited
18 11 2022 18:26:16.960:INFO [launcher]: Starting browser FirefoxHeadless
18 11 2022 18:26:16.978:ERROR [launcher]: Cannot start FirefoxHeadless
	Can not find the binary firefox
	Please set env variable FIREFOX_BIN
18 11 2022 18:26:16.979:ERROR [launcher]: FirefoxHeadless stdout: 
18 11 2022 18:26:16.979:ERROR [launcher]: FirefoxHeadless stderr: 

Finished in 0 secs / 0 secs @ 18:26:16 GMT+0000 (Coordinated Universal Time)

Error: Process completed with exit code 1.
```

Anyone able to do a bit of digging? Help would be welcome.

**Comment by ChristopherChudzicki** [comment]
Is this still happening? I'm not sure why https://github.com/josdejong/mathjs/actions/runs/3499302957/jobs/5860710342 failed, but 
- https://github.com/josdejong/mathjs/actions/runs/3823849776/jobs/6505453263 seems to be succeeding 

_Though something else is failing on that empty PR... _

**Comment by josdejong** [comment]
It looks indeed like the "Browser testing locally" tests are working again, looking at the history of Github Actions:

https://github.com/josdejong/mathjs/actions/workflows/local-browser.yaml

Thanks for testing Chris. The reason that a [node.js test was failing in your test PR](https://github.com/josdejong/mathjs/actions/runs/3823849355/jobs/6505453118) is a rare race condition in the integration tests for the CLI of mathjs. It happens so rarely that I haven't found it important enough to look into it, but feel free to try fix it :). I've executed your tests again, now they pass.
