### ISSUE TITLE
wrong results on .resize() because @param size

### ISSUE THREAD

**Issue by Thorstorm** [josdejong/mathjs#285]
I will explain it better just putting an example:
```javascript
math.resize([1, 2, 3, 4],         [1, 4]);   returns [[1, 0, 0, 0]]
math.resize([[1], [2], [3], [4]], [1, 4]);   returns [[1, 0, 0, 0]]

math.resize([1, 2, 3, 4],   [4, 1]);         returns [[1], [2], [3], [4]]
math.resize([[1, 2, 3, 4]], [4, 1]);         returns [[1], [2], [3], [4]]
```
It seems that `.resize()` has troubles when its parameter `size` has a bigger value for columns than rows.

**Comment by josdejong** [comment]
Thanks, I will look into it.

**Comment by josdejong** [comment]
This is expected behavior, though I have to admit it looks quite odd in the example you gave. 

If I try to explain the behavior in general:

```js
var a = [1, 2, 3, 4];
math.size(a);    // [4]

// add an dimension
var b = math.resize(a, [4,1]); // b = [[1], [2], [3], [4]]
math.size(b);  // [4, 1]

var c = [[1, 2], [3, 4]];
math.size(c);    // [2, 2]

// add columns
math.resize(c, [2, 4]);  // [[1, 2, 0, 0], [3, 4, 0, 0]]
math.resize(c, [1, 4]);  // [[1, 2, 0, 0]]

// add rows
math.resize(c, [4, 2]);  // [[1, 2], [3, 4], [0, 0], [0, 0]]
math.resize(c, [4, 1]);  // [[1], [3], [0], [0]]
```

So what happens in your first example is that you throw away the 2th to 4th row having values 2, 3, and 4, and add columns with new values zero.
 
```js
var a = [1, 2, 3, 4];
math.size(a);    // [4]

// first resize to [1]
var b = math.resize(a, [1]);  // b = [1]
math.size(b);    // [1]

// then add an extra dimension
var c = math.resize(b, [1, 4]);  // c =[[1, 0, 0, 0]]
math.size(c);    // [1, 4]
```

Does that make sense?

**Comment by Thorstorm** [comment]
Everything you explain fits whenever you specify a dimensional range (parameter size) that needs more values than the ones stored in the array. e.g.:
```javascript
var c = [[1, 2], [3, 4]];
math.size(c);    // [2, 2] --------> 4 stored values 

// add columns
math.resize(c, [2, 4]);  
/** 
 * this resize requires 8 values, 
 * so .resize() fills the two extra columns of each row with zeros
 * c = [[1, 2, 0, 0], [3, 4, 0, 0]];
 */
math.resize(c, [1, 4]); 
/** 
 * this resize only needs 4 values, 
 * so .resize() takes the 4 columns values in the first row
 * c = [[1, 2, 0, 0]];
 */
```
But in some cases, like mine, where I'm specifying a `.resize()` function that doesn't have to put zeros or remove any stored value to output a matrix with the specified `size` parameter, and also IT CAN resize a `[1, 2, 3, 4]` array, which has `math.size([1, 2, 3, 4]) = [4]`, INTO a `math.size([[1], [2], [3], [4]]) = [4, 1]` OR INTO a `math.size([[1, 2], [3, 4]]) = [2, 2]` putting no zeros on it, BUT cannot resize a `math.size([[1, 2, 3, 4]) = [1, 4]` without adding zeros, your standpoint doesn't fit, in my opinion. 

Anyway, I was trying to resize a flattered matrix with size `[3]` into a `[1, 3]` sized one using the 3 values stored. I know this is easy to adapt, but I'm wondering if there's any predefined function in `mathjs` to do so, in case I will need it in the future.

Thank you

**Comment by josdejong** [comment]
I understand what you mean, and this is for example how matrices in Python/numpy works : The data is just a list of entries (say 4 entries), mapped to the current size of the array, no matter whether this is [4], [2,2], [1,4], [4,1], etc. Only the *shape* of the data is changed. 

math.js does not change the shape of the data when resizing (similar to Matlab btw). So if you change size from say [1,4] to [4,1], you "loose" most of your data. It depends on the use case of course if this is desired behavior or not. I think that in general the structure of a matrix and the location of data points in a matrix has actual *meaning*. It would be odd to move a certain data point to a totally different row and column. It's like adding an extra row in your excel sheet, and seeing that all your data has shifted to fill up this new column with values.

Note that if you want to add data to an existing matrix, mathjs will "smartly" resize the provided subset, like:
```js
var a = math.zeros([1,4]);                                   // a = [[0, 0, 0, 0]]
var b = math.subset(a, math.index(0, [0, 4]), [1, 2, 3, 4]); // b = [[1, 2, 3, 4]]

var c = math.zeros([4,1]);                                   // c = [[0], [0], [0], [0]]
var d = math.subset(c, math.index([0, 4], 0), [1, 2, 3, 4]); // d = [[1], [2], [3], [4]]
```

What is the actual *meaning* of your resize example? You want to reorganize data in a matrix, but is this maybe a transpose you want to apply?

**Comment by Thorstorm** [comment]
You're right when you assume that I was thinking in a Python/numpy way. I was considering the array data as a list of entries instead of understanding it as you've explained, the mathematical approach to matrices. I totally agree that data location in a matrix has actual *meaning* and I recognize that the mathematical approach should be the standard.

Once said that, and following with your example, I agreed that, considering the mathematical way to handle matrices, if I had changed size from [1, 4] to [4, 1] or vice versa, I would have to loose most of the data. But, as I wrote on my first comment, it conserves the data. e.g.: 
```javascript
/**
 * CODE 1
 */
var a= [[4, 3, 2, 1]];
math.size(a); // [1, 4]
math.resize(a, [4, 1]); // [[4], [3], [2], [1]]
``` 
In the other hand, if I try the inverse operation, I loose data, as you're saying in your example:
```javascript
/**
 * CODE 2
 */
var a= [[4], [3], [2], [1]];
math.size(a); // [4, 1]
math.resize(a, [1, 4]); // [[4, 0, 0, 0]]
``` 
Now, considering your standpoint, I would expect that CODE 1 returned this:
```javascript
/**
 * CODE 3
 * this is not the real code behaviour
 * It's a representation of your example
 */
var a= [[4, 3, 2, 1]];
math.size(a); // [1, 4]
math.resize(a, [4, 1]); // [[4], [0], [0], [0]]
``` 
But instead I get the results as in the CODE 1 block. 

The problem I'm trying to point out since the beginning is the `.resize()` behaviour inconsistency. Mathematically, considering the matrix rows as linear equations and columns as coefficients of the same variable in each equation, I would expect to loose data both [1, 4] to [4, 1] as [4, 1] to [1, 4]. Following the [1, 4] to [4, 1]case, having this linear equation *4x + 3w + 2y + z*, you can't put the *w, y, z* coefficients as new *x* coefficients of new equations, so you loose *3w + 2y + z* and set them up to *0*. This is not happening, CODE 1 block is the proof.

Either you treat the array as a list of entries with no data location *meaning* or you treat the matrix mathematically and give each data location a purpose. But you can't do one for the [1, 4] to [4, 1], CODE 1, and the other for the [4, 1] to [1, 4], CODE 2.

**Comment by josdejong** [comment]
Thanks for your reply. Indeed, no matter what solution is implemented, it should at least work in a consistent way.

When I run your code examples, the output I get is:

```
CODE 1: [[4], [0], [0], [0]] as expected  (not your [[4], [3], [2], [1]])
CODE 2: [[4, 0, 0, 0]]       as expected
CODE 3: [[4], [0], [0], [0]] as expected 
```

However when I change your CODE 1 to `a=[4, 3, 2, 1]` (a vector instead of a matrix), I indeed get your output `[[4], [3], [2], [1]]`

Maybe what works different from what you expected is that resizing a 1D matrix like `[4, 3, 2, 1]` having size `[4]` into a 2D matrix of size `[4,1]`, the new, second dimension will be added as an *inner* Array rather than an *outer* Array, i.e. the matrix will become `[[4], [3], [2], [1]]`?

**Comment by Thorstorm** [comment]
My argument is held by the CODE 1, which is based in my first comment. I've just check the CODE 1 again and it returns the values you wrote. My point was poorly informed. I'm truly sorry for wasting your time.

I expected consistency, and `.resize()` has it. It was nice to have a debate with you. Greetings and keep up the good work!

**Comment by josdejong** [comment]
Yes, thanks for your input and the constructive discussion. Great that it is clear now. 

If you have other thoughts or suggestions on things regarding math.js please let us know. There is a topic https://github.com/josdejong/mathjs/issues/279 discussing breaking changes for v2, so that's a nice opportunity to rethink previous decisions and possible inconsistent/unhandy behavior.
