### ISSUE TITLE
Implicit conversion issue using percentages with evaluate

### ISSUE THREAD

**Issue by maddockst-monek** [josdejong/mathjs#2863]
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**
I use mathjs to perform monetary calculations. However, when I am doing calculations involving percentages I'm getting the following error:

`TypeError: Cannot implicitly convert a number with >15 significant digits to BigNumber (value: 0.018500000000000003). Use function bignumber(x) to convert to BigNumber.`

I've managed to resolve this using creating a custom instance with the config `{ number: 'BigNumber', precision: 64 }` but I'm not confident this is the right way to solve this.

**To Reproduce**
```
mathJs.evaluate('transactionAmount * 1.85%', {
    transactionAmount: mathJs.bignumber(0.01),
});

// TypeError: Cannot implicitly convert a number with >15 significant digits to BigNumber (value: 0.018500000000000003). Use function bignumber(x) to convert to BigNumber.
```

**Comment by josdejong** [comment]
> I've managed to resolve this using creating a custom instance with the config `{ number: 'BigNumber', precision: 64 }` but I'm not confident this is the right way to solve this.

That is indeed the right way. With the default configuration, `mathJs.evaluate('1.85%')` will return a `number` (just try it out). With the configuration you mention, `evaluate` will create a `BigNumber` from `1.85` and use that.
