### ISSUE TITLE
Some functions are still available even with a custom evaluate that doesn't define them

### ISSUE THREAD

**Issue by stuartlangridge** [josdejong/mathjs#2876]
Building on https://mathjs.org/examples/advanced/custom_evaluate_using_factories.js.html I would like to build an evaluating expression parser which only allows addition, multiplication, division, subtraction, and square roots on integers and that's it.

Below is an example. Note that `sin(5)` correctly fails with `Error: Undefined function sin` (because I haven't defined it). However, `det([-1, 2; 3, 1])` succeeds even though I haven't defined the `det()` function in my custom factories (and also matrix syntax exists as well, which I also don't want). Is this example not intended to demonstrate how to build a parser with only certain expressions defined? If this isn't the best way to do that, is there a better way?

```javascript
const { create, evaluateDependencies, factory } = require('mathjs')

// custom implementations of all functions you want to support
const add = (a, b) => a + b
const subtract = (a, b) => a - b
const multiply = (a, b) => a * b
const divide = (a, b) => a / b
const sqrt = (a) => a ** 0.5

// create factories for the functions, and create an evaluate function with those
// these functions will also be used by the classes like Unit.
const { evaluate } = create({
  evaluateDependencies,
  createAdd: factory('add', [], () => add),
  createSubtract: factory('subtract', [], () => subtract),
  createMultiply: factory('multiply', [], () => multiply),
  createDivide: factory('divide', [], () => divide),
  createSqrt: factory('sqrt', [], () => sqrt)
})

console.log(evaluate('2 + 3 * sqrt(4)')) // 14
console.log(evaluate('1.2 * (2 + 4.5)')) // 7.8
console.log(evaluate('det([-1, 2; 3, 1])')) // succeeds even though det is not defined
console.log(evaluate('sin(5)')) // correctly fails because sin is not defined
```

**Comment by josdejong** [comment]
Ah, good point. 

I had a look, and the reason for this is that the expression parser depends on a set of node classes like `OperatorNode` and `SymbolNode`. `SymbolNode` has an optional dependency on the `Unit` class, which is quite large and has dependencies on functions like `pow`, which depends on `inv`, which depends on `det` 😁 .

To prevent this, you can use the number only implementation of mathjs, like `require('mathjs/number')`. I've updated the examples accordingly: https://github.com/josdejong/mathjs/commit/cb168f60d9caee793997363454a03c825806c347
