### ISSUE TITLE
Documentation for stat functions

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#2883]
Hello,

While reading about `sum( )` I found out a few issues mainly with the documentation in the category of **Statistics** on version **11.5.0**

## `sum( )`

On **syntax** and **examples**

* There is no reference for `sum(A, dim)` even though it works as expected.

On **See also**

* There is a reference for itself `sum`

## `std( )`

On **syntax** and **examples**

* There is no reference to `std(A, dim)` even though it works as expected.
* There are references for `std(A, normalization)` but it also works as `std(A, dim-1, normalization)`. I include `dim-1` because is zero indexed inside `math.evaluate( )`.

## `variance( )`

On **syntax** and **examples**
* There is no reference to `variance(A, dim)` even though it works as expected.
* There are references for `variance(A, normalization)` but it also works as `variance(A, dim-1, normalization)`. I include `dim-1` because is zero indexed inside `math.evaluate( )`.

While doing these tests I got the errors that `median(A, dim)` and `prod(A, dim)` are not yet supported.

My main concern was finding that `sum(A, dim)` works but I hope the rest of the report can be useful.

**To Reproduce**
These were found inside the equation parser and the website documentation.

**Comment by josdejong** [comment]
Thanks @dvd101x for bringing this up. I've updated the docs via a012c1e (not yet published)

**Comment by dvd101x** [comment]
Thanks!

**Comment by josdejong** [comment]
Fix is published now in `v11.5.1`, thanks again.
