### ISSUE TITLE
`math.column` unexpectedly returns a scalar

### ISSUE THREAD

**Issue by evanmiller** [josdejong/mathjs#2891]
**Describe the bug**

The [docs](https://mathjs.org/docs/reference/functions/column.html) indicate that `.column` will always return an Array or Matrix. However, if the input matrix is 1x1, the result is a number.

**To Reproduce**

```
math.column(math.identity(1) as math.Matrix, 0)
```

Expected: a Matrix

Received: a number

Tested on 11.5.1

**Comment by josdejong** [comment]
Thanks for reporting this bug Evan. It is fixed via 68b4b503f75a554d17e476cdd9205c37aeb4b1b6 (not yet published)

**Comment by josdejong** [comment]
The fix is now published in `v11.6.0`.
