### ISSUE TITLE
Converting 1 meV (1 millielectronvolt) returns 1.602176565e-22 meV

### ISSUE THREAD

**Issue by panokhio** [josdejong/mathjs#2894]
While writing tests for various units, I noticed that sending in the unit of meV (millielectronvolt) with a value of 1 to convert to a full unit would return "1.602176565e-22 meV" instead of "1 meV". The conversion seems to work for other values just not 1.

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce what you describe?

**Comment by panokhio** [comment]
Look at the result of unit(1, "meV")

**Comment by josdejong** [comment]
As far as I see that works normally:

```js
math.unit(1, "meV").toString() // '1 meV'
math.unit(1, "meV").toNumber() // 1
```

You should be careful to not just look at the internal `.value` property, that is a normalized value.

**Comment by gwhitney** [comment]
Since there has been no follow-up in over six months and the behavior seems to be as designed, closing.
