### ISSUE TITLE
Matrices not always getting squeezed properly when using subset and index

### ISSUE THREAD

**Issue by Archer6621** [josdejong/mathjs#2906]
**Describe the bug**
According to the documentation on matrices (https://mathjs.org/docs/datatypes/matrices.html#resizing), the result from calling `subset` should be squeezed automatically when possible. I believe I may have found a case where it is possible and desirable, but it doesn't happen automatically.

**To Reproduce**
See JSFiddle, it has further comments as well: https://jsfiddle.net/19b7p8he/10/

**Comment by josdejong** [comment]
Thanks for reporting. 

I think the docs are quite misleading there. The actual behavior is that no squeezing is taking place at all, except in one specific case: when you get a single scalar value out of a matrix. So:

```js
const a = math.ones(10, 10, 3)

console.log(a.subset(math.index(1, 1, math.range(0,3)))) // Matrix [[[1, 1, 1]]]

console.log(a.subset(math.index(1, 1, 2))) // number 1 and not [[[1]]]
```

I'll improve the documentation to clearly reflect that, OK?

**Comment by Archer6621** [comment]
> Thanks for reporting.
> 
> I think the docs are quite misleading there. The actual behavior is that no squeezing is taking place at all, except in one specific case: when you get a single scalar value out of a matrix. So:
> 
> ```js
> const a = math.ones(10, 10, 3)
> 
> console.log(a.subset(math.index(1, 1, math.range(0,3)))) // Matrix [[[1, 1, 1]]]
> 
> console.log(a.subset(math.index(1, 1, 2))) // number 1 and not [[[1]]]
> ```
> 
> I'll improve the documentation to clearly reflect that, OK?

I see, thanks for clarifying this! 

However, wouldn't it be a feature to consider for the future? Since numpy does this as well when retrieving slices from multi-dimensional arrays. It might be especially nice with that new broadcasting feature that was recently added, since this removes the struggle of having to fiddle with the dimensions all the time.

**Comment by josdejong** [comment]
Ah, yes, that maybe interesting to rethink. Now that we have broadcasting this may change things. Can you open a discussion to think this through? Then I'll share a bit of the reasons that this wasn't done originally.

https://github.com/josdejong/mathjs/discussions

**Comment by Archer6621** [comment]
> Ah, yes, that maybe interesting to rethink. Now that we have broadcasting this may change things. Can you open a discussion to think this through? Then I'll share a bit of the reasons that this wasn't done originally.
> 
> https://github.com/josdejong/mathjs/discussions

Will do this soon, thanks for adjusting the docs!
