### ISSUE TITLE
Format with fixed notation not working for very large values

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#291]
```js
var x = 1e+27;

console.log(math.format(x, {notation: 'fixed'}));
// output: "1e+27"
// expected: "1000000000000000000000000000"

console.log(math.format(x, {notation: 'auto', exponential: {lower: 1e-100, upper: 1e+100}}));
// output: "1e+27"
// expected: "1000000000000000000000000000"
```

This has to do with the 21 digit limit of JavaScripts [`toPrecision`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toPrecision) function.

Would be nice to support fixed notation for very large values too.

**Comment by maxkcy** [comment]
Hello, it seem this issue is still not fixed. 
in my code this line ``simplified = math.format(simplified,{exponential:{lower: 1e-100000, upper: 1e100000}}).toString();`` 
is still producing values with the scientific notation.

**Comment by josdejong** [comment]
How can I reproduce your issue?
