### ISSUE TITLE
Math functions are Symbol nodes

### ISSUE THREAD

**Issue by Simonrazer** [josdejong/mathjs#2914]
**Describe the bug**
![image](https://user-images.githubusercontent.com/30187223/224504687-1cebfea5-4c6d-47b4-9c1a-a73cc706c23d.png)
According to your docs, sin(), sqrt() and the like should return as Function Nodes. But they report as Symbol node, so one can't see the difference from them to a true Variable

**To Reproduce**
`math.parse("sin(3)").traverse( (n,a,v) => {console.log(n)})`

**Comment by ChristopherChudzicki** [comment]
_I tested this in versions `11.2.0` and `11.5.0`, but I expect it's the same in all versions, back a long ways._

`sin(3)` reports as a FunctionNode. Note that it's the function call `sin(3)`, not `sin` that corresponds to the FunctionNode. (FunctionEvaluationNode might be a more accurate name.)

Your traversal shows that the function node has two children, the function (a SymbolNode, `sin`) and the arguments (here, one a constant node):
```
> math.parse('sin(3)').traverse(n => console.log(n))
FunctionNode {
  fn: SymbolNode { name: 'sin' },
  args: [ ConstantNode { value: 3 } ]
}
SymbolNode { name: 'sin' }
ConstantNode { value: 3 }
```

IMO this makes sense: as far as the parser is concerned, `sin` is just as symbol. It might be a function, like `math.parse("sin(3)").evaluate({ sin: Math.sin })`. Or it might be anything else, like an array `math.parse(sin(3)).evaluate({ sin: [] })`. 

_Of course, assigning an array to `sin` would be silly and would throw an error during evaluation. But function names could be anything... could just be "f" or "r" etc._

**Comment by josdejong** [comment]
Well explained @ChristopherChudzicki , thanks. The returned node indeed is a `FunctionNode` (in your screenshot it's the first, not expanded console log).
