### ISSUE TITLE
[DOC] distance syntax is wrong

### ISSUE THREAD

**Issue by tmtron** [josdejong/mathjs#2923]
**Describe the bug**
The `syntax` of the [distance](https://mathjs.org/docs/reference/functions/distance.html) function is a copy of the `examples`

**To Reproduce**
![image](https://user-images.githubusercontent.com/20422904/227935565-5f319862-9450-4e5c-afdd-bade7b2010fe.png)

**Comment by josdejong** [comment]
Fix has been published now in `v11.8.0`
