### ISSUE TITLE
cos(pi/2) and sin(pi) not zero

### ISSUE THREAD

**Issue by ybh10** [josdejong/mathjs#2933]
This problem was discussed here: https://github.com/josdejong/mathjs/issues/447
The solution to use big numbers does not seem to work anymore.
math.config({number: 'bignumber'});
math.evaluate('cos(pi/2)').toString() //=1.539082031431044993140174126710585339910740432566411533235469223e-64 != 0
Is there a way to do it now with a full expression (e.g 5*sin(pi/2*2)/4)?

**Comment by Darawanb** [comment]
Yes. This is the most common issue posted. It is a round-off error.  The way I would fix this is pretty simple actually.

`function cos(x) {
    return x % ( Math.PI / 2 ) === 0 ? 0 : Math.cos(x);
}`

**Comment by josdejong** [comment]
See also #2928
