### ISSUE TITLE
Missing `math.js.map`

### ISSUE THREAD

**Issue by matthewelmer** [josdejong/mathjs#2943]
When I use `math.js` as a standalone library, my console shows the following warning: `DevTools failed to load source map: Could not load content for file:///home/matt/school/AREUS/SARLACC/web/thirdparty/math.js.map: System error: net::ERR_FILE_NOT_FOUND`

I cannot find `math.js.map` anywhere in this repository or on the main website.

**Comment by matthewelmer** [comment]
I recommend putting that more prominently on [the webpage where math.js can be downloaded](https://mathjs.org/download.html).

**Comment by josdejong** [comment]
That makes sense. Done.
