### ISSUE TITLE
distance function error when calculate distance from point to line 

### ISSUE THREAD

**Issue by Kiku-CN** [josdejong/mathjs#2964]
There are two points (5,0) and (10,0) in a line. The distance between from point (8,0) to the line should be 0, but got wrong result. 
Is this a bug or my syntax error?

```js
var {distance} = math

// math.distance([x1,y1], [x2,y2], [x3,y3])
// math.distance({pointX, pointY}, {lineOnePtX, lineOnePtY}, {lineTwoPtX, lineTwoPtY})

console.log(distance([8,0],[10,0],[5,0]));  // 3.5777087639996634
console.log(distance(
 {pointX: 8, pointY: 0},
 {lineOnePtX: 10, lineOnePtY: 0},
 {lineTwoPtX: 5, lineTwoPtY: 0})   );  //5.008792269599529
```

**Comment by Kiku-CN** [comment]
[There](https://github.com/josdejong/mathjs/blob/23cf6e8035237747f5d197e659eeeaab3996bd89/src/function/geometry/distance.js#L75) seem to be some errors when calculating the coefficients and constant.

distance() work correctly after using the algorithm  below algorithm for calculating the coefficients and constant.
```js
var xCoeff = subtract(z.lineTwoPtY, y.lineOnePtY);
var yCoeff = subtract(y.lineOnePtX ,z.lineTwoPtX);
var constant = subtract(multiplyScalar(z.lineTwoPtX, y.lineOnePtY),multiplyScalar(y.lineOnePtX, z.lineTwoPtY));
```

**Comment by josdejong** [comment]
Thanks for reporting this bug. Would you be able to work out a fix in a PR, with some additional unit tests?

**Comment by Kiku-CN** [comment]
> Thanks for reporting this bug. Would you be able to work out a fix in a PR, with some additional unit tests?

#2965 My pleasure to contribute，it's my first PR :)

**Comment by josdejong** [comment]
Thanks a lot! I expect to review your PR next week.
