### ISSUE TITLE
zpk2tf and freqz functions implementation

### ISSUE THREAD

**Issue by alykhaled** [josdejong/mathjs#2969]
I've created an implementation for `zpk2tf` function. The function is used to convert a zero-pole-gain representation of a filter to a transfer function representation where the return value is a array of numerator and denominator coefficients. The function is used in the design of digital filters.
The equivalent function in Matlab is [zp2tf(z,p,k)](https://www.mathworks.com/help/signal/ref/zp2tf.html) and in Python is [scipy.signal.zpk2tf(z,p,k)](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.zpk2tf.html).

I've also created an implementation for `freqz` function. The function is used to compute the frequency response of a digital filter. where it takes the numerator and denominator coefficients as input and returns the frequency response as an array of complex numbers.
The equivalent function in Matlab is [freqz(b,a)](https://www.mathworks.com/help/signal/ref/freqz.html#d124e78711) and in Python is [scipy.signal.freqz(b,a)](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.freqz.html).

I want to create a PR but I don't know the right category for this functions, should it be in `src/function/special` or create a new category for it named `signal` or `filter`?

**Comment by josdejong** [comment]
Thanks Aly! That would be a useful addition. Good question what a suitable category would be. I think `filter` is a bit of an overloaded term, associated with filtering values from an Array, and `special` is mostly associated a function like `erf`. Maybe best to just follow the naming of Python here and name it `signal`? 

One more question: what functions do we need to make this "feature complete"? Are there any related functions that we should implement too? (i.e. if you implement `sin` you should also implement `cos` and `tan` for example). I see the Matlab docs have an "See also" section, is there anything important there?

**Comment by josdejong** [comment]
Thanks for the clear overview! 

> But for now I only implemented `zpk2tf` and `freqz`. My suggestion is to create a github project for the `signal` part with the remaining unimplemented functions so people would know.

Ok sounds like a plan, let's start by implementing `zpk2tf` and `freqz` in mathjs itself. If the full set of functions is large (and not mainstream), we can indeed consider putting the functionality in a separate library, like other extensions: https://mathjs.org/download.html#extensions

> Should I start a PR to implement these two functions ?

Yes please, thanks!

**Comment by josdejong** [comment]
Implemented via #2988 (not yet published)

**Comment by josdejong** [comment]
Published now in `v11.9.0`
