### ISSUE TITLE
max gives incorrect return type

### ISSUE THREAD

**Issue by bofa** [josdejong/mathjs#2971]
In version 11.8.1 type definitions has been added to min/max functions. They do not seam to reflect what is actually being returned from the function.

type according to typescript
max<T extends MathType[]>(...args: T): T[number]

**Describe the bug**
Defined return type do not reflect returned value for number array input.

**To Reproduce**
```ts
math.max([1,2,3])
3
```
stated type is number[] not number.

**Comment by jonathantsao** [comment]
Also experiencing this issue.

**Comment by josdejong** [comment]
Thanks for reporting, this is a regression introduced in #2955, I didn't review this PR thoroughly enough I'm afraid.

Fixed via 29db0fb288929920c7379cd404f70b7114094149. @Maxim-Mazurok can you have a brief look at this commit?

I also improved the typings of other statistics functions like `mean`. The typings become a bit unwieldy though. To really improve them we should introduce generics for `MathCollection`, `MathArray`, and `MathMatrix`, but that is quite a refactor.

**Comment by josdejong** [comment]
Should be fixed now in `v11.8.2`

**Comment by Maxim-Mazurok** [comment]
Right, I don't think I considered that you can pass an array of numbers.
Thanks for the fix, 11.8.2 seems to work very well for me.

**Comment by josdejong** [comment]
Thanks @Maxim-Mazurok for checking.
