### ISSUE TITLE
Unit.divide(Unit) return type is incorrect when units cancel out

### ISSUE THREAD

**Issue by matt18224** [josdejong/mathjs#2972]
**Describe the bug**
Version 11.8.1

The return type of `Unit.divide(Unit)` is `Unit`, but if the result of the division is a scalar, a number is actually returned.

The `divide(Unit, Unit)` function has the correct return type: `Unit | number`.

**To Reproduce**
```typescript
const kg = unit('1 kg');
const hundredGrams = unit('100 g');

//typeof divResult === 'number', but return type of function is Unit
const divResult = kg.divide(hundredGrams);
console.log(typeof divResult); //"number"

```

**Comment by josdejong** [comment]
Fixed now in `v11.8.2`
