### ISSUE TITLE
Simplify puts plus and minus signs next to eachother

### ISSUE THREAD

**Issue by popiolek** [josdejong/mathjs#2974]
Trying to use `.simplify()` function on string equations I came across some wiered behaviors.

**Describe the bug**
I would expect some simplifications, that I don't see in result:
1. plus and minus signs are next to eachother (`...a + -(3...`)- I'd expect for plus to be reduced
2. parenthesis is kept even though it doesn't have to be there (`...+ -(3 * x) -...`)
3. Above simplifications work in case of `...+ (-2z)...` being converted to `...- 2 * z` - not sure if it's a bug, or some other problem.

**To Reproduce**
```
math.simplify("+3a + (-2z) + x * (-3)").toString({parenthesis: "auto", implicit: "hide"})
```

**Result**
```
"3 a + -(3 * x) - 2 * z"
```

**Expected**
```
"3 a - 3 * x - 2 * z"
```

**Comment by josdejong** [comment]
Thanks for reporting. 

Anyone interested in debugging this and fine-tuning the rules of `simplify`?

**Comment by DevasishY** [comment]
hi , I am new to opensource, I want to resolve this issue , could you help me how to approach this problem.
I went through simplify.js file  in algebra section, I found simplify rules is it that part where I should focus to resolve.
