### ISSUE TITLE
Can not install from npm

### ISSUE THREAD

**Issue by censujiang** [josdejong/mathjs#2982]
error while installing mathjs

**Describe the bug**

```console
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error @squoosh/lib@0.5.3: The engine "node" is incompatible with this module. Expected version " ^12.5.0 || ^14.0.0 || ^16.0.0 ". Got "18.16.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**To Reproduce**

yarn add mathjs

**Comment by josdejong** [comment]
When I do run `yarn add mathjs` in an empty folder I do not get such an error and can install mathjs succesfully. 

Are you sure this is related to mathjs? How to reproduce your issue?

**Comment by censujiang** [comment]
You can try it in Node18

**Comment by josdejong** [comment]
I'm using node `18.12.1` right now.

**Comment by josdejong** [comment]
Have you tried `yarn add mathjs` in an empty folder?

Why is the error mentioning a library `@squoosh/lib` and nothing related to `mathjs`?

**Comment by josdejong** [comment]
Closing this issue now due to lack of response. As far as I can see this is an issue related to the library `@squoosh/lib@0.5.3` and not related to `mathjs`. Feel free to reopen if needed.
