### ISSUE TITLE
Function eigs does not work when matrix is defective

### ISSUE THREAD

**Issue by ishaanjain** [josdejong/mathjs#2984]
**Describe the bug**
When a matrix has only one eigenvector, the function `eigs` does not work.

**To Reproduce**
The matrix `[[1, 1], [0, 1]]` is a simple shear matrix that has the eigenvector `[0,1]`.
However, `eigs([[1, 1], [0, 1]])` returns an error.

**Comment by josdejong** [comment]
Thanks for reporting.

Help debugging this issue with `eigs` would be welcome. Anyone?

**Comment by DarshanDixit05** [comment]
Hi @josdejong👋, I want to work on the issue. Can you please assign it to me?

**Comment by josdejong** [comment]
Thanks a lot Darshan! Please let me know if you need any help.

**Comment by gwhitney** [comment]
Likely duplicate of #2879

**Comment by gwhitney** [comment]
Works with #2879 fix, so confirmed to be a duplicate. Closing.
