### ISSUE TITLE
rollup unresolved dependencies waring

### ISSUE THREAD

**Issue by Jiguangjie** [josdejong/mathjs#2993]
![20230707-112831](https://github.com/josdejong/mathjs/assets/10969137/e4a71858-1e21-4c50-b737-d64c5a73a55d)

install mathjs waring

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce your issue?

**Comment by Jiguangjie** [comment]
Thanks, because i use @rollup/plugin-node-resolve. extensions set error

**Comment by Jiguangjie** [comment]
> Thanks for reporting. How can I reproduce your issue?

**Comment by Jiguangjie** [comment]
Thanks, because i use @rollup/plugin-node-resolve. extensions set error
