### ISSUE TITLE
Validate many marks

### ISSUE THREAD

**Issue by hieunv1** [josdejong/mathjs#3006]
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**
I want validate 
"1+1"  => true
"1++++1" => false 
currently i am using math.parse()
please help  .

**Comment by josdejong** [comment]
That indeed looks odd :) 

mathjs does have a unary plus operator similar to the unary minus, so the following expressions are valid:

```
+1
-1
```

Your expression `1++++1` is evaluated as `1 + (+(+(+1)))`, and is just valid syntax.

If you want to guard against this, you can either write a regular expression to detect such issues and throw an error, or you can parse the expression using `math.parse`, then traverse the expression tree to see if there is an occurrence of `unaryPlus`, and if so throw an error. See docs: https://mathjs.org/docs/expressions/expression_trees.html
