### ISSUE TITLE
Error with fraction.js dependency

### ISSUE THREAD

**Issue by ai-rohit** [josdejong/mathjs#3024]
The https://github.com/josdejong/mathjs/issues/3022 issue was fixed with mathjs v11.10.1 using fraction.js v4.3.4. Now the issue is reproduced again with v11.10.1 using fraction.js v4.3.6

Fraction.js:9 Uncaught TypeError: Object.defineProperty called on non-object
at Function.defineProperty ()
at Fraction.js:9:10
at a (factory.js:35:12)
at Object. (pureFunctionsAny.generated.js:22:38)
at u ((index):1:2157)
at Object. (main.cd1dd74d.chunk.js:1:292368)
at u ((index):1:2157)
at Object. (main.cd1dd74d.chunk.js:1:115856)
at u ((index):1:2157)
at Object. (main.cd1dd74d.chunk.js:1:785656)
(anonymous) @ Fraction.js:9
a @ factory.js:35
(anonymous) @ pureFunctionsAny.generated.js:22

<img width="1189" alt="image" src="https://github.com/josdejong/mathjs/assets/68155913/25091dd5-4e87-4872-bc5d-fdf0a564c4c1">

I tried locking fraction.js to v4.3.4. which solved the issue but I dont think this as long term solution.

**Comment by YangBo29** [comment]
Please lock it. Don't let him get into trouble all the time

**Comment by josdejong** [comment]
See https://github.com/rawify/Fraction.js/issues/68

**Comment by Runtime4642** [comment]
I am also experiencing the same problem.
