### ISSUE TITLE
inv (matrix inverse) is not exported in esm/number

### ISSUE THREAD

**Issue by Fil** [josdejong/mathjs#3033]
I'm trying to import the inv function via

`const mathjs = await import("https://esm.sh/mathjs/lib/esm/number");`

but mathjs.inv is undefined (tested with deno and observable).

Ideally we could tree-shake with:
`const {inv} = await import("https://esm.sh/mathjs/lib/esm/number?exports=inv&min");`

**Comment by josdejong** [comment]
The number-only version of mathjs only supports... numbers. Matrices and functions for matrices are not available in the number only version, you'll use the regular, full-fledged functions then.

Here are the docs about number-only, custom bundling, and tree-shaking: https://mathjs.org/docs/custom_bundling.html

**Comment by Fil** [comment]
ahahha sorry, I thought it was supporting matrices of numbers (vs. complex). My bad! thanks for the library

**Comment by Fil** [comment]
To be complete, this works in deno:

~~~js
const {inv} = await import("https://esm.sh/mathjs/lib/esm/index.js?exports=inv&min");
inv([[1,2], [3, 5]]). // [ [ -5, 2 ], [ 3, -1 ] ]
~~~

(unfortunately it breaks on observable, but there we can use `require("mathjs")`).
