### ISSUE TITLE
[DecimalError] Invalid argument 

### ISSUE THREAD

**Issue by karchinkong** [josdejong/mathjs#3034]
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**
Uncaught Error: [DecimalError] Invalid argument: 2.30258509299404568401799145468436420760110148862877297603332790096757260967735248023599720508959829834196778404228624863340952546508280675666628736909878168948290720832555468084379989482623319852839350530896537773262884616336622228769821988674654366747440424327436515504893431493939147961940440022210510171417480036880840126470806855677432162283552201148046637156591213734507478569476834636167921018064450706480002775026849167465505868569356734206705811364292245544057589257242082413146956890167589402567763113569192920333765871416602301057030896345720754403708474699401682692828084811842893148485249486448719278096762712757753970276686059524967166741834857044225071979650047149510504922147765676369386629769795221107182645497347726624257094293225827985025855097852653832076067263171643095059950878075237103331011978575473315414218084275438635917781170543098274823850456480190956102992918243182375253577097505395651876975103749708886921802051893395072385392051446341972652872869651108625714921988499789cc713771345686209167058

![image](https://github.com/josdejong/mathjs/assets/16110331/ee2b39d5-7904-406a-b568-b5485ac68b43)

**To Reproduce**
import cdn mathjs in my project, and then take this error.

**Comment by josdejong** [comment]
Thanks for reporting. Can you share a code example demonstrating the issue?

**Comment by gwhitney** [comment]
As far as I can see, the difficulty lies in the characters 'cc' that occur 21 places from the end. These are indeed not allowed in BigNumber literals. So I do not believe there is a bug here; marking it as such. Jos, if you agree, please feel free to close.

**Comment by josdejong** [comment]
Ah, well spotted Glen, you're right. I'll close the issue.
