### ISSUE TITLE
Derivative error for min, max functions

### ISSUE THREAD

**Issue by sylee957** [josdejong/mathjs#3074]
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**

I get a error `Expected TypeError, but none found` for derivatives like `max(x, 1)` and for `max(x, y)`, 

```typescript
import * as math from "mathjs";

const expr = math.parse("max(x, 1)");
const sym = math.parse("x");
console.log(math.derivative(expr, sym));
```

while 
```typescript
import * as math from "mathjs";

const expr = math.parse("max(x)");
const sym = math.parse("x");
console.log(math.derivative(expr, sym));
```
gives the error message `Function "max" is not supported by derivative, or a wrong number of arguments is passed`

**To Reproduce**
Steps to reproduce the behavior.

I'm using mathjs `11.11.1`

**Comment by josdejong** [comment]
Thanks for reporting, I've improved the error message so it will be `Function "max" is not supported by derivative, or a wrong number of arguments is passed` in all cases.
