### ISSUE TITLE
`pickRandom` return type inconsistency between code and doc

### ISSUE THREAD

**Issue by Vistinum** [josdejong/mathjs#3088]
**Describe the bug**
https://github.com/josdejong/mathjs/blob/f9ab3a107393f7ed356dfcb662f5bfa6df1407fe/types/index.d.ts#L2278
https://github.com/josdejong/mathjs/blob/f9ab3a107393f7ed356dfcb662f5bfa6df1407fe/src/function/probability/pickRandom.js#L53
According to the documentation, in `pickRandom(array, number)`, passing `1` as `number` should result in a `number` being returned. However, `pickRandom([1], 1)` returns an array `[1]`.

It is easy to confirm this behavior in code.
https://github.com/josdejong/mathjs/blob/f9ab3a107393f7ed356dfcb662f5bfa6df1407fe/src/function/probability/pickRandom.js#L93
https://github.com/josdejong/mathjs/blob/f9ab3a107393f7ed356dfcb662f5bfa6df1407fe/src/function/probability/pickRandom.js#L154
The fix would be very simple. If this is intended, the doc should be updated. Otherwise, the logic around `single` should be fixed.

**To Reproduce**
`math.pickRandom([1], 1)` returns `[1]`.

**Comment by josdejong** [comment]
Thanks for reporting, this was indeed an issue in the docs. The TS types and actual implementation are ok.
