### ISSUE TITLE
Applying the math.js file makes the Promise.all asynchronous callback on our project finally is not a function problem

### ISSUE THREAD

**Issue by admincopm** [josdejong/mathjs#3089]
TypeError: Promise.all(...).then(...).catch(...).finally is not a function

**Comment by admincopm** [comment]
I map js to the global as if the promise prototype chain has modified finally

**Comment by josdejong** [comment]
How can we reproduce your issue?

**Comment by josdejong** [comment]
Closing this issue due to a lack of response. Please reopen if there is more info.

**Comment by admincopm** [comment]
Indeed, by introducing math.js alone I could not reproduce this problem, probably with other js resources, too many js files. I used the last similar method to solve the current problem. Thank you for your reply.

**Comment by josdejong** [comment]
👍 thanks for letting me know.
