### ISSUE TITLE
Fix the Naming Convention for Error Log. Incorrect English

### ISSUE THREAD

**Issue by Saoming** [josdejong/mathjs#3092]
Please take a look at line 38 and tell me why the word is used: "is no valid number"
https://github.com/josdejong/mathjs/blob/8679c076176a8ea14be92985622dc4255800e527/src/type/number.js#L38C1-L39C1

Fix:

"It's not a valid number" somewhere along these lines.

**Comment by josdejong** [comment]
👍 thanks for your feedback

**Comment by Saoming** [comment]
No no no, Thanks to Mr Eric from Sheet JS. 

https://sheetjs.com/demo/

**Comment by josdejong** [comment]
The fix is published now in `v12.1.0`
