### ISSUE TITLE
MathArray typescript type definition only handles 1D and 2D arrays

### ISSUE THREAD

**Issue by Amolition** [josdejong/mathjs#3098]
**Description**
The MathArray typescript type cannot accept any N-dimensional arrays (it is limited to 1D or 2D arrays). This is despite many/all functions where the MathArray type is used being capable of handling and returning arbitrary n-dimensional arrays

**To Reproduce**
Use a function from mathjs which accepts a MathCollection or MathArray parameter in a typescript file. Try to apply the function to a 3D or greater dimensional array. Typescript linters will claim there is an incorrect type but the function should run normally and output the result as expected.

**Comment by josdejong** [comment]
Good point to see if we can improve on this 👍

**Comment by rakheesingh** [comment]
@josdejong what exactly need to improve herr, which functions doesn't take multi dimensional array?

**Comment by josdejong** [comment]
See #3099
