### ISSUE TITLE
Please get onto packagist!

### ISSUE THREAD

**Issue by Saeven** [josdejong/mathjs#310]
Thanks!
Alex

**Comment by josdejong** [comment]
Sure! Feel free to create a `composer.json` file and do a pull request to the `develop` branch.

**Comment by josdejong** [comment]
Nevermind I've added the file and created the component on packagist, wasn't much work.

Can you give it a try to see whether everything works as it shoud?

**Comment by josdejong** [comment]
Here is the url: https://packagist.org/packages/components/mathjs

**Comment by Saeven** [comment]
Beautiful! Like Christmas.
Thanks man
