### ISSUE TITLE
1/0 returns Infinity

### ISSUE THREAD

**Issue by akpi816218** [josdejong/mathjs#3105]
**Describe the bug**
dividing by zero gives Infinity, should be undefined or NaN

**To Reproduce**
```ts
import { evaluate } from 'mathjs';
console.log(evaluate('1/0'));
```

**Comment by kgryte** [comment]
The current behavior matches built-in JavaScript behavior for arithmetic operations.

```
console.log(1/0);
// => Infinity
```

**Comment by akpi816218** [comment]
while that may be, it's mathematically incorrect.

**Comment by kgryte** [comment]
That is not strictly true. While a common convention is to define division-by-zero as undefined, this is not a mathematical law, and, in different domains, defining division-by-zero to be infinity, zero, or signed infinity is perfectly valid.

**Comment by dvd101x** [comment]
Just for fun I tried `1/0` in Wolfram Alpha, Julia and Matlab and they yield Infinity. I understand the discussion might be more complex than this but I wanted to include these references. El 13 dic 2023, a la(s) 8:06 p.m., Athan ***@***.***> escribió:﻿
That is not strictly true. While a common convention is to define division-by-zero as undefined, this is not a mathematical law, and, in different domains, defining division-by-zero to be infinity, zero, or signed infinity is perfectly valid.

**Comment by josdejong** [comment]
We can discuss about what the best result would be for `1/0`, there are various valid choices: Infinity, NaN, undefined, or throwing an exception. We simply have to make a choice. For `mathjs` we did choose to return `Infinity` (similar to JavaScript, Mathematica, Matlab). At this point I think it's just fine to keep it like that, OK @akpi816218?

**Comment by akpi816218** [comment]
all right then, closing this issue
