### ISSUE TITLE
Different results when using String vs Number in bignumber function

### ISSUE THREAD

**Issue by bornova** [josdejong/mathjs#3137]
**Describe the bug**
Using a number value instead of string gives different results in the following case:
```javascript
math.evaluate(hex(bignumber(18446744073709552)))  // 0x4189374bc6a7ee
math.evaluate(hex(bignumber("18446744073709552")))  // 0x4189374bc6a7f0
```

**To Reproduce**
Visit: https://mathnotepad.com/#contents=N4IgzgLghhCmIC5RlgG1gYwgSwPYDtFRt8ATWAD0QEYAacaAJwkQAZ7Yy2BfesDRrlSoAKrgAOPDhXGNYYMHnxhEAbVAA3KKgCu8BCAAWlABQAjbAHN8OgLZnYjE9QAcAFjcA2AOwfW3gGZvVgBOAFYwgCYASmiAHXxjCnMrG3tHEziQVw8fP0Dg8Kis2JB6W1hoIm5eTW09RBAykAqqpBqAXXoNR0UCRAD6HXFSGFhSRsjWSLcAWlZqWZmRahCEaYQAzwA6VjCXAC0QbiA%3D

**Note**
Changing configuration to 'BigNumber' does fix the issue: `math.config({ number: 'BigNumber' })`:
```javascript
// With math.config({ number: 'BigNumber' })
math.evaluate(hex(18446744073709552))  // 0x4189374bc6a7f0
math.evaluate(hex("18446744073709552"))  // 0x4189374bc6a7f0
```

However, then the following expression gives an error, which may be a separate bug:
```javascript
// With math.config({ number: 'BigNumber' })
math.evaluate(format(-830, { notation: "hex", wordSize: 32 }))  // Error: Option "wordSize" must be a number

// can be fixed by doing:
math.evaluate(format(-830, { notation: "hex", wordSize: number(32) }))  // 0xfffffcc2i32
```

```javascript
// With math.config({ number: 'number' })
math.evaluate(format(-830, { notation: "hex", wordSize: 32 }))  // 0xfffffcc2i32
```

Thank you

**Comment by josdejong** [comment]
Try `console.log(18446744073709552)` in your developer console. By creating it as `number`, the value is already rounded off before it reaches the `bignumber(...)` constructor, since a JavaScript `number` can hold only about 16 digits.

**Comment by bornova** [comment]
Thank you @josdejong, that explains it.  How about the second part of the question where an error is throws when evaluating the following:
```javascript
// With math.config({ number: 'BigNumber' })
math.evaluate(format(-830, { notation: "hex", wordSize: 32 }))  // Error: Option "wordSize" must be a number
```

**Comment by josdejong** [comment]
You're welcome.

The function format does not support a `BigNumber` as `wordSize`, it would be neat to improve on that! Can you open a separate issue for that @bornova?
