### ISSUE TITLE
Config.epsilon doesn't seem to be working

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#3140]
On the current version V12.3.0, `config.epsilon` doesn't seem to be working.

The expected behavior is:

> epsilon. The minimum relative difference used to test equality between two compared values. This value is used by all relational functions. Default value is 1e-12.

```jl
equal(0, 1e-13)    # false but should be true
equal(0, 1e-14)    # false but should be true
equal(0, 1e-15)    # false but should be true
equal(0, 1e-16)    # true

config({epsilon: 1e-3})  # {"epsilon": 0.001, "matrix": "Matrix", ...
equal(0, 1e-4)     # false but should be true
equal(0, 1e-6)     # false but should be true
equal(0, 1e-7)     # false but should be true
equal(0, 1e-15)    # false but should be true
equal(0, 1e-16)    # true
```

Regardless of `config.epsilon`, it's as if the value of epsilon was `2.220446049250313e-16`
```jl
equal(0, 2.220446049250313e-16)     # true
equal(0, 2.220446049250314e-16)     # false
smallerEq(2.220446049250313e-16, 0) # true
smallerEq(2.220446049250314e-16, 0) # false
```
And it seems to be coming from this line of code.
https://github.com/josdejong/mathjs/blob/a131845524812c2117197cbfcbc8e054f8b73a24/src/utils/number.js#L596

I have not tested all relational functions but is seems consistent on the few I have tested.

Maybe it's also related to #3100

(Also tested V9.5.2, V10.6.4 and V11.12.0 with the same results)

**Comment by josdejong** [comment]
The nearly-equal comparison uses a relative equality. Comparing against zero is a special case.

Does this help: https://mathjs.org/docs/datatypes/numbers.html#equality?

**Comment by dvd101x** [comment]
Yes, thank you very much.

My bad, didn't notice that comparing against 0 was a special case.
