### ISSUE TITLE
How to check if an equation is correct/valid using math.js?

### ISSUE THREAD

**Issue by q2apro** [josdejong/mathjs#315]
I have the problem that I throw in an equation and would like to use math.js to check if it is valid, but as soon as I use `math.eval(equation)` or `math.parse(equation)` the web console says `SyntaxError: Unexpected end of expression (char ...)` (e.g. if it is "a+") or `Error: Undefined symbol ...` (e.g. if it is "test"). 

How do evaluate if the equation is correct then? 

		var fe = function(x) {
			var scope = {x: x};
			var expr = math.eval(func_equation, scope);
			return expr;
		};

I do not know where to put the try catch block. 

Thank you.

**Comment by josdejong** [comment]
The `math.eval` function can throw an error, so you should enclose that in a try/catch block. 

How you want to handle these errors though? Do you want to return an empty string or something? Or give the user an error message?
