### ISSUE TITLE
Issues in documentation for parsing

### ISSUE THREAD

**Issue by dvd101x** [josdejong/mathjs#3157]
Hi,

Documentation states that in a parser `getAll()` retrieves a map, but it's an object.

https://github.com/josdejong/mathjs/blob/cee9deb3772900b7ed03b9987f2a338cc595912d/docs/expressions/parsing.md?plain=1#L169-L170

The one that retrieves a map is `getAllAsMap` but it's not documented, fixing the grammatical error of "defined a variables" probably should be:

>  - `getAll()` 
   Retrieve an object with all defined variables in the parser's scope. 
>  - `getAllAsMap()` 
   Retrieve a map with all defined variables in the parser's scope. 

Reference

https://github.com/josdejong/mathjs/blob/cee9deb3772900b7ed03b9987f2a338cc595912d/src/expression/Parser.js#L99-L113

**Comment by josdejong** [comment]
Good find, we should update and clarify the docs!

**Comment by josdejong** [comment]
Fixed via #3158

**Comment by josdejong** [comment]
The fix is now published in `v12.4.0`
