### ISSUE TITLE
Invalid values for math.round

### ISSUE THREAD

**Issue by tusharmath** [josdejong/mathjs#316]
math.round(2.135, 2) // returns 2.13 when it should be 2.14

**Comment by josdejong** [comment]
Thanks, will fix it asap.

**Comment by josdejong** [comment]
While the direct cause was because of rounding issues in the `round` implementation of math.js, it turns out JavaScript itself has these issues itself too:

```js
(0.25).toFixed(1); // 0.3
(0.15).toFixed(1); // 0.1 oops!
```

Let's see what we can do about it...

**Comment by Yaffle** [comment]
JavaScript uses binary floating point, so `2.135 === 2.13499999999999978684`

**Comment by josdejong** [comment]
exactly...

**Comment by tusharmath** [comment]
I have faced the issue myself, so I created this custom Class to make it work.
```js
function Decimal(val) {
    var dotPosition, sVal;
    if (val instanceof Decimal) {
        this.p = val.p, this.m = val.m;
    } else {
        sVal = Number(val).toString();
        this.p = 0, this.m = parseInt(sVal.replace('.', ''), 10);
        dotPosition = sVal.indexOf('.');
        if (dotPosition !== -1) {
            this.p = sVal.length - dotPosition - 1;
        }
    }
}
Decimal.prototype.valueOf = function () {
    return this.m / Math.pow(10, this.p);
};

Decimal.prototype.mul = function (val) {
    var a = new Decimal(this),
        d = new Decimal(val);
    a.p += d.p;
    a.m *= d.m;
    return a;
};

Decimal.prototype.toFixed = function (precision) {
    var a, radix;
    a = new Decimal(this);
    radix = Math.pow(10, a.p - precision);
    a.m = Math.round(a.m / radix);
    a.p = precision;
    return a;
};
var r = new Decimal(2.135);
console.log(2.135.toFixed(2), r.toFixed(2).valueOf()); //Outputs: 2.13 2.14
```

**Comment by Yaffle** [comment]
you can use "big number" (used by mathjs) for "decimal arithmetic", and, possibly, you can avoid interpreting js number as "decimal fraction" fully if you use "decimal arithmetic" everywhere.

**Comment by josdejong** [comment]
We should indeed not rely on JavaScripts built in functions `toFixed`, `toExponential`, `toPrecision`. I've now created a little class [`NumberFormatter`](https://github.com/josdejong/mathjs/blob/develop/lib/util/NumberFormatter.js) which does not use JavaScript's functions but reads a value a string and handle the digits individually.

We could indeed use the functionality from decimal.js for formatting. I think though that it's important to keep these low-level number functions independend of decimal.js. In math.js v2 we want to be able to create custom builds of math.js, for example with big numbers excluded.
