### ISSUE TITLE
Incorrect Copyright and License for CSparse functions

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [josdejong/mathjs#3162]
All of the files in this folder: https://github.com/josdejong/mathjs/tree/develop/src/function/algebra/sparse are direct line-for-line copies of my CSparse libary here:
https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/dev/CSparse/Source .

A translation of my open-source CSparse software in mathjs can only be done with the correct copyright and license for the package.  Please add the following comments to each of the files in https://github.com/josdejong/mathjs/tree/develop/src/function/algebra/sparse:

```
// Copyright (c) 2006-2024, Timothy A. Davis, All Rights Reserved.
// SPDX-License-Identifier: LGPL-2.1+
// https://github.com/DrTimothyAldenDavis/SuiteSparse/tree/dev/CSparse/Source
```

The copyright notice should also be added to https://github.com/josdejong/mathjs/blob/develop/README.md:

```
CSparse: a Concise Sparse matrix package.
Copyright (c) 2006, Timothy A. Davis.
http://www.suitesparse.com

--------------------------------------------------------------------------------

CSparse is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

CSparse is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this Module; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
```

**Comment by kgryte** [comment]
For some context, the port to JS happened in 2015: https://github.com/josdejong/mathjs/pull/385

Looks like CSparse was not put on GitHub until 2019: https://github.com/DrTimothyAldenDavis/SuiteSparse/graphs/contributors

Just checking: is it possible that the software was not distributed under the same GPL license (or any license) back in 2015?

**Comment by DrTimothyAldenDavis** [comment]
No. It has been LGPL for its entire existence.

**Comment by DrTimothyAldenDavis** [comment]
The CSparse package was published in its entirety in my book, published by SIAM in 2006.
https://archive.siam.org/books/fa02
https://epubs.siam.org/doi/book/10.1137/1.9780898718881

And it has been under my copyright, and LGPL, since then (2006).

**Comment by josdejong** [comment]
Thanks for letting us know Tim Davis. I'm sorry that the attribution was not in place as it should. And big thanks for open sourcing this work in the first place!

For reference: the port of CSparse was added to mathjs in https://github.com/josdejong/mathjs/pull/385

I've created https://github.com/josdejong/mathjs/pull/3164 which adds the license information, @DrTimothyAldenDavis can you review it, please?

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the update -- it looks great!  This resolves this issue.  Thanks for the quick update.

I've also added a link to math.js on my SuiteSparse page, so JavaScript users can know about math.js, and its CSparse port in particular:
https://github.com/DrTimothyAldenDavis/SuiteSparse?tab=readme-ov-file#interfaces-to-suitesparse

**Comment by josdejong** [comment]
> I've also added a link to math.js on my SuiteSparse page, so JavaScript users can know about math.js, and its CSparse port in particular: https://github.com/DrTimothyAldenDavis/SuiteSparse?tab=readme-ov-file#interfaces-to-suitesparse

Nice, thanks!
