### ISSUE TITLE
Typescript signatures for add, multiply are incorrect

### ISSUE THREAD

**Issue by dmyronuk** [josdejong/mathjs#3180]
**Describe the bug**
From [the docs](https://mathjs.org/docs/reference/functions/add.html#function-add)
> Add two or more values, x + y. For matrices, the function is evaluated element wise... `math.add(x, y, z, ...)`

But the function takes exactly 2 arguments according to TS definition:
https://github.com/josdejong/mathjs/blob/02f195f70003a588cc5d4f0aad910aff2a2a57b7/types/index.d.ts#L1038

Same issue affects [multiply](https://mathjs.org/docs/reference/functions/multiply.html)

**To Reproduce**
`const x = math.add(1, 2, 3);`
Transpiler error: `Expected 2 arguments, but got 3.`

If you suppress the error with `@ts-ignore` the function works as expected.

**Comment by josdejong** [comment]
Thanks for reporting, will be fixed via 2e427ec3a9f61d7cc966b19309f668e2c3335720 (not yet published).

**Comment by josdejong** [comment]
Fix published now in `v12.4.2`
