### ISSUE TITLE
Complex numbers regression with math.js 1.5.0

### ISSUE THREAD

**Issue by gang65** [josdejong/mathjs#319]
With math.js 1.5.0 I noticed regression with complex numbers:
With math.js 1.4.0 (correct result):
   66i*i = -66

With math.js 1.5.0:
   66i*i = -6.6

https://bugs.launchpad.net/ubuntu-calculator-app/+bug/1439846

**Comment by josdejong** [comment]
Thanks, this issue was related to a bug in formatting negative numbers, see #317, I've fixed this yesterday and hope to publish a bugfix release today.

**Comment by josdejong** [comment]
This issue is resolved now in the just released v1.5.1 (website is not yet updated). Thanks!
