### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "mathjs". Relative references must start with either "/", "./", or "../".

### ISSUE THREAD

**Issue by DasGestirn** [josdejong/mathjs#3201]
Hi.

I downloaded mathjs using npm, but i'm having trouble actually using it. I need to use the complex numbers tools that the libray provides in one of my project's modules (a js file), but merely trying to import mathjs (as the documentation shows): 

`import { complex } from "mathjs";`

Is enough to give this error:

`Uncaught TypeError: Failed to resolve module specifier "mathjs". Relative references must start with either "/", "./", or "../".`

Everything else in my project is working just fine.

**Project folder structure:**

![VSCodium_v4EC5vACEj](https://github.com/josdejong/mathjs/assets/97317228/79a36539-3b36-48d4-bd49-58f64bd7ba6d)

**How to reproduce the error and observe it:**

1. Install mathjs using npm;
2. Try to import 'complex' from the mathjs library to the main.js module using the `import { complex } from "mathjs` command;
3. Open the html file inside the browser using Live Preview and then go the console.

**Comment by josdejong** [comment]
How can we reproduce your issue?

**Comment by DasGestirn** [comment]
> How can we reproduce your issue?

Hi Jos.

I added the project's folder structure and how to reproduce the error in the main post.

**Comment by DasGestirn** [comment]
After cracking my head for hours, the solution i've found was to use a module bundler (Vite) and to use the `import { create, all } from 'mathjs';` syntax to get it working. I didn't want to use Vite for such a small project, but that's how things have come to be.

Jon, before closing the issue, i'd like to know if there was a way to use the library without resorting to a module bundler, because it bloats my project massively. The documentation also doesn't mention the necessity of using one.

**Comment by josdejong** [comment]
So I understand that you want to use the library as ES module and without any bundlers like discussed in #1928?

You can use the browser bundle if you don't want to use a bundler, like `mathjs/lib/browser/math.js`.

**Comment by DasGestirn** [comment]
> So I understand that you want to use the library as ES module and without any bundlers like discussed in #1928?
> 
> You can use the browser bundle if you don't want to use a bundler, like `mathjs/lib/browser/math.js`.

Yes, correct. That was my intention.

Thanks, i will use this solution next time i need to use the library.

**Comment by DasGestirn** [comment]
> So I understand that you want to use the library as ES module and without any bundlers like discussed in #1928?
> 
> You can use the browser bundle if you don't want to use a bundler, like `mathjs/lib/browser/math.js`.

Yes, correct. That was my intention.

Thanks, i will use this solution next time i need to use the library.
