### ISSUE TITLE
Example `examples/advanced/convert_fraction_to_bignumber.js` broken

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#3212]
I noticed the example [`convert_fraction_to_bignumber.js`](https://github.com/josdejong/mathjs/blob/develop/examples/advanced/convert_fraction_to_bignumber.js) is broken, when running it, you get:

```
Error: There is already a conversion from "Fraction" to "BigNumber"
    at typed.addConversion ([...]\node_modules\typed-function\lib\umd\typed-function.js:2050:15)
    at [...]/mathjs/examples/advanced/convert_fraction_to_bignumber.js:33:12
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)
```

So, `typed-function` complains about a duplicate conversion, which is right. However, there is currently no way to get rid of the second conversion. There is a `typed.removeConversion()`, but that is very strict and requires to pass the actual conversion, but we don't have access to the conversion added by mathjs.

As a solution, we could:

1. make `typed.removeConversion()` less strict, requiring to pass only `{ from, to }` and not the test function.
2. make a function `typed.getConversions()`, so you can look up the existing conversion and then pass that to the (strict) method `typed.removeConversion()`.
3. extend `typed.addConversion()` with an optional second argument `{ override: true }` that allows overriding an existing conversion without having access to it.

I think I both options (1) and (3): I think `typed.removeConversion()` is needlessly strict, and from an user point of view it would be most convenient to override an existing conversion (rather than having to look up the existing conversion and removing it first).

**Comment by yaojiejia** [comment]
Hi Jos, after I run the convert_fraction_to_bignumber.js, I got:
```
Fraction 7/12
Complex 2
BigNumber 3.4
```
It seems everything is working, is the issue fixed already?

**Comment by josdejong** [comment]
OOo, yes, I've fixed that recently via https://github.com/josdejong/mathjs/commit/060219854055c941bde614e1a78ab86b015e44ec. Will close this issue now.
