### ISSUE TITLE
modulus of bigNumber

### ISSUE THREAD

**Issue by nycos62** [josdejong/mathjs#3214]
Hello, while trying to compute the digital root of factorial, I ends up on this weird result

`math.config({  number: 'BigNumber',  precision: 509  }) `
`math.mod(math.BigNumber('620448401733239439359999'), 9).toFixed()`
`//result : -1 but should be 8`

is there something I missed or is it an error in the math.js library ?

formula for digital root:   
`//1+ (number-1)%9 => overflow int`
`math.add(math.mod(math.subtract(number, 1), 9), 1)`

**Comment by josdejong** [comment]
Thanks for reporting, this is a bug.

Trying out on Wolfram Alpha gives 8 as result too: https://www.wolframalpha.com/input?i=620448401733239439359999+%25+9

Anyone able to help debugging this issue?

**Comment by nycos62** [comment]
it seems to come from math.floor function
[https://www.wolframalpha.com/input?i=floor%2868938711303693271039999.888888888%29](https://www.wolframalpha.com/input?i=floor%2868938711303693271039999.888888888%29)

`math.floor(math.bignumber('68938711303693271039999.888888888')).toFixed()`
`// =>'68938711303693271040000' instead of '68938711303693271039999'`

**Comment by josdejong** [comment]
o wow, it's this pitfall related to using bignumber but still having `relTol` and `absTol` configured for numbers. This solves it:

```js
math.config({
  number: 'BigNumber',
  relTol: 1e-60,
  absTol: 1e-63
})

math.mod(math.bignumber('620448401733239439359999'), 9).toString()
// 8

// or using evaluate:
math.evaluate('620448401733239439359999 % 9').toString() 
// 8
```

See docs: https://mathjs.org/docs/datatypes/bignumbers.html#usage

Still thinking, how can we prevent people (including me) from falling into this trap? 🤔

**Comment by josdejong** [comment]
See also: https://github.com/josdejong/mathjs/issues/2608

**Comment by nycos62** [comment]
thank you so much, I don't remember ever seen relTol and absTol in parameters... Sorry, I should read again the documentation on new versions... my bad...
maybe is there a way ,when setting up math.config.number as BigNumber , to automatically set up these values ? relTol: 1e-60,
  absTol: 1e-63 under the hood ?

**Comment by nycos62** [comment]
nevermind..
updated from v12.3.2 to v13.0.0
it's working like a charm :

```
math.config({
  number: 'BigNumber',
  precision:509,
  relTol: 1e-505,
  absTol: 1e-508
})
math.mod(math.bignumber('620448401733239439359999'), 9).toString()
//8

```

**Comment by nycos62** [comment]
v12.3.2 no ok but v13.0.0 => ok

**Comment by josdejong** [comment]
Good to hear you have a working solution now!

> I don't remember ever seen relTol and absTol in parameters

That's correct, it's brand new in `v13`, released a few days ago :). Formerly, it was called `epsilon`.
