### ISSUE TITLE
valueOf()  return ?

### ISSUE THREAD

**Issue by marsDes** [josdejong/mathjs#3217]
```js
typeof  math.multiply(1,2).valueOf()  // number   2

typeof math.multiply(math.bignumber(1.0),2).valueOf()  // string  '2'
`

**Comment by marsDes** [comment]
@josdejong

**Comment by josdejong** [comment]
Yes, that is how it works.

`BigNumber` converts into a string because normally its value cannot be represented correctly using a `number` (otherwise there would be no reason to use `BigNumber` in the first place).

**Comment by josdejong** [comment]
Closing due to a lack of response.
