### ISSUE TITLE
MathJS 13.0.0 is not compatible with ES6

### ISSUE THREAD

**Issue by diseraluca** [josdejong/mathjs#3227]
The README for Math.js states that 

> Math.js works on any ES6 compatible JavaScript engine [...]

Nonetheless, the minified version for version 13.0.0 (downloaded from https://cdnjs.com/libraries/mathjs or directly installed from npm) contains a catch block without a catch parameter (line 2, column 180523).

`[...]catch{}[...]`

This form of a catch block is only valid from ES2019 (https://262.ecma-international.org/10.0/) and is thus incompatible with ES6 engines.

**Comment by josdejong** [comment]
Thanks for reporting! Fixed via d8cc47a6cb0c0eba97e2aa85ae5389e83d958c9f

**Comment by Elgot** [comment]
There are also bigint suffixes (like 0n), which seems to be ECMAScript 2020.

**Comment by josdejong** [comment]
Hm, that is a good point. 

I've had a look to see if we can convert BigInt code into ES6 compatible (polyfillable) code, but couldn't find that.

I've update the docs to mention that mathjs requires ES 2020 or newer. 

If there is a big need for compatibility with older JS engines I'm open to a PR that creates a bundle for legacy JS engines.
