### ISSUE TITLE
format notation option type missing `'hex'/'bin'/'oct'`

### ISSUE THREAD

**Issue by Oddwerth** [josdejong/mathjs#3232]
**Describe the bug**
In the [documentation](https://mathjs.org/docs/reference/functions/format.html), it is written that we can use 'hex'/'bin'/'oct' as a notation value, in the format function. These option are working, but we get a typescript error when we use them. 
The typescript union is written as follow :
`notation?: 'fixed' | 'exponential' | 'engineering' | 'auto'`
When it should look like this : 
`notation?: 'fixed' | 'exponential' | 'engineering' | 'auto' | 'hex' | 'bin' | 'oct'`

**To Reproduce**
Use the `math.format()` function, with the notation option as 'hex' :
`format(50, { notation: "hex" })`
Error: `Type "hex" is not assignable to type "fixed" | "exponential" | "engineering" | "auto" | undefined`

**Comment by josdejong** [comment]
Thanks for reporting, fixed via c118eaec90481a813eda117fe158301abd2acfa0

**Comment by josdejong** [comment]
Fix published now in `v13.0.3`
