### ISSUE TITLE
Incorrect answer of math.evaluate("x+y%")

### ISSUE THREAD

**Issue by Kiritorz** [josdejong/mathjs#3237]
Using `math.evaluate()` to calculate expression like `"x+y%"` will get `x+x*y*0.01` but the answer should be `x+y*0.01`

```javascript
// math-test.mjs
import { evaluate } from "mathjs";
const exp = "2+1%";
console.log(exp + " = " + evaluate(exp)); // 2+1% = 2.02
```

**Comment by josdejong** [comment]
This is intended behavior, implemented in #2304. If you want to calculate `x+y*0.01` you can use parenthesis, like `'2+(1%)'` .
