### ISSUE TITLE
`leafCount` is missing from typings

### ISSUE THREAD

**Issue by veggiesaurus** [josdejong/mathjs#3246]
**Describe the bug**
The function `leafCount(expr)` is described in the [docs](https://mathjs.org/docs/reference/functions/leafCount.html), and works fine. However, it is missing from the typescript definitions

**To Reproduce**
Try to use `leafCount` in a typescript file.

**Comment by josdejong** [comment]
Fixed now via https://github.com/josdejong/mathjs/commit/4c64018a79cc14a86c62cfb53498fde209b69630 (not yet published)

**Comment by josdejong** [comment]
Published now in `v13.2.0`
