### ISSUE TITLE
SyntaxError:No identifiers allowed directly after numeric literal

### ISSUE THREAD

**Issue by fyhhub** [josdejong/mathjs#3248]
**Describe the bug**
IOS 13.x  safari
SyntaxError:No identifiers allowed directly after numeric literal

![image](https://github.com/user-attachments/assets/4e3aeb39-19c1-47aa-9906-a07105a33977)

**Comment by josdejong** [comment]
mathjs 13 requires `bigint` support.

**Comment by fyhhub** [comment]
> mathjs 13 requires `bigint` support.
ok   thanks
