### ISSUE TITLE
 mathjs , round( 1.8549999999999998, 2);  Why is the result 1.86 .

### ISSUE THREAD

**Issue by ningshunqiang** [josdejong/mathjs#3270]
mathjs v13.0.3 , round( 1.8549999999999998, 2);  Why is the result 1.86 .

I expected 1.85

**Comment by josdejong** [comment]
Mathjs has logic in place to deal with round off errors like value `1.8549999999999998` has. This value is most likely the result of a floating point operation, and most likely should have been `1.855`. Mathjs first restores this round-off error resulting in `1.855`, and next, applies the rounding on the restored value, resulting in `1.86`. 

Similarly, mathjs will consider `1.855` and `1.8549999999999998` equal:

```js
math.equal(1.8549999999999998, 1.855) // true
```

Mathjs does this by determining whether two numbers are [nearly equal](https://mathjs.org/docs/datatypes/numbers.html#equality). If you do not want this behavior, you can use BigNumbers and configure a smaller `relTol` and `absTol`.

**Comment by josdejong** [comment]
Closing due to a lack of response.
