### ISSUE TITLE
TypeError: Cannot set properties of undefined (setting 'constructor')

### ISSUE THREAD

**Issue by WangGuan11** [josdejong/mathjs#3279]
<img width="1043" alt="iShot_2024-10-08_15 40 53" src="https://github.com/user-attachments/assets/afb27d3b-f3d0-4527-8cbb-839e4ee06be3">

对于遇到这个问题的人，想要快速解决的方式，更换2.1.1 的版本的包，怕你们找不到，下面附上链接。

UPDATE: download removed by maintainer. Please install complex.js via npm.

把这个包替换原来的在 node_modules 的 complex，会提示 文件找不到，因为路径有点不一样
<img width="470" alt="企业微信截图_807d19b3-fa70-4913-b122-4b40047c8d1c" src="https://github.com/user-attachments/assets/ddf9f486-fe2b-4e49-824b-c66805e2a1db">
可以手动创建dist 文件夹，然后丢两个文件进去就好了

**Comment by jiahwei** [comment]
package.json中指定complex.js版本就可以
```package.json
    "complex.js": "2.1.1",
    "mathjs": "^13.1.1",
```

**Comment by josdejong** [comment]
Guys, please use English so everyone can join the conversation.

I've remove the download file, it's better and safer to download via npm.

**Comment by josdejong** [comment]
Closing this issue in favor of #3277

**Comment by josdejong** [comment]
@WangGuan11 what version of Webpack are you using?

**Comment by WangGuan11** [comment]
> @WangGuan11你使用的 Webpack 是什么版本？

@josdejong  i use Vue2.7

**Comment by josdejong** [comment]
Thanks of letting us know!

**Comment by josdejong** [comment]
@WangGuan11 and what version of Webpack do you use?

**Comment by WangGuan11** [comment]
> @WangGuan11 and what version of Webpack do you use?

@josdejong  i use Node 14.17.0 and I want to know what version of Mathjs I should use

**Comment by WangGuan11** [comment]
> package.json中指定complex.js版本就可以
> 
> ```json
>     "complex.js": "2.1.1",
>     "mathjs": "^13.1.1",
> ```

@josdejong  13.1.1 is too high， I was 11.12.0 before

**Comment by josdejong** [comment]
You can choose an older version of `mathjs` too, only thing necessary part is `"complex.js": "2.1.1"`.

Do you know what version of Webpack is used in your `vue` setup?

**Comment by josdejong** [comment]
This issue has been solved in `complex.js@2.2.4`.
