### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by FSMaxB** [josdejong/mathjs#329]
@josdejong Could you please make a release? ( 1.6 maybe, because my changes to `toTex` quite substantially change the LaTeX output ). This way I could build on my latest work without having to ship a development version. There's still work to do on the LaTeX front, but that won't happen right now.

**Comment by josdejong** [comment]
Sure! I will do that tonight (wanted to do that last weekend already...)

**Comment by FSMaxB** [comment]
Okay, thanks.

**Comment by josdejong** [comment]
I've released v1.6.0 containing your improvements in toTex. Enjoy :)
