### ISSUE TITLE
Floor function with BigNumbers unexpected answer

### ISSUE THREAD

**Issue by mcnole25** [josdejong/mathjs#3295]
The floor function with bignumbers is sometimes returning the incorrect answer.

Like when you type "math.evaluate(floor(10000000000000000000.8))" (must be a BigNumber) It rounds to the nearest integer instead of truncating.

The same thing happens with mod. "77777777777777777.777 % 1" returns -0.223 instead of 0.777.

**Comment by rana-aakash** [comment]
Are not you using it like this

console.log(math.evaluate('floor(10000000000000000000.8)'))
console.log(math.evaluate('77777777777777777.777 % 1'))

My outputs are:
10000000000000000000
0

**Comment by nkumawat34** [comment]
> Are not you using it like this
> 
> console.log(math.evaluate('floor(10000000000000000000.8)')) console.log(math.evaluate('77777777777777777.777 % 1'))
> 
> My outputs are: 10000000000000000000 0
I am also getting same answer.

**Comment by nkumawat34** [comment]
> The floor function with bignumbers is sometimes returning the incorrect answer.
> 
> Like when you type "math.evaluate(floor(10000000000000000000.8))" (must be a BigNumber) It rounds to the nearest integer instead of truncating.
> 
> The same thing happens with mod. "77777777777777777.777 % 1" returns -0.223 instead of 0.777.

can you elaborate more.

**Comment by josdejong** [comment]
First issue: the function `evaluate` expects a string, so `"math.evaluate(floor(10000000000000000000.8))"` should be `math.evaluate("floor(10000000000000000000.8)")` instead. I guess that is just a wrong copy/paste in this issue though.

Second issue: by default, function `evaluate` will parse numeric values into a regular `number`, which cannot hold that much digits. So you can either configure to parse as bignumbers, or use the function `bignumber`:

```js
// WRONG
console.log(math.evaluate('floor(10000000000000000000.8)')) 
// number 10000000000000000000

// RIGHT
math.config({ number: 'BigNumber'})
console.log(math.evaluate('floor(10000000000000000000.8)').toString()) 
// BigNumber 10000000000000000001

// RIGHT
console.log(math.evaluate('floor(bignumber("10000000000000000000.8"))').toString()) 
// BigNumber 10000000000000000001
```
