### ISSUE TITLE
Precedence of % (mod) is higher than * and /

### ISSUE THREAD

**Issue by gwhitney** [josdejong/mathjs#3301]
The issues section is used only for bug reports. Please use the [Discussions](https://github.com/josdejong/mathjs/discussions) section to ask questions and share ideas and suggestions.

**Describe the bug**
Unlike in any other language I have checked, the precedence of `%` (or `mod`) used as a binary remainder operator is higher than * and /. As it is essentially a division operation, its precedence should be the same as * and /, as it is in essentially every other language checked.

**To Reproduce**
Evaluate `3.6 * 28 % 25`. Currently mathjs produces 10.8 = 3.6 * 3 = 3.6 * (28 % 25). It should produce 0.8 = 100.8 % 25 = (3.6 * 28) % 25, as multiplicative/division operators should be evaluated left to right.

**Comment by nkumawat34** [comment]
can i work on this issue.

**Comment by nkumawat34** [comment]
![Screenshot (29)](https://github.com/user-attachments/assets/6b1a9f00-906b-465f-99c7-b605b2d5f66a)
They have written in their document

**Comment by gwhitney** [comment]
Yes, the mathjs documentation is clear on this behavior. It is just different than just about any other system. But I would not recommend working on changing it unless the designer @josdejong agrees there should be a change. He may have his reasons for the unusual behavior, which I would respect. So this issue was more of a proposal/query as to why the departure from norms. I think if the current behavior is retained, such a rationale should be added to the documentation.

**Comment by josdejong** [comment]
Thanks for bringing this up Glen. The precedence of the modulus operator regularly leads to questions and unexpected behavior. I think it would be a good thing to bring bring the behavior in line with other applications: let module have the same precedence as multiplication and division.

Originally, modulus had the same precedence as multiplcation and division. I think the precedence was accidentally changed as as unintened side effect of implementing support for using `%` as percentage in #2304. See also (https://github.com/josdejong/mathjs/issues/3189#issuecomment-2082242733.

It would be great if you can pick this up @nkumawat34 , though it's not the easiest first issue. Do you like a challenge? 😉

**Comment by nkumawat34** [comment]
I will pick it.

**Comment by josdejong** [comment]
Thanks

**Comment by nkumawat34** [comment]
Please review my PR #3311

**Comment by josdejong** [comment]
👍 I'll look into it this week, thanks!!

**Comment by josdejong** [comment]
Fixed now in `v14.0.0`.
