### ISSUE TITLE
eigs method return different vectors per version (10 vs 13)

### ISSUE THREAD

**Issue by entelostre** [josdejong/mathjs#3304]
**Describe the bug**

I call eigs like that:

let covariance = [[99.15192547870485, -206.05811568043288], [-206.05811568043288, 791.0897678733841]];
eigs(covariance);

Results per mathjs version:

**v13.1.1**
console.log(eigs.eigenvectors.map(e => e.vector));
[[0.9641465805245403, 0.2653702531611938], [-0.2653702531611938, 0.9641465805245403]]

**v10.3.0**
 console.log(eigs.vectors) 
[[0.9641465805245403, -0.2653702531611938], [0.2653702531611938, 0.9641465805245403]]

**Comment by nkumawat34** [comment]
can i work on this issue

**Comment by nkumawat34** [comment]
it is only coming with real symmetric matrices or did you check with more matrices also.

**Comment by nkumawat34** [comment]
in case of 10.2.0 version eigen vectors are coming in column wise for eigen values
in case of 13.2.0 version eigen vector you are printing coming in row wise for eigen values.

**Comment by josdejong** [comment]
Thanks for looking into this @nkumawat34 . If I understand you, the results are different but are both valid, right?

**Comment by nkumawat34** [comment]
yes

**Comment by josdejong** [comment]
Thanks, that makes sense indeed. I think that was changed in `v12.0.0` via #3037. 

Closing this issue now.
