### ISSUE TITLE
Performance issue with `range`

### ISSUE THREAD

**Issue by twitwi** [josdejong/mathjs#3321]
**Describe the bug**

I was exploring array slicing/subset (I'm technically trying to implement numpy slicing).
I realized that `range` creation is not O(1).

For instance `math.range(0, 100000)` takes more than a second, and is even slower than `Array.from({length: 100000}, (_,i)=>i)` (which cannot be O(1) anyway).
This prevents its use for instance for a typical use case that would used `subset` to say "remove the first and last element".

**Comment by twitwi** [comment]
I guess this issue is too specific and my requirement closer to https://github.com/josdejong/mathjs/discussions/2702 so I'm closing to reduce noise.

**Comment by josdejong** [comment]
Thanks, I did a little test and it looks like `math.range` is about 25% times slower than the optimum. Now, the function is more versatile than a simple `Array.from`: it supports data types `number`, `BigNumber`, and `Unit`. It supports different steps and also negative steps, and it supports either including or excluding the end.

I guess we can optimize this function, but I think we should be careful not to overengineer this.

The current implementation is here: https://github.com/josdejong/mathjs/blob/develop/src/function/matrix/range.js#L135-L146

**Comment by twitwi** [comment]
Thank you for the details. I was using it for `index` so I saw it more as a concept (that we can iterate but does not allocate any array). Indeed gaining 25% would not be worth the effort I'd say.
