### ISSUE TITLE
Matrix / vector multiplication returns unexpected results

### ISSUE THREAD

**Issue by mauritslamers** [josdejong/mathjs#334]
I am currently trying to port an algorithm written in Python (using numpy) to JS.
I will admit up front that I don't know python very well, and also not the mathematical rules behind matrices and vectors.

What I noticed though is, that in Python a multiplication between a vector and a matrix seems to return different results, as in that mathjs will reduce the number of dimensions, where python does not:

```python
import numpy;
a = numpy.array([ [ 1,1], [2,2], [3, 3]])    # two dim array
b = numpy.array([1, 2])                      # one dim array
a*b # result: array([[1, 2], [2, 4], [3, 6]]) 
```

When I do the mathjs equivalent however:

```javascript
var a = mathjs.matrix([ [ 1, 1], [2, 2], [3, 3] ]);
var b = mathjs.matrix([1, 2]);
mathjs.multiply(a*b); // result is [3, 6, 9]
```

Why do these results differ and how could I implement something like the Python multiplication using mathjs?

**Comment by FSMaxB** [comment]
I don't know what numpy is doing there, but multiplying a 3x2 matrix with a vector (2x1 matrix) has a 3x1 matrix as result. So what mathjs is doing here is the mathematically correct thing to do (see https://en.wikipedia.org/wiki/Matrix_multiplication )

What numpy seems to do here is an elementwise multiplication. It multiplies the first value from the vector with the first value of the first row of the matrix, the second value of the vector with the second value of the first row of the matrix. The first value of the vector with the first value of the second row of the matrix and so on. I don't know numpy, but there should be a function that does matrix multiplication. When using that, the result should be the same for mathjs and numpy.

**Comment by mauritslamers** [comment]
@FSMaxB Thanks for your reply! 

Does this mean that MathJS does not have a method for elementwise multiplication?

**Comment by josdejong** [comment]
@mauritslamers for element wise multiplication you can use the function `dotMultiply` (and in the expression parser you can use the `.*` operator).

**Comment by mauritslamers** [comment]
@josdejong wonderful! Thanks for the replies. As a side question, is there an IRC channel for MathJS? It would be very useful to be able to ask questions in a more direct way.

**Comment by mauritslamers** [comment]
Interestingly though, the dotMultiply doesn't work on arrays or matrices of different dimensions.

**Comment by josdejong** [comment]
There is no IRC channel or something like that, this github issues section is the best place to ask questions.

What is `b` in your example? Is it a matrix? If you pass two matrices to `dotMultiply`, the function will multiply them element wise, and they need to have the same size for this. For example `math.dotMultiply([2,3],[4,5])` will return `[8,15]`.

**Comment by mauritslamers** [comment]
I am trying to port a MelCepstrum algorithm from python to javascript (https://github.com/jameslyons/python_speech_features/blob/master/features/base.py). 

The line a and b come from is https://github.com/jameslyons/python_speech_features/blob/master/features/sigproc.py#L33,
which is the frames*win line from the example below, which is part of a function which frames a signal into overlapping frames.

```python
    indices = numpy.tile(numpy.arange(0,frame_len),(numframes,1)) + numpy.tile(numpy.arange(0,numframes*frame_step,frame_step),(frame_len,1)).T
    indices = numpy.array(indices,dtype=numpy.int32)
    frames = padsignal[indices]
    win = numpy.tile(winfunc(frame_len),(numframes,1))
    return frames*win
```
frames is a subset of a series of samples with padding added, which is a one dimensional array.
winfunc(frame_len) will return a 1D array with length frame_len, filled with ones.
The numpy.tile line will create a 2D repeated array of the 1D array created with winfunc, the example below is the JS equivalent.

```
MelCepstrum.tile(math.ones(2), [2, 1]) // returns [ [ 1, 1], [1, 1] ]
```

**Comment by josdejong** [comment]
Thanks for the explanation, so if I understand it correctly both a and b are arrays. In that case you will indeed have to loop over the 2D array yourself.
