### ISSUE TITLE
Combinatorics Module

### ISSUE THREAD

**Issue by devanp92** [josdejong/mathjs#339]
Is it possible to create a combinatorics module? This includes integer partitions, Stirling numbers of the second kind/Bell Numbers, compositions, set partitions, etc. This can go into the probability module.

**Comment by josdejong** [comment]
Yes, functionality for combinatorics would be great. 

If anyone is interested in contributing here please let me know.

**Comment by devanp92** [comment]
Great. I can work on it.

**Comment by josdejong** [comment]
That would be great, thanks. Please let me know if you need any directions.
