### ISSUE TITLE
math.zeros cannot be optimized because of the way arguments is used

### ISSUE THREAD

**Issue by mauritslamers** [josdejong/mathjs#340]
While profiling my code which uses mathjs, I noticed that the use of mathjs.zeros could not be optimized because of the way arguments was used.

Specific spot:
https://github.com/josdejong/mathjs/blob/master/lib/function/matrix/zeros.js#L49

Because arguments is used non-locally (in this case given as argument to a function which is not Function.apply), it needlessly slows down execution.

It is better to copy it locally, even if that means you add extra code. See also: 
https://github.com/petkaantonov/bluebird/wiki/Optimization-killers

Looking at the code, adding copying code doesn't seem to be really necessary, as something like this should also work:

```
	   math.zeros = function zeros (_m, _n, _format) {
	   	var numArgs = arguments.length;
	   	var m = _m,
	   			n = _n,
	   			format = _format;

	   	if (!format) {
	   		if (m instanceof Matrix) {
	   			format = size.storage();
	   		}
	   		else if (!isArray(m) && config.matrix === 'matrix') {
	   			format = 'default';
	   		}
	   	}

	   	var args = [];
	   	if (m) args.push(m)
	   	if (n) args.push(n);
	   
	   // convert arguments from bignumber to numbers if needed
	   var asBigNumber = false;
	   // map arguments & validate
	   args = args.map(function (value) {
	     // check it is a big number
	     if (value instanceof BigNumber) {
	       // set flag
	       asBigNumber = true;
	       // convert it
	       value = value.toNumber();
	     }
	     // validate arguments
	     if (!isNumber(value) || !isInteger(value) || value < 0) {
	       throw new Error('Parameters in function eye must be positive integers');
	     }
	     return value;
	   });

	   	// default value
	   	var defaultValue = asBigNumber ? new BigNumber(0) : 0;

	   
	   	// check we need to return a matrix
	   	if (format) {
	   	  // create empty matrix
	   	  var m = math.matrix(format);
	   	  // check we need to resize matrix
	   	  if (args.length > 0) {
	   	    // resize it to correct size
	   	    return m.resize(args, defaultValue);
	   	  }
	   	  return m;
	   	}
	   	// empty array
	   	var res = [];
	   	// check we need to resize array
	   	if (args.length > 0) {
	   	  // resize array
	   	  return array.resize(res, args, defaultValue);
	   	}
	   	return res;

	   };
```

This code example is taken from mathjs 1.5.1.

BTW: it is kind of strange to see the error telling that this function is eye...

**Comment by FSMaxB** [comment]
I fixed the error message, but I don't want to mess with the arguments because I don't completely understand what it's doing there  at this point.

**Comment by josdejong** [comment]
Good point @mauritslamers, I recently figured this out the hard way: passing `arguments` to another function disables optimization of the function :(. This will be fixed in v2 (most functions using `argsToArray` aren't yet refactored, but in the end the `argsToArray` will be redundant).

**Comment by josdejong** [comment]
This has been resolved in v2
