### ISSUE TITLE
Removing nodes from a node tree via transform

### ISSUE THREAD

**Issue by FSMaxB** [josdejong/mathjs#349]
I'm currently working on implementing the different parenthesis options and the `ParenthesisNode` to support that. My current approach is using the node tree with `ParenthesisNodes` for the `'keep'` option and creating a copy of the node tree which has the `ParenthesisNodes` removed for the `'always'` and `'auto'` options. This approach creates the overhead of cloning the entire node tree, but it makes the code much easier and more maintainable.

But to come to the point, I don't get this to work (removing `ParenthesisNodes` from a node tree). I haven't been able to understand `transform` properly.

Here's what I've tried so far:

First the shared code:
```js
/**
   * Get the next Node in the tree that isn't a ParenthesisNode.
   * @return {Node} node
   **/
  Node.prototype.getContent = function () {
    var node = this;
    while (node.isParenthesisNode) {
      node = node.content;
    }
    return node;
  }
```
First try, using return:
```js
nodeTree.transform(function (node) {
  return node.getContent();
});
```
This get's rid of the highest level `ParenthesisNode` but that's it. Doesn't work on the entire tree.

Next try:
```js
nodeTree.transform(function (node) {
  node = node.getContent();
}
```
Doesn't work. I returns undefined, because the callback doesn't return anything, so this is equivalent to just using `traverse` here. Also I'm only overwriting the local reference, so nothing that isn't expected.

So next try:
```js
nodeTree.transform(function (node, path, parent) {
  if (parent !== null) {
    parent[path] = node.getContent();
  }
  else {
    return node.getContent();
  }
}
```
This does the same thing as the first try. I also tried adding `return` to the line with `parent[path]` but still not the expected result.

I tried understanding the way transform works by following the recursive function calls in my head, but the stack trace in my head more or less blew my mind.

Do you have any suggestion how I can remove nodes from a node tree by using one of the functions for modifying node trees?

**Comment by josdejong** [comment]
I think these parenthesis options `keep`, `auto`, `always` should not mutate the node tree but only be used for `toTex` and `toString`, or not? Manipulating / normalizing / cleaning-up the node tree is a different story, and you should be able to do this easily with `transform`.

About the issue with:
```js
nodeTree.transform(function (node) {
  return node.getContent();
});
```
This is a bug, this should work. I assumed that if the returned node is not the original node, there is no need to traverse about this replacement, but that's a wrong assumption. I've just fixed this in the develop branch.

**Comment by FSMaxB** [comment]
I'm not mutating the node tree, but creating a copy that is then mutated. When `toString` or `toTex` is called, the node tree without `ParenthesisNodes` is stored within the root node so that it doesn't have to be created all over again, when calling `toTex` or `toString`.

The reason why I create a separate node tree without `ParenthesisNodes` is that with those nodes, the `toString` and `toTex` logic of the nodes would need to be much more complicated and duplicate or even triple large parts of the logic. This makes it much cleaner from a code perspective.

This has the following consequences:
* In `'keep'` mode, the performance is better than without the copying approach, because the node tree doesn't need to be copied and it requires less case/if-else
* In `'auto'` and `'all'` mode, the performance is slower and the memory usage is higher, because the node tree is copied once.

**Comment by Lakedaemon** [comment]
On 05/02/2015 08:57 PM, Max Bruckner wrote:
>
> I'm not mutating the node tree, but creating a copy that is then 
> mutated. When |toString| or |toTex| is called, the node tree without 
> |ParenthesisNodes| is stored within the root node so that it doesn't 
> have to be created all over again, when calling |toTex| or |toString|.
>
> The reason why I create a separate node tree without 
> |ParenthesisNodes| is that with those nodes, the |toString| and 
> |toTex| logic of the nodes would need to be much more complicated and 
> duplicate or even triple large parts of the logic. This makes it much 
> cleaner from a code perspective.
>
> This has the following consequences:
>
>   * In |'keep'| mode, the performance is better than without the
>     copying approach, because the node tree doesn't need to be copied
>     and it requires less case/if-else
>   * In |'auto'| and |'all'| mode, the performance is slower and the
>     memory usage is higher, because the node tree is copied once.
>
> —
>

Instead of cloning the Tree, might it be possible to decorate it ?
Say, you build a lightweight hashMap that maps nodeTree to whatever 
structure you need to make 'auto' and 'all' work ?

performance might not be that important for 'auto' and 'all' anyway, 
because it mainly exists for displaying purposes and it will have to go 
through other costly transformations before the user can see it (say 
MathJax processing and mathml + css rendering on the browser)

**Comment by FSMaxB** [comment]
@Lakedaemon The reason why I copy the node tree in the first place is to make the code easier, not to complicate it. But I agree, the performance impact shouldn't be too bad in practice (If people don't create incredibly large node trees with thousands of nodes, but I don't have numbers to back this up).

@josdejong I think I'll have a pull request ready in a few days. For now I've cherry picked your bugfix into my feature branch, because I gave up merging develop into v2 after having to port the new combinatorics functions to factory functions ( and making typed functions out of them ).

**Comment by josdejong** [comment]
@FSMaxB thanks, I get the point. I don't have a 100% clear picture of the coupling between parents and childs which makes this hard, but I know it's not trivial. It would be great if there was an easier way. I don't know, maybe `operators.getPrecedence` and `operators.getAssociativity` could have an option passed to iterate to the childs of `ParenthesisNodes` or something like that.

Just one little remark: you could refactor
```js
  Node.prototype.getContent = function () {
    var node = this;
    while (node.isParenthesisNode) {
      node = node.content;
    }
    return node;
  }
```

into:
```js
  Node.prototype.getContent = function () {
    return this;
  }

  ParenthesisNode.prototype.getContent = function () {
    return this.content;
  }
```

So the two implementations remain decoupled (`Node` should not know about `ParenthesisNode` or any of it's implementations)

**Comment by FSMaxB** [comment]
Hm, maybe you're right, there might be a way to avoid copying the entire node tree.

**Comment by FSMaxB** [comment]
Yes, it's totally possible to implement this without having to copy the entire node tree.

**Comment by josdejong** [comment]
Sounds promising Max. For me most important here is finding a simple, transparent solution, not per se the best performing. I don't know if that will mean copying and normalizing the node tree or extending a few methods like `getPrecedence` with an extra option.
