### ISSUE TITLE
integration and differentation

### ISSUE THREAD

**Issue by ChrisRaven** [josdejong/mathjs#35]
Hi,
is it possible to add integrals and differentials to the library?
Or maybe it already is added, but I didn't spot it.

**Comment by BigFav** [comment]
If I were to start working on this, where specifically should I be looking? Should I be making a transform?

**Comment by josdejong** [comment]
This would be awesome :)

Please implement this in the `v2` branch, merging from `develop` would be painful. Maybe the best place for these new functions is in [/lib/expression/function](https://github.com/josdejong/mathjs/tree/v2/lib/expression/function) or a subfolder there.

I think you can develop these functions in two steps: 
- First make a low level function which accepts a Node tree as input. On this node tree you can do manipulations, maybe using methods like [`Node.transform`](https://github.com/josdejong/mathjs/blob/v2/docs/expressions/expression_trees.md#methods).
- For use in expressions you could create a [transform](https://github.com/josdejong/mathjs/blob/v2/docs/expressions/customization.md#function-transforms) on top of this low level function which uses [custom argument parsing](https://github.com/josdejong/mathjs/blob/v2/docs/expressions/customization.md#custom-argument-parsing), so you get a node tree as input.

**Comment by FSMaxB** [comment]
It's not clear to me if you are talking about numeric integration or algebraic integration.

**Comment by josdejong** [comment]
@BigFav you where thinking about algebraic integration right?

**Comment by rjbaucells** [comment]
In case numeric derivative is needed I have already implemented it on my [derivative branch](https://github.com/rjbaucells/mathjs/blob/derivative/lib/function/numeric/derivative.js). I worked on it some time ago but I never found the time to create all the needed tests.

**Comment by BigFav** [comment]
I was only thinking about working on algebraic things in the parser. Nice to see some backend work was done on this, I'll note once I set some basic things up.

**Comment by harrysarson** [comment]
mathjs now has support for calculating derivatives and there is a now #442 and #1015 which look at the possibility of implementing integration. I think we can close this in favour of these other issues.

**Comment by josdejong** [comment]
:+1:
