### ISSUE TITLE
Rename 'collection' type to 'Collection' for consistency

### ISSUE THREAD

**Issue by devanp92** [josdejong/mathjs#352]
All type objects are proper nouns (e.g., Range, ResultSet, BigNumber, etc.). For consistency sake, 'collection' should be renamed to 'Collection'.

**Comment by josdejong** [comment]
Thanks. In this case it's more that `collection.js` is located in the wrong folder. It does not contain a prototype but is a collection of utility functions for Arrays and Matrices. I was planning to move it to  `./lib/type/matrix/` instead.
