### ISSUE TITLE
Percentile

### ISSUE THREAD

**Issue by paulmelnikow** [josdejong/mathjs#354]
Hi there, would you consider adding a percentile function? i.e. you'd pass in a vector and a quantile and it'd compute the `q`th percentile of the data in the vector. Here's the [numpy version](http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.percentile.html).

**Comment by josdejong** [comment]
Sure, that would be useful. Feel free to contribute if you like :)

**Comment by BigFav** [comment]
Virtual duplicate of issue #305 (not exact, but pretty close).

**Comment by josdejong** [comment]
Is this still an issue? Math.js contains a `quantileSeq` function implemented by @BigFav .

**Comment by BigFav** [comment]
I thought this should have been closed when I referenced it in PR #366. If you want this functionality, call `quantileSeq` with a probability instead of a percentile (e.g. 33% -> 0.33).
