### ISSUE TITLE
Proposal: Intersection function

### ISSUE THREAD

**Issue by kv-kunalvyas** [josdejong/mathjs#358]
Last semester, I used math.js for my graphics class. It had all the major useful functions that I wanted. However, for one particular problem, I couldn't find a function for finding the intersection point of two lines in 2D/3D. So, I had to implement it. Now that the semester is over, I wish to contribute that small part  I wrote to math.js.
So, I was getting started by going through some functions in the .../lib/function/... folder and was starting to think how to model the function. I was thinking of taking the names of two arrays containing the two lines' four endpoints' x, y(, z) coefficients as parameters.
Being my first time getting involved in an open source project, I wish to discuss this with you before I start writing and make a pull request.

Also, I wasn't sure which folder in .../lib/function/ would this function be created, closest being *trigonometry*, or maybe a new folder *geometry*?

**Comment by devanp92** [comment]
(2D) Why do you need 4 points for each array parameter when only 2 points make a line (unless it is a vector that has finite length)?

**Comment by kv-kunalvyas** [comment]
Yes you are right. By four points, I meant, two for each line.

**Comment by josdejong** [comment]
Thanks @kv-kunalvyas , such functionality would be a nice addition. I think it would fit best in a new category `geometry`. For naming and parameters I would first look around how other math applications and libraries call these functions and see how they pass arguments. Here some options that come in mind:

```js
// Option A
intersect(x1, y1, x2, y2)
intersect(x1, y1, z1, x2, y2, z2)

// Option B
// not yet supported by the expression parser, but makes sense
intersect({x: x1, y: y1}, {x: x2, y: y2})
intersect({x: x1, y: y1, z: z1}, {x: x2, y: y2, z: z2})

// Option C
// as array is a bit odd I think
intersect([x1, y1], [x2, y2])
intersect([x1, y1, z1], [x2, y2, z2])
```

Note that it is possible to support for example both options A and B.

**Comment by FSMaxB** [comment]
I don't think that arrays are that odd. Arrays are the way that vectors and matrices are represented in mathjs, so this notation represents an intersection between two lines that are defined by vectors.

**Comment by josdejong** [comment]
Hm, you're right. Arrays make sense indeed, you will get the same syntax as the functions `cross` and `dot` for example.

**Comment by devanp92** [comment]
I agree with @FSMaxB. However, the term 'intersect' can refer to many graphs other than straight lines. For example, plane intersection (3D), quadratic functions intersection points, etc.

**Comment by kv-kunalvyas** [comment]
@devanp92 I think that can be added to the intersect function later where it would return appropriate values based on the parameters it receives.

An alternate way to do this could be to write different functions instead of one, like:
`intersectLineLine2d(endPts1, endPts2)`
`intersectLineLine3d(endPts1, endPts2)`
`intersectLinePlane3d(lineEndPts, planeCoefficients)`, etc.

For now, I suggest we do this without higher degree polynomial curves and planes.

**Comment by josdejong** [comment]
@kv-kunalvyas thanks for the ideas. These names like `intersectLineLine2d` are very long though, and you get quite a lot of functions. Couldn't the function `intersect` detect itself whether input was 2d, 3d, or a plane?

**Comment by kv-kunalvyas** [comment]
Yes it can, and thats what I have decided upon. Thanks!

**Comment by devanp92** [comment]
@josdejong isn't having all of those 'mini-methods' within the intersect method itself burdening the function? I feel like the method would have too much functionality for what it is supposed to do. Could utilizing a design pattern like [Strategy](https://en.wikipedia.org/wiki/Strategy_pattern) or [Command](https://en.wikipedia.org/wiki/Command_pattern) reduce this risk?

**Comment by josdejong** [comment]
I think from the users point of view this is the easiest to use/remember. 

The code is neatly split sub-functions each handling a single case, and a public function which "routes" to the right function depending on given input. I'm not really affraid this particular function will grow too large or something. And in v2 it will be even possible to directly access these "sub functions" directly if you need to squeeze out more performance.

Which risk do you see exactly? That the code grows too complicated? Or performance issues?

**Comment by devanp92** [comment]
Ah, ok! Yes, it was the risk of the code growing too complicated, but if we can access these 'sub-functions' in v2, then it is not an issue :)

**Comment by josdejong** [comment]
Ok. Thanks for being critical

**Comment by josdejong** [comment]
The function `intersect` is now available in the today released v2. Thanks again @kv-kunalvyas
