### ISSUE TITLE
Cannot calculate sum of an empty array

### ISSUE THREAD

**Issue by zba** [josdejong/mathjs#369]
Is it correct ? Isn't it will be more correct to return 0 here ? 
https://github.com/josdejong/mathjs/blob/master/lib/function/statistics/sum.js#L72

My case is the  following:

I have a list of arguments, and one of them it is array with variable length including 0, 
My function accept list of fields and math.js function for evaluate, so I got this exception, workaround would be to check if the argument is empty Array and set it to  [0], if true, but it would cause incorrect result in cases for other statistical functions, so It make more inconvenience than just return zero on empty Array.

If it is not possible for sum() function, is  it possible to create functions like sum0, which would be  less strict than sum itself ?

**Comment by josdejong** [comment]
Thanks, we can indeed change that to just have `sum` return 0 for empty arrays. Makes sense.

**Comment by FSMaxB** [comment]
@josdejong Is this for v2 or v1?

**Comment by josdejong** [comment]
Shall we fix this in `v2`? The more we keep doing in `v1`, the more we have to merge/refactor again.

**Comment by FSMaxB** [comment]
That's true. It's already quite hard. I've tried doing a merge and aborted because it was too much. I'll make a commit that fixes this in v2.

**Comment by FSMaxB** [comment]
Ok, this is now fixed in v2

**Comment by josdejong** [comment]
Thanks!

**Comment by josdejong** [comment]
This has been fixed in the just released v2.
