### ISSUE TITLE
support for mixed fractions (e.g.  '3 4/5')

### ISSUE THREAD

**Issue by husayt** [josdejong/mathjs#370]
Would be nice to handle mixed numbers. Also to convert improper fraction into mixed number and mixed number into improper fractions.

**Comment by josdejong** [comment]
Makes sense. Did you accidentally close this issue?

**Comment by josdejong** [comment]
hm there is one problem though: it means that the parser should interpret `3 4/5` as `3+4/5`, an addition. That is at odds with implicit multiplication like `2 (3 + 4)` and `2 x`.

**Comment by makarandkarkare** [comment]
May be inclusion of a new operator (&) can solve this issue. Please check the calculator at this link https://mathpapa.com/algebra-calculator.html
Here, you can enter 3&4/5 and it shows it correctly as a mixed fraction, and also treats it correctly as one.
