### ISSUE TITLE
Weird test failure while developing attachable toString and toTex callbacks

### ISSUE THREAD

**Issue by FSMaxB** [josdejong/mathjs#378]
I started implementing `toTex` and `toString` callbacks today, but I experienced weird test failures and I can't quite understand where they are coming from.

I first implemented this for `toTex`, see https://github.com/FSMaxB/mathjs/commit/949bf027dcfd26402336d1ee559f18c38f04528f everything working fine there.

But when doing the same thing to `toString`, hell breaks lose and I don't know where this is coming from. https://github.com/FSMaxB/mathjs/commit/d4c90dedd325bcdba884fe03a592de31067326a0

Test log: https://travis-ci.org/FSMaxB/mathjs/jobs/63780807

**Comment by josdejong** [comment]
`toString` already exists for functions. It may be a good idea not to mess with the `function.toString` method, this method normally gives the code contents of the function back.  (try `(function (a,b) {return a+b}).toString()` in a browser console. So we need to be creative with an other name...

The logged output errors in the test log is the code of the functions `sqrt` and `add` as generated by `typed-function` (basically a dumb tree with type checking statements for all possible argument types).

**Comment by FSMaxB** [comment]
That explains a lot.

That means that either another name for this attached callback is needed, or we could just not implement it. ( both approaches are inconsistent ).

I was planning to at least use the attached-callback approach for ´toTex´ with either a callback or a template string, thereby getting rid of the long list in `util/latex.js` and have all the LaTeX implementations in the functions themselves.

**Comment by josdejong** [comment]
That sounds good.

For `toTex` these custom callback functions are useful and needed, but maybe a customizable `.toString` isn't that necessary? Can you think of any use cases where you would need a custom toString?

**Comment by FSMaxB** [comment]
I can think of one use case: Translations to another language, but that can be done with wrapper functions. Also my previous work already enables custom `toString` functions via the `options` parameter, so I guess I can simply leave it out.

**Comment by FSMaxB** [comment]
The idea of those attachments are primarily to provide a way to define `toTex` for imported functions, but the standard `toString` function syntax `function(arg1,arg2)` should be fine for this purpose in most cases. So: Necessary for `toTex` but not really for `toString`. It's just a thing that I wanted to do out of consistency.

**Comment by FSMaxB** [comment]
As my question is answered, I'll close this issue now.

**Comment by josdejong** [comment]
Ok then let's just go for attaching toTex.
