### ISSUE TITLE
randomInt documentation wrong

### ISSUE THREAD

**Issue by s9w** [josdejong/mathjs#381]
The [documentation](https://github.com/josdejong/mathjs/blob/master/docs/reference/functions/randomInt.md) mentions a call without arguments `math.randomInt()`, but that is not actually implemented in [the code](https://github.com/josdejong/mathjs/blob/master/lib/function/probability/distribution.js#L90).

Also the documentation does not state if the min and max limits are inclusive or exclusive. This is especially important because this library handles the limits different than almost any other.

**Comment by devanp92** [comment]
It looks like the limits are [min, max) (includes min, excludes max).

**Comment by s9w** [comment]
Oops, sorry about the range.

**Comment by josdejong** [comment]
Devan made a fix for this, see https://github.com/josdejong/mathjs/pull/382

**Comment by devanp92** [comment]
As referenced [here](https://github.com/josdejong/mathjs/pull/382), I propose we either remove randomInt(no arguments) or make randomInt(no arguments) return a number between 0 and Number.MAX_VALUE ( from [Mozilla's Javascript reference](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Number/MAX_VALUE)).

Having randomInt() return an integer between [0,1) will always return 0.
