### ISSUE TITLE
Proposal: Mode function

### ISSUE THREAD

**Issue by kv-kunalvyas** [josdejong/mathjs#395]
The statistics section is missing a mode function, which computes the most frequent value(s) in a dataset.
It can take in a vector as input and return the value that occurs the most. And if there are multiple such values, then it returns a vector.

**Comment by josdejong** [comment]
Thanks for the suggestion, would be nice to have this function added. We could have a look at how it's implemented for python: https://docs.python.org/3/library/statistics.html#statistics.mode

**Comment by kv-kunalvyas** [comment]
@josdejong Thanks for the python example. I have initiated a [merge request #399 ](https://github.com/josdejong/mathjs/pull/399) for the same.
Before doing this, I opened a wrong pull request #398  by mistake. I don't know what I was thinking and I'm sorry for that.
