### ISSUE TITLE
math.multiply floating point

### ISSUE THREAD

**Issue by GerhardLiebenberg** [josdejong/mathjs#406]
math.multiply(69999.93, 100) returns 6999992.999999999

Is there a way to get 6999993 without turning the result into a string - i.e. not using math.format?

**Comment by josdejong** [comment]
You could do do the rounding via `math.format` and then turn the string into a number again using `math.number`:

```
var ans = math.multiply(69999.93, 100);          // 6999992.999999999
math.number(math.format(ans, {precision: 14}));  // 6999993
```

You could also use BigNumbers to prevent these sort of round-off errors from happening: http://mathjs.org/docs/datatypes/bignumbers.html

**Comment by GerhardLiebenberg** [comment]
Many thanx. Will try and report back.

**Comment by GerhardLiebenberg** [comment]
Looks like big numbers are working.
math.format is not working with notation: "fixed".

var ans = math.multiply(69999.93, 100);          // 6999992.999999999
math.number(math.format(ans, {notation: "fixed", precision: 14}));  // 6999992.999999999

var ans = math.multiply(math.bignumber(69999.93), math.bignumber(100)); // 6999993

**Comment by josdejong** [comment]
Check out the docs to read what precision does in case of notation "fixed"

http://mathjs.org/docs/reference/functions/format.html

**Comment by GerhardLiebenberg** [comment]
In example-1 the "precision: 14" produces rounding error, while "precision: 0" works.
In example-2 it is the opposite - "precision: 0" results in rounding.

// example-1
var ans = math.multiply(69999.93, 100);  // 6999992.999999999
alert(math.number(math.format(ans, {notation: "fixed", precision: 14})));  // 6999992.999999999
alert(math.number(math.format(ans, {notation: "fixed", precision: 0})));    // 6999993
							
// example-2
alert(math.number(math.format(9999.99, {notation: "fixed", precision: 14})));	 // 9999.99
alert(math.number(math.format(9999.99, {notation: "fixed", precision: 0})));	 // 10000

**Comment by josdejong** [comment]
I'm not sure why you started using notation `fixed`, it works differently than `auto`. If you read the docs I think you will get the difference:

> `precision: Number` A number between 0 and 16 to round the digits of the number. In case of notations 'exponential' and 'auto', `precision` defines the total number of significant digits returned and is undefined by default. In case of notation 'fixed', `precision` defines the number of significant digits after the decimal point, and is 0 by default.

http://mathjs.org/docs/reference/functions/format.html

Also, for better understanding you can have a look at the following examples:

```js
math.number(math.format(111.111111, {precision: 2}))                    // 110
math.number(math.format(111.111111, {precision: 5}))                    // 111.11
math.number(math.format(111.111111, {notation: "fixed", precision: 2})) // 111.11
math.number(math.format(111.111111, {notation: "fixed", precision: 5})) // 111.11111
```

**Comment by GerhardLiebenberg** [comment]
Thanx Jos. I will try out those.

**Comment by GerhardLiebenberg** [comment]
Hi Jos
Im working with money. Simple add, subtract, multiply. 
How do you ensure that you always get two decimals without any rounding? Excess decimals must be truncated, without influencing the value of the first two decimals via rounding?

**Comment by josdejong** [comment]
When working with money you have o prevent round-off errors by using BigNumbers. Math.js always rounds to the closest integer (i.e. `0.007` is rounded to `0.01` and `0.003` is rounded to `0.00`). The BigNumber library that math.js uses, decimal.js, supports different ways of rounding ([see docs](http://mikemcl.github.io/decimal.js/#rounding)).

If I understand you correctly you want to do this:
```js
var BigNumber = math.type.BigNumber; // this is the decimal.js constructor `Decimal`
BigNumber.config({ rounding: BigNumber.ROUND_DOWN}); // or would you like ROUND_FLOOR?
```

**Comment by GerhardLiebenberg** [comment]
BigNumber.ROUND_DOWN should do the job.

Many thanx Jos.

**Comment by josdejong** [comment]
you're welcome.
