### ISSUE TITLE
Equation Simplifier

### ISSUE THREAD

**Issue by BigFav** [josdejong/mathjs#412]
It is common for interfaces that support equations to only return simplified version of input equations. As of now, the expression parse has no such function.

Examples:

``` javascript
math.eval('simplify(2 + 3)');            // Output math.parse('5')
math.eval('simplify(2x^2 + 2 + 3x^2)');  // Output equivalent of math.parse('5x^2 + 2')
```

**Comment by ericman314** [comment]
Here's what looks like a good approach: http://stackoverflow.com/questions/7540227/strategies-for-simplifying-math-expressions 

Has anyone worked on this yet?

**Comment by ericman314** [comment]
Well I'm taking a shot at it. We'll see how it goes.

**Comment by josdejong** [comment]
Cool, thanks Eric.

**Comment by ericman314** [comment]
Please see PR #439

**Comment by josdejong** [comment]
I will close this issue now since we do have `simplify` nowadays :)
