### ISSUE TITLE
Distance between two points

### ISSUE THREAD

**Issue by kv-kunalvyas** [josdejong/mathjs#418]
I think it would be a good idea to have a `distance` function in the `geometry` section that calculates the distance between two points. The points can be passed as 4 numerical arguments, a 2x2 Matrix or as two 1D arrays. The output will be the numeric value of the distance between those two points.
This can also be scaled up for 3 dimensions.

**Comment by josdejong** [comment]
Yes, sounds good. And I suppose you would return the euclidean distance? Later on we could implement more types (like matlabs [pdist](http://nl.mathworks.com/help/stats/pdist.html)). Would you like to pick this one up?

**Comment by kv-kunalvyas** [comment]
Surely, I'd love to do this. Yes, it is the euclidian distance. Thanks for letting me know about `pdist`. I think I'll add it to the function.

**Comment by josdejong** [comment]
Ok great. What do you think would be a good name for this function? I think `distance` is fine.

**Comment by kv-kunalvyas** [comment]
Yes, `distance` is good. I'll be placing it in the `geometry` folder.

**Comment by josdejong** [comment]
sounds good

**Comment by devanp92** [comment]
Has this been finished?

**Comment by kv-kunalvyas** [comment]
Though I am working on the `distance` function, I will add extra functionality(3D, distances between pairs of points) to it after your merge.

**Comment by josdejong** [comment]
Thanks for the cooperation guys :)

**Comment by devanp92** [comment]
@kv-kunalvyas what is the status with the 3D, distance b/w pairs to points?

**Comment by kv-kunalvyas** [comment]
@devanp92 I was waiting for your commit to merge. Now that its done, I'll build the functions in a few days. Thanks a lot!

**Comment by kv-kunalvyas** [comment]
Okay so in merge #456 I have added a basic addition to the `distance` function, which returns distance between two 3D points (and added a couple of unit tests and TODOs). I have added an extra flag that differentiates between 2D and 3D.

Need to add in following features; and then the function should be complete:
*  Distance between point and plane (2D)
*  Distance between point and plane (3D)
*  Distance between pairs of points (2D)
*  Distance between pairs of points (3D)
*  and finally...distance between pairs of points and a plane(2D & 3D)

With these requirements, the function is getting quite complex to implement. Any suggestions on how to neatly design the parameters based on the above features? (check `math.intersect` for plane and point)

**Comment by devanp92** [comment]
We could create types for a plane and point and then in the distance function, type check them, then pass them to the according function like so:

distance(x, y) {

//if x is a plane and y is a point - distanceBetweenPlaneAndPoint(x, y)
//if x is point and y is point - distanceBetweenPoints(x,y)
...

**Comment by josdejong** [comment]
I've just released v2.4.0 with the extended function `distance`, so I think we can close this issue. Thanks for your work Devan and Kunal!
