### ISSUE TITLE
Question: custom types w/ new mathjs instance

### ISSUE THREAD

**Issue by balagge** [josdejong/mathjs#420]
Hi, and thank you for this awesome library. I am prototyping a system that uses mathjs as a back-end and encountered a question.

When creating a new instance of mathjs (using `math.create([options])`), and importing custom type(s) to this new instance (using `newmathinstance.import(require('.../pathToDataTypeFile/...'))`), mathjs does not complain. However, the datatype is not available.

The same data type works fine if it is imported to the default mathjs instance. Also, it works if it is imported to the default instance **first**, and then a new instance is created. (so reversing `create` and `import` solves the problem **even in the new instance**).

However, it would be nice to import specific types to a new instance instead of importing everything to the default instance. After all, creation of a new instance is intended for a mathjs environment which behaves slightly differently, if I understand the concept correctly.

So the question is, is this intended behavior / deliberate limitation, or am I getting something wrong here?

(note: the data type has been created base on this [example](https://github.com/josdejong/mathjs/tree/master/examples/advanced/add_new_datatypes).)

**Comment by josdejong** [comment]
When you import new functions or data types in a math.js instance, it should indeed be imported only in that instance and not in others. 

I tried to reproduce your issue by doing the following in [the example you refer to](https://github.com/josdejong/mathjs/tree/master/examples/advanced/add_new_datatypes):

```js
var math1 = require('../../../index');

// create a new instance
var math2 = math1.create();

// import the new type MyType and the function `add` in math2
// it should *not* appear in math1
math2.import(require('./MyType'));
math2.import(require('./myAdd'));

console.log('math1.type.MyType', math1.type.MyType);  // undefined (as expected)
console.log('math2.type.MyType', math2.type.MyType);  // exists (as expected)
```

but that works as expected. How can I reproduce your issue?

**Comment by balagge** [comment]
The problem actually occurs when evaluating an expression. My scenario is this:
I have a custom node and a custom type as well. The custom node (when compiled and evaluated) creates a new instance of this type. So it takes quite a while to set this scenario up...

The reason I posted this as a 'Question', and not as an 'Issue' is that I am also unsure of some parts of my code. It definitely works with the default mathjs instance, it definitely does **not** work with a new instance created from it, but there may be many factors affecting this behavior on my side.

Actually you answered my question, which was 'is custom type importing supposed to work on a new instanc of mathjs as well?' - with 'yes', so at the moment I am satisfied with that and try alternatives on my side. I didn't want to rewrite that part before I was sure this is supposed to work, because each iteration takes a lot of time.

And I also don't want to waste your time :) Thank you for the reply.

**Comment by josdejong** [comment]
I tried with `eval` too, that seems to work ok too. 

You will have to pinpoint the cause of this, see if the cause is in math.js or in your code. Good luck with it!
