### ISSUE TITLE
Configuration for default units if none are given

### ISSUE THREAD

**Issue by rcfox** [josdejong/mathjs#426]
I was wondering if it would be possible to add configuration for default units. For example, if you defaulted to millimetres, an expression like "1 + 1cm" would parse the first "1" as "1mm".

Thanks.

**Comment by josdejong** [comment]
Thanks for your suggestion and your pull request Ryan (your PR looks good btw).

I strongly doubt whether this would be a good idea, you introduce all sorts of ambiguities which may lead to people wrongly interpreting expressions. How would "1cm + 2 + 3inch" be interpreted for example? I think it is better to enforce writing the units explicitly. In your case above you could for example do `(1 + 1) cm` if you don't want to write the unit twice.

**Comment by rcfox** [comment]
> How would "1cm + 2 + 3inch" be interpreted for example?

It would depend on the value of the defaultUnits config value. If set to "mm", it would be interpreted as "1cm + 2mm + 3inch".

In my application, I have an input for a number, and a dropdown to select the units. The value of the dropdown would be used as the defaultUnits. Most values would be in millimeters, for example, but there's inevitably a value in mils that also needs to be added.

Anyway, I guess that is perhaps a little too specific. Thanks for the tip about the parentheses, that's probably a good enough substitute.

**Comment by josdejong** [comment]
Ok then. Well, you can always add this specific behavior to your own application if needed for your use case. You could just extend the existing functions `add` and `subtract` by doing something like:

```js
// find the implementation of `add(Unit, Unit)`
var unitUnitAddScalar = math.typed.find(math.add, 'Unit, Unit');

math.import({
  add: math.typed({
    'Unit, number': function (x, y) { ... },
    'number, Unit': function (x, y) { ... }
  }),

  subtract: math.typed({
    'Unit, number': function (x, y) { ... },
    'number, Unit': function (x, y) { ... }
  })
})
```

When you import a `typed-function`, and a function with the same name already exists, the new signatures will be merged into the existing function.
