### ISSUE TITLE
[Combinatorics] Create Permutation Type

### ISSUE THREAD

**Issue by devanp92** [josdejong/mathjs#427]
In combinatorics, Permutations have many different properties and functions. Such properties include cycle length, parity of transposition, inversions, reverse, etc. Some functions include multiply (with another permutation), calculate inverse, pattern avoiding/containing, etc.

**Comment by josdejong** [comment]
Thanks for your suggestion Devan. We shortly discussed such a Permutation type per mail some months ago. It's still not clear to me how such a Permutation type would look like and how and in which functions we would need it. If possible, I would prefer using types like regular objects and arrays rather than very specific data types.

Can you explain more concretely what you have in mind with this Permutation type?

**Comment by devanp92** [comment]
Sure. This Permutation object, would need to store the elements in an array-like form (a permutation is a function pi, where pi(i) = some element - indexed similar to an array). It needs to be represented in different ways ([one line notation] (http://groupprops.subwiki.org/wiki/One-line_notation_for_permutations), [two-line notation](http://groupprops.subwiki.org/wiki/Two-line_notation_for_permutations), as a set of [cycles](http://mathworld.wolfram.com/PermutationCycle.html), etc.), it has functions (composition, inverting, multiplying, etc,0 and has properties (cycle length, order, odd/even, etc). 

It also can have a child object, Partially Ordered Set (Poset), which is used for sorting permutations (231-avoiding, West-stack sortable, etc.).

Since it is specific to combinatorics, it may be better to have this object residing in the Combinatorics module and not in the 'types' one.

You can check out Sage's object [here](http://doc.sagemath.org/html/en/reference/combinat/sage/combinat/permutation.html).

**Comment by josdejong** [comment]
Thanks for the explanation, I'm not so familiar with combinatorics and this is all new to me. Sounds like a useful addition, it would be great if you would like to work on this.

I think it fits best as a new data type under `/lib/type/permutation`, this folder could contain both `Permutation` and `Poset` (have a look at the `/lib/type/matrix` folder, it contains various matrix related types and functions.

There could be two approaches here:
- We can just implement this as part of math.js (like Complex, Unit, etc).
- We could first develop a standalone library `permutation`, publish that on npm, and use that into math.js (like `decimal.js` and `fraction.js`). It sounds like this could be a useful library on it's own. This gives some overhead of creating a new project and hooking it into math.js, but helps our work modular and more broadly usable.
- We can look around if there maybe already exists a nice Combinatorics library with such a Permutation type (https://www.npmjs.com/package/js-combinatorics ?), and hook that into math.js. You can probably better than me judge what is out there.

What do you think?

**Comment by devanp92** [comment]
I like developing a standalone library. It keeps this modular and not encumbered by esoteric 'types'.

**Comment by josdejong** [comment]
Sounds good. I see you created a project here: https://github.com/devanp92/combinatorics.js

Are there no suitable combinatorics libraries out there already?
