### ISSUE TITLE
Combinatorics Library Contribution

### ISSUE THREAD

**Issue by devanp92** [josdejong/mathjs#436]
Hi everyone - @josdejong and I have created a library [combinatorics.js](https://github.com/devanp92/combinatorics.js) that will be able to be used in math.js. Feel free to contribute!

**Comment by josdejong** [comment]
@devanp92 thanks for our initiative. 

Just to repeat my question from #427, are you sure there are no suitable existing libraries out there?

**Comment by devanp92** [comment]
I haven't found one that is extensive enough to support many of the used functions in research today.

**Comment by josdejong** [comment]
Ok thanks
