### ISSUE TITLE
Bug fix: Unit.to

### ISSUE THREAD

**Issue by ericman314** [josdejong/mathjs#441]
@josdejong, I noticed a problem today:

```
math.eval("230 V * 3.88 A / (60 s^-1) to ft lbf")
14.873333333333333 J
```
The correct answer should be `10.970007700250527 ft lbf`. It seems `Unit.to` wasn't setting the `isUnitListSimplified` flag, so `ft lbf` was being simplified by `Unit.format`. I have added a test for this and pushed a bug fix to the `develop` branch.

**Comment by josdejong** [comment]
Thanks, good find!
