### ISSUE TITLE
Algebraic integration

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#442]
To have a complete algebra package, we need support for three operations: `derivative`, `integral`, and `simplify`. @BigFav created an initial function `derivative`, @ericman314 is currently having fun with creating a `simplify` function. An implementation for algebraic integration is still missing.

The current work is available in the [`algebraic_differentiation`](https://github.com/josdejong/mathjs/tree/algebraic_differentiation) branch. It's still a work in progress and we're still discussing what API to offer. See earlier discussions: #439, #386.

Who is interested in working on algebraic integration? 

@nicolewhite maybe you are interested in helping out here, seen your recent work on [algebra.js](https://github.com/nicolewhite/algebra.js)?

**Comment by devanp92** [comment]
@josdejong I can work on integration.

**Comment by nicolewhite** [comment]
Do you plan to add any capabilities around solving?

**Comment by josdejong** [comment]
@nicolewhite good point, I didn't have this in mind for this first set of algebraic functions but a solver will be indispensable :). Would you find it interesting to work on that?

**Comment by sonnyk22** [comment]
Would be great to have a good solid JavaScript-based algebra equation solver.  The closest one I came across is http://davidwees.com/coding/2006/11/javascript_systems_of_equation.html.

@nicolewhite, is your algebra.js able to solve such equation as:
2(x-2)(x+3)/5+3/4(x-2)+2x-3/2x^2+2=3(x-2)+(2x-3)(2x+2)-4
x^2-6x+5=0 
1/(x-3)=1 
x(2+2)=4

**Comment by BigFav** [comment]
I got pretty busy as I was going to work on this, but I still gathered a few resources which may be helpful for anyone interested.

http://mathematica.stackexchange.com/questions/6811/how-does-mathematica-integrate
https://asmeurersympy.wordpress.com/2010/06/30/the-risch-algorithm-part-1/

**Comment by Announcement** [comment]
what about `.solveFor`

**Comment by josdejong** [comment]
yes, I think we can simply name it `solve`?

**Comment by husayt** [comment]
@NicoleWhite math.js now has solid derivative and simplify implementations, algebra.js integration would be great. Algrbra.js could also benefit from very strong expression tree,  toLatex and other features of math.js.
Thanks for great work

**Comment by m93a** [comment]
Let's continue the discussion in #1015
