### ISSUE TITLE
Result formatting (digit grouping)

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#453]
Is there a way for the MathJS lib to provide us with a formatted result in digit grouping; for example:

55555 * 44444 = 2,469,086,420
444.88 * 656.99 = 292,281.7112

**Comment by ericman314** [comment]
Math.js doesn't have built-in support for digit grouping, so you will need to post-process the output.

Here's something that might work for you:
http://stackoverflow.com/questions/6784894/add-commas-or-spaces-to-group-every-three-digits

You could also try [`toLocaleString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString), but it's not supported everywhere.

**Comment by sonnyk22** [comment]
Thank you

**Comment by josdejong** [comment]
@sonnyk22 maybe the number formatting library [Numeral.js](http://numeraljs.com/) can help you?

**Comment by sonnyk22** [comment]
I will have to look into right now.  Thank you.
