### ISSUE TITLE
The "+" sign in exponential mode result

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#454]
Is there a way to turn off the "+" sign returned in an exponential mode result?  For example:

MathJS result: 2.905265e+5.  I want 2.905265e5
MathJS result: 2.905265e-5.  I want the same (2.905265e-5)

**Comment by ericman314** [comment]
There's no built-in option in math.js for this, but here's a way to do it using JavaScript's `replace` function:

```js
math.format(2.905265e+5).replace('e+', 'e');
```

Or, to do the same thing with a custom formatter:

```js
function myFormatter(value) {
  return math.format(value).replace('e+', 'e');
}

math.format(2.905265e+5, myFormatter);
```

**Comment by sonnyk22** [comment]
thanks!
