### ISSUE TITLE
Support for engineering notation display.

### ISSUE THREAD

**Issue by mofosyne** [josdejong/mathjs#457]
Is there some configuration to allow for engineering notation?

Ergo instead of displaying as 5e7, it would be in 50e6 ? Basically to the power of 3, which is convenient when dealing with SI units.

**Comment by josdejong** [comment]
This isn't yet supported but will would a nice new formatting option. We could call it `{notation: 'engineer'}`.

**Comment by devanp92** [comment]
@mofosyne Displaying 5e7 is closer to [scientific notation](http://www.purplemath.com/modules/exponent3.htm) standard, whereas 50e6 is not. Technically it should be 5.0e7.

**Comment by mofosyne** [comment]
Well, some calculators support "Engineering Notation" which does things in powers of 3s.

I'm not saying to replace scientific notation, but rather support "Engineering Notation" mode for those of us who rather not have to do mental conversion to get to micro, nano, pico meters etc... Which these physical calculators did think is valuable enough to include as a feature.

Which the same site you mentioned, also mentioned engineering notation: http://www.purplemath.com/modules/exponent4.htm

**Comment by devanp92** [comment]
Ah, gotcha! This would be a great feature to add.

**Comment by johnmarinelli** [comment]
Hey there, I'd like to take a stab at this - started it here:
https://github.com/johnmarinelli/mathjs/tree/issue457

should have something to show within a few days!

**Comment by josdejong** [comment]
Thanks John!

**Comment by josdejong** [comment]
@johnmarinelli what do you think, should we call the notation option `{notation: 'engineer'}` or `{notation: 'engineering'}`? I think I may like the shorter one better.

**Comment by mofosyne** [comment]
In general speech, I would say: "engineering notation" vs "scientific
notation"

So try "Engineering" for the notation key field.

**Comment by johnmarinelli** [comment]
@josdejong I opted to use `{notation: 'engineering'}`; I figure that it's the idiomatic way to say it.  PR here: https://github.com/josdejong/mathjs/pull/519

**Comment by josdejong** [comment]
@johnmarinelli yes makes sense, lets go for `engineering`.

**Comment by mofosyne** [comment]
Oh @johnmarinelli is your commit ready to be pulled? I noticed its ` 243 commits behind josdejong:master` which might cause possible conflict when merging

**Comment by mofosyne** [comment]
Looks like it's all merged in now. Closing.
