### ISSUE TITLE
Setting the Lower and Upper bounds 

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#459]
How can I configure the MathJS lib to override the existing Lower and Upper bounds when notation='auto'?

For example:
        999,999,999,999 *1 = 999,999,999,999  (the result I want)

but, for any results over 999,999,999,999 (Upper) or less than -999,999,999,999 (Lower), it should return: 
         999,999,999,999 + 1 = 1e+12
        -999,999,999,999 - 1 = -1e+12

The code that I have used below does not comply:

                        result = mathjs.format(result, {
                            notation: _displayMode,  //'auto' or 'exponential'
                            precision: 11,
                            lower: -9e+12,  
                            upper: 9e+12
                        });

http://mathjs.org/docs/reference/functions/format.html

**Comment by ericman314** [comment]
When `notation` is `"auto"`, the number will be formatted with exponential notation only if its **absolute value** is less than `lower` or greater than or equal to `upper`. So typically one would choose a small positive number for `lower`, like `1e-3`, and a large positive number for `upper`, like `1e+12`.

Also, `lower` and `upper` are not options themselves, but parameters of the `exponential` option, like this:

```js
result = mathjs.format(result, {
    notation: _displayMode,  //'auto' or 'exponential'
    precision: 11,
    exponential: {lower: 1e-3, upper: 1e+12}
});
```

The docs are indeed a little unclear on this; I think we could improve the wording and/or add another example to the docs.

**Comment by sonnyk22** [comment]
Thank you!
