### ISSUE TITLE
FFT functions

### ISSUE THREAD

**Issue by sebpiq** [josdejong/mathjs#46]
I don't know if that stays in the scope of mathjs.
If you're interested I can implement them.

**Comment by drom** [comment]
Nice Library. I desperately need FFT in it. What is the progress with implementation? Can I help?

**Comment by josdejong** [comment]
FFT is still not implemented, sorry. Help would be welcome here. For now you could use the FFT of for example http://numericjs.com/, you can import functions from this library into math.js if your like.

**Comment by drom** [comment]
FFT/iFFT would need to operate on the real/complex vector.
We probably can start with input:Float64Array -> output:Float64Array function.
Do you have recommendation how to store Float64Array array of complex numbers, interleaved / half-half?

**Comment by josdejong** [comment]
I would start with a basic `fft` implementation using regular numbers and a regular Array (and with support for the `Matrix` type of math.js, but that will probably be a wrapper). For `ifft` I would start with an implementation using the `Complex` type of math.js, and using a regular `Array` and with support for `Matrix`.

For a second iteration we could optimize performance by using typed arrays. However typed arrays are not (yet) supported by all browsers so the library must be able to fall back on regular Arrays. Support for typed arrays is a needed for *all* functions of math.js, not just `ftt`. The changes currently being made for `v2` will pave the way for library-wide support for typed arrays, resulting in way better performance. 

One future matrix type could be a `ComplexMatrix`. This matrix could store a series of complex numbers in two typed arrays (one for `im`, one for `re`), which I expect to best performance.

**Comment by drom** [comment]
I have started small repo here: https://github.com/drom/fourier
Testing with Travis encountered float differences between node 0.12 / iojs and node 0.10
How are you dealing with floating point differences in testing of Math operations?

**Comment by josdejong** [comment]
To prevent round-off errors from breaking on round-off errors, we have a little utility approx.js, which compares whether two numbers are approximately equal.

https://github.com/josdejong/mathjs/blob/master/tools/approx.js

**Comment by drom** [comment]
I have done KISS implementation of dft / idft. Will do the radix 2 / 4 / 8 / 16 next. For the accuracy will follow the following methodology http://www.fftw.org/accuracy/method.html in order to compare with other FFTs.

**Comment by josdejong** [comment]
sounds good :)

**Comment by drom** [comment]
I have implemented power-of-2 radix-2 decimation in time version with normal arrays and typed array.
Performance and accuracy different between node 0.10, 0.12 and iojs.
Surprised to see only 10-15% performance improvement with typed arrays.

**Comment by josdejong** [comment]
Interesting to see what typed arrays do for the performance of such an algorithm. If it's just 10-15% it may not even be worth all extra work. Could there be more asm.js related techniques allowing the JS engine to better optimize this? (or is the current implementation already close to what you could get from a bare-bone C implementation?...)

**Comment by drom** [comment]
This a very good question. My current FFT implementation uses classic Decimation in Time, Radix-2 algorithm, which is far from being the best in class. I am comparing Float64, Float32, and Array implementations on three V8 based engines.

Raw benchmarks for (node 0.12.2, 0.10.38; iojs 1.6.3) can be found in Travis logs here: https://travis-ci.org/drom/fourier

Here are some charts I have crafted from the results:
![preamp1](https://cloud.githubusercontent.com/assets/511872/6968123/06845e52-d919-11e4-9e37-48837e40d9cf.png)

I am not sure what CPU type Travis uses on their servers. But here is the chart from:
http://www.fftw.org/speed/CoreDuo-3.0GHz-icc64/
Which includes some state of art FFT implementations in C.

Double precision:
![](http://www.fftw.org/speed/CoreDuo-3.0GHz-icc64/supersgj0-64.1d.dcxx.p2.png)

Single precision:
![](http://www.fftw.org/speed/CoreDuo-3.0GHz-icc64/supersgj0-64.1d.scxx.p2.png)

Obviously we are x20 slower then the best. And results are different with different version of V8 engine.
It make sense to try:
 * higher radix algorithms (4,8,16,...)
 * better data / operation flow organisation.
 * data type casting techniques like asm.js
 * SIMD extensions: https://github.com/johnmccutchan/ecmascript_simd

Any other ideas are welcome!

**Comment by josdejong** [comment]
Thanks. So if I understand it correctly:

- The speed improvements for using typed arrays *are* actually significant,  but the differences in performance differs a lot on different JavaScript engines.
- The JavaScript implementation performs *way* slower than other implementations like in C

**Comment by drom** [comment]
I have done some more experiments with FFT code. Results are here: https://github.com/drom/fourier/issues/1

**Comment by echo66** [comment]
@josdejong take a look at the emscripten compilation of FFTW that I upload to this repository: https://github.com/echo66/FFTW3-emscripten/

**Comment by drom** [comment]
It does not look complete.

**Comment by echo66** [comment]
@drom , look at this file: https://github.com/echo66/FFTW3-emscripten/blob/master/test_code.js

**Comment by drom** [comment]
@echo66 As i mentioned above, it does not look like FFT implementation. How do you use this code?

**Comment by echo66** [comment]
Oh, I just noticed that I forgot to upload the compiled files. 

Done.

**Comment by echo66** [comment]
The initial delay is due to the loading of the "simple_1d_wrapper.js" file (1.4 MB).

**Comment by drom** [comment]
@echo66 it is better now. But, how dose one simply use it? Can you benchmark it for 64K with jsperf, or benchmark.js ?

**Comment by echo66** [comment]
http://jsperf.com/benchmark-for-fftw-js

**Comment by echo66** [comment]
A comparison between several FFT solutions: http://jsperf.com/comparing-two-fft-functions/3

I will add @drom FFT code to it.

**Comment by echo66** [comment]
@drom, can you upload a "browserified" version of your library?

**Comment by echo66** [comment]
It is kind of ironic to see that chrome is faster than firefox when dealing with ASM code. x)

**Comment by drom** [comment]
Can you compare bigger size FFT? It make sense to compare 64K, I think.
I upload browserified version.

**Comment by echo66** [comment]
An exaustive benchmark for @drom FFT and FFTWJS:
http://jsperf.com/benchmark-for-fftw-js-and-drom-s-fft

**Comment by echo66** [comment]
An exaustive benchmark for FFTWJS and drom's FFT:
http://jsperf.com/benchmark-for-fftw-js-and-drom-s-fft

**Comment by drom** [comment]
@echo66 your benchmark look fine to me.
My current implementation uses:
 - classic Radix-2;
 - Decimation in Time (DIT) algorithm;
 - in-place, (performs data permutations before first stage);
 - one typed data array, complex data, all real point, then all imaginary points.
 - generator: https://github.com/drom/fourier/blob/master/bin/fft-gen.js generates individual code for each FFT size using `lodash` template: https://github.com/drom/fourier/blob/master/src/fft-template.js (can be done dynamically if needed)
 - I use _asm.js_ conventions on function interface.
 - all twiddle factors (1.25 of SIN period) calculated upfront ( `.init()` function ) and stored in the twiddle array.
 - in both `asm` and `raw` versions I perform `i32` casting with (x | 0) hint, `u32` casting with (x >>> 0)
 - in `asm` version I perform `f32` casting using `fround(x)` hint, and `f64` casting using `+(x)` hint.
 - `asm` version has `'use asm';` pragma and passes Firefox AOT validation (as it can be seeing in the log).

More details are here: https://github.com/drom/fourier/issues/1

**Comment by echo66** [comment]
If you create a multidimensional version of fourier.js, I see no reason to use FFTWJS.

**Comment by drom** [comment]
@echo66 I have never done Nd FFT in my life. Can you suggest good description? reference code? or pull request? ;)

**Comment by echo66** [comment]
Sorry, I never implemented a FFT before. :/

Still, you have this implementation: https://github.com/scijs/ndarray-fft

**Comment by echo66** [comment]
Just one note: for each execution of forward and inverse in the FFTW wrapper, I'm creating a new FFTW plan. And it is always the same type of plan. I probably should take a look at it.

**Comment by mrquincle** [comment]
Hi Jos,

Created a simple FFT implementation with radix-2. This is a discrete-in-time version. It is out-of-place, memory/space complexity is not optimized. Implementation details are common knowledge, for example on https://en.wikipedia.org/wiki/Cooley%E2%80%93Tukey_FFT_algorithm

https://gist.github.com/mrquincle/b11fff96209c9d1396b0

I haven't visualized it, but this should be nice to combine with vis.js.

Cheers,

Anne

**Comment by josdejong** [comment]
Thanks Anne, that looks neat! 

Should be quite straight forward to add this code to math.js, though we have to add docs and unit tests of course. Would you like to pick that up too?

**Comment by mrquincle** [comment]
Sure, remind me if I forget.

**Comment by josdejong** [comment]
great, thanks!

**Comment by arkajitmandal** [comment]
Hi is this implemented yet?

**Comment by josdejong** [comment]
No this hasn't been implemented. Anyone interested in picking this up?

**Comment by arkajitmandal** [comment]
I can do this once I am done the eig functions

**Comment by josdejong** [comment]
Great, thanks for your offer Arkajit!

**Comment by mklilley** [comment]
I would like to add a +1 for adding this feature. I'm a physicist trying to create an [ObservableHQ notebook to solve the Schrödinger equation](https://observablehq.com/@mklilley/solving-the-schrodinger-equation-01). Currently I'm using [numjs](https://github.com/nicolaspanel/numjs) because it's got FFT, but it doesn't have complex arithmetic so I'm having the create that functionality myself....and probably not doing a good job at it.

**Comment by m93a** [comment]
A cool comparison of different implementations of FFT in JavaScript: https://github.com/scijs/fourier-transform/blob/master/benchmark.md

**Comment by HanchaiN** [comment]
Which category should the function be implemented in? (Just in case someone will actually implement it.)

Also, the multidimensional Fourier transform seems to be a good generalization as the module normally works with multidimensional arrays/matrices. (It may or may not affect the performance to implement this.)

**Comment by josdejong** [comment]
> Which category should the function be implemented in?

I think we can add `fft` to the `matrix` category. If you have an other suggestion just let me know.

> Also, the multidimensional Fourier transform seems to be a good generalization as the module normally works with multidimensional arrays/matrices. (It may or may not affect the performance to implement this.)

That sounds good. If there is performance impact I suppose we could have two implementations under the hood (1 dimensional and multi dimensional), and automatically pick the right one.

**Comment by HanchaiN** [comment]
As for now, the function can only operate on a power-of-two--size array. It still needs to be fixed to support the input of arbitrary sizes. (Either open a new issue or reopen this one would be fine.)

**Comment by josdejong** [comment]
Yes that is true. Can you open a new issue about fft support for arbitrary size matrices?
