### ISSUE TITLE
Is there a standard for your arithmetic grammar?

### ISSUE THREAD

**Issue by tomekwi** [josdejong/mathjs#462]
Hi, I’m working on a parametric drawing system based on SVG. The spec for arithmetic expressions (<https://github.com/parametric-svg/spec/tree/7bea264#expression>) is currently based on ECMAscript. But I want it to be implementable in any language – so I want to refer to a language-agnostic spec.

Your library looks like more than a perfect match for me!

But do you have any form of a spec for the grammar you use for parsing `math.eval` expressions?

**Comment by tomekwi** [comment]
Oops! I got so excited to have found this library, that I failed to look closely before asking a question.

For all others looking for a formal spec: <http://mathjs.org/docs/expressions/syntax.html>.

Sorry for the fuss!

**Comment by josdejong** [comment]
You're welcome, enjoy :)
