### ISSUE TITLE
inconsistent implicit multiplication

### ISSUE THREAD

**Issue by julinas** [josdejong/mathjs#463]
This is on the released version... 2 * 3 3 3 is interpreted as syntax error, but 2 * 3 3 is parsed as 2 * 3 * 3. 2 + 2 3 also gives a syntax error instead of 2 + 2 * 3 as expected. Maybe it's no longer a problem in develop?

**Comment by FSMaxB** [comment]
I didn't even know something like `2 * 3 3` was even possible. But looking at the source code of the parser I found this:
https://github.com/josdejong/mathjs/blob/248d314f3e8492f0b58019397810d2c87dc03807/lib/expression/parse.js#L880-L891
```js
    // parse implicit multiplication
    if ((token_type == TOKENTYPE.SYMBOL) ||
        (token == 'in' && (node && node.isConstantNode)) ||
        (token_type == TOKENTYPE.NUMBER && !(node && node.isConstantNode)) ||
        (token == '(' || token == '[')) {
      // symbol:      implicit multiplication like '2a', '(2+3)a', 'a b'
      // number:      implicit multiplication like '(2+3)2'
      //              Note: we don't allow implicit multiplication between numbers,
      //              like '2 3'. I'm not sure whether that is a good idea.
      // parenthesis: implicit multiplication like '2(3+4)', '(3+4)(1+2)', '2[1,2,3]'
      node = new OperatorNode('*', 'multiply', [node, parseMultiplyDivide()]);
    }
```

The comments suggest that implicit multiplication between numbers wasn't intended at all.

In my understanding this means one of two things:
1. It is a bug that `2 * 3 3` works, according to the comments it shouldn't.
2. It is a bug that `2 * 3 3 3` doesn't work **and** that `2 3` doesn't work.

But I don't quite understand the parser at this point.

@josdejong: What is your take on this.

**Comment by josdejong** [comment]
Thanks for bringing this up.

> The comments suggest that implicit multiplication between numbers wasn't intended at all.

That's correct. Implicit multiplication between two numbers should not be supported, so "2 * 3 3" should throw an error instead of evaluating. 

Reason for not allowing implicit multiplication between values was that I thought it could easily lead to misreading expressions, you can easily confuse it with a list of values (how do you think `[1 2 3]` would evaluate? as `[1, 2, 3]` or as `[1 * 2 * 3]`?).

**Comment by josdejong** [comment]
This inconsistent behavior is fixed now in the `develop` branch.
