### ISSUE TITLE
explicitly declaration of constants in degrees or radiance

### ISSUE THREAD

**Issue by mofosyne** [josdejong/mathjs#465]
When declaring variables, for readability and mixing of constants of varying degrees and radiance. It may be nice to:

```
degrees1 = 52 ^rad
degrees2 = 52 ^deg
degrees3 =  52^rad + 52^deg
```

It may be required for parsing convenience to:

```
degrees3 =  ( 52 ^rad ) + ( 52 ^deg )
```

basically we are looking for a solo `^rad` or `^deg`

**Comment by ericman314** [comment]
Are you asking whether you can add a number in degrees to a number in radians? If so, then yes, that is allowed. You can also define explicitly which unit you would like the result expressed with using the `to` operator. You can also assign the result to a constant you can use in subsequent expressions:

```
rad3 = 52 rad + 52 deg   // 52.90757121103705 rad
degrees3 = rad3 to deg   // 3031.3805346802806 deg
rad3 == degrees3         // true
tan(rad3)                // -0.5456585050462265
tan(degrees3)            // -0.5456585050462265
```

In the expression, `degrees3 =  ( 52 rad ) + ( 52 deg )`, parentheses are acceptable but not required, as an implicit `*` is assumed between the number and the unit, and `*` has a higher operator precedence than `+`.

Also, it looks like you are trying to use `^` as a variable prefix? In mathjs, `^` is used for exponentiation (like, `2^3 = 8`).
