### ISSUE TITLE
Extension point/hook to support new symbols/operators

### ISSUE THREAD

**Issue by CraigCav** [josdejong/mathjs#467]
The library has some great [extension](http://mathjs.org/docs/extension.html) points already, but one thing that would be great is being able to extend the parser with support for new symbols.

I'd like to be able to use mathjs to be able to parse Salesforce formula to execute against plain JS objects. Currently mathjs supports most of the [valid salesforce formula operators](https://help.salesforce.com/apex/HTViewHelpDoc?id=customize_functions.htm#legal_operators) however, there are a few that are missing, for example: `<>` (not equal) and `!` ([logical complement operator](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/langCon_apex_expressions_operators_understanding.htm) rather than factorial).

It'd be great if there were a means to be able to import new symbols/operators/delimeters into the parser and map them to specific types of [node](http://mathjs.org/docs/expressions/expression_trees.html#nodes).

**Comment by CraigCav** [comment]
I'd imagine that the parser could be constructed dynamically using the precedence/associativity metadata that is included in the [operators module](https://github.com/josdejong/mathjs/blob/master/lib/expression/operators.js). It would seem like a good first step towards being able to extend the parser with support for new syntax.

**Comment by josdejong** [comment]
Thanks for your suggestion @CraigCav. Being able to customize/extend the supported operators would be cool, though I'm not sure though whether this is a broadly desired need. The operators are currently hard-coded and hand-optimized in the parser. It will indeed be a challenge to be able to correctly specify precedence and associativity. 

Note that you could probably also use a parser generator like [Jison](http://jison.org) or [PEG.js](http://pegjs.org/) to generate a parser with the *exact* syntax that you want to have supported.

**Comment by CraigCav** [comment]
I can definitely appreciate that is unlikely a broadly desired need. Another factor to consider is that composing the parser with smaller pieces might offer benefits for maintainability. 

What I had in mind was switching the parser from using recursive descent, to being an [operator-precedence parser](http://javascript.crockford.com/tdop/tdop.html) using a symbol table. The symbol table would provide a suitable means for extending mathjs with new symbols. It would also allow logic for handling specific symbols to be extracted out into separate components.

I'll have a go a it in a branch and see what sticks.

**Comment by josdejong** [comment]
Sounds good if you could do some experimentation here, thanks :)

**Comment by BigFav** [comment]
>Currently mathjs supports most of the valid salesforce formula operators however, there are a few that are missing, for example: <> (not equal) and ! (logical complement operator rather than factorial).

Although this isn't related to this functionality, I do want to point out that [logical not for the parser is `not`] (https://github.com/josdejong/mathjs/blob/master/lib/expression/parse.js#L903-L927) and you can add `<>` as unequal by inserting it into [the delimeters](https://github.com/josdejong/mathjs/blob/master/lib/expression/parse.js#L92-L130) and into [`operators` in `parseRelational`](https://github.com/josdejong/mathjs/blob/master/lib/expression/parse.js#L701-L708) just in case you have a deadline.

**Comment by CraigCav** [comment]
Thanks @BigFav. I'm currently using a fork of Mathjs that does just that.

**Comment by Frodojj** [comment]
I'm currently developing a calculator app using math.js. Currently my app preprocesses input before sending it to the parser. A feature to have additional characters (such as the radical/sq root sign in my case) as function names would be extremely useful for me. An option to set pre-parser or post-eval functions, called before/after eval and parse would also be nice (the absence breaks my hooks to add custom documentation to the help function). A post-processing function could transform the type of output if desired (like converting to a new base-n type in my app's case) if certain input conditions are met.

**Comment by josdejong** [comment]
Thanks for your input @Frodojj . Can you explain your use case in more detail? Which new "characters" do you exactly need, how would the user use these? It may be the case that (at least some) of the customization you need can be achieved by utilizing `math.import`, `math.parse`, and `Node.transform`, and overriding `math.eval` to do this post processing.

**Comment by Frodojj** [comment]
There are two main cases:

1. My app uses the radical sign character - "\u221A" - as shorthand for math.sqrt() or math.nthRoot() via an imported function (which actually calls math.sqrt() with 1 argument, math.nthRoot() with 2 arguments). However, math.js's parser doesn't recognize "\u221A(9)"; it throws SyntaxError: "Syntax error in part "√(9)" (char 1)". There are 3 solutions using the built-in parser:

  1. Use nrt() or another custom-named function.
  2. Replace "\u221A" with "nrt" before passing the function to the parser.
  3. Editing function `isAlpha (c)` to return `/^[a-zA-Z_\u00C0-\u02AF\u0370-\u03FF\u221A]$/.test(c)`.

 I chose the last option, but I am wary of making additional changes to math.js. 

2. My app adds a new BaseNumber type for dealing with numbers in a base other than 10. It uses shorthand to represent binary, octadecimal, and hexadecimal numbers, e.g. `\b1001110.1101`, `-\o123.45`, or `\xC0FFEE`. That syntax is obviously illegal, so it must be preprocessed before sending it to the parser. However, when writing documentation for the associated helper functions, math.help() will give an annoying error (which doesn't completely break the behavior) for examples. e.g:
````javascript
    math.expression.docs.dec = {
        name: "dec",
        category: "Base-N Numbers",
        description: "Converts a base-N number to a base-10 number",
        syntax: ["dec(string)", "dec(number)"],
        examples: ['dec("12345.06789")', "dec(\\xFF)"],
        seealso: ["bin", "oct", "dec", "baseN"]
    };
````
 The ability to specify a preprocessor function would solve both issues (1) and (2).

**Comment by josdejong** [comment]
Thanks for your in-dept explanation, makes sense. Your issue (2), support for other bases, is something I would love to implement in mathjs anyway. 

Issue (1) is quite specific and indeed would be solvable with some preprocessing hook. Wouldn't it be enough for your case to use a simple RegExp to replace all `\u221A` characters with `sqrt` before passing the expression to `math.expr`?

**Comment by Frodojj** [comment]
Regarding (1), that's definitely an alternative. In fact, I do a regexp search/replace before sending an expression to `math.eval`. However, it precludes the ability to correctly parse examples for a help object for `\u221A` (since `math.help()` uses math.js's parser). The alternative is simply to not provide examples for the help object, or to modify `math.help()` (I'd rather not do this).

**Comment by josdejong** [comment]
Thanks for the clarification, makes sense. These hooks into the parser would indeed make life much easier :)

**Comment by ChristopherChudzicki** [comment]
This would be a great feature! I would love it for my project [math3d.org](https://www.math3d.org) which uses MathJS for parsing. For this project I wanted cross product and dot product operators. Currently I pre-process `'a cross b'` to `'a & b'` and have reassigned `OperatorNode.fn` from `bitAnd` to `cross`. This works (since I wasn't using `&` operator for anything) but seems _very_ hacky.

**Comment by josdejong** [comment]
Thanks for sharing you workaround @ChristopherChudzicki

**Comment by stoplion** [comment]
Hello, I'm attempting to do something similar. Trying to replace `% ` as modulus operator to perfect unit, and only using `mod` as the modulus operator.

I'm walking the node tree and filtering out "%" operator nodes. 

What I'd like to do is..
When I find an "%" operator node, walk up the tree and find the left hand ConstantNode and insert 
a SymbolNode with name '%'. 

I'm sure this is the best way to do it but I can't think of another way. Also another problem is that I can't create a unit with the name `%`, so I'm sort of stuck using this approach anyway. Units have to begin with a letter. 

This project I'm working on absolutely has to have `%` as percentage. Additionally if a percent is added to a number, the requirements are to take that second `%` number and get the percentage of the first number, and add it together. (e.g. 164 + 5% === 172.2). 

Alternatively might need to run some kind of preprocessing (PegJS?) before sending the result to MathJS.

**Comment by josdejong** [comment]
Trying to change the meaning of % from modulus to percentage is really tricky. I think it's safer to either adjust the source code of the parser to your needs, or use a parse generator to generate your own parser instead.

**Comment by socreative** [comment]
Came across this issue when trying to implement additional operators for the math.js parser. One of the ones I need to implement is "<>" which is pretty much an alias for the existing "!=" ("unequal")

Not keen on forking the repo and modifying the parser - I'd rather keep the reference to the original repo and follow its updates. 

Is there anything in plans to make the existing parser more flexible? @josdejong Would you accept a PR with this feature?

**Comment by josdejong** [comment]
@socreative I'm hesitant with that, I'm afraid that we'll open up a lot of difficulties with precedence, associativity, etc, as I explained in an earlier comment: https://github.com/josdejong/mathjs/issues/467#issuecomment-141633265

If your use case is just adding an extra alias `<>` for the existing operator `!=`, an easy solution may be preprocessing your expressions with a regex that replaces all `<>` with `!=` (and maybe some smartness to adjust any error message too). Would that work for you?

**Comment by josdejong** [comment]
Closing this issue now, it's been inactive for a long time and I don't actions being taken based on these ideas any time soon. Feel free to open a new issue.
