### ISSUE TITLE
Question: How to detect if a Node is a variable?

### ISSUE THREAD

**Issue by tomekwi** [josdejong/mathjs#468]
I thought `node.isSymbolNode` does the trick. But it turns out that `mathjs.parse('false').isSymbolNode` is `true` as well.

**Comment by tomekwi** [comment]
Is there a reliable way to check if a `node` is a variable?

**Comment by FSMaxB** [comment]
As far as I know, `SymbolNode`'s are always "variables". Some of them have predefined values but you can still assign to them. (`pi`, `tau`, `e`, `phi`, `E`, `PI` [note that `pi` and `PI` are two different ones]).

To check if a Node is a `SymbolNode` you can use it's `type` attribute:
```js
if (node.type === 'SymbolNode') {
    console.log('This node is a variable');
}
```

**Comment by FSMaxB** [comment]
A `SymbolNode` is always a "variable", some of them have predefined values, but you can still assign to them, those are:
 `true`, `false`, `null`, `uninitialized`, `Infinity`, `NaN`, `pi`, `PI`, `tau`, `phi`, `e`, `E`, `i` and `version`. 
Those are currently defined in `lib/constants` (https://github.com/josdejong/mathjs/blob/4b22c8c95c45b303c01505f5c36966dd3882597d/lib/constants.js)

As far as I know, there's no way to distinguish predefined variables from others without checking for the names of the predefined variables manually.

**Comment by tomekwi** [comment]
:+1: that’s just what I needed – thanks!
