### ISSUE TITLE
Is it safe to accept user input?

### ISSUE THREAD

**Issue by mjnaderi** [josdejong/mathjs#469]
Hi,

I want to accept user input in my website and use mathjs and node.js to evaluate user's input. Is it safe to do this without any harm to server?

Can I prevent evaluating too much time-consuming expressions?

Thanks,

**Comment by josdejong** [comment]
Yes it's safe in the sense that math.js has it's own expression parser, and a user cannot execute arbitrary commands. But the user can easily crash the server by creating a huge matrix or doing a very expensive operation. 

You will have to run the actual requests in a child process. You an use a library like [workerpool](https://github.com/josdejong/workerpool) to create these child processes and limit execution time to for example 10 sec. I used this library for http://api.mathjs.org.

**Comment by josdejong** [comment]
I will add a simple example for running math.js in a web servers child process to the examples section.

**Comment by josdejong** [comment]
@mjnaderi I've added a web server example, it's in the develop branch right now. Can you have a look if this is what you where looking for?

See: https://github.com/josdejong/mathjs/tree/develop/examples/advanced/web_server

**Comment by mjnaderi** [comment]
Thanks, this is great.
But I'm still afraid of memory usage. Don't we need to put a limit on memory usage?

**Comment by josdejong** [comment]
It would be interesting to see how to limit memory usage, though node.js doesn't offer a fine grained control over memory. The following (old) FAQ talks about a `--max_old_space_size` flag to limit the memory: https://github.com/nodejs/node-v0.x-archive/wiki/FAQ#what-is-the-memory-limit-on-a-node-process. I'm not sure if this is still available in the latest node.js versions, and whether also holds for child processes spawned by the main process. I haven't experimented with this myself, maybe you do some trials here.
