### ISSUE TITLE
Would it be possible for mathjs to recognize ln as well as log?

### ISSUE THREAD

**Issue by kristiankime** [josdejong/mathjs#471]
I guess this is really more of a feature request than a but... I'm using mathjs in an editor for a site I'm developing. It works great except that user would like to use ln for natural log. Would it be possible to have mathjs support ln?

**Comment by josdejong** [comment]
You can add it yourself:

```js
math.import({ln: math.log});

math.ln(math.e); // 1
```

**Comment by kristiankime** [comment]
My apologies I should have noticed that feature. Thanks.

**Comment by josdejong** [comment]
You're welcome :). If you have more questions or suggestions don't hesitate to share them.
