### ISSUE TITLE
Unit "stone" is 1000x too large

### ISSUE THREAD

**Issue by Esvandiary** [josdejong/mathjs#473]
The "stone" unit is defined in Unit.js:1775 as having a size of 6350. However, this is in kilograms, not grams (hence "g" is defined as 0.001). As a result, this implies that 1 stone is 6350kg, which is incorrect.

**Comment by ericman314** [comment]
Thanks! This is now fixed in the `develop` branch, see PR #474.

**Comment by josdejong** [comment]
This has been fixed in the just released v2.4.0.
