### ISSUE TITLE
parser considers array indexes as one-based

### ISSUE THREAD

**Issue by simoneb** [josdejong/mathjs#475]
Hello,

With this setup:

```js
var parser = math.parser();
parser.set('a', [1,2,3]);
```

I'm trying to figure out why this is happening:

```js
parser.get('a')[0];   
// 1
parser.eval('a[0]'); 
// IndexError {index: 0, min: 1, max: NaN, message: "Index out of range (0 < 1)"}
```

Searching past issues I see that #23 mentions that indexes should be zero-based, but apparently they aren't.

**Comment by josdejong** [comment]
Yes this can be confusing. The expression parser uses one-based indices with upper bound included, whilst the JavaScript methods use zero-based indices with upper bound excluded. The differences between JavaScript API and expression parser are summarized here: http://mathjs.org/docs/expressions/syntax.html#differences-from-javascript
 
See also #66.

**Comment by simoneb** [comment]
Ahh, I had been looking for this but couldn't find it. Thanks

**Comment by josdejong** [comment]
You're welcome :)
