### ISSUE TITLE
how to parse out equation parameters to list

### ISSUE THREAD

**Issue by spitzbubchen** [josdejong/mathjs#478]
Is there an easy way to parse an arbitrary equation to get all of its variables to a list?

For example, given 'a + 2*b + c' get [a, b, c]?

**Comment by ericman314** [comment]
Meant to get to this sooner but it looks like you already found an answer. In case anyone else has the same question, you can use the `filter` function:

```js
var node = math.parse('a + 2*b + c');
var filtered = node.filter(function (node) {
  return node.isSymbolNode;
});
// returns an array with three SymbolNodes: 'a', 'b', and 'c'.
```
