### ISSUE TITLE
nthRoot function fails in MSIE 11

### ISSUE THREAD

**Issue by Frodojj** [josdejong/mathjs#480]
When `math.nthRoot` is called from Math.js version 2.3.0, MSIE 11 throws TypeError: Object doesn't support property or method 'isFinite'. This can be fixed easily with a [simple polyfill from MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite) ([public domain](https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses)):
```javascript
Number.isFinite = Number.isFinite || function (value) {
    "use strict";
    return typeof value === "number" && isFinite(value);
};
```

**Comment by josdejong** [comment]
Thanks for spotting this issue @Frodojj . The issue can be solved even simpler, by replacing `Number.isFinite` with `isFinite`, as we already know the variable is a number.

**Comment by Frodojj** [comment]
That is true. I used a polyfill in my project; because, I wanted to make as few changes to third party libraries as possible. Obviously that's not an issue here. Heh :-) Thank you very much for the great library and your development of it!
