### ISSUE TITLE
Joining a matrix

### ISSUE THREAD

**Issue by tomekwi** [josdejong/mathjs#481]
Hi, I can’t figure this out:

Having a matrix of strings like `["a", "bcd", "ef"]`, how can I concatenate items to get a single string? What I want at the end is `"abcdef"`.

**Comment by devanp92** [comment]
I believe that matricies are 'typed arrays' and therefore you can use the [Array.prototype.join()](http://www.w3schools.com/jsref/jsref_join.asp).

**Comment by tomekwi** [comment]
Yeah, but that’s JS – I can only use pure mathjs syntax in my case.

**Comment by josdejong** [comment]
The `Matrix` class of math.js does not extend `Array`, I wish that would be possible but it isn't.

math.js doesn't have a built in function to join strings. You can easily add this function yourself, something like:

```js
// add function join
math.import({
  join: function (x) {
    return math.flatten(x).valueOf().join('');
  }
});

// use:
math.join(["a", "bcd", "ef"]);         // "abcdef"
math.eval('[join("a", "bcd", "ef"])'); // "abcdef"
```

Or with input type checking and support for `join("a", "b", ...)`:
```js
math.import({
  join: math.typed('join', {
    'Matrix | Array': function (x) {
      return math.flatten(x).valueOf().join('');
    },
    '...string': function (x) {
      return x.join('');
    }
  })
});
```

**Comment by tomekwi** [comment]
Wow! Thanks for the in-depth answer. You rock @josdejong!
