### ISSUE TITLE
Output without scientific notation?

### ISSUE THREAD

**Issue by tomekwi** [josdejong/mathjs#483]
Hello!

It looks like any number with more than five digits is output in scientific notation:

```js
math.eval('string(10000)');
//» '10000'
math.eval('string(100000)');
//» '1e+5'
math.eval('string(100001)');
//» '1.00001e+5'
```

Is there any way to suppress this conversion and output it as a plain old decimal?

***

P. S. I hope you don’t mind me asking support questions here. Please tell me if there’s a better place.

**Comment by josdejong** [comment]
This is indeed the right place to ask questions, report bugs, and share suggestions :)

The function `format` may be what you're looking for: http://mathjs.org/docs/reference/functions/format.html

**Comment by tomekwi** [comment]
Oh yes – it looks great!

But if I want to format stuff this way within `math.eval` / `math.parse`, it looks like I’ll have to pass a custom function to it – doesn’t it?

**Comment by josdejong** [comment]
Yes indeed, but that's only because the parser doesn't yet support JSON objects, and you have to pass the options as a JSON object, something like `math.format(123e10, {exponential: {lower: 1e-99, upper: 1e99}})` in your case. So you can indeed do:

```js
math.import({
  myFormat: function (x) {
    var options = {
      exponential: {
        lower: -Infinity, // 1e-3 by default
        upper:  Infinity  // 1e5 by default
      }
    };
    return math.format(x, options);
  }
});

math.eval('myFormat(10000)');
//» '10000'
math.eval('myFormat(100000)');
//» '100000'
math.eval('myFormat(100001)');
//» '100001'
```

**Comment by tomekwi** [comment]
Thanks for your assistance @josdejong – I really appreciate it!

Here’s what did the trick for me:

```js
mathjs.import({output: String});


math.eval('output(10000)');
//» '10000'
math.eval('output(100000)');
//» '100000'
math.eval('output(100001)');
//» '100001'
```

**Comment by josdejong** [comment]
Ah, nice and simple :)

**Comment by nickkolok** [comment]
Any progress on this? The workaround looks elegant enough, but a systematic solution would be even more good!

**Comment by dvd101x** [comment]
I think these days is something like: `math.format(1e6, {notation:'fixed'})`
