### ISSUE TITLE
sinh not too accurate for numbers approaching -1 or 1

### ISSUE THREAD

**Issue by jrus** [josdejong/mathjs#484]
I left a [comment on the relevant pull request](https://github.com/josdejong/mathjs/pull/247#issuecomment-149182824), but I figured I should make a separate issue, in case nobody sees that one. Ping @pavpanchekha.

A 5th degree Taylor expansion for sinh, [as currently used by mathjs](https://github.com/josdejong/mathjs/blob/8158dafd3d45e7f0/lib/function/trigonometry/sinh.js#L67-L70), isn’t very accurate when you get away from zero. For instance, with x = 0.99, it has an error of ~1.87e-4 (according to Wolfram Alpha).

As an alternative, you could use the degree 17 Taylor expansion [the way the GNU Scientific Library does](https://github.com/ampl/gsl/blob/1a819c2daab24f5f/specfunc/trig.c#L39-L52) for the range [-1, 1], or you could e.g. use a Chebyshev series expansion.

Also, it probably makes sense to defer to the native Math.sinh function if it is defined. (Part of ECMAScript 6.)

**Comment by josdejong** [comment]
Thanks for bringing this up! Would you be interested in improving the current implementation?

**Comment by pavpanchekha** [comment]
Hi @jrus, and thanks for bringing up this problem. I'll look into using Chebyshev series, and try to figure out how to avoid the problem in the future.

**Comment by josdejong** [comment]
Thanks @pavpanchekha

**Comment by cukejianya** [comment]
See if #555 solves this problem.

**Comment by josdejong** [comment]
I've fixed this in the `develop` branch by using ES6 Math functions when available, and if not, falling back on a simple implementation using `exp` (nothing fancy). This means that in practice you may see some inaccuracy issues on old versions of node (v0.10, v0.12).
