### ISSUE TITLE
Easiest way to handle the Deg/Rad mode for the Trig funcs 

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#488]
Is there an easier way to calculate the trig functions in DEG mode for the entire expression?

For example:
RAD Mode: 1 + cos(5) + tan(6) + sin((pi/2)*2) + 0.44
DEG Mode: 1 + cos(5 deg) + tan(6 deg) + sin((pi/2)**2 deg) + 0.44

This requires writing a hefty function to use the combinations of the RexEx, parsing, insertion, and concatenation to insert the word 'deg' in each expression's trig functions prior to calling the mathjs.eval() function.

Hope there is an easier way to handle this? Or a good strategy to handling it?

**Comment by josdejong** [comment]
Here is an example which simply overrides the original functions: http://mathjs.org/examples/browser/angle_configuration.html

**Comment by sonnyk22** [comment]
Great code; already applied it to my app; thx.

Lets take this example: cos(30) in DEG Mode

Based on the the calculations at the link provided, it returns 0.4999999999, but on MathJS.com when i enter cos(30 deg), it returns 0.5 which is the correct i am looking for; in-fact, all Sci-Calcs out there returns 0.5.  Did you round this off only if it is in the DEG Mode?

**Comment by josdejong** [comment]
The example can use an update (doesn't work for matrix inputs anymore), but I guess you get the idea.

the editor on the main page of http://mathjs.org simply formats the output with limited precision, something like `var str = math.format(result, {precision: 12})`. This way you can get rid of displaying these  round-off errors. See also http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by sonnyk22** [comment]
Worked perfectly! Thanks

**Comment by josdejong** [comment]
ok great :)
