### ISSUE TITLE
Returned small results in DEG mode

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#491]
Lets take an expression "abs(sin(270))*abs(cos(270))" as an example for this question.

At both links below, the returned result in DEG Mode is an extremely small value.
http://mathjs.org/examples/browser/angle_configuration.html:
![calc2](https://cloud.githubusercontent.com/assets/6744710/10738901/f3653452-7bef-11e5-8a3c-6ee001760f23.png)

And, at www.mathjs.org:
![calc1](https://cloud.githubusercontent.com/assets/6744710/10738930/2aec258e-7bf0-11e5-90c3-2a297c7bae2a.png)

But, the returned result on the TI calculators and some other emulators is 0.
![calc3](https://cloud.githubusercontent.com/assets/6744710/10739066/c7ea87ae-7bf0-11e5-87a2-6d8a78577e23.png)

Is this something that the MathJS.format() function can take care, so that I can get a 0 back for the result?

**Comment by josdejong** [comment]
> Is this something that the MathJS.format() function can take care, so that I can get a 0 back for the result?

Indeed, you can use `format` to round the result to say 12 or 14 digits precision. But the function `math.format(x, 14)` only reduces the number of digits of the result. For a value like `0.30000000000000004` this will return `0.3`. But in case of `1.8369701987210297e-16`, this will return `1.836970198721e-16` and not `0`. 

If you're working with very small numbers, you may not want to consider something like `1e-16` equal to zero. If you work with "normal" numbers, you may want to consider this equal to zero. So it depends.

Maybe in your case you want to use a function like [`math.round`](http://mathjs.org/docs/reference/functions/round.html), which rounds the number of decimals behind the decimal point.

**Comment by sonnyk22** [comment]
The MathJS.round(x, n) function worked out perfectly for me.

Thank you!
