### ISSUE TITLE
Dealing with Percantage% expressions

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#492]
The MathJS.eval() function returns a 5 for the expression 5%290.  It is using a MOD for the % symbol.  In my app, I changed my parsing function to output (5/100)*290.  Is this the only way to handle this scenario?

**Comment by FSMaxB** [comment]
The nicest solution would probably be to implement percent as a unit in mathjs (if it isn't already). Then you could do a simple string replacement that replaces `%` with whatever the name of the percent unit would be (like `percent` or `per`).

**Comment by ericman314** [comment]
Would it work to define a variable such as `percent = 0.01` and use that instead of a built-in unit? For example,

```js
var parser = math.parser();
parser.eval('percent = 0.01');
console.log(parser.eval('5 percent'));

Output:
0.05
```

You would still do the string substitution just as @FSMaxB suggested.

Adding a dimensionless unit `percent` would work fine for simple expressions. The returned type from the evaluation would be `Unit`. You would then use the `value` property to get the value:

```js
var ans = math.eval('5 percent');
ans.toString();        // "5 percent"
ans.value;             // 0.05
```

However, for some expressions this will cause other parts of the evaluation to fail:

```js
var ans = math.eval('exp(5 percent)');
TypeError: Unexpected type of argument in function exp (expected: number
or Complex or BigNumber or Array or Matrix, actual: Unit, index: 0)
```

**Comment by FSMaxB** [comment]
Yeah, using a variable is much easier. The only thing to look out for is that this variable can be reassigned with a new value.

**Comment by sonnyk22** [comment]
Is this possible to do?

var ans = mathjs.parser().eval('percent = 0.01').eval('5 percent');

**Comment by josdejong** [comment]
@sonnyk22 you cannot chain `eval` calls, it would look like this:

```js
var parser = math.parser();
parser.eval('percent = 0.01');

var ans = parser.eval('5 percent'); // 0.05
```

or:

```js
var parser = math.parser();
parser.set('percent', 0.01);

var ans = parser.eval('5 percent'); // 0.05
```

or:

```js
var scope = {percent: 0.01};
var ans = math.eval('5 percent', scope); // 0.05
```

**Comment by sonnyk22** [comment]
This solution worked out perfectly for me:

var scope = {percent: 0.01};
var ans = math.eval('5 percent', scope); // 0.05

Thank you

**Comment by sonnyk22** [comment]
One "possible" issue that has shown up is that after adding the below code snippet to my app,

![calc1](https://cloud.githubusercontent.com/assets/6744710/10802149/79273110-7d91-11e5-9c78-6c620e72dd5d.png)

when I pass-in just '%' to the MathJS.eval() function, it actually does returns a value.  Could this be a  bug?

![calc2](https://cloud.githubusercontent.com/assets/6744710/10802151/7a824590-7d91-11e5-9d7b-2848037528df.png)

Currently, in my app I am blocking such expressions.

**Comment by josdejong** [comment]
Your `percent` is just a regular variable, so if you do `math.eval('percent', scope)`, it will return the value of the variable, i.e. `0.01`.
