### ISSUE TITLE
"Possible" issue with the Combination() function

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#493]
When I enter combinations(4,0.5) on the MathJS.org, I get a return value of 1 which may be incorrect.  In my application, I am also getting the same result returned from the MathJS.eval() function.

![calc6](https://cloud.githubusercontent.com/assets/6744710/10743008/d2773e68-7c06-11e5-8f7e-2e320e3e8530.png)

I get an Error message when I enter the same on 2 different TI calculators that I have, as well as on another calculator emulator. 

![calc7](https://cloud.githubusercontent.com/assets/6744710/10743117/80f54854-7c07-11e5-8d5d-99109c5a6e11.png)

Is there an extra setting (parameter) that I need to pass into this function?

**Comment by josdejong** [comment]
Thanks for reporting this bug @sonnyk22 . This has been fixed now in the `develop` branch of the project.
