### ISSUE TITLE
Question regarding 2PI and PI2

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#495]
When I pass-in the expression '2pi' to the MathJS.eval() function, the correct result is returned:

![calc1](https://cloud.githubusercontent.com/assets/6744710/10800810/56fda76a-7d8a-11e5-86e5-a20a67622615.png)

but, when 'pi2' is passed-in, an exception is thrown.  In-fact any numbers after PI causes exception, including 'pipi', however, 'pi*2' or 'pi*pi' works.

![calc2](https://cloud.githubusercontent.com/assets/6744710/10800812/585841a6-7d8a-11e5-8b5f-67f64df52c85.png)

**Comment by josdejong** [comment]
That's correct. Variables cannot start with a number, hence `2pi` is unambiguous, it can only mean `2 * pi`. But `pi2` is ambiguous, it could mean two things: (a) a variable named `'pi2'`, and (b) `pi * 2`. Therefore that's not allowed.

**Comment by sonnyk22** [comment]
Thanks.
