### ISSUE TITLE
Question related to factorial of negative numbers

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#497]
MathJS works great by throwing an exception when applying factorial to a negative number (when enclosed), as seen below:

![calc1](https://cloud.githubusercontent.com/assets/6744710/10829576/343392fe-7e51-11e5-8fb5-241bf6da15eb.png)

Also, the factorial work great with positive numbers with the '!' symbol and by calling the factorial() function.

But, when I pass in '-4!', it does calculate it, however it works fine when '(-4)!' is enclosed.  Is this a possible bug or perhaps a quick enhancement to the library?  If not, is there a way to use the scope parameter of the .eval() function to let MathJS know it should encapsulate '-4!' in parenthesis like '(-4)!'?

**Comment by FSMaxB** [comment]
´!´ has higher precedence than `-`, see [the list of operator precedence](http://mathjs.org/docs/expressions/syntax.html#precedence). It's probably quite hard to change this behavior because the operator precedence is hardcoded in the parser.

**Comment by sonnyk22** [comment]
Thank you.  On my end, I have added a quick RegEx to output (-4)!, so its all good.

**Comment by josdejong** [comment]
The behavior is there to ensure a consistency in calculations like  `-4!` and `0-4!`, they both evaluate to the same result `-12` as `!` has higher precedence to both minus and unary minus operator.

Be careful with using a RegEx for these sorts of expressions, it's very tricky. There is a lot of dependency on surrounding context. Does your RegEx for example work ok with cases like `20-4!`? If it changes it to `20(-4)!` you change the meaning of the expression.
