### ISSUE TITLE
Possible issue with 2^2^2^2^2

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#498]
When I enter 2^2^2^2^2 on the MathJS.org site or pass into the .eval() function, I get the Infinity result back where the answer should be 65536.  

![calc1](https://cloud.githubusercontent.com/assets/6744710/10848208/22c0e4ae-7ef1-11e5-9346-50081a6175a7.png)

I verfied this on other calculators as well, and I am getting back the result of 65536.

![calc2](https://cloud.githubusercontent.com/assets/6744710/10848263/71ab9924-7ef1-11e5-92a5-fb1327a2a50b.png)

Also, the answer for 2^2^2^2 should be 256 as well.

![calc6](https://cloud.githubusercontent.com/assets/6744710/10848318/c510c8e6-7ef1-11e5-849a-b20bf91f4255.png)

Could this be a possible bug?

**Comment by josdejong** [comment]
Some applications have the power operator left-to-right associative (such as your calculator and Matlab), others have it right-to-left (such as math.js and Mathematica). 

http://www.wolframalpha.com/input/?i=2%5E2%5E2%5E2%5E2

Not all math/calculator applications have the exact same behavior. In some cases there are different valid behaviors. Apparently the behavior of math.js differs at some points from your favorite calculator. Just [study the docs](http://mathjs.org/docs/expressions/syntax.html) to figure out relevant differences.

**Comment by sonnyk22** [comment]
I never knew about left-to-right/right-to-left power operator. Good reading.  

I am a little bit confused; need your advice on this.  I am In my app, if the end-user enters 2^2^2^2^2, in what format should I pass into the .eval() function to get the 65536 result?

**Comment by FSMaxB** [comment]
That would be `(((2^2)^2)^2)^2`!

Right to left is what one would do in normal maths on paper as far as I know.

**Comment by josdejong** [comment]
Indeed, in math.js:

```
2^2^2^2        # right to left
    65536
2^(2^(2^2))    # right to left
    65536
((2^2)^2)^2    # left to right
    256
```

In practice, it's always safer not to rely on the default behavior of the evaluator at hand for these ambiguous order of operations. Just use parenthesis to make things unambiguous for both yourself, the evaluator, and other people looking at your expressions (and maybe having others ideas on what is "normal" behavior). This holds for `-4!`, `2^2^2^2`, `z and y or z`, etc.

**Comment by sonnyk22** [comment]
Awesome! I will apply it to my code.

Thank you
