### ISSUE TITLE
Error in mac 

### ISSUE THREAD

**Issue by arunsathyan** [josdejong/mathjs#500]
Emberjs build fails when mathjs is added in mac , works fine in windows 

npm version 1.4.28

EMFILE, open '/Users/xx/xx/node_modules/mathjs/package.json'
Error: EMFILE, open '/Users/xx/xx/node_modules/mathjs/package.json'

**Comment by josdejong** [comment]
That sounds weird. Does a normal `npm install` work?

Besides that, you seem to be using an old version of npm (1.x), maybe it's an idea to upgrade?...

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by arunsathyan** [comment]
No , after npm update this is working

On Saturday 5 December 2015, Jos de Jong <notifications@github.com> wrote:

> Is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/josdejong/mathjs/issues/500#issuecomment-162176681>.
>


-- 
Thanks and Regards

Arun Sathyan

**Comment by josdejong** [comment]
ok
