### ISSUE TITLE
Unable to evaluate "(3+4i)^2" formula with BigNumbers

### ISSUE THREAD

**Issue by gang65** [josdejong/mathjs#502]
When I'm trying to run "eval" function on "(3+4i)^2" string, it gives me exception:
"TypeError: Property 'toExponential' of object -6.999999999999997 + 24i is not a function"
It is an issue only in that case.

When I evaluate "(3+4i)*(3+4i)) it returns correct result "-7+24i"

**Comment by josdejong** [comment]
Are you using the latest version of math.js? Or are you maybe trying to call this `toExponential` function in your own code?

I can't reproduce this error, tried:

```
math.config({number: 'bignumber'});
math.eval('(3+4i)^2'); // Returns Complex -6.999999999999997 + 24i
```

Besides that, please note that `Complex` numbers internally use regular `numbers`, they can't use `BigNumbers` and simply convert BigNumbers to regular numbers.

**Comment by gang65** [comment]
Yes. I'm trying to use expotential on Complex number.

**Comment by josdejong** [comment]
You can look into `math.format`, which allows formatting of all data types of math.js:

http://mathjs.org/docs/reference/functions/format.html

**Comment by gang65** [comment]
I'm already using both of them (math.format and toExponential)

I like "toExponential", because it returns short numbers like: "1e-10"
With math.format I have strictly defined length like: "1.0000000000e-10"

Here is the function which is used to limit number of characters in result:

    /**
     * Format bigNumber
     */
    function formatBigNumber(bigNumberToFormat) {

        // Maximum length of the result number
        var NUMBER_LENGTH_LIMIT = 14;

        if (mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10}}).length > NUMBER_LENGTH_LIMIT) {
            if (bigNumberToFormat.toExponential().length > NUMBER_LENGTH_LIMIT) {
                // long format like: "1.2341322e+22"
                var resultLenth = mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10},
                                                precision: NUMBER_LENGTH_LIMIT}).length;

                return mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10},
                                                precision: (NUMBER_LENGTH_LIMIT - resultLenth + NUMBER_LENGTH_LIMIT)});
            } else {
                // short format like: "1e-10"
                return bigNumberToFormat.toExponential();
            }
        } else {
            // exponential: Object An object containing two parameters, {Number} lower and {Number} upper, 
            // used by notation 'auto' to determine when to return exponential notation.
            return mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10}});
        }
    }

**Comment by gang65** [comment]
The idea to display short numbers, with limited space:

Instead of: "10.000000000", display: "10"
Instead of: "1.000000e-10", display: "1e-10"

and make sure that result string not exceed 14 characters.

**Comment by josdejong** [comment]
Why/how are these trailing zeros added? If I execute your function `formatBigNumber`, I don't get trailing zeros.

The `math.format` function does add trailing zeros then when using notation `exponential` or `fixed`, but you'r not using these modes as far as I can see.

**Comment by gang65** [comment]
This function limits number of characters in the string:
When bigNumberToFormat is 0.3333333333333333333333333333333333333333333333333333333333333333
it returns: 0.333333333333 


When bigNumberToFormat is  10 it returns 10 (no change, standard form, no trailing zeros)

When bigNumberToFormat is 0.0000000001 it returns 0.0000000001 (no change, standard form)

When bigNumberToFormat is 0.00000000001 it returns 1e−11 (too long string to display, expotentional form,  it is shorter and more precise)

**Comment by gang65** [comment]
Please let me check, I need to remind myslelf why I cannot use:
                var resultLenth = mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10},
                                                precision: NUMBER_LENGTH_LIMIT}).length;

                return mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10},
                                                precision: (NUMBER_LENGTH_LIMIT - resultLenth + NUMBER_LENGTH_LIMIT)});

instead :-)

**Comment by gang65** [comment]
I have no excuse to start using:

var resultLenth = mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10},
precision: NUMBER_LENGTH_LIMIT}).length;

            return mathJs.format(bigNumberToFormat, {exponential: {lower: 1e-10, upper: 1e10},
                                            precision: (NUMBER_LENGTH_LIMIT - resultLenth + NUMBER_LENGTH_LIMIT)});

It fit all my needs.

**Comment by gang65** [comment]
Unfortunately I don't know how to limit number of digits for Complex number.
mathJs.format with precision parameter is not working for me:
(3+4i)^2=-6.999999999999997 + 24i

Do you have idea how to fix that?

**Comment by josdejong** [comment]
Yes, that sounds much better/simpler than your initial solution.

To format Complex numbers... drum roll.... use `math.format`. And for Units too. And for Matrices. Etc.

```js
var res = math.eval('(3+4i)^2');   // Complex -6.999999999999997 + 24i
math.format(res, {precision: 14}); // "-7 + 24i"
```

See also: http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by gang65** [comment]
Unfortunately it is not working for me.
Maybe it is connected that I'm using BigNumbers.

**Comment by josdejong** [comment]
How can I reproduce your issue?

**Comment by josdejong** [comment]
Via the code @gang65 sent me via mail I tracked down the issue. 

Turns out that the `format` function was relying on some behavior of modern browsers not according to the JavaScript spec (but consistently implemented differently in all of them):

```js
var a = [1,2,3];
var b = a.splice(0); // omit the required second argument deleteCount
console.log('a=',a, 'b=', b);      
// most browsers will return a=[], b=[1,2,3] but Qt returns a=[1,2,3], b=[]
```

Basically: when omitting the required second argument `deleteCount` of the method `splice`, most browsers interpret this as "splice everything until the end of the array" (similar to methods like `slice`, `substr`, and `substring`), whilst Qt interprets it as "splice zero elements".

This issue is fixed in the develop branch, I will do a bugfix release this weekend.

**Comment by gang65** [comment]
Thanks Jos.

**Comment by Hypercubed** [comment]
@josdejong Sorry to hijack this old issue... but have you thought about implementing a BigNumberComplex type?  I've found myself doing just that, would like to avoid double efforts.

**Comment by josdejong** [comment]
Well, actually see this discussion of last days: https://github.com/josdejong/mathjs/issues/550#issuecomment-174639250
