### ISSUE TITLE
Error during compilation math.js by Google Closue

### ISSUE THREAD

**Issue by gang65** [josdejong/mathjs#503]
During compilation by Google closure:
https://developers.google.com/closure/

 I have errors, which is quite easy to fix.
Maybe it is worth to fix that?

java -jar ~/Dokumenty/compiler.jar  < ~/Pulpit/math.js 
The compiler is waiting for input via stdin.
stdin:115: WARNING - Keywords and reserved words are not allowed as unquoted property names in older versions of JavaScript. If you are targeting newer versions of JavaScript, set the appropriate language_in option.
	  math.import(__webpack_require__(13));
	       ^

stdin:9121: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
	          power: 1.0,
	                    ^

stdin:10491: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
	      offset: 0,
	               ^

stdin:10937: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
	      + latex.symbols['i'] + '\\cdot\\left(${args[1]}\\right)\\right)',
	                                                                      ^

stdin:19616: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
	    'lup(sparse([[2, 1], [1, 4]]))',
	                                   ^

stdin:19680: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
	    'x=usolve(sparse([1, 1, 1, 1; 0, 1, 1, 1; 0, 0, 1, 1; 0, 0, 0, 1]), [1; 2; 3; 4])',
	                                                                                      ^

stdin:25239: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
	      latexRightParens: false,
	                             ^

6 error(s), 1 warning(s)

**Comment by josdejong** [comment]
Thanks, fixed that on the develop branch.
