### ISSUE TITLE
Cannot refer to component of matrix variable in scope?

### ISSUE THREAD

**Issue by nasailja** [josdejong/mathjs#508]
The documentation doesn't seem to mention how to refer to a component of a matrix variable in scope, is it possible? Various versions the following didn't work:
```
var scope = {
    a: [[1, 2, 3]]
};
math.eval('a[0]', scope);
```

**Comment by devanp92** [comment]
It looks like [here](https://github.com/josdejong/mathjs/blob/049c5ce2c31737e5a59a5333a8d6230f48a4b180/test/expression/parse.test.js#L431), you need to first initialize a variable to hold 'a[0]' or call scope.a[0] in eval. Otherwise, you will get an undefined error.

```javascript
var scope = {
    a: [[1, 2, 3]]
};
var a = scope.a;
math.eval('a[0]', scope);
```

or

```javascript
var scope = {
    a: [[1, 2, 3]]
};
math.eval('scope.a[0]', scope);
```

**Comment by josdejong** [comment]
@devanp92 that's simply not correct. (did you actually run your code examples?)

@nasailja your matrix `a` is two dimensional, so you should provide an index with two dimensions. Running your code, math.js returns an error which gives you a clue: 
```
DimensionError: Dimension mismatch (1 != 2)
```
Besides that, the expression parser uses one based indexes, so you can access elements like this:

```js
var scope = {
    a: [[1, 2, 3]]
};
math.eval('a[1,2]', scope);  // returns 2
```

See also docs: http://mathjs.org/docs/expressions/syntax.html

**Comment by nasailja** [comment]
> `a: [[1, 2, 3]]`
Thanks, sorry, I wanted to use a 1d matrix but forgot to change my example. And I only tried with an index of 0... Is there a way to make indices start from 0? I'm only using 3 component vectors so I could replace [0]...[2] in all input with [1]...[3] if there's no other option.

**Comment by josdejong** [comment]
The JavaScript methods of math.js are zero-based, but the expression parser is one-based.

So you could use JavaScript instead, the equivalent of `math.eval('a[1]', scope)` would be:

```js
var a = [1,2,3];
math.subset(a, math.index(0));  // 1
```

See docs: http://mathjs.org/docs/reference/functions/subset.html

**Comment by nasailja** [comment]
Thanks but my use case is to parse expressions from users to catch errors before they get to a program that uses C++ expression parsers so the mathjs syntax should be close. Replacing [0]...[2] with [1]...[3] should be easy enough but more complicated transformations are probably not feasible at this point.

**Comment by josdejong** [comment]
This differing behavior in the expression parser is achieved via transforms, see docs:

http://mathjs.org/docs/expressions/customization.html#function-transforms

It's a bit hacky, but you can simply remove all transforms if you want, you can find them under `math.expression.transform`, which is an object containing the transform functions and extends the `math` namespace.

```js
var scope = {
  a: [1,2,3]
};

// original behavior: one-based, upper-bound included, etc:
math.eval('a[1:3]', scope);  // [1,2,3]

// throw away all transform functions -> get the JS behavior in the expression parser
math.expression.transform = Object.create(math);

// zero-based indexes, upper-bound excluded, etc.
math.eval('a[0:3]', scope);  // [1,2,3]
```
