### ISSUE TITLE
Support for frequency (Hz)?

### ISSUE THREAD

**Issue by Fidel90** [josdejong/mathjs#510]
Hello,

is there already support for the Hz unit? I can't find anything (only something like s^-1 seems to work). It would be great to convert through the given prefixes (Hz to kHz and so on) and it would be even better to have the ability to convert a frequency to a time unit (e.g. 5Hz -> 200ms). Would this be a possible feature?

**Comment by josdejong** [comment]
Thanks, `Hz` (and `Hertz`) are still missing, we should add this one.

**Comment by josdejong** [comment]
Support for `hertz` and `Hz` is implemented by @SwamWithTurtles and is now available in v2.5.0.

**Comment by Fidel90** [comment]
Great, thank you very much :) Is it possible to add conversion Hz <--> s? I'd like to do sth. like:

`math.unit(5, "Hz").to("ms").toString() --> "200 ms"`

**Comment by josdejong** [comment]
Please note that `1Hz` equals `1/s`, not `1s`. You can do:

```js
math.unit(5, 'Hz').to(math.unit('s^-1')).toString();  // 5 s^-1  
math.divide(1, math.unit(5, 'Hz')).toString();        // 200 ms
```

**Comment by Fidel90** [comment]
This seems to works nice for my approach:

`math.divide(1, math.unit(5, 'Hz')).to("ms").toString(); //200 ms`

Thanks again :+1:
