### ISSUE TITLE
math.mod doesn't return the right value

### ISSUE THREAD

**Issue by atiertant** [josdejong/mathjs#513]
math.mod(10.8,1.2);

return

    1.7763568394002505e-15

instead of 0

**Comment by josdejong** [comment]
That's a round-off error. Basically you could round your outputs to say 14 digits to prevent this, or you could use BigNumbers. See docs:

http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
http://mathjs.org/docs/datatypes/bignumbers.html

**Comment by atiertant** [comment]
thank you !
