### ISSUE TITLE
What does “a flexible expression parser” mean?

### ISSUE THREAD

**Issue by tomekwi** [josdejong/mathjs#514]
Hi,

the front page of mathjs says that it sports “a flexible expression parser”. Does that mean that I can extend the parser somehow?

Right now in the library http://parametric-svg.js.org/ we use mathjs under the hood – but we support extra syntax like [template strings](https://github.com/parametric-svg/-/tree/d9d615f5a466fb0a655e36e2e0f02675e97814f5/packages/spec#/syntax/template-strings). As we didn’t have time to write our own parser from scratch, we temporarily made a bit of a trick which transpiles parametric-svg expressions to mathjs expressions. https://github.com/parametric-svg/-/tree/master/packages/expression-to-mathjs.

Is it possible to configure your parser so that it supports new syntax? Or do we really have to write our own parser there?

**Comment by josdejong** [comment]
Maybe "flexible" isn't the best description for the parser, words like "feature rich" or "extensive" may be a better fit. I had in mind the flexibility of how you can use it with providing a scope, parsing into [a tree](http://mathjs.org/docs/expressions/expression_trees.html), processing and transforming expression trees, adding new functions to math [define transforms](http://mathjs.org/docs/expressions/customization.html#function-transforms) for them if needed or have them [process their own arguments](http://mathjs.org/docs/expressions/customization.html#custom-argument-parsing). 

Anyway, the exrpession parser is not yet "extensible" or "customizable" in a way that you can add new operators or change their behavior, or add new features like template strings. Would be great to make the parser more flexible in this regard, see also https://github.com/josdejong/mathjs/issues/467.

For now the only options for you that I can think of are:
- Preprocess the expressions and replace template strings with a regular function notation that the parser of math.js can handle. For example replace ``d="`M ${1 + 2}, ${3 + 4}`"`` with something like `d=template("M ${1 + 2} ${3 + 4}")` and implement a regular function `template` which replaces the placeholders in the string with their evaluated result. You could probably use [custom argument parsing](http://mathjs.org/docs/expressions/customization.html#custom-argument-parsing) to evaluate the placeholders with the correct scope at hand.
- Generate your own parser using a parser generator like [jison](http://zaach.github.io/jison/) or [peg.js](http://pegjs.org/).

**Comment by tomekwi** [comment]
Thanks for the explanation! I’ll look into both options you’ve suggested.

I’m excited to see what #467 brings about. Cheers!
