### ISSUE TITLE
Add time units

### ISSUE THREAD

**Issue by owenversteeg** [josdejong/mathjs#520]
Would you be open to adding some time units to Math.js? I feel that they're very useful, especially for end users, who quickly tire of dividing everything by 3600 seconds (or 86400 seconds) to get a usable figure. 

```
Month: 2629800 sec (length of an average month, lasting 30.416667 days, 1/12th of a Julian year)
Year: 31536000 sec (length of a regular, non-leap year) OR 31557600 sec (length of a Julian year)
Decade: 315360000 sec, for exactly 10 normal years, OR the Julian decade of 315576000 sec
Century: 3153600000 sec, for exactly 100 normal years, OR the Julian century of 3155760000 sec
Millennium: 31536000000 sec, for exactly 1000 normal years, OR the Julian millennium of 31557600000 sec
```

I think it makes the most sense to just define the year as the Julian year of 31557600 sec, and set the month to 1/12th of that, the decade to 10x that, century to 100x that, and millennium to 100x that. Really, the only benefit of using the length of a "normal" year is that you get 365 days per year.

**Comment by josdejong** [comment]
Thanks for your suggestion. 

I'm a bit unsure about whether to add month, year, etc. as the length of these are ambiguous (from a practical point, a month can be 28, 30, or 31 days). I'm not sure what people would expect and I have a feeling that no matter what solution we choose (like 1/12th of a Julian year which is reasonable), people will get confused anyway.

So before we decide on this I would like to think a bit about the use cases that this would serve. Do you have any clear use cases? And how to other similar libraries solve this?

I was also thinking about implementing support for time and duration similar to how [moment.js](http://momentjs.com/) works: convert from date string to timestamp and vice versa, add time units like 1 day to some moment, etc. Maybe we can create a function to calculate the duration between two moments in time. There is also the plugin [moment-duration-format](https://github.com/jsmreese/moment-duration-format) which [uses different ratios](https://github.com/jsmreese/moment-duration-format/blob/master/test/moment-duration-format-tests.js#L81-L101).

**Comment by Nekomajin42** [comment]
I think the most frequent use case is calculating the difference between two dates. Like today is X and I was born in Y, so I am Z days old. It's the same with time. I started to run at X and now it's Y, so it was Z minutes long.

It would be very practical to be able to do calculations like these. With time, it's not a problem, however there is the thing with the lengths of months and leap years.

**Comment by owenversteeg** [comment]
I agree that the length of a month is ambiguous, but I also feel that in the context of any problem entered into Math.js the user would certainly expect a month to be 1/12 of a Julian year. Almost everywhere I looked uses 1/12 of the Julian year as the definition for a month without context, including Wolfram|Alpha and Google's Instant.

Here are some examples of how people expect to be able to use Math.js that are only possible with time units: 
 - Fractions of a year: (5 months+3 days)/1 year
 - Speed: 3 miles/month to mph
 - Modeling weight gain/loss: 4 kg/month to g/day
 - More speed calcs: 200m/day to m/year
 - Modeling speed increases in cars: 5 mph/decade * 1 millennium

Basically, a lot of what makes Math.js useful -- its ability to do dimensional analysis -- hinges on having all the commonly used units, and people use weeks, months, and years all the time. I know I hear people use weeks much more than they use, say, hogsheads or henrys, as valuable as those units are. Also, a user might be confused why they can't use weeks but can use days, hours, and minutes.

Also, I feel that for now the priority should just be to implement these time units basically, and in the future move on to something more complex (like adding a day to a date.) I can make a separate issue for that, especially as this is a simple change and that would take more code and work.

**Comment by josdejong** [comment]
Thanks for your indepth feedback. I think you're right that 1/12th makes most sense. Thanks for listing some use cases, this indeed makes sense. You convinced me :)

**Comment by owenversteeg** [comment]
Great, thanks! I've written up #526 so we can tackle the issue of more complex time calculations when we have the time.
