### ISSUE TITLE
It will be great to upgrade decimal.js to 4.0.3

### ISSUE THREAD

**Issue by gang65** [josdejong/mathjs#521]
With decimal.js 4.0.3 the internal rounding was fixed.
https://github.com/MikeMcl/decimal.js/commit/277e8a8ad39b8c6411dec88235d8615b23c350e7

I don't know if it is critical  for math,js, but maybe we should consider to upgrade.

**Comment by josdejong** [comment]
Thanks, sure let's update to the latest dependency versions in the next release. Probably next week.

**Comment by josdejong** [comment]
math.js v3 has upgraded to decimal.js v5.
