### ISSUE TITLE
Retrieving a single column using math.index not working

### ISSUE THREAD

**Issue by johnmarinelli** [josdejong/mathjs#523]
Consider:

```javascript
let mat1 = math.matrix([[1,2,3],[4,5,6],[7,8,9]]);
let mat2 = mat1.subset(math.index([0,1,2], [1,1]))
// =>
/*
Matrix {
  _data: [ [ 2, 2 ], [ 5, 5 ], [ 8, 8 ] ],
  _size: [ 3, 2 ],
  _datatype: undefined }
*/
```

What this is doing is returning a matrix with a duplicate column rather than a single column.  Is there another way to get a column from a matrix?  If not, I can fix this.

**Comment by josdejong** [comment]
You should change

```js
math.index([0,1,2], [1,1])
```
into

```js
math.index([0,1,2], [1])
```
however, it looks like math.js returns a faulty result then: `2` instead of `[[2],[5],[8]]`. This really surprises me as the code is quite heavily unit tested. I will fix this asap.

What works correctly is:
```js
math.index([0,1,2], 1)
```

**Comment by josdejong** [comment]
This issue is fixed now in the `develop` branch
