### ISSUE TITLE
variables' roots makes complex numbers where not needed

### ISSUE THREAD

**Issue by KoalaHuman** [josdejong/mathjs#524]
x = -27
x ^ (1/3)
// 1.5 + 2.5980762113533i
// but (-3) ^ 3 = -27 and nthRoot(-27, 3) also = -3

**Comment by ericman314** [comment]
There are three cube roots of `-27`, two complex and one real. `nthRoot` always returns the real root, but the `^` operator returns the principal root, which is not always the same as the real one you might prefer to get.

There's already plenty of discussion on what constitutes the "preferred" root to return. Let's continue the conversation here: #486 

Just in case there is some confusion, note that the string `"-27 ^ (1/3)"` is parsed as `-(27 ^ (1/3))`, which *is* `-3`. However, `(-27) ^ (1/3)` returns `1.5 + 2.5980762113533i`.
