### ISSUE TITLE
Advanced time calculation

### ISSUE THREAD

**Issue by owenversteeg** [josdejong/mathjs#526]
In #520, the idea of doing calculations with time seemed popular. After the merge of #522, the current calculations that are possible are all relatively simple, for example `10 days+2 months+10 hours to seconds`.

More advanced time calculations would likely involve using Moment.js, which is a popular, tried and tested library that should be relatively easy to integrate due to its robust API. 

If this issue is something that people want (which it seems that it is) here are some example calculations:
- `Dec 25, 2015 plus three days and a month`
- `Three hours from now`
- `Time from Aug 3, 2000 to Sept 3, 2010`

I think this would be an excellent addition to Math.js, and it would cover a number of calculation bases. It would also remove all ambiguity from calculations involving days, weeks, months, years, etc. -- if a user needs the exact precision demanded by a date calculation and doesn't want to use the Julian year approximation, they can provide the dates in question and get an exact result.

**Comment by josdejong** [comment]
Thanks for sharing your ideas. 

What I have in mind is that we use moment.js and allow using it in the expression parser of math.js like:

```
a = date("2015-12-26")
b = date("2015-12-29")
diff = a - b
c = b + 2 days
```

I think we come a long way extending the functions `add` and `subtract` with support for dates (could be either Date or moment instances). Moment.js is quite a large library, I'm not sure if we really should use it here. Maybe it's not needed to use moment.js and we can just use smaller a date parsing library or something.

**Comment by m93a** [comment]
Let's continue the discussion in #384
