### ISSUE TITLE
Update Contribute.md style guide link

### ISSUE THREAD

**Issue by joshghent** [josdejong/mathjs#528]
Kind of new around these parts but just noticed a minor thing.

In the Contribute.md file, you point to a style guide found [here](http://nodeguide.com/style.html)
However, that link states that the version is outdated and points to a github page found [here](https://github.com/felixge/node-style-guide).

Is this intended?

If it is not then I will happily fix this :grinning:

**Comment by josdejong** [comment]
Thanks for reporting. That's funny, this was noticed two days ago by @paulmasson and is fixed already in the develop branch (see #527).

**Comment by joshghent** [comment]
Ah didn't spot that!
