### ISSUE TITLE
math.js and react-native experiment

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#534]
Just to share something fun: today I familiarized myself with [react-native](https://facebook.github.io/react-native/), and built a simple calculator app using math.js:

https://github.com/josdejong/react-native-mathjs-demo

It's no fully fledged application, just an experiment. Tested on Android, should work out of the box on iOS too. Have fun :)

**Comment by neilhighley** [comment]
v4.2.1 doesn't play nice with react-native, 3.9.3 seems to work ok.

**Comment by josdejong** [comment]
@neilhighley thanks for reporting, can you open a separate issue for this and provide some more details?
