### ISSUE TITLE
Question regarding mathjs.format()

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#538]
The result that I am getting back after evaluating the expression mathjs.eval('-5.1^(-8.99+0.85)') is -0.00000173931709936.

After executing the code below, I get the same result back, instead of getting the result of either -0.000001739317 or -1.7393170993647e-6.

var result = -0.00000173931709936;
result = mathjs.format(result, {
                    notation: 'auto',
                    precision: 12,
                    exponential: {
                        lower: -1e-12,
                        upper: 1e+12
                    }
                });

Another example is mathjs.eval('factorial(77)/factorial(80)'), where the returned result is 0.00000202856215514.  

When you get a free moment, would you assist me with this issue.

**Comment by josdejong** [comment]
From the docs on [math.format](http://mathjs.org/docs/reference/functions/format.html):

> precision: number A number between 0 and 16 to round the digits of the number. **In case of notations 'exponential' and 'auto', precision defines the total number of significant digits returned** and is undefined by default. In case of notation 'fixed', precision defines the number of significant digits after the decimal point, and is 0 by default.

To get the result formatted as `-0.000001739317` you can use the `fixed` notation.
To get the result formatted as `-1.73931709936e-6` you can use the `exponential` notation.

**Comment by sonnyk22** [comment]
Thank you!
