### ISSUE TITLE
Question related to math.parse() function

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#539]
I came across this documention that I believe maybe a fantastic solution for solving an issue that I have:
http://mathjs.org/docs/expressions/expression_trees.html 

Lets use this expression as an example: 4 * sin(4*(pi/2)) * sin(3pi/2) * sin(pi/(4/2))

Is there a way that I can leverage math.parse() and the use of its math.parse().filter() to get an array for every sin() functions that has a pi/2 or .eval(pi/(4/2)) which is pi/2?

It would be great if its possible to do this.

**Comment by FSMaxB** [comment]
This is certainly possible.
(You mean an array *containing* every sin function like that, not an array for every sin function, right?)

```js
var sinArray = [];
var expression = math.parse("4 * sin(4*(pi/2)) * sin(3pi/2) * sin(pi/(4/2))+sin(pi/2)");
expression.filter(
  function (node) {
    if ((node.type == "FunctionNode") && math.equal(node.eval(), 1)) {
      sinArray.push(node);
    }
  }
);
sinArray.forEach(
  function (node) {
    console.log(node.toString());
  }
);
```

Output:
```
sin(pi / (4 / 2))
sin(pi / 2)
```

Note: I added `sin(pi/2)` at the end to demonstrate that it works.

**Comment by sonnyk22** [comment]
Awesome!  Thank you!
