### ISSUE TITLE
Eigenvalue

### ISSUE THREAD

**Issue by WG-** [josdejong/mathjs#542]
Simple question, why does this library not have a function to calculate the eigenvalues of a matrix?

**Comment by josdejong** [comment]
Simple answer: nobody has yet implemented it. It's indeed an important function to have when working with matrices.

**Comment by timqian** [comment]
@jherdman Is there anyone working on it? Or I will have a try on this feature.

**Comment by josdejong** [comment]
@timqian As far as I know nobody is working on it. Would be great if you could pick it up.

**Comment by kv-kunalvyas** [comment]
I can pick it up if no one has started on it yet.

**Comment by josdejong** [comment]
Thanks Kunal, that would be great!

**Comment by m93a** [comment]
See issues #1741 and #2180.
