### ISSUE TITLE
Unit conversion after calculation

### ISSUE THREAD

**Issue by mazing** [josdejong/mathjs#543]
Great library!

But why is it not possible to for instance evaluate `2+2 cm to inches`?

It should do the calculating first and then convert it.

**Comment by josdejong** [comment]
Thanks :)

Addition (+) has a lower precedence than implicit multiplication (2 cm). It's the same as doing `2 + 3 * 4`, which is evaluated as `2 + (3 * 4)`. 

Your expression `2+2 cm to inches` is evaluated as `(2 + (2 * cm)) to inches`. To override the default precedence, you can enclose your addition in parentheses:

```
(2+2) cm to inches
```
