### ISSUE TITLE
Question related to 0^0

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#545]
Currently, MathJS.eval() returns a 1 for the expression of 0^0.  I believe the answer should be undefined or throwing an exception. I tried this on a few different calculators and gotten Domain error or undefined, and as well for (1-1)^0.  Is there a parameter that I can pass into .eval() to provide a result of not 1?

**Comment by josdejong** [comment]
hm, interesting point. I think you're right that the mathematically correct result is undefined ([Mathematica gives that as result](http://www.wolframalpha.com/input/?i=+0%5E0+)), though most programming languages and also Matlab return `1` when you evaluate `Math.pow(0, 0)`.

**Comment by sonnyk22** [comment]
Is there a possibility to put a request to make this a feature enhancement?

**Comment by josdejong** [comment]
Yes maybe we want to change this but I really have to give is some more thought. The mathematically correct answer is not always useful (like [working with infinity](https://github.com/josdejong/mathjs/issues/444) ;) ).

**Comment by sonnyk22** [comment]
Is there a way that I can use any of the provided MathJS functions (such as .parse(), etc), or a similar strategy as you mentioned in #562 to find out when an expression results to 0^0.

For example:  (((4-4) + (4+4)) * (1-1))^((5-1)-4)

**Comment by josdejong** [comment]
Sure, you can do exactly the same as I proposed in #562 with pow.

**Comment by sonnyk22** [comment]
Your solution worked perfectly for my need!  Thank you!

Should I close this issue ticket or leave it open as a possible future enhancement?

**Comment by josdejong** [comment]
I think it's fine to close it. There are simply different justifiable behaviors for `0^0` and current behavior is a common one. We can always rethink it if there is a good reason.
