### ISSUE TITLE
Question about mathjs.parse() and %

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#547]
To better illustrate my question, lets use the example code below:

var expr = '5%290+sqrt(89)-1';
var scope = { percent: 0.01 };
var result = math.eval(expr, scope);

In the above code, I can pass in an scope object to the math.eval() function, and MathJS engine will know what to do with the %.

Is there such option parameter for the math.parse() function?  If not, is there an strategy you can recommend me to follow to accomplish this?  I am not sure by replacing % with '/100*' may not work all the time with certain expressions.

**Comment by ericman314** [comment]
Perhaps try replacing each `%` with `(percent)`:

```js
var expr = '5%290+sqrt(89)-1';
var scope = { percent: 0.01 };
var result = math.eval(expr.replace('%', '(percent)'), scope);
```
