### ISSUE TITLE
Operators for Units and Numbers

### ISSUE THREAD

**Issue by hgupta9** [josdejong/mathjs#548]
Brilliant syntax, whoever thought of bringing units directly into equations! The only thing that comes close (or goes further), is Google's math input.

Currently a few very simple unit expressions that fail to evaluate are:
- 2 + 2 cm .... [fails](https://www.google.co.in/search?q=2%2B2+cm&oq=2%2B2+cm&es_sm=93&ie=UTF-8#q=2+%2B+2+cm+in+inch) in google
- 2 cm + 2 .... [works](https://www.google.co.in/search?q=2%2B2+cm&oq=2%2B2+cm&es_sm=93&ie=UTF-8#q=2+cm+%2B+2+in+inch) in google

>TypeError: Unexpected type of argument in function add (expected: Array or Matrix, actual: number, index: 1)

Can these be supported by adding a Unit/Number and Number/Unit version into the add function? I'm really new to the library so I wanted to ask if such a thing is easily possible before messing with the code.

The way they would function
- 2 + 2 cm
  - adding 2 (Number) and 2 cm (Unit)
     - since 2nd arg is Unit, add 2 to the Unit, resulting in 4 cm (Unit)
- 2 cm + 2
  - adding 2 cm (Unit) and 2 (Number)
     - since 1st arg is Unit, add 2 to the Unit, resulting in 4 cm (Unit)

**Comment by ericman314** [comment]
Thanks, @hgupta9!

`2 cm + 2` doesn't work by design. You could run into all kinds of ambiguities with something like `2 cm + 2 + 4 inch`. So we require the units to be included explicitly.

If you want to take a crack at messing with the code, see #426 for a similar discussion on this topic and example code to extend the `add` and `subtract` functions.

Also, when I click on your [second link](https://www.google.co.in/search?q=2%2B2+cm&oq=2%2B2+cm&es_sm=93&ie=UTF-8#q=2+cm+%2B+2+in+inch) google shows the query `2 cm + 2 in inch` and returns `(2 cm) + (2 in)`, not `(2 cm) + (2 cm)`. It's possible google is interpreting the `in` operator as an abbreviation for inches, then returns the result in inches. This is the equivalent expression in math.js:

```
2 cm + 2 in to inches
2.78740157480315 inch
```

**Comment by hgupta9** [comment]
I understand about the ambiguities, but it would still be nice for simple expressions like the ones I listed in my question. Anyways what would be the code needed for adding or subtracting two units? (to replace the `...` in the code snippet below) I am totally new to the library's inner functionality so I don't want to mess around.

```
math.import({
  add: math.typed('add', {
    'Unit, number': function (x, y) { ... }, // <--- what goes in here??
    'number, Unit': function (x, y) { ... }
  }),

  subtract: math.typed('subtract', {
    'Unit, number': function (x, y) { ... },
    'number, Unit': function (x, y) { ... }
  })
})
```

**Comment by josdejong** [comment]
Hi, I agree with @ericman314 in that this will lead to ambiguities and is better not to do. It's perfectly fine of course if you like to play around and see how far you can get.

There is no implementation of adding a number to a unit right now as that's ambiguous: you don't give information on how to normalize the number. When you create a unit, it normalizes it's value and forgets it's original unit and prefix (unless you specifically convert to some unit), so you would have to change that behavior. After that, it would be possible to create a new unit from a number using the unit and prefix of the other value. Next, for the expression parser, you will have to determine whether the addition was part of a chain of additions/subtractions containing ambiguities like the example @ericman314 gave.

**Comment by hgupta9** [comment]
Did you check my code example below yours? Is it correct? Would that work fine?

**Comment by josdejong** [comment]
Yes that would be correct except that `x.unit` does not exist right now for the reasons I explained, so you would have to do some work there. And as a small optimization you could use `math.addScalar` instead of `math.add`. Again, I don't think this will be a fruitful exercise but if you really want I will not stop you of course.

**Comment by hgupta9** [comment]
If by normalization you mean that 1 kg becomes 100 gram (since K is just gram * 1000), then the following equation :

   1 kg + 2

Would actually evaluate as:

    1 kg + 2 grams = 1002 grams

Creating ambiguities in the unit type postfix as well. Why is the original postfix (kg) not retained in the Unit object? I'm sure retaining that information would be useful for other uses cases as well. Perhaps as a property `originalUnit` or something like that. That would enable me to write the following:

    'Unit, number': function (x, y) { return math.add(x, math.unit(y, x.originalUnit)); }
    'number, Unit': function (y, x) { return math.add(x, math.unit(y, x.originalUnit)); }

Which would correctly evaluate my expression of `1 kg + 2` as :

    1 kg + 2 kg = 3000 grams

**Comment by josdejong** [comment]
> I really want it because it would make the expressions "smarter" IMO.

Yes I understand that. I expect though that the downsides (ambiguities resulting in WTF's) are bigger than the benefits (less verbose syntax).

> Why is the original postfix (kg) not retained in the Unit object? I'm sure retaining that information would be useful for other uses cases as well.

Yes that could be useful. So far it wasn't needed.

**Comment by hgupta9** [comment]
Any idea which file I should dig through to retain that info?

**Comment by josdejong** [comment]
That is correct.

The Unit class is here: https://github.com/josdejong/mathjs/blob/master/lib/type/unit/Unit.js
The expression parser is here: https://github.com/josdejong/mathjs/blob/master/lib/expression/parse.js

**Comment by hgupta9** [comment]
Thank you! I'll see what I can do.

**Comment by ericman314** [comment]
@hgupta9, the Unit class does retain that information already. [Here](https://github.com/josdejong/mathjs/blob/5911fe6ffd7c44bf9173cd00a8652d87d547ca12/lib/type/unit/Unit.js#L51) in the constructor an array of units used to build the unit are saved in the `units` property. This array of units is used in `Unit.prototype.formatUnits` for example to output a Unit using the original list of units it was created from.

Not to encourage what @josdejong has called a fruitless exercise, but nevertheless interested in seeing if it can be done, I would suggest using the `_denormalize` function to extract the value of the unit as expressed in the original unit string. Keep in mind however that something like this: `1 inch + 2 cm + 3 feet + 4` would be evaluated as `((1 inch + 2 cm) + 3 feet) + 4` and that during addition only the first unit is kept and the second is discarded. It would be evaluated like this:

```
((1 inch + 2 cm) + 3 feet) + 4
= (1.7874015748031 inch + 3 feet) + 4
= 37.787401574803 inch + 4
= ?
```

So the `4` would be assigned units of inches, not feet as the original expression `1 inch + 2 cm + 3 feet + 4` may have suggested. Also realize that complicated unit strings like `kg m / s^2` are subject to simplification to `N`, so the original units might be lost anyway. Anyway, very interested in seeing what you come up with!

**Comment by josdejong** [comment]
@ericman314 thanks, I wasn't aware that the original units where already stored, nice.
