### ISSUE TITLE
More aliases for common units

### ISSUE THREAD

**Issue by hgupta9** [josdejong/mathjs#551]
Where do I add additional aliases for common units? Currently the following do not work:

- for hour : h, hr, hrs
- for minute : m, min, mins
- for second : s, sec, secs

As I understand the current ALIASES list only allows one alias per unit type, and its already used up for plural functionality. If it supported an array of aliases I could just add it in. Also, `m` is currently used for 'meter' so it will conflict, therefore, it may only be possible to add 'min' and 'mins' for minutes.

The docs say 'min' is used for `liquid volume/minim`, but I would rather rewire it for `minute`. Many of these changes I could make in a fork but currently this is impossible as the ALIASES list does not take an array.

**Comment by josdejong** [comment]
Thanks, yes lets add these aliases. 

If you want to use them right now, you could use them in the expression parser like:

```js
math.import({hrs: math.unit('hour')});
math.eval('5 hrs in minutes'); // 300 minutes
```

If `min` is documented to be liquid volume I think we should remove that as it's conflicting with the function `min` (sibling of `max`).

**Comment by hgupta9** [comment]
Is this correct then? (I leave out `m` which is used for `meter` and `s` which is already assigned to `second`)

    math.import({h: math.unit('hour')});
    math.import({hr: math.unit('hour')});
    math.import({hrs: math.unit('hour')});
    math.import({mins: math.unit('minute')});
    math.import({sec: math.unit('second')});
    math.import({secs: math.unit('second')});

**Comment by josdejong** [comment]
yes that would be correct. 

I was thinking, though, the solution using math.import will work in the expression parser, but will not allow you to create a unit like `math.unit('5 hrs')`. So a better workaround would be: 

```js
var aliases = {
  h: 'hour',
  hrs: 'hour',
  // ...
};

for (var name in aliases) {
  if (aliases.hasOwnProperty(name)) {
    var original = math.type.Unit.UNITS[aliases[name]];
    var alias = Object.create(original);
    alias.name = name;
    math.type.Unit.UNITS[name] = alias;
  }
}
```

Anyway it's just a few lines of code to add these aliases to math.js itself, we will do that.

**Comment by hgupta9** [comment]
Is there any API for devs to add their own units into the system? I have a few custom units (in a new unit base) that I want to convert via the math.js library but have no idea where to start. Basically I need to add a new base, then a couple of units with that new base, then a couple of aliases for that.

**Comment by hgupta9** [comment]
OK thats nice. Thanks for the help.

**Comment by hgupta9** [comment]
I finally managed to add the following aliases in:

- hour : h, hr, hrs
- minute : mins
- seconds : secs

Sadly I had to exclude `min` and `sec` since there were functions by that name.

- `min` which is mapped to the `min()` function
- `sec` which is mapped to the `sec()` function

I wonder if there's a way to respond to these 2 since they are extremely common in colloquial syntax.

**Comment by josdejong** [comment]
I've added these aliases to math.js, they will be available in the first next release. (`h` is already available).

If you want to use `sec` and `min` for units, you can always rename these functions, and override them as units with the solutions we discussed above. Of course that makes the original functions harder to use. Could be something like:

```js
math.import({
  secTheFunction: math.sec,
  minTheFunction: math.min,
  sec:            math.unit('second'),
  min:            math.unit('minute')
}, {override: true});
```

**Comment by hgupta9** [comment]
Wow. Thats amazing. Thanks for the help!! I tried overloading but it crashed with an error. `override` is what I needed.

**Comment by hgupta9** [comment]
Oh my, for some reason the following overrides "sec" correctly but "min" refuses to be overridden.

    math.import({
         minFunc: math.min,
         secFunc: math.sec,
         min: math.unit('minute'),
         mins: math.unit('minute'),
         sec: math.unit('second'),
         secs: math.unit('second'),
    }, {override:true});

**Comment by hgupta9** [comment]
Its alright. Don't bother. I had to change the source code in various places to change `min` to `minFunc`. I don't think you should waste your time on this. Thanks for all the help, dude!
