### ISSUE TITLE
Expression passed in .parse() and eval() functions.

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#552]
To better illustrate the results I am getting, lets use the code below (I am using Chrome Developer Tool):

var ex = '-(8)!';

When executing the .eval() function, I am getting 2 different results:
mathjs.eval(ex) throws an exception, but mathjs.eval('-(8)!') outputs the correct results.
![calc1](https://cloud.githubusercontent.com/assets/6744710/12460669/dfbb0036-bf82-11e5-97bf-9fe9bdfcca7d.png)

Its seems that this is also happening with the .parse() function as well:
![calc2](https://cloud.githubusercontent.com/assets/6744710/12460670/e10aa4be-bf82-11e5-981a-7a6523fee714.png)

**Comment by josdejong** [comment]
Seen from your screenshots, the `-` in the variable `ex` is not a regular hypen character a dash.

**Comment by sonnyk22** [comment]
Thank you!
