### ISSUE TITLE
Limit eval parser

### ISSUE THREAD

**Issue by mazing** [josdejong/mathjs#553]
Is it possible to limit the eval parser to only handle addition, subtraction, multiplication, and division and hence no unit conversion, matrix operations, bitwise operations, etc?

**Comment by josdejong** [comment]
To do that you will have to hack into [the parser](https://github.com/josdejong/mathjs/blob/master/lib/expression/parse.js) and disable all parts that you don't want. It's perfectly doable but requires some effort.
