### ISSUE TITLE
Class-wise docs for Math.js

### ISSUE THREAD

**Issue by hgupta9** [josdejong/mathjs#556]
As I understand after sifting through the online docs, there are no class-wise docs. This creates a lot of confusion during usage. Firstly its quite unclear that all the methods (most) are top-level methods directly under `math.*`. Usual numeric libs let you call common arithmetic functions on the object, eg, for bignumbers you would call `myBigNum.add(2)`, not `math.add(myBigNum, 2)`. Secondly, there a quite a few data types (classes) in the system and there is more ambiguitiy if the function would be on the object (units, bignumbers, matrix, etc) or on the top-level `math` var.

I have attempted to create some [class-wise docs](https://github.com/hgupta9/mathjs/tree/master/docs/classes) following the node.js doc format (which I loved). I have limited it to one class per MD file and specified properties and methods explicitly. Each input argument is discussed in whatever form is appropriate and the data type is also specified (where needed).

 I have written these for my own usage, but please review these and consider if such docs can be added into the Math.js website. Again, these are partial docs and created in a hurry so do not represent the best possible version. The [Top Level](https://github.com/hgupta9/mathjs/blob/master/docs/classes/top_level.md) file has seen the most work, notice how my format differs and expands on the current Math.js docs.

- [Top Level](https://github.com/hgupta9/mathjs/blob/master/docs/classes/top_level.md) functions
- [Parser](https://github.com/hgupta9/mathjs/blob/master/docs/classes/parser.md) object
- [Complex](https://github.com/hgupta9/mathjs/blob/master/docs/classes/complex.md) object

I will create more class-wise docs according to my usage and according to the feedback I receive here.

**Comment by hgupta9** [comment]
Some advantages of the "nodejs-style" class-wise docs:

1. They must be *complete*, and document every single property and function available in a given class. Obviously this would take some doc effort. Currently the docs offer only an incomplete picture of each class, with a few functions documented here and there. This creates a lot of confusion.

2. The formatting helps understand the various properties and functions of each class. Just taking a glance at the headings helps you understand the approx. behavior of the class. See the class-wise [Complex](https://github.com/hgupta9/mathjs/blob/master/docs/classes/complex.md) vs the current [Complex](https://github.com/hgupta9/mathjs/blob/master/docs/datatypes/complex_numbers.md) file.

3. The "type" documentation helps. Ssee [math.bignumber()](https://github.com/hgupta9/mathjs/blob/master/docs/classes/top_level.md#mathbignumbervalue) vs the current [BigNumbers](https://github.com/hgupta9/mathjs/blob/master/docs/datatypes/bignumbers.md) file. I've specified the exact set of supported input types that `math.bignumber()` can handle, rather than relying on assumption.

4. Listing each signature separately helps. For example since [math.complex()](https://github.com/hgupta9/mathjs/blob/master/docs/classes/top_level.md#mathcomplexstring) had multiple different signatures (not just optional args) I listed each separately. This lets us document each signature and therefore each use-case independently without causing confusion.

5. All possible use cases must be documented/demonstrated. For example in [math.import()](https://github.com/hgupta9/mathjs/blob/master/docs/classes/top_level.md#mathimportobject-options) I've added an example for "unit aliases"; a behavior that I just discovered (via a [github issue](https://github.com/josdejong/mathjs/issues/551)) but something that the authors might have known for a long time. Just creating better docs would have all of this wonderful behavior discovered easily by devs.

6. Only one right place to find docs. Based on the class they are in. Currently since docs are grouped by functionality, the library authors and users have some confusion as to where to place/find docs regarding a certain data type or function.

**Comment by josdejong** [comment]
Thanks for your input @hgupta9 . 

There are indeed a lot of methods available on instances of BigNumbers, Fractions, Units, etc. These are not documented, they are not considered "public API", though still available if you need to go "under the hood" for some reason. 

The core idea of math.js is to integrate support for different data types. It uses static functions and no class methods. Math.js favors `add(x, y)` over `x.add(y)`. This allows us to do operations on mixed data types, wheres class methods of individual datatype typically only supports operations on it's own data type.

**Comment by hgupta9** [comment]
Yes I understood that. Did you see my class-wise docs? Did you like any of them? Would you consider adding such things to your docs?

**Comment by josdejong** [comment]
Yes if there are methods that we see as "public" API we should document them.

**Comment by hgupta9** [comment]
If I do class wise docs, will you add them to the MathJS Website at the bottom of the docs page under a title called "classes" or something similar?

**Comment by josdejong** [comment]
Yes, for most types we already have a page (BigNumbers, Fractions, Matrices, Units). These should all have a section "API". Units and Complex numbers already have their methods described, but it's missing for Fractions, BigNumbers, an Matrices. It would be great if you could help writing these sections. I think it should roughly contain the construction methods conversion methods (like toString), but not the operations like `add`, `multiply`, etc, as we want to encourage using the static functions of math.js like `math.add`, `math.multiply`. What do you think?

**Comment by hgupta9** [comment]
I agree with you on most points. I'll do class wise docs for those "class" types. One point however, needs more discussion. Top level functions. I finally discovered that TL functions are under "[reference > functions](http://mathjs.org/docs/reference/functions/alphabetical.html)". I think this section should be reserved for math functions only. The name "functions" in a mathematical context implies math functions. Special TL functions like `config`, `eval`, `compile`, `parse` should be documented in a separate file called "top level" or "main" or something and added as an entry on your main docs page. That's where I, as a dev would expect to find such functions. Also, if we can just modify the main docs page to point to each "class" page (all which already exist) it would make it easier to find such content.

**Comment by hgupta9** [comment]
See if you like the format of [this](https://github.com/hgupta9/mathjs/blob/master/docs/index.md#api). 

- Adding the classes into the main docs page is the only major change I made. 
- I will keep working on the Top Level file, obviously its not ready for upload right now.
- [Parser](https://github.com/hgupta9/mathjs/blob/master/docs/datatypes/parser.md) is all new
- [Complex ](https://github.com/hgupta9/mathjs/blob/master/docs/datatypes/complex_numbers.md)has a different format (matching Node.js docs)
- [Units ](https://github.com/hgupta9/mathjs/blob/master/docs/datatypes/units.md#api)also has the Node.js format

Are all these fine with you?

**Comment by josdejong** [comment]
@hgupta9 I will have a look tomorrow, sorry for the delay

**Comment by josdejong** [comment]
Thanks. I like the layout like Complex and Unit where the top part explains how to use it and the API placed at the bottom of the page but in the same file. 

A few thoughts:

- I think it's a good idea to have both overview, usage, and API of a for example a data type on a single page. That way you can easily find everything related to say working with matrices or complex numbers in one place. 
- But that means that there is no clear separation between "overview" and "API" docs. I see you've moved the "classes" to a new section "API", but I think I would rather group them together with related functionality, ie. all data types in the section "Data types", everything related to expressions under the section "Expressions", and everything related to core or top level under "Core".
- I'm not sure whether we should put the Unit reference on the Units page or keep it separated.
- I think the eval and parse functions are not part of "Core" (top level) but of "Expressions".

The library consists of the following parts, and I think this structure should be reflected in the docs:
- Core: "math" namespace, configuration, import, extension, serialization, chaining
- Data types: BigNumber, Complex, Fraction, Unit, etc.
- Functions: functions in different categories
- Constants
- Expressions: parsing, evaluation, manipulating parsed expressions

Except for the functionality in Core, each of the individual parts can (or should) be stripped out from the library whilst keeping the left over parts working. For example we could remove everything related to expression parsing from the library, it's no part of the Core, `parse`  and `eval` are no "top level" functions. Or we could remove BigNumber and it's constructor function `bignumber`, this is no top-level functionality.

Here just an idea for grouping the index page of the docs:

____________

## Getting Started

- [Getting Started](getting_started.md)

## Overview

- ~~[Introduction](introduction.md)~~ Remove, move contents to 'Core'
- [Core](#)      NEW. Contains the contents of Introduction plus some extra
  - [Configuration](configuration.md)
  - [Chaining](chaining.md)
  - [Extension](extension.md)
  - [Serialization](serialization.md)
- [Expressions](expressions/index.md)
  - [Parsing and evaluation](expressions/parsing.md)   NEW: add API section for Parser at the bottom
  - [Syntax](expressions/syntax.md)
  - [Expression trees](expressions/expression_trees.md)
  - [Customization](expressions/customization.md)
- [Data Types](datatypes/index.md)
  - [Numbers](datatypes/numbers.md)
  - [BigNumbers](datatypes/bignumbers.md)  NEW: add API section
  - [Fractions](datatypes/fractions.md)  NEW: add API section
  - [Complex Numbers](datatypes/complex_numbers.md) CHANGE: move API section to the bottom
  - [Matrices](datatypes/matrices.md) NEW: add API section
  - [Units](datatypes/units.md) CHANGE: move API section to the bottom
- [Custom bundling](custom_bundling.md)
- [Command Line Interface](command_line_interface.md)

## Examples

- [Examples](http://mathjs.org/examples/index.html)

## Reference

- [Constants](reference/constants.md)
- [Functions (alphabetical)](reference/functions/alphabetical.md)
- [Functions (categorical)](reference/functions/categorical.md)
- [History](../HISTORY.md)
- [Units](reference/units.md)

______________

What do you think?

**Comment by hgupta9** [comment]
Okay, cool with me. I've implemented most of your changes with one exception. Class-wise docs are also available. Can you see this : [Index](https://github.com/hgupta9/mathjs/blob/master/docs/index.md)

And this: [Parser](https://github.com/hgupta9/mathjs/blob/master/docs/expressions/parsing.md#parser)

**Comment by josdejong** [comment]
Looks good, I like it! A few ideas:

- A "Classes" page can be useful. Since this page only lists the classes and links to their page, we can maybe we can put the classes in a table form? With columns Name and Description or something like that? Maybe a few tables, like grouping all data type classes in one table, all Node classes in one table, etc. 
- Right now the "Classes" page not only describes classes but also "top level functions". Shouldn't the right place for describing the top level functions be the "Functions" page?
- For functions we had two pages: alphabetical and categorical. Thinking about it, this may not be that useful. I think it's just enough to keep the categorical list. If you want to find a function by name you can simple search on the page (Ctrl+F).
- Most of the functions that you list under "Top level functions" are just one category of functions but no core functions. I think we can simply take the categorical list of functions and make it complete, it just misses a few functions.
  - The functions `compile`, `eval`, `help`, `parse`, `parser` are no "top level" functions, they are regular functions in the category "expression" (already listed that way)
  - The construction functions are no top level functions but regular functions in the category "construction" (already listed that way)
  - The categorical list of functions misses the following functions: `config`, `import`, `typed`. We should add these to the categorical list under the category "Core".
  - Besides that I think the function list is complete?

**Comment by hgupta9** [comment]
Okay. See if you like it now:

- [Classes](https://github.com/hgupta9/mathjs/blob/master/docs/class_api.md)
- [Functions](https://github.com/hgupta9/mathjs/blob/master/docs/reference/functions.md)
- [Matrix#API](https://github.com/hgupta9/mathjs/blob/master/docs/datatypes/matrices.md#api) (added matrix specific API)

**Comment by josdejong** [comment]
Hm.

- Classes: The page contains all classes, and describing the "math" namespace there is useful I think. The page only looks weird and empty with this list of clickable headers. How about putting the classes in a table with a short description for each?
- Functions 
  - A description for each function sounds good. 
  - Please be aware that the page is auto-generated using the source code of math.js, so in the end we should not manually rewrite this page but update the script that generates the categorical list.
  -  It's good that you try to remove functions from the "Utils" section, but I think the new "Array functions" section should just be merged into "Matrix functions". These functions act on matrices and arrays.
  - The functions `format` and `print` could go in a separate section. How about calling the section "String functions" instead of "Print functions"?
  - I think that's a good idea. We should adjust the doc generator to enforce this order, not that difficult.
- Matrix#API
  - huh? Shouldn't the API list the methods available on `DenseMatrix` and `SparseMatrix` instead of give a list of functions that act on matrices?
  - I'm not really in favor of listing all functions available per data type. I think it gives a lot of noise but isn't really helpful in practice.

I personally think `math.format` is a better name for this function than `math.toString`, but the function should indeed be find-able. Until now I have never had any question in this regard, people seem to be able to find this function without a problem, so I don't think it's a big deal.

**Comment by hgupta9** [comment]
Hmm.
- Classes : Okay, its your project, you know best.
- Functions : Yes, "String functions" is better.
- Matrix : I just listed those functions there because they were specially designed for matrices I think? If they are not "matrix" related then I guess there's no need to list them there. I thought there was no public API for matrix types and the math.* funcs were all, therefore I listed them.

**Comment by josdejong** [comment]
Thanks.

The doc generator works like a charm, generates all docs for all individual functions, and generates the reference pages. It just needs to be updated a bit, I can take care of that. It's nice not having to take care of keeping the docs up to date by hand.

Yes I'm still not sure in what these functions `map`, `forEach`, `filter`, and `sort` belong best. They act on matrices, so maybe the Matrix section makes most sense for now.

**Comment by hgupta9** [comment]
Wohoo! You'll be happy to know that I was able to accelerate the process of generating MD docs using [JsDoc2Md](http://stackoverflow.com/questions/35403789/prototype-functions-not-handled-by-jsdoc-or-jsdoc2md/). Yes, that's my question. I just had to add the @class alias and it generates JsDocs just fine. Perhaps if you or I or someone can go thru your entire codebase adding that keyword into your comments we can generate JsDoc directly! For now I'm using this to generate MD docs that I will manually add into the MD files.

**Comment by josdejong** [comment]
That looks neat :)

**Comment by hgupta9** [comment]
Can I submit a PR of this version? Will you accept it and make it go live (with whatever changes you'd like)?

Changes:

- [Matrix API](https://github.com/hgupta9/mathjs/blob/master/docs/datatypes/matrices.md#api)
- [JS doc generated stuff](https://github.com/hgupta9/mathjs/tree/master/docs/datatypes/api)
   - many of these will be merged into the main page (eg. complex, unit, but NOT matrix classes)
   - or should we keep it here since it can be re-generated at any time automatically and simply link to it from the main page? (ie. from units.md and complex_numbers.md)
    - these definitely look more professional although they are much more verbose and therefore ugly 
- [Class list](https://github.com/hgupta9/mathjs/blob/master/docs/class_api.md) (listing every "public" class I could find)
- [Function list](https://github.com/hgupta9/mathjs/blob/master/docs/reference/functions.md) (with changes you wanted)

**Comment by hgupta9** [comment]
Also, adding just a few links to the bottom of the Matrix file would be very useful. Just for matrices. It would prevent doubts like [this](https://github.com/josdejong/mathjs/issues/580). By few links I mean this list:

#### Matrix functions

- [math.concat(a, b, c, ... [, dim])](functions/concat.md)
- [math.cross(x, y)](functions/cross.md)
- [math.det(x)](functions/det.md)
- [math.diag(X)](functions/diag.md)
- [math.dot(x, y)](functions/dot.md)
- [math.eye(n)](functions/eye.md)
- [math.flatten(x)](functions/flatten.md)
- [math.inv(x)](functions/inv.md)
- [math.ones(m, n, p, ...)](functions/ones.md)
- [math.range(start, end [, step])](functions/range.md)
- [math.resize(x, size [, defaultValue])](functions/resize.md)
- [math.size(x)](functions/size.md)
- [math.squeeze(x)](functions/squeeze.md)
- [math.subset(x, index [, replacement])](functions/subset.md)
- [math.trace(x)](functions/trace.md)
- [math.transpose(x)](functions/transpose.md)
- [math.zeros(m, n, p, ...)](functions/zeros.md)

#### Matrix/Array functions

- [math.filter(x, test)](functions/filter.md)
- [math.forEach(x, callback)](functions/forEach.md)
- [math.map(x, callback)](functions/map.md)
- [math.sort(x)](functions/sort.md)

**Comment by josdejong** [comment]
Yes, but we still aren't there entirely I think. As for the actual tasks:

I will:
- adjust the script that generates the categorical functions as discussed above: add missing functions&sections, order them in a particular order. This page is auto generated so should not be changed by hand.
- remove the alphabetical functions page

You can create a PR with:
- the updated index.md page
- The new class list page
- The pages with classes

What needs work:
- The pages generated by `jsdoc2md` look nice but need some work by hand. We can use this as a start and further on refine things by hand, or we could add the required annotations to the classes and create a script to auto generate these pages.
-  I haven't looked to the class pages in detail, but for example the DenseMatrix page does not describe what arguments the constructor accepts. Not sure if there are more things missing or redundant in the class docs
- The class docs do not describe how you can actually create these classes given a math.js instance, that would be something like `new math.type.DenseMatrix(...)`.

**Comment by hgupta9** [comment]
I'll do that but can I also add these:

- `acre` and `hectare` units that I defined in `Unit.js`
- Matrix API section only linking to the relevant "math.*" matrix functions
- the JS files that I hand annotated to be JSDoc-compatible (matrix, etc)

**Comment by hgupta9** [comment]
Can you check this out? I deleted my repo, forked the latest, diff'd my changes into the docs/libs folders and created a PR.

https://github.com/josdejong/mathjs/pull/585

**Comment by josdejong** [comment]
I've updated the script that generates the categorical function list, moved it to the root of the docs, added docs for the missing core functions, and moved these util functions to the matrix section.

Thanks for your PR, I will check it out tomorrow.

**Comment by hgupta9** [comment]
Thanks for that. I saw the changes you did to make it happen (doc generator). Some things are missing though, specifically:

- The postfix " functions" to every header ("Matrix functions")
- The prefix "math." to every function ("math.concat")
- One line descriptions
- "String" functions category does not exist
- "Array" functions? Where?

You could add them in or tell me how/where to help.

**Comment by josdejong** [comment]
Thanks, good points. All points are fixed now in the develop branch.

As for the Array functions: they are under the Matrix section. These functions act on both Matrices and Arrays, and I think they should be a single category. Best name I think is "Matrix" (see also https://github.com/josdejong/mathjs/issues/556#issuecomment-183669582 5th bullet).

**Comment by josdejong** [comment]
Just thinking about the list of matrix functions that you added at the bottom of [the matrices.md file](https://github.com/josdejong/mathjs/blob/develop/docs/datatypes/matrices.md#api): this list is already available on the functions page, and it's redundant I think. How about only keeping the functions to construct matrices listed there, and just link to [the full matrix functions list](https://github.com/josdejong/mathjs/blob/develop/docs/functions.md#matrix-functions) instead?

**Comment by hgupta9** [comment]
Thank you, that was fast :)

If you don't like the redundant matrix API list, we could link to the full thing but I would prefer to keep the introductory para ("All relevant mathematical functions" yada yada). Your choice actually, you're the expert.

**Comment by hgupta9** [comment]
Just saw the [functions ](https://github.com/josdejong/mathjs/blob/develop/docs/reference/functions.md)page, it looks beautiful! Good work!

**Comment by josdejong** [comment]
Ok I removed the list with matrix functions from the page Matrices. I left the text there (and adjusted it a bit). I also moved the "core" pages into a directory "core", and move the Class API pages from datatypes/api to reference/classes (symmetric with reference/functions). I think the docs are now ready for release :D

**Comment by hgupta9** [comment]
Thats cool. Can't wait to see it on the site. Are there any more classes that need class-wise API?

**Comment by josdejong** [comment]
I think all classes are complete. I will update the website as soon as v3 is available on cdnjs.com (all examples rely on the hosting of the library by cdnjs)

**Comment by hgupta9** [comment]
I like the docs now. The class-wise API will help newcomers too. Thanks for absorbing and refining my improvements. Great work done with the math.js library.
