### ISSUE TITLE
Implementing polynomial.js

### ISSUE THREAD

**Issue by cukejianya** [josdejong/mathjs#557]
I was wondering if there are any plans to integrate @infusion polynomial.js https://github.com/infusion/Polynomial.js/ or sometype of symbolic function solver in the future.

**Comment by josdejong** [comment]
Yes, actually @BigFav and @ericman314 made a start with this some time ago. It has been on the back burner for a while now but we're definitely planning on implementing algebraic solving/differentiation/integration. 

See: https://github.com/josdejong/mathjs/pull/386, https://github.com/josdejong/mathjs/issues/442, https://github.com/josdejong/mathjs/pull/439, ...

**Comment by josdejong** [comment]
I will mark this as a duplicate and close the issue, lets continue any discussion in the other related issues.
