### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#562]
Currently, the .eval() function returns 'Infinity' for the expression of 1/((5-5)).  Is there a way I can use any of the provided MathJS functions (such as .parse(), etc) to somehow be able to find out that the result is division by 0, so that I can display this message to the end-user.

The expression could a even more complicated such as ((5+6)+cos(45)) / (((5-5))*85*8)

**Comment by josdejong** [comment]
You could override division with your own, like:

```js
math.divide(2,0); // Infinity

var originalDivide = math.divide;
math.import({
  divide: function (a, b) {
    if (math.isZero(b)) {
      throw new Error('Divide by zero');
    }
    return originalDivide(a, b);
  }
}, {override: true})

math.divide(2,0); // throws Error "Divide by zero"
```

**Comment by sonnyk22** [comment]
Nice! Let me use this in my code.

**Comment by josdejong** [comment]
Ok great.

**Comment by sonnyk22** [comment]
This worked great!  Thank you!
