### ISSUE TITLE
Fraction lcm edge case should return NaN

### ISSUE THREAD

**Issue by infusion** [josdejong/mathjs#563]
Hi Jos,

in the complex branch, I also improved some minor Fraction.js things. One was, that I dropped the `lcm()` implementation and simply called Fraction.js's own `lcm()`. However, you have one test

```
  2) lcm should find the least common even for edge cases:

      AssertionError: { [Number: NaN] s: 1, n: NaN, d: 1 } deepEqual { [Number: 0] s: 1, n: 0, d: 1 }
      + expected - actual

       {
         "d": 1
      -  "n": NaN
      +  "n": 0
         "s": 1
       }
      
      at Context.<anonymous> (test/function/arithmetic/lcm.test.js:96:12)
```

I think the behavior of my implementation is correct, that the LCM of a NaN remains NaN. What do you think?

**Comment by josdejong** [comment]
> I think the behavior of my implementation is correct, that the LCM of a NaN remains NaN. What do you think?

Yes that makes sense.
