### ISSUE TITLE
mathJS cannot take powers of complex zero.

### ISSUE THREAD

**Issue by HildoBijl** [josdejong/mathjs#564]
Try the following expression.
`
var a = math.complex(0,0);
var b = math.pow(a, 2);
`
The parameter `b` should equal zero as well, right? Well, it equals `NaN`. Although funny enough `var b = math.multiply(a, a);` does work.

**Comment by FSMaxB** [comment]
Here's what causes the bug:

In mathjs, the power of a complex number is calculated as `x^y = exp(log(x)*y)`, but `log(0)` is `-Infinity`, but `multiply(-Infinity, 2)` returns `NaN`.

@josdejong: I can think of two possible solutions:
1. Handle `0+0i` as a special case in `_powComplex`.
2. Make the multiplication of `-Infinity` and any positive real number return `-Infinity`, as well as all the other cases involving multiplications with `Infinity`. (That's what wolfram alpha does). Note that this would still leave `(0+0i)^0` undefined.

**Comment by infusion** [comment]
@HildoBijl,
I'm working on the integration of https://github.com/infusion/Complex.js into math.js. The task is almost done and Complex.js is capable of handling 0^2, so fixing it in the old implementation might be redundant work.

**Comment by josdejong** [comment]
@infusion do you have added unit tests for these cases like `0^2`?

Infinity of re and im parts of complex numbers. Indeed give a lot of edge cases, I don't think it's worth it to put too much effort in there.

**Comment by infusion** [comment]
I have unit tests for these cases in my suite. Should we double check it math.js as well? 

I haven't unit tested the trig functions for Infinity yet. The other functions are now capable of handling Infinity, even if there are still really strange cases when internally `Infinity - Infinity` or `Infinity * 0` must be calculated. The latter occurs in `Complex(Infinity).mul(123)` for example. I handle this case, as both numbers are real, but I suspect that this was the last case and I agree that we shouldn't spend too much effort in here.

**Comment by josdejong** [comment]
> I have unit tests for these cases in my suite. Should we double check it math.js as well?

Ok great. No need to do all unit tests twice I think, though we can leave the extensive unit tests for Complex in math.js as they are, it doesn't do harm.

**Comment by infusion** [comment]
Yep, I wouldn't remove any tests. It helped a lot with the integration, as it showed what cases my test suite didn't handle and it will also further ensure we're on the right track.

**Comment by josdejong** [comment]
This has been fixed in v3.0.0 with the integration of the Complex.js library
