### ISSUE TITLE
Unit valueOf should return a parsed value

### ISSUE THREAD

**Issue by infusion** [josdejong/mathjs#565]
Jos,

for complex values you set the `valueOf` function to `toString`. This makes sense, but the same is also true for units:

```
  /**
   * Returns the string representation of the unit.
   * @return {string}
   */
  Unit.prototype.valueOf = Unit.prototype.toString;
```

Don't you think it would be better to return a parsed value here? For example `Math.cos(new Unit(90, 'deg'));` would work then.

**Comment by josdejong** [comment]
The reason that this is not supported is that it is ambiguous what number `valueOf` should return. Should `new Unit(90, 'deg').valueOf()` return a number in radians or degrees? Should `Unit(2, 'cm').valueOf()` return a number in centimeters or in meters? 

Therefore, there is a method `Unit.toNumber(unitName)` which forces you to provide the unit when converting to a number, and `Unit.valueOf()` returns a string representation of the unit without ambiguities.

**Comment by infusion** [comment]
Okay, I see. But at the end every unit can be translated to a different unit under a certain type. For example angles are common in radians in CS, then this would be the default. For units of length, you could say that everything is broken down to meter, as every further metrical unit is just a multiple, like mill, deci, kilo, ... and also miles or inches, whatever can be seen as a multiple, or a linear transformation. The only thing remaining is that you have to declare a default.

The reason why I'm asking for this is the following. Having an explicit interface like `toNumber(unit)` is good, but I like it when classes can communicate with each other in a natural way. In my case, you call the Complex constructor with a Unit. An explicit statement would require Complex to handle every possible class which gets passed. There are of course cases where these cases must be handled, but if it's possible through the neutral interface of `valueOf()`, why not making use of it.

**Comment by josdejong** [comment]
if we would return a number from `valueOf()`, most logic would indeed be to return the values as SI base units (meter, second, radians, etc).

I think the radians that are useful for Complex.js are a very specific case, and we should not overthink this. In general, when you have some component that needs to work with Units, you will need to pass both unit and value. Converting to a number and passing that throws away crucial information. So in general you will need to write some "glue" code to convert from Unit to some data structure understood by your component and vice versa.

**Comment by infusion** [comment]
Okay, agreed.
