### ISSUE TITLE
feat: Add `.isPrime(n)` to functions checks

### ISSUE THREAD

**Issue by diosney** [josdejong/mathjs#568]

**Comment by diosney** [comment]
For reference you can check how `big-integer` does it:

https://www.npmjs.com/package/big-integer

**Comment by josdejong** [comment]
You mean add a function `math.isPrime(n)` to math.js?

**Comment by diosney** [comment]
Yes, that will be nice.

I use mathjs and so far very happy with it, hopefully one day its gets standarized into ECMAScript (native Math class just sucks, it is very incomplete) :) but I had to use other math library in order to use an efficient algorithm to check primeness, sure, I could have implement my own, but would be nice to have a one-to-all awesome math library, if it is in its scope, of course (i think it is).

**Comment by josdejong** [comment]
ok thanks for the clarification

**Comment by m93a** [comment]
I believe that [`isPrime`](https://mathjs.org/docs/reference/functions/isPrime.html) has been implemented.
