### ISSUE TITLE
PREFIXES.NONE vs. PREFIX_NONE

### ISSUE THREAD

**Issue by ericman314** [josdejong/mathjs#571]
`Unit.js` has two representations for "no prefix" which are slightly different:

```
PREFIX_NONE:
{name: '', value: 1, scientific: true}

PREFIXES.NONE:
'': {name: '', value: 1, scientific: true}
```

When adding a custom unit, using `prefix: PREFIXES.NONE` works, but using `prefix: PREFIX_NONE`  causes a `SyntaxError: Unit "myunit" not found`. This can create confusion when trying to add a custom unit using the malformed `PREFIX_NONE`.

PR #570 removes `PREFIX_NONE` and substitutes its one occurrence with `PREFIXES.NONE`.

**Comment by josdejong** [comment]
Thanks Eric
