### ISSUE TITLE
Quick help on a library

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#573]
Have a quick question to ask you that is not related to MathJS.  I am using the MathJS library in the little calculator application that I am developing.  I am running into a issue that you may be able to help with.

There are several decent Algebra Equation Solvers on the Github which have been implemented using JavaScript, but each (at least for now) is somehow lacking the ability to solve for some or many equation types that exist.  

AlgebraJS: https://github.com/nicolewhite/algebra.js 
Demo website: http://algebra.js.org/ 

and,

Khan Exercises: https://github.com/Khan/khan-exercises 
Sample website: http://www.mathpapa.com/about/ 

Are there any other good JavaScript libraries out there that you may have come across that can solve for the following equation types:

1.	Algebraic equations
2.	Quadratic equations & Quartic equations
3.	Exponential equations
4.	Logarithmic equations
5.	Trigonometric equations

**Comment by josdejong** [comment]
Besides the ones you list there I don't know of other CAS libraries. 

Some time ago we started implementing CAS in math.js, see #411, #439 and more. This has been on the back burner for a while but we will get there.

**Comment by sonnyk22** [comment]
I will pray soon.  Thank you!
