### ISSUE TITLE
Question relating to sqrt(-6)

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#575]
I recently updated my application to use the latest version of the MathJS lib; (originality I was using v2.41).  On the latest version, when executing eval(sqrt(-6)) I get a returned result of NaN where I used to have gotten a result of "2.44948974 i" in the older version which I was important to the app, so that I could use to provide a defined app exception to the end-user.  Has something may have changed?

**Comment by josdejong** [comment]
I guess you're using BigNumbers, which will return NaN for negatieve input of sqrt.

**Comment by sonnyk22** [comment]
Yup; on the same day i changed it from Number to BigNumber setting.  Thank you
