### ISSUE TITLE
Quick question about .format() function

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#576]
To better illustrate my question, lets use this expression: sin((2*3-2*2) deg)
The initial result that the MathJS.eval() function returns is: 0.03489949670250097

Then, I pass the above result into the .format() function:

                var result= 0.03489949670250097;

                result = mathjs.format(result, {
                    notation: 'auto',
                    precision: 12,
                    exponential: {
                        lower: 1e-12,
                        upper: 1000000000000
                    }
                });

The formatted result returned is now 0.0348994967025 which is 13 decimal places; the result I was hoping to get is 0.034899496703.  Using a testing script that I wrote, I have tested nearly 400 different expressions so far and they all came out perfectly rounded and at 12 decimal places, but this one seems to be a unique one.   In the calculator application I am implementing, it is important to keep the notation set to 'auto'.

When you get a free moment, would you provide me with help on this.

**Comment by josdejong** [comment]
From the [docs on format](http://mathjs.org/docs/reference/functions/format.html):

> precision: number A number between 0 and 16 to round the digits of the number. In case of notations 'exponential' and 'auto', precision defines **the total number of significant digits** returned and is undefined by default. In case of notation 'fixed', precision defines the number of significant digits after the decimal point, and is 0 by default.

If you want to round to decimals behind the decimal point, you will have to use notation `fixed`.

**Comment by sonnyk22** [comment]
Applied it; thank you

**Comment by sonnyk22** [comment]
I ran into another small issue.  After setting the notation to 'fixed, when I pass in the expression of nthroot((e ^ -2, e ^ -4) to the .format(), I get a result of 0, but when the notation is 'auto', I get a correct exponential result (3.772675371627809e-48).  Is there another property of the .format() function that I need to set when notation is set to 'fixed'?

**Comment by josdejong** [comment]
I think you can figure this out by reading the docs and some experimenting in you browser console.

**Comment by josdejong** [comment]
Hint: it has something to do with the fundamental difference between fixed notation and scientific notation
