### ISSUE TITLE
matrix clone - shallow and deep copy

### ISSUE THREAD

**Issue by mbana** [josdejong/mathjs#579]
I've been using the library lately. Thanks for making it available.

Could you possibly enhance it matrix to not clone the objects?

I could submit PR, if you want?

**Comment by josdejong** [comment]
Mutating objects is typically error prone, and math.js keeps objects immutable. That can indeed be expensive. What particular case are you dealing with right now?

**Comment by josdejong** [comment]
This has been addressed in v3.0.0.
