### ISSUE TITLE
matrix.diagonal - antidiagonal

### ISSUE THREAD

**Issue by mbana** [josdejong/mathjs#581]
```
var m = [[1,2,3], [4,5,6], [7, 8, 9]];
m.diagonal() -> [1, 5, 9]
```

I am probably missing something. How do I get the antidiagonal of `m`?

**Comment by josdejong** [comment]
There is no function available to reverse the elements of a matrix, you could do something like:

```js
var A = [1, 2, 3];
math.subset(A, math.index(math.range(2, -1, -1)));  // [3, 2, 1]
```

or in the expression parser (less verbose):
```
A = [1, 2, 3]
A[end:-1:1]   # [3, 2, 1]
```

You could write a function `reverse` for this of course and extend math.js with that.
