### ISSUE TITLE
consider adding columns method to matrix

### ISSUE THREAD

**Issue by mbana** [josdejong/mathjs#582]
Not too sure how often people do this, however it seems like such a common operation.
I can see several ways of getting the columns using: a `transpose`, or possibly a `_.zip()` on the rows.
Is there a quicker way?

**Comment by josdejong** [comment]
What do you mean exactly with "columns method"? Do you want to extract a specific column from a matrix or something like that?

**Comment by mbana** [comment]
I am essentially wanting to use the library to extract columns, rows and diags without having to hard-code these values myself. I want to do a one-time operation where I get the rows, cols etc. and keep a reference to them. It's why I raised the issue about the cloning of the items.

**Comment by josdejong** [comment]
math.js offers a method `math.subset` which you can use to extract a subset of a matrix, whether it's a row, column, or otherwise. Isn't that sufficient? The method is quite verbose to use in JS, but works great in the expression parser (like `A[2, :]`).

**Comment by josdejong** [comment]
There are functions `column` and `row` nowadays, I think this issue can be closed.
