### ISSUE TITLE
Using pressure units

### ISSUE THREAD

**Issue by hgupta9** [josdejong/mathjs#583]
Its not clear how certain pressure computations can be done with math.js?

Eg. 1
> **10 kg/cm2 in psi** //  Error : Units do not match

Eg. 2
> **10 mmHg in Pa** // Error: Undefined symbol mmHg

**Comment by ericman314** [comment]
Try `10 N/cm2 in psi` instead. `cm2` can also be replaced by `cm^2` if you like that better.

Math.js doesn't yet have `mmHg` or `torr`, or many other useful pressure units. It would be good to add these. 

We should probably also add an API for adding custom units, as suggested in #554. I might be able to get to this in the coming weeks.

**Comment by hgupta9** [comment]
Can you list down any "useful" pressure units? I'll add them up as I did for acre and stuff.
