### ISSUE TITLE
Prevent redefinition of constants and unit variables

### ISSUE THREAD

**Issue by hgupta9** [josdejong/mathjs#584]
Currently when you type something like this into the `eval()` function or even on the [math.js site](http://mathjs.org/):
> **PI = 10**
> **PI / 2** // output: 5!
> **mm = 2**
> **20 mm** // output: 40!

As you can see, if a user sets a certain constant or unit type, math.js interprets it as a variable, stores the variable in the context and "incorrectly" executes all subsequent math done with that unit type. 

Therefore, I think it would be useful to **prevent redefinition of constants or unit variables by default**. Perhaps there can be an option in the eval function, `allowRedefinition`, which allows users to do that. But in most cases this behavior is *not* useful and tantamount to redefining the meaning of PI. 

To build such functionality would require 2 things:
1. A list of all constants & unit type permutations (`g`, `kg`, `Mg`, `gram`, `kgram`, `Mgram`, etc)
2. Rejecting editing vars with those names (somewhere in the expression execution engine?)

I could help build the first one, of course, since I need this functionality too, but the 2nd point is totally out of my area of expertise since I'm very new to the math.js codebase.

What do you think?

**Comment by josdejong** [comment]
I think we discussed something like this long time ago, and it is a good idea to make overriding system variables configurable. 

Note that it will be very annoying too if you can't override variables of a large system. We have a lot of units, so you will not be able to use all sorts of common variables like `A`, `b`, `B`, `C`, `K`, `l`, `H`, `m`, `s`, `S`, `T`, `W`, just to mention a few. 

I'm not yet sure what would be the right default for this option: allow overriding or not. I tend to think the current behavior (allow overriding) is best as default.

**Comment by josdejong** [comment]
As for the actual implementation: there is no need to create a list of all constants and units: we can simply check whether some variable exists in the `math` namespace and whether it is a valid unit.

**Comment by ericman314** [comment]
Is there a standard way to display a warning when a user overrides a built-in variable?

**Comment by josdejong** [comment]
That's a smart idea. There is no such solution to pass warnings along with a result, we have to think about that. Could also be useful for example to warn for a divide by zero.

**Comment by hgupta9** [comment]
@josdejong 

I would like to build this. Can you elaborate on the code needed? Off the top of my head

    function allowVar(varName){
        if (math[varName] != null && math.ismath[varName].units != null){
               return false;
        }
        return true;
    }

**Comment by hgupta9** [comment]
Ignore my last message. I built it already. Can you integrate this someplace if you think its nice?

	function isVarOK(varName){
		try {
			if (math[varName] == null && math.unit(varName) == null){
			
				// OK
				return true;
			}
		} catch(e) {
			// SyntaxError : unit not found .. meaning OK
			return true;
		}
		
		// not OK
		return false;
	}

**Comment by hgupta9** [comment]
I'm closing this since I have proposed a solution and have no time ATM for a pull request. Cheers.

**Comment by josdejong** [comment]
Thanks for sharing your solution, we will implement it, it's on the to-do list.
