### ISSUE TITLE
How to check the datatype with mathjs? (Help)

### ISSUE THREAD

**Issue by q2apro** [josdejong/mathjs#590]
Could not find it in the docs: http://mathjs.org/docs/datatypes/index.html

Using pure javascript such as: 

    typeof(result)

will give me `number` if number, but an object which could be a complex number.

I want to check if it is a valid number, which can be real or complex. Thanks.

**Comment by josdejong** [comment]
You can use [`math.typeof(x)`](https://github.com/josdejong/mathjs/blob/develop/docs/reference/functions/typeof.md). 

I've added some info and an example about `typeof` on the data types index page.

**Comment by q2apro** [comment]
Thanks for the info. Great work.
