### ISSUE TITLE
math.eval('asec(1)') gives "Undefined symbol asec"

### ISSUE THREAD

**Issue by q2apro** [josdejong/mathjs#591]
Regarding to the docs at http://mathjs.org/docs/reference/functions/asec.html there is the math.asec function. So I guessed that the eval function would also understand them. However, using: 

	math.eval('asec(1)') 

for instance, I get an undefined message.

Functions that I would like to "eval" are: sin(x) cos(x) tan(x) sec(x) csc(x) cot(x) asin(x) acos(x) atan(x) asec(x) acsc(x) acot(x), sinh(x) cosh(x) tanh(x) sech(x) csch(x) coth(x) asinh(x) acosh(x) atanh(x) asech(x) acsch(x) acoth(x), ln(x) log(x) sqrt(x) abs(x) floor(x) ceil(x) u(x)

Problematic are: 

	asec(x) acsc(x) acot(x) asinh(x) acosh(x) atanh(x) ln(x) u(x)

**Comment by josdejong** [comment]
Yes `math.eval('asec(1)')` is the right way, and it just works as far as I can test. When you enter this in the developer console of the website http://mathjs.org, it will return the right answer `0`.

**Comment by josdejong** [comment]
are you using the latest version of math.js?

**Comment by q2apro** [comment]
Version was: 
   * @version 0.26.0
   * @date    2014-08-03

I have updated to the latest: 

   * @version 2.7.0
   * @date    2016-02-03

And it works now.

However, `ln(x)` and `atanh(x)` still do not work. 

This is my small project where I am using those: 

1. Example ln(x): http://www.matheretter.de/formeln/analysis/wertetabelle/?draw=ln(x)&imin=0&imax=5&p=7
2. Example: http://www.matheretter.de/formeln/analysis/wertetabelle/?draw=atanh(x)&imin=0&imax=5&p=7

**Comment by josdejong** [comment]
That looks nice :)

Math.js doesn't have `ln` but uses `log` and `log10`.

as for the atanh: just check out the output for values 0,1,2,3,4,5. You will see that certain inputs result in a complex valued output, and probably the graph doesn't know how to handle that? If you just always want a number as ouptut you can set `math.config({predictable: true})`, then `atanh(2)` will simply return NaN instead of a complex number.

**Comment by q2apro** [comment]
I have tried `log(x)` but I get:

    SyntaxError: Invalid number

You can try it yourself: http://www.matheretter.de/formeln/analysis/wertetabelle/?draw=log%28x%29&imin=0&imax=5&p=7

**Comment by josdejong** [comment]
Did you read my last comment?

**Comment by q2apro** [comment]
Yes: 

    Math.js doesn't have ln but uses log and log10.

So I changed ln(x) to log(x) in hope it would work :)

**Comment by josdejong** [comment]
> as for the atanh: just check out the output for values 0,1,2,3,4,5. You will see that certain inputs result in a complex valued output, and probably the graph doesn't know how to handle that? If you just always want a number as ouptut you can set math.config({predictable: true}), then atanh(2) will simply return NaN instead of a complex number.

and the same holds for `log`.
