### ISSUE TITLE
math.import cannot redefine an import

### ISSUE THREAD

**Issue by ctzurcanu** [josdejong/mathjs#592]
second time it returns the error:
Uncaught Error: Cannot import "\<import\>": already exists

An workaround is not documented. Is it?

**Comment by josdejong** [comment]
The function `math.import` was accidentally not generated into the docs and on the website, sorry for that. this will be fixed within a week with the release of v3. You can view the docs of `math.import` here:

https://github.com/josdejong/mathjs/blob/develop/docs/reference/functions/import.md

Basically, you can provide option `{override: true}` if you want to allow overriding existing functions.
