### ISSUE TITLE
mathjs, bower and grunt-contrib-uglify 

### ISSUE THREAD

**Issue by olimortimer** [josdejong/mathjs#595]
I've downloaded mathjs using bower, and then using grunt-contrib-uglify to uglify it into another JS file, just like I do with all bower components that I use.

However, when I run grunt, it hangs at grunt-contrib-uglify and the CPU usage spikes to 100%+.  As soon as I remove mathjs, it runs fine.

I've tried with 'dist/math.min.js', 'dist/math.js' and also manually downloaded it, and used the 102KB development version, but they all result in the same hanging and 100%+ CPU.

Has anyone else experience this issue whilst using mathjs with grunt-contrib-uglify?

**Comment by josdejong** [comment]
Minification of math.js takes two and a half minute on my computer. I haven't looked into why uglifyjs has so much trouble minifying math.js, maybe we can do something about that. I only have to run the minification once for every release, the slow minification hasn't been an issue for me so far.

**Comment by olimortimer** [comment]
Is that the same for the 102KB version, that's downloaded outside of Grunt?

I've tried with the 1.4MB math.js via Grunt, 400KB math.min.js via Grunt, and the 102KB math.js via manual download.

**Comment by josdejong** [comment]
What do you mean exactly? 

The non minified version of math.js is 1.4MB, minified version is about 100KB.

**Comment by olimortimer** [comment]
![image](https://cloud.githubusercontent.com/assets/1190115/13528261/b7893806-e20c-11e5-8959-89d80888694f.png)

**Comment by olimortimer** [comment]
![image](https://cloud.githubusercontent.com/assets/1190115/13528287/d88a63c2-e20c-11e5-8c1a-896c61071a4c.png)

**Comment by josdejong** [comment]
Ah sorry, the 100KB size refers to the minified *and* gzipped version. Just minified it's about 400KB.

**Comment by olimortimer** [comment]
Ah ok, thanks for the clarification.

I've just added math.min.js (from bower) back into Grunt, and it has been running for 10 minutes at uglifying, but still has't finished - it's basically uglifying 5 files together, which is doesn't have a problem with except when I add mathjs.

This is on an iMac - 2.7 GHz Intel Core i7, 16GB, SSD, so it's a pretty capable machine.

**Comment by josdejong** [comment]
math.min.js is already minified. I don't think it's a good idea to minify it again, that's even heavier...

**Comment by josdejong** [comment]
In short, you can do two things:

- Use the non-minified version and minify it yourself together with your other 5 files.
- Used the minified version and exclude it from minifying again in your Grunt task.

**Comment by olimortimer** [comment]
I've tried using the non-minified version, and it's just the same.  If I look at the debug that grunt outputs, it never seems to write the uglified file.

Without mathjs:
```
Minifying with UglifyJS...
Reading bower_components/jquery-sortable/source/js/jquery-sortable-min.js...OK
Reading assets/scripts/jquery.royalslider.custom.min.js...OK
Reading assets/scripts/project.js...OK
Reading assets/scripts/project-setup.js...OK
OK
Writing assets/scripts/railsimv2-simulation-setup.min.js...OK
File assets/scripts/railsimv2-simulation-setup.min.js created: 49.98 kB → 43.61 kB
```

With mathjs:
```
Minifying with UglifyJS...
Reading bower_components/jquery-sortable/source/js/jquery-sortable-min.js...OK
Reading bower_components/mathjs/dist/math.js...OK
Reading assets/scripts/jquery.royalslider.custom.min.js...OK
Reading assets/scripts/project.js...OK
Reading assets/scripts/project-setup.js...OK
```

...and then it just sits there.

**Comment by josdejong** [comment]
I'm afraid that besides the info I gave I can't help any further.
