### ISSUE TITLE
min does not work correctly in the "eval" form

### ISSUE THREAD

**Issue by maciejjaskowski** [josdejong/mathjs#598]
```
p = {'p': [4,5]}
math.eval("min([1,2], p)", p)
>> 4
```
instead of `[1,2]`

This 
```
math.eval("min([1,2], [4,5])")
```
works correctly.

This does NOT work either:
```
p = {'p': [4,5]}
math.min([1,2], p['p'])
```

but that works:
```
p = {'p': math.matrix([4,5])}
math.min([1,2], p['p'])
```

**Comment by josdejong** [comment]
Thanks, that's indeed odd. Something weird going on when passing one Matrix and one Array instead of two Matrices. Will have a look into it asap.

**Comment by maciejjaskowski** [comment]
There is more weirdoes with 'min', e.g.:
```
math.min(math.matrix([1,2]), math.matrix([4,5])).toArray()
>> [4,5]
```

**Comment by bergstrat** [comment]
Hey guys,

Is this being looked into? 
I am looking to contribute to an OS project for school and this seems like a good place to start.

**Comment by josdejong** [comment]
Thanks for your offer @bergstrat, would be greate if you could pick this up. A simple, the short term solution is to add a check on whether the arguments are scalars and if not throw an Error. A nicer solution is to extend the functions like `min` and `max` with support for this.

**Comment by josdejong** [comment]
I've implemented error messages when passing multiple matrices.

@bergstrat still interested in picking extension of these functions this up?
