### ISSUE TITLE
Using reserved characters in symbols/ variables.

### ISSUE THREAD

**Issue by mohitgp** [josdejong/mathjs#599]
I have expression in my application which get defined by the end user. Also a user could use some application specific syntax while defining the symbols. Fo e.g.

(!costOfMaterialA * @weigtOfMaterialA) + (!costOfMaterialB * @weigtOfMaterialB)

This is one of the simpler expression that we are planning to use. I understand !, @ and a host of other special characters are reserved keywords which cannot be used in a variable (symbol) name.

My question: is there a way to escape these special characters so that they can be used in a symbol?

**Comment by FSMaxB** [comment]
A naive approach: Use a regex to replace it with something that works, like `@ --> ___at___` and "! --> ___excl___`. This is quite ugly but it should work in most cases:
```js
var special_string = "!ab!@!";
// replace all "!" with "___excl___"
special_string = special_string.replace(/\!/g, "___excl___");
// replace all "@" with "___at___"
special_string = special_string.replace(/\@/g, "___at___");
// convert an exclamation mark at the end of a variable back to "!" so that factorial works.
special_string = special_string.replace(/___excl___($|[\W])/g, "!$1");
console.log(special_string); // --> "___excl___ab___excl______at___!"
```
