### ISSUE TITLE
Matrix method for creating subset the ith column / ith row

### ISSUE THREAD

**Issue by ckitt** [josdejong/mathjs#600]
Currently for a matrix A, if i want to select the ith column in A, I have to do the following, which I don't think it's clean and tity, and I am not sure whether I did it in a proper way.

```
var size = A.size();
var numberOfRow = size[0];
var X = math.subset(A, math.index(math.range(0, numberOfRow), i));  // select the ith column
```
What if we can have a new method which allow us to select subset matrix by specifying which column we want.

Thanks in advance!

**Comment by josdejong** [comment]
Getting a matrix column or row in JavaScript is indeed verbose, as we can't override operators in JavaScript. Doing so with the expression parser is very concise:

```
colI = A[:, i]
```

I don't think we need to create a special method for this in math.js. If you repeatedly need this yourself you can easily create a utility function for it. Something along these lines:

```js
// create a function col(A, i) 
// A must be a Matrix or Array, i an integer number
math.import({
  col: function (A, i) {
    var size = math.size(A);
    var rowCount = size[0];
    return math.subset(A, math.index(math.range(0, rowCount), i));
  }
});
```

Which can be used like:

```js
var colI = math.col(A, i)
```

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by ckitt** [comment]
ok, maybe i call this issue resolved... thanks!

**Comment by josdejong** [comment]
Ok thanks for the feedback.
