### ISSUE TITLE
Issues with 0.0254037844386*1000-25

### ISSUE THREAD

**Issue by karenpb** [josdejong/mathjs#606]
I am encountering an issue with the below equation:
0.0254037844386*1000-25
The expected value should be 0.4037844386 but mathJs is returning 0.4037844385999989
Is there any way I can get rid of this round off error?
Thanks ahead for your help.

**Comment by josdejong** [comment]
Yes there are ways to deal with round off errors, see docs:

http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors

**Comment by karenpb** [comment]
Thanks for your response! I will try.
