### ISSUE TITLE
Implicit multiplication

### ISSUE THREAD

**Issue by chmln** [josdejong/mathjs#607]
Is there a way to disable implicit multipliction by space?

![screenshot_2016-03-14_19-16-48](https://cloud.githubusercontent.com/assets/11352152/13859306/3b69773e-ec59-11e5-8843-690c0ab090de.png)

Below the textarea is the expression converted `toTex()`

**Comment by FSMaxB** [comment]
This is quite ugly indeed. @josdejong: I could most likely fix this by introducing a special case for units in `OperatorNode`'s `toTex` and `toString` functions. Should I do that or can you think of a better solution?

**Comment by FSMaxB** [comment]
@chmin You have been asking about disabling implicit multiplication. I assume you only mean the `toTex` and `toString` output. Am I right?

**Comment by chmin** [comment]
Hi,
you probably meant chmln instead of chmin.
Cheers

2016-03-18 12:32 GMT+01:00 Max Bruckner <notifications@github.com>:

**Comment by FSMaxB** [comment]
Oh, sorry @chmin. Yes I meant @chmln.

**Comment by chmln** [comment]
Correct! 

The formula itself gets sent to the server where it is parsed correctly again by mathjs.

There must be a space between x and deg by syntax, and
it'd be lovely if we could avoid it being treated as multiplication to prevent confusion among other users :cake:

**Comment by FSMaxB** [comment]
It's a multiplication internally either way, but it is possible to fix the output that the user sees. I still have to discuss this with Jos de Jong though.

**Comment by josdejong** [comment]
@FSMaxB I think indeed we should store information in the parsed tree about implicit multiplication, like we also need to store parenthesis. 

I think we can extend `OperatorNode` to accept an option fourth argument `implicit`, and have `toString` and `toTex` output a space instead of the operator when `implicit` is true. I think we also need to make it configurable to output an implicit operator or not, maybe a new option `implicit: 'show'|'hide'` that can be passed to `toString` and `toTex`?

**Comment by FSMaxB** [comment]
This can be done but it doesn't solve the problem that units look ugly when a multiplication sign is output by `toTex` or `toString`. I've been implementing some special cases for `OperatorNode`'s `toTex` and `toString` but it erroneously removes the multiplication operator for `b`. Is there an actual Unit called `b`?

I guess the problem I'm facing with automatic unit detection is, that it depends on the current scope. The approach is:
1. Find out if the symbol is in the current scope --> no unit
2. If it is not, call `Unit.isValuelessUnit` to determine if it is a Unit.

What I'm wondering right now: Can I even have a scope available when calling `toTex` or `toString`?

**Comment by josdejong** [comment]
When by default implicit multiplications are displayed as a space by toString and toTex, I think this works fine for practical cases (`45 deg`, `4m/s`, etc). Only when you input `sin(45 * deg)`, the multiplication sign would show up.

We could indeed let the nodes recon with a scope and defined units, but I quite like the independency that's there now.

**Comment by FSMaxB** [comment]
Hm, yeah that's right. One would usually type in units as implicit multiplication anyway.

Ok, I will take a look at implementing a new `implicit` option with `show` and `hide`, where `show` means printing the multiplication and `hide` will print a space. `hide` being the default.

**Comment by josdejong** [comment]
Great, sounds good. Thanks

**Comment by FSMaxB** [comment]
I just found a bug in the `toString` method of the parenthesis node. I will fix it along with the other improvements.

**Comment by josdejong** [comment]
ok great! I wanted to do a release tonight or tomorrow, shall I await your improvements?

**Comment by FSMaxB** [comment]
I'm almost done. Please wait.

**Comment by josdejong** [comment]
This has been adressed in v3.1.0, thanks @FSMaxB
