### ISSUE TITLE
Parsing multiple expressions at once

### ISSUE THREAD

**Issue by priidikvaikla** [josdejong/mathjs#610]
Last parse example on the documentation https://github.com/josdejong/mathjs/blob/master/docs/reference/functions/parse.md doesn't seem to work for me.

```
var nodes = math.parse(['a = 3', 'b = 4', 'a * b']);
nodes[2].compile().eval(); // 12
```

gives me 

```
math.js:32443 Uncaught Error: Undefined symbol a(…)undef @ math.js:32443defs.eval @ VM11604:3(anonymous function) @ VM11603:3InjectedScript._evaluateOn @ (program):878InjectedScript._evaluateAndWrap @ (program):811InjectedScript.evaluate @ (program):667
```

What's the right way to parse multiple expressions?

**Comment by FSMaxB** [comment]
This is the right way to parse multiple expressions at once. Still, the example from the documentation is incorrect.

The problem in this example is, that every one of those three expressions is independent from each other, so `a` and `b` aren't defined in the third expression.

One way to make the example work would be the following:
```
var node = math.parse('a = 3; b = 4; a * b');
var results = node.compile().eval();
results.entries[0]; //12
```

@josdejong: I'm marking this as bug because of the error in the documentation.

**Comment by priidikvaikla** [comment]
Allright, thanks. Another question is that I see that this works
```
var node = math.parse('b = 4; a = 1 + b; a * b');
```
while 
```
var node = math.parse('a = 1 + b; b = 4; a * b');
```
doesn't.

I'm wondering is there a way to parse multiple expressions which doesn't need to be inserted in the right order and then evaluate one of the expressions?

**Comment by FSMaxB** [comment]
Short answer: No. Those expressions don't work like in mathematics but like in most programming languages: The expressions are evaluated sequentially. The right hand side of the expression is evaluated and the result gets assigned to the symbol on the left hand side. This means that in your second example, `b` is undefined in the first expression therefore `1 + b` throws an error.

**Comment by josdejong** [comment]
The order of expressions is indeed important. 

Another option to evaluate multiple expressions:

```js
var nodes = math.parse(['a = 3', 'b = 4', 'a * b']);
var scope = {};
nodes[0].compile().eval(scope); // 3
nodes[1].compile().eval(scope); // 4
nodes[2].compile().eval(scope); // 12
// scope: {a: 3, b: 4}
```

**Comment by priidikvaikla** [comment]
Allright, thanks guys!

**Comment by josdejong** [comment]
You're welcome :)
