### ISSUE TITLE
Question related to bignumbers

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#611]
Is there a possibility to get a 32 decimal places result for the expression of asin(0.5) in radian mode?

Hoping to get: math.eval('asin(0.5)') = 0.52359877559829887307710723054658

The configuration I currently have is:
                 math.config({ number: 'BigNumber', precision: 64 });

This is related to question #605.  The goal that I am trying to achieve is:
Expr: asin(0.5)*6-pi
Goal: 0.52359877559829887307710723054658 * 6 -  3.1415926535897932384626433832795 
Result: 0
Remark: On my end, I can replace pi with 32 decimal places value of 3.1415926535897932384626433832795

Would you provide me with the guidance as to how I can achieve this?

**Comment by sonnyk22** [comment]
Below is a small code snippet that I wrote using bignumber by following the direction at this link (http://mathjs.org/docs/datatypes/bignumbers.html), but unfortunately I am not getting the result of 0 when using bignumber.

    math.config({
        number: 'BigNumber',
        precision: 64
    });

    //var result = math.add(math.bignumber(0.1), math.bignumber(0.2));  //returning 0.3 (correct)

    var pi = math.bignumber(3.1415926535897932384626433832795); //pi value
    var asin = math.bignumber(0.52359877559829887307710723054658);  //asin(0.5)
    var m = math.multiply(asin, math.bignumber(6));  //asin(0.5) * 6
    var d = math.subtract(m, pi);  //asin(0.5) * 6 - 1
    var bnResult = d.toString();   //returning 4e-16 (it should be 0)

    var numResult = math.eval('0.52359877559829887307710723054658 * 6 - 3.1415926535897932384626433832795'); // returning 4.440892098500626e-16

**Comment by sonnyk22** [comment]
I think there is a solution based on #612.

**Comment by josdejong** [comment]
When you configure math.js to use BigNumbers, like `math.config({number: 'BigNumber', precision: 64});`, `pi` has a precision of 64 digits and the result of `asin(0.5)` too.

If you create a BigNumber from a number, the BigNumber will have a precision of about 16 digits. You should create a BigNumber from string:

```js
console.log(math.bignumber(3.1415926535897932384626433832795).toString()); 
    // 3.141592653589793
console.log(math.bignumber('3.1415926535897932384626433832795').toString()) 
    // 3.1415926535897932384626433832795
```
again, there is no need to create pi yourself, you can simply use `math.pi`.
```js
math.config({number: 'BigNumber'});
console.log(math.pi.toString());
    // 3.141592653589793238462643383279502884197169399375105820974944592
```

**Comment by sonnyk22** [comment]
Thank you for getting back to me on this.  It seems that the issue I was experiencing is now working for me in v3.1, and now the BigNumber is working awesome!!!  Please see below:

**Version 2.7.0:**
![calc1](https://cloud.githubusercontent.com/assets/6744710/13924914/a05a0ee6-ef5c-11e5-90a4-8f80d929df50.png)

**Version 3.1.0:**
![calc2](https://cloud.githubusercontent.com/assets/6744710/13924915/a27ec3ba-ef5c-11e5-8eba-a40a1f895de2.png)
