### ISSUE TITLE
PI value of 15 decimal places

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#612]
Currently, the value of PI returning from the library is `3.141592653589793` which is 15 decimal places.

When I evaluate for `asin(0.5)*6`, I get a returning result of `3.1415926535897936` which is 16 decimal places.  Then, when evaluating `asin(0.5)*6-pi`, I get a result of `4.440892098500626e-16 `because of the PI value used is of 15 decimal places.  However, when I hard-code the PI value with its 16 decimal places value, I get the correct result of `0`.  This solution has also worked out fine with solving several of other expressions that we were getting results of negative exponential values.  

Two questions that I have:
1) Is this correct that I did above?
2) Is there a way that I can override the MathJS PI value with a 16 decimal places value instead of me passing-in this value for every PI's in an expression?

![calc1](https://cloud.githubusercontent.com/assets/6744710/13888991/95114534-ed1a-11e5-9022-0517dfb4f036.png)

**Comment by sonnyk22** [comment]
I saw in the library's code that internal Math.PI has been used that returns `3.141592653589793 `which is 15 decimal places.  Based on this, is there a way to use the solution in #562 for my question 2 in this thread?

![calc1](https://cloud.githubusercontent.com/assets/6744710/13893086/120b6576-ed32-11e5-9604-58037eb38ed0.png)

**Comment by josdejong** [comment]
Again: round-off errors.

A number in JavaScript has *almost* 16 digits (`log(2^53)/log(10)` to be precise). You should realize that with floating point numbers, the last few digits are not always reliable, you can have round-off errors there. Take the first 12 or 14 digits of the result and you should be ok.

**Comment by sonnyk22** [comment]
That what I told to our team.  Thank you for getting back to me on this.  Will let them know.

**Comment by sonnyk22** [comment]
Solved in v3.*.  Thank you
