### ISSUE TITLE
ReferenceError: require is not defined (browser)

### ISSUE THREAD

**Issue by jmichae3** [josdejong/mathjs#613]
ReferenceError: require is not defined
I get this when I use require in a browser. apparently the examples are not tested. require is not a valid keyword in javascript - I suspect it is only valid in node.js, but this is not shown in any of the examples I have seen so far.
firefox on vista32

**Comment by jmichae3** [comment]
I also do not know how to instantiate an instance of math.js.
all I know is (true means what in this context?)
//var math=mathjs();

math is not defined how-much-do-i-need-to-make.html:645:3

**Comment by FSMaxB** [comment]
Take a look at this: http://mathjs.org/docs/getting_started.html#browser

The `require.js` instructions are only if you use `require.js`.

**Comment by jmichae3** [comment]
it doesn't say that in any of the examples. people who do not have a full spec will use the errant require.js. what browser does use require()?

**Comment by FSMaxB** [comment]
Oh, you mean those examples.

As far as I know, there is no browser that uses require. [require.js](http://requirejs.org/) is a library that implements a module system and can be used in the browser.

In case of those examples, the `require` built into NodeJS is used. This might actually be the `require` from `require.js` but I'm not sure.

**Comment by josdejong** [comment]
> it doesn't say that in any of the examples.

Many examples indeed assume a little bit of common knowledge about JavaScript in node.js and browser. There is plenty of examples and docs for you to get up and running though: the examples under [./examples/browser](https://github.com/josdejong/mathjs/tree/master/examples/browser), the [getting started](http://mathjs.org/docs/getting_started.html), the [jsbin from the front page](http://jsbin.com/devacu/edit?html,output)? I've now added a comment in the examples explaining that this is loaded using node.js, that may give you another hint. If you have never used node.js, I strongly advice you to spend some evening playing around with it. Any web developer should have at least basic knowledge about node.js, should at least recognize it and know what it is about.

There are a few different environments (node.js, browser) and different module systems (AMD, common.js, globals) in JavaScript land. @FSMaxB I think you're mixing up `require` statements (common.js modules system used by node.js) and the `require.js` library which is an AMD module loader.

**Comment by FSMaxB** [comment]
@josdejong At first I though he was refering to [this example](http://mathjs.org/docs/getting_started.html#requirejs). But thanks for clearing this up.
