### ISSUE TITLE
3.0.0 not working with sequence of additions of floats in a string in math.eval(s,true)

### ISSUE THREAD

**Issue by jmichae3** [josdejong/mathjs#614]
`
		try {

		var hproptaxpct=getidval('ihproptaxpct').replace(/%|pct|percent/g,'');
		hproptaxpct=math.eval(hproptaxpct,true);
		hproptaxpct=hproptaxpct[0];
	} catch(e) {
		console.log(e.message);
	}

//	var hproptaxpct=getidfloatvalnofail(,false,true,',',new Array("%","pct","percent"),false);

	setidinner('oproptaxpct',hproptaxpct.toFixed(4)+'%');

`

this gives the error that .toFixed() as a function doesn't exist.

**Comment by FSMaxB** [comment]
I'm not quite sure what you are trying to do there because I don't know what the functions you are calling are actually doing, can you provide a proper explanation and the actual string that is passed to `math.eval`?

Also, you use a boolean as second parameter to `math.eval` which doesn't make sense. `math.eval` accepts an expression as a string or multiple expressions as an array. And optionally a scope (an object that defines values for given symbols). See http://mathjs.org/docs/reference/functions/eval.html

**Comment by jmichae3** [comment]
it is 2.4897%+1.5408%+2.1595%+3.1722%+0.0625%+0.0125%+0.0125%+0.0099%+5.6259%+1.5000%+0.4355%+0.7560%+.1646%+.5000%+1.1513%+0.5000%

the % symbols get stripped out

**Comment by FSMaxB** [comment]
This should work properly if you remove the second argument to `math.eval` and remove the line `hproptaxpct=hproptaxpct[0];` because in this case, hproptaxpct is not an array. The result of `math.eval` is an array only if multiple expression separated with semicolons have been passed to it.

**Comment by jmichae3** [comment]
here's the log:
TypeError: e.data is undefined
 how-much-do-i-need-to-make.html:650:1
"http://jesusnjim.com/math.js
line:col808:18
message:Unexpected type of argument in function compile (expected: Object, actual: boolean, index: 1)
stack:createError@http://jesusnjim.com/math.js:808:18
compile@http://jesusnjim.com/math.js line 1715 > Function:30:1
calc@http://jesusnjim.com/calculators/finances/how-much-do-i-need-to-make.html:738:27
@http://jesusnjim.com/calculators/finances/how-much-do-i-need-to-make.html:608:1

actual:true
expected[0]:Object
fn:compile" how-much-do-i-need-to-make.html:756:3
{$:160000} atoi64.js:939:4
{$:2500} atoi64.js:939:4

**Comment by josdejong** [comment]
OK so that confirms the cause that Max explained. Max explained how to fix your issue twice, so I suppose you've solved it?

**Comment by jmichae3** [comment]
yes. did that and problem is solved.

**Comment by josdejong** [comment]
ok great to hear
