### ISSUE TITLE
implicit multiplication with brackets around the left hand side creates a FunctionNode

### ISSUE THREAD

**Issue by FSMaxB** [josdejong/mathjs#615]
This might be intentional, as some of the tests in `test/expression/parse.test.js` imply:

```js
assert.equal(parseAndEval('(a)(2+3)', {a: function() {return 42;}}), 42); // function call
```

I still think it's quite strange that `(a)(2+3)` and even `(a+b)(c+d)` get parsed as functions.

Is this behaving the way it should?

**Comment by josdejong** [comment]
Yeah, I've been thinking about this. I've changed this in v3.0.0 when introducing support for objects and expressions like `obj.method(args)`, and I made functions first-class. Basically I changed it such that an expression `lhs (args)` just always invokes the left hand side as a function, no matter what `lhs` is: it can be `a`, `(a)`, `a.toString`, `a["toString"]`, `(condition ? f1 : f2)`, etc. 

I agree that it's weird when you're wanting to type an implicit multiplication. Maybe it's better to only allow function calls after a symbol or accessor, and simply don't allow statements like 
`(condition ? f1 : f2)(42)`. Let me rethink other consequences that this would have.

**Comment by josdejong** [comment]
I can't really come up with many practical cases where you would want to do a function invocation but many more where you want to do an implicit multiplication. I will revert this behavior. I guess most people consider the current behavior a "bug" so no need for a breaking release :D

**Comment by josdejong** [comment]
I've restored the behavior for implicit multiplication in this commit: https://github.com/josdejong/mathjs/commit/c8d41fc5b47a749c429af97501df83540a5e4436
