### ISSUE TITLE
Error with decimal power in scientific notation (1E1.2)

### ISSUE THREAD

**Issue by karenpb** [josdejong/mathjs#618]
I happened to know that mathjs does not support decimal number as a power in scientific notation. Example is **1E1.2**.
Is there any way I can overcome this?
Thanks.

![image](https://cloud.githubusercontent.com/assets/6461338/13921144/df2c0620-ef4c-11e5-8628-abf75f7bbd2a.png)

**Comment by josdejong** [comment]
Sure, you can write `1 * 10^1.2` as that is what an exponential notation means.

**Comment by karenpb** [comment]
Thanks for the quick response. Is there any plan to handle this in the future version to address this?
If not I will take your suggestion to do the conversion.

**Comment by josdejong** [comment]
I doubt whether we should add support for this, I don't think allowing decimal exponents is a common notation for values. It doesn't make a value readable, and I think it's better to consider this an operation rather than a value notation.

**Comment by karenpb** [comment]
Thanks for the input. I will go for the work around

**Comment by josdejong** [comment]
Ok!
