### ISSUE TITLE
BigNumber result for deg mode

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#620]
In the new version of the library, the `BigNumber `works great with the `Trig `functions in the `rad `mode, but in the `deg `mode I am having a little bit of issues.  Lets use `1/sin(60) `in `deg `mode as an expression example.

I wrote the below code to demenstrate the issues I am running into.

![calc2](https://cloud.githubusercontent.com/assets/6744710/13959971/b4ff7efa-f02c-11e5-9164-27f780a9383b.png)

The below code was extracted from a link that you've provided me in the past which I'll need to get your advise on.  The challenges that I am having with are: 

- The result gets converted from `BigNumber `to a `Number` which returns a `16 decimal `places result.
- Sometimes the results are more than 15 digits, thus I get `Cannot implicitly convert a number with >15 significant digits to BigNumber`  error message.

I need your help on these 2 issues.

![calc1](https://cloud.githubusercontent.com/assets/6744710/13959918/6953982e-f02c-11e5-9d9a-857d325f9fa0.png)

In MathJS library:
![calc6](https://cloud.githubusercontent.com/assets/6744710/13959977/bdaadedc-f02c-11e5-96ce-e30c36f91065.png)

Even when I made changes to the code, shown below, I run into the same issue due to the `15 digits` limitation.
![grid1](https://cloud.githubusercontent.com/assets/6744710/13960989/f3b63a4a-f030-11e5-8201-1703cc47fa82.png)

**Comment by josdejong** [comment]
You will simply have to extend the `replacement(x)` function with support for BigNumbers. Right now it only supports numbers. I.e. for numbers the conversion from degrees is:

```
fn(x / 360 * 2 * math.pi)
```

a generic version which works for numbers, BigNumbers, and Fractions would be:

```
fn(math.multiply(math.multiply(math.divide(x, 360), 2), math.pi))
```

or using chaining if you prefer that:
```
fn(math.chain(x).divide(360).multiply(2).multiply(math.pi).valueOf())
```

**Comment by sonnyk22** [comment]
I applied the suggested code below and it worked great! Thank you.

`fn(math.multiply(math.multiply(math.divide(x, 360), 2), math.pi))`

**Comment by josdejong** [comment]
Good to hear, thanks for the feedback
