### ISSUE TITLE
Question related to implicit multiplication

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#621]
The implicit multiplication is working great for any of the nearly 1000 simple/complex test cases I have testes on the library so far.  Today, I tried below expression which I want to ask you about.

Expression: `((43)(60)+(21)(80)+(16)(100))/(43+21+16)`
MathJS: result: `18995.25`
Other Calcs result: `73.25`

Would you think this could be related to the parsing?

`MathJS:`
![calc1](https://cloud.githubusercontent.com/assets/6744710/13962672/6a65c47e-f038-11e5-8460-4a82733434c0.png)

**Google Calc:**
![calc2](https://cloud.githubusercontent.com/assets/6744710/13962680/75e5e586-f038-11e5-9e53-f2752a4ebfbc.png)

**Comment by josdejong** [comment]
Thanks for spotting this bug! I reduced it to `(2)(3)+4` being parsed with the wrong precedence as 
`2 * (3 + 4)` instead of `(2 * 3) + 4`. I've fixed it in the develop branch and will do a bug fix release asap.

**Comment by sonnyk22** [comment]
Thank you!

**Comment by sonnyk22** [comment]
Worked fantastically! Thank you!!
