### ISSUE TITLE
nthRoot(0, -4)

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#623]
I tried my testing script on the library and for expression of `nthRoot(0, -4) `and `nthRoot(0, -2) ` it is giving back `0` as the result.  However, I get error messages shown on TI and other calculators.  Is this correct?

**Comment by josdejong** [comment]
Thanks for reporting, this should return `Infinity`. `pow` works correctly in this regard: `0^(1/-4) = Infinity`.

**Comment by sonnyk22** [comment]
Thank you!!!
