### ISSUE TITLE
Named multipliers for numeric literals

### ISSUE THREAD

**Issue by hgupta9** [josdejong/mathjs#626]
Is it possible to add "thousand", "million", etc, as named multipliers for numeric literals? It would allow clearer definition of large values, eg:

10 million - 2.5 million
> = (10 * 1000000) - (2.5 * 1000000)

1 kg * 2 million
> = 1 kg * (2 * 1000000)

2.5 million grams in kg
> = (2.5 * 1000000) grams in kg

**Comment by josdejong** [comment]
Well, you can define it yourself, like:

```
million = 1e6
1 * 2.5 million
1 kg * 2 million
2.5 million grams in kg
```

**Comment by hgupta9** [comment]
Thats totally brilliant! Thank you!!

**Comment by hgupta9** [comment]
Do you want to add this into the default math.js system as a constant variable? It would really make expressions much more natural.
