### ISSUE TITLE
Functions to check the type of the object

### ISSUE THREAD

**Issue by robinrodricks** [josdejong/mathjs#627]
We need some functions in math.js to check the type of the value. Right now I'm forced to roll my own which would be wierd and buggy. The API should look like :

> **math.isunit** (value:any):boolean
> **math.isnumber** (value:any):boolean
> **math.isbignumber** (value:any):boolean
> **math.iscomplex** (value:any):boolean
> **math.isfraction** (value:any):boolean
> **math.ismatrix** (value:any):boolean

And some more utils to help check validity of input values:

> **math.isvalid** (value:any):boolean .. checks if not `NaN` and if not a NaN Unit, Fraction, BigNumber, etc
> **math.isblank** (value:any):boolean .. returns true if the value is `0` or `NaN`, or is a `0` or NaN Unit, Fraction, BigNumber, etc

Do you guys think its a good idea?

**Comment by josdejong** [comment]
Makes sense to add these util functions. We already have `math.typeof` and some utils like `isNumeric` and `isPositive`.

The implementation is easy:

```js
function isUnit (value) {
  return value && value.isUnit;
}
function isBigNumber (value) {
  return value && value.isBigNumber;
}
// ... etc ...
```

You could also check using `math.typeof`, like `math.typeof(value) === 'Unit'`, but that's a bit less efficient.

`math.isvalid` is interesting but it may be better to name it `isNaN`, and indeed have it work for numbers, complex numbers, bignumbers, etc. I'm not sure about `isBlank`, I think it would be better to only offer primitive checks and let the user decide on what he wants combinations of checks (like isNaN, isZero, isFinite, ...)

Here a proposal for a complete list of type checks:
- EXISTS `math.typeof(x)` returns the type of x
- EXISTS `math.isInteger(x)` is is an integer numeric value
- EXISTS `math.isNegative(x)` x is smaller than zero
- EXISTS `math.isNumeric(x)` x is a number, BigNumber, Fraction, or boolean
- EXISTS `math.isPositive(x)` x is larger than zero
- EXISTS `math.isZero(x)` x is zero
- `math.isNaN(x)`
- `math.isFinite(x)`
- `math.isBoolean(x)`
- `math.isNumber(x)`
- `math.isBigNumber(x)`
- `math.isString(x)`
- `math.isComplex(x)`
- `math.isFraction(x)`
- `math.isUnit(x)`
- `math.isMatrix(x)`
- `math.isArray(x)`
- `math.isCollection(x)`  x is a Matrix or an Array

**Comment by hgupta9** [comment]
Looks great. Can't wait for it.

**Comment by hgupta9** [comment]
@josdejong - Any plans to build these into math.js? Would be very useful.

**Comment by josdejong** [comment]
Yes :)

**Comment by josdejong** [comment]
Would you be interested in contributing these functions?

**Comment by hgupta9** [comment]
I'll have a go. Can you fix these and merge them in? No time to do a full PR right now.

	function isNaN (value) {

	  // Avoid isNaN. Its behaviour is misleading -- http://stackoverflow.com/questions/8965364/comparing-nan-values-for-equality-in-javascript

	  // check if value is NaN
	  if (value !== value || !math.equals(value, value)){
		return true;
	  }
	  
	  // check if any slot in the array is NaN
	  if (value instanceof Array){
		for (var i=0; i<value.length; i++){
		  var item=value[i];
		  if (item !== item || !math.equals(item, item)){
			return true;
		  }
		  return false;
		}
	  }
	  
	  // unknown
	  return false;
	}
	function isNonZero (value) {

	  // check non-zero value
	  if (value == null || value == 0 || math.equals(value, 0)){
		return false;
	  }
	  
	  // check non-zero array
	  if (value instanceof Array){
		for (var i=0; i<value.length; i++){
		  var item=value[i];
		  if (item != null && item != 0 && !math.equals(item, 0)){
			return true;
		  }
		  return false;
		}
	  }
	  
	  // unknown
	  return false;
	}
	function isValid (value) {
	  return !isNaN(value) && !isNonZero(value);
	}
	function isBoolean (value) {
	  return value === true || value === false; // faster than "typeof"
	}
	function isNumber (value) {
	  return value != null && typeof value === "number";
	}
	function isString (value) {
	  return value != null && typeof value === "string";
	}
	function isBigNumber (value) {
	  return value != null && value.isBigNumber;
	}
	function isComplex (value) {
	  return value != null && value.isComplex;
	}
	function isFraction (value) {
	  return value != null && value.isFraction;
	}
	function isUnit (value) {
	  return value != null && value.isUnit;
	}
	function isMatrix (value) {
	  return value != null && value.isMatrix;
	}
	function isArray (value) {
	  return value != null && value instanceof Array;
	}
	function isCollection (value) {
	  return value != null && (value instanceof Array || value.isMatrix);
	}

**Comment by josdejong** [comment]
Thanks. Please note that in JavaScript you have to use `Array.isArray(value)` instead of `value instanceof Array` (one of these infamous JS inconsistencies). 

I understand your arguments for an `isValid` function, but looking at your pseudo code already gives a lot of discussion: I could use a utility function which does a check whether values are not null, not NaN, and finite. But I would not want this function to check whether a value is a non-empty matrix or something, and a value `0` typically is "valid" for me too. But in your use cases you *do* want these checks. I really think it depends a lot on the use case what you want such an `isValid` function to do and not tot do. So I suggest we leave it up to the user to compose it's own `isValid` function from primitive functions like `isNaN`, `isFinite`, etc.

**Comment by stoplion** [comment]
Has `isUnit` made it to MathJS?

**Comment by josdejong** [comment]
Hm, there is an isUnit function but it's a bit hidden under math.type.isUnit.

Makes sense to move these functions to the main math namespace instead

**Comment by josdejong** [comment]
I think all those functions are exposed nowadays, will close this issue
