### ISSUE TITLE
Allow customizing math.format

### ISSUE THREAD

**Issue by hgupta9** [josdejong/mathjs#628]
Some feature requests for `math.format`:

- Add commas to separate large values (10,000,000 instead of 10000000)
- Add natural postfixes where applicable (10 million instead of 10000000)

Firstly, is there an easy way I can post-process the numeric part of the value within `math.format`? Eg. for a value like `25 mm`, I need to post-process just the `25` part. Then I can pass this value through various utils that I already have to add commas, postfixes, etc.

Secondly, if there is no such possibility, can someone help me build it into math.js?

**Comment by josdejong** [comment]
Thanks for your suggestion. 

It's indeed on my to do list to allow customizing `math.format`. There are excellent formatting libraries like http://numeraljs.com/. I think it would be best to allow users to provide there own callback function for formatting individual numbers in matrices, units, complex numbers, etc.

**Comment by hgupta9** [comment]
Yes, I would like the callback too. Its what I tried to ask for in my first post.

**Comment by josdejong** [comment]
I wanted to implement this... but it turns out this feature was already there :D 

I've clarified the docs a bit more and added a example here: 

http://mathjs.org/docs/reference/functions/format.html#examples

**Comment by hgupta9** [comment]
That's very cool. Thanks very much.

**Comment by hgupta9** [comment]
Your docs don't mention a use case like `math.format(value, options, callback)` .. are all 3 usable at once? For example I would like to use fixed notation in options.

**Comment by josdejong** [comment]
That's not possible. The callback is called *instead* of the internal formatting function which accepts these options.

What you can do is call `math.format(value, options)` inside your own callback function if you want:

```js
var options = {
  notation: 'fixed', 
  precision: 2
};
function formatCurrency(value) {
  return '$' + math.format(value, options);
}
math.format([2.1, 3, 0.016], formatCurrency}; // returns '[$2.10, $3.00, $0.02]'
```

**Comment by hgupta9** [comment]
Oh, that's brilliant. Thank you!

**Comment by hgupta9** [comment]
Can you add your last post to the docs of `math.format`? I think its a brilliant idea and totally non obvious.

**Comment by josdejong** [comment]
Sure, done: https://github.com/josdejong/mathjs/commit/2127047948ec9773254d19a31057fd53744a6fa7

**Comment by hgupta9** [comment]
Wow; you are so fast.
