### ISSUE TITLE
Invalid Scientific notation -3E0.5 is returning value

### ISSUE THREAD

**Issue by karenpb** [josdejong/mathjs#629]
In scientific notation, it should throw error if the exponent is decimal number. 
eg. **3E0.5** is throwing Syntax Error
But **-3E0.5** returns **-1.5** as the result.
Is this a bug?

**Comment by karenpb** [comment]
Just tried 3E.5 and it returns 4.0774227426886. Does mathjs interprets as 3*e*0.5 in this case? Thanks.

**Comment by josdejong** [comment]
That's interesting. Some of your expressions are parsed as an implicit multiplication:

```js
math.parse('3E0.5');  // SyntaxError: Unexpected part ".5" (char 4)
math.parse('-3E0.5').toString({implicit: 'show'});   // "-3E0 * .5"
math.parse('3E.5').toString({implicit: 'show'});     // "3 * E * .5"
math.parse('-3E.5').toString({implicit: 'show'});    // "-3 * E * .5"
```

We will fix it, the parser should parse all of these cases as an invalid exponential notation and throw an error.

**Comment by karenpb** [comment]
Thank you!

**Comment by josdejong** [comment]
This has been fixed now in the `develop` branch

**Comment by infusion** [comment]
I would call it undefined behavior. Also JS itself doesn't have the feature of passing decimal exponents. If you've implemented it now, it should be declared a new feature of math.js.

**Comment by josdejong** [comment]
?

The fix is that an error is thrown when you enter a decimal exponent, instead of having it parsed as an implicit multiplication. Decimal exponents are still not supported.

**Comment by infusion** [comment]
Ahh! Okay, sorry, haven't looked into your fix.

**Comment by josdejong** [comment]
oki
