### ISSUE TITLE
Some unit aliases are broken

### ISSUE THREAD

**Issue by frankdugan3** [josdejong/mathjs#631]
I have not exhaustively tried all unit aliases, but several I would like to use appear to be broken:
```
1 year
  1 year
1 years
  Error: Undefined symbol years
1 month
  1 month
1 months
  Error: Undefined symbol months
1 week
  1 week
1 weeks
  Error: Undefined symbol weeks
```

Several definitions are missing from ALIASES in Unit.js:
```
seconds: 'second',
secs: 'second',
minutes: 'minute',
mins: 'minute',
hours: 'hour',
hr: 'hour',
hrs: 'hour',
days: 'day',
```
If these are being deprecated, then the docs should be updated to reflect this: http://mathjs.org/docs/datatypes/units.html#reference

**Comment by josdejong** [comment]
Thanks, these three aliases where simply missing, I've added them.
