### ISSUE TITLE
Problem with escaped backslashes at the end of strings

### ISSUE THREAD

**Issue by ConorOBrien-Foxx** [josdejong/mathjs#632]
In methods like `math.parse` and `math.eval`, when entering the following and the like, an error occurs:

    > "This string has an escaped backslash at the end.\\"
         SyntaxError: End of string " expected (char 53)

This only seems to happen when the escaped backslash occurs at the end of the string.

**Comment by josdejong** [comment]
Thanks for reporting. This has been fixed now in the develop branch
