### ISSUE TITLE
f(x)=sin() (or any other function)

### ISSUE THREAD

**Issue by aleki** [josdejong/mathjs#634]
I apologize in advance for my English.

I had tried compile this expression: `math.parse("f(x)=sin()")` (or just `math.parse("sin()")`) and I had expected an error while compilation, but it compiled successfully.

It is correct?

I mean that sin() must have a params.

I can check it like this: 
![default](https://cloud.githubusercontent.com/assets/4836709/14228532/9ae0b5ce-f91f-11e5-95b6-d88eb5f3afb4.PNG)
~~but I don't know number of arguments for all functions.~~

Thanks.

**Comment by aleki** [comment]
So, I wrote simple hack for this case:
```js
var node = math.parse(expression);
var nodes = node.filter((node) => {
	return node.type == "FunctionNode";
});
for (var i = 0; i < nodes.length; i++) {
	if (math[nodes[i].name].length != nodes[i].args.length) {
		throw new Error();
	}
}
```
but I think that it should be included in the program by default.

**Comment by FSMaxB** [comment]
These kinds of errors aren't catched at compile time, only when you evaluate the expression!

```js
var node = math.parse("sin()");
node.eval();
//TypeError: Too few arguments in function sin (expected: number or Complex or BigNumber or Unit or Array or Matrix, index: 0)
```

**Comment by aleki** [comment]
@FSMaxB So, it is so sad to hear.

**Comment by FSMaxB** [comment]
I thought about how this could be done, but I can't think of a way that would work. As far as I know, the parser doesn't actually know, how many parameters a function expects. Even if it did, there's still the problem that you can redefine any function like this: `sin(x, y) = max(x, y)`, but the redefinition only happens when evaluating --> the number of parameters changes after parsing.

**Comment by josdejong** [comment]
`typed-functions` have a property `signatures` which is a map with all the signatures of the function. You could write a `validate` function which gets the function from the `math` namespace (or from a `scope` or both), and then checks the number of arguments of FunctionNodes against all of the function's signatures.

**Comment by FSMaxB** [comment]
That sounds like it's possible to do this as long as you don't redefine existing functions.

**Comment by josdejong** [comment]
Why not? It should work with redefined function too: as long as the new function is a `typed-function` too you can grab the signatures and validate the parsed FunctionNode.

**Comment by FSMaxB** [comment]
Even if you do things like `sin(a, b) = a + b; sin(1,2)"?

**Comment by josdejong** [comment]
ah, good point. no, it won't resolve functions you've defined yourself. hm, that becomes really tricky. So it's not solvable for *all* function invocations, only to built-in functions.

**Comment by aleki** [comment]
@josdejong Maybe mathjs have some "safe mode"?

**Comment by josdejong** [comment]
Yes we where discussing the options for such a "safe mode" but the best you can do without actually evaluating code is a "half safe mode", which I think is worse because it behaves unpredictable.

**Comment by aleki** [comment]
@josdejong Thanks for your reply! Meanwhile, I will use `node.filter()` and forbid the user to use the dangerous operation.

**Comment by josdejong** [comment]
What dangerous operations? All that happens when you evaluate `sin()` is getting an error message telling you that it expects an argument.

**Comment by aleki** [comment]
@jherdman I must get the error before compilation.

**Comment by josdejong** [comment]
Can you explain why?

**Comment by aleki** [comment]
@josdejong because I compile expression of safe function and render it with three.js

**Comment by josdejong** [comment]
Maybe you can put a try/catch block around the evaluation, and in case of an error simply don't render a point in your graph. There are also cases like `sqrt(x)` which gives a complex number for `x < 0`, you probably also need to handle that somehow (look into the `predictable` option).

**Comment by aleki** [comment]
@josdejong I'll think about it. Btw thanks for `predictable` option, I didn't know about it.

**Comment by josdejong** [comment]
You're welcome :)
