### ISSUE TITLE
Explicitly show multiplier for Implicit multiplication inside a Tri function

### ISSUE THREAD

**Issue by karenpb** [josdejong/mathjs#635]
Hi,

MathJS has the option to show multiplier for implicit multiplication.

eg. 
math.parse('**2cos(pi)**').toString({implicit: 'show'});
Output: "**2*cos(pi)**"

Is it possible to extend this option to the arguments for the function?
For example: math.parse('2cos(**3pi**)').toString({implicit: 'show'});
Output: "2 * cos(**3 pi**)" 
A * is missing between 3 and "pi". Is there a way to add the * ?

Same for all other functions like sin, nthRoot, int and etc.

Thanks.

**Comment by josdejong** [comment]
Yes, it should also output the multiplication character for nested operations, this is a bug. Thanks for bringing this up

**Comment by josdejong** [comment]
This has been fixed now in the `develop` branch

**Comment by karenpb** [comment]
That's great! Thank you for the quick response.
