### ISSUE TITLE
(-8)^(2/3) in BigNumber

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#637]
Is there a possibility for the library to provide the same result for `(-8)^(2/3)` in `BigNumber`(#525)?  The default `config()` in the calculator application I am currently implementing is BigNumber, but I have to revert back to `number`when there is `(^2/3) or similar` in the expressions. The use of `BigNumber`is crucial to my app.  Could this also apply to `nthRoot(-8, 3/2)` as well (#633).

**Comment by josdejong** [comment]
The BigNumber implementation indeed needs to be extended to support these kind of fraction exponents, thanks for the suggestion.

Just curious: what is the calculator application you're working on btw?

**Comment by sonnyk22** [comment]
Thanks for setting this request as a Feature; its an important one for me.  I am currently finishing developing a scientific and a graphing calculators for my client; basically creating a web-based TI calculator.  Got the Sci-Calc done and Graphing-Calc is in beta testing now, but both are on pending approval status right now due to equation solving (solver/solving)/plotting testing, and anything related to (-8)^(2/3/) or nthRoot((-8), (3/2)), or similar. The MathJS library is they key component to my project; thank you!!

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
