### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by saputera** [josdejong/mathjs#639]
Hi,

There is a possible bug here. 

If a = 4, b = 2, then (a)(a) + (b) = 24, while it should be 18. Apparently, (a)(a) + (b) is treated as (a)((a) + (b)).

This is reproducible, refer to the code below:

=========================================================

    var scope = {a:4,b:2};

    var code = math.compile('(a)(a)+(b)');
    var code1 = math.compile('(a)*(a)+(b)');
    var node = math.parse('(a)(a)+(b)');
    var code2 = node.compile();

    var result = code.eval(scope);
    var result1 = code1.eval(scope);
    var result2 = code2.eval(scope);

    console.log(result); //24
    console.log(result1); //18
    console.log(result2); //24
    
    var parser = math.parser();
    parser.eval('f(a,b) = (a)(a)+(b)');
    console.log(parser.eval('f(4,2)')); //24
    parser.eval('f(a,b) = (a)*(a)+(b)');
    console.log(parser.eval('f(4,2)')); //18

**Comment by FSMaxB** [comment]
I can't reproduce this on the current version `3.1.4`. Also not on the current `develop` branch (commit 02f8b13ae0007249a1be5c09d45533b2e96ef731).

**Comment by saputera** [comment]
I just realized I used 3.1.0. 

I tried version 3.1.4, it works just fine!!

Thank you.

**Comment by FSMaxB** [comment]
Good to hear!
