### ISSUE TITLE
ie9 vista x32 3.0.0 error

### ISSUE THREAD

**Issue by jmichae3** [josdejong/mathjs#640]
SCRIPT438: Object doesn't support property or method 'trim' 
math.min.js, line 27 character 7602

**Comment by jmichae3** [comment]
excuse me - math.js 3.1.0

**Comment by FSMaxB** [comment]
When you ask questions please provide more information. We can't help you if we don't know what you are attempting to do. We can't know what `SCRIPT` contains or what is in line 438 of it.

Please test first if the issue still exists on the newest version (3.1.4 currently). If the issue still exists on the newest version, then please provide some code to reproduce the issue.

**Comment by josdejong** [comment]
@jmichae3 is this still an issue?
