### ISSUE TITLE
Precedence of exponential versus implied multiplication

### ISSUE THREAD

**Issue by karenpb** [josdejong/mathjs#641]
When I parse the expression 5^(2^3)(-2) to mathjs in the following way: 

math.parse("5^(2^3)(-2)").toString({implicit: 'show'});

output: 5^((2^3)*(-2))

It is adding parenthesis around (2^3) and (-2). Does that mean in mathjs implied multiplication takes higher precedence than ^ operator?
I am actually expecting the output to be 5^(2^3)*(-2).

Is this a bug?

**Comment by FSMaxB** [comment]
According to the list of [operator precedence](http://mathjs.org/docs/expressions/syntax.html#precedence) it is a bug.

**Comment by josdejong** [comment]
This bug is fixed in v3.2.0
