### ISSUE TITLE
Issues with a negative base power to a decimal exponent or fractional exponent

### ISSUE THREAD

**Issue by karenpb** [josdejong/mathjs#642]
I found that someone already raised the issue regarding a negative number power to a fraction (-8)^(2/3).
I also found that for the expression (-2)^0.4 is throwing error.

In this case, should the result be a real number or complex number? Not sure when the exponent is an decimal, if it should be converted to the simplest form  (0.4 --> 2/5 in this case). If that's the case, it falls to the same category with the issue #637 which will be a feature to be implemented.

Are they the same issue?

**Comment by josdejong** [comment]
Fractions have limitations, they don't support decimal exponents. We could improve the fraction implementation of `pow` to calculate the complex valued result instead of throwing an error, makes sense. This would be configurable with the `predictable` option.

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
