### ISSUE TITLE
Question related to the parse() and toTex() functions

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#643]
When you have a free moment, would you help me with the code snippet below so that the `customLaTeX ` will execute for ` e`?  I may be using incorrect `'e' `property name.  The Chrome debugging break-point is not stopping within the `customLaTeX`.

My goal is to convert the below, and I believe I can achieve this via the` toTex() `function.

`e^(2x)-e^x – 2` to `exp(2x)-exp(x) – 2`
`e^x -10` to `exp(x) -10`

```
var eq='e^x -10';
//var eq='e^(2x)-e^x – 2';

var customFunctions = {
    e: function (n, k) {
        //calculate n choose k
        // (do some stuff)
        return result;
    }
};

var customLaTeX = {
    'e': function (node, options) {
        return '\\exp{' + node.args[0].toTex(options) + '}{' + node.args[1].toTex(options) + '}';
    },
};

math.import(customFunctions);
var expression = math.parse(eq);
var latex = expression.toTex({ handler: customLaTeX });
```

**Comment by FSMaxB** [comment]
The way you use `e`, it isn't parsed as a function but as a symbol! This will create a `SymbolNode` which means that your custom LaTeX function has no chance of being called. If you want `e` to be treated as a function, you need to actually call it with function call syntax like `e(2, 1)`, that should then accept your custom LaTeX function.

**Comment by josdejong** [comment]
You can create custom handler for the operator `pow`, similar to http://mathjs.org/docs/expressions/customization.html#examples-for-option-2.

basically the handler should:

- Check whether a node is an OperatorNode `^` (name `pow`)
- If so, check whether the first argument is a `SymbolNode` with name `e`
- if so, format like `exp(args[1])`, 
- and if not format the regular way

**Comment by sonnyk22** [comment]
Thank you both!  It worked beautifully.
