### ISSUE TITLE
Add a `parser.getAll()` function which returns a list of all variables and functions currently in scope.

### ISSUE THREAD

**Issue by gbmhunter** [josdejong/mathjs#644]
I think a `parser.getAll()` function which returns a list of all variables and functions currently in scope would be useful to developers. We can then display the list to the user, so the user has some feedback/guidance on what variables and functions he/she can currently use.

**Comment by josdejong** [comment]
That makes sense, thanks for your suggestion.

**Comment by gbmhunter** [comment]
I don't know whether it would be best to add two separate functions:
`parser.getAllVariables()`
`parser.getAllFunctions()`
or to just return a single list/array:
`parser.getAll()`
and be able to determine whether it's a variable or function by inspecting a member of each list/array element?

**Comment by josdejong** [comment]
I don't think we should separate functions and variables. You can always filter this yourself if you need to.

I suppose `parser.getAll()` should just return the user defined functions and variables, not built-in functions like `sin`, `sqrt`, `pi`, etc. Like `parser.get(name)` only returns user defined variables too.

**Comment by gbmhunter** [comment]
Yes, maybe it would be worth extended the function name to `parser.getAllCustom()` or something similar, to suggest it is not actually retrieving all functions and variables. But then again, if `parser.get()` only returns user defined objects than it might better to keep it as just `parser.getAll()` to keep it inline with what is currently available.

**Comment by josdejong** [comment]
> But then again, if parser.get() only returns user defined objects than it might better to keep it as just parser.getAll() to keep it inline with what is currently available.

Yes I would let `getAll` only return custom defined variables. If you want to create a list of everything custom defined and built-in, you can do something like: 

```js
var custom = parser.getAll();
var everything = _.assign({}, math, custom); // use lodash assign
var names = Object.keys(everything);


```

**Comment by josdejong** [comment]
I've implemented `Parser.getAll()` in v3.2.0
