### ISSUE TITLE
Missing Documentation For "engineering" notation when using math.format().

### ISSUE THREAD

**Issue by gbmhunter** [josdejong/mathjs#645]
I see the following comment in the [changelog (2016-01-08, version 2.6.0)](http://mathjs.org/history.html#20160108-version-260):

> Implemented new notation engineering in function math.format. Thanks @johnmarinelli.

But when [viewing the docs for math.format()](http://mathjs.org/docs/reference/functions/format.html) I see no mention of it?

**Comment by josdejong** [comment]
You're right, I've added the missing docs in the `develop` branch.

**Comment by gbmhunter** [comment]
Removed any reference to the word "metric prefixes" in this issue, as I just realised this is a separate subject.
