### ISSUE TITLE
Support for metric prefixes?

### ISSUE THREAD

**Issue by gbmhunter** [josdejong/mathjs#646]
In the engineering and physics world, metric prefixes (e.g. u, m, k, M, G) are frequently used instead of the "e-6, e-3, e3, e6, e9" notation to scale variables.

For example, when doing an Ohm's Law calculation (voltage = current * resistance) it would be really nice to be able to enter in:
`10m*1.2k` 
to calculate 10m(Amps)*1.2k(Ohm's).

I realise the form `10k` is currently ambiguous to expression `10*k`, where `k` is a user-defined variable. But this be circumvented by having a mode which forces you to use the multiplication symbol (`*`), and no shorthand `10k` to represent "10 times k".

I believe there are many Javascript libraries/code examples out there already that convert to and from raw values to a string in a metric prefix, so I don't think it would be too hard to implement.

**Comment by josdejong** [comment]
You *can* use metric prefixes, you can enter `5km`, `10 megaohm`, etc.

**Comment by gbmhunter** [comment]
As far as I understand you can only use metric prefixes IF there is a recognised unit after it. This is quite limiting.

I have attached a screenshot of "Math Notepad" vs. "Console Calc", a small desktop app which does allow metric prefixes.

![image](https://cloud.githubusercontent.com/assets/2396869/14557019/36db11c0-034f-11e6-8292-b981928ec5af.png)

**Comment by josdejong** [comment]
Ah yes, you mean using prefixes without units. That would be nice. There is at least one conflict though which I think make it impossible to implement this: `m` is the unit for meter.

you can always define them yourself when not using units anyway:

```
m = 1e-3;
k = 1e3;

10m * 1.2k
    12
```

**Comment by gbmhunter** [comment]
Would it possible to have two different modes, set by the config? I would think metric prefixes, even at the expense of loosing unit capability, would be a great feature.

I like your workaround in the meantime. One issue I can see with defining `m = 1e-3` e.t.c. is that then the following would be valid:

`10+m`

This should really throw an error (usually it's because the user has done a typo and missed the number infront).

**Comment by josdejong** [comment]
I'm not in favor of such a mode. That would make specific variables return something *really* different depending on the mode, which can be really confusing. The config that math.js has so far only alters the type and precision of results, but does not change the result itself, and I think that's a good thing.

**Comment by gbmhunter** [comment]
O.K., fair enough. I guess one could always add metric prefix support with a pre-filter/post-filter (e.g. something which wrapped the input/output of `math.parse()`.
