### ISSUE TITLE
Question related to (-8)^(4/3)

### ISSUE THREAD

**Issue by sonnyk22** [josdejong/mathjs#647]
Because of the left-to-right expression conversion, I am not sure if I am formatting the expression  `(-8)^(4/3)` inaccurately; hope I can get your hope on this.

I am getting a `Domain error` returning from `eval()` function for the expression `(-8)^(4/3)`; TI is returning `16`.   I formatted it to `((-(8))^(4/3))` (left-to-right), and still gotten the same exception message returning.

Other test cases that I've used which are throwing the `Domain error` exception are: (on the MathJS.org site as well)

(-8)^(7/3)
(-2)^(119/3)
(-2)^(220/3)
(-2)^(-220/3)
(-.3)^(-220/3)

Would you think that my left-to-right formatted expression is incorrect?

**Comment by josdejong** [comment]
How can I reproduce your issue? What configuration are you using?

Things seems to work fine:
```js
math.config()
// Object {epsilon: 1e-12, matrix: "Matrix", number: "number", precision: 64, predictable: false}

math.eval('(-8)^(4/3)')
// Complex -8 - 13.856406460551009 i
```

and:

```js
math.config({predictable: true})
// Object {epsilon: 1e-12, matrix: "Matrix", number: "number", precision: 64, predictable: true}

math.eval('(-8)^(4/3)')
// number 16
```
