### ISSUE TITLE
Failure on Chrome Canary

### ISSUE THREAD

**Issue by Lex-2008** [josdejong/mathjs#648]
Steps to reproduce:

1. Create a file like this:
````
<!doctype html><html>
<head><script src="math.js"></script></head>
<body><script>document.write(math.median([1,2,3]))</script></body>
</html>
````
2. Open the file in Chrome Canary or Opera Developer

Pass if you see "2"

Currently you see this error in console: "`Uncaught SyntaxError: Unexpected token |`"

As I understand, the problem is that latest Chrome supports function names. Try this, for example: `asd=function(){return 1};asd.name` in JS console - it prints "asd" in older browsers and empty string in newest ones. This seems to confuse `getName` function, which can return function name like "`number | BigNumber | Unit`" when called from inside the `typed` function (line 1854 of math.js file), and then `_typed` function will try to build a function body like this:
````
var convert1 = refs.categories['convert'][1];
var convert2 = refs.categories['convert'][2];
return function number | BigNumber | Unit(arg0) {
  "use strict";
  var name = 'number | BigNumber | Unit';
  if (test0(arg0)) { // type: number
    if (arguments.length === 1) {
````
which of course fails.

**Comment by josdejong** [comment]
Thanks for reporting Aleksei. I think this is a duplicate of #601, which is fixed in the `develop` branch and should be fixed in the first next release.

**Comment by Lex-2008** [comment]
Yes, looks like this. Thanks a lot!
