### ISSUE TITLE
really slow

### ISSUE THREAD

**Issue by deltreey** [josdejong/mathjs#649]
This library is really slow in my testing:

`math.eval('1')` is over 80 milliseconds to process.

Any ideas how to speed it up?

**Comment by josdejong** [comment]
Evaluating an expression typically takes in the order of a few milliseconds or less, 80 ms is very slow.

How do you do the testing and on what machine and browser?

**Comment by deltreey** [comment]
nodejs, consistently slow on windows 10, 7, and ubuntu server.  Here's a demo

https://github.com/deltreey/mathjs-test

**Comment by FSMaxB** [comment]
I've reproduced this on Mac OS X El Capitan and an up to date Archlinux.

But I've noticed that, if you run the same test twice in a row, only the first time takes that long, the second time is faster.

```
$ npm test

> mathjs-speed-test@0.0.0 test /home/max/mathjs-test
> mocha test.js --slow 0



  mathjs
    ✓ eval("1") (142ms)

  mathjs
    ✓ eval("1") (1ms)

  nodejs
    ✓ eval("1")


  3 passing (161ms)
```
@josdejong: Is there some first time initialization or lazy loading going on?

**Comment by FSMaxB** [comment]
(Sorry about closing and reopening, hit the wrong button)

**Comment by josdejong** [comment]
@deltreey please dive a bit into how to do benchmarking - executing something once in a test framework is far from representative. 

Be careful though with micro benchmarks - today's JavaScript engines are very smart in optimizing code and for example can strip out code which isn't actually used from for loops etc.

Here a very simple example:

```js
var start = Date.now();

var COUNT = 1000;
var res = 0;
for (var i = 0; i < COUNT; i++) {
  // change the expression in every loop to prevent optimizations/caching 
  // and use the result
  res += math.eval(String(i)); 
}

var end = Date.now();
console.log('duration per evaluation (milliseconds):', (end - start) / COUNT);
```

This outputs a duration of `0.163 ms` on my computer

**Comment by josdejong** [comment]
@FSMaxB yes there is definitely initialization going on here, could be in different places, but at least in the JS engine.

**Comment by deltreey** [comment]
I'm not trying to benchmark.  I had no intent of telling anyone about the quality of this software.  What I can tell you is that I put this together because I ran into an issue (processing approx 50 calculations took over 2 seconds, breaking my build).  I tried to find any information on the speed of the library and all I found was that "big numbers are slow" which is not super helpful.  Are there accurate benchmarks somewhere?  Is there a faster alternative to `.eval`?  At this point, I'm borderline on not using the library, and I'd prefer not to go that route.

**Comment by FSMaxB** [comment]
Do you generate a new instance of mathjs every time you evaluate an expression? Like spawning a new nodejs process for every expression you evaluate?

If yes, there's probably no other way to make it faster than writing it in a way that mathjs is only loaded once and then reused.

**Comment by deltreey** [comment]
singleton it? I can do that.

**Comment by deltreey** [comment]
after some testing, I can confirm that this was probably my mistake.  It appears to be with the way js handles string parsing, as a raw eval() is about the same speed, when we take out the cost of initializing the library.  That proxmity of computing speed is a testament to the quality of this library, not the other way around.

**Comment by josdejong** [comment]
Thanks for your feedback!

**Comment by kbiedrzycki** [comment]
@josdejong I am using parser for some more advanced math, and I am wondering is there any way to speed things up. Even with your previous benchmark, it says that calling evaluation 1000 times takes about 163ms (I've tested for 10000 times and it's 10 times more). Can you provide some tips for optimalization?

**Comment by josdejong** [comment]
@kbiedrzycki that strongly depends on what you're doing. 

You will have to do profiling, find the bottleneck. That could lie in parsing your evaluations, or maybe in heavy matrix operations, or other stuff. If you have found a bottleneck, you can do experiments to see whether alternative solutions improve performance. Some general ideas: 
- parse an expression once, evaluate it often.
- cache results
- do heavy lifting in a Web Worker (or child_process)

**Comment by kbiedrzycki** [comment]
@josdejong sure, I understand, the case is quite simple, I am creating "matlab-like" editor which allows user to put some computations and run as a group, for example to code may look similar to this:

```
on_circle = 0
n = 1000
k = 0

for (k = 0; k < n; k++) {
    x = bignumber(random())
    y = bignumber(random())
    r = sqrt(x^2 + y^2)

    if (r <= 1) {
	    on_circle = on_circle +1
    }
}

p = 4 * on_circle / n
```

It calculates the pi number with monte carlo method, for 1000 iterations it takes around 1700ms on i7 machine. I've created little parser which creates JS parsable code, with output:

```
(function() { console.time('editor'); var circle = mathParser.eval('on_circle = 0'); var n = mathParser.eval('n = 1000'); var k = mathParser.eval('k = 0'); for (k = 0; k < n; k++) { mathParser.eval('k = ' + k); var x = mathParser.eval('x = bignumber(random())'); var y = mathParser.eval('y = bignumber(random())'); var r = mathParser.eval('r = sqrt(x^2 + y^2)'); if (r <= 1) { var circle = mathParser.eval('on_circle = on_circle +1'); } } var p = mathParser.eval('p = 4 * on_circle / n'); console.timeEnd('editor'); })();
```

And here I am looking for some suggestions how to make that quite faster, where are some places to improve. I wrote similar function is plain javascript and it takes way much lower time to compute. Each 10 times iterations more takes 10 times time more..

**Comment by FSMaxB** [comment]
If possible you should parse all the expressions only once and then only evaluate the parsed expressions in the loop.

I'm not sure what implications this has for the scope of the variables (like `on_circle`) though.

**Comment by josdejong** [comment]
First, note that BigNumbers are very slow compared to regular numbers. 

And you should indeed replace the `math.eval` with `math.compile` to make things faster.

http://mathjs.org/docs/expressions/parsing.html#compile

You can do things like:
```js
// compile once
var hypot = math.compile('sqrt(x^2 + y^2)')

// eval as often as you like
var r = hypot.eval({x: 3, y: 4})  // 5
```
or define a function:
```js
var hypot = math.eval('hypot(x, y) = sqrt(x^2 + y^2)')

var r = hypot(3, 4)  // 5
```
