### ISSUE TITLE
Correct support of the sin(PI)

### ISSUE THREAD

**Issue by zagovorichev** [josdejong/mathjs#652]
Why no one not support `sin(PI) = 0`
For example: I have equation `y=x*sin(PI)`, I try to check knowledges of somebody, and propose to introduce the variables which satisfy: Enter x: __ y: __. User enter y=0, x = 100, and result is false.

**Comment by zagovorichev** [comment]
for now I use if (result >=-1e-10 && result <= 1e-10), but, as for me, it's a dirty hack. Maybe has sense to create static library, with preloaded results?

**Comment by josdejong** [comment]
Calculations with irrational numbers and trigonometric functions result in round off errors. The relational functions of math.js like `math.equal` reckon with round-off errors. 

See relevant docs:
http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
http://mathjs.org/docs/datatypes/numbers.html#equality
http://mathjs.org/docs/reference/functions/equal.html

**Comment by zagovorichev** [comment]
@josdejong Thanks for response, but it's not work for me

```math.equal(0,132*math.sin(math.pi)) === false```

**Comment by josdejong** [comment]
Ah, yes that's true. We can't compare against zero since the function can't know what "scale" to compare the value against. It's explained in the docs:

http://mathjs.org/docs/datatypes/numbers.html#equality

To work around this you could add for example `10` to both values and compare that:

```js
var offset = 10;
math.equal(0 + offset, 132*math.sin(math.pi) + offset); // true
```

**Comment by zagovorichev** [comment]
Thank you! Now it's clear

**Comment by zagovorichev** [comment]
But it's doesn't work with big numbers
```
var offset = 10;
math.equal(0 + offset, 999999999*math.sin(math.pi) + offset); // false
```

**Comment by josdejong** [comment]
You will have to rewrite this check to allow using bignumbers too. Replacing the operators `+` and `*` with `math.add` and `math.multiply` should do the trick.
