### ISSUE TITLE
Suggestion: Section in website showing other projects that integrates Math.js

### ISSUE THREAD

**Issue by mofosyne** [josdejong/mathjs#654]
Just thought it would be nice if we know who uses it

**Comment by Ixus** [comment]
It would be interesting to see how people are using it.

**Comment by mofosyne** [comment]
Plus hey Jos! Its a way to have a screenshot of the notebook thing you are
making too!

**Comment by josdejong** [comment]
Thanks for the suggestion, we should indeed create a "showcase" section.

**Comment by FSMaxB** [comment]
If I remember it correctly, the Ubuntu Touch calculator App relies on mathjs. This would be interesting to showcase.

**Comment by josdejong** [comment]
Yes, and numerics too:

http://www.numerics.info/
https://chrome.google.com/webstore/detail/numerics-calculator-conve/liglcienpnkhdajdfmnpbgmpjglonipe?utm_source=chrome-ntp-icon
