### ISSUE TITLE
Unicode handling bug in math.parse()

### ISSUE THREAD

**Issue by Lakedaemon** [josdejong/mathjs#656]
in http://mathnotepad.com/, when you type 
imply(isSet(A), subSet(∅, A))
you get this error :
SyntaxError: Syntax error in part "∅, A))" (char 24)

math.parse handles "imply(isSet(A), subSet(emptySet, A))" correctly

**Comment by FSMaxB** [comment]
I'm not sure what @josdejong's official stance on this is, but looking at the code, it seems like mathjs doesn't support arbitrary unicode characters in symbols, only a few select ranges.

The relevant code is in [lib/parse.js#329](https://github.com/josdejong/mathjs/blob/7511d4288de582614bb468885098489751b9de3e/lib/expression/parse.js#L329) which calls [currentIsApha()](https://github.com/josdejong/mathjs/blob/7511d4288de582614bb468885098489751b9de3e/lib/expression/parse.js#L392) to determine if the current character is a valid character for a symbol.

∅ is in the [mathematical operators block](https://www.wikiwand.com/en/Mathematical_operators_and_symbols_in_Unicode#/Mathematical_Operators_block) which seems to be intentionally unsupported by the current code.

@josdejong: Your code assumes that JavaScript engines use UTF-16 internally, is this really a safe assumption for all browser versions that mathjs aims to support?

**Comment by josdejong** [comment]
The parser indeed supports a predefined set of math related unicode characters, (see #265). We can add this symbol too. Are there other related symbols missing too?

@FSMaxB I don't remember the exact details by heart except that I remember that unicode in JavaScript is a mess. UTF-16 is indeed safe as far as I know, but please correct me if I'm wrong.
