### ISSUE TITLE
Cannot calculate the dot product of matrix and vector, or two matrices?

### ISSUE THREAD

**Issue by trashofmasters** [josdejong/mathjs#658]
Using Mathjs v3.2.1, the following code throws an Error (see below) instead of the resulting vector `[1, 3/2, 1/2, 1]`.

```js
const math = require('mathjs');
var matrix = math.matrix([[0, 0, 0, 1], [1, 0, 0, 1/2], [0, 0, 0, 1/2], [0, 0, 0, 1]]);
math.dot(matrix, [1, 1, 1, 1]);
```

The [documentation](http://mathjs.org/docs/reference/functions/dot.html) seems to suggest a `math.Matrix` object can be used, but I'm not completely certain I'm using the library correctly. I think I could use an example of doing this in the way that's intended by the library.

I noticed from the stack trace that there's a `TODO` item in [dot.js](https://github.com/josdejong/mathjs/blob/master/lib/function/matrix/dot.js#L65), so perhaps this particular functionality isn't ready yet?

```
RangeError: Vector expected
    at _dot (/tmp/mathjs-issue/node_modules/mathjs/lib/function/matrix/dot.js:65:57)
    at typed.Matrix, Array (/tmp/mathjs-issue/node_modules/mathjs/lib/function/matrix/dot.js:38:14)
    at Object.dot (eval at _typed (/tmp/mathjs-issue/node_modules/typed-function/typed-function.js:1042:22), <anonymous>:34:16)
    at repl:1:6
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

**Comment by FSMaxB** [comment]
What you're trying to do is mathematically impossible, the dot product is only defined for two vectors/one dimensional matrices. See https://en.wikipedia.org/wiki/Dot_product.

What is it that you're trying to do with this matrix and vector?

**Comment by trashofmasters** [comment]
You are right, I mistook the dot product for the multiplication 😵. 


I think the confusion arouse from the fact that in Mathematica I'd just use the `Dot` function to multiply matrices or vectors to obtain a vector of scalars, or a scalar. From a quick glance at one-sentence description of `mathjs.dot` and its signature, so I was lead to believe it was essentially the same thing as the `Dot` function in the Wolfram Language.

**Comment by trashofmasters** [comment]
You are right, I mistook the dot product for matrix multiplication 😵.

What I needed to do was multiply a `1xN` vector with a `NxN` matrix. I was confused because in Mathematica I'd normally use the `Dot` function to multiply matrices and vectors.

From a quick glance at the documentation for the `mathjs.dot` function I was led to believe it was the same to its namesake from the Wolfram language.

Thanks for the clarification then, I'll stick to to `mathjs.multiply` as it does in fact give me the intended result.

**Comment by FSMaxB** [comment]
Good to hear!
