### ISSUE TITLE
Seed the random generator

### ISSUE THREAD

**Issue by agladysh** [josdejong/mathjs#661]
I let my users to set the random generator seed for the program to get reproducible results (I use chance.js for that). I'm adding an option for user to write math.js expressions, including `random()` function. I would like it to be reproducible as well.

Can I seed the random generator that math.js uses? Alternatively, can I replace `random()` function in the `math.eval()` with my own implementation?

**Comment by FSMaxB** [comment]
See http://mathjs.org/docs/core/extension.html.

Alternatively you could import a scope that contains it.

**Comment by agladysh** [comment]
Thank you! For the record, I ended up doing this:

```
math.import({
  random: function(min, max) {
    return sampler.chance.floating({
      min: min === undefined ? 0 : min,
      max: max === undefined ? 1 : max
    });
  }
}, { override: true })
```
