### ISSUE TITLE
math.create is very performance-heavy

### ISSUE THREAD

**Issue by agladysh** [josdejong/mathjs#662]
In my code, I import a custom `random()` function into math.js object to be used in `math.eval` (see #661 for motivation).

My code calls `math.eval` many times (for handling of embedded expressions in a text-template DSL).

Each time I call `math.eval`, I have to re-initialize my `random()` function, since the random seed might change. So I end up calling `math.import` many times. (I could resolve this via an upvalue, of course, but this approach somehow smells worse to me.)

Originally each time I called `math.import()`, I created a fresh math.js instance by calling `math.create`— so I would have an instance that is guaranteed to be pristine clean.

However, I found out that the `math.create` is too performance-heavy to be called as often as I'd like it to.

Right now it is not such a big problem, as I import the same symbols every time. But if / when the symbols imported will depend on a context, I'll have a problem.

Can `math.create` be radically optimized?

Alternatively, can I reset math object back to pristine state?

**Comment by agladysh** [comment]
Apparently, `math.import` is rather heavy too. Reorganizing my code now to call `math.import` only once and to rely on upvalues... Doh.

**Comment by FSMaxB** [comment]
Performance should be much better if you pass in your symbols and custom functions via a scope (that you have to pass in for every call to `math.eval`. Although I didn't do benchmarks.

This would also leave the library in a clean state.

```js
var scope = {
	a: 4,
	random: function () {
		return -1;
	}
}

math.eval("a", scope); // 4
math.eval("random()", scope); // -1
```

**Comment by FSMaxB** [comment]
But I think using an 'upvalue' (probably a Lua-only term) isn't actually that bad of an idea for the random seed.

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
