### ISSUE TITLE
String concatenation documentation is unclear

### ISSUE THREAD

**Issue by agladysh** [josdejong/mathjs#664]
http://mathjs.org/docs/expressions/syntax.html:

> Strings can be concatenated by adding them.

but in example:

```
parser.eval('a = concat("hello", " world")'); // String, "hello world"
```

**Comment by agladysh** [comment]
When I do `concat("1-001", b)` (b is a variable), I get this error:

> error: TypeError: Array.prototype.concat called on null or undefined

and when I do `"1-001"+b`, I get another error:

> error: Error: Cannot convert "1-001-" to a number

How do I concatenate a string in a math.js expression?

**Comment by agladysh** [comment]
Apparently, the correct way to concatenate strings is `concat("1-001", b)`.

However, I'm not able to — and was not able to get a minimal example so far.

This expression fails in my code with the above error about `prototype.concat`:

```
concat("1-001-",string(_bc_1_001))
```

The variable `_bc_1_001` contains number `1`.

This code seems to work in the demo, so the problem is apparently somewhere else. Any clues?

**Comment by agladysh** [comment]
Here is what I have (in my toy template language):

```
{?_bc_1_001=1|$_t}
{?dump(_bc_1_001)|$_t} --> This prints `number 1`
{?dump(concat("1-001-", string(_bc_1_001)))|$_t} --> This fails
```

`dump` is defined as follows:

```
  dump: function(param) {
    console.log("DUMP", typeof(param), param);
    return JSON.stringify(param);
  },
```

The stack trace I get:

```
index.js:136 expr `dump(concat("1-001-", string(_bc_1_001)))` error: TypeError: Array.prototype.concat called on null or undefined
    at eval (eval at <anonymous> (http://localhost:8080/bundle.js:58168:20), <anonymous>:3:550)
    at Object.defs.eval (eval at <anonymous> (http://localhost:8080/bundle.js:58168:20), <anonymous>:3:717)
    at typed.string, Object (http://localhost:8080/bundle.js:62079:37)
    at Object.compile (eval at _typed (http://localhost:8080/bundle.js:1:0), <anonymous>:26:16)
    at Object.handlers.? (http://localhost:8080/bundle.js:182:29)
    at balanced.replacements.replace (http://localhost:8080/bundle.js:341:42)
    at replaceMatchesInString (http://localhost:8080/bundle.js:8586:19)
    at Object.Balanced.replaceMatchesInBetweenBrackets (http://localhost:8080/bundle.js:8486:11)
    at Object.exports.replacements (http://localhost:8080/bundle.js:8675:19)
    at replace (http://localhost:8080/bundle.js:255:30)
```

**Comment by josdejong** [comment]
What is your variable `b` exactly?

So far `math.concat` expects strings and can't handle for example mixed numbers and strings like `math.concat("hello", 2)`. Would be nice to extend the function for this.

**Comment by agladysh** [comment]
```
concat("1-001-", string(_bc_1_001)
```

It is a string...

**Comment by josdejong** [comment]
? 

and what is the value of `_bc_1_001`?

**Comment by agladysh** [comment]
It is a number 1.

**Comment by josdejong** [comment]
hm, hen I call `math.eval('concat("1-001-", string(1))')` things just work. Do you have the latest version of math.js and can your repeat your problem for example on the website http://mathjs.org?

**Comment by agladysh** [comment]
Yes, I have the latest version (as installed my npm install). As I mentioned above, no, I can not reproduce this in the demo on the website. I can not even reproduce it with a smaller dataset with my own code...

**Comment by agladysh** [comment]
...Anyway, please note that this ticket is about documentation self-contradiction. I worked around this mysterious bug.

**Comment by josdejong** [comment]
I'm not sure whether this "mysterious bug" originates in math.js. I have no idea how to reproduce your error "TypeError: Array.prototype.concat called on null or undefined". When I do the following:

```js
math.concat("str", 1)
```
a clear error is thrown:

```
TypeError: Unexpected type of argument in function concat (expected: string, 
  actual: number, index: 1)
```

Besides that, the documentation "Strings can be concatenated by adding them." is clear and correct. It would be nice when `concat` would also support concatenation of mixed strings and numbers into a string though.

**Comment by agladysh** [comment]
> I'm not sure whether this "mysterious bug" originates in math.js. I have no idea how to reproduce your error "TypeError: Array.prototype.concat called on null or undefined".  [...]

Indeed. I noted that I (obviously) get similar error when I call `Array.prototype.concat.call(null, something)` manually. But that, of course does not mean anything.

As for the documentation: I am not sure then, what "adding" means in this context. Example in the documentation lists "concat()" function call, not addition operator for concatenation. Furthermore, this does not work in the demo:

```
"a"+"b"
Error: Cannot convert "a" to a number
```

Am I missing something?

**Comment by josdejong** [comment]
You're right about the docs being wrong/unclear, I think this was a left over from long time ago when `"a"+"b"` would concatenate the strings like JavaScript does too. 

I've rewritten the relevant section in the docs (https://github.com/josdejong/mathjs/commit/6f1094a3099ca7fa58c162ecb62beed0589efb75):

> Strings are enclosed by double quotes ". **Strings can be concatenated using the
function `concat` (not by adding them using `+` like in JavaScript)**. Parts of
a string can be retrieved or replaced by using indexes. Strings can be converted
to a number using function `number`, and numbers can be converted to a string
using function `string`.

Does that make more sense?
