### ISSUE TITLE
Functions to return metadata for units

### ISSUE THREAD

**Issue by robinrodricks** [josdejong/mathjs#666]
I am requesting for three functions to get the unit type and multiplier separately. I know about `formatUnits()` but that works a little bit differently:

**formatUnits()**

``` javascript
math.unit('1 kg').formatUnits()  // returns "kg"
```

**unitType()**

``` javascript
math.unit('1 kg').unitType() // returns "gram"
// code is:
 unit.units[0].unit.name
```

**unitMultiplier()**

``` javascript
math.unit('1 kg').unitMultiplier() // returns "kilo"
// code is:
unit.units[0].prefix.name
```

**unitBase()**

``` javascript
math.unit('1 kg').unitBase() // returns "MASS"
// code is:
unit.units[0].unit.base.key
```

**Comment by josdejong** [comment]
The function `formatUnits()` wasn't meant as a public function, I will refactor it (see #667).

You can use `Unit.toJSON` to get the value and unit separately, or simply call `Unit.toString()` and split the string at the fist space.

I understand that you would also like to split the prefix and unit from each other? Like split `cm` in `c` (centi) and `m` (meter)? You can indeed read them from `unit.units`. But what's exactly your use case?

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
