### ISSUE TITLE
denseMatrix.resize(size, [defaultValue], [copy])  Not working as expected.

### ISSUE THREAD

**Issue by husenxce** [josdejong/mathjs#668]
var scope = {u: this.MathJS.matrix([u],'dense'), X: X};
       scope.u = scope.u.resize([100,2],0,true);
       console.log(scope.u);

The 'true' flag does not create the resized copy of the matrix instead it fills the rest of the matrix with 0s.

![issue](https://cloud.githubusercontent.com/assets/4683089/15456320/6ce8ea78-203a-11e6-9c89-208644461443.png)

**Comment by josdejong** [comment]
The third argument `copy` determines whether the matrix itself will be resized, or that a clone of the matrix will be resized and returned.

```js
var A = math.matrix([1,2,3], 'dense')
console.log(A.toString())  // "[1, 2, 3]"

// with copy == true, the original matrix is left untouched  
// and a clone of the matrix is resized and returned
var B = A.resize([5], 0, true)
console.log(B === A)       // false
console.log(A.toString())  // "[1, 2, 3]"
console.log(B.toString())  // "[1, 2, 3, 0, 0]"

// with copy == false, the matrix itself is resized
var C = A.resize([8], 0)
console.log(C === A)       // true
console.log(A.toString())  // "[1, 2, 3, 0, 0, 0, 0, 0]"
```
