### ISSUE TITLE
Boolean operators not working

### ISSUE THREAD

**Issue by ellis** [josdejong/mathjs#669]
The boolean operators currently aren't working.  For example, at <http://mathjs.org/index.html>, the following fails:

```
true || false
    SyntaxError: Value expected (char 7)

true && true
    SyntaxError: Value expected (char 7)
```

I assume they should work?  Bitwise operators are working fine.

**Comment by josdejong** [comment]
The expression parser has logical operators `and`, `or`, `not`, `xor`.

See docs: http://mathjs.org/docs/expressions/syntax.html#operators

**Comment by ellis** [comment]
Thanks
