### ISSUE TITLE
why the data-cell must be `[A-Z]+\d+` ? 

### ISSUE THREAD

**Issue by ystyle** [josdejong/mathjs#671]
why the data-cell must be `[A-Z]+\d+` ? 

how to confgure like `taxMny1`  reg: (`[A-Za-z]+\d+` or `[A-Za-z]+\d+[A-Za-z]+`)

**Comment by josdejong** [comment]
I'm not sure what you're talking about, can you elaborate?

**Comment by ystyle** [comment]
@josdejong i found `data-cell` attr value only work such as `A1` `A2` `K3` `TEST1` , but no work like `money1` `tableName1_price`

**Comment by josdejong** [comment]
I really have no clue what you're talking about. Is this a question related to math.js?

**Comment by ystyle** [comment]
@josdejong I'm so sorry, I made the wrong place.

**Comment by josdejong** [comment]
Ah that explains it :)
