### ISSUE TITLE
how to get eigenvalue and vector of the matrix

### ISSUE THREAD

**Issue by smartliukun** [josdejong/mathjs#672]
Hi,guys:
    the mathjs lib is wonderful.I very like it .Thanks the authors and contributors.
    I use it in my application,but the lib has no function or api to calculate the eigenvalue and eigenvector of matrix.Anybody knows how to get it?
    Your prompt reply will be much appreciated.

**Comment by josdejong** [comment]
Calculating eigenvalues should definitely be supported by math.js, I'm sorry that this is not yet the case.

The following example shows how you can import the `eig` function from [numeric.js](http://www.numericjs.com/) and use it in math.js:

https://github.com/josdejong/mathjs/blob/master/examples/import.js#L59-L73

You can do the same with other missing functions: import them from some other library.

**Comment by smartliukun** [comment]
thanks ,the guide will be useful.
