### ISSUE TITLE
math.round(). Not rounding accurately with very small numbers.

### ISSUE THREAD

**Issue by DastardlyMut** [josdejong/mathjs#677]
Hello

I have been needing to round very small numbers to specific decimal points. The math.round() function works for all examples except the exponentially small numbers. i.e,  6.123233995736766e-17 rounds to 0, where it should be rounded to 6.1232e-17

I'm not sure if this is the expected behaviour of the math.round() function, but thought I'd put it here as an issue as it was not the behaviour I expected.

Thanks!

**Comment by josdejong** [comment]
The function `math.round` rounds to a number of digits behind the decimal comma (when you write the value out without exponential notation), not to a specific number of significant digits. There was a PR for a function `sigFig` but that hasn't been merged so far (see #242).

To do what you want, you could do something like:

```js
function sigFig (value, precision) {
  return math.number(math.format(value, {precision: precision || 0}));
}

sigFig(6.123233995736766e-17, 5); // 6.1232e-17
```

**Comment by DastardlyMut** [comment]
ah, I see. I have tried to apply this to a multidimensional array and it seems to round differently for normal numbers. Here is the array and my code.

` var array = [ [ 0.8660254037844387, 0.49999999999999994, 0 ],
  [ 0.8660254037844387, -0.49999999999999994, 0 ],
  [ 1, 0, 0 ],
  [ -0.4999999999999998, 0.8660254037844387, 0 ],
  [ -0.4999999999999998, -0.8660254037844388, 0 ],
  [ 6.123233995736766e-17, 1, 0 ],
  [ 6.123233995736766e-17, -1, 0 ],
  [ 0.5000000000000001, 0.5, 0.7071067811865475 ],
  [ 0.5000000000000001, -0.5, 0.7071067811865475 ],
  [ -0.5, 0.5000000000000001, 0.7071067811865475 ],
  [ -0.5, -0.5000000000000001, 0.7071067811865475 ] ] `

function
` vertices = math.map(vertices, function(value){
		return sigFig(value,5);
	}) ` 

output 

` [ [ 0.86603, 0.5, 0 ],
  [ 0.86603, -0.5, 0 ],
  [ 1, 0, 0 ],
  [ -0.5, 0.86603, 0 ],
  [ -0.5, -0.86603, 0 ],
  [ 6.1232e-17, 1, 0 ],
  [ 6.1232e-17, -1, 0 ],
  [ 0.5, 0.5, 0.70711 ],
  [ 0.5, -0.5, 0.70711 ],
  [ -0.5, 0.5, 0.70711 ],
  [ -0.5, -0.5, 0.70711 ] ] `

expected output 

` [ [ 0.866, 0.5, 0 ],
  [ 0.866, -0.5, 0 ],
  [ 1, 0, 0 ],
  [ -0.5, 0.866, 0 ],
  [ -0.5, -0.866, 0 ],
  [ 6.1232e-17, 1, 0 ],
  [ 6.1232e-17, -1, 0 ],
  [ 0.5, 0.5, 0.7071 ],
  [ 0.5, -0.5, 0.7071 ],
  [ -0.5, 0.5, 0.7071 ],
  [ -0.5, -0.5, 0.7071 ] ] `

Is there a way to alternate depending on what sort of number it is?

**Comment by josdejong** [comment]
From a JavaScript point of view all values are of the same type. If specific values, rows, or columns have to be handled differently you will have to write a function to handle your matrix specifically.

**Comment by DastardlyMut** [comment]
Alrighty, thanks for the help!

**Comment by josdejong** [comment]
you're welcome!
