### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Nekomajin42** [josdejong/mathjs#684]
Hi guys!

I am working on a web-based project using math.js. I'd like do some syntax highlighting on the expressions typed by the user. Basically I want to find variable names, numbers, strings and boolean values and apply different styling. I know the markup part, I only need a way to filter the expression.

I know that I can use regexp, but it is messy. I tried to work with the expression tree and node types, but it seems it is not entirely suitable for that. Or is it? Am I missing something? Is there any other built-in solution to help to reach my goal?

**Comment by josdejong** [comment]
I think parsing the expression in a tree will work very nicely: this tree breaks down the expression in all its parts (operators, constants, symbols, etc). You can look into the `.toString` and `.toTex` implementations that all nodes have, and create a new one for your editor named `.toHTML` or something like that. For example for a `SymbolNode`, your `.toHTML` method will probably return markup like `<span class="highlight-symbol">mySymbol</span>`. 

If you don't want to extend the Node prototypes you can also use the method `traverse` to walk through the whole tree, check the type of the node, and depending on the type append build up your markup code.

**Comment by Nekomajin42** [comment]
I've tried what you've suggested, but I have a few problems with SymbolNodes.

1. Why are `true` and `false` are symbols? The `typeof` functions tells me they are boolean values, which is correct. So, shouldn't they be ConstantNodes with valuetype "boolean"?

2.  Since both variable names and functions names are SymbolNodes too, it seems I can't tell the difference between a built-in name and a user-defined name.

3. In complex numbers, "i" is also a SymbolNode. I understand why, but for me, it should be part of the number, like the exponent in flooting point numbers.

Can you help me with these problems?

**Comment by josdejong** [comment]
1. In math.js, constants like `true`, `false`, `Infinity`, etc. do not have a special status, they are treated as regular variables, and evaluated via their definitions in the `math` namespace (`math.true` and `math.false`). If you need to differentiate these you will have to keep a list with these constants yourself and act accordingly.
2. The expression parser doesn't know what type a variable is (function, number, string, etc) until it evaluates it. If you want to give functions and variables a different color, you can check the type of a symbol against it's definition in `math` and the scope you've provided to the parser.
3. When you enter something like `2 + 3i`, it is evaluated as `2 + 3 * i` and indeed `i` is again a regular symbol. I suppose you want to colorize the `3i` part in some specific way? If so, you will have to traverse the node tree and find all OperatorNodes which are an implicit multiplication with a ConstantNode containing a number as first argument, and a SymbolNode `i` as second argument. The expression tree is flexible enough to figure out these sort of things, though it will require some work.

**Comment by Nekomajin42** [comment]
Thanks for the detailed answer.

However, after some search and test I will stick to the regexp solution. I think I can make it work pretty easily, after all. Thank you for your time.

**Comment by josdejong** [comment]
Ok!
