### ISSUE TITLE
parser().getAll() retrieves only variables

### ISSUE THREAD

**Issue by mazing** [josdejong/mathjs#685]
In the `parser`, we have `getAll()` (http://mathjs.org/docs/expressions/parsing.html#parser), but it prints only the variables.

What about having a method for retrieving functions or retrieving both variables and functions in `getAll()`?

**Comment by josdejong** [comment]
If you want to merge the built-in functions and constants with de variables you defined yourself, you can do something like `Object.assign({}, math, parser.getAll())` in modern browsers, or `_.assign({}, math, parser.getAll())` using lodash/underscore.

**Comment by mazing** [comment]
I meant that if I define a function in the parser with `parser.eval('f(x) = x^2')` it is not represented when I write `parser.getAll()`

**Comment by josdejong** [comment]
Ok. How can I reproduce your issue? Things seems to work as expected:

```js
    var parser = math.parser()
    parser.eval('foo = 42')
    parser.eval('f(x) = x^2')
    
    var all = parser.getAll()
    document.write('scope: ' + Object.keys(all).join(', ')) 
    // displays "scope: foo, f"
```

try it here: http://jsbin.com/fogolineji/edit?html,output

**Comment by mazing** [comment]
Seems to work using your approach. I just did this http://jsbin.com/yapidimifa/1/edit?html,output and realized that the function was not shown

**Comment by josdejong** [comment]
JavaScript functions cannot be represented in JSON, `JSON.stringify` simply ignores functions. To inspect these sort of things I normally use `console.log(...)`, which gives detailed information about the contents of an object or array or anything.
