### ISSUE TITLE
Generating heirarchical scope from a database

### ISSUE THREAD

**Issue by mark-lester** [josdejong/mathjs#686]
I have a self referencing hierarchical data structure in my sequelize ORM.
I want to be able to go 
`A.B.C `
where C is a child of B, which is a child of A, which is an orphan in my tree.
I traverse the expression tree before calling eval, and fill in a scope 
`{A:{B:{C:"the value of C"}}`
It's working but my head hurts already, so if there is some cool stuff pray tell.

**Comment by josdejong** [comment]
I'm not sure what you're trying to do and what your question is, can you elaborate?

**Comment by mark-lester** [comment]
I have a tree, it's stored in a database
It has four fields
```
id
name
value
parent

```
I want 
`A.B.C`
to be evaluated as the value field of the row that it is the child of B (parent = B.id) and B is the child of A.

**Comment by josdejong** [comment]
Still doesn't ring a bell. How is this related to mathjs?

**Comment by mark-lester** [comment]
I want to evaluate an expression, such as A + 1. so I can assign B to A+1. So I need to fill in the scope, so I need to scan the expression first to determine what variables are refereed to, in this case A, and go fetch it from my DB and fill that in in my scope object before calling eval.
Now I want to be able to go A.B.C, or even A.B.C. + D.E.F. 
All this data is in a DB, so I've got a load of asynch  going on, fetching the thing named A, then the thing named B that is a child of A, then the thing named C which is a child of B.
I have something, but I just thought I'd ask.

**Comment by mark-lester** [comment]
edit: assign X+1 to Y I guess that should read. But it's A.B.C I want to deal with. I cant load the entire name space, it's a database.

**Comment by mark-lester** [comment]
I have this for a.b.c.d from the parser

`{"object":{"object":{"object":{"name":"a"},"index":{"dimensions":[{"value":"b","valueType":"string"}],"dotNotation":true}},"index":{"dimensions":[{"value":"c","valueType":"string"}],"dotNotation":true}},"index":{"dimensions":[{"value":"d","valueType":"string"}],"dotNotation":true}}
`
I need to traverse that to produce a scope
```
{
a:{b:{c:{d:'value of d'}}}
}
```
Which I can then pass to eval.
It's fiddly in javascript as I cant pass back a reference. In perl for instance I could tie my hash so was wondering how we do that, or other approaches using javascript.

**Comment by mark-lester** [comment]
Jos, I will dump my work-in-progress code here just FYI as it may help you understand what I am doing.
I am good, so this is just so you may have some closure. Thanks a bundle for putting this stuff out, and for at least having a look at my question, but I am good, just close this off if you dont see any point in this.

```
ThreeTC.prototype.fetchElement =function (ContractId,name,parent){
	if (name === '-')
		return {id:null};

	return this.sequelize.models.Element.findAll({
		where:{
			ContractId:ContractId,
			name:name,
			parent:parent
		}
	})
	.then(function(elements){
		if (!elements)
			return undefined;
		return elements[0];
	});

}

ThreeTC.prototype.getObject=function(ContractId,object,scope,context){
	if (object.object){
		var os;
		return getObject(ContractId,object.object,scope,context)
		.then(function(o){
			os=o;
			return this.fetchElement(ContractId,object.index.dimensions[0].value,o.context)
		})
		.then(function(element){
			var value=element.value;
			if (element.type === 'block')
				value={};
			
			if (!element.parent){
				scope[element.name]=value;
			}
			
			os.value[object.index.dimensions[0].value]=value;

			return Promise.resolve({value:value,context:element.id});
		});
	}

	if (object.name){
		return fetchElement(ContractId,object.name,context)
		.then(function(element){
			var value=element.value;
			if (element.type === 'block')
				value={};
			
			if (!element.parent)
				scope[object.name]=value;
			return Promise.resolve({value:value,context:element.id});
		})
	}
}


ThreeTC.prototype.Scope=function(ContractId,expresion,scope,context){
	scope=scope||{};
	var job=Promise.resolve();
	if (e.object)
		job=this.getObject(ContractId,e,scope,context)

	_.each(e.args,function(arg){
		job=job.then(function(){
			return this.Scope(arg,scope,context);
		});
	});

	return job.then(function(){
		return scope;
	});
}

ThreeTC.prototype.evaluateOperand=function(operand,proposal){
	var expr=math.parse(operand);
	var scope={};
	return this.Scope(proposal.ContractId,expr,scope,proposal.ElementId)
	.then(function(scope){
		var complete=true;
		// only set value if scope is fulfilled
		_.each(scope,function(val,name){
			if (val === undefined)
				complete=false;
			scope[name]=val.value;
		});
		var result=undefined;
		try{
			result= complete ? expr.eval(scope) : undefined;
		}catch(err){
console.log("ERROR EVALUATING ["+operand+"] ERROR="+err);
		}
		return result;
	});
}

```

**Comment by josdejong** [comment]
Ah, now I get it. So you have some variables which values you have to fetch asynchronously from a database. There is indeed no easy solution for this. Any solution will be something along the lines of your current solution: first resolve all (nested) variables that you find in the parsed expression, then evaluate the expression.

**Comment by josdejong** [comment]
thanks for sharing your solution btw!

**Comment by mark-lester** [comment]
hey, thanks. i am getting some rather better code and we're in biz. but it's not reusable. thanks for getting me.

**Comment by josdejong** [comment]
You're welcome!

**Comment by mark-lester** [comment]
Here is my code which at least runs, though there's plenty of duplication still. It supports _ as a root context, I will prob need special chars for the parent context and previous sibling block.
 
`ThreeTC.prototype.getValue=function (ElementId,name){
	var element;
	return this.sequelize.models.Proposal.findAll({
		where:{
			ElementId:ElementId
		}
	})
	.then(function(proposedValues){
		if (!proposedValues || proposedValues.length != 1) // we have an unresolved proposal conflict, so dont cascade til its resolved
			return {ElementId:ElementId,value:null};

		// we may/will want to do some checking here on votes and stuff
		return proposedValues[0];
	});
}

ThreeTC.prototype.fetchElement =function (ContractId,name,context){
	var self=this;
	var element=undefined;

	if (name === '_')
		return Promise.resolve({ContractId:ContractId,id:null,name:name,dataType:'block'});

	return this.sequelize.models.Element.findById(context)
	.then(function(element){
		var parentElementId=null;
		if (element)
			parentElementId=element.parentElementId;
console.log("GETTING PARENT "+parentElementId);
		return self.sequelize.models.Element.findAll({
			where:{
				ContractId:ContractId,
				name:name,
				parentElementId:parentElementId
			}
		})
	})
	.then(function(elements){
console.log("GOT ELEMENTS "+elements);
		if (!elements)
			return undefined;
		element=elements[0];
		return self.getValue(element.id);
	})
	.then(function(proposal){
console.log("GOT PROPOSAL "+proposal);
		if (!proposal)
			return undefined;
		element.value=proposal.value;
		return element;
	});
}

ThreeTC.prototype.getObject=function(ContractId,object,scope,context,deps){
	var self=this;
console.log("GetObject SCOPE="+JSON.stringify(scope)+" CONTEXT="+context);
	if (object.object){
		var os;
		return this.getObject(ContractId,object.object,scope,context,deps)
		.then(function(o){
			os=o;
			return self.fetchElement(ContractId,object.index.dimensions[0].value,o.context)
		})
		.then(function(element){
			if (!element)
				return undefined;
			if (element.id)
				deps[element.id]=true;
			var value=element.value;
			if (element.type === 'block')
				value={};
			
			if (!element.parent){
				scope[element.name]=value;
			}
			
			os.value[object.index.dimensions[0].value]=value;

			return Promise.resolve({value:value,context:element.id});
		});
	}

	if (object.name){
console.log("CALL FETCH ELEMENT="+ContractId+","+object.name+","+context);
		return this.fetchElement(ContractId,object.name,context)
		.then(function(element){
			if (!element)
				return undefined;
console.log("GOT ELEMENT in getObject="+object.name+" PARENT="+element.parentElementId+" VALUE="+element.value+" TYPE="+element.dataType);
			if (element.id)
				deps[element.id]=true;

			var value=element.value;
			if (element.dataType === 'block')
				value={};
			
			if (!element.parent)
				scope[object.name]=value;
console.log("SETTING SCOPE "+object.name+" "+value+" "+JSON.stringify(scope));

			return Promise.resolve({value:value,context:element.id});
		})
	}
	if (object.value){
		return Promise.resolve({value:object.value,context:null});
	}

	return Promise.resolve({value:null,context:null});	
}


// this returns a mapping of varname->{entityId,value}. you have to squash it for use expr.eval().
ThreeTC.prototype.Scope=function(ContractId,expression,scope,context,deps){
	scope=scope||{};
	deps=deps||{};

	var job=Promise.resolve(scope);
console.log("BUILDING SCOPE FROM "+JSON.stringify(expression)+" SCOPE="+JSON.stringify(scope));
	
	job=this.getObject(ContractId,expression,scope,context,deps)

	_.each(expression.args,function(arg){
		job=job.then(function(){
			return this.Scope(ContractId,arg,scope,context,deps);
		});
	});

	return job.then(function(){
console.log("RETURNING SCOPE "+JSON.stringify(scope));
		return scope;
	});
}

ThreeTC.prototype.evaluateOperand=function(operand,proposal){
	var expr=math.parse(operand);
	var scope={};
	var deps={};
	return this.Scope(proposal.ContractId,expr,scope,proposal.ElementId,deps)
	.then(function(scope){
console.log("GOT A SCOPE "+JSON.stringify(scope));
		var result=undefined;
		try{
			result=expr.eval(scope);
		}catch(err){
console.log("ERROR EVALUATING ["+operand+"] ERROR="+err);
		}
console.log("GOT EVAL "+result);
		return result;
	});
}
`

**Comment by josdejong** [comment]
Thanks!
