### ISSUE TITLE
Static CDN link

### ISSUE THREAD

**Issue by Nekomajin42** [josdejong/mathjs#687]
Is it possible to provide a static link which point to the actually newest version of math.js?

I am working on a browser extension, and currently I can bundle the file into the extension package, or use a link with the version number in it. Both of them is hard to maintain. I don't always have time to follow what's new with the library, and the extension review process takes some time too, so it would be good to pull the newest version on every page load.

**Comment by josdejong** [comment]
cdnjs doesn't (yet) have any sort of "latest" url.

I did some looking around, and npmcdn does support this:

https://npmcdn.com/mathjs/dist/math.min.js

redirects automatically to:

https://npmcdn.com/mathjs@3.3.0/dist/math.min.js

**Comment by Nekomajin42** [comment]
Thanks!
