### ISSUE TITLE
SymbolNode shouldn't include built-in constants

### ISSUE THREAD

**Issue by 50Wliu** [josdejong/mathjs#692]
By "built-in constants" I mean these: https://github.com/josdejong/mathjs/blob/1588b0ebe0e4789f6b7ca3f4887fe7c83667daae/lib/constants.js

For example, if I `math.parse("pi");`, the parser returns a SymbolNode.  Shouldn't it instead return a ConstantNode?  And if not, is there any way I can differentiate between these constants and other symbols?

(this is with Math 2.7.0 by the way; I haven't gotten around to updating yet but I didn't see anything relevant in the changelogs)

**Comment by josdejong** [comment]
`ConstantNode` is used for things that can never change: numbers and strings.

The parser indeed doesn't differentiate between built in variables (or "constants") like `pi` and user defined variables, they are all parsed into a `SymbolNode`. If you want to check whether something is a built-in constant, you can simply check whether it exists in the `math` namespace, like:

```js
if (symbolNode.name in math) {...}
```

Would that work for you?

**Comment by Nekomajin42** [comment]
WOW, it's that simple?

**Comment by 50Wliu** [comment]
@josdejong Yup, that works!  Thanks so much!

**Comment by 50Wliu** [comment]
For posterity the builtin check should actually be
```js
if (symbolNode.name in math && math[symbolNode.name] === 'number') {...}
```
or else you could wind up accidentally matching builtin functions as well.

**Comment by josdejong** [comment]
thanks for sharing! 

A small side note: when you configure math.js to use BigNumbers, the constants will be a BigNumber instead of a number.
