### ISSUE TITLE
Aliased units cannot be multiplied or divided

### ISSUE THREAD

**Issue by ericman314** [josdejong/mathjs#695]
While working on #683 I discovered a bug that was introduced some time ago, as a result of the way units are multiplied and divided. During multiplication and division, units are cloned using `JSON.parse(JSON.stringify(...))` ([see here](https://github.com/josdejong/mathjs/blob/1588b0ebe0e4789f6b7ca3f4887fe7c83667daae/lib/type/unit/Unit.js#L642)). This fails for aliased units, since these are defined prototypically from the original unit using `Object.create` ([see here](https://github.com/josdejong/mathjs/blob/1588b0ebe0e4789f6b7ca3f4887fe7c83667daae/lib/type/unit/Unit.js#L2860)), and only an object's own properties are serialized in `JSON.stringify`.

In this example, `feet` is an alias for `foot`:

```js
console.log(math.eval('8 s * 2 foot').toString());
16 s foot

console.log(math.eval('8 s * 2 feet').toString());
undefined:489
  throw createError(name, arguments.length, 0, arguments[0], 'number,Complex,BigNumber,Fraction,Unit');
  ^

TypeError: Unexpected type of argument in function multiplyScalar (expected: number or Complex or BigNumber or Fraction or Unit, actual: undefined, index: 0)
    at createError (/home/ubuntu/mathjs/node_modules/typed-function/typed-function.js:135:17)
    at multiplyScalar (eval at _typed (/home/ubuntu/mathjs/node_modules/typed-function/typed-function.js:1042:22), <anonymous>:489:9)
    at Unit._denormalize (/home/ubuntu/mathjs/lib/type/unit/Unit.js:510:31)
    at Unit.format (/home/ubuntu/mathjs/lib/type/unit/Unit.js:1065:22)
    at Unit.toString (/home/ubuntu/mathjs/lib/type/unit/Unit.js:847:17)
    at Object.<anonymous> (/home/ubuntu/mathjs-debug/index.js:19:39)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

I propose that we:
  1. Make each alias its own stand-alone unit rather than inheriting from another unit. This would help prevent bugs like this from cropping up later on. I don't believe this would increase the memory usage very much anyway, since the majority of the information in a `unit` is just references to other objects.
  2. Replace the `JSON.parse(JSON.stringify(...))` code with a shallow copy, as that should also help to conserve memory.

I am planning on fixing this in #683.

**Comment by josdejong** [comment]
Ah, good find! I think both solutions are good. Maybe apply both? Not sure but maybe creating a shallow copy instead of JSON stringify/parse is faster too. And I agree that creating standalone copies instead of inheriting is simpler and more robust. I don't think we have to worry about memory usage for these couple of aliases.
