### ISSUE TITLE
Print options argument type error

### ISSUE THREAD

**Issue by ThomasBrierley** [josdejong/mathjs#700]
Passing the "options" argument as an object to the print function throws a type error (expecting a number). The docs state the third parameter may be of type "number" or "object" for precision or formatting respectively. e.g:

```
math.print('x = $x', {x: 1}, {
    notation: 'exponential'
});
```

**Comment by josdejong** [comment]
Thanks for reporting Thomas, this is a bug.

**Comment by josdejong** [comment]
Ah, I see you created a PR with a fix already, awesome :+1:

**Comment by ThomasBrierley** [comment]
Your welcome, thanks for the awesome library :)
