### ISSUE TITLE
Mod precision error

### ISSUE THREAD

**Issue by francofs** [josdejong/mathjs#702]
`math.mod(8.5, 0.017)` should return `0`, instead, it returns `0.01699999999999946`

**Comment by ThomasBrierley** [comment]
Try ```8.5 % 0.017``` in JavaScript, or C or anything, also try ```0.2 + 0.1``` Welcome to the world of floating point math :P You can try using the fraction number type as an alternative:

```
math.config({
    number: 'Fraction'
})
```

Only do this if performance is not a concern, because you don't get the speed of an FPU.

**Comment by francofs** [comment]
I am very aware of floating point arithmetics. That's why I am using mathjs, I don't want to reinvent the wheel. I have degree in engineering, no need to patronize. 

Anyways, the calculation I am doing is not a periodic, so it does not apply to your explanation. Determine the mantisse and you will know what I am talking about.

The thing is that 32 bit floating point precision is not enough for me.

mathjs handles most cases correctly, just try for yourself:

javascript: 0.2 + 0.1 = 0.30000000000000004
mathjs: 0.2 + 0.1 = 0.3

javascript: 3000 % 0.003 = 0.00299999999993755
mathjs: math.mod(3000, 0.003) = 0

If mathjs is supposed to handle floating point error, it has a bug. Period.

You get the idea...

**Comment by josdejong** [comment]
Take it easy guys.

math.js supports a couple of number types: regular JavaScript numbers (IEEE 754), Fractions, and BigNumbers. The regular numbers give the well known, infamous round-off errors. If you want to prevent these, you can use Fractions or BigNumbers, i.e.:

```js
// numbers
math.mod(8.5, 0.017)       // number 0.01699999999999946
math.eval('8.5 % 0.017')  // number 0.01699999999999946

// BigNumbers
math.mod(math.bignumber('8.5'), math.bignumber('0.017'));  // BigNumber 0
math.config({
  number: 'BigNumber', 
  precision: 128  // 64 by default
});
math.eval('8.5 % 0.017')  // BigNumber 0

// Fractions
math.mod(math.fraction('8.5'), math.fraction('0.017'));  // Fraction 0
math.config({number: 'Fraction'});
math.eval('8.5 % 0.017')  // Fraction 0
```

@francofs How did you evaluate this mathjs result `0.1 + 0.2 = 0.3`? By default math.js will use numbers and returns `0.30000000000000004`. The `math.mod` function doesn't use the JavaScript `%` operator internally, and it's behavior can therefore differ, [see code with argumentation](https://github.com/josdejong/mathjs/blob/master/lib/function/arithmetic/mod.js#L159-L181). 

Your solution with changing your operands to integers first sounds like a good idea: calculating the modulus of floating points is tricky! BigNumbers are still floating points, just with more digits, and can still give round off errors (in general, probably not in your specific case). If you can use Fractions they are a great and fast solution, thanks @ThomasBrierley for your suggestion and explanation!

Relevant docs:
http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
http://mathjs.org/docs/datatypes/bignumbers.html
http://mathjs.org/docs/datatypes/fractions.html

**Comment by ThomasBrierley** [comment]
I'm sorry you interpreted my reply as patronising @francofs, from your short description all I could assume was an unawareness. I personally find floating point arithmetic a very confusing subject with many nuances and would never try to patronise someone with the subject.

> If mathjs is supposed to handle floating point error, it has a bug. Period.
> 
> Edit: By the way, 8.5 % 0.017 is handled correctly by a 128 bit floating point type (ie decimal in c#)

There is no silver bullet to floating point arithmetic rounding errors, I hesitate to assume anything else about your knowledge on the subject... but increasing precision will not eradicate rounding errors, it just defines a higher limit, it will reduce them and will work for specific cases but cannot be relied upon as an complete solution.

There are many "almost" solutions including a variety of epsilon based rounding and ULP methods, but ultimately non of them work completely. I found this to be an interesting and insightful article exploring these solutions if you are interested in the problem:

https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

**Comment by francofs** [comment]
@josdejong, thanks for the pointers, I guess I wasn't successful with @ThomasBrierley at first because I was unaware of  `math.fraction('0.017')`.

I tried with BigNumber too, which didn't work, again because I didn't first parse it.

@josdejong how far can BigNumber go beyond 128 bits? 128 bits did the trick, but I am wondering if it is

By the way, I guess it was my mistake about the 0.1 + 0.2, I think I was playing around the config and had it using greater precision when I tried.

Thanks a lot for the tips on using your library. My idea of calculating mod with an integer.

**Comment by francofs** [comment]
@ThomasBrierley sorry if I sounded a bit harsh, it was not my intention, but I know it happens. Again, sorry about that.]]

> but increasing precision will not eradicate rounding errors, it just defines a higher limit

Yes, I know, and that's a problem we have to live with. I never got in a situation where 128 bit wouldn't handle but I get your point.

> There are many "almost" solutions

Yes, and I don't think we can have a perfect solution unless we deal with a different data scructure entirely. Fixed point arithimetics, fractions, etc.

But as you mentioned we have FPU built into our processors and I don't see change on the paradigm anytime soon.

> https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

I will have a read, thanks!

**Comment by josdejong** [comment]
> @josdejong how far can BigNumber go beyond 128 bits? 128 bits did the trick, but I am wondering if it is

You can go as high as you like, but at some point the calculations become too slow to be practical. 1024 bit is still usable. Just play around a bit with it and see how fast calculations are for various precisions.

**Comment by francofs** [comment]
Awesome, thanks :)

**Comment by josdejong** [comment]
You're welcome. If you have any suggestions or ideas to improve mathjs please let us know.
