### ISSUE TITLE
Extending multiply matrices behavior

### ISSUE THREAD

**Issue by albertoantunes** [josdejong/mathjs#708]
I am using mathjs to do some matrices multiplications, and in some cases am hitting the issue of having zero multiplied by Inifinty or -Infinity. The default javascript behavior is to have these evaluate to NaN (0 * Infinity = NaN), but in my case I need it to be evaluated to zero (0 * Infinity = 0). I've been able to do this by changing the specific function being hit in my case (_multiplyDenseMatrixDenseMatrix) and inside that function algorithm do the checking to see if sum is NaN give it the value of 0:

```
var _multiplyDenseMatrixDenseMatrix = function (a, b) {
	   ...
	    // loop matrix a rows
	    for (var i = 0; i < arows; i++) {
	      // current row
	      var row = adata[i];
	      // initialize row array
	      c[i] = [];
	      // loop matrix b columns
	      for (var j = 0; j < bcolumns; j++) {
	        // sum (avoid initializing sum to zero)
	        var sum = mf(row[0], bdata[0][j]);
	        if(isNaN(sum)) { sum = 0; }
	        // loop matrix a columns
	        for (var x = 1; x < acolumns; x++) {
	          // multiply & accumulate
	            var mtemp = mf(row[x], bdata[x][j]);
	            if(isNaN(mtemp)) { mtemp = 0; }
	          sum = af(sum, mtemp);
	        }
	        c[i][j] = sum;
	      }
	    }
          ...
```

This feels very hackish tough, and I was wondering if there is a better way to extend this function without having to modify it directly. I tried using the [math.import](http://mathjs.org/docs/core/extension.html#extension) with the override option but had no luck with it. Is there any better way to handling this situation that I am missing?

**Comment by josdejong** [comment]
As far as I know, `0 * Infinity` is undefined in mathematics and `NaN` is the "correct" result. 

Can you give an example calculation of where you hit this issue with NaN?

**Comment by albertoantunes** [comment]
Yes, it is indeed the "correct" result. But in my case it is "ok" to assume that 0 * Infinity = 0. It's not really something that should be incorporated in the lib, I am just looking for ways to customize it to meet this specific need. The calculation I am having trouble with is a transform matrix multiplication: 
[[10, 0, 0, 0], 
[0, 10, 0, 0],
[0, 0, 10, 0],
[0, 0, 0, 1]],

multiplied by:
[-Infinity, Infinity, Infinity, 1]

This is just one example, there are many of these multiplications happening (some without Infinity values) and I need to get the maximum and minimum values. With the default behavior, i get [NaN, NaN, NaN, NaN] which doesn't tell me anything and by treating Infinity * 0 = 0 I get [-Infinity, Infinity, Infinity, 1], which makes sense for my use case.

**Comment by albertoantunes** [comment]
After scratching my head for a while, I came up with a better way to deal with this issue, which will not need to customize the lib at all. Before multiplying the matrices, if I convert every Infinity to Number.MAX_VALUE and -Infinity to Number.MIN_VALUE, I end up with correct results, after all if there aren't any Infinity in the matrix, they will never be multiplied by zero.

It is better to treat my input beforehand than trying to reinvent the math ;)

Thanks and sorry for not realizing this earlier before creating this issue!

**Comment by josdejong** [comment]
Sounds indeed like a good solution to reprocess your matrices and replace all Infinite values. 

I will close this issue now.
