### ISSUE TITLE
webpack custom bundle issue

### ISSUE THREAD

**Issue by handoyo** [josdejong/mathjs#719]
Hi ,

I am trying to create a custom bundle. I just want to use the unit data type. I have successfully build the custom bundle, but I get `math.unit is not a function`  when i want to use it. I install mathjs via npm, and here is my code:

`var core = require('./node_modules/mathjs/core');
var math = core.create();
math.import(require('./node_modules/mathjs/lib/type/unit'));
math.import(require('./node_modules/mathjs/lib/function/unit'));
math.import(require('./node_modules/mathjs/lib/function/string/format'));`

And here is the bundled code:
[http://pastebin.com/n9iv8DjK](http://pastebin.com/n9iv8DjK)

Did i missed something in my code? Thank you.

**Comment by josdejong** [comment]
I tried to reproduce your issue, but things seem to work just fine:

```js
var core = require('mathjs/core');
var math = core.create();

math.import(require('mathjs/lib/type/unit'));
math.import(require('mathjs/lib/function/unit'));
math.import(require('mathjs/lib/function/string/format'));

var a = math.unit('2inch');
var b = a.to('cm');
console.log(math.format(b)); // "5.08 cm"
```

Can you provide more information?

**Comment by handoyo** [comment]
Hi @josdejong, here is my testing code:

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script type="text/javascript" src="math.js"></script>

</head>
<body>
<script type="text/javascript">
    var length=math.unit('1.666666768 ft');
    alert (math.format(length,6));
</script>
</body>
</html>`

And I get `(index):11 Uncaught TypeError: math.unit is not a function`. I put the math.js link file on my previous post. Thanks.

**Comment by josdejong** [comment]
Can you post the code and command line command you used to generate this bundle? The bundle itself isn't easy to read...

**Comment by handoyo** [comment]
Here is the code. [https://www.dropbox.com/s/4mfweh7ulhjzbt4/custom.zip?dl=0](url)

**Comment by josdejong** [comment]
Please check how you properly create a url in markdown, your links doesn't work (I've fixed the first one for you already)

I only had a short look at your code, can the reason be that you forget to export anything from your /src/index.js file?

**Comment by handoyo** [comment]
I have fixed the url, and thanks for the fix on the first one.

I didn't export anything in my /src/index.js file. Are there any example that i can look on how to export from the index.js file? 

Thanks

**Comment by josdejong** [comment]
> I didn't export anything in my /src/index.js file. Are there any example that i can look on how to export from the index.js file?

You can do:
```
var core = require('../node_modules/mathjs/core');
var math = core.create();

math.import(require('../node_modules/mathjs/lib/type/complex'));
math.import(require('../node_modules/mathjs/lib/type/unit/Unit'));
math.import(require('../node_modules/mathjs/lib/type/matrix'));
math.import(require('../node_modules/mathjs/lib/function/unit'));
math.import(require('../node_modules/mathjs/lib/function/string/format'));

module.exports = math;
```

This is the CommonJS module system of node.js (you can google for it and find some tutorials).

**Comment by handoyo** [comment]
Thanks a lot for the example. It's working now. I will remember to use the module system for future math js custom bundling.
