### ISSUE TITLE
compile an expression with null returns 0

### ISSUE THREAD

**Issue by XeniaSiskaki** [josdejong/mathjs#728]
In my app I need to transform some data values based on an expression provided by the user and while doing so, I stumbled upon the following situation:

`var fn = math.compile('-y').eval;`
`var result = fn({y: null});`

I would expect `result` to still be `null`. However, it is `-0`. Is this expected behavior or a bug?

**Comment by josdejong** [comment]
You negate the value of `y`. Math.js can not do a negation on `null`, therefore it converts `null` to the number `0`, then negate it, and return the result `-0`.

**Comment by XeniaSiskaki** [comment]
So I have to take care of checking whether it's `null` and if it is, don't do anything. Got it, thanks!

**Comment by josdejong** [comment]
You're welcome
