### ISSUE TITLE
Expression parser doesn't allow the Ω character

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#732]
I see the parser doesn't allow the Ω character (ohm, `\u2126`). That would be a nice one to add. I haven't yet checked whether this is part of a block of related characters that we still miss, could well be.

**Comment by FSMaxB** [comment]
It's part of the [greek symbols](http://unicode-table.com/en/sets/greek-symbols/), I think all of them could be useful be cause they are used as symbols quite a lot in mathematics.

**Comment by josdejong** [comment]
It's part of a block with "letter like symbols". We can just add this block (range \u2100 to \u214F).

http://unicode-table.com/en/#letterlike-symbols
