### ISSUE TITLE
loops with specific break criteria

### ISSUE THREAD

**Issue by h1ps** [josdejong/mathjs#733]
Hi, 
i wanted to ask, if it's possible with mathjs to generate a value based on an array of keys.
For example i want to determine the h-index. 
The h-index is defined by:

> "The  definition of the index is that a scholar with an index of h has published h papers each of which has been cited in other papers at least h times.[4] Thus, the h-index reflects both the number of publications and the number of citations per publication. The index is designed to improve upon simpler measures such as the total number of citations or publications. The index works properly only for comparing scientists working in the same field; citation conventions differ widely among different fields. "
https://en.wikipedia.org/wiki/H-index

![Image of h-index](https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/H-index-en.svg/638px-H-index-en.svg.png)

So in normal javascript i would loop through sorted array of citations and break this loop when my index is higher than the stored citations. 

Example loop:
```javascript
var hIndex = 0;
var citesPerPublication = [22,14,12,12,11,10,9,9,7,7,6,6,5,5,5,5,4,4,4,3,3,3,3,3,2,2,11,1,1,1,1,0,0,0];
for(var i=0; i < citesPerPublication.length; i++){
    if(citesPerPublication[i] > hIndex){
        hIndex++;
    }else{
        break;
    }
}
```
So if it is possible, maybe someone can give me a hint how to achieve this?
Thank you in advance!

**Comment by josdejong** [comment]
The expression parser does not have support for loops. There are functions `map` and `forEach` to loop over arrays. These have way to "break" out though, but something like this could work:

```
citesPerPublication = [22,14,12,12,11,10,9,9,7,7,6,6,5,5,5,5,4,4,4,3,3,3,3,3,2,2,11,1,1,1,1,0,0,0];
valueLargerEqualIndex(value, index) = value >= index[1]   
# note that indices are one based, hence the >= instead of a >

largeEnough = map(citesPerPublication, valueLargerEqualIndex)
    # returns [true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false]

isTrue(value) = value == true
filtered = filter(largeEnough, isTrue)
    # returns [true, true, true, true, true, true, true, true]

hIndex = size(filtered)[1]
    # returns 8

# A shortcut would be to simply sum up all true values, 
# they are implicitely converted to the number 1:
hIndex = sum(map(citesPerPublication, valueLargerEqualIndex))
    # returns 8
``` 

Note that this only works when `citesPerPublication` is ordered in descending order. In your example it almost is except for a value `11` almost at the end. So you may have to sort the numbers first using
```
sorted = sort(citesPerPublication, "desc")
```

**Comment by h1ps** [comment]
Great, it helped me a lot! Thank you very much

**Comment by josdejong** [comment]
You're welcome
