### ISSUE TITLE
Weird behavior with Energy Unit : Wh

### ISSUE THREAD

**Issue by jderuere** [josdejong/mathjs#740]
Hi,

I'm trying to convert MWh to Wh.
For 1 MWh, I have 3600000000 Wh instead of 1 000 000 Wh.
```

var math = require('mathjs');

var eval = math.eval('1 MWh to Wh');
console.log(eval.value + " Wh");
```

Thanks

**Comment by jderuere** [comment]
I just realized you transform hour into seconds. Does it make sense?

**Comment by ericman314** [comment]
The private `value` property is the SI value of the unit that is used internally for calculation. This quantity would be represented in seconds. I don't know your actual use case, but it should probably suffice to do this:

```js
var math = require('mathjs');

var eval = math.eval('1 MWh to Wh');
console.log(eval.toString());    // 1e+6 Wh
```
