### ISSUE TITLE
Expressions/syntax example has error

### ISSUE THREAD

**Issue by HarrySarson** [josdejong/mathjs#743]
In file: https://github.com/josdejong/mathjs/blame/master/docs/expressions/syntax.md#L395

The expected result of evaluating each expression is indicated in comments after each line.
I believe some of these to be wrong. When running the code in my terminal:

![docscreenshot](https://cloud.githubusercontent.com/assets/16308754/20074155/fc2f9364-a526-11e6-8005-483b6dc410b9.png)

Problems are:
 - `size` returns 1 by 1 matrix whereas comment indicates it will return a number.
 - Changing a character of string returns only the character changed whereas comment indicates that the whole string will be returned.
 - Likewise, changing a range of characters returns the range of characters changed and not the whole string.

Changing the strings is easy, I don't know how the size should be documented but having it as a number is confusing at is isn't a number.

**Comment by josdejong** [comment]
Thanks, we should update the comments according to the behavior of math.js
