### ISSUE TITLE
How to verify that the expression is legal?

### ISSUE THREAD

**Issue by ptlinyi** [josdejong/mathjs#746]
How to verify that the expression is legal? Otherwise, there will be a lot of errors in the console when call mathjs.eval()

**Comment by josdejong** [comment]
To see whether the syntax is valid, you have to parse the expression. To see whether all function calls are valid, you have to evaluate the expression. 

You can put a try/catch around the code and do "something" when an error is thrown.

What is exactly your use case?

**Comment by ptlinyi** [comment]
@josdejong 
I was used to calculate the expression of user input, the user is likely to enter the wrong expression, and because the real-time operation in the user input in the process, which will lead to a lot of mistakes in the information on the console.

**Comment by josdejong** [comment]
Maybe you can debounce evaluation whilst the user is typing, or only evaluate when the user leaves the input field or clicks an eval button explicitly. You will have to deal with reporting errors to the user one way or the other.

**Comment by josdejong** [comment]
I suppose the question is answered and will close this issue now.
