### ISSUE TITLE
No prefix support for rad

### ISSUE THREAD

**Issue by XeniaSiskaki** [josdejong/mathjs#749]
If I'm not mistaken, currently no prefixes are supported for `rad`. Would it be possible to add them?

**Comment by josdejong** [comment]
Yeah, makes sense, thanks for the suggestion.

**Comment by XeniaSiskaki** [comment]
We just updated to the latest version and saw you used the `LONG` prefixed. May I ask why? It doesn't really in our case, but I can still use the custom unit I created. I was just curious

**Comment by josdejong** [comment]
I simply didn't think of that, my mistake. 

Makes sense to fix this, and implement `milliradian` and corresponding `mrad` instead of `millirad`. It will be a breaking change so we'll schedule it for v4.
