### ISSUE TITLE
how to define a custom operator

### ISSUE THREAD

**Issue by kagarwala** [josdejong/mathjs#75]
Hi,
it might be supported by current api...But upon initial look I couldn't find how to achieve this...
F
or example...

(1+2) ^ (1 + 1) = 9...it works perfectly...

What if I am to parse an expression with a custom operator like...nCr...

(1+2) C (1 + 1) ...???? How do I do it...???
Can I register 'C' as a binary operator to the parser and tell it what to do when it encounters the same?

**Comment by nycos62** [comment]
same here I was searching to add double factorial ‼ to mathjs
https://en.wikipedia.org/wiki/Double_factorial
