### ISSUE TITLE
Invalid unit name (must begin with alpha character)

### ISSUE THREAD

**Issue by XeniaSiskaki** [josdejong/mathjs#754]
I tried adding a custom unit with
`math.createUnit('%/V', '1/V');` 
but it throws the `Invalid unit name (must begin with alpha character): "%/V"` error.

Is there a workaround for that? We need the `%/V` unit and since percentage is not supported, I have to create a custom one. How could I do this?

**Comment by josdejong** [comment]
I would not recommend creating a unit named `%/V` since this name conflicts with two operators: modulus `%` and division `/`. 

It's currently not possible to customize the allowed characters for new unit names. We can make that customizable, we recently did that for symbol names too (see #715).

**Comment by XeniaSiskaki** [comment]
So there is no workaround?

**Comment by josdejong** [comment]
As workaround you can override the method `Unit.prototype.createUnitSingle`, see code:

https://github.com/josdejong/mathjs/blob/master/lib/type/unit/Unit.js#L3026-L3197

The relevant part is the call `assertUnitNameIsValid(name)` here:
https://github.com/josdejong/mathjs/blob/master/lib/type/unit/Unit.js#L3043 

This function is not accessible from outside and does the actual validation of the unit name. You will have to replace this function with your own, it contains a check `isValidAlpha` which you need to adjust:
https://github.com/josdejong/mathjs/blob/master/lib/type/unit/Unit.js#L2941-L2961

**Comment by ericman314** [comment]
For more discussion and possible workarounds, see #547, #492, #504.
