### ISSUE TITLE
Support +=

### ISSUE THREAD

**Issue by toddmedema** [josdejong/mathjs#760]
Example:
`a = 1`
`a += 1` should set a = 2 and return `2`

**Comment by josdejong** [comment]
Thanks for the suggestion, I miss this operator too every now and then.

**Comment by Nekomajin42** [comment]
Will it work with `-=`, `*=` and `/=` too?

**Comment by josdejong** [comment]
Yes we we should add all of them :)

**Comment by Nekomajin42** [comment]
Not strictly related, but what about the ES7 exponential operator (`**`)?

**Comment by josdejong** [comment]
Well, we already have `^` for exponentiation, adding `**` too would not really help I think.

**Comment by harrysarson** [comment]
Lets discuss in #1134.
