### ISSUE TITLE
Function return another function and executing it not working.

### ISSUE THREAD

**Issue by ionescuvictor** [josdejong/mathjs#762]
It works with normal eval but not with the mathjs parser, which i do not understand what is its benefit over normal eval, can somebody explain please.Thank you.

```
 var scope = {
        obj: {
            window: window,
            prop: 42,
            setAge: function () {
                var myJsName = "testff";
                return function () {
                    return myJsName;
                }
            }
        }, 
    };

    console.log(scope.obj.setAge()());

    // retrieve properties using dot notation or bracket notation



    function evalInContext(js, context) {
        //# Return the results of the in-line anonymous function we .call with the passed context
        return function () { return eval(js); }.call(context);
    }

    console.log(evalInContext('scope.obj.setAge()()', scope))
   console.log(math.eval('obj.setAge()()', scope));

```

**Comment by josdejong** [comment]
Thanks for reporting, that should indeed work.

**Comment by josdejong** [comment]
I've fixed this in the `develop` branch, the fix will be available in the first next release.

**Comment by josdejong** [comment]
This has been fixed now in v3.8.1

**Comment by ionescuvictor** [comment]
Great! ty for fixing this.A thing to further watch out are static members of a function.

**Comment by josdejong** [comment]
> A thing to further watch out are static members of a function.

This works as it should right now, I've added another unit test to prevent any regressions here (see https://github.com/josdejong/mathjs/commit/572ec25665335ddc632a040d2c8a531e44b98194)
