### ISSUE TITLE
FunctionAssignmentNodes are irreversibly stringified

### ISSUE THREAD

**Issue by oskardahlberg** [josdejong/mathjs#765]
When using toString on a FunctionAssignmentNode, for example 'y(x) = 3x', it outputs 'function y(x) = 3x'.
That, however, cannot be parsed back to a FunctionAssigmentNode like `math.parse(math.parse('y(x) = 3x').toString())`

**Comment by josdejong** [comment]
Thanks for reporting, I think this is a left-over of a very early version of math.js where this was the actual syntax for defining a function, this should have been changed together with the change of the syntax itself. `.toTex()` already works correctly, it's just `.toString()`.
