### ISSUE TITLE
Modify embedded decimal.js properties?

### ISSUE THREAD

**Issue by pdh0710** [josdejong/mathjs#769]
(Please excuse my English)

Hi...

I am making a web calculator using math.js, now. I found decimal.js is embedded in math.js, and want to modify properties such as toExpPos/toExpNeg of the embedded decimal.js.
This is related to somewhat annoying problem. I want to make a high precision and high significant digits calculator, but the current default settings of math.js converts the high significant digits to exponential notation too easily.

How can I modify the properties? Probably, the direct way is modifying math.js source code, simply. But this way can make problems in future updates of math.js, I think. Please let me know the recommended way to modify the properties.

Happy New Year!

**Comment by josdejong** [comment]
You can access the embedded version of decimal.js via `math.type.BigNumber`, and change any config there like you would with `Decimal`.

**Comment by pdh0710** [comment]
Thank you.
