### ISSUE TITLE
(x+a)^n -> mistake

### ISSUE THREAD

**Issue by herhor67** [josdejong/mathjs#770]
(x+3)^2 looks like (3x)^2.
(x-(-3))^2 works.

same with 1/(x+3).

**Comment by josdejong** [comment]
Sorry I don't understand what you mean, can you elaborate?

**Comment by herhor67** [comment]
Well,  it turned out that (x+3)^2 from $_GET is automatically converted to (x 3)^2 which evaluates to (3*x)^2.
Sorry for the hassle, my bad.

**Comment by josdejong** [comment]
Ah, you forgot to encode the query parameters of the web service :D . Great to hear it's solved now.
