### ISSUE TITLE
Max and Eric I would like to ask something in private

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#772]
Hi @FSMaxB and @ericman314 I would like to ask you something in private but I don't have your emails. Could you please share your email addresses by mailing something to wjosdejong@gmail.com? Thanks!

**Comment by FSMaxB** [comment]
@josdejong I sent you an email, but my mail client crashed, so tell me if you didn't receive anything.

**Comment by josdejong** [comment]
Thanks, I got your mail and Eric's too!

**Comment by josdejong** [comment]
@FSMaxB I've sent you an email, if you didn't receive it please let me know
