### ISSUE TITLE
Custom latex output for integrated functions

### ISSUE THREAD

**Issue by h1ps** [josdejong/mathjs#775]
Hi,

is it possible to overwrite the build in _toTex()_ function for your math functions?

I know that i can import own functions and for this i can create own _toTex()_  for example: 

```javascript
function foo() {}
foo.toTex = function(node,options){
   return " some latex code"
}
math.import({foo: foo})
```

but if i try it for example for the _sum_ function like 
```javascript

sum.toTex = function(node,options){
   return " some latex code"
}
math.import({sum: sum})
```
this doesn't work.

 Thanks in advance!

**Comment by FSMaxB** [comment]
You can always just override `toTex` directly.

```js
math.sum.toTex = function () {
  return "some latex";
}

math.parse("sum()").toTex(); // -> "some latex"
```

In theory you should be able to pass a custom handler to `toTex` like the following, but it doesn't seem to work for some reason, not sure what is going on:
```js
customToTex = function () {
  return "some latex";
}

math.parse("sum()").toTex({sum: { handler: customToTex}}); //sadly doesn't work
```

Maybe I'm doing something wrong (which would be pathetic because I'm the one who implemented that feature).

You should also be able to override the `sum` function completely, including custom `toTex` handling. This requires that you pass `{override: true}` as option parameter to `import`.

**Comment by FSMaxB** [comment]
One thing to keep in mind: If you call `toTex` on the arguments of `sum`, you should pass `options` on to them.

**Comment by FSMaxB** [comment]
Looking at the code it makes sense why the second option doesn't work. Either there was a change and the documentation wasn't updated, or this feature never worked.

I'll investigate this (probably today).

**Comment by h1ps** [comment]
oh, nice!
Thank you for your hint!

**Comment by FSMaxB** [comment]
Oh, my bad, the documentation is correct I just can't read.

**Comment by FSMaxB** [comment]
The correct way to do the second option is as specified in the documentation:
```js
var customLaTeX = function (node, options) {
  if ((node.type === 'FunctionNode') && (node.name === 'sum')) {
      return 'some latex';
  }
}

math.parse("sum()").toTex({handler: customLaTeX});
```

**Comment by h1ps** [comment]
I tried your suggestion
> You should also be able to override the sum function completely, including custom toTex handling. This requires that you pass {override: true} as option parameter to import.

with the following code, 
```javascript 

function foo(test){
   console.log(test);
}
math.import({sum: foo, options: {override: true}});
```
but i get an error: 
```javascript 
Error: Cannot import "sum": already exists
```
what do I make wrong?

**Comment by FSMaxB** [comment]
`math.import` actually has two parameters:
```js
function foo(test) {
  console.log(test);
}
math.import({sum: foo}, {override: true});
```
