### ISSUE TITLE
Custom bundle for expression parser with number type

### ISSUE THREAD

**Issue by Anrymart** [josdejong/mathjs#777]
Hello, I really liked math.js expression parser and want to use it in web application. But I need only number type, so I'm trying to make a custom bundle as described in [documentation](http://mathjs.org/docs/custom_bundling.html), using browserify. However, my custom bundle contains a lot of extra code (for example, functions typed for other types and algorithms for matrices). What are possible solutions for excluding this code?

My code for browserify is
```javascript
var core = require('mathjs/core');
var math = core.create();

math.import(require('mathjs/lib/type/number'));

math.import(require('mathjs/lib/function/arithmetic'));
math.import(require('mathjs/lib/function/trigonometry'));

math.import(require('mathjs/lib/expression'));
```

**Comment by josdejong** [comment]
That's correct, the expression parser is still entangled quite a bit with other code of math.js, I think if you try to create a bundle with just the expression parser the best you can get right now is 25% of the total size of the library or something like that. 

Improving modularity (so we can improve custom bundling) is on the radar but it's not that simple, see this related issue #71.

**Comment by josdejong** [comment]
A workaround would be to configure browserify/webpack exclude all source code files of math.js that you know you will not need, like matrix related stuff which is quite large.

**Comment by Anrymart** [comment]
Thanks!
