### ISSUE TITLE
nthRoot(x,a) stops script when x is negative and a is even

### ISSUE THREAD

**Issue by herhor67** [josdejong/mathjs#781]
Hello, I have a problem, because sqrt(x) where x is negative results with NaN, and then I proceed if it's not NaN, only for positive x. But nthRoot(x) or nthRoot(x,2) or nthRoot(x,4) and so on stops my script...
This works: http://herhor.tk/math/konkurs/wykres/?f=nthRoot(x,3)
But this does not: http://herhor.tk/math/konkurs/wykres/?f=nthRoot(x,2)

**Comment by ericman314** [comment]
`nthRoot(x, a)` throws an exception if invalid arguments are given, such as negative `x` and `a` even.
In your script, this line is causing the exception:

```js
heighty = math.eval(formula, {x: lengthy});
```

You can surround that statement in a `try...catch` to gracefully handle errors. [More info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#try...catch_statement)

**Comment by herhor67** [comment]
Tried a lot, still stops. Could you give me an example?

**Comment by ericman314** [comment]
OK, glad to help.
