### ISSUE TITLE
Bug in documentation of configs

### ISSUE THREAD

**Issue by HarrySarson** [josdejong/mathjs#783]
In description of `config.predictable`: 

> When false (default), output type can vary depending on input values. For example math.sqrt(-2) returns NaN when predictable is false, and returns complex('2i') when true. 

See http://mathjs.org/docs/core/configuration.html

This is wrong on two counts
1. `sqrt(-2) === complex('1.41i')` and not `complex('2i')`
2. predictable output - `sqrt` always returns a number and for negatives returns `NaN`
  
   non predictable output - `sqrt` returns true value which is `sqrt(2) * i`

**Comment by josdejong** [comment]
:+1: good find, fixed via #784.
