### ISSUE TITLE
How do I configure mathjs to include derivative?

### ISSUE THREAD

**Issue by firepick1** [josdejong/mathjs#786]
I'm excited to try using the new derivative function (yay!). But the default mathjs only has parse(), and no derivative(). How do I configure it for use?

**Comment by ericman314** [comment]
`derivative` requires version 3.9.0 or higher. Here is a working example: https://jsfiddle.net/bmtfwgye/4/

**Comment by firepick1** [comment]
Thank you. I had a rogue node_modules in a sub directory. I was able to verify that my mathjs.version was 3.6.0, which helped me track down the rogue directory. I am very grateful for the awesome derivative support--I can now play with deep neural nets in javascript instead of python. Wheee!
