### ISSUE TITLE
Live currency conversions

### ISSUE THREAD

**Issue by sgarbesi** [josdejong/mathjs#787]
Can you supply an example on how you would go about converting currencies?

For example if I wrote `1 USD to EUR` how could I get the eval value to equate to `2`?

```javascript
math.createUnit('usd', {
	definition: '1',
	aliases: ['usd', 'USD']
});


math.createUnit('eur', {
	definition: '2',
	aliases: ['eur', 'EUR'],
	base: 'USD'
});

math.eval('1 USD to EUR').value;
```

**Comment by ericman314** [comment]
The base unit `usd` shouldn't be given a definition. Other units derived from `usd` should be defined in terms of the base unit (or other units themselves derived from the base unit). The `value` property is only used internally and shouldn't be used. Instead, try `toNumeric` or `to`:

```js
math.createUnit('usd', {
	aliases: ['USD']
});

math.createUnit('eur', {
	definition: '2 usd',
	aliases: ['EUR']
});

print(math.eval('1 USD to EUR'));   // 0.5 EUR
print(math.unit('1 USD').to('EUR'));   // 0.5 EUR
print(math.unit(1, 'USD').toNumeric('EUR'));   // 0.5

```
Here's a [live example](https://jsfiddle.net/98eLo7ro/).

**Comment by sgarbesi** [comment]
@ericman314 Thanks!

**Comment by josdejong** [comment]
Maybe interesting to add an example to mathjs where actual currencies are retrieved from for example http://fixer.io/, then added as units to mathjs, then used to convert from one to another?

**Comment by ericman314** [comment]
Here's a little experiment: https://utahengineer.com/currency.html

**Comment by josdejong** [comment]
Nice Eric, `createUnit` works smooth and easy :) 

I think there is an error in your experiment, you should take 1/rate to get the correct conversions (1 USD is 0.929 EUR at this moment, not 1.0741 EUR).

I've worked out an example here: https://github.com/josdejong/mathjs/blob/develop/examples/browser/currency_conversion.html
live demo: http://codepen.io/josdejong/pen/dNegPa?editors=1000#0
