### ISSUE TITLE
Implementing Integral

### ISSUE THREAD

**Issue by ericman314** [josdejong/mathjs#788]
To go along with the recent additions of `simplify` and `derivative` in version 3.9.0, it would be very good to begin implementing `integral` as well. This issue will discuss ideas on how to do this and how we would like to improve this function over time.

**Comment by ericman314** [comment]
Here are some ideas to get us started:

1. Use a lookup-table and pattern matching like we do in `simplify`
1. Implement the insanely complicated [Risch Algorithm](https://en.wikipedia.org/wiki/Risch_algorithm)
1. Quietly forward all calls to `integral` to [Wolfram|Alpha](http://products.wolframalpha.com/api/)

**Comment by josdejong** [comment]
I think we should indeed start with your option (1): a relatively simple pattern matching solution.

Option (3) can definitely be interesting! I think this should be a clearly separate set of functions or a separate module which adds the API of wolfram into math.js. Maybe we could integrate the [`wolfram-alpha`](https://www.npmjs.com/package/wolfram-alpha) library or create an example demonstrating how you can extend math.js with the wolfram api.

**Comment by m93a** [comment]
Let's continue the discussion in #1015
