### ISSUE TITLE
Units in different languages

### ISSUE THREAD

**Issue by valoricDe** [josdejong/mathjs#793]
I would like to use mathjs for a german platform. Do you think it is possible to integrate https://sourceforge.net/p/i18nlib/wiki/units/ into the math parser? The source contains a locale folder with all the translations. Maybe it's possible to overwrite existing unit names and aliases with these translations.

**Comment by ericman314** [comment]
Others may have more elegant solutions, but I think it might be easiest to just create aliases for the German units:

```js
math.createUnit("Meile", "1 mile");
math.createUnit("Stunde", "1 hour");

math.eval("60 Meile/Stunde to km/hr");    // 96.56064 km / hr
```

You would have to use `createUnit` for every unit you wanted translated, though.
