### ISSUE TITLE
atan2 returns a positive result when x value is negative and y value is positive

### ISSUE THREAD

**Issue by rlbaldwin** [josdejong/mathjs#806]
For example, atan2 returns the following results in radians
*   (3, 3)    =  0.785398163397448
*   (3, -3)   = 2.35619449019234
*   (-3, 3)   = -0.785398163397448
*   (-3, -3)  = -2.35619449019234
I believe the 2nd and 4th results cannot be true.  Also, contemporary arctan2 calculators return the signs required to properly determine quadrant.  This library doesn't appear to do this when the signs of the numbers don't agree.

**Comment by josdejong** [comment]
As far as I can see it's all correct (and Matlab and Wolfram Alpha seem to agree too). 

`atan2(y, x)` has coordinates described with a clear picture [here for example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2).
