### ISSUE TITLE
Implementing QR decomposition.

### ISSUE THREAD

**Issue by HarrySarson** [josdejong/mathjs#808]
Mathjs doesn't seem to have this yet. It is something I think I would be able to implement and I have found fortran and java implementations of the function which I reckon I could rewrite in javascript.

Would this be something that you would be interested in including in the libary?

**Comment by josdejong** [comment]
@HarrySarson thanks for your offer. Yes QR decomposition would be great to have!

**Comment by HarrySarson** [comment]
How do sparse matrices work? 

From https://uk.mathworks.com/help/matlab/math/sparse-matrix-operations.html#f6-14516

> 
> QR Factorization
> MATLAB computes the complete QR factorization of a sparse matrix S with
> 
>  [Q,R] = qr(S)
> or
> [Q,R,E] = qr(S)
> but this is often impractical. The unitary matrix Q often fails to have a high proportion of zero elements. A more practical alternative, sometimes known as "the Q-less QR factorization," is available.

But the "the Q-less QR factorization," returns something that isn't in itself a matrix just can be used e.g. to solve equations with.

**Comment by josdejong** [comment]
I'm not sure what your question is? I think it would be easiest to start with implementing QR decomposition for DenseMatrix. A second step would be to implement an efficient version for SparseMatrix too. From the docs you refer to I understand that Q is normally not sparse so it's not very helpful to have a SparseMatrix version, so it may not be interesting to create the SparseMatrix version of the QR decomposition and just an "R decomposition" makes more sense?

**Comment by HarrySarson** [comment]
Ah ok, I'll start with dense matrix and see how it goes :)

**Comment by josdejong** [comment]
:+1:
