### ISSUE TITLE
Document browser support

### ISSUE THREAD

**Issue by SamuelMarks** [josdejong/mathjs#810]
Last I saw was January 2014:
https://github.com/josdejong/mathjs/issues/131#issuecomment-33103607

ES5 requirement. Is that still the only requirement? - Do you support IE9 and above?

**Comment by josdejong** [comment]
That's correct, math.js works on IE9 and newer.

**Comment by SamuelMarks** [comment]
Cool. Might be worth advertising this in the README.

**Comment by josdejong** [comment]
That's a good point. I've added a section in the readme (only in the `develop` branch right now), and on the [download page](http://mathjs.org/download.html).

There was already a bit of text on the [getting started page](http://mathjs.org/docs/getting_started.html#browser), and there was already an example [old_browsers.html](http://mathjs.org/examples/browser/old_browsers.html.html) though I can't test right now if that still works.
