### ISSUE TITLE
toTex() and mathrm

### ISSUE THREAD

**Issue by ChristopherChudzicki** [josdejong/mathjs#812]
I noticed that `toTex()` uses `mathrm{...}` in places I would not expect. For example:

```
math.parse("a+b").toTex() // returns "a+\mathrm{b}" ... [b, g, h, l, m, s] all behave the similarly
math.parse(f(x)).toTex() // returns "\mathrm{f}\left( x\right)"
```

This seems typographically nonstandard (and undesirable for my app). Is this intended?

**Comment by FSMaxB** [comment]
`mathrm{...}` is used everywhere, where the text should look like normal text, not italic.

In general, `mathrm{...}` is used for Units and function names.

It is a known problem (at least to me) that some single letters are italic and some are not. This is because `toTex()` doesn't have a way to know if a letter or a word is a unit or not in a particular context, so letters that could be units are always printed as normal text, not italic.

**Comment by FSMaxB** [comment]
See [here](https://github.com/josdejong/mathjs/blob/5d11f2eeb1885f714b45a982615224eb5ae497e9/lib/expression/node/SymbolNode.js#L119) for Units and variables (it checks if it is in the list of units):

```js
  SymbolNode.prototype._toTex = function(options) {
    var isUnit = false;
    if ((typeof math[this.name] === 'undefined') && Unit.isValuelessUnit(this.name)) {
      isUnit = true;
    }
    var symbol = latex.toSymbol(this.name, isUnit);
    if (symbol[0] === '\\') {
      //no space needed if the symbol starts with '\'
      return symbol;
    }
    //the space prevents symbols from breaking stuff like '\cdot' if it's written right before the symbol
    return ' ' + symbol;
  };

  return SymbolNode;
}
```

And [`latex.toSymbol`](https://github.com/josdejong/mathjs/blob/5d11f2eeb1885f714b45a982615224eb5ae497e9/lib/utils/latex.js#L85):

```js
exports.toSymbol = function (name, isUnit) {
  isUnit = typeof isUnit === 'undefined' ? false : isUnit;
  if (isUnit) {
    if (units.hasOwnProperty(name)) {
      return units[name];
    }
    return '\\mathrm{' + name + '}';
  }

  if (exports.symbols.hasOwnProperty(name)) {
    return exports.symbols[name];
  }
  else if (name.indexOf('_') !== -1) {
    //symbol with index (eg. alpha_1)
    var index = name.indexOf('_');
    return exports.toSymbol(name.substring(0, index)) + '_{'
      + exports.toSymbol(name.substring(index + 1)) + '}';
  }
  return name;
};
```

For functions, the code is [here](https://github.com/josdejong/mathjs/blob/5d11f2eeb1885f714b45a982615224eb5ae497e9/lib/expression/node/FunctionNode.js#L368) and it uses either the template provided by the implementation of a function, or the [default template](https://github.com/josdejong/mathjs/blob/5d11f2eeb1885f714b45a982615224eb5ae497e9/lib/utils/latex.js#L77):

```js
exports.defaultTemplate = '\\mathrm{${name}}\\left(${args}\\right)';
```

**Comment by ChristopherChudzicki** [comment]
@FSMaxB Thanks for the reply and reference. That makes sense regarding single letters and units. Happily customization is easy with the `toTex` handler.
