### ISSUE TITLE
[Question] Eval equation for multiple input values

### ISSUE THREAD

**Issue by doc-z** [josdejong/mathjs#818]
I've been using mathjs for compiling and evaluating very large polynomial equations (100's of terms), which works great for evaluating single cases (scope with single values). However, I'd like to know if there's a proper way to evaluate multiple cases (scope where one variable has n number of values and all other variables are constant) in a single line. For example, I found I can get this to work:

```
var test = math.compile("x_1*2 + x_2*2");
var inp = {'x_1': [2,1], 'x_2': 2};
var result = test.eval(inp);
```
In this case result returns 8,6 which are the correct results for x_1=2 and x_1=1, respectively. However, when I try this same approach using an equation with 6 inputs and ~200 polynomial terms I get answers that are quite different than they're supposed to be. Is the above example an appropriate approach for evaluating multiple input cases at once? 
Note: I know I could just put the scope and eval lines in a loop, however, I am trying to avoid such a loop if possible, especially for equations with many inputs.

**Comment by josdejong** [comment]
I'm not sure what the difference is between your example with 2 inputs and 2 terms vs 6 inputs and ~200 terms, that should both just evaluate correctly. Passing an array for one of the inputs to get the different results for each of the different values is an elegant solution. 

Can you post an example of the case where your get wrong results?

**Comment by doc-z** [comment]
Thanks for getting back to me, here's a quick example in fiddle:

https://jsfiddle.net/c03Lam8f/7/

Please let me know if that example doesn't work... first time using fiddle. Note, the numbers for "results should be" come from the program I use to generate the equations.

**Comment by josdejong** [comment]
Thanks for the fiddle, I can reproduce your issue. 

So:

```js
code.eval({'x_1': 0.7, 'x_2': 0.8, 'x_3': 0.5, 'x_4': 0.5, 'x_5': 0.8, 'x_6': 0.7})  
    // correct 0.545366...
code.eval({'x_1': 0.7, 'x_2': 0.8, 'x_3': 0.5, 'x_4': 0.5, 'x_5': 0.75, 'x_6': 0.7})  
    // correct 1.239166...
code.eval({'x_1': 0.7, 'x_2': 0.8, 'x_3': 0.5, 'x_4': 0.5, 'x_5': [0.80,0.75], 'x_6': 0.7})  
    // wrong [1.188877679796621, 1.4770311218640277]
    // instead of [0.545366, 1.239166]
```

I haven't yet looked into it but the issue is clear.

**Comment by doc-z** [comment]
Yes, that is correct.

**Comment by josdejong** [comment]
@doc-z I did a bit of digging in your code example and found the cause of the unexpected behavior.

At various places in your equation you multiply `x_5` with `x_5`, for example:

```
 (x_5 - 0.850026506737947) * ((x_5 - 0.850026506737947) * 25.0047679649085) +\
```

When `x_5` is a vector, the matrix product will be returned, but you want to evaluate vectors element wise instead. Replacing all multiplications `*` with element-wise multiplications `.*` will give you the expected results.

**Comment by doc-z** [comment]
That makes complete sense, can't believe I missed that. Thanks again for taking the time to have a look, much appreciated!

**Comment by josdejong** [comment]
:+1: you're welcome
