### ISSUE TITLE
complex gamma

### ISSUE THREAD

**Issue by nsg21** [josdejong/mathjs#828]
Approximation used for gamma function is not appropriate for certain ranges of complex numbers

math.gamma(-4.24309)
-0.13040485878797353
math.gamma(math.complex(-4.24309,0.00001))
o {re: -11947294568.824968, im: -13865208816.957504}

gamma is continuous at -4.24309, so that should be close -0.13

**Comment by josdejong** [comment]
Thanks for reporting!

**Comment by gwhitney** [comment]
And indeed, six and a half years later, `gamma(-4.24309)` and `gamma(complex(-4.24309,0.00001))` are very close =). Closing.
