### ISSUE TITLE
Fractions

### ISSUE THREAD

**Issue by husayt** [josdejong/mathjs#84]
A way to convert decimal numbers into their fraction form i.e. `0.25 = 1/4`.

Operations on fractions:
* `1/4+2/4=3/4`
* `1/4*2/4=3/4`
* and etc

**Comment by josdejong** [comment]
I've implemented support for fractions in the [`v2`](https://github.com/josdejong/mathjs/tree/v2) branch of the project. Powered by [fraction.js](https://github.com/infusion/Fraction.js). It works awesome!

docs: https://github.com/josdejong/mathjs/blob/v2/docs/datatypes/fractions.md
examples: https://github.com/josdejong/mathjs/blob/v2/examples/fractions.js

There is one thing I'm not yet certain about: what should be the default notation when formatting a fraction using `math.format`? Right now I have built in two formatting options:

```js
var a = math.fraction(2, 3);
console.log(math.format(a));                          // Fraction, 2/3
console.log(math.format(a, {fraction: 'ratio'}));     // Fraction, 2/3
console.log(math.format(a, {fraction: 'decimal'}));   // Fraction, 0.(6)
```

Which value should be the default for option `fraction`? `'ratio'` or `'decimal'` notation?

**Comment by husayt** [comment]
THIS IS AMAZING NEWS.  My most missing feature is not missing anymore. Thank you Jos. 

I think ratio notation should be default, as not everything can be expressed as decimal.

**Comment by josdejong** [comment]
:) 

It was cool to implement, it's now very easy in `v2` as it automatically converts fractions to numbers for functions not supporting fractions :). `v2` is not yet released, but is largely complete. 

I agree with you that `ratio` should be the default. I was thinking that higher educated people may prefer the `decimal` notation, whilst regular users probably prefer the `ratio` notation.

**Comment by husayt** [comment]
This is so nice, I can't wait to v2 release. We will be integrating it into numerics straigthaway.

Just need to figure out best way of putting this in calculator. Before our calculator was working in bigNumber mode by default and it was ok. But now I am not sure.

On one side I want `6.5+3.4` to display `9.4`, on the other `2/3+2/3` to display `4/3`. Need to figure out the best way to config this.

**Comment by husayt** [comment]
Jos, shall I put issues above into different card? or is it ok to leave here?

**Comment by josdejong** [comment]
Please create a new issue for them, thanks!

**Comment by josdejong** [comment]
The just released v2 has support for fractions, powered by https://github.com/infusion/Fraction.js/
