### ISSUE TITLE
power with negative integer exponent for matrices (feature request)

### ISSUE THREAD

**Issue by balagge** [josdejong/mathjs#842]
As the notation `A^n` is quite common with square matrix `A`, negative integer `n` (especially with `n= -1`), it would make sense to add this possibility to `math.pow()`. (currently only positive integers are allowed).

**Comment by josdejong** [comment]
Thanks for the suggestion. That would indeed be a nice improvement.

Anyone interested in picking this one up?

**Comment by kv-kunalvyas** [comment]
Sounds good, I have started working on this feature.

**Comment by josdejong** [comment]
Thanks Kunal. It's a long time ago I heard from you :)

**Comment by josdejong** [comment]
This is supported nowadays, closing this issue.
