### ISSUE TITLE
Filter does not properly handle FunctionAssignmentNode

### ISSUE THREAD

**Issue by 30percent** [josdejong/mathjs#846]
When calling `filter` through eval, if the callback parameter is a FunctionAssignmentNode, it is not properly called. Simple test here:

```
var context = {collection: [1,2,3,4]};
console.log(math.eval("filter(collection, f(x) = x > 2)", context)); //prints [1,2,3,4]; expected: [3,4]
console.log(math.eval("filter(collection, x > 2)", context)); //prints [3,4]
```
This is not in line with map, which has behavior in reverse...sort of
```
var context = {collection: [1,2,3,4]};
console.log(math.eval("map(collection, f(x) = x + 2)", context)); //prints [3,4,5,6];
console.log(math.eval("map(collection, x + 2)", context)); //Error: Undefined symbol x
```

**Source of issue**:
Filter has a special transform factory to check for `OperatorNode` and create a function with parameters based on undefined symbols.  (This allows for: `math.eval("filter(collection, x > 2)", {collection: [1,2,3,4]}) //[3,4]`). However, the transform checks for:
```
if (args[1] && args[1].isSymbolNode) {
...
} else {
// an equation like filter([3, -2, 5], x > 0)
...
```
The trouble is that this creates the assumption that anything not a `SymbolNode` is a `OperatorNode`. 

**Solution**: 
Either:
1. swapping the conditionals such that we only do special behavior on specific target case (`if(args[1].isOperatorNode`), otherwise do what amounts to a passthrough.
2. change ln22: `if (args[1].isSymbolNode || args[1].isFunctionAssignmentNode) { //we don't need to check for args[1] existence again, it's above`

**Comment by josdejong** [comment]
Thanks for your clear report! 

I see both `filter` and `map` aren't behaving correcty for input like `filter([3, -2, 5], boolean(x))`, will fix that as well.
