### ISSUE TITLE
Float equal to 0 issue

### ISSUE THREAD

**Issue by cloudrick** [josdejong/mathjs#854]
Hi,

I have a float precision issue and I do not know how to solve:
math.equal(0.98+0.3, 0.57+0.71);  // true
math.equal(0.98+0.3-0.57-0.71, 0);  // true
math.equal(0.98+0.3-(0.57+0.71), 0);  // false ????

Is it a limitation or my mistake?
Thank you!

**Comment by josdejong** [comment]
This has to do with round-off errors in floating point numbers, and is indeed very confusing. 

Check out the section "Equality" here in the docs: http://mathjs.org/docs/datatypes/numbers.html#equality
