### ISSUE TITLE
Add 'pluck' function for (arrays of) objects

### ISSUE THREAD

**Issue by benthorner** [josdejong/mathjs#855]
It would be useful to have a 'pluck' function in the standard functions, which can map an array of objects to an array of values of a specified property.

     map([{a: 1}, {a: 2}], 'a') // returns [1, 2]

There is a map function for matrices/arrays, but I can't get it to work with eval. Happy to define it in my own scope - just think it might be quite useful in general.

**Comment by benthorner** [comment]
Realised you can already define your own :-)

   map(myArray, f(x) = x["myField"])

**Comment by josdejong** [comment]
:+1: 

You can also always import utility functions from for example lodash using `math.import`, I don't think we should replicate all these sort of utilities in math.js itself.
