### ISSUE TITLE
Incorrect interaction between access.js and array with bignumbers

### ISSUE THREAD

**Issue by 30percent** [josdejong/mathjs#856]
I would expect: `math.eval("[1,bignumber(2)][2]") === math.bignumber(2)`. Unfortunately, access.js calls `.valueOf` on the subset result for matrix requests. It is the only case of a valueOf call. Bignumber returns the string result on a valueOf call. It's not clear why matrices uniquely require a base value on result. It would seem to me we could just remove that call. 

*Reference link*: [access.js](https://github.com/josdejong/mathjs/blob/933f1bbb5d7711b64c9ae95bd96c217865b30415/lib/expression/node/utils/access.js#L23-L25)

**Comment by josdejong** [comment]
Thanks for reporting Mark, this is a bug.

**Comment by josdejong** [comment]
Has been fixed in the `develop` branch.
