### ISSUE TITLE
inv() returns a wrong result for a sparse matrix

### ISSUE THREAD

**Issue by jcybha** [josdejong/mathjs#863]
I have a sparse matrix AtA. But math.multiply(math.inv(AtA), AtA) is not close to eye. Seems det is very small and interestingly lusolve says it's singular. However, configuring a 64 precision with Bignumber doesn't help.

console.log('det: ' + math.det(AtA));
> det: -1.6742646460461195e-12

console.log('solve: ' + math.lusolve(math.lup(AtA), c));
>  Error: Linear system cannot be solved since matrix is singular

console.log('AtA: ' + math.format(AtA));
> AtA: Sparse Matrix [18 x 18] density: 0.25925925925925924
> 
>     (0, 0) ==> 0.5
>     (3, 0) ==> -0.125
>     (6, 0) ==> -0.125
>     (12, 0) ==> -0.25
>     (1, 1) ==> 0.5
>     (4, 1) ==> -0.125
>     (7, 1) ==> -0.125
>     (13, 1) ==> -0.25
>     (2, 2) ==> 0.5
>     (5, 2) ==> -0.125
>     (8, 2) ==> -0.125
>     (14, 2) ==> -0.25
>     (0, 3) ==> -0.125
>     (3, 3) ==> 1.3125
>     (6, 3) ==> -0.1875
>     (12, 3) ==> 0
>     (9, 3) ==> -0.5
>     (15, 3) ==> -0.5000000000000001
>     (1, 4) ==> -0.125
>     (4, 4) ==> 1.3125
>     (7, 4) ==> -0.1875
>     (13, 4) ==> 0
>     (10, 4) ==> -0.5
>     (16, 4) ==> -0.5000000000000001
>     (2, 5) ==> -0.125
>     (5, 5) ==> 1.3125
>     (8, 5) ==> -0.1875
>     (14, 5) ==> 0
>     (11, 5) ==> -0.5
>     (17, 5) ==> -0.5000000000000001
>     (0, 6) ==> -0.125
>     (3, 6) ==> -0.1875
>     (6, 6) ==> 0.8125
>     (12, 6) ==> 0
>     (9, 6) ==> -0.5
>     (15, 6) ==> 0
>     (1, 7) ==> -0.125
>     (4, 7) ==> -0.1875
>     (7, 7) ==> 0.8125
>     (13, 7) ==> 0
>     (10, 7) ==> -0.5
>     (16, 7) ==> 0
>     (2, 8) ==> -0.125
>     (5, 8) ==> -0.1875
>     (8, 8) ==> 0.8125
>     (14, 8) ==> 0
>     (11, 8) ==> -0.5
>     (17, 8) ==> 0
>     (3, 9) ==> -0.5
>     (6, 9) ==> -0.5
>     (9, 9) ==> 1
>     (15, 9) ==> 0
>     (4, 10) ==> -0.5
>     (7, 10) ==> -0.5
>     (10, 10) ==> 1
>     (16, 10) ==> 0
>     (5, 11) ==> -0.5
>     (8, 11) ==> -0.5
>     (11, 11) ==> 1
>     (17, 11) ==> 0
>     (0, 12) ==> -0.25
>     (3, 12) ==> 0
>     (6, 12) ==> 0
>     (12, 12) ==> 0.25
>     (1, 13) ==> -0.25
>     (4, 13) ==> 0
>     (7, 13) ==> 0
>     (13, 13) ==> 0.25
>     (2, 14) ==> -0.25
>     (5, 14) ==> 0
>     (8, 14) ==> 0
>     (14, 14) ==> 0.25
>     (3, 15) ==> -0.5000000000000001
>     (6, 15) ==> 0
>     (9, 15) ==> 0
>     (15, 15) ==> 0.5000000000000001
>     (4, 16) ==> -0.5000000000000001
>     (7, 16) ==> 0
>     (10, 16) ==> 0
>     (16, 16) ==> 0.5000000000000001
>     (5, 17) ==> -0.5000000000000001
>     (8, 17) ==> 0
>     (11, 17) ==> 0
>     (17, 17) ==> 0.5000000000000001

console.log('AtA-1 x AtA: ' + math.format(math.multiply(math.inv(AtA), AtA)));
> AtA-1 x AtA: Sparse Matrix [18 x 18] density: 0.3333333333333333
> 
>     (0, 0) ==> 2
>     (3, 0) ==> 4
>     (6, 0) ==> 6
>     (9, 0) ==> 4
>     (12, 0) ==> 8
>     (15, 0) ==> 4
>     (1, 1) ==> 2
>     (4, 1) ==> 4
>     (7, 1) ==> 6
>     (10, 1) ==> 4
>     (13, 1) ==> 8
>     (16, 1) ==> 4
>     (2, 2) ==> 2
>     (5, 2) ==> 4
>     (8, 2) ==> 6
>     (11, 2) ==> 4
>     (14, 2) ==> 8
>     (17, 2) ==> 4
>     (0, 3) ==> 0
>     (3, 3) ==> 0
>     (6, 3) ==> -4
>     (9, 3) ==> 8
>     (12, 3) ==> -4
>     (15, 3) ==> 0
>     (1, 4) ==> 0
>     (4, 4) ==> 0
>     (7, 4) ==> -4
>     (10, 4) ==> 8
>     (13, 4) ==> -4
>     (16, 4) ==> 0
>     (2, 5) ==> 0
>     (5, 5) ==> 0
>     (8, 5) ==> -4
>     (11, 5) ==> 8
>     (14, 5) ==> -4
>     (17, 5) ==> 0
>     (0, 6) ==> -8
>     (3, 6) ==> -8
>     (6, 6) ==> 0
>     (9, 6) ==> 0
>     (12, 6) ==> -4
>     (15, 6) ==> -8
>     (1, 7) ==> -8
>     (4, 7) ==> -8
>     (7, 7) ==> 0
>     (10, 7) ==> 0
>     (13, 7) ==> -4
>     (16, 7) ==> -8
>     (2, 8) ==> -8
>     (5, 8) ==> -8
>     (8, 8) ==> 0
>     (11, 8) ==> 0
>     (14, 8) ==> -4
>     (17, 8) ==> -8
>     (0, 9) ==> -8
>     (3, 9) ==> -8
>     (6, 9) ==> -8
>     (9, 9) ==> -8
>     (12, 9) ==> -8
>     (15, 9) ==> -8
>     (1, 10) ==> -8
>     (4, 10) ==> -8
>     (7, 10) ==> -8
>     (10, 10) ==> -8
>     (13, 10) ==> -8
>     (16, 10) ==> -8
>     (2, 11) ==> -8
>     (5, 11) ==> -8
>     (8, 11) ==> -8
>     (11, 11) ==> -8
>     (14, 11) ==> -8
>     (17, 11) ==> -8
>     (0, 12) ==> -2
>     (3, 12) ==> -4
>     (6, 12) ==> -4
>     (9, 12) ==> -4
>     (12, 12) ==> -4
>     (15, 12) ==> -4
>     (1, 13) ==> -2
>     (4, 13) ==> -4
>     (7, 13) ==> -4
>     (10, 13) ==> -4
>     (13, 13) ==> -4
>     (16, 13) ==> -4
>     (2, 14) ==> -2
>     (5, 14) ==> -4
>     (8, 14) ==> -4
>     (11, 14) ==> -4
>     (14, 14) ==> -4
>     (17, 14) ==> -4
>     (0, 15) ==> 0
>     (3, 15) ==> 0
>     (6, 15) ==> 0
>     (9, 15) ==> 0
>     (12, 15) ==> 0
>     (15, 15) ==> 0
>     (1, 16) ==> 0
>     (4, 16) ==> 0
>     (7, 16) ==> 0
>     (10, 16) ==> 0
>     (13, 16) ==> 0
>     (16, 16) ==> 0
>     (2, 17) ==> 0
>     (5, 17) ==> 0
>     (8, 17) ==> 0
>     (11, 17) ==> 0
>     (14, 17) ==> 0
>     (17, 17) ==> 0
> 

-------

**Comment by jcybha** [comment]
This happens with a dense matrix too:

> AtA: [[0.5, 0, 0, -0.125, 0, 0, -0.125, 0, 0, 0, 0, 0, -0.25, 0, 0, 0, 0, 0], [0, 0.5, 0, 0, -0.125, 0, 0, -0.125, 0, 0, 0, 0, 0, -0.25, 0, 0, 0, 0], [0, 0, 0.5, 0, 0, -0.125, 0, 0, -0.125, 0, 0, 0, 0, 0, -0.25, 0, 0, 0], [-0.125, 0, 0, 1.3125, 0, 0, -0.1875, 0, 0, -0.5, 0, 0, 0, 0, 0, -0.5000000000000001, 0, 0], [0, -0.125, 0, 0, 1.3125, 0, 0, -0.1875, 0, 0, -0.5, 0, 0, 0, 0, 0, -0.5000000000000001, 0], [0, 0, -0.125, 0, 0, 1.3125, 0, 0, -0.1875, 0, 0, -0.5, 0, 0, 0, 0, 0, -0.5000000000000001], [-0.125, 0, 0, -0.1875, 0, 0, 0.8125, 0, 0, -0.5, 0, 0, 0, 0, 0, 0, 0, 0], [0, -0.125, 0, 0, -0.1875, 0, 0, 0.8125, 0, 0, -0.5, 0, 0, 0, 0, 0, 0, 0], [0, 0, -0.125, 0, 0, -0.1875, 0, 0, 0.8125, 0, 0, -0.5, 0, 0, 0, 0, 0, 0], [0, 0, 0, -0.5, 0, 0, -0.5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, -0.5, 0, 0, -0.5, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, -0.5, 0, 0, -0.5, 0, 0, 1, 0, 0, 0, 0, 0, 0], [-0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0, 0], [0, -0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0, 0], [0, 0, -0.25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.25, 0, 0, 0], [0, 0, 0, -0.5000000000000001, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5000000000000001, 0, 0], [0, 0, 0, 0, -0.5000000000000001, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5000000000000001, 0], [0, 0, 0, 0, 0, -0.5000000000000001, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5000000000000001]]

> AtA-1 x AtA: [[2, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -2, 0, 0, 0, 0, 0], [0, 2, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -2, 0, 0, 0, 0], [0, 0, 2, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -2, 0, 0, 0], [4, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0, 0], [0, 4, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0], [0, 0, 4, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -4, 0, 0, 0], [6, 0, 0, -4, 0, 0, 0, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0, 0], [0, 6, 0, 0, -4, 0, 0, 0, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0], [0, 0, 6, 0, 0, -4, 0, 0, 0, 0, 0, -8, 0, 0, -4, 0, 0, 0], [4, 0, 0, 8, 0, 0, 0, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0, 0], [0, 4, 0, 0, 8, 0, 0, 0, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0], [0, 0, 4, 0, 0, 8, 0, 0, 0, 0, 0, -8, 0, 0, -4, 0, 0, 0], [8, 0, 0, -4, 0, 0, -4, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0, 0], [0, 8, 0, 0, -4, 0, 0, -4, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0], [0, 0, 8, 0, 0, -4, 0, 0, -4, 0, 0, -8, 0, 0, -4, 0, 0, 0], [4, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0, 0], [0, 4, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -4, 0, 0, 0, 0], [0, 0, 4, 0, 0, 0, 0, 0, -8, 0, 0, -8, 0, 0, -4, 0, 0, 0]]
>

**Comment by josdejong** [comment]
The determinant of your matrix is zero (except for numerical errors), so your matrix is not invertable I think? Calculating with higher precision will only give you a determinant closer to the exact value (zero).

**Comment by jcybha** [comment]
Probably. In my case, I actually don't need to invert, but need to solve Ax = C. The C library I'm porting from is umfpack. Calling umfpack_di_symbolic, umfpack_di_numeric, and umfpack_di_solve gives a correct solution. Will lusolve() be able to try something similar instead of throwing the 'singular matrix' exception?

**Comment by josdejong** [comment]
I don't know. Apparently this C library uses a different algorithm which can deal with this. We could of course look into improving the current implementation of `lusolve` if there is a better algorithm for it.
