### ISSUE TITLE
Algebraic calculations

### ISSUE THREAD

**Issue by husayt** [josdejong/mathjs#87]
If you think about algebraic calculations are very similar to operations on units. You can already do `5m+6m` in math.js. So I guess this is something which can be implemented.
- `a+a=2a`
- `a*a=a^2`
- `a/a=1`
- `a-a=0`
- `a+b=a+b`
- `a*b=ab` 
- `a/b=a/b`
- `2a*3b=6ab`

**Comment by josdejong** [comment]
I will close this issue now since we do have implementations of `simplify` and `derivative`. They can be improved of course, and we would love to have `integral` too, but let's close this generic topic and discuss further improvements in separate, more specific topics.
