### ISSUE TITLE
Does not work in browser

### ISSUE THREAD

**Issue by 30kcom** [josdejong/mathjs#872]
Seems like distributed version is only for node.js. Is there any way to include the library as regular js script on HTML page? How to do it?

**Comment by HarrySarson** [comment]
http://mathjs.org/examples/browser/basic_usage.html.html has an example of using mathjs in a html page.

The key bit is:
``` html
<script src="http://cdnjs.cloudflare.com/ajax/libs/mathjs/3.13.3/math.min.js"></script>
```

Which includes the libary and sets the global variable `math` to an instance of `mathjs`.

**Comment by 30kcom** [comment]
Sorry, my mistake. I was referring to the library through "mathjs" variable, not "math". Thank you for fast reply!
