### ISSUE TITLE
Better document global variable in downloads page.

### ISSUE THREAD

**Issue by HarrySarson** [josdejong/mathjs#873]
Off the back of #872 I think that the name of the global variable set when the package is imported through a script tag (i.e. `math`) should be included in the text at http://mathjs.org/download.html#download.

I can't work out how to edit this page to make a pr.

**Comment by josdejong** [comment]
Right now this is described on a separate page Getting Started, it may be too much information to merge both Downloads and Getting Started pages into one page. Maybe we can link to the Getting Started page from the Downloads page?

**Comment by HarrySarson** [comment]
Could we add an extra line to Getting Started then? At the moment you have to read the example to find the name of the global variable.

**Comment by josdejong** [comment]
yes we can do that :)

**Comment by HarrySarson** [comment]
I can do a pr :)

**Comment by josdejong** [comment]
yes please :)
