### ISSUE TITLE
Specify number format.

### ISSUE THREAD

**Issue by shenkev** [josdejong/mathjs#875]
`math.unit("123 angstrom").toSI().toNumber();`

is returning 1.23e-8. 

Is there any way to make it return 123*10^(-8)? This is the format I want to pass to another function.

**Comment by josdejong** [comment]
You can use function `format` to format numbers in various ways, though I'm not sure about exactly what format you're looking for. Something like this?

```js
var result = math.unit("123 angstrom").toSI().toNumber();
console.log(math.format(, {notation: 'exponential'}));  // "1.2300000000000e-8"
```

docs:
http://mathjs.org/docs/reference/functions/format.html
