### ISSUE TITLE
Aditional Units

### ISSUE THREAD

**Issue by pjhampton** [josdejong/mathjs#879]
We used the math.js for our [interative conversion tool](https://duckduckgo.com/?q=1234+cm+to+m&t=hz&ia=answer) at DuckDuckGo. We added a load of custom units to meet the demand of the users. Would it be of interest for me to add these to Math.js over the coming weeks?

[Our custom units](https://github.com/duckduckgo/zeroclickinfo-goodies/blob/master/share/goodie/conversions/conversions.js#L45)

**Comment by josdejong** [comment]
That's really cool to hear!

Yes, would be great you add more missing units and aliases! 

(Sorry for the late reply btw)

**Comment by pjhampton** [comment]
Hey, I'm not working with ddg anymore so I can't offer dev support. Sorry!
