### ISSUE TITLE
Reducing filesize for eval operations only for browsers [question]

### ISSUE THREAD

**Issue by Murph9** [josdejong/mathjs#880]
Hello, I am trying to use the math.eval feature of this library on our teams website.
The math.js library is running well on our sites development version and is exactly what we needed.
Although we did find out that the minified version is a very large 464Kb which is way too large for browser use. (we have many other js libraries included that all total to less than that) 

Our website is C# ASP.NET based and we don't have the option to use info on the custom bundles page to reduce the size of the file.
We must have our content coming from one site because of local privacy regulations and policies - which means we can't use a cdn. (this also wouldn't reduce the file size hit)

Our interest is really only for math eval and doesn't require any variable context but we may require evaluation trees.

What would we need to do to generate a smaller version of the file?
Or does someone already have a vesrion just containing eval?

Thanks.

**Comment by josdejong** [comment]
> What would we need to do to generate a smaller version of the file?

Create a [custom bundle](http://mathjs.org/docs/custom_bundling.html) once and include that in your web application. This can reduce the file size to 25% or 50% of the full version. See also #882 . 

Alternatively, you can find another expression parser that suits your needs, like [expr-eval](https://www.npmjs.com/package/expr-eval) or [math-expression-evaluator](https://www.npmjs.com/package/math-expression-evaluator).

> Or does someone already have a vesrion just containing eval?

not that I know of.

**Comment by Murph9** [comment]
Thanks for the response,

We have already looked at the custom bundle page but it doesn't fit with our requirements.
I had also searched the issues here and found that as the size doesn't reduce enough (our target was 10% of the current min file size) and would be too large.

The only solution to use this library would be if there was a custom build but it was a long shot.

Thanks for the help this library looks great, although one of the libraries you linked looks like it will work better for what we wanted.

**Comment by josdejong** [comment]
Sounds good, good to hear you've found a solution!

I've been working on creating a standalone version of the expression parser this weekend, which is almost there. The minified+gzipped size is 28 KiB (full library size is 121 KiB). Still relatively large because the expression parser contains functionality for parsing into an expression tree and operating on this tree. That functionality may not be needed by everyone in which case an alternative library with just a simple "eval" may be a better fit.

**Comment by jean-emmanuel** [comment]
> I've been working on creating a standalone version of the expression parser this weekend, which is almost there

I just stumbled on this, maybe a bit late but by any chance could you point out what needs to be imported to make a standalone parser/eval build ?

**Comment by Murph9** [comment]
I ended up going with a much smaller library as the use case only simple
+-* #
math.

**Comment by josdejong** [comment]
> I ended up going with a much smaller library as the use case only simple +-* # math.

:+1:  the expression parser of mathjs can be overkill, good to stay critical and select a pragmatic, fitting approach. 

> I just stumbled on this, maybe a bit late but by any chance could you point out what needs to be imported to make a standalone parser/eval build ?

@jean-emmanuel did you try the documentation on custom bundling http://mathjs.org/docs/custom_bundling.html ? Or have a look at https://github.com/josdejong/mathjs-expression-parser?

**Comment by jean-emmanuel** [comment]
https://github.com/josdejong/mathjs-expression-parser is a very good start thanks a lot :)

**Comment by josdejong** [comment]
:+1:
