### ISSUE TITLE
math.smallerEq('5', '10') returns false

### ISSUE THREAD

**Issue by scottagarman** [josdejong/mathjs#881]
First, I have been using strings for all the mathjs functions including chaining etc. My values comeback from nodepg as strings (numeric postgres type) so I thought I would just be consistent and use strings the whole way though. 

With that said smallerEq and similar functions are returning unexpected results.

https://jsbin.com/dacufetegu/edit?html,output

math.smallerEq(5, 10) // returns true
math.smallerEq('5', '10') // returns false
math.smallerEq('5', '9')  // returns true

Is this a bug or am I missing something in relation to using strings with mathjs?

**Comment by josdejong** [comment]
Strings are currently compared by their characters, not the meaning of the characters. We want to change this behavior in the first next breaking version, see #680.

**Comment by scottagarman** [comment]
Thanks for the heads up. Is there a list of functions that do this so I can audit my code to make sure not to send strings to them?

**Comment by josdejong** [comment]
I'm not sure what you mean. I guess the easiest is to convert your string inputs to numbers and then do calculations with them.
