### ISSUE TITLE
Custom build?

### ISSUE THREAD

**Issue by focussing** [josdejong/mathjs#882]
Hello Jos, (goedemorgen)

What a great library!!

The current (min) build is around 470kB. For my application (Appcelerator Titanium) this is quite large, that is appears to be hanging. After 30 minutes it continues.
Can I make a custom build (or could you help me with that) which only contains the functions I use?
This is important for me, currently this blocks releasing a test app for my customer...

I use bignumbers only with the following functions:
- math.bignumber
- math.bitXor
- math.bitAnd
- math.multiply
- math.rightArithShift

This is my code:

```
var PINprime = math.bignumber('0x3A8F05AD');
var PINrnd = math.bignumber('0x239ca5b6c7ab918d');
var lowWordMask = math.bignumber('0x00000000ffffffff');

for (var i = 0; i < 12; i++) {
  var pin = math.bignumber(PIN[i]);
  PINrnd = math.bitXor(PINrnd, pin);
  PINrnd = math.bitXor(math.multiply(math.bitAnd(PINrnd, lowWordMask), PINprime), math.rightArithShift(PINrnd, 32));
}

console.log('out dec:', PINrnd.toString());
```

Looking forward to hearing from you.

**Comment by focussing** [comment]
I have commented out all functions, the expression parser that I do not use, and finally end up with a math.min.js file of 208kB. This file has reduced the build time from almost an hour, to 2 minutes. This is off course a lot, but 2 minutes to wait before every build is long compared to the 12 seconds it was...

I cannot see a way of reducing it more. Tried to comment out the matrix and complex numbers parts, but that gives errors during npm build.
However I can imagine that removing these types will help a lot... Is there a way to do that?

Best regards,
Raymond

**Comment by josdejong** [comment]
I think you're asking two questions here:

1. _Even a custom bundle is quite large_ 
  That's true, reason is mainly that when you include for example `math.add`, you also include all datatypes like Matrix, Complex, BigNumber, which are quite large. It is possible to strip the custom build further, though it requires more work: you can instruct the bundler that you use (like webpack or browserify) to exclude specific files or paths with wildcards.
2. _The build time is very long in my setup_
  I don't know what sort of setup you have. For reference: the default bundling script of math.js takes about 2 seconds to bundle and 25 seconds to minify on my machine. Some ideas:
    - Adjust your setup to only bundle and not minify when in development mode
    - Bundle+minify mathjs only once beforehand in a separate step, and do not bundle it again with every build of your development setup

**Comment by focussing** [comment]
1) okay... so it is possible but not easy/fast. Any suggestions how to do that? You are using gulp so that itself would be easy. Otherwise I will continue with what I have now.

2) I use mathjs in an APP development environment, and building the APP when mathjs included takes a lot of time to build. Building mathjs itself is fast.

Thanks for your reply!

**Comment by josdejong** [comment]
I think the best way to start stripping off parts of math.js that you don't need is:
- go through the [dependencies](https://github.com/josdejong/mathjs/blob/master/package.json#L84-L89) in package.json and see which ones you will not need, for example complex.js and fraction.js.
- go through [the source code](https://github.com/josdejong/mathjs/tree/master/lib), and identify folders/files that you know you will not use, like the whole [`type/matrix` folder](https://github.com/josdejong/mathjs/tree/master/lib/type/matrix). Then exclude these paths and files from bundling.

I'm curious to hear whether you can make it work for your use case...

**Comment by josdejong** [comment]
Just a stupid question: if you're just using a few BigNumber functions, can't you just use the BigNumber library used by math.js instead ([decimal.js](https://github.com/MikeMcl/decimal.js/))?

**Comment by focussing** [comment]
NOT a stupid question :) this might be a good opportunity, I will surely take a look into that.
I can easily setup a test with decimal.js. Thanks for pointing me to that direction.

In the meantime I tested with [the n64 library](https://github.com/chjj/n64) which also gives good results.

**Comment by josdejong** [comment]
sounds good!

**Comment by josdejong** [comment]
I think we can close this issue right?

**Comment by focussing** [comment]
Ok we can. Thank you 👍🏻

Best regards, 
Mit freundlichen Grüßen,
Met vriendelijke groet,
Raymond Verbruggen
 
FOCUSSING B.V.
Mispel 8
7621 WB Borne
Netherlands
+31 6 250 500 69 
mail@focussing.nl 
www.focussing.nl

**Comment by josdejong** [comment]
okido
