### ISSUE TITLE
sin() Huston you have problem

### ISSUE THREAD

**Issue by ViktorKostin** [josdejong/mathjs#883]
```
cos(0pi)
1
sin(0pi)
0
cos(pi)
-1
sin(pi)
1.2246467991474e-16
cos(2pi)
1
sin(2pi)
-2.4492935982947e-16
```
sinus has been evaluating incorrect

**Comment by josdejong** [comment]
This is a numeric round off error, see docs for more context:

http://mathjs.org/docs/datatypes/numbers.html#roundoff-errors
