### ISSUE TITLE
Bodmas: Displaying parsed expression 

### ISSUE THREAD

**Issue by pjhampton** [josdejong/mathjs#884]
Hey again

We are using mathjs as a backend to the DuckDuckGo calculator](https://duckduckgo.com/?q=calculator&t=hz&ia=calculator). I'm wondering if there is an out of the box way of showing the finalized BODMAS expression. For example `32 + 2 * 32` ==> `32 + (2 * 32)`

Is this currently supported in math.js before I write this functionality myself?

**Comment by josdejong** [comment]
Cool project :D

You can parse an expression in an expression tree, and do operations on that tree. One output is `toString`, and this `toString` method has some options like `{ parenthesis: 'all'}` to enclose all operations in parenthesis:
```js
var tree = math.parse('32 + 2 * 32');
var res = tree.compile().eval();               // 96
var str = tree.toString({parenthesis: 'all'}); // '32 + (2 * 32)'
```
is that what you're looking for?

If the `toString` method doesn't exactly fit your needs, you can always implement your own `toString` variant on the expression tree nodes (like there is also a `toTex` variant).
 
Docs: http://mathjs.org/docs/expressions/expression_trees.html

**Comment by pjhampton** [comment]
That's amazing! Thanks @josdejong! 😄  This is going to save me a load of work 💙  💛  💜

**Comment by josdejong** [comment]
:+1:
