### ISSUE TITLE
String values in scope...

### ISSUE THREAD

**Issue by peterchavasse** [josdejong/mathjs#885]
Is it possible to eval this...

print(math.eval("x == 'fred'", {x: 'fred'}))

I think it is complaining about the value of x in the scope not being a number.

Many thanks.

**Comment by josdejong** [comment]
The error your get is 

```
Uncaught SyntaxError: Value expected (char 6)
```
The reason is that the expression parser only supports double quotes for strings, no single quotes. A single quote is use for matrix transforms.

**Comment by peterchavasse** [comment]
Thank you :)
