### ISSUE TITLE
Is there a way to expand multiplications?

### ISSUE THREAD

**Issue by donjar** [josdejong/mathjs#890]
For example:

`math.simplify(math.parse("(a + b) * (a - b)"))`

I want it to return `a ^ 2 - b ^ 2` for my use case.

**Comment by josdejong** [comment]
Yes, you can add your own rules to the `simplify` function.

See docs: http://mathjs.org/docs/reference/functions/simplify.html

**Comment by donjar** [comment]
Oh, I just found out about it. But what if I want to expand multiplications in the general case? I want every of these to be expanded properly:
```
(a+b)(c+d) = ac + ad + bc + bd
(a+b)(c+d+e) = ac + ad + ae + bc + bd + be
(a+b+c)(d+e+f) = ad + ae + af + bd + be + be + cd + ce + cf
(a+b)(c+d)(e+f) = ace + ...
etc.
```

**Comment by josdejong** [comment]
You can either write out a new rule for every of these cases, or you can write a "dynamic" rule: you can create your own callback function which has a node tree as input and must give a node tree as output. In this function you can do any smart pattern recognition that you want.

**Comment by donjar** [comment]
I see. Thanks for the answer! :)
