### ISSUE TITLE
Constant values and fractions

### ISSUE THREAD

**Issue by madprops** [josdejong/mathjs#896]
I have a math instance with number setting as Fraction.

It seems operations like math.eval('pi + 0') throw an error:

"Cannot implicitly convert a number to a Fraction when there will be a loss of precision (value: 3.141592653589793). Use function fraction(x) to convert to Fraction."

If I just eval pi --> math.eval('pi')  I get 3.14159 as the result. 

But, if I use for instance the 64 bit BigNumber result of pi, 3.141592653589793238462643383279502884197169399375105820974944592, it converts the fraction perfectly. http://i.imgur.com/Jiwqrwa.jpg

So what I'm wondering is, why does it have trouble using constants like pi? Is it because the number used is huge? (Bigger than the BigNumber?)

**Comment by madprops** [comment]
I noticed it happens with functions like tan() but that's not listed in the list of supported functions. I wondered why it wouldn't truncate the number to be turned into a fraction by eval, but the way it is is probably the correct behavior.

**Comment by josdejong** [comment]
This is what math.js outputs:

```js
math.add(math.pi, math.fraction(0));
// TypeError: Cannot implicitly convert a number to a Fraction when there will be a 
//            loss of precision (value: 3.141592653589793). Use function fraction(x) 
//            to convert to Fraction.

var bigPi = math.bignumber('3.141592653589793238462643383279502884197169399375105820974944592');
math.add(bigPi, math.fraction(0));
// TypeError: Cannot implicitly convert a Fraction to BigNumber or vice versa. 
//            Use function bignumber(x) to convert to BigNumber or fraction(x) 
//            to convert to Fraction.
```

The error messages speak for themselves I think. It's not possible to express `pi` as a fraction, and math.js warns of that if you try. It gives such an error when you would lose precision when converting from a number to a Fraction or BigNumber.

**Comment by madprops** [comment]
What I'm confused about is that if you do math.eval('3.141592653589793238462643383279502884197169399375105820974944592 + 0') it gives a fraction just fine.

**Comment by madprops** [comment]
But I'm thinking the BigNumber instance is just different even if they're the same number.

**Comment by josdejong** [comment]
> What I'm confused about is that if you do math.eval('3.141592653589793238462643383279502884197169399375105820974944592 + 0') it gives a fraction just fine.

hm, yes, I understand that's confusing. To be consistent, math.js should throw an Error there too. Right now it doesn't since under the hood it explicitely makes numbers, Fractions, or BigNumbers from the string input. We could create these checks for lost precision here in the parser too, I think I like that idea.
