### ISSUE TITLE
Why does it give a call stack size exceedeed error here?

### ISSUE THREAD

**Issue by madprops** [josdejong/mathjs#897]
I'm wondering about why it throws "RangeError: Maximum call stack size exceeded", when I try to calculate https://pastebin.com/ezkXEiMj.

Just checking if this is normal and/or avoidable.

Edit: Forgot to say I'm using eval()

**Comment by madprops** [comment]
This might be helpful https://stackoverflow.com/a/8256867/661424

**Comment by josdejong** [comment]
The expression parser parses an expression in a recursive way, when parsing a large expression you will get a large stack of function calls. There is a limit to the number of recursive function calls you can do in JavaScript (and all programming languages), you're hitting the limit with this example. 

If you want to know more about call stacks you can google for it. To solve it, well, you shouldn't create too large expressions :D.

**Comment by FSMaxB** [comment]
Depending on the environment that the code is running in, you might be able to increase the maximum stack size, either via the operating system and or the JavaScript engine.

But that wouldn't be a solution for code that runs on machines outside of your control. And it would only delay the inevitable, since there will always be a limit.

**Comment by firepick1** [comment]
@madprops, that expression has a LOT of redundancy. How did you come to need the evaluation of such an expression?

**Comment by madprops** [comment]
@firepick1 I just use it for tests purposes. I fill my application with big random data to test how it works under heavy use. And on a specific case where that needed to be parsed it failed. But it's not a problem. I'm closing this now.
