### ISSUE TITLE
Substitution of symbols in scope

### ISSUE THREAD

**Issue by Ephs05msm** [josdejong/mathjs#904]
Hello,

Thanks for making this library available to the public; it's a wonderful tool. I've run into a bit of trouble using scope in the context of `math.eval(expr, scope)` as follows:

`scope = { infl: 0.03, costPerArea: .2, area: 60000, cost: "costPerArea * area", inflated: "cost + (cost * infl)" }`

When used in:

`math.eval(inflated, scope);`

Throws:
`Cannot convert "costPerArea * area" to a number`

I anticipated that `cost`, which resolves to `12000` through substitution of `.2 * 60000`, would have its resolved value substituted wherever else `cost` appears (i.e., `"cost + (cost * infl)"`).

Is this possible?

I asked a similar [question over at the mathsteps repo](https://github.com/socraticorg/mathsteps/issues/209) and received, among other helpful information, this example [implementation](http://patternmatics.org/mathsteps/tmp/eval_using_substitution.html).

Thanks again,
Matt

**Comment by josdejong** [comment]
The scope for eval can only contain variables, no expressions. So what you _can_ do with the expression parser is something like:

```js
var scope = {
  infl: 0.03,
  costPerArea: .2, 
  area: 60000
}
math.eval('cost = costPerArea * area', scope);
math.eval('inflated = cost + (cost * infl)', scope);

// scope is {infl: 0.03, costPerArea: 0.2, area: 60000, cost: 12000, inflated: 12360}
```


If you're looking into a solver you could look into a solution like [mathsteps](https://github.com/socraticorg/mathsteps) or a spreadsheet library like [hypercalc](https://github.com/anywhichway/hypercalc), which is capable of resolving a set of expressions.

**Comment by Ephs05msm** [comment]
Thanks for explaining. I understand now. There are some other aspects of mathsteps that align well with what I'm working on now, so I'll continue to explore this with the team over there in hopes of being able to run all math code through one API.

I'll summarize any progress we make on that end back here in case people are interested.

Thanks again.

**Comment by josdejong** [comment]
sounds good!

I will close this issue now.
