### ISSUE TITLE
Some examples on the documentation are not working properly

### ISSUE THREAD

**Issue by kemelzaidan** [josdejong/mathjs#910]
Some `eval` method examples on the documentation are not giving the same result.  This are some examples:

```js
var math = require('mathjs')
undefined
> math.eval('5.08 cm to inch');
{ [String: '2.0000000000000004 inch']
  units: [ { unit: [Object], prefix: [Object], power: 1 } ],
  dimensions: [ 0, 1, 0, 0, 0, 0, 0, 0, 0 ],
  value: 0.050800000000000005,
  fixPrefix: true,
  isUnitListSimplified: true }
> math.eval('sin(45 deg) ^ 2');
0.4999999999999999
> math.eval('9 / 3 + 2i');
{ [String: '3 + 2i'] re: 3, im: 2 }
```

**Comment by josdejong** [comment]
Thinks look fine. You see the raw output formatted as formatted by node.js. If you stringify the output with `.toString()` or `math.format(...)` you will see more readable output.

**Comment by firepick1** [comment]
The more readable output is produced by mathjs. The less readable output is produced by node. Please use mathjs to format your output, not node. We have no control over node.

**Comment by josdejong** [comment]
The command line application of math.js outputs better human readable output: http://mathjs.org/docs/command_line_interface.html

As for the round-off errors like `5.08 cm to inch` which gives `2.0000000000000004 inch` and not 2: I will try to improve the examples to prevent confusion.

**Comment by josdejong** [comment]
I've updated all examples that resulted in round-off errors, hope that helps.
