### ISSUE TITLE
Invalid operand to 'in': Object expected

### ISSUE THREAD

**Issue by krnjn** [josdejong/mathjs#912]
It seems like [this change](https://github.com/josdejong/mathjs/commit/e8ace81449584fed49c626a59bb84fff181d2b35) made in v3.15.0 broke some functionality on IE 10 and lower. Downgrading to v3.14.2 resolved the issue.

This may have something to do with the [caveat](https://babeljs.io/docs/usage/caveats/#internet-explorer) listed on Babel about the use of `__proto__` on IE 10 and below:

> If you’re inheriting from a class then static properties are inherited from it via __proto__, this is widely supported but you may run into problems with much older browsers. NOTE: __proto__ is not supported on IE <= 10 so static properties will not be inherited. See the protoToAssign for a possible work around. For classes that have supers, the super class won’t resolve correctly. You can get around this by enabling the loose option in the es2015-classes plugin.

The specific error we received (in the title) and full stack trace we received via Honeybadger is available here:
```
Invalid operand to 'in': Object expected
 customs.js  100  0  unknown(...)
webpack:///./node_modules/mathjs/lib/utils/customs.js:100:0:in `unknown'
 98  */
 99 function isSafeMethod (object, method) {
100   if (!object || typeof object[method] !== 'function') {
101     return false;
102   }
 OperatorNode.js  77  0  unknown(...)
webpack:///./node_modules/mathjs/lib/expression/node/OperatorNode.js:77:0:in `unknown'
 compile.js  43  0  unknown(...)
webpack:///./node_modules/mathjs/lib/expression/node/compile.js:43:0:in `unknown'
 Node.js  57  0  code(...)
webpack:///./node_modules/mathjs/lib/expression/node/Node.js:57:0:in `code'
 eval.js  47  0  unknown(...)
webpack:///./node_modules/mathjs/lib/expression/function/eval.js:47:0:in `unknown'
 calculator.js  56  6  result(...)
webpack:///./app/javascript/src/form_filler/calculator.js:56:6:in `result'
 calculator.js  33  10  result(...)
webpack:///./app/javascript/src/form_filler/calculator.js:33:10:in `result'
 calculator.js  26  8  unknown(...)
webpack:///./app/javascript/src/form_filler/calculator.js:26:8:in `unknown'
 calculator.js  28  6  unknown(...)
webpack:///./app/javascript/src/form_filler/calculator.js:28:6:in `unknown'
```

**Comment by josdejong** [comment]
Thanks for reporting, we'll fix this issue asap.

**Comment by josdejong** [comment]
This issue is fixed now in v3.16.0

**Comment by krnjn** [comment]
Thanks for the quick fix @josdejong!

**Comment by josdejong** [comment]
you're welcome :)
