### ISSUE TITLE
math.js can not calc float correctly

### ISSUE THREAD

**Issue by FAAAAT** [josdejong/mathjs#917]
with the original js there is a problem when we calc expressions like
`8*0.7`
js will return 5.6000000000000005
I find math.js also have this problem.
would it be fixed in the future?

**Comment by HarrySarson** [comment]
The way javascript stores floats means than some numbers (for instance `0.1`) cannot be exactly represented. By default mathjs uses the the javascript's numbers to store values.

Google floating point arithmetic for more information.

mathjs supports a fraction type for representing numbers exactly. Try:
```js
math.multiply(8, math.fraction(7, 10))

// or

math.config({
    number: "Fraction"
});

math.eval('8 * 0.7')

```
