### ISSUE TITLE
Transforming expressions into polynomials

### ISSUE THREAD

**Issue by paulobuchsbaum** [josdejong/mathjs#920]
_Algebrite_ is  an alternative javascript package for math.

In _Algebrite_ there are a set of  functions very useful to convert a expression in a polynomial equation, that can be solved by some numeric or algebric method, some specific to polynomial form, like the reputed Jenkins-Traub method. 

**expand** - deletes all parentheses from an expression, except, of course, function parentheses. 

Example:
```
var a= require('algebrite'); 
s='(2x^2-5)*(3x^2-5x+2)';
u=a.expand(s);   //  6 x^4 - 10 x^3 - 11 x^2 + 25 x - 10
```
**rationalize**, **numerator**, **denominator** - the first function rationalizes a expression converting in a numerator and denominator, both get without divide operators. Related functions are  _numerator_ that returns the upper part and _denominator_ that returns the lower part of an expression.

```
var a= require('algebrite');  
s =  "3x/(x^2+2)  -  2/(x-1)  - 4";
t=a.rationalize(s);   //  (-4 x^3 + 5 x^2 - 11 x + 4) / ((x - 1) (x^2 + 2))
t=a.numerator(s); // -4 x^3 + 5 x^2 - 11 x + 4
t=Algebrite.denominator(s);  // x^3 - x^2 + 2 x - 2
```
The _numerator_ function can be used to reduces an general expression to a direct polynomial equation form. So one can solve the resulting equation for any method.  

However, _mathjs_ is much sturdier than _algebrite_.

For instance, 

`s = "(2x-5)*(3x-3)*(x+4) / (x^2-5)   + (x-5)*(2x-3)*(2x+5) / (x^2+3x-2)  + 2x - 3";` 

 It's enough to use _numerator_ or any other function to let _algebrite_ nuts. The same does not happens in _mathjs_.

It would be great if these functions (_expand, rationalize, numerator, denominator_) existed in _mathjs_

**Comment by josdejong** [comment]
Thanks for your suggestions, that sounds like useful additions.

If anyone is interested in implementing one of the proposed functions please drop a message here.

**Comment by paulobuchsbaum** [comment]
@josdejong, using `simplify` I guess that I've got something very close to proposed `expand` function. 
It makes sense?

```
    var m=requires("mathjs");
    var defRules = m.simplify.rules;
    defRules.splice(15,3);  // Delete the rules that don't match with expand. 
    defRules.splice(12,2); 
   defRules.splice(4,3);  
   var rules =[ { l:'(n1+n2)*(n3+n4)', r:'n1*n3 + n1*n4 + n2*n3 + n2*n4' } ,
                { l:'(n1-n2)*(n3-n4)', r:'n1*n3 - n1*n4 - n2*n3 + n2*n4' } ,
	        { l:'(n1+n2)*(n3-n4)', r:'n1*n3 - n1*n4 + n2*n3 - n2*n4' } ,
		{ l:'(n1-n2)*(n3+n4)', r:'n1*n3 + n1*n4 - n2*n3 - n2*n4' } ,
                { l:'(-n1+n2)*(n3+n4)', r:'n1*n3 + n1*n4 + n2*n3 + n2*n4' } ,
                { l:'(-n1-n2)*(n3-n4)', r:'n1*n3 - n1*n4 - n2*n3 + n2*n4' } ,
		{ l:'(-n1+n2)*(n3-n4)', r:'n1*n3 - n1*n4 + n2*n3 - n2*n4' } ,
		{ l:'(-n1-n2)*(n3+n4)', r:'n1*n3 + n1*n4 - n2*n3 - n2*n4' } ,
		{ l:'(n1+n2)*n3', r:'n1*n3 + n2*n3' },
 	        { l:'(n1-n2)*n3', r:'n1*n3 - n2*n3' },
 		{ l:'(-n1+n2)*n3', r:'-n1*n3 + n2*n3' },
 	        { l:'(-n1-n2)*n3', r:'-n1*n3 - n2*n3' },
 		{ l:'(-n1+n2)*-n3', r:'n1*n3 - n2*n3' },
 	        { l:'(-n1-n2)*-n3', r:'n1*n3 + n2*n3' },
 		{ l:'(n1+n2)*-n3', r:'-n1*n3 - n2*n3' },
		{ l:'(n1-n2)*-n3', r:'-n1*n3 + n2*n3' },
		{ l: 'c1*n + c2*n', r:'(c1+c2)*n'} ,
 		{ l: 'c1*n + -c2*n', r:'(c1-c2)*n'} ,
 		{ l: 'c1*n - c2*n', r:'(c1-c2)*n'} ,
		{ l: '-c1*n + c2*n', r:'(c2-c1)*n'} ,
 		{ l: '-c1*n + -c2*n', r:'(-c1-c2)*n'} ,
                { l: '-c1*n - c2*n', r:'(-c1-c2)*n'} ,
                { l: '(n1^n2)^n3', r:'n1^(n2*n3)'} ,
 		{ l: 'c+v', r:'v+c'} ,
        	{ l: 'v*c', r:'c*v'} ,
  		{ l: '-c+v', r:'v-c'} ,
        	{ l: 'v*-c', r:'-c*v'} ]
   newRules = defRules.concat(rules);
   var expr='(x^2-2x-3)*(2x^2-3x-4)'
   console.log(m.simplify(expr,newRules).toString());
```
So the expression:

` (x^2-2x-3)*(2x^2-3x-4)`

results in:

`-4 * x ^ 2 + -7 * x ^ 3 + 17 * x + 2 * x ^ 4 + 12`

**Comment by josdejong** [comment]
He, that looks good, basically just a different set of rules with simplify. That's neat.

**Comment by paulobuchsbaum** [comment]
@josdejong, thanks.

I've added  2 additional  rules in order to handle with more complex polinomial expressions:

```
newRules = [  ...
{ l:'(n1/n2)/n3', r:'n1/(n2*n3)' } ,
{ l:'n1/(n2/n3)', r:'(n1*n3)/n2'} ....]
```

So 

```
var expr = '2x/( (2x-1) / (3x+2) ) - 5x/ ( (3x+4) / (2x^2-5) ) + 3';   
console.log(m.simplify(expr,newRules).toString());
```

Results in

> (36 * x ^ 2 + 18 * x   ^ 3 + 16 * x + -20 * x ^ 4 - 25 * x + 18 * x ^ 2 - 9 * x +      
> 24 * x - 12) / (6 * x ^ 2 - 3 * x + 8 *   x - 4)     

 With few lines one can separate the numerator and denominator:

```
var hasDivide = (node.type==='OperatorNode'  &&  node.op==="/");  // Has divide operator
var nume, deno;
if (hasDivide)
   nume = node.args[0]
   deno = node.args[1];
} else  {
   nume = node; 
   deno = m.parser('1);
}
```

**Comment by josdejong** [comment]
sounds good! Can you work this out in a pull request as a new function with tests and docs?
