### ISSUE TITLE
error in new simplify using scope and rules

### ISSUE THREAD

**Issue by paulobuchsbaum** [josdejong/mathjs#924]
The following code

```
m.require("mathjs");
var node = m.simplify("y+x",[{l:'n1-n2',r:'-n2+n1'}],{x:5})
```

Generates the error message:

>  Too many arguments in function simplify (expected: 2, actual: 3)

The [syntax](http://mathjs.org/docs/reference/functions/simplify.html) presents as one of the options:

`simplify(expr, rules, scope)`

**Comment by firepick1** [comment]
Thanks for reporting Paolo. I shall investigate. --Karl

**Comment by firepick1** [comment]
@Jos, I've committed a fix to simplify2: https://github.com/josdejong/mathjs/commit/52e29d6456b28cb877c870722f8d4127ea6c5afb
I think this is benign and feels like a simple omission. Recommend merge into develop.

**Comment by josdejong** [comment]
Thanks @firepick1 I've merged it in develop, will do a bug fix release today or tomorrow.
