### ISSUE TITLE
Symbolic Calculations

### ISSUE THREAD

**Issue by CesMak** [josdejong/mathjs#928]
Hey there,

I am working with math js and what i would like to do is something like this:
invert(imatrix(2)*s-A)  where A should also be a 2x2 Matrix

and s is a symbol.

Any ideas how something like this can be implemented.

Anyway I would like to ask how to work with symbols in math js?

**Comment by josdejong** [comment]
If with "symbols" you mean variables, you can simply use the expression parser and provide a scope with variables (just search for it in the docs). The function `imatrix` is called `eye` in math.js.

If you want to do symbolic computation you can check out the docs on that.
