### ISSUE TITLE
Fibonacci Heap `isEmpty()` returns opposite of expected

### ISSUE THREAD

**Issue by davidabrahams** [josdejong/mathjs#929]
using `node` to run code.

`test.js`:

```javascript
var math = require('mathjs');

console.log('test');

var fib = new math.type.FibonacciHeap();
console.log(fib);
console.log(fib.isEmpty());
fib.insert(1, 1);
console.log();
console.log(fib);
console.log(fib._minimum);
console.log(!fib._minimum);
console.log(!!fib._minimum);
console.log();
console.log(fib.isEmpty());
```

Running `node_modules/.bin/node test.js`:

```
test
FibonacciHeap { _minimum: null, _size: 0 }
false

FibonacciHeap {
  _minimum: 
   { key: 1,
     value: 1,
     degree: 0,
     left: [Circular],
     right: [Circular] },
  _size: 1 }
{ key: 1,
  value: 1,
  degree: 0,
  left: [Circular],
  right: [Circular] }
false
true

true
```

**Comment by josdejong** [comment]
Thanks for reporting this bug David. 

So if I see it correctly, the implementation of `isEmpty()` has one `!` too many, and should be `return !this._minimum`.

**Comment by josdejong** [comment]
This is fixed now in the `develop` branch.

**Comment by davidabrahams** [comment]
Not an issue, but, I'm having trouble figuring out how to properly import and use this library. Could you provide a code snippet for utilizing `_decreaseKey`?

**Comment by josdejong** [comment]
`_decreaseKey` is an internal function used by `FibbonacciHeap`, it's not part of the public API.

**Comment by davidabrahams** [comment]
Ah. For many uses of a Fibonacci heap, (Astar, for example), you need to be
able to decrease the key of an existing object in the heap. How does one do
that with this API?

Thanks!

**Comment by josdejong** [comment]
I'm not very familiar with Fibbonacci heap, isn't decreasing a key value automatically done when removing  a node with `FibonacciHeap.remove`?

**Comment by josdejong** [comment]
The original issue (`isEmpty` returning wrong result) should be fixed now in `v3.16.3`.

I will keep the issue open the discussion

**Comment by HarrySarson** [comment]
Can the `bug` label now be removed.

**Comment by josdejong** [comment]
ha ha, true

**Comment by josdejong** [comment]
> I will keep the issue open to continue the discussion on any missing methods.

Hm, I don't remember what these exact missing methods are?...

**Comment by josdejong** [comment]
Closing this discussion now because it has been inactive for a long time. Feel free to reopen if needed.
