### ISSUE TITLE
How To / Suggestion, aggregating by a key on a list of Objects

### ISSUE THREAD

**Issue by whistlerbrk** [josdejong/mathjs#932]
If this is not something currently doable in the library I would love to take a stab at implementing it.

Given a common structure of a list of objects: 

```
const foo = [
  { bar: 1, baz: 5 },
  { bar: 2, baz: 6 },
  { bar: 3, baz: 7 },
  { bar: 4, baz: 8 },
]
```

I would like to calculate the sum of a "column", say like this:

```
  mathjs.eval("sum(foo['bar'])", {foo: foo})
```

Which would of course eval to 10.

I see that operations like sum will work on a matrix, but the "list of objects" composite structure is ever present in day to day coding. Is there a way to do this that I missed, and if not, would you accept a PR to this effect, if so, is that notation okay, what would work if not?

**Comment by firepick1** [comment]
I would just use JS itself: 
`foo.reduce((a,obj) => a + obj.bar, 0)`

**Comment by josdejong** [comment]
Yes or something like `mathjs.sum(foo.map(obj => obj.bar))`

**Comment by firepick1** [comment]
@jos your solution is better because it can handle all the mathjs types. 😄

**Comment by whistlerbrk** [comment]
I didn't fully explain my use case, but I have come up with a solution.

This is a direct example from an application I'm building for a client, in which I generate a spreadsheet powered by questions and formula they ask their users. So I'm letting my client write formula like this:

```
sum(all(duty_vehicle.n2o) * miles_per_month)

group(sum(all(duty_vehicle.co2) * miles_per_month), duty_vehicle)
```

In my scope, `miles_per_month` is an array of floats, and duty_vehicle is an array of Objects, from which I need to extra the value of 'co2' key or 'n2o' key from, for example.

So I implemented my `all` function like so:

```
export function all(args, math, scope) {
  // this function takes a single argument
  const arg = args[0]
  const prop = arg.object.name
  const index = arg.index.dimensions[0].value

  return scope[prop].map(obj => obj[index])
};
all.rawArgs = true;
```

The group function on the other hand is way more complicated, unfortunately. My duty_vehicle objects are actually the values of a user selected dropdown (so they are not unique), so they have an index, a label, the values themselves (stored in those n2o, ch4, or co2 keys for example). So when I group, I want to split up the nested expression to only operate on each group at a time.

Given this scope:
`
  {
     duty_vehicle: [{index: 1, label: 'Pick Up Trucks', co2: '4'}, {index: 2, label: 'Regular Car', co2: '3'}, {index: 2, label: 'Regular Car', co2: '3'}],
     miles_per_month: [200, 300, 400]
  }
`

I want:

{
  'Pick Up Trucks': (4 * 200),
  'Regular Car': sum([3 * 300], [3 * 400]),
}

and I'm achieving that with this:

```
function newScopeForIndex(scope, index) {
  const i = index.index;

  const matchingScopeIndices = scope[index.key].reduce((matchingIndices, item, j) => (
    (item.index === i) ? [...matchingIndices, j] : matchingIndices
  ), [])

  return Object.keys(scope).reduce((newScope, key) => (
    {...newScope, [key]: scope[key].filter((_, index) => includes(matchingScopeIndices, index)) }
  ), {})
}

export function group(args, math, scope) {
  // the expression, which we will evaluate once for every unique index
  const exrp  = args[0];
  // the group is the name of the index
  const group = args[1].name;
  // get the unique values in scope for the group
  const indices = uniq(scope[group])

  return indices.reduce((results, index) => (
    {...results, [index.label]: exrp.eval(newScopeForIndex(scope, index))}
  ), {})
};
group.rawArgs = true;
```

Anyway, not sure if this is at all useful for anyone in the slight, I suppose my application is very specific, but I'm incredibly impressed by this library. Excuse my crap Javascript above.

**Comment by josdejong** [comment]
Thanks for sharing your use case and solution Kunal. 

In general, I think math.js should not end up duplicating all code from `lodash` since we can simply import lodash functions when needed.

**Comment by whistlerbrk** [comment]
Oh of course, I was just documenting for whatever future purposes, surely this should not be in core! Thanks @josdejong

**Comment by josdejong** [comment]
:+1:
