### ISSUE TITLE
Transforming node tree starting with deepest node first?

### ISSUE THREAD

**Issue by pklavins** [josdejong/mathjs#939]
I have a node tree from doing `test = math.parse("sqrt(75 / 3) + det([[-1, 2], [3, 1]]) - sin(pi / 4)^2")`. It's a rather large node tree with lots of functions and operators. What I want to do is to find the deepest function/operator node and evaluate it, replacing it with a constant node containing the result of the evaluation. However, the `transform()` function works the other way; it finds the 'shallowest' node first (in this case the - operator between the det and sin), evaluates that, and then nothing is left to evaluate.

```
test2 = test.transform(node => {
    if (node.isOperatorNode || node.isFunctionNode){
        console.log(node); 
        return new math.expression.node.ConstantNode(node.eval()); 
    }
})
```

I know I can find the ops/functions depth-first by doing a `filter()` and reversing that array, but the problem there is that I find the nodes 'out of context' of the whole function, so going in and evaluating that array of found nodes doesn't work either. Is there a way to modify `transform` to work depth-first?

**Comment by josdejong** [comment]
You could implement such a variant your self, that should go something like this (not tested):

```js
function transformDepthFirst(node, callback) {
  // first process childs (depth first)
  var nodeWithUpdatedChilds = node.map(child => transformDepthFirst(child, callback));

  // then process the node itself
  return callback(nodeWithUpdatedChilds);
}
```

you can make it a one liner if you want ;)
