### ISSUE TITLE
How to pass variable in callback function?

### ISSUE THREAD

**Issue by tangkhaiphuong** [josdejong/mathjs#943]
I have expression like that:
`date(f) = f != null ? f(1) : 2`

I make callback in callback. How to pass variable in next callback:

`date(_(x) = date(_(y) = x + y ))`
Error: Undefined symbol x
How to get result = 2?

**Comment by firepick1** [comment]
That is perhaps more of a Javascript question than a MathJs question. Function scope in JS is subtle and tricky. This may help: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions
