### ISSUE TITLE
can i load only what i need?

### ISSUE THREAD

**Issue by zzzgit** [josdejong/mathjs#946]
`mathjs` is too much heavy, more than 60000 lines.
only `add` `subtract` `multiply` `divide` on `bigNumber` are needed by me. so, can i just load the these functionalities?

**Comment by josdejong** [comment]
Yes, see:

http://mathjs.org/docs/custom_bundling.html
http://mathjs.org/examples/advanced/custom_loading.js.html

Depending on your use case, if you're just in need of a bignumber library you may not even need mathjs and can directly use `decimal.js` (which is used in mathjs).

**Comment by davidgilbertson** [comment]
+1 it would great to be able to `import median from 'mathjs/median'` like I can with lodash/date-fns etc.

**Comment by zzzgit** [comment]
good, thank you all very much
but now,i am directly using use decimal.js as @josdejong suggested me

**Comment by josdejong** [comment]
@davidgilbertson see #71 for a discussion on that
