### ISSUE TITLE
How do I make an alias for "=>" to mean "to"?

### ISSUE THREAD

**Issue by FjicdeiwFeiej** [josdejong/mathjs#952]
I've spent literally hours going through the documentation (which really needs to be on a single page so you can actually search it without using Google's cancer engine), but I just cannot figure it out. This certainly did NOT work:
math.createUnit('=>', 'to');

**Comment by ericman314** [comment]
Would it be acceptable to use a substring replacement on the input expression, or are you looking for something more "correct"?

```js
math.eval(expr.replace('=>', ' to '))
```

**Comment by FjicdeiwFeiej** [comment]
Well, if it isn't directly supported, it isn't. If your method works and is the only solution, it's okay with me. Thanks.
