### ISSUE TITLE
Incorrect value when using implicit multiplication

### ISSUE THREAD

**Issue by robinrodricks** [josdejong/mathjs#955]
Ok: `math.eval("10000 / 10000")` = `1`

Fails: 
`math.eval("thousand = 1000");`
`math.eval("10 thousand / 10 thousand")` = `1e+6`... Huh??

I don't know if I'm doing something wrong or its a bug in math.js...

**Comment by robinrodricks** [comment]
What worked was this:

`(10*1000) / (10*1000)` = `1` .. Ok.

But I always thought multiplication had a higher precedence than division?

**Comment by josdejong** [comment]
As far as I know, in all math applications multiplication and division have the same precedence (i.e. `4/2*2` results in `2` and not `1`). How implicit multiplication is treated differs per application, in mathjs is has the same precedence as explicit multiplication.

**Comment by robinrodricks** [comment]
Oh. I need some way to fix this as it appears to be a bug, like in the example I provided.

**Comment by josdejong** [comment]
This behavior is hardcoded in the expression parser, it's not configurable or something. There are discussions though to rethink the behavior of implicit multiplication, see #792.

**Comment by robinrodricks** [comment]
Thank you for linking me to the older issue. Hope it's implemented someday.

**Comment by josdejong** [comment]
:+1: let's close this issue and continue any discussion in #792.
