### ISSUE TITLE
math.simplify is very slow for complicated expressions

### ISSUE THREAD

**Issue by IvanVergiliev** [josdejong/mathjs#959]
Simplifying large expressions can be pretty slow. Specifically, I'm testing with expressions containing addition, multiplication and exponentiation. I glanced at the source code for simplify - I see it's iterating through all the rules until there are no more to be applied; I don't know if there are rules that would make this more efficient, or if the code should be tuned, for example.

Also, I don't know how much of a concern this is since the problematic expressions are probably not too likely to be human-generated. I'm getting them as a result from a computation.

To be more specific, the following expression:
```
0 + x * x ^ 28 + x * x ^ 28 + x * x * x ^ 27 + x * x * x * x ^ 26 + x * x * x * x * x ^ 25 + x * x * x * x * x * x ^ 24 + x * x * x * x * x * x * x ^ 23 + x * x * x * x * x * x * x * x ^ 22 + x * x * x * x * x * x * x * x * x ^ 21 + x * x * x * x * x * x * x * x * x * x ^ 20 + x * x * x * x * x * x * x * x * x * x * x ^ 19 + x * x * x * x * x * x * x * x * x * x * x * x ^ 18 + x * x * x * x * x * x * x * x * x * x * x * x * x ^ 17 + x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 16 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 15 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 14 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 13 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 12 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 11 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 10 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 9 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 8 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 7 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 6 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 5 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 4 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 3 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x ^ 2 + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x + x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * x * 1
```

, which simplifies successfully to `30 * x ^ 29` (after applying https://github.com/josdejong/mathjs/pull/958), takes about 7 seconds to run. With a similar expression where the expected result was `40 * x ^ 39`, it took ~20s, and for 100 I didn't manage to wait until it was done.

**Comment by firepick1** [comment]
Simplify serves two incompatible use cases: 1) fast simplification for engineering use, 2) thorough simplification for publication. By default, simplify is slow and thorough. Just use simplify.simplifyCore() if you need fast, single-pass simplification. That's what I use for gradient descent computation, for example, which needs fast more than pretty. How will that work for you?

**Comment by IvanVergiliev** [comment]
My use case is for eventually presenting the result to the user, so `simplifyCore` probably won't cut it. I'll probably try to stick to simpler expressions.

**Comment by firepick1** [comment]
I'll leave this open until we can speed up simplify with additional optimizations. The collection of like terms may be what's slowing it down.

**Comment by josdejong** [comment]
I've tried to find the biggest bottleneck in the `simplify` function, which seems to be the deduplication logic inside the function `mergeChildMatches` (with JSON.stringify):

https://github.com/josdejong/mathjs/blob/master/lib/function/algebra/simplify.js#L464-L479

```js
  function mergeChildMatches(childMatches) {
    if (childMatches.length === 0) {
      return childMatches;
    }

    var sets = childMatches.reduce(combineChildMatches);
    var uniqueSets = [];
    var unique = {};
    for(var i = 0; i < sets.length; i++) {
      var s = JSON.stringify(sets[i]);
      if (!unique[s]) {
        unique[s] = true;
        uniqueSets.push(sets[i]);
      }
    }
    return uniqueSets;
  }
```
When I simply drop deduplication, the function becomes in the order to 10x faster:
```js
  function mergeChildMatches(childMatches) {
    if (childMatches.length === 0) {
      return childMatches;
    }

    return childMatches.reduce(combineChildMatches);
  }
```
Currently, no unit tests break when removing this logic, but it was there for a reason so we need to be careful here. Maybe we can replace it by comparing against a unique id for each rule or comparing by object pointer or something like that. 

@tetslee it looks like you've introduced this code at the time if I'm not mistaken, can you explain a bit more about the reason behind it, and do you have ideas on how to improve it?

**Comment by firepick1** [comment]
This is great detective work! Seems like we need unit tests that would break if this code is removed so that we can understand a bit more about the effects of code removal.

**Comment by josdejong** [comment]
I'm not sure if this is still an issue. Will close it now. Feel free to reopen if needed.
