### ISSUE TITLE
README.md claims mathjs "has no dependencies", but package.json lists several

### ISSUE THREAD

**Issue by kyptin** [josdejong/mathjs#961]
I don't understand why the readme would claim that mathjs has no dependencies, when I see several dependencies in the `package.json`. Is this a vestigial claim that is no longer true, or is the phrase "has no dependencies" intended to mean something else, other than the dependencies listed in `package.json`?

Relevant snippets, from current `master`:

`README.md` line 20:

    - Has no dependencies. Runs on any JavaScript engine.

`package.json` lines 88–96:

```
  "dependencies": {
    "complex.js": "2.0.4",
    "decimal.js": "7.2.3",
    "fraction.js": "4.0.2",
    "javascript-natural-sort": "0.7.1",
    "seed-random": "2.2.0",
    "tiny-emitter": "2.0.0",
    "typed-function": "0.10.5"
},
```

Thanks for clarifying, and for your work on a useful open source library. :smile:

**Comment by josdejong** [comment]
Ha ha, thanks for pointing this out, that sentence has been there for ages :smile: 

It's indeed technically not correct anymore, and its meaning is a bit vague. The bundled version of math.js has no external dependencies, but the node.js source indeed code does. I will simply remove the sentence, it doesn't add much.

**Comment by kyptin** [comment]
Ha, glad to help. Thanks for the quick response. :smile:
