### ISSUE TITLE
Allow for case insensitive function names in expressions

### ISSUE THREAD

**Issue by sfescape** [josdejong/mathjs#962]
Allow for expressions such as 'ABS(A1)' or 'Abs(A1)' in addition to 'abs(A1)'.

Simple toLowerCase() call during (or before) parsing is insufficient because some functions are defined with mixed case.

**Comment by josdejong** [comment]
Some math applications indeed are case insensitive, but math.js is created case sensitive. This is partly a matter of preference. In the case of math.js it is important for example for units too, which need to be case sensitive since the meaning may differ depending on the case, like with prefixes `m` (milli) and `M` (mega). I don't think we will change this behavior.

If you really need it for your application, you can indeed convert your expression to lower case, and import a lower case alias of all functions into mathjs via a small loop over all function names.

**Comment by sfescape** [comment]
I did import several functions in that manner as a stopgap.

`    'average':    math.mean,
      'bitand':    math.bitAnd,
      'bitor':    math.bitOr,
      'bitxor':    math.bitXor,
      'leftshift':    math.leftShift,
      'isinteger':    math.isInteger,
      'isnumeric':    math.isNumeric,
      'ispositive':    math.isPositive,
      'isprime':    math.isPrime,
      'iszero':    math.isZero`

Your point on units is critical though, which I why I am making the suggestion. I don't want to convert the whole expression to lower case, it would be better to just lower case the function names. But that would require a change to math.js to support. As is, my stop gap measure breaks when specifying units (I'm not asking that units become case insensitive).

But I understand this is a convenience request, I can parse the expressions and lower case the function names myself (or just create a custom version of math.js). I just wanted to throw the suggestion out there. I don't really see a downside.

**Comment by josdejong** [comment]
You can make all function calls lowercase by transforming an expression:

```js
var tree = math.parse('someFunction(2) + someVariable');

var treeLowerCaseFns = tree.transform(function (node) {
  if (node.isFunctionNode && node.fn.isSymbolNode) {  // "fn(...args)"
    return new math.expression.node.FunctionNode(node.fn.name.toLowerCase(), node.args);
  } else {
    return node;
  }
});

console.log(tree.toString());               // "someFunction(2) + someVariable"
console.log(treeLowerCaseFns.toString());   // "somefunction(2) + someVariable"

var result = treeLowerCase.eval(); // get the result
```

See docs for more info: http://mathjs.org/docs/expressions/expression_trees.html

Does that solve your issue?

**Comment by sfescape** [comment]
Yes, that does along with registering lowercase function names. I have to maintain the list with each release of math.js and hope no function names conflict. It's not perfect, but it will certainly work. Thanks.

**Comment by josdejong** [comment]
:+1: 

Yes, it's still a workaround. You can of course automatically loop over all functions of math.js and create their lowercase alias. I don't think we will ever introduce two functions with the same name but different casing.
