### ISSUE TITLE
complex.js integration

### ISSUE THREAD

**Issue by infusion** [josdejong/mathjs#964]
Hi Jos,

can you say something to the following tweet I received? Is there something not exported properly?

> Neither `math.complex.fromPolar` nor `math.complex({abs:..,arg:...})` seem to work as documented on website. The 1st one doesn't even exist.
https://twitter.com/DoubleRainWave/status/923338548392144897

Robert

**Comment by josdejong** [comment]
I guess DoubleRainWave refers to the API docs here:

http://mathjs.org/docs/datatypes/complex_numbers.html#api

The docs are a bit unclear: most refer to methods and properties on a complex number instance (like `complex.re`, `complex.toPolar()`. Some however refer to static functions available on the Complex data type, but these are not exposed on the factory function `math.complex`, like `math.type.Complex.fromPolar(...)`. We should improve this.

Here some action points:
- Make clear in the API is about methods of a complex number, `Complex`, created via `math.complex()`.
- Put the static functions apart in the docs: `math.type.Complex.fromJSON`, `math.type.Complex.fromPolar`, `math.type.Complex.compare`.
- Extend the factory function `math.complex()` to support `math.complex({abs: ..., arg: ..})`, so special construction via `fromPolar` is not needed at all.

Anyone interested in picking this up?

**Comment by ssaket** [comment]
Hi @josdejong, I have submitted a pull request for this. 
Cheers
