### ISSUE TITLE
Derivative function issues

### ISSUE THREAD

**Issue by juanchireca** [josdejong/mathjs#965]
Hi guys, i found an few issues on **derivative** function.

I tried to make this: `math.derivative('1/x','x')` 
and the result was this: `-(1 / x ^ 2)` which is wrong, should be `-1 / x^(-2)`.

Here you have another case test, which are not working:
`math.derivative('x^(-1)','x').toString() -> "-(1 / x) ^ 2"`
`math.derivative('x^-1','x').toString() -> "-(1 / x ^ 2)"`
`math.derivative('x^(-1)','x').toString() -> "-(1 / x) ^ 2"`

`math.derivative('1/x^2','x').toString() -> "-(x * 2 / (x ^ 2) ^ 2)"`
`math.derivative('(x^-2)','x').toString() -> "-(2 / x ^ 3)"`

The problem seems to be on negative exponents and with variables that are raised to n value in the divisor.

P/d: The library is awesome and apologize for my english

**Comment by juanchireca** [comment]
Sorry, i'm just realized that i am wrong.
Sorry, i just getting crazy

**Comment by josdejong** [comment]
:+1: nevermind
