### ISSUE TITLE
Code in docs directory can be deleted by yarn

### ISSUE THREAD

**Issue by edoloughlin** [josdejong/mathjs#969]
See https://github.com/yarnpkg/yarn/issues/4882

If you do a `yarn autoclean --init `in your project it creates a `.yarnclean` file with a _'docs'_ entry. It seems mathjs depends on code in a docs directory so it doesn't work if you install using yarn with the default `.yarnclean` file.

**Comment by josdejong** [comment]
I responeded in https://github.com/yarnpkg/yarn/issues/4882

See also: #809

**Comment by josdejong** [comment]
How does mathjs depend on the code in the docs folder? Can you clarify? As far as I can see mathjs works fine when the docs folder is deleted

**Comment by joris-calvat** [comment]
I have the same issue
Yarn clean the folders probably cause it cannot find it. In fact when you look at this exemple. It uses relative paths for the directories attribute
https://registry.npmjs.org/npm/latest
I suggest to replace

  "directories": {
    "doc": "docs",
    "example": "examples",
    "lib": "lib",
    "test": "test"
  }
by
  "directories": {
    "doc": "./docs",
    "example": "./examples",
    "lib": "./lib",
    "test": "./test"
  }

**Comment by josdejong** [comment]
I'm not sure if that works but I've changed the paths to relative paths which is a good idea in general.

In order to be pragmatic, I've renamed the internal folder `docs` to `embeddedDocs` so mathjs should not give issues with yarn autoclean. (next version is not not yet released)

**Comment by josdejong** [comment]
This should be fixed now in v3.18.0, @edoloughlin or @joris-calvat can you double check whether there are still issues with yarn autoclean?
