### ISSUE TITLE
Source of equations from rocket_trajectory_optimization.html?

### ISSUE THREAD

**Issue by olleharstedt** [josdejong/mathjs#971]
It would be nice to have the source of the equations in the browser example rocket_trajectory_optimization.html, so it can be seen more clearly how to go from mathematical notation to math.js notation.

**Comment by ericman314** [comment]
The equations are from this: https://mathematica.stackexchange.com/a/65135. We modified one of the equations to be in terms of thrust rather than drag, and added one additional equation representing the reduction in mass of the rocket as it consumes propellant.

The author also says,

> I don't have a ready source for the derivation. I derived them myself (it's quite straightforward), but they are not original. I have seen equations like them many times.
