### ISSUE TITLE
[feature] Matrix exponential?

### ISSUE THREAD

**Issue by FabienFellay** [josdejong/mathjs#974]
It would be nice to introduce a _matrix exponential_ function as described here?
<https://en.wikipedia.org/wiki/Matrix_exponential>

And more explicitely here:
<https://en.wikipedia.org/wiki/Matrix_exponential#Computing_the_matrix_exponential>

So far, it seems that only an element-wise exponential function is available for matrices.

**Comment by josdejong** [comment]
Thanks for the suggestion!

Anyone interested in implementing this please drop a message here.

**Comment by ericman314** [comment]
Here's a good resource. The method we would want to use is on pages 9 and 10:

http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.92.5653&rep=rep1&type=pdf

**Comment by ericman314** [comment]
See #976

**Comment by FabienFellay** [comment]
Thanks! That was fast. Well done.

**Comment by josdejong** [comment]
Available now in v4.3.0.

**Comment by FabienFellay** [comment]
Thank you guys!
