### ISSUE TITLE
math.lusolve's docs are incorrect

### ISSUE THREAD

**Issue by jussch** [josdejong/mathjs#975]
http://mathjs.org/docs/reference/functions/lusolve.html has the example:

```
var a = [[-2, 3], [2, 1]];
var b = [11, 9];
var x = lusolve(a, b);  // [[-5.5], [20]]
```

but when I opened the console on the same page and typed:
```
var a = [[-2, 3], [2, 1]];
var b = [11, 9];
var x = math.lusolve(a, b);  // [[-5.5], [20]]
```

it found that `x === [[2],[5]]`.

**Comment by josdejong** [comment]
Thanks for reporting Justin! I've fixed it in the develop branch.
