### ISSUE TITLE
How to extend Node class with the new method?

### ISSUE THREAD

**Issue by metelkin** [josdejong/mathjs#977]
Hello!
I am writing the extension which transforms Node tree to another Node and must be imported from external file. My current version is something like this:

**main.js file**
```JavaScript
var math = require("mathjs");
math.import(require("./myMethod"));

var res0 = math.parse("x*y*sin(z)");
var res1 = math.myMethod(res0, someArg);
```

**myMethod file**
```JavaScript
exports.name = "myMethod";
exports.factory = function(type, config, load, typed){
  return function(node, someArg){
      ...
      return newNode;
  }
}
```
It works but I suppose to rewrite the code to use more convenient chaining call.
**main.js file**
```JavaScript
var math = require("mathjs");
math.import(require("./myMethod"));

var res0 = math
    .parse("x*y*sin(z)")
    .myMethod(someArg);
```
Node class is anavailable from `math` so I cannot use prototype. I cannot understand how to import another method to typed-functions in a legal way. Is it possible at all?

**Comment by josdejong** [comment]
You can find all `Node` classes under `math.expression.node` (i.e. `math.expression.node.Node`) and add methods to the prototype of the classes there. You should of course be careful with these things.

**Comment by metelkin** [comment]
Yes. it works.
Thank you!
