### ISSUE TITLE
How to get the mean/std of a matrix as vector?

### ISSUE THREAD

**Issue by rwieruch** [josdejong/mathjs#982]
The other day I was looking for a way to get the mean or std of a matrix not as a scalar but as a vector. The math.mean method over a matrix gives only a scalar. I implemented the [functionality on my own](https://github.com/javascript-machine-learning/mathjs-util/blob/master/src/index.js), but was curious if there is a more effective way to do it in math.js. 

```
const getMeanAsRowVector = (matrix) => {
  const n = getDimensionSize(matrix, 2);
  const vectors = Array(n).fill().map((_, i) => math.eval(`matrix[:, ${i + 1}]`, { matrix }));
  return vectors.reduce((result, vector) => result.concat(math.mean(vector)), []);
};

const getStdAsRowVector = (matrix) => {
  const n = getDimensionSize(matrix, 2);
  const vectors = Array(n).fill().map((_, i) => math.eval(`matrix[:, ${i + 1}]`, { matrix }));
  return vectors.reduce((result, vector) => result.concat(math.std(vector)), []);
};
```

On a side note, is there a shorter way in mathjs to push a vector in a matrix? In Octave / Matlab it is a one liner, but I couldn't find an efficient way to do it in math.js.

```
const pushVector = (matrix, index, vector) => {
  const extendedMatrix = math
    .ones([
      getDimensionSize(matrix, 1),
      getDimensionSize(matrix, 2) + 1
    ])
    .valueOf();

  return extendedMatrix.map((row, rowKey) => row.map((column, columnKey) => {
    if (index === columnKey) {
      return vector[rowKey][0];
    }
    if (columnKey < index) {
      return matrix[rowKey][columnKey];
    }
    if (columnKey > index) {
      return matrix[rowKey][columnKey - 1];
    }
  }));
};
```

Thanks for your help. Feel free to close the issue if it doesn't contribute to the library itself. Thanks for putting so much work into it!

**Comment by josdejong** [comment]
Thanks for your question!

Most statistics functions like `mean` allow passing over which dimension you want to get the mean ([see docs](http://mathjs.org/docs/reference/functions/mean.html)), like:

```js
const a = [[1,2,3], [4,5,6], [7,8,9]]
math.mean(a) // 5
math.mean(a, 1) // [4, 5, 6]
math.mean(a, 2) // [2, 5, 8]
```
I think that is what you mean?



This functionality is still missing for `std` though. Would be nice to add that. Would you be interested in extending the `std` function with support for dimension?

**Comment by rwieruch** [comment]
Thanks for your answer! That's great.

Yes, I will have a look today if it is feasible for me to cram it into my spare time. What about the side question: Pushing a vector in a matrix? I am coming from Octave here and there you can slot in vectors in matrices with a one liner.

**Comment by josdejong** [comment]
We still lack a handy way to glue matrices and vectors together, we had an idea to create sort of a `slice` function for matrices but I can't find it right now. 

There is the function `concat` to merge matrices together, is that what you mean? Something like:
```js
var A = [[1,2,3],[4,5,6],[7,8,9]] 
var v = [100, 100, 100]
var B = math.concat(A, math.transpose([v]))
// B = [
//   [1, 2, 3, 100]
//   [4, 5, 6, 100]
//   [7, 8, 9, 100]
// ]
var C = math.concat(A, [v], 0)
// C = [
//   [1, 2, 3]
//   [4, 5, 6]
//   [7, 8, 9]
//   [100, 100, 100]
// ]

**Comment by rwieruch** [comment]
Thank you @josdejong for all your help. I was able to refactor all my projects to use the concat and mean functions. Regarding the std function I opened up a [dedicated issue](https://github.com/josdejong/mathjs/issues/999). Perhaps it is a valuable first time contributor issue? Thank you again!

**Comment by josdejong** [comment]
:+1:
