### ISSUE TITLE
pickRandom inconsistent behavior: returns array if receives an array of length=1

### ISSUE THREAD

**Issue by moshetet** [josdejong/mathjs#983]
pickRandom([6,7]); //returns either 6 or 7
pickRandom([6]); //returns [6] instead of 6

Seen on Node 8.9.0

**Comment by HarrySarson** [comment]
See http://mathjs.org/docs/reference/functions/pickRandom.html

The return type of `math.pickRandom` is documented as `array` so either it  so the docs wrong.
I have found the offending code, will submit a pr.

**Comment by josdejong** [comment]
I think that the idea is that `pickRandom` returns a single value like `pickRandom([6,7])` does, unless you want it to return multiple values like `pickRandom([1,2,3,4], 2)`, in which case it returns an array with the number of values that you configured.

So I think:
- the documentation needs to be improved to clarify that
- `pickRandom([6])` returning `[6]` is a bug, should return `6` instead

**Comment by josdejong** [comment]
Should be fixed now in the develop branch.

**Comment by josdejong** [comment]
Should be fixed now in v3.18.0
