### ISSUE TITLE
Drop support for node.js 0.10 and 0.12?

### ISSUE THREAD

**Issue by josdejong** [josdejong/mathjs#987]
Currently we have integration tests running on node.js 0.10, 0.12, 4, 6, and 8. To keep stuff compatible with node.js 0.10 and 0.12, we can't update all dev dependencies (like mocha, webpack), which isn't a good thing. 

I think it is time to drop support for node.js 0.10 and 0.12. mathjs will likely keep working on these node.js versions, but it's impossible to keep the develop environment running on these ancient versions of node.js. Ideally, we should set up an integration environment where we test the production version of mathjs on the latest versions of all browsers and node.js. Anyone interested in looking into that? (we can probably use BrowserStack for free since mathjs is an open source project).

Does anyone have concerns/objections in dropping support for node.js 0.10 and 0.12?

**Comment by FSMaxB** [comment]
I think that existing stable and long term releases of GNU/Linux distribution should be kept in mind.

* Ubuntu 14.04 LTS (Supported until 2019): 0.10
* RHEL/CentOS: ?
* Debian oldstable: ?

Wether these old distributions are worth it is debatable.

**Comment by ericman314** [comment]
I'll look into BrowserStack.

**Comment by josdejong** [comment]
It's a bit of a search for me too what sort of setup we want, I think this will be the ingredients (just thinking aloud):

- A development environment with node.js + ES6 ( webpack, babel, ...), for local development and unit testing. This doesn't need to run on old versions of node.js.
- A production setup (build) which can be tested on different browsers, old browsers, and old and new versions of node.js. Should run automatically on an continuous integration environment (BrowerStack? Travis? CircleCI?). Compile all unit tests also to ES5 so we can run them on all browsers?

**Comment by ThomasBrierley** [comment]
>I think that existing stable and long term releases of GNU/Linux distribution should be kept in mind.
>[... ]
>Wether these old distributions are worth it is debatable.

I'd like to debate against their worth :P neither myself or any of my colleagues have been able to stick with the stock nodejs version on the various LTS apt repos, nodejs just moves too fast and they are way too old. There are too many new packages that don't work with these versions so I doubt there are many people who have been able to stick with 0.10 as their daily version for development... Ubuntu 16.04 has nodejs v4 LTS but even that is 2 LTS versions behind now (latest LTS is v8).

The most common way to install node is via an install script, for debian based linux this adds itself to the apt source lists. I expect the other scripts do something similar for other package managers.

**Comment by josdejong** [comment]
> I think it would be best to stick to nodejs LTS schedule

That makes sense indeed Thomas. Note that official support for v0.10 and v0.12 ended _a year ago_, not this month :)

I think it's a good time then to drop support for v0.10 and v0.12 from the development environment, it really starts to hurt. That does not mean that the bundled version of mathjs doesn't run there (it should). Separately, we need to set up an continuous integration environment where we test different browsers and node.js versions (including older browser versions), Eric made a start with that already (thanks).

**Comment by HarrySarson** [comment]
Currently mathjs is only being tested against node >= 4. Given that this is the case, it might be worth explicitly dropping support for older node version (adding `{ "engines" : { "node" : ">=4" } }` in package.json and maybe a note in the readme) to prevent users being caught out.

**Comment by josdejong** [comment]
Thanks @harrysarson , good point. I've fixed that in the develop branch

**Comment by harrysarson** [comment]
node 4 is now no longer supported. Should we be dropping support for it too?

**Comment by josdejong** [comment]
Yes makes sense, can you do that? 

We still have to set up CI for testing against all browsers too.

**Comment by harrysarson** [comment]
Yeah both dropping node 4 and getting browser tests are both very good ideas :)

**Comment by josdejong** [comment]
I've removed node 4 from the TravisCI configuration, and added node 10.

**Comment by josdejong** [comment]
I think we can close this issue :)
