### ISSUE TITLE
derivative fails if MathJS configured to use big number

### ISSUE THREAD

**Issue by ovk** [josdejong/mathjs#991]
Please see this example: https://jsfiddle.net/mc0fgvxt/
If MathJS is configured to use big number the `derivative` function always fails by throwing an exception:

`TypeError: Unsupported type of value "BigNumber"`

**Comment by josdejong** [comment]
Thanks for reporting, we should extend derivative and simplify such that they can deal with BigNumbers and Fractions too.

**Comment by josdejong** [comment]
This issue will be fixed in v4 (the first release candidate has been published today)

**Comment by josdejong** [comment]
This should be fixed now in v4
