### ISSUE TITLE
distance and intersect functions fail if MathJS configured to use big numbers

### ISSUE THREAD

**Issue by ovk** [josdejong/mathjs#992]
This similar to #991 but has to do with arrays. 
Please see this self-explanatory example for `distance` function: https://jsfiddle.net/c216nods/1/
The same applies for `intersect` function. Unless every numeric literal is casted to `number` they always fail.

**Comment by josdejong** [comment]
Thanks for reporting. The `distance` function currently doesn't support BigNumbers. It shouldn't be too hard to extend the function.

**Comment by josdejong** [comment]
Anyone interested in extending the `distance` function with support for BigNumbers and Fractions?

**Comment by ovk** [comment]
@josdejong what about `intersect` function? It looks very similar with `_2d`/`_3d` helpers checking for type to be `number`.

**Comment by josdejong** [comment]
You're right, same for `intersect`.

**Comment by ovk** [comment]
Ok I'll try to fix both, you can assign the issue to me.

**Comment by josdejong** [comment]
This issue was still open but is already resolved.
