### ISSUE TITLE
Ability to Integrate? 

### ISSUE THREAD

**Issue by jeffreyshen19** [josdejong/mathjs#993]
From what I can see, there doesn't seem to be an ability to integrate math functions. Is this a desired feature? If so, I can put in a pull request. 

Cheers,
Jeffrey

**Comment by josdejong** [comment]
Do you mean like building support for integration (opposite of differentiation)? Or do you mean importing new functions? For the latter case, there already is a function `import` available.

**Comment by jeffreyshen19** [comment]
I meant the former (opposite of differentiation).

**Comment by josdejong** [comment]
Having support for integration would indeed be great!

It's complicated to implement integration though. Do you have concrete plans how you would go ahead?

**Comment by jeffreyshen19** [comment]
I was thinking of implementing integration similar to how differentiation is done (manually inputing integration rules).

**Comment by ericman314** [comment]
Integration is a completely different problem than differentiation. In
terms of difficulty, differentiation is like computing a hash, and
integration is like reversing it. But it's definitely on our wish list, so
we can use all the help we can get.

**Comment by jeffreyshen19** [comment]
Agreed. However, many common functions can be integrated using simple integration rules + reverse chain rule. This, unfortunately, is not general and can not be applied to every function. Another possibility is to have a function which calculates the numeric value of an integral using a Riemannian approximation.

Thoughts?

**Comment by josdejong** [comment]
A numeric integration (and differentiation) function would be interesting too, that's not that hard to implement. It's completely different from symbolic computations though :)

**Comment by bjodah** [comment]
FWIW: As far as I know the best CAS implementation of integration is [RUBI](http://www.apmaths.uwo.ca/~arich/). There was a Google summer of code project last year in the sympy organization which aimed to port these rules into SymPy. They didn't quite finish, but once (if) that ends up wokring, then it shouldn't be too hard writing another export function for mathjs (since the approach they ended up taking was *generating* Python code).

**Comment by ericman314** [comment]
Fascinating idea, @bjodah. I think it's worth a look.

**Comment by bjodah** [comment]
If you are interested in the status of that effort I would recommend reading up/reaching out on SymPy's mailing list: https://groups.google.com/forum/m/#!searchin/sympy/rubi

**Comment by josdejong** [comment]
@joelhoover what you you think about that? (See #1015)

**Comment by Schnark** [comment]
BTW: _Numeric_ integration is actually one of the examples in the documentation: http://mathjs.org/examples/advanced/custom_argument_parsing.js.html

**Comment by m93a** [comment]
Let's continue the discussion in #1015
